"use client";
import {ShieldCheck,PackageOpen,ShieldAlert,ScanLine,Info,ArrowUpRight} from 'lucide-react';
import {useProductNotices} from '../../lib/product-notice-resource';
import {publicNoticeSignal,evidenceCarrier} from '../../lib/passport-evidence-summary';
import {useSunLocale} from './sun-locale-provider';
import styles from './passport-essential-signals.module.css';
const copy={
 'es-AR':{group:'Tres datos diferentes de tu producto',identity:'Etiqueta',seal:'Precinto',product:'Producto',not_checked:'Sin consulta real',checking:'Consultando avisos',unknown:'Avisos sin confirmar',warning:'Aviso vigente',stale_warning:'Aviso · actualizar',lifted:'Aviso levantado',none:'Sin avisos publicados',more:'Más avisos por revisar',demo:'Ejemplo ilustrativo',demoCarrier:'Etiqueta de muestra',past:'Registro histórico',current:'Resultado de esta lectura',details:'Qué demuestra cada tecnología',secure_nfc:'NFC seguro',tagtamper:'NFC con TagTamper',qr:'Código QR',gs1:'GS1 Digital Link',basic_nfc:'NFC informativo',uhf:'UHF / RFID logístico',unknownCarrier:'Tecnología no informada',static:'Este enlace identifica información. No autentica el chip, el precinto ni la posesión del producto.',crypto:'La verificación del chip, el estado del precinto y los avisos comerciales son controles separados.',uhfCopy:'Una lectura UHF corresponde al lector logístico y su registro. No equivale a una verificación SUN del celular.',demoCopy:'Simulación: no genera evidencia física ni consulta avisos productivos.',noticeHelp:'Abrir avisos actuales del producto',inapplicable:'No evaluado',notverified:'Sin autenticación NFC'},
 en:{group:'Three different product checks',identity:'Tag',seal:'Seal',product:'Product',not_checked:'Not checked',checking:'Checking notices',unknown:'Notices unconfirmed',warning:'Active notice',stale_warning:'Notice · refresh',lifted:'Notice lifted',none:'No published notices',more:'More notices to check',demo:'Illustrative example',demoCarrier:'Sample tag',past:'Historical record',current:'This reading',details:'What each technology proves',secure_nfc:'Secure NFC',tagtamper:'NFC with TagTamper',qr:'QR code',gs1:'GS1 Digital Link',basic_nfc:'Informational NFC',uhf:'Logistics UHF / RFID',unknownCarrier:'Technology unreported',static:'This link identifies information. It does not authenticate the chip, seal or product possession.',crypto:'Chip authentication, seal state and commercial notices are separate checks.',uhfCopy:'UHF evidence comes from a logistics reader and its record, not a phone SUN verification.',demoCopy:'Simulation: no physical evidence or production notice query.',noticeHelp:'Open current product notices',inapplicable:'Not assessed',notverified:'No NFC authentication'},
 'pt-BR':{group:'Três verificações diferentes do produto',identity:'Etiqueta',seal:'Lacre',product:'Produto',not_checked:'Sem consulta real',checking:'Consultando avisos',unknown:'Avisos não confirmados',warning:'Aviso vigente',stale_warning:'Aviso · atualizar',lifted:'Aviso levantado',none:'Sem avisos publicados',more:'Mais avisos a revisar',demo:'Exemplo ilustrativo',demoCarrier:'Etiqueta de exemplo',past:'Registro histórico',current:'Resultado desta leitura',details:'O que cada tecnologia comprova',secure_nfc:'NFC seguro',tagtamper:'NFC com TagTamper',qr:'Código QR',gs1:'GS1 Digital Link',basic_nfc:'NFC informativo',uhf:'UHF / RFID logístico',unknownCarrier:'Tecnologia não informada',static:'O link identifica informações. Não autentica chip, lacre ou posse do produto.',crypto:'Autenticidade do chip, estado do lacre e avisos comerciais são verificações distintas.',uhfCopy:'A leitura UHF vem do leitor logístico e seu registro, não da verificação SUN no celular.',demoCopy:'Simulação: sem evidência física ou consulta de avisos produtivos.',noticeHelp:'Abrir avisos atuais do produto',inapplicable:'Não avaliado',notverified:'Sem autenticação NFC'}
} as const;
export function PassportEssentialSignals({identityLabel,sealLabel,tone,carrierCode,isQr,isDemo,isHistorical}:{identityLabel:string;sealLabel:string;tone:string;carrierCode:string;isQr:boolean;isDemo:boolean;isHistorical:boolean}){
 const {locale,text}=useSunLocale(),c=copy[locale],resource=useProductNotices(),signal=publicNoticeSignal(resource),carrier=evidenceCarrier(carrierCode,isQr);
 const informationOnly=['qr','gs1','basic_nfc','uhf'].includes(carrier);
 const observedIdentity=informationOnly&&!isDemo?c.notverified:text(identityLabel),observedSeal=informationOnly&&!isDemo?c.inapplicable:text(sealLabel);
 return <section className={styles.root} aria-label={c.group} data-testid="passport-essential-signals" data-sun-server-evidence="true">
  <div className={styles.context}><ScanLine size={13} aria-hidden="true"/><span>{isDemo?c.demo:isHistorical?c.past:c.current}</span><strong>{carrier==='unknown'?(isDemo?c.demoCarrier:c.unknownCarrier):c[carrier]}</strong></div>
  <dl className={styles.signals} data-testid="sun-summary-facts"><div data-tone={informationOnly?'info':tone}><dt><ShieldCheck size={16} aria-hidden="true"/>{c.identity}</dt><dd>{observedIdentity}</dd></div><div data-tone={informationOnly?'info':tone}><dt><PackageOpen size={16} aria-hidden="true"/>{c.seal}</dt><dd>{observedSeal}</dd></div><div data-tone={['warning','stale_warning','more'].includes(signal)?'risk':'info'}><dt><ShieldAlert size={16} aria-hidden="true"/>{c.product}</dt><dd>{!isDemo&&resource?.enabled?<a href="#product-notices" aria-label={c.noticeHelp}>{c[signal]}<ArrowUpRight size={13} aria-hidden="true"/></a>:c.not_checked}</dd></div></dl>
  <details className={styles.details}><summary><Info size={14} aria-hidden="true"/>{c.details}</summary><p>{isDemo?c.demoCopy:carrier==='uhf'?c.uhfCopy:informationOnly?c.static:c.crypto}</p></details>
 </section>;
}
