export const reportProblemCopy = {
  "es-AR": {
    title: "Reportar un problema", intro: "Contanos qué pasó con este producto o esta lectura. Antes de enviar, podrás revisar el reporte.",
    demo: "Esta ficha es de muestra. No permite enviar reportes de un producto real.",
    unavailable: "No hay un acceso válido para reportar esta lectura. Volvé a abrir el pasaporte del producto para intentarlo.",
    category: "¿Qué querés reportar?", categories: { tap_review: "Problema con la lectura", seal_opened: "Sello abierto o dañado", product_problem: "Problema con el producto", other: "Otro motivo" },
    description: "Describí lo que pasó", descriptionHelp: "Incluí los detalles que ayuden a revisar el caso. Máximo 1500 caracteres.",
    contact: "Contacto (opcional)", contactHelp: "Podés dejar un correo o teléfono. Máximo 320 caracteres.",
    privacy: "Al confirmar, se enviarán el detalle, el contacto que decidas incluir y la referencia del producto y de la lectura para que la empresa vinculada pueda revisarlos. No se solicita tu ubicación. No incluyas contraseñas, datos de pago ni información sensible.",
    review: "Revisar reporte", reviewTitle: "Revisá antes de enviar", product: "Producto", batch: "Lote", reading: "Lectura", noContact: "Sin contacto", unknownProduct: "Producto de esta lectura",
    confirm: "Confirmar reporte", sending: "Enviando reporte…", edit: "Editar detalles", retry: "Reintentar el mismo reporte", reviewAgain: "Revisar un nuevo envío",
    received: "Reporte recibido", existing: "Reporte ya registrado", reference: "Referencia del reporte", createdAt: "Fecha de registro",
    open: "Pendiente de revisión", pending: "Estado: pendiente", closed: "Estado: cerrado",
    receivedHelp: "El reporte quedó registrado para la empresa vinculada al producto. No confirma que una persona lo haya revisado ni garantiza una respuesta o contacto.",
    earlierUncertain: "Un envío anterior pudo haberse registrado. Todavía no podemos confirmar si existe un ticket para ese intento.",
    errors: { required: "Completá la descripción.", tooLongDescription: "Usá hasta 1500 caracteres.", tooLongContact: "Usá hasta 320 caracteres.", invalid: "Revisá este dato antes de continuar.",
      expired: "El acceso para reportar venció o no pudo validarse. El texto sigue en esta pantalla: copialo antes de volver a abrir el pasaporte.",
      rate_limited: "Hay demasiados intentos. Esperá unos minutos y reintentá este mismo reporte.",
      unavailable: "El servicio no está disponible. Tus datos se conservan; reintentá este mismo reporte.",
      conflict: "Este envío no coincide con un intento anterior. Revisá los detalles antes de confirmar un nuevo envío.",
      uncertain: "No pudimos confirmar la recepción. Reintentá el mismo reporte para consultar o completar ese envío, sin cambiar sus datos.",
      context_unavailable: "El acceso no corresponde a esta lectura. Este intento no se envió.",
      resolve_attempt: "Primero resolvé el envío pendiente reintentando el mismo reporte.",
      request_id_unavailable: "No pudimos preparar el envío en este navegador. Los datos se conservan.",
      invalid_response: "La solicitud no fue aceptada. Revisá los detalles antes de volver a confirmar.",
    },
  },
  en: {
    title: "Report a problem", intro: "Tell us what happened with this product or reading. You can review the report before sending it.",
    demo: "This is a sample passport. It cannot submit reports about a real product.",
    unavailable: "There is no valid access to report this reading. Reopen the product passport to try again.",
    category: "What would you like to report?", categories: { tap_review: "Reading problem", seal_opened: "Open or damaged seal", product_problem: "Product problem", other: "Other reason" },
    description: "Describe what happened", descriptionHelp: "Include details that can help review the case. Maximum 1500 characters.",
    contact: "Contact (optional)", contactHelp: "You may leave an email address or phone number. Maximum 320 characters.",
    privacy: "When you confirm, the details, any contact information you choose to include, and the product and reading references will be sent for review by the company linked to the product. Your location is not requested. Do not include passwords, payment details or sensitive information.",
    review: "Review report", reviewTitle: "Review before sending", product: "Product", batch: "Batch", reading: "Reading", noContact: "No contact provided", unknownProduct: "Product from this reading",
    confirm: "Confirm report", sending: "Sending report…", edit: "Edit details", retry: "Retry the same report", reviewAgain: "Review a new submission",
    received: "Report received", existing: "Report already recorded", reference: "Report reference", createdAt: "Recorded at",
    open: "Awaiting review", pending: "Status: pending", closed: "Status: closed",
    receivedHelp: "The report was recorded for the company linked to the product. This does not confirm that a person has reviewed it or guarantee a reply or contact.",
    earlierUncertain: "An earlier submission may have been recorded. We still cannot confirm whether a ticket exists for that attempt.",
    errors: { required: "Enter a description.", tooLongDescription: "Use up to 1500 characters.", tooLongContact: "Use up to 320 characters.", invalid: "Check this field before continuing.",
      expired: "Reporting access expired or could not be validated. Your text remains on this screen: copy it before reopening the passport.",
      rate_limited: "Too many attempts. Wait a few minutes and retry the same report.",
      unavailable: "The service is unavailable. Your details are kept; retry the same report.",
      conflict: "This submission does not match an earlier attempt. Review the details before confirming a new submission.",
      uncertain: "We could not confirm receipt. Retry the same report to check or complete that submission without changing its details.",
      context_unavailable: "Access does not match this reading. This attempt was not sent.",
      resolve_attempt: "First resolve the pending submission by retrying the same report.",
      request_id_unavailable: "We could not prepare the submission in this browser. Your details are kept.",
      invalid_response: "The request was not accepted. Review the details before confirming again.",
    },
  },
  "pt-BR": {
    title: "Relatar um problema", intro: "Conte o que aconteceu com este produto ou esta leitura. Você poderá revisar o relato antes de enviá-lo.",
    demo: "Esta ficha é uma demonstração. Não permite enviar relatos sobre um produto real.",
    unavailable: "Não há acesso válido para relatar esta leitura. Abra novamente o passaporte do produto para tentar outra vez.",
    category: "O que você quer relatar?", categories: { tap_review: "Problema com a leitura", seal_opened: "Lacre aberto ou danificado", product_problem: "Problema com o produto", other: "Outro motivo" },
    description: "Descreva o que aconteceu", descriptionHelp: "Inclua detalhes que ajudem a analisar o caso. Máximo de 1500 caracteres.",
    contact: "Contato (opcional)", contactHelp: "Você pode informar um e-mail ou telefone. Máximo de 320 caracteres.",
    privacy: "Ao confirmar, serão enviados os detalhes, o contato que você optar por incluir e as referências do produto e da leitura, para análise pela empresa vinculada ao produto. Sua localização não é solicitada. Não inclua senhas, dados de pagamento nem informações sensíveis.",
    review: "Revisar relato", reviewTitle: "Revise antes de enviar", product: "Produto", batch: "Lote", reading: "Leitura", noContact: "Sem contato", unknownProduct: "Produto desta leitura",
    confirm: "Confirmar relato", sending: "Enviando relato…", edit: "Editar detalhes", retry: "Tentar o mesmo relato novamente", reviewAgain: "Revisar um novo envio",
    received: "Relato recebido", existing: "Relato já registrado", reference: "Referência do relato", createdAt: "Data do registro",
    open: "Aguardando análise", pending: "Estado: pendente", closed: "Estado: encerrado",
    receivedHelp: "O relato foi registrado para a empresa vinculada ao produto. Isso não confirma a análise por uma pessoa nem garante resposta ou contato.",
    earlierUncertain: "Um envio anterior pode ter sido registrado. Ainda não podemos confirmar se existe um chamado para aquela tentativa.",
    errors: { required: "Preencha a descrição.", tooLongDescription: "Use até 1500 caracteres.", tooLongContact: "Use até 320 caracteres.", invalid: "Revise este dado antes de continuar.",
      expired: "O acesso para relatar expirou ou não pôde ser validado. O texto continua nesta tela: copie-o antes de reabrir o passaporte.",
      rate_limited: "Muitas tentativas. Aguarde alguns minutos e tente o mesmo relato novamente.",
      unavailable: "O serviço está indisponível. Seus dados foram mantidos; tente o mesmo relato novamente.",
      conflict: "Este envio não corresponde a uma tentativa anterior. Revise os detalhes antes de confirmar um novo envio.",
      uncertain: "Não foi possível confirmar o recebimento. Tente o mesmo relato novamente para consultar ou concluir o envio, sem alterar seus dados.",
      context_unavailable: "O acesso não corresponde a esta leitura. Esta tentativa não foi enviada.",
      resolve_attempt: "Primeiro resolva o envio pendente tentando o mesmo relato novamente.",
      request_id_unavailable: "Não foi possível preparar o envio neste navegador. Seus dados foram mantidos.",
      invalid_response: "A solicitação não foi aceita. Revise os detalhes antes de confirmar novamente.",
    },
  },
} as const;
