"use client";
import { useEffect, useRef, useState } from "react";
import { LocateFixed, CheckCircle2, ChevronDown, MapPin } from "lucide-react";
import { SunLocationRequestButton, useSunLocationController } from "./sun-location-controller";
import { useSunLocale } from "./sun-locale-provider";
import styles from "./sun-location-quick-action.module.css";
const COPY = {
  "es-AR": {title:"Ubicación del TAP",body:"Opcional · compartí una zona aproximada.",area:"Zona aproximada del teléfono",source:"Fuente: teléfono · zona aproximada con permiso",map:"Ver zona en el mapa",cta:"Compartir ubicación",later:"Ahora no",optional:"Opcional · el producto sigue disponible sin permiso",saved:"Zona del teléfono guardada",savedBody:"Se actualizó esta lectura; no se registró otro TAP.",details:"Qué se comparte",privacy:"Una zona aproximada, no seguimiento continuo. La posición se mide después del TAP y solo se confirma al recibir el comprobante del servidor.",network:"Sin compartir ubicación, la zona puede estimarse por red/IP cuando esté disponible; puede indicar otra ciudad.",retry:"Reintentar",retryable:"La zona no se guardó esta vez. Podés volver a intentar; el pasaporte sigue disponible.",denied:"El navegador no permitió la ubicación. Podés habilitarla desde los permisos del sitio; el pasaporte sigue disponible.",timeout:"El teléfono no obtuvo ubicación a tiempo. Acercate a una zona con mejor señal y reintentá.",failed:"No se obtuvo una ubicación utilizable. Podés reintentar o continuar sin compartirla.",uncertain:"No se pudo confirmar el guardado. La zona no se muestra como guardada. Hacé un nuevo TAP físico para compartirla con certeza.",fresh:"Esta lectura ya no permite una nueva ubicación. Acercá otra vez el teléfono a la etiqueta.",unsupported:"Este navegador no admite ubicación. Abrí el pasaporte en un navegador compatible.",ready:"Preparando la lectura…",requesting:"Si aparece el permiso del navegador, elegí si querés compartir tu zona. El pasaporte sigue disponible.",measuring:"El permiso está habilitado. El teléfono está obteniendo una zona aproximada; todavía no se guardó.",saving:"La zona se está enviando. Esperamos el comprobante del servidor antes de mostrarla como guardada."},
  en:{title:"Tap location",body:"Optional · share your approximate area.",area:"Approximate phone area",source:"Source: phone · approximate area shared with permission",map:"View area on the map",cta:"Share location",later:"Not now",optional:"Optional · the product remains available without permission",saved:"Phone area saved",savedBody:"This reading was updated; no new tap was created.",details:"What is shared",privacy:"An approximate area, not continuous tracking. It is measured after the tap and confirmed only by the server receipt.",network:"Without sharing location, an area may be estimated from network/IP when available; it may point to another city.",retry:"Try again",retryable:"The area was not saved this time. You can try again; the passport remains available.",denied:"Location permission was denied. You can change the site's permissions; the passport stays available.",timeout:"The phone did not obtain a location in time. Try again with a better signal.",failed:"No usable location was obtained. Try again or continue without sharing.",uncertain:"Saving could not be confirmed. This area is not shown as saved. Make a new physical tap to share it with certainty.",fresh:"A new tap is needed to share another location.",unsupported:"Location is unavailable in this browser.",ready:"Preparing this reading…",requesting:"If the browser asks for permission, choose whether to share your area. The passport remains available.",measuring:"Permission is enabled. The phone is obtaining an approximate area; it has not been saved yet.",saving:"The area is being sent. We are waiting for the server receipt before showing it as saved."},
  "pt-BR":{title:"Localização do TAP",body:"Opcional · compartilhe uma área aproximada.",area:"Área aproximada do telefone",source:"Fonte: telefone · área aproximada com permissão",map:"Ver área no mapa",cta:"Compartilhar localização",later:"Agora não",optional:"Opcional · o produto permanece disponível sem permissão",saved:"Área do telefone salva",savedBody:"Esta leitura foi atualizada; nenhum novo TAP foi criado.",details:"O que é compartilhado",privacy:"Uma área aproximada, não rastreamento contínuo. É medida após o TAP e confirmada pelo comprovante do servidor.",network:"Sem compartilhar localização, a área pode ser estimada pela rede/IP quando disponível; pode indicar outra cidade.",retry:"Tentar novamente",retryable:"A área não foi salva desta vez. Você pode tentar novamente; o passaporte continua disponível.",denied:"O navegador negou a localização. Você pode ajustar as permissões do site; o passaporte continua disponível.",timeout:"O telefone não obteve a localização a tempo. Tente novamente com melhor sinal.",failed:"Não foi possível obter uma localização utilizável. Tente novamente ou continue sem compartilhar.",uncertain:"Não foi possível confirmar o salvamento. A área não é exibida como salva. Faça um novo TAP físico para compartilhá-la com certeza.",fresh:"Faça um novo TAP para compartilhar outra localização.",unsupported:"Este navegador não oferece localização.",ready:"Preparando esta leitura…",requesting:"Se o navegador pedir permissão, escolha se deseja compartilhar sua área. O passaporte continua disponível.",measuring:"A permissão está habilitada. O telefone está obtendo uma área aproximada; ela ainda não foi salva.",saving:"A área está sendo enviada. Aguardamos o comprovante do servidor antes de exibi-la como salva."},
} as const;
export function SunLocationQuickAction() {
  const control=useSunLocationController(); const {locale}=useSunLocale();
  const copy=COPY[locale==="en"||locale==="pt-BR"?locale:"es-AR"];
  const initiatedHere=useRef(false); const savedRef=useRef<HTMLElement>(null);
  const [dismissed,setDismissed]=useState(false);
  const state=control?.state || "idle";
  const busy=state==="requesting"||state==="measuring"||state==="saving";
  const phase=state==="requesting"?copy.requesting:state==="measuring"?copy.measuring:state==="saving"?copy.saving:"";
  const status=state==="denied"?copy.denied:state==="timeout"?copy.timeout:state==="retryable"?copy.retryable:state==="uncertain"?copy.uncertain:state==="fresh_tap_required"?copy.fresh:state==="unsupported"?copy.unsupported:["invalid","stale","unavailable"].includes(state)?copy.failed:"";
  const actionLabel=["denied","timeout","invalid","stale","unavailable","retryable"].includes(state)?copy.retry:copy.cta;
  useEffect(()=>{if(state==="updated" && initiatedHere.current)savedRef.current?.focus({preventScroll:true});},[state]);
  if(state==="updated" && control?.receipt) {
    const area=[control.receipt.city,control.receipt.countryCode].filter(Boolean).join(", ");
    return <section ref={savedRef} tabIndex={-1} className={`${styles.card} ${styles.success}`} id="share-phone-location" data-testid="sun-location-quick-action" data-state={state} data-location-receipt="saved" aria-live="polite">
      <div className={styles.heading}><CheckCircle2 size={22} aria-hidden="true"/><div><strong>{copy.saved}</strong><p>{copy.source}</p></div></div>
      <strong className={styles.area} data-testid="sun-location-quick-confirmed" data-sun-server-evidence={area ? "true" : undefined}>{area || copy.area}</strong>
      <p className={styles.savedBody}>{copy.savedBody}</p>
      <a className={styles.mapLink} href="#geo-trace"><MapPin size={18} aria-hidden="true"/>{copy.map}</a>
    </section>;
  }
  return <section onClickCapture={event=>{if(event.target instanceof Element && event.target.closest('[data-testid="sun-location-consent-cta"]'))initiatedHere.current=true;}} className={styles.card} id="share-phone-location" data-testid="sun-location-quick-action" data-state={state}>
    <div className={styles.heading}><LocateFixed size={22} aria-hidden="true"/><div><h2>{copy.title}</h2>{!dismissed && <p>{copy.body}</p>}</div></div>
    {dismissed ? <button type="button" className={styles.reopen} onClick={()=>setDismissed(false)}>{copy.cta}<ChevronDown size={16}/></button> : <>
      <div className={styles.actions}><SunLocationRequestButton className={styles.primary}><LocateFixed size={19} aria-hidden="true"/><span>{actionLabel}</span></SunLocationRequestButton><button type="button" className={styles.secondary} disabled={busy} onClick={()=>setDismissed(true)}>{copy.later}</button></div>
      {!control?.ready && <p className={styles.optional}>{copy.ready}</p>}
      {phase && <p className={`${styles.feedback} ${styles.phase}`} data-testid="sun-location-phase" role="status">{phase}</p>}
      {status && <p className={styles.feedback} role="status">{status}</p>}
      <details className={styles.details}><summary>{copy.details}<ChevronDown size={16} aria-hidden="true"/></summary><p>{copy.optional}</p><p>{copy.privacy}</p><p>{copy.network}</p></details>
    </>}
  </section>;
}
