import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';
import {channelProjection,gs1Path,channelFailure} from '../src/lib/batch-channel-service.ts';
const row={id:'batch',bid:'QA',tenant_slug:'tenant-qa',status:'active',tenant_status:'active',policy_enabled:true,product_name:'QA',carrier:'qr_basic',catalog_code:'qr_basic'};
test('QR uses only the registered carrier and authorized public scope',()=>{const v=channelProjection(row);const u=new URL(v.publicUrl);assert.equal(u.searchParams.get('bid'),'QA');assert.equal(u.searchParams.get('carrier'),'qr_basic');assert.equal(v.carrier.cryptographic,false);});
test('TT retains configured bytes but never creates a static SUN QR',()=>{const cfg={...row,carrier:'ntag424_dna_tt',catalog_code:'ntag424_dna_tt',tt_enabled:true,tt_source:'enc_decrypted',tt_length:2,tt_closed:['4343'],tt_opened:['4F4F','4F43'],tt_invalid:['4949']};const before=structuredClone(cfg),r=channelProjection(cfg);assert.equal(r.publicUrl,null);assert.equal(r.carrier.tamper,true);assert.deepEqual(r.tt.opened,['4F4F','4F43']);assert.equal(r.tt.physicalState,'NOT_READ_BY_CONFIGURATION');assert.deepEqual(cfg,before);});
test('non-TT NFC and unconfigured carriers never inherit TT evidence',()=>{for(const c of ['ntag424_dna','ntag213','unknown']){const r=channelProjection({...row,carrier:c,catalog_code:c});assert.equal(r.tt,null);assert.equal(r.publicUrl,null);}});
test('disabled policy and inactive batch withhold QR even when URL can be formed',()=>{for(const patch of [{policy_enabled:false},{status:'inactive'},{tenant_status:'blocked'},{catalog_code:null}])assert.equal(channelProjection({...row,...patch}).publicUrl,null);});
test('GS1 syntax validates check digit and preserves lot and serial hierarchy',()=>{assert.equal(gs1Path({gtin:'09506000134352',lot:'L-1',serial:'S1'}),'/01/09506000134352/10/L-1/21/S1');assert.throws(()=>gs1Path({gtin:'09506000134353'}));assert.throws(()=>gs1Path({gtin:'09506000134352',lot:'A/B'}));});
test('errors do not expose database internals',()=>{assert.deepEqual(channelFailure(new Error('db password confidential')),{reason:'channel_source_unavailable',status:503});});
test('write service accepts only commercial identity fields and uses existing durable registry',async()=>{const s=await readFile(new URL('../src/lib/batch-channel-service.ts',import.meta.url),'utf8');assert.match(s,/registerGs1Identity/);assert.match(s,/channel_profile_mismatch/);assert.match(s,/channel_field_not_allowed/);assert.doesNotMatch(s,/UPDATE batches|UPDATE tags|clear_attendance|reset_counter|meta_key_ct|file_key_ct/);});

import {canRepairRegisteredTagTamper} from '../src/lib/ttstatus-repair-policy.ts';
test('TT repair never converts QR, GS1, plain NFC or unknown hardware into TagTamper',()=>{for(const c of ['qr_basic','gs1_digital_link','ntag424_dna','ntag213',''])assert.equal(canRepairRegisteredTagTamper(c,{}),false);assert.equal(canRepairRegisteredTagTamper('ntag424_dna_tt',{}),true);assert.equal(canRepairRegisteredTagTamper('ntag424_dna_tt',{carrier_profile_code:'qr_basic'}),false);});
test('repair checks registered hardware before building or writing new TT configuration',async()=>{const s=await readFile(new URL('../src/app/admin/batches/[bid]/ttstatus-config/route.ts',import.meta.url),'utf8');assert.ok(s.indexOf('ttstatus_repair_requires_registered_tagtamper')<s.indexOf('const nextConfig'));});
