import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const migration = await readFile(
  new URL("../db/migrations/20260906120000_0102_campaign_drafts.sql", import.meta.url),
  "utf8",
);
const sql = migration.replace(/--[^\n]*/g, "").replace(/\s+/g, " ").trim();

test("campaign draft identity is generated by the database and bound to an existing tenant", () => {
  assert.match(sql, /CREATE TABLE public\.campaign_drafts \(/);
  assert.match(sql, /id uuid PRIMARY KEY DEFAULT gen_random_uuid\(\)/);
  assert.match(sql, /tenant_id uuid NOT NULL REFERENCES public\.tenants\(id\) ON DELETE RESTRICT/);
  assert.doesNotMatch(sql, /tenant_id[^,]*(?:DEFAULT|ON DELETE CASCADE|ON DELETE SET NULL)/);
});

test("draft content requires bounded nonblank title, message and actor labels", () => {
  for (const [field, maximum] of [
    ["title", 160],
    ["message", 6000],
    ["created_by_label", 160],
    ["updated_by_label", 160],
  ]) {
    assert.match(sql, new RegExp(`${field} text NOT NULL CONSTRAINT campaign_drafts_${field}_check CHECK \\(char_length\\(btrim\\(${field}\\)\\) BETWEEN 1 AND ${maximum}\\)`));
  }
});

test("campaign drafts accept only the declared channel, purpose and lifecycle vocabulary", () => {
  assert.match(sql, /channel text NOT NULL CONSTRAINT campaign_drafts_channel_check CHECK \(channel IN \('whatsapp', 'email', 'phone'\)\)/);
  assert.match(sql, /purpose text NOT NULL DEFAULT 'marketing' CONSTRAINT campaign_drafts_purpose_check CHECK \(purpose = 'marketing'\)/);
  assert.match(sql, /status text NOT NULL DEFAULT 'draft' CONSTRAINT campaign_drafts_status_check CHECK \(status IN \('draft', 'archived'\)\)/);
  assert.doesNotMatch(sql, /'scheduled'|'sending'|'sent'|'published'|'transactional'/);
});

test("draft revisions start at one and timestamps are database assigned", () => {
  assert.match(sql, /revision integer NOT NULL DEFAULT 1 CONSTRAINT campaign_drafts_revision_check CHECK \(revision > 0\)/);
  assert.match(sql, /created_at timestamptz NOT NULL DEFAULT now\(\)/);
  assert.match(sql, /updated_at timestamptz NOT NULL DEFAULT now\(\)/);
});

test("both draft authors reference durable internal users without cascading deletion", () => {
  for (const field of ["created_by", "updated_by"]) {
    assert.match(sql, new RegExp(`${field} uuid NOT NULL REFERENCES public\\.users\\(id\\) ON DELETE RESTRICT`));
  }
  assert.doesNotMatch(sql, /ON DELETE (?:CASCADE|SET NULL)/);
});

test("create idempotency is bounded, fingerprinted and unique inside each tenant", () => {
  assert.ok(sql.includes("create_idempotency_key text NOT NULL CONSTRAINT campaign_drafts_create_idempotency_key_check CHECK (create_idempotency_key ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$')"));
  assert.ok(sql.includes("create_fingerprint text NOT NULL CONSTRAINT campaign_drafts_create_fingerprint_check CHECK (create_fingerprint ~ '^[0-9a-f]{64}$')"));
  assert.match(sql, /CONSTRAINT uq_campaign_drafts_tenant_create_idempotency UNIQUE \(tenant_id, create_idempotency_key\)/);
  assert.doesNotMatch(sql, /UNIQUE \(create_idempotency_key\)/);
});

test("draft listing index supports tenant, status and stable descending pagination", () => {
  assert.match(sql, /CREATE INDEX idx_campaign_drafts_tenant_status_updated ON public\.campaign_drafts \(tenant_id, status, updated_at DESC, id DESC\)/);
});

test("0102 only introduces its table and index under the migration runner transaction", () => {
  assert.equal(sql.split(";").filter((statement) => statement.trim()).length, 2);
  assert.doesNotMatch(sql, /\b(?:BEGIN|START TRANSACTION|COMMIT|ROLLBACK|GRANT|REVOKE|TRIGGER|FUNCTION|INSERT INTO|UPDATE|DELETE FROM|DROP|ALTER TABLE)\b/i);
  assert.doesNotMatch(sql, /schema_migrations|CREATE EXTENSION|SECURITY DEFINER|CREATE POLICY/i);
});
