import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {queueFilters,queueNextStep,queueScopeDigest,readQueueCursor,queueCursor,queueActorId} from '../src/lib/editorial-queue-policy.ts';
const actor={id:'qa_user',edit:true,review:true,publish:true},filters={state:'',view:'all',q:''};
test('review involvement blocks self-approval even with all editorial permissions',()=>{assert.deepEqual(queueNextStep('in_review',true,actor),{code:'needs_independent_review',forActor:false});assert.equal(queueNextStep('in_review',false,actor).code,'review');});
test('each saved state names its next role without autoassigning or authorizing writes',()=>{const reader={...actor,edit:false,review:false,publish:false};assert.equal(queueNextStep('draft',false,reader).code,'needs_editor');assert.equal(queueNextStep('changes_requested',false,actor).code,'edit');assert.equal(queueNextStep('approved',false,reader).code,'needs_publisher');assert.equal(queueNextStep('published',false,actor).forActor,false);});
test('only allowlisted bounded filters are accepted',()=>{assert.deepEqual(queueFilters(new URLSearchParams('q= test &view=mine')),{state:'',view:'mine',q:'test'});for(const q of ['state=fake','view=everyone','actorId=admin','q=a&q=b','q='+ 'x'.repeat(101)])assert.throws(()=>queueFilters(new URLSearchParams(q)));});
test('queue position is scoped to query actor and current capabilities',()=>{const scope=queueScopeDigest('tenant',filters,actor),c={v:1,scope,lastAt:'2026-09-19T12:00:00.123456Z',lastId:'10000000-0000-4000-8000-000000000001',page:2};assert.deepEqual(readQueueCursor(queueCursor(c),scope),c);assert.throws(()=>readQueueCursor(queueCursor(c),queueScopeDigest('other',filters,actor)));assert.throws(()=>readQueueCursor(queueCursor(c),queueScopeDigest('tenant',filters,{...actor,review:false})));assert.throws(()=>readQueueCursor('!',scope));});
test('actor IDs are persisted identifiers rather than arbitrary email or browser claims',()=>{assert.equal(queueActorId('QA_actor'),'QA_actor');assert.throws(()=>queueActorId('someone@example.invalid'));assert.throws(()=>queueActorId(''));});
test('single queue statement projects metadata and does not load raw technical keys or mutate records',async()=>{const s=await readFile(new URL('../src/lib/editorial-queue-service.ts',import.meta.url),'utf8');assert.equal((s.match(/await sql`/g)||[]).length,1);assert.doesNotMatch(s,/INSERT INTO|UPDATE |DELETE FROM|sdm_config|seed_config/);assert.match(s,/LIMIT 26/);assert.match(s,/h.tenant_id=c.tenant_id/);assert.match(s,/last.action==='request_changes'/);});
