import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {intakeCapabilities,intakeDocument,intakeReference,digest} from '../src/lib/epcis-intake-policy.ts';
import {buildFleetRateLimitDecision} from '../src/lib/fleet-rate-limit-policy.ts';
const doc=()=>({'@context':'https://ref.gs1.org/standards/epcis/epcis-context.jsonld',type:'EPCISDocument',schemaVersion:'2.0',epcisBody:{eventList:[{type:'ObjectEvent',eventID:'urn:qa:one',eventTime:'2026-09-19T12:00:00Z',eventTimeZoneOffset:'-03:00',action:'OBSERVE',bizStep:'receiving',epcList:['https://nexid.lat/01/09506000134352/21/ONE']}]}});
test('existing roles and explicit denies determine capability; MFA is mandatory to commit',()=>{assert.equal(intakeCapabilities('tenant-admin',()=>true,()=>false,true).canCommit,true);assert.equal(intakeCapabilities('tenant-admin',()=>true,()=>false,false).canCommit,false);assert.equal(intakeCapabilities('viewer',()=>true,()=>false,true).canRead,false);assert.equal(intakeCapabilities('tenant-admin',()=>true,p=>p==='sdk:epcis:write',true).canCommit,false);assert.equal(intakeCapabilities('super-admin',()=>true,p=>p==='epcis.import',true).canRead,false);});
test('the existing parser prepares the declared business event without NFC claims',()=>{const d=intakeDocument(doc());assert.equal(d.events[0].event_type,'ObjectEvent');assert.equal(d.projectionCount,1);assert.match(d.events[0].biz_step,/receiving/);});
test('stable explicit event IDs and restricted extension fields are mandatory',()=>{const d=doc();delete d.epcisBody.eventList[0].eventID;assert.throws(()=>intakeDocument(d),/unique_event_id/);const r=doc();r.epcisBody.eventList.push(r.epcisBody.eventList[0]);assert.throws(()=>intakeDocument(r),/unique_event_id/);const secret=doc();secret.epcisBody.eventList[0].cmac='not allowed';assert.throws(()=>intakeDocument(secret),/fields_unsupported/);});
test('context, event limit, file size and references cannot be silently defaulted',()=>{assert.throws(()=>intakeDocument({...doc(),schemaVersion:'1.2'}));assert.throws(()=>intakeDocument({...doc(),epcisBody:{eventList:Array(51).fill(doc().epcisBody.eventList[0])}}));assert.throws(()=>intakeDocument({value:'x'.repeat(100001)}));for(const r of ['',123,'x\nxx'])assert.throws(()=>intakeReference(r));});
test('stable semantic digest ignores property order but not value changes',()=>{assert.equal(digest({a:1,b:2}),digest({b:2,a:1}));assert.notEqual(digest({a:1}),digest({a:2}));});
test('operator captures use the same conservative fan-out budget as SDK documents',()=>{const r=buildFleetRateLimitDecision({method:'POST',pathname:'/admin/batches/X/epcis-intake/commit',tenantId:'tenant',subjectId:'actor'});assert.equal(r.rateClass,'sdk_epcis_capture');assert.equal(r.limit,2);const p=buildFleetRateLimitDecision({method:'POST',pathname:'/admin/batches/X/epcis-intake/preview'});assert.equal(p.rateClass,'observability_read');assert.equal(p.limit,12);});
test('migration keeps one engine, guards its previous version and enforces mutually exclusive actor provenance',async()=>{const s=await readFile(new URL('../db/migrations/20260919200000_0111_epcis_operator_intake.sql',import.meta.url),'utf8');assert.match(s,/epcis_engine_changed_reconcile_before_upgrade/);assert.match(s,/epcis_capture_actor_choice/);assert.match(s,/IS TRUE/);assert.match(s,/FOR SHARE OF u,m,t/);assert.match(s,/v_existing.actor_user_id IS DISTINCT FROM v_actor_user_id/);assert.match(s,/g.batch_id=\(v_operator_context/);assert.doesNotMatch(s,/CREATE TABLE|UPDATE tags|DELETE FROM|DROP TABLE/);});
test('nested extensions and impossible calendar values are refused',()=>{
 const d=doc();d.epcisBody.eventList[0].readPoint={id:'urn:qa:reader',unexpectedField:'not accepted'};
 assert.throws(()=>intakeDocument(d),/fields_unsupported/);
 const t=doc();t.epcisBody.eventList[0].eventTime='2026-02-30T12:00:00Z';
 assert.throws(()=>intakeDocument(t),/time_with_zone/);
});
