import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {productionRows,productionFailure} from '../src/lib/gs1-production-service.ts';
const valid={gtin:'09506000134352',lot:'L1',serial:'000001'};
test('file keeps GTIN and leading zero series as text',()=>{assert.deepEqual(productionRows([valid]),[valid]);assert.equal(productionRows([valid])[0].serial,'000001');});
test('unbounded arrays or payload fields never reach the SQL function',()=>{for(const rows of [[],Array(101).fill(valid),[{...valid,tenant:'other'}],[{...valid,actorId:'other'}],[{...valid,raw_keys:'not-a-key'}],[{...valid,serial:123}],[{...valid,lot:'line\nnext'}]])assert.throws(()=>productionRows(rows));});
test('known concurrency failures remain conflicts without leaking SQL details',()=>{assert.deepEqual(productionFailure(Error('duplicate key on uq_gs1_identity_public_path')),{reason:'gs1_import_state_changed',status:409});assert.deepEqual(productionFailure(Error('password secret connection')),{reason:'gs1_production_unavailable',status:503});});
test('function validates, locks and commits identity audit with the same receipt',async()=>{const s=await readFile(new URL('../db/migrations/20260919180000_0110_gs1_batch_import.sql',import.meta.url),'utf8');assert.match(s,/SECURITY INVOKER/);assert.match(s,/pg_advisory_xact_lock/);assert.match(s,/gs1_import_plan_changed/);assert.match(s,/INSERT INTO public.gs1_digital_link_identity_audit/);assert.match(s,/INSERT INTO public.gs1_batch_import_operations/);assert.doesNotMatch(s,/UPDATE public.batches|UPDATE public.tags|DELETE FROM|DROP TABLE|GRANT .* PUBLIC/);});
test('print service never dereferences public product links or contacts a generator',async()=>{const s=await readFile(new URL('../src/lib/gs1-production-service.ts',import.meta.url),'utf8');assert.match(s,/QRCode.toString/);assert.match(s,/margin:4/);assert.doesNotMatch(s,/fetch\(|https:\/\/.*qrcode/);assert.match(s,/physicalVerification:false/);});
test('route ignores supplied roles and actor identity by obtaining the existing session authority',async()=>{const s=await readFile(new URL('../src/lib/gs1-production-http.ts',import.meta.url),'utf8');assert.match(s,/channelAccess/);assert.match(s,/access.principal!.userId/);assert.match(s,/readBoundedJsonBody/);assert.match(s,/private, no-store/);});
