import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';
import {createEditorialDraft,transitionEditorialDraft,completeEditorialPublication,reopenEditorialDraft} from '../src/lib/passport-editorial-policy.ts';
import {sourceEditorialDocument,validateStudioCommand,studioFailure} from '../src/lib/passport-editorial-service.ts';
import {roleMayUseEnterpriseCapability} from '../src/lib/enterprise-capability-policy.ts';
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;const scope={tenantId:id(1),batchId:id(2)},authority={actorId:'user_editor',canEdit:true,canReview:true};const digest='a'.repeat(64),at='2026-09-18T10:00:00.000Z';
const doc={schemaVersion:'nexid.passport-editorial.v1',template:'general',locale:'es-AR',identity:{product_name:'Producto QA'}};
const options=d=>({scope,expectedRevision:d.revision,expectedContentDigest:d.contentDigest,at});
function approved(){const draft=createEditorialDraft({id:id(3),scope,authority,document:doc,basePublishedDigest:digest,at});const submitted=transitionEditorialDraft(draft,{...options(draft),action:'submit',authority});return transitionEditorialDraft(submitted,{...options(submitted),action:'approve',authority:{actorId:'user_reviewer',canEdit:false,canReview:true}});}
test('publish is a new state and revision, while a subsequent edit cycle clears approval',()=>{const d=approved();const p=completeEditorialPublication(d,{...options(d),canPublish:true,currentPublishedDigest:digest});assert.equal(p.state,'published');assert.equal(p.revision,d.revision+1);const r=reopenEditorialDraft(p,{...options(p),authority,currentPublishedDigest:'b'.repeat(64)});assert.equal(r.state,'draft');assert.equal(r.approval,null);assert.equal(r.submittedBy,null);assert.equal(r.basePublishedDigest,'b'.repeat(64));});
test('reopening cannot be used to bypass edit permission or stale revision guards',()=>{const d=approved();assert.throws(()=>reopenEditorialDraft(d,{...options(d),authority:{...authority,canEdit:false},currentPublishedDigest:digest}),/editorial_edit_forbidden/);assert.throws(()=>reopenEditorialDraft(d,{...options(d),expectedRevision:0,authority,currentPublishedDigest:digest}),/editorial_revision_conflict/);});
test('source projection excludes keys and keeps unrelated fields outside editorial documents',()=>{const result=sourceEditorialDocument({product_name:'Producto QA',meta_key:'private-fixture',read_counter:4,sun:{product:{name:'other',vintage:2024}}},'general','es-AR');assert.equal(result.identity.product_name,'Producto QA');assert.ok(!JSON.stringify(result).includes('private-fixture'));assert.ok(!JSON.stringify(result).includes('read_counter'));});
test('command does not accept browser-supplied actor or capability flags',()=>{const c={action:'submit',operationId:id(4),scope,draftId:id(3),expectedRevision:1,expectedContentDigest:digest};assert.equal(validateStudioCommand(c).action,'submit');for(const extra of [{actorId:'another'},{canReview:true},{approval:{}},{document:doc}])assert.throws(()=>validateStudioCommand({...c,...extra}));});
test('a review rejection requires an actionable note',()=>{assert.throws(()=>validateStudioCommand({action:'request_changes',operationId:id(4),scope,draftId:id(3),expectedRevision:1,expectedContentDigest:digest}),/editorial_note_required/);});
test('review and publish are role-limited without altering editor roles',()=>{assert.equal(roleMayUseEnterpriseCapability('marketing-manager','batch.product.configure'),true);assert.equal(roleMayUseEnterpriseCapability('marketing-manager','batch.product.review'),false);assert.equal(roleMayUseEnterpriseCapability('packaging-operator','batch.product.publish'),false);assert.equal(roleMayUseEnterpriseCapability('tenant-admin','batch.product.review'),true);});
test('database faults return bounded reasons without raw data',()=>{assert.deepEqual(studioFailure(Object.assign(new Error('sql contains private data'),{code:'42P01'})),{reason:'editorial_migration_required',status:503});assert.equal(studioFailure(new Error('connection private')).reason,'editorial_unavailable');});
test('legacy editor and database guard both preserve the managed workflow',async()=>{const route=await readFile(new URL('../src/app/admin/batches/[bid]/product-config/route.ts',import.meta.url),'utf8');const sql=await readFile(new URL('../db/migrations/20260918120000_0104_passport_editorial.sql',import.meta.url),'utf8');assert.match(route,/editorial_managed_use_studio/);assert.match(route,/sdm_config IS NOT DISTINCT FROM/);assert.match(sql,/CREATE TRIGGER nexid_editorial_write_guard/);assert.match(sql,/FOR UPDATE/);assert.match(sql,/SECURITY INVOKER/);});
