import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {recallCommand,recallTotals,requireRecallAction} from '../src/lib/recall-policy.ts';
const id='10000000-0000-4000-8000-000000000001';
const doc={kind:'recall',title:'Retiro por control',reason:'Investigación interna documentada',publicMessage:'Este lote tiene un retiro vigente.',instructions:'Separar el producto y contactar al responsable.',contact:'Soporte de la empresa',unitLabel:'envases',destinations:[{id,recipient:'Distribuidor QA',assigneeId:id,units:10}]};
const command={operationId:id,caseId:id,expectedVersion:0,document:doc};
test('only declared recall fields reach the transaction; clients cannot grant roles or publish silently',()=>{for(const key of ['actorId','canPublish','tenantId','status','ttstatus_source'])assert.throws(()=>recallCommand('create',{...command,[key]:true}));});
test('destinations need real user IDs and integral bounded declared quantities',()=>{for(const units of [-1,0,0.5,'10',10000001])assert.throws(()=>recallCommand('create',{...command,document:{...doc,destinations:[{...doc.destinations[0],units}]}}));});
test('duplicated destination identity and hidden extra recipient data are rejected',()=>{assert.throws(()=>recallCommand('create',{...command,document:{...doc,destinations:[...doc.destinations,...doc.destinations]}}));assert.throws(()=>recallCommand('create',{...command,document:{...doc,destinations:[{...doc.destinations[0],secret:'bad'}]}}));});
test('public message, scope and contact are explicit, not inferred from a tap',()=>{assert.throws(()=>recallCommand('create',{...command,document:{...doc,publicMessage:''}}));assert.equal(recallCommand('create',command).document.kind,'recall');});
test('publication requires both write and publication authority',()=>{for(const actor of [{canRead:true,canWrite:true,canPublish:false},{canRead:true,canWrite:false,canPublish:true}])assert.throws(()=>requireRecallAction(actor,'publish'));});
test('totals are operator-declared and keep outstanding units visible',()=>{assert.deepEqual(recallTotals(doc,{[id]:{returnedUnits:3,heldUnits:2,acknowledgedAt:'2026-09-18T00:00:00Z'}}),{declaredUnits:10,returnedUnits:3,heldUnits:2,pendingUnits:5,acknowledgedDestinations:1,totalDestinations:1,basis:'operator_declared'});});
test('SQL never rewrites hardware status, chip evidence or product configuration',async()=>{const s=await readFile(new URL('../db/migrations/20260918180000_0106_batch_recall_workflow.sql',import.meta.url),'utf8');assert.doesNotMatch(s,/UPDATE (?:public\.)?(?:batches|tags)|ttstatus|sdm_config|meta_key_ct/);assert.match(s,/pg_advisory_xact_lock/);assert.match(s,/recall_independent_review_required/);assert.match(s,/recall_pending_actions/);assert.match(s,/INSERT INTO public.product_recall_operations/);});
test('public projection has no recipients, evidence references, internal reasons or actor fields',async()=>{const s=(await readFile(new URL('../src/lib/recall-service.ts',import.meta.url),'utf8')).split('export async function publicRecallNotices')[1];assert.doesNotMatch(s,/created_by|actor_label|destinations|evidenceReference|->>'reason'/);assert.match(s,/published_at IS NOT NULL/);});

import {recallCapabilities} from '../src/lib/recall-authority.ts';
test('existing company lifecycle and quality-plan authority can operate recalls without granting new roles',()=>{const grants=['batch.lifecycle','qa.plan.approve','reports.export'];assert.deepEqual(recallCapabilities('tenant-admin',p=>grants.includes(p),()=>false,true),{canRead:true,canWrite:true,canPublish:true,canExport:true});assert.equal(recallCapabilities('operations-manager',p=>grants.includes(p),()=>false,true).canPublish,false);});
test('specific denies and absent MFA override inferred lifecycle access',()=>{assert.equal(recallCapabilities('tenant-admin',()=>true,p=>p==='recalls.publish',true).canPublish,false);assert.equal(recallCapabilities('tenant-admin',()=>true,()=>false,false).canPublish,false);assert.equal(recallCapabilities('tenant-admin',()=>true,p=>p==='incidents:read',true).canRead,false);assert.equal(recallCapabilities('marketing-manager',()=>true,()=>false,true).canWrite,false);});
