import assert from 'node:assert/strict';import test from 'node:test';import {readFile}from'node:fs/promises';
import {checkAdmin}from'../src/lib/auth.ts';
import {makeRuntimeReadinessHandler}from'../src/lib/runtime-readiness-http.ts';
import {RUNTIME_FUNCTIONS,RUNTIME_LEDGER_IDS,RUNTIME_REQUIREMENTS,RUNTIME_FLAG_KEYS,collectRuntimeReadiness,projectRuntimeReadiness}from'../src/lib/runtime-readiness.ts';
import {DEFAULT_REQUIRED_SCHEMA_MIGRATIONS}from'../src/lib/db.ts';
import {CARRIER_PROFILES}from'../src/lib/carrier-profiles.ts';
const now=Date.parse('2026-09-24T23:58:00.000Z');
const fixture=(patch={})=>{const migrations=[...new Set([...DEFAULT_REQUIRED_SCHEMA_MIGRATIONS,...RUNTIME_LEDGER_IDS])].sort();return {observed_at:new Date(now).toISOString(),database:{name:'neondb',session_role:'nexid_runtime',login_role:'nexid_runtime',endpoint_id:'ep-test-fixture',server_version_num:'170010',transaction_read_only:true},role:{superuser:false,bypass_rls:false,create_role:false,create_database:false,create_public_schema:false,owns_database:false,owns_public_objects:false},migrations,migration_count:migrations.length,migrations_truncated:false,catalogs:{carriers:CARRIER_PROFILES.map(p=>p.code),carriers_count:CARRIER_PROFILES.length,ledgers:['none','polygon','iota'],ledgers_count:3,truncated:false},functions:RUNTIME_FUNCTIONS.map(signature=>({signature,present:true,executable:true})),...patch};};
const session=(patch={})=>({id:'10000000-0000-4000-8000-000000000001',userId:'20000000-0000-4000-8000-000000000001',email:'operator@example.invalid',label:'QA',role:'super-admin',tenantId:null,tenantSlug:null,permissions:['audit.read'],deniedPermissions:[],mfaVerified:false,expiresAt:new Date(now+60000).toISOString(),rotatedCookieValue:null,setupCompleted:true,...patch});
function harness(options={}){const calls=[];const get=makeRuntimeReadinessHandler({authorize:(req,scopes)=>checkAdmin(req,scopes,options.resolver||(async()=>session(options.session))),query:async(strings,...values)=>{calls.push({text:strings.join('?'),values});if(options.failure)throw Error('postgresql://PRIVATE_SECRET/never');return [{observation:options.raw??fixture()}];},environment:()=>options.env||{},now:()=>now});return{calls,get};}
const request=(query='',method='GET',headers={})=>new Request('https://api.example.invalid/admin/diagnostics/runtime-readiness'+query,{method,headers:{authorization:'Bearer fixture-session',...headers}});
test('named prerequisites present never means an authorization to promote or apply SQL',()=>{const report=projectRuntimeReadiness(fixture(),{},now);assert.equal(report.readiness,'further_acceptance_required');assert.equal(report.promotionAllowed,false);assert.equal(report.migrationExecutionAllowed,false);assert.equal(report.ledger.fullRepositoryReconciliation,'not_performed');assert.equal(report.requirements.every(r=>r.status==='named_prerequisites_present'),true);assert.equal(report.runtime.environment,'unverified');});
test('actual missing migration and routine block the feature even if its rollout flag is enabled',()=>{const raw=fixture(),id=RUNTIME_REQUIREMENTS.find(r=>r.id==='cancellation').migrations[0];raw.migrations=raw.migrations.filter(x=>x!==id);raw.migration_count--;raw.functions=raw.functions.map(f=>f.signature.includes('nexid_cancel_supplier')?{...f,present:false,executable:false}:f);const report=projectRuntimeReadiness(raw,{SUPPLIER_REQUEST_CANCELLATION_ENABLED:'true'},now);const result=report.requirements.find(r=>r.id==='cancellation');assert.equal(result.status,'schema_or_ledger_missing');assert.deepEqual(result.missingMigrations,[id]);assert.ok(report.enabledWithoutPrerequisites.includes('cancellation'));});
test('a table or recorded migration is not a substitute for the runtime EXECUTE permission',()=>{const raw=fixture();raw.functions[0].executable=false;const report=projectRuntimeReadiness(raw,{},now);assert.ok(report.requirements.some(r=>r.status==='execute_privilege_missing'));});
for(const flag of Object.values(RUNTIME_FLAG_KEYS))test('only literal true enables flag '+flag,()=>{for(const value of [undefined,'false','TRUE','1','', 'true ']){const out=projectRuntimeReadiness(fixture(),{[flag]:value},now);assert.ok(Object.values(out.featureFlags).every(f=>!f.enabled));}});
test('a privileged connection is visible without claiming it is an isolated tenant database user',()=>{const raw=fixture();raw.role.owns_database=true;const report=projectRuntimeReadiness(raw,{},now);assert.equal(report.privilegedConnection,true);assert.equal(report.scope,'nexid_global_admin');assert.equal(report.promotionAllowed,false);});
test('secret environment fields and unrecognized data never reach the projection',()=>{const raw=fixture({connectionString:'postgresql://hidden',rows:[{email:'private'}]});raw.database.password='secret';raw.role.role_password='secret';const out=projectRuntimeReadiness(raw,{DATABASE_URL:'postgresql://hidden',KMS_MASTER_KEY_HEX:'private',VERCEL_ENV:'production',VERCEL_DEPLOYMENT_ID:'dpl_abcdefgh12345',VERCEL_GIT_COMMIT_SHA:'a'.repeat(40)},now);assert.equal(out.runtime.environment,'production');assert.equal(out.runtime.commit,'a'.repeat(40));assert.doesNotMatch(JSON.stringify(out),/hidden|password|role_password|private|postgresql/);});
test('metadata is server-observed, and malformed deployment headers cannot create binding proof',()=>{const out=projectRuntimeReadiness(fixture(),{VERCEL_DEPLOYMENT_ID:'bad/secret',VERCEL_GIT_COMMIT_SHA:'not-a-commit',VERCEL_ENV:'evil'},now);assert.equal(out.runtime.commit,null);assert.equal(out.runtime.deploymentId,null);assert.equal(out.runtime.environment,'unverified');assert.ok(out.unverified.includes('control_plane_branch_mapping'));});
for(const patch of [{observed_at:'invalid'},{observed_at:new Date(now+31000).toISOString()},{observed_at:new Date(now-61000).toISOString()},{migration_count:0},{migrations_truncated:true},{migrations:['bad']},{functions:[]},{role:{superuser:false}}])test('incomplete or stale observation is rejected '+JSON.stringify(patch),()=>assert.throws(()=>projectRuntimeReadiness(fixture(patch),{},now)));
test('duplicates, mismatched catalog sizes, excessive results and impossible function privileges fail',()=>{
 for(const mutate of [r=>r.migrations.push(r.migrations[0]),r=>r.catalogs.carriers.push(r.catalogs.carriers[0]),r=>r.catalogs.truncated=true,r=>r.catalogs.carriers_count++,r=>r.functions[0]={...r.functions[0],present:false,executable:true},r=>r.functions[1]={...r.functions[0]},r=>r.database.endpoint_id='postgresql://secret',r=>r.database.server_version_num='17',r=>r.database.transaction_read_only='on']){const raw=fixture();mutate(raw);assert.throws(()=>projectRuntimeReadiness(raw,{},now));}
});
test('one fixed diagnostic query reads catalogs and ledger, not customer tables, keys or dynamic SQL',async()=>{const h=harness(),response=await h.get(request());assert.equal(response.status,200);assert.equal(h.calls.length,1);const q=h.calls[0];assert.deepEqual(q.values,[RUNTIME_FUNCTIONS]);assert.match(q.text,/LIMIT 513/);assert.match(q.text,/LIMIT 129/);assert.doesNotMatch(q.text.replace(/'(?:''|[^'])*'/g,''),/\b(?:CREATE|ALTER|DROP|INSERT|UPDATE|DELETE|GRANT|REVOKE|CALL)\b/);assert.doesNotMatch(q.text,/FROM public\.(?:users|tenants|tickets|batch_keys|vault_artifacts|events)\b/);for(const header of ['cache-control','vary','pragma','referrer-policy','x-content-type-options'])assert.ok(response.headers.get(header));assert.equal(response.headers.get('vary'),'Authorization');});
for(const patch of [{role:'tenant-admin',tenantId:'30000000-0000-4000-8000-000000000001',tenantSlug:'demo'},{role:'tenant-owner',tenantId:'30000000-0000-4000-8000-000000000001',tenantSlug:'demo'},{role:'security-analyst',tenantId:'30000000-0000-4000-8000-000000000001',tenantSlug:'demo'},{role:'supplier-operator',permissions:['*']},{role:'api-integration'},{role:'viewer'},{deniedPermissions:['audit.read']},{deniedPermissions:['audit:read']},{deniedPermissions:['*']}])test('non-global or explicitly denied authority sees no database metadata '+JSON.stringify(patch),async()=>{const h=harness({session:patch}),r=await h.get(request());assert.equal(r.status,403);assert.equal(h.calls.length,0);assert.doesNotMatch(await r.text(),/neondb|endpoint|migrations/);});
test('missing, revoked or failed persisted session cannot be replaced by headers',async()=>{for(const resolver of [async()=>null,async()=>{throw Error('PRIVATE_SESSION');}]){const h=harness({resolver}),r=await h.get(request('', 'GET',{'x-admin-scope':'super_admin','x-tenant':'other','x-admin-permissions':'*'}));assert.ok([401,503].includes(r.status));assert.equal(h.calls.length,0);assert.doesNotMatch(await r.text(),/PRIVATE_SESSION/);}});
for(const query of ['?tenant=other','?sql=SELECT%201','?role=neondb_owner','?force=true'])test('selectors cannot redirect diagnostics '+query,async()=>{const h=harness();assert.equal((await h.get(request(query))).status,400);assert.equal(h.calls.length,0);});
test('method overrides and mutation methods fail without a diagnostic SQL call',async()=>{for(const [method,headers] of [['POST',{}],['GET',{'x-http-method-override':'POST'}]]){const h=harness();assert.ok([400,405].includes((await h.get(request('',method,headers))).status));assert.equal(h.calls.length,0);}});
test('SQL, malformed rows and stale returns fail with a sanitized unavailable response',async()=>{for(const options of [{failure:true},{raw:{}},{raw:fixture({observed_at:'invalid'})}]){const response=await harness(options).get(request());assert.equal(response.status,503);assert.deepEqual(await response.json(),{ok:false,reason:'runtime_readiness_unavailable'});}});
test('the deployed route is GET-only, Node and dynamic; no public health mutation is introduced',async()=>{const text=await readFile(new URL('../src/app/admin/diagnostics/runtime-readiness/route.ts',import.meta.url),'utf8');assert.match(text,/export const GET=makeRuntimeReadinessHandler/);assert.match(text,/force-dynamic/);assert.doesNotMatch(text,/export (?:async function|const) (?:POST|PUT|DELETE|PATCH)/);});
