import assert from 'node:assert/strict';import test from 'node:test';import{checkAdminWithPermission}from'../src/lib/auth.ts';
import{makeSupplierServiceStatusHandler,SUPPLIER_SERVICE_DEPENDENCIES as manifest}from'../src/lib/supplier-service-status-http.ts';
const id='10000000-0000-4000-8000-000000000001';
const session=(patch={})=>({id:'30000000-0000-4000-8000-000000000001',userId:'20000000-0000-4000-8000-000000000001',role:'operations-manager',tenantId:id,tenantSlug:'qa-only',permissions:['supplier_order.create'],deniedPermissions:[],email:'qa@example.invalid',label:'QA',mfaVerified:false,expiresAt:new Date(Date.now()+60000).toISOString(),setupCompleted:true,rotatedCookieValue:null,...patch});
const observation=()=>({observed_at:new Date(),migrations:[...new Set(Object.values(manifest).flatMap(v=>v.migrations))].map(id=>({id,recorded:true})),functions:[...new Set(Object.values(manifest).flatMap(v=>v.functions))].map(signature=>({signature,present:true,executable:true}))});
function fixture({patch={},row=observation(),enabled=true,missingSession=false,fail=false}={}){const queries=[];let authCalls=0;return{queries,get authCalls(){return authCalls;},handler:makeSupplierServiceStatusHandler({authorize:(req,p)=>{authCalls++;return checkAdminWithPermission(req,p,async()=>missingSession?null:session(patch));},enabled:()=>enabled,query:async(strings,...values)=>{queries.push({sql:strings.join('?'),values});if(fail)throw Error('PRIVATE_DATABASE_URL');return strings.join('').includes('FROM public.tenants')?[{id,slug:'qa-only'}]:[row];}})};}
async function call(f,query='?tenant=qa-only',method='GET',headers={}){const r=await f.handler(new Request('http://localhost/admin/supplier-requests/service-status'+query,{method,headers:{authorization:'Bearer synthetic-local-session',...headers}}));assert.match(r.headers.get('cache-control'),/private.*no-store/);return{status:r.status,body:await r.json()};}
test('availability is one bounded catalog query after scope resolution, never a business operation',async()=>{const f=fixture(),r=await call(f);assert.equal(r.status,200);assert.equal(f.queries.length,2);assert.ok(f.queries.every(q=>q.sql.trim().startsWith('SELECT')));assert.ok(f.queries[1].sql.includes('pg_')||f.queries[1].sql.includes('to_regprocedure'));assert.doesNotMatch(f.queries[1].sql,/FROM public\.(?:supplier_requests|audit_logs|users|consumers)/);assert.doesNotMatch(JSON.stringify(r.body),/signature|schema_migrations|current_user|database|password|auth_session/);assert.equal(r.body.operationAuthorized,false);});
test('disabled flags preserve history access except cancellation which has no separate read-only route',async()=>{const r=await call(fixture({enabled:false}));assert.equal(r.body.services[0].state,'temporarily_disabled');assert.ok(r.body.services.slice(1).every(s=>s.state==='read_only'&&s.readAvailable&&!s.writesEnabled));});
for(const type of ['missing_migration','missing_function','missing_execute'])test('required deployment input '+type+' is not inferred true from another module',async()=>{const row=observation();if(type==='missing_migration')row.migrations.find(m=>m.id.includes('_0120_')).recorded=false;else{const f=row.functions.find(f=>f.signature.includes('delivery_ack_read'));f.executable=false;if(type==='missing_function')f.present=false;}const r=await call(fixture({row}));assert.equal(r.body.services.find(s=>s.id==='delivery_ack').state,'setup_required');assert.equal(r.body.services.find(s=>s.id==='quotation').state,'workflow_available');});
for(const patch of [{role:'viewer'},{role:'supplier-operator',tenantId:null,tenantSlug:null,permissions:['*']},{role:'api-integration'},{permissions:[]},{deniedPermissions:['supplier_order.create']},{deniedPermissions:['supplier_orders:write']}])test('real authority rejects before database reads '+JSON.stringify(patch),async()=>{const f=fixture({patch}),r=await call(f);assert.ok([401,403].includes(r.status));assert.equal(f.queries.length,0);});
test('missing session, foreign tenant and global-without-tenant do not discover another scope',async()=>{const f=fixture({missingSession:true});assert.equal((await call(f)).status,401);assert.equal(f.queries.length,0);const tenant=fixture();assert.equal((await call(tenant,'?tenant=foreign')).status,403);assert.equal(tenant.queries.length,0);assert.equal((await call(fixture({patch:{role:'super-admin',tenantId:null,tenantSlug:null}}),'')).status,400);});
for(const q of ['?tenant=qa-only&tenant=other','?tenant=qa-only&url=https://remote.invalid','?tenant=qa-only&sql=SELECT','?tenant=qa-only&before_revision=2'])test('unknown or repeated selectors are rejected '+q,async()=>{const f=fixture();assert.equal((await call(f,q)).status,400);assert.equal(f.authCalls,0);});
for(const method of ['POST','PATCH','PUT','DELETE','HEAD'])test('no mutation method '+method,async()=>{const f=fixture();assert.equal((await call(f,undefined,method)).status,405);assert.equal(f.queries.length,0);});
test('unexpected database data never becomes an optimistic status',async()=>{for(const modify of [r=>r.migrations.pop(),r=>r.functions.push(r.functions[0]),r=>r.functions[0].executable='true',r=>{r.functions[0].present=false;r.functions[0].executable=true},r=>r.observed_at='invalid']){const row=observation();modify(row);assert.equal((await call(fixture({row}))).status,503);}const failed=await call(fixture({fail:true}));assert.equal(failed.status,503);assert.doesNotMatch(JSON.stringify(failed),/PRIVATE/);});
