import assert from 'node:assert/strict';import test from 'node:test';
import{checkAdminWithPermission}from'../src/lib/auth.ts';import{makeSupplierBindingHandlers}from'../src/lib/supplier-request-binding-http.ts';import{supplierOrderLifecycleError}from'../src/lib/supplier-order-lifecycle.ts';
const tenant='10000000-0000-4000-8000-000000000001',other='10000000-0000-4000-8000-000000000002',actor='20000000-0000-4000-8000-000000000001',sid='30000000-0000-4000-8000-000000000001',id='40000000-0000-4000-8000-000000000001',key='50000000-0000-4000-8000-000000000001',orderId='60000000-0000-4000-8000-000000000001',eid='70000000-0000-4000-8000-000000000001',did='80000000-0000-4000-8000-000000000001';
const supplier=()=>({reference:'FACTORY-QA',name:'Proveedor QA',confirmation_ref:'DOC-QA'}),spec=()=>({revision:1,hash:'sha256:'+'a'.repeat(64),decision_id:did});
const command=()=>({action:'assign',expected_revision:0,expected_request_revision:5,order_id:orderId,supplier:supplier(),spec:spec(),reason:'Registro revisado.'});
const event=(patch={})=>({id:eid,revision:1,request_revision:5,order_id:orderId,action:'assign',supplier:supplier(),spec:spec(),reason:'Registro revisado.',actor_id:actor,created_at:'2026-09-24T12:00:00.000Z',...patch});
const result=(patch={})=>({ok:true,tenant_id:tenant,tenant_slug:'qa-a',request_id:id,request_revision:5,order:{id:orderId,status:'pack_ready',pack_purpose:'production'},specification:{status:'approved',...spec(),ready:true},revision:1,current:event(),history:[event()],count:1,truncated:false,next_before_revision:null,dispatch_receipt:null,as_of:'2026-09-24T12:00:01.000Z',receipt:{idempotency_key:key,event_id:eid,action:'assign',revision:1},idempotent_replay:false,...patch});
function session(patch={}){return{id:sid,userId:actor,email:'qa@example.invalid',label:'QA',role:'super-admin',tenantId:null,tenantSlug:null,permissions:['supplier_order.create'],deniedPermissions:[],mfaVerified:false,expiresAt:new Date(Date.now()+60000).toISOString(),rotatedCookieValue:null,setupCompleted:true,...patch};}
function fixture(options={}){const queries=[],permissions=[];const handlers=makeSupplierBindingHandlers({enabled:()=>options.enabled!==false,authorize:(req,p)=>{permissions.push(p);return checkAdminWithPermission(req,p,options.resolver||(async()=>session(options.session)));},query:async(strings,...values)=>{const sql=strings.join('?');queries.push({sql,values});if(sql.includes('FROM public.tenants'))return[{id:tenant,slug:'qa-a'}];if(sql.includes('to_regprocedure'))return[{available:options.available!==false}];if(options.fail)throw Error('PRIVATE_SQL_CREDENTIAL');return[{result:options.result===null?null:options.result||result()}];}});return{queries,permissions,handlers};}
async function call(f,method='post',body=command(),query='?tenant=qa-a',headers={}){const req=new Request('http://localhost/admin/supplier-requests/'+id+'/supplier-binding'+query,{method:method==='get'?'GET':'POST',headers:{authorization:'Bearer synthetic-local-session',...(method==='post'?{'content-type':'application/json','idempotency-key':key}:{}),...headers},...(method==='post'?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});const response=await f.handlers[method](req,id);assert.match(response.headers.get('cache-control'),/private.*no-store/);assert.equal(response.headers.get('referrer-policy'),'no-referrer');return{status:response.status,body:await response.json()};}
test('history reads remain available with writes disabled; disabled writes perform no queries',async()=>{const f=fixture({enabled:false});assert.equal((await call(f,'get')).body.writes_enabled,false);const blocked=fixture({enabled:false});assert.equal((await call(blocked)).status,503);assert.equal(blocked.queries.length,0);assert.equal((await call(fixture({available:false}),'get')).status,503);});
test('binding carries only authenticated actor/session and a matching tenant/order/spec receipt',async()=>{const f=fixture(),r=await call(f);assert.equal(r.status,200);assert.deepEqual(f.permissions,['supplier_order.create']);assert.deepEqual(JSON.parse(f.queries.at(-1).values[0]),{...command(),tenant_id:tenant,request_id:id,actor_id:actor,auth_session_id:sid,idempotency_key:key});assert.equal(r.body.binding_status,'current');assert.doesNotMatch(JSON.stringify(r.body),/auth_session_id|fingerprint|PRIVATE_SQL/);});
test('company is read-only, even with its existing request management permission',async()=>{const patch={role:'operations-manager',tenantId:tenant,tenantSlug:'qa-a'};assert.equal((await call(fixture({session:patch}),'get')).status,200);const denied=fixture({session:patch});assert.equal((await call(denied)).status,403);assert.equal(denied.queries.length,0);});
for(const patch of [{role:'supplier-operator',permissions:['*']},{role:'viewer'},{role:'api-integration'},{deniedPermissions:['supplier_order.create']},{deniedPermissions:['supplier_orders:write']}])test('auth scope rejected before SQL '+JSON.stringify(patch),async()=>{for(const method of ['get','post']){const f=fixture({session:patch});assert.ok([401,403].includes((await call(f,method)).status));assert.equal(f.queries.length,0);}});
test('missing/revoked and failed session resolution never leaks internals',async()=>{for(const resolver of [async()=>null,async()=>{throw Error('PRIVATE_SESSION');}]){const f=fixture({resolver}),r=await call(f);assert.ok([401,503].includes(r.status));assert.equal(f.queries.length,0);assert.doesNotMatch(JSON.stringify(r),/PRIVATE/);}});
test('bad selectors, cursors and cross-tenant requests never reach binding data',async()=>{for(const query of ['?tenant=qa-a&tenant=qa-a','?tenant=qa-a&before_revision=0','?tenant=qa-a&before_revision=2&before_revision=2','?tenant=qa-a&extra=true']){const f=fixture();assert.equal((await call(f,'get',null,query)).status,400);assert.equal(f.queries.length,0);}const f=fixture({session:{role:'operations-manager',tenantId:tenant,tenantSlug:'qa-a'}});assert.equal((await call(f,'get',null,'?tenant=foreign')).status,403);assert.equal(f.queries.length,0);});
test('invalid bodies, identity injection and secret-like reference are rejected before mutation',async()=>{for(const[body,headers,status]of [['x'.repeat(17000),{},413],['{broken',{},400],[{...command(),actor_id:actor},{},400],[{...command(),supplier:{...supplier(),name:'PACK_PASSWORD'}},{},400],[{...command(),supplier:{...supplier(),confirmation_ref:'api_key=synthetic-private-value'}},{},400],[command(),{'content-type':'text/plain'},415],[command(),{'idempotency-key':'bad'},400]]){const f=fixture();assert.equal((await call(f,'post',body,undefined,headers)).status,status);assert.equal(f.queries.length,2);}});
for(const[reason,status]of [['supplier_binding_scope_forbidden',403],['supplier_request_not_found',404],['supplier_binding_request_changed',409],['supplier_binding_revision_conflict',409],['supplier_binding_idempotency_conflict',409],['supplier_binding_dispatch_locked',409],['supplier_binding_spec_changed',409],['supplier_binding_transition_invalid',409]])test('bounded refusal '+reason,async()=>assert.equal((await call(fixture({result:{ok:false,reason}}))).status,status));
test('foreign snapshots and mismatched receipts are unavailable instead of fabricated success',async()=>{for(const patch of [{tenant_id:other},{tenant_slug:'foreign'},{current:event({actor_id:other}),history:[event({actor_id:other})]},{current:event({reason:'other'}),history:[event({reason:'other'})]},{receipt:{...result().receipt,idempotency_key:id}},{receipt:{...result().receipt,revision:2}},{receipt:{...result().receipt,event_id:did}},{idempotent_replay:undefined},{request_revision:6}])assert.equal((await call(fixture({result:result(patch)}))).status,503);const out=await call(fixture({fail:true}));assert.equal(out.status,503);assert.doesNotMatch(JSON.stringify(out),/PRIVATE/);});
test('existing lifecycle gives actionable 409 on governed supplier/spec/recipient mismatch',()=>{for(const reason of ['supplier_binding_required','supplier_binding_spec_changed','supplier_binding_recipient_mismatch','supplier_binding_receipt_invalid'])assert.deepEqual(supplierOrderLifecycleError(Error(reason)),{status:409,reason});});
