import assert from 'node:assert/strict';import test from 'node:test';import{fileURLToPath}from'node:url';
import{splitSchemaStatements,observeSqlObjects,observeJsonTables,assessSupplierSchema,sha256,SUPPLIER_SCHEMA_FEATURES,MAX_SCHEMA_BYTES}from'../scripts/lib/supplier-schema-observation.mjs';
import{collectSupplierSchema,loadExpectedSupplierBodies,parseSchemaProviderJson,validateSchemaTarget}from'../scripts/lib/supplier-schema-collection.mjs';
import{parseSchemaPreflightArgs,readSchemaThroughCli,main}from'../scripts/supplier-schema-preflight.mjs';
const now=Date.parse('2026-09-24T23:20:00.000Z');
const target={projectId:'project-123',branchId:'br-main-123',databaseName:'neondb'};
const source=()=>({...target,provider:'neon-control-plane',method:'GET',observedAt:new Date(now).toISOString()});
function fixture(){const defs=new Map();for(const f of SUPPLIER_SCHEMA_FEATURES)for(const[t,columns]of Object.entries(f.tables)){const set=defs.get(t)||new Set();for(const c of columns)set.add(c);defs.set(t,set);}
 const tables=[...defs].map(([name,columns])=>({schema:'public',name,columns:[...columns].map(name=>({name,type:name==='status'?'text':'uuid',nullable:false})),constraints:[]}));
 const names=[...new Set(SUPPLIER_SCHEMA_FEATURES.flatMap(f=>f.functions))];const expectedBodies=Object.fromEntries(names.map(n=>[n,sha256('SELECT 1;')]));
 const sql=[...defs.keys()].map(t=>'CREATE TABLE public.'+t+' (id uuid);').join('\n')+'\n'+names.map(n=>'CREATE FUNCTION public.'+n+'() RETURNS integer LANGUAGE sql AS $$SELECT 1;$$;').join('\n');
 return{jsonSchema:{json:{tables}},sqlSchema:{sql},source:source(),expectedBodies};}
const assess=x=>assessSupplierSchema(x,now);
test('all named objects and bodies still do not prove ledger, runtime credentials or authority to promote',()=>{const r=assess(fixture());assert.ok(r.features.every(f=>f.structurePresent&&f.bodyComparison==='matches'));assert.equal(r.promotionAllowed,false);assert.ok(r.features.every(f=>f.ledgerApplied==='unverified'));assert.equal(r.atomicSnapshot,false);assert.ok(r.unverified.includes('actual_runtime_role'));assert.ok(r.unverified.includes('deployment_database_binding'));assert.equal(r.remoteSqlExecuted,false);});
test('missing cancellation fields are not disguised as a compatible sent request',()=>{const f=fixture();f.jsonSchema.json.tables.find(t=>t.name==='supplier_requests').columns=f.jsonSchema.json.tables.find(t=>t.name==='supplier_requests').columns.filter(c=>c.name!=='cancelled_at');const r=assess(f);assert.deepEqual(r.features.find(f=>f.id==='cancellation').missingColumns,['supplier_requests.cancelled_at']);assert.equal(r.status,'blocked_on_schema_or_definition');});
test('absent tables/functions and modified ticket bodies produce distinct actionable observations',()=>{const f=fixture();f.jsonSchema.json.tables=f.jsonSchema.json.tables.filter(t=>t.name!=='supplier_request_quote_events');f.sqlSchema.sql=f.sqlSchema.sql.replace('CREATE TABLE public.supplier_request_quote_events (id uuid);','').replace('CREATE FUNCTION public.nexid_mutate_supplier_quote_v1() RETURNS integer LANGUAGE sql AS $$SELECT 1;$$;','');f.expectedBodies.nexid_transition_support_ticket_v1=sha256('SELECT 2;');const r=assess(f);assert.deepEqual(r.features.find(f=>f.id==='quotations').missingTables,['supplier_request_quote_events']);assert.deepEqual(r.features.find(f=>f.id==='quotations').missingFunctions,['nexid_mutate_supplier_quote_v1']);assert.equal(r.features.find(f=>f.id==='ticket_type_compatibility').bodyComparison,'different');});
test('CREATE statements hidden in routine bodies and comments never count as installed objects',()=>{
 const text="-- CREATE TABLE public.fake_comment(id uuid);\n/* nested /* CREATE TABLE public.fake_nested(id uuid); */ comment */\nCREATE FUNCTION public.real() RETURNS void LANGUAGE plpgsql AS $body$ BEGIN PERFORM 'x;y'; -- CREATE TABLE public.fake(id uuid);\nPERFORM $$CREATE FUNCTION public.fake() RETURNS int AS $f$ SELECT 1; $f$ LANGUAGE sql;$$; END; $body$;\nCREATE TABLE public.real_table(id uuid);";
 const r=observeSqlObjects(text);assert.deepEqual([...r.functions.keys()],['public.real']);assert.deepEqual([...r.tables],['public.real_table']);
});
test('escaped string and identifier delimiters are handled without splitting embedded semicolons',()=>{const s="SELECT E'escaped\\\';still string'; SELECT 'a'';b'; SELECT \"semi;colon\";";assert.equal(splitSchemaStatements(s).length,3);});
for(const text of ["SELECT 'bad",'SELECT "bad','/* open comment','DO $x$ BEGIN NULL;'])test('unterminated SQL input is rejected '+text,()=>assert.throws(()=>splitSchemaStatements(text),/sql_unterminated/));
test('pg_dump restrict directives are ignored only outside function bodies',()=>{const header='\\restrict RANDOM123\n',footer='\n\\unrestrict RANDOM123\n';const fn='CREATE FUNCTION public.f() RETURNS text AS $$\n\\restrict INSIDEBODY\nSELECT 1;\n$$ LANGUAGE sql;';const parsed=observeSqlObjects(header+fn+footer);assert.equal(parsed.functions.get('public.f')[0].bodyHash,sha256('\\restrict INSIDEBODY\nSELECT 1;'));});
test('CRLF bodies compare canonically without discarding business text or escaping',()=>{const a='CREATE FUNCTION public.f() RETURNS int LANGUAGE sql AS $$\nSELECT 1;\n$$;';assert.deepEqual(observeSqlObjects(a),observeSqlObjects(a.replaceAll('\n','\r\n')));});
test('two exports disagreeing on a required table fail rather than merging conflicting observations',()=>{const f=fixture();f.sqlSchema.sql=f.sqlSchema.sql.replace('CREATE TABLE public.tickets (id uuid);','');assert.throws(()=>assess(f),/exports_disagree/);});
test('duplicate SQL/JSON tables, duplicate columns and ambiguous required functions fail closed',()=>{
 const f=fixture();f.sqlSchema.sql+='\nCREATE TABLE public.tickets(id uuid);';assert.throws(()=>assess(f),/duplicate_table/);
 const g=fixture();g.jsonSchema.json.tables.push(g.jsonSchema.json.tables[0]);assert.throws(()=>assess(g),/duplicate_table/);
 const h=fixture();h.jsonSchema.json.tables[0].columns.push(h.jsonSchema.json.tables[0].columns[0]);assert.throws(()=>assess(h),/column_invalid/);
 const k=fixture();k.sqlSchema.sql+='\nCREATE FUNCTION public.nexid_supplier_requests_assigned_v1(x text)RETURNS integer LANGUAGE sql AS $$SELECT 1;$$;';assert.throws(()=>assess(k),/routine_ambiguous/);
});
test('output is a projection and cannot carry extra secret-like metadata or raw SQL bodies',()=>{const f=fixture();f.source.secret='PRIVATE_SENTINEL';f.jsonSchema.json.tables[0].extra='PRIVATE_SENTINEL';const r=assess(f);assert.doesNotMatch(JSON.stringify(r),/PRIVATE_SENTINEL|CREATE FUNCTION|SELECT 1;/);assert.equal(r.retrievedDatabaseCredentials,false);assert.equal(r.businessRowsRead,false);});
for(const patch of [{observedAt:'2026-09-24T21:00:00.000Z'},{observedAt:'2026-09-25T00:00:00.000Z'},{observedAt:'invalid'},{provider:'manual'},{method:'POST'},{projectId:'bad/path'},{branchId:'main'},{databaseName:'name;DROP'}])test('invalid/future/stale source metadata fails '+JSON.stringify(patch),()=>{const f=fixture();Object.assign(f.source,patch);assert.throws(()=>assess(f));});
test('missing expected routine source is unverified, not a verified match',()=>{const f=fixture();delete f.expectedBodies.nexid_cancel_supplier_request_v1;assert.equal(assess(f).features.find(f=>f.id==='cancellation').bodyComparison,'unverified');});
test('schema and provider inputs are bounded with strict UTF8 and JSON',()=>{assert.throws(()=>splitSchemaStatements('x'.repeat(MAX_SCHEMA_BYTES+1)),/sql_invalid/);assert.throws(()=>splitSchemaStatements('SELECT\0'),/sql_invalid/);for(const v of [Buffer.from([255,254]),Buffer.from('{broken')])assert.throws(()=>parseSchemaProviderJson(v),/response_invalid/);assert.throws(()=>parseSchemaProviderJson(Buffer.alloc(MAX_SCHEMA_BYTES+1)),/too_large/);});
test('collector issues exactly three fixed GET routes, verifies branch identity and emits no raw schema',async()=>{const f=fixture(),seen=[];const r=await collectSupplierSchema(target,async(path,query)=>{seen.push({path,query});if(!query.length)return{branch:{id:target.branchId,project_id:target.projectId}};return query.includes('format=json')?f.jsonSchema:f.sqlSchema;},{clock:()=>now,expectedBodies:f.expectedBodies});assert.equal(seen.length,3);assert.ok(seen.every(s=>s.path.startsWith('/projects/project-123/branches/br-main-123')));assert.deepEqual(seen[1].query,['db_name=neondb','format=json']);assert.deepEqual(seen[2].query,['db_name=neondb','format=sql']);assert.equal(r.collection.branchIdentityVerified,true);assert.equal(r.promotionAllowed,false);assert.equal(r.sqlSchema,undefined);});
test('collector rejects a foreign project/branch before it ever requests schema',async()=>{let calls=0;await assert.rejects(collectSupplierSchema(target,async()=>{calls++;return{branch:{id:target.branchId,project_id:'foreign'}};}),/identity_mismatch/);assert.equal(calls,1);});
test('unrecognized target options and injected CLI routes never reach a child process',async()=>{assert.throws(()=>validateSchemaTarget({...target,sql:'DROP TABLE'}),/target_invalid/);assert.throws(()=>validateSchemaTarget({...target,projectId:'x;echo nope'}),/target_invalid/);await assert.rejects(readSchemaThroughCli('unused','/projects/p/branches/br-b',['format=json;echo bad']),/request_invalid/);});
test('collection budget expires rather than certifying a stale joined export',async()=>{const f=fixture();let ticks=0;await assert.rejects(collectSupplierSchema(target,async(p,q)=>!q.length?{branch:{id:target.branchId,project_id:target.projectId}}:q.includes('format=json')?f.jsonSchema:f.sqlSchema,{expectedBodies:f.expectedBodies,clock:()=>now+(ticks++?120001:0)}),/collection_timeout/);});
test('CLI needs explicit safe identity and module/output paths; duplicate/unknown flags fail',()=>{const base=['--project','project-123','--branch','br-main-123','--database','neondb','--output','report.json','--cli-module',process.execPath];assert.equal(parseSchemaPreflightArgs(base).project,'project-123');for(const args of [[],[...base,'--project','other'],[...base,'--execute','yes'],base.slice(0,-2)])assert.throws(()=>parseSchemaPreflightArgs(args));});
test('candidate expected routine bodies are read from actual later migrations including 0121',async()=>{const e=await loadExpectedSupplierBodies(new URL('../db/migrations',import.meta.url));assert.equal(Object.keys(e.bodies).length,new Set(SUPPLIER_SCHEMA_FEATURES.flatMap(f=>f.functions)).size);assert.ok(e.migrationFiles.at(-1).endsWith('0121_support_ticket_status_type_compatibility.sql'));assert.ok(Object.values(e.bodies).every(v=>/^[a-f0-9]{64}$/.test(v)));});

test('AS text in quoted or dollar-quoted defaults cannot masquerade as the routine body',()=>{
 const q="CREATE FUNCTION public.f(x text DEFAULT 'AS $$SELECT 1;$$')RETURNS integer LANGUAGE sql AS $body$SELECT 2;$body$;";
 const d='CREATE FUNCTION public.f(x text DEFAULT $arg$AS $$SELECT 1;$$$arg$)RETURNS integer LANGUAGE sql AS $body$SELECT 2;$body$;';
 for(const input of [q,d])assert.equal(observeSqlObjects(input).functions.get('public.f')[0].bodyHash,sha256('SELECT 2;'));
});
test('a missing database name never coerces to the string undefined',()=>{assert.throws(()=>validateSchemaTarget({projectId:'project-123',branchId:'br-main-123'}),/target_invalid/);});

test('existing output is refused before the CLI executable can run',async()=>{
 await assert.rejects(main(['--project','project-123','--branch','br-main-123','--database','neondb','--output',fileURLToPath(import.meta.url),'--cli-module',process.execPath]),/output_exists/);
});
