import assert from 'node:assert/strict';import test from 'node:test';
import{checkAdminWithPermission}from'../src/lib/auth.ts';import{makeSupplierQuoteHandlers}from'../src/lib/supplier-request-quote-http.ts';
const tenant='10000000-0000-4000-8000-000000000001',other='10000000-0000-4000-8000-000000000002',actor='20000000-0000-4000-8000-000000000001',sid='30000000-0000-4000-8000-000000000001',id='40000000-0000-4000-8000-000000000001',key='50000000-0000-4000-8000-000000000001';
const offer=()=>({currency:'USD',net_minor:10001,tax_minor:2100,shipping_minor:499,conditions:'Condiciones QA.',valid_until:'2026-10-01T12:00:00.000Z'});
const command=()=>({action:'issue',expected_revision:0,expected_request_revision:2,expected_review_revision:0,offer:offer(),reason:'Propuesta comercial.'});
const event=(patch={})=>({...offer(),id:key,revision:1,request_revision:3,quote_version:1,source_request_revision:2,review_revision:0,action:'issue',state:'offered',total_minor:12600,reason:command().reason,actor_id:actor,created_at:'2026-09-24T12:00:00.000Z',...patch});
const request=(patch={})=>({id,tenant_id:tenant,tenant_slug:'qa-a',title:'Proyecto QA',construction_id:'tt_bridge',quantity:125,pack_purpose:'production',notes:'Datos originales',status:'submitted',revision:3,quotation_revision:1,quotation_state:'offered',created_by:actor,updated_by:actor,submitted_by:actor,created_at:'2026-09-23T12:00:00.000Z',submitted_at:'2026-09-23T12:01:00.000Z',updated_at:'2026-09-24T12:00:00.000Z',order_id:null,review_summary:{state:'pending',revision:0,updated_at:null},...patch});
const result=(patch={})=>({ok:true,request:request(),revision:1,current:event(),history:[event()],count:1,truncated:false,next_before_revision:null,as_of:'2026-09-24T12:00:01.000Z',receipt:{idempotency_key:key,action:'issue',revision:1,request_revision:3,quote_version:1},idempotent_replay:false,...patch});
function session(patch={}){return{id:sid,userId:actor,email:'qa@example.invalid',label:'QA',role:'super-admin',tenantId:null,tenantSlug:null,permissions:['supplier_order.create'],deniedPermissions:[],mfaVerified:false,expiresAt:new Date(Date.now()+60000).toISOString(),rotatedCookieValue:null,setupCompleted:true,...patch};}
function fixture(options={}){const queries=[],permissions=[];const handlers=makeSupplierQuoteHandlers({enabled:()=>options.enabled!==false,authorize:(req,p)=>{permissions.push(p);return checkAdminWithPermission(req,p,options.resolver||(async()=>session(options.session)));},query:async(strings,...values)=>{const sql=strings.join('?');queries.push({sql,values});if(sql.includes('FROM public.tenants'))return[{id:tenant,slug:'qa-a'}];if(sql.includes('to_regprocedure'))return[{available:options.available!==false}];if(options.fail)throw Error('PRIVATE_SQL_CREDENTIAL');return[{result:options.result===null?null:options.result||result()}];}});return{queries,permissions,handlers};}
async function call(f,method='post',body=command(),query='?tenant=qa-a',headers={}){const req=new Request('http://localhost/admin/supplier-requests/'+id+'/quotation'+query,{method:method==='get'?'GET':'POST',headers:{authorization:'Bearer synthetic-local-session',...(method==='post'?{'content-type':'application/json','idempotency-key':key}:{}),...headers},...(method==='post'?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});const response=await f.handlers[method](req,id);assert.match(response.headers.get('cache-control'),/private.*no-store/);assert.equal(response.headers.get('referrer-policy'),'no-referrer');return{status:response.status,body:await response.json()};}
test('quote read remains available when writes are disabled; disabled mutation performs zero queries',async()=>{
 const f=fixture({enabled:false}),read=await call(f,'get');assert.equal(read.status,200);assert.equal(read.body.writes_enabled,false);assert.equal(read.body.current.total_minor,12600);
 const off=fixture({enabled:false});assert.equal((await call(off)).status,503);assert.equal(off.queries.length,0);
 const missing=fixture({available:false});assert.equal((await call(missing,'get')).status,503);assert.equal(missing.queries.length,2);
});
test('issuer operation carries only trusted actor/session/tenant and returns bounded public receipt',async()=>{
 const f=fixture(),r=await call(f);assert.equal(r.status,200);assert.deepEqual(f.permissions,['supplier_order.create']);const input=JSON.parse(f.queries.at(-1).values[0]);assert.deepEqual(input,{...command(),tenant_id:tenant,request_id:id,actor_id:actor,auth_session_id:sid,idempotency_key:key});assert.doesNotMatch(JSON.stringify(r),/auth_session_id|fingerprint|PRIVATE_SQL/);
});
test('company cannot issue/withdraw and superadmin cannot accept for the company',async()=>{
 const company={role:'operations-manager',tenantId:tenant,tenantSlug:'qa-a'};
 for(const action of ['issue','withdraw']){const f=fixture({session:company});assert.equal((await call(f,'post',{...command(),action,offer:action==='issue'?offer():null})).status,403);assert.equal(f.queries.length,2);}
 for(const action of ['accept','reject']){const f=fixture();assert.equal((await call(f,'post',{...command(),action,offer:null})).status,403);assert.equal(f.queries.length,2);}
});
for(const patch of [{role:'supplier-operator',permissions:['*']},{role:'viewer'},{role:'api-integration'},{role:'operations-manager',tenantId:tenant,tenantSlug:'qa-a',permissions:[]},{deniedPermissions:['supplier_order.create']},{deniedPermissions:['supplier_orders:write']}])test('real auth gate before quote SQL '+JSON.stringify(patch),async()=>{for(const method of ['get','post']){const f=fixture({session:patch});assert.ok([401,403].includes((await call(f,method)).status));assert.equal(f.queries.length,0);}});
test('duplicate selectors, invalid cursor and cross-tenant commands cannot access quotes',async()=>{
 for(const query of ['?tenant=qa-a&tenant=qa-a','?tenant=qa-a&before_revision=0','?tenant=qa-a&before_revision=2&before_revision=2','?tenant=qa-a&extra=true']){const f=fixture();assert.equal((await call(f,'get',null,query)).status,400);assert.equal(f.queries.length,0);}
 const foreign=fixture({session:{role:'operations-manager',tenantId:tenant,tenantSlug:'qa-a'}});assert.equal((await call(foreign,'get',null,'?tenant=qa-b')).status,403);assert.equal(foreign.queries.length,0);
});
test('oversized, invalid JSON, secret conditions, unknown fields or wrong MIME are refused before quote mutation',async()=>{
 for(const [body,headers,status]of [['x'.repeat(33000),{},413],['{bad',{},400],[{...command(),actor_id:actor},{},400],[{...command(),offer:{...offer(),conditions:'api_key=synthetic-private-value'}},{},400],[command(),{'content-type':'text/plain'},415],[command(),{'idempotency-key':'bad'},400]]){const f=fixture();assert.equal((await call(f,'post',body,undefined,headers)).status,status);assert.equal(f.queries.length,2);}
});
for(const [reason,status]of [['supplier_quote_scope_forbidden',403],['supplier_request_not_found',404],['supplier_request_not_submitted',409],['supplier_quote_idempotency_conflict',409],['supplier_quote_revision_conflict',409],['supplier_quote_expired',409],['supplier_request_information_required',409]])test('stable quote refusal '+reason,async()=>assert.equal((await call(fixture({result:{ok:false,reason}}))).status,status));
test('foreign scope, wrong totals and malformed receipts cannot become successful quotes',async()=>{
 for(const patch of [{request:request({tenant_id:other})},{current:event({total_minor:1})},{history:[]},{receipt:{...result().receipt,idempotency_key:id}},{receipt:{...result().receipt,request_revision:2}},{receipt:{...result().receipt,revision:2}},{idempotent_replay:undefined},{current:event({actor_id:other}),history:[event({actor_id:other})]}])assert.equal((await call(fixture({result:result(patch)}))).status,503);
 const failed=await call(fixture({fail:true}));assert.equal(failed.status,503);assert.doesNotMatch(JSON.stringify(failed),/PRIVATE/);
});
test('revoked or failed sessions perform no SQL and do not leak resolver errors',async()=>{for(const resolver of [async()=>null,async()=>{throw Error('PRIVATE_SESSION');}]){const f=fixture({resolver}),r=await call(f);assert.ok([401,503].includes(r.status));assert.equal(f.queries.length,0);assert.doesNotMatch(JSON.stringify(r),/PRIVATE/);}});

test('technical preflight rejects a quoted request before proceeding unless its exact current quote is accepted',async()=>{
 const {validateSupplierRequestConversion}=await import('../src/lib/supplier-request-store.ts');const principal={scope:'super_admin',userId:actor,sessionId:sid},technical={quantity:125,purpose:'production',carrier:'ntag424_dna_tt',chip:'NTAG424_DNA_TT',material:'tagtamper_tail'};
 for(const state of ['offered','rejected','withdrawn',null]){let reads=0;const query=async(strings)=>{reads++;return strings.join('').includes('supplier_request_quote_events')?(state?[{state,revision:1}]:[]):[request()];};await assert.rejects(validateSupplierRequestConversion({id,revision:3},principal,{id:tenant,slug:'qa-a'},technical,query),/supplier_request_quote_acceptance_required/);assert.equal(reads,2);}
 const query=async(strings)=>strings.join('').includes('supplier_request_quote_events')?[{state:'accepted',revision:1}]:[request({quotation_state:'accepted'})];assert.equal((await validateSupplierRequestConversion({id,revision:3},principal,{id:tenant,slug:'qa-a'},technical,query)).id,id);
});
