// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title NexidTraceabilityNFT
 * @notice NFT contract for NTAG 424 DNA digital twins.
 * @dev Store only chip UID hash (never raw chip secret/UID) to preserve privacy.
 */
contract NexidTraceabilityNFT is ERC721URIStorage, Ownable {
    error EmptyChipHash();
    error ChipAlreadyBound();
    error InvalidToken();
    error UnauthorizedMinter();

    uint256 private _nextTokenId = 1;

    // tokenId => hash(uid || salt/version) generated by trusted backend
    mapping(uint256 => string) public chipUidHashByTokenId;
    // hash(uid) => tokenId+1 (0 = not minted) to enforce 1:1 bind
    mapping(string => uint256) private _tokenByChipHash;
    // tokenId => mutable traceability metadata URI (JSON/IPFS pointer)
    mapping(uint256 => string) public traceabilityUriByTokenId;
    // tokenId => optional asset/business ref (BID:UID hash / SKU batch ref)
    mapping(uint256 => string) public assetRefByTokenId;
    // backend/executor wallets allowed to mint without owning contract admin.
    mapping(address => bool) public authorizedMinters;

    event DigitalTwinMinted(
        uint256 indexed tokenId,
        address indexed to,
        string chipUidHash,
        string assetRef,
        string tokenUri
    );
    event TraceabilityUpdated(uint256 indexed tokenId, string traceabilityUri);
    event MinterUpdated(address indexed minter, bool enabled);

    constructor(address initialOwner, address initialMinter) ERC721("Nexid Digital Twin", "NXDT") Ownable(initialOwner) {
        if (initialMinter != address(0)) {
            authorizedMinters[initialMinter] = true;
            emit MinterUpdated(initialMinter, true);
        }
    }

    modifier onlyOwnerOrMinter() {
        if (owner() != msg.sender && !authorizedMinters[msg.sender]) revert UnauthorizedMinter();
        _;
    }

    function setMinter(address minter, bool enabled) external onlyOwner {
        authorizedMinters[minter] = enabled;
        emit MinterUpdated(minter, enabled);
    }

    function mintWithChipHash(
        address to,
        string calldata chipUidHash,
        string calldata tokenUri,
        string calldata assetRef
    ) external onlyOwnerOrMinter returns (uint256 tokenId) {
        if (bytes(chipUidHash).length == 0) revert EmptyChipHash();
        if (_tokenByChipHash[chipUidHash] != 0) revert ChipAlreadyBound();

        tokenId = _nextTokenId;
        _nextTokenId += 1;

        _safeMint(to, tokenId);
        _setTokenURI(tokenId, tokenUri);

        chipUidHashByTokenId[tokenId] = chipUidHash;
        assetRefByTokenId[tokenId] = assetRef;
        _tokenByChipHash[chipUidHash] = tokenId;

        emit DigitalTwinMinted(tokenId, to, chipUidHash, assetRef, tokenUri);
    }

    function updateTraceability(uint256 tokenId, string calldata traceabilityUri) external onlyOwner {
        if (_ownerOf(tokenId) == address(0)) revert InvalidToken();
        traceabilityUriByTokenId[tokenId] = traceabilityUri;
        emit TraceabilityUpdated(tokenId, traceabilityUri);
    }

    function tokenByChipHash(string calldata chipUidHash) external view returns (uint256) {
        return _tokenByChipHash[chipUidHash];
    }
}
