import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3452',api='http://127.0.0.1:4752',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,realHistoryHandler:true,realPostgres:true,syntheticAuthentication:true,checks:[],visual:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json(),root=p=>p.locator('[data-testid="consumer-history"]:visible');
async function open(who='user',width=1440){const c=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce',locale:'es-AR',timezoneId:'America/Argentina/Mendoza',serviceWorkers:'block',permissions:['clipboard-read','clipboard-write']});if(who)await c.addCookies([{name:'history_qa',value:who,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await c.newPage(),errors=[],writes=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(['POST','PATCH','DELETE'].includes(r.method())&&r.url().includes('/api/'))writes.push(new URL(r.url()).pathname);});await p.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await p.goto(base+'/me/taps',{waitUntil:'load',timeout:90000});return {p,c,errors,writes};}
async function filters(p){const d=root(p).getByTestId('history-filter-panel');if(!await d.evaluate(e=>e.open))await d.locator('summary').first().click();}
async function ready(p,n){await root(p).getByRole('heading',{name:'Página '+n,exact:true}).waitFor();}
try{
 await fetch(api+'/qa-mode',{method:'POST'});const user=await open(),p=user.p;await ready(p,1);const items=root(p).getByRole('list',{name:'Lecturas guardadas de mi cuenta'});assert.equal(await items.getByRole('listitem').count(),25);assert.match(await items.innerText(),/sin autenticación NFC/);assert.match(await items.innerText(),/Sello abierto reportado/);
 const before=(await state()).calls.length;await root(p).getByRole('searchbox',{name:'Buscar en esta página'}).fill('no-match');assert.equal(await root(p).getByRole('button',{name:'Página siguiente de mis lecturas'}).isDisabled(),false);await root(p).getByRole('searchbox',{name:'Buscar en esta página'}).fill('');await root(p).getByRole('button',{name:'Horarios UTC',exact:true}).click();assert.match(await items.innerText(),/hora local/);assert.ok((await root(p).getByRole('status').innerText()).includes(await p.evaluate(()=>Intl.DateTimeFormat().resolvedOptions().timeZone)));await root(p).getByRole('button',{name:/Copiar referencia/}).first().click();await root(p).getByText('Referencia copiada',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>navigator.clipboard.readText()),'9007199254741229');assert.equal((await state()).calls.length,before);report.checks.push('Local search, device time and copying exact bigint references make no history request or new TAP');
 const first=await items.getByRole('link',{name:/Abrir lectura/}).evaluateAll(a=>a.map(e=>e.getAttribute('href')));await root(p).getByRole('button',{name:'Página siguiente de mis lecturas'}).click();await ready(p,2);const second=await items.getByRole('link',{name:/Abrir lectura/}).evaluateAll(a=>a.map(e=>e.getAttribute('href')));assert.ok(second.every(x=>!first.includes(x)));await root(p).getByRole('button',{name:'Página anterior de mis lecturas'}).click();await ready(p,1);assert.deepEqual(await items.getByRole('link',{name:/Abrir lectura/}).evaluateAll(a=>a.map(e=>e.getAttribute('href'))),first);report.checks.push('Forward/backward personal pages retain their order and do not repeat rows across boundaries');
 await filters(p);await root(p).getByRole('textbox',{name:'Referencia de lectura'}).fill('9007199254740993');assert.equal(await root(p).getByRole('listitem').count(),0);await root(p).getByRole('button',{name:'Consultar historial',exact:true}).click();await ready(p,1);assert.equal(await items.getByRole('listitem').count(),1);assert.equal(await items.getByRole('link',{name:'Abrir lectura 9007199254740993'}).getAttribute('href'),'/me/taps/9007199254740993');assert.ok(!(await items.innerText()).includes('OTHER_PERSON'));report.checks.push('Exact reference search finds a personal reading outside the former 200-row sample without exposing another consumer');
 await filters(p);await root(p).getByRole('button',{name:'Quitar filtros'}).click();await root(p).getByRole('combobox',{name:'Empresa',exact:true}).selectOption('wine-qa');await root(p).getByRole('button',{name:'Consultar historial',exact:true}).click();await ready(p,1);assert.ok(!(await items.innerText()).includes('Agro de prueba'));report.checks.push('Company filter preserves personal-account scope instead of querying all company scans');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1000});await p.evaluate(t=>{document.documentElement.dataset.theme=t;document.documentElement.classList.toggle('theme-light',t==='light');document.documentElement.classList.toggle('theme-dark',t==='dark');window.scrollTo(0,0);},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.addScriptTag({content:axe});const v=await p.evaluate(async()=>{const r=await axe.run('[data-testid="consumer-history"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(x=>({id:x.id,impact:x.impact,targets:x.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`history-${width}-${theme}.png`),fullPage:false});assert.deepEqual(v.filter(x=>['serious','critical'].includes(x.impact)),[]);report.visual.push({width,theme,violations:v});}
 await filters(p);await root(p).getByText('Filtrar por fecha en que se guardó',{exact:true}).click();await root(p).getByLabel('Desde · UTC',{exact:true}).fill('2026-08-31');await root(p).getByLabel('Hasta · inclusive UTC',{exact:true}).fill('2026-08-31');await root(p).getByRole('button',{name:'Consultar historial',exact:true}).click();await ready(p,1);await root(p).getByRole('heading',{name:'Sin lecturas en esta selección'}).waitFor();await filters(p);await root(p).getByRole('button',{name:'Quitar filtros'}).click();await root(p).getByRole('button',{name:'Consultar historial',exact:true}).click();await ready(p,1);await root(p).getByRole('button',{name:'Continuar con más lecturas'}).click();await ready(p,2);await root(p).getByRole('button',{name:'Página anterior de mis lecturas'}).click();await ready(p,1);report.checks.push('UTC saved-date filters and the bottom continuation control navigate without making a new physical reading');
 await fetch(api+'/qa-mode?failed=1',{method:'POST'});await root(p).getByRole('button',{name:'Página siguiente de mis lecturas'}).click();await root(p).getByText('El historial todavía no está confirmado',{exact:true}).waitFor();assert.equal(await root(p).getByRole('listitem').count(),0);await fetch(api+'/qa-mode',{method:'POST'});await root(p).getByRole('button',{name:'Reintentar consulta'}).click();await ready(p,2);report.checks.push('Failed page lookup removes old rows and can retry the same position');
 await fetch(api+'/qa-mode?expired=1',{method:'POST'});await root(p).getByRole('button',{name:'Página siguiente de mis lecturas'}).click();await root(p).getByRole('heading',{name:'Iniciá sesión para continuar'}).waitFor();assert.equal(await root(p).getByRole('listitem').count(),0);await fetch(api+'/qa-mode',{method:'POST'});report.checks.push('Session expiration clears private results and offers a real account login, not fake empty history');
 const empty=await open('empty',390);await ready(empty.p,1);await root(empty.p).getByRole('heading',{name:'Sin lecturas en esta selección'}).waitFor();await filters(empty.p);assert.equal(await root(empty.p).getByRole('combobox',{name:'Empresa',exact:true}).locator('option').count(),1);const forbidden=await empty.c.request.get(base+'/api/consumer/taps/history?consumerId=10000000-0000-4000-8000-000000000001');assert.equal(forbidden.status(),400);const anonymous=await open(null);await anonymous.p.waitForURL(u=>u.pathname==='/login');report.checks.push('Empty accounts remain private, actor injection is rejected and anonymous navigation returns to login');
 assert.deepEqual([...user.errors,...empty.errors],[]);assert.deepEqual([...user.writes,...empty.writes],[]);for(const x of [user,empty,anonymous])await x.c.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,10000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
