// Actual Next pages and notice reader backed by real PostgreSQL. Consumer identity and SUN results are explicit local fixtures.
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3187',api='http://127.0.0.1:4287',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,actualNoticeService:true,actualPostgres:true,syntheticConsumerAndSun:true,checks:[],visual:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json(),notices=s=>s.calls.filter(c=>c.path==='/public/product-notices/v2').length;
async function open(auth=true,width=1440){const context=await browser.newContext({viewport:{width,height:980},locale:'es-AR',reducedMotion:'reduce',serviceWorkers:'block'});if(auth)await context.addCookies([{name:'consumer_qa',value:'local',url:base,httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage(),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(['POST','PATCH','PUT','DELETE'].includes(r.method())&&r.url().includes('/api/')&&!r.url().includes('/api/sun/locale'))writes.push(new URL(r.url()).pathname);});await page.route('**/*',r=>{const u=new URL(r.request().url());return ['localhost','127.0.0.1'].includes(u.hostname)||u.protocol==='data:'||u.protocol==='blob:'?r.continue():r.abort();});await page.addInitScript(()=>{window.__locationCalls=0;Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition:()=>{window.__locationCalls++;throw Error('Unexpected automatic location request');}}});});return {context,page,errors,writes};}
async function theme(p,value){await p.evaluate(value=>{document.documentElement.dataset.theme=value;document.documentElement.classList.toggle('theme-light',value==='light');document.documentElement.classList.toggle('theme-dark',value==='dark');},value);}
async function assess(p,selector,name,width,value){await p.evaluate(()=>window.scrollTo(0,0));await p.evaluate(()=>new Promise(requestAnimationFrame));await p.addScriptTag({content:axe});const violations=await p.evaluate(async selector=>{const result=await axe.run(selector,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return result.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));},selector);await p.screenshot({path:join(out,`${name}-${width}-${value}.png`),fullPage:name!=='sun-signals'});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({name,width,theme:value,violations});}
try{
 const user=await open(),p=user.page;const before=notices(await state());await p.goto(base+'/me/products',{waitUntil:'load',timeout:90000});await p.getByTestId('consumer-product-library').waitFor();assert.equal(await p.getByRole('button',{name:/Abrir ficha y avisos de /}).count(),12);await p.getByRole('button',{name:'Mostrar más productos',exact:false}).click();assert.equal(await p.getByRole('button',{name:/Abrir ficha y avisos de /}).count(),14);
 await p.getByRole('searchbox',{name:'Buscar producto, marca o lote'}).fill('reserva');assert.equal(await p.getByRole('button',{name:/Abrir ficha y avisos de /}).count(),1);assert.equal(notices(await state()),before);report.checks.push('Account product list filters and paginates locally without notice queries or new taps');
 await p.getByRole('searchbox',{name:'Buscar producto, marca o lote'}).fill('QA');for(const [width,value] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:980});await theme(p,value);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await assess(p,'[data-testid="consumer-product-library"]','product-library',width,value);}await p.getByRole('searchbox',{name:'Buscar producto, marca o lote'}).fill('reserva');
 await p.getByRole('button',{name:'Abrir ficha y avisos de Vino reserva QA',exact:true}).click();const dialog=p.getByRole('dialog');await dialog.getByText('Sin avisos de retiro publicados en esta consulta.',{exact:true}).waitFor();assert.match(await dialog.innerText(),/NO ES UN TAP NUEVO/);assert.ok(notices(await state())>before);report.checks.push('Opening the saved product reads current notices, separate from its stored closed-seal reading');
 await fetch(api+'/qa-publish',{method:'POST'});await dialog.getByRole('button',{name:'Actualizar avisos',exact:true}).click();await dialog.getByRole('heading',{name:'Aviso vigente de calidad QA',exact:true}).waitFor();assert.match(await dialog.innerText(),/Sello cerrado reportado/);assert.match(await dialog.innerText(),/RETIRO DE LOTE/);assert.ok(!(await dialog.innerText()).includes('PRIVATE_'));report.checks.push('A later database-published recall appears beside the historical valid reading without overwriting either');
 for(const [width,value] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:980});await theme(p,value);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await assess(p,'dialog[open]','saved-product',width,value);}
 await fetch(api+'/qa-mode?notices=failed',{method:'POST'});await dialog.getByRole('button',{name:'Actualizar avisos',exact:true}).click();await dialog.getByText('No se pudieron consultar los avisos del lote.',{exact:false}).waitFor();assert.equal(await dialog.getByRole('heading',{name:'Aviso vigente de calidad QA'}).count(),1);report.checks.push('Failed refresh retains the known product warning instead of displaying a safe result');
 await p.keyboard.press('Escape');await p.getByRole('dialog').waitFor({state:'hidden'});await p.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Abrir ficha y avisos de Vino reserva QA');await fetch(api+'/qa-mode',{method:'POST'});
 await p.getByRole('searchbox',{name:'Buscar producto, marca o lote'}).fill('oliva');await p.getByRole('button',{name:'Abrir ficha y avisos de Aceite de oliva QA',exact:true}).click();await dialog.getByText('Sin avisos de retiro publicados en esta consulta.',{exact:true}).waitFor();assert.equal(await dialog.getByRole('heading',{name:'Aviso vigente de calidad QA'}).count(),0);await p.keyboard.press('Escape');report.checks.push('Switching products never carries another tenant warning into the next product');
 await p.goto(base+'/me/products?focus=900001',{waitUntil:'load'});await p.getByRole('dialog').getByRole('heading',{name:'Vino reserva QA',exact:true}).waitFor();await p.keyboard.press('Escape');await p.goto(base+'/me/products?focus=999999',{waitUntil:'load'});await p.getByTestId('consumer-product-library').waitFor();assert.equal(await p.locator('dialog[open]').count(),0);report.checks.push('Account continuation resolves only a reading already present in that account');
 await p.goto(base+'/me/taps/900001',{waitUntil:'load'});const count=notices(await state());await p.getByRole('button',{name:'Consultar avisos actuales del producto'}).click();await p.getByRole('heading',{name:'Aviso vigente de calidad QA'}).waitFor();assert.ok(notices(await state())>count);report.checks.push('Private saved-reading page exposes current notices only after an explicit request');
 const phone=await open(false,390),s=phone.page;
 await s.goto(base+'/sun?bid=TT-OPEN-QA',{waitUntil:'load',timeout:90000});await s.getByTestId('passport-essential-signals').waitFor();await s.getByRole('heading',{name:'Aviso vigente de calidad QA',exact:true}).waitFor();const signal=s.getByTestId('passport-essential-signals');assert.match(await signal.innerText(),/Verificada/);assert.match(await signal.innerText(),/Abierto/);assert.match(await signal.innerText(),/Aviso vigente/);assert.equal(await s.evaluate(()=>window.__locationCalls),0);report.checks.push('SUN shows chip, opened seal and active product notice as three independent signals');
 const countsBefore=notices(await state());await s.getByRole('button',{name:'Actualizar avisos',exact:true}).click();await s.getByTestId('product-notices').filter({has:s.getByText('Aviso vigente de calidad QA',{exact:true})}).waitFor();await s.waitForTimeout(400);assert.equal(notices(await state()),countsBefore+1);report.checks.push('Warning and first-screen signals share one notice read per manual refresh');
 await theme(s,'light');await assess(s,'[data-testid="passport-essential-signals"]','sun-signals',390,'light');await theme(s,'dark');await assess(s,'[data-testid="passport-essential-signals"]','sun-signals',390,'dark');
 const readsBeforeLanguage=notices(await state());await s.locator('.locale-switcher select').selectOption('en');await signal.getByText('Verified',{exact:true}).waitFor();await s.locator('.locale-switcher select').selectOption('pt-BR');await signal.getByText('Lacre',{exact:true}).waitFor();await s.locator('.locale-switcher select').selectOption('es-AR');await signal.getByText('Precinto',{exact:true}).waitFor();assert.equal(notices(await state()),readsBeforeLanguage);report.checks.push('Language changes preserve the same evidence and notice query');
 for(const [url,label] of [['/sun?qr=1&bid=QR-QA','Código QR'],['/sun?qr=1&bid=GS1-QA&carrier=gs1_digital_link','GS1 Digital Link']]){await s.goto(base+url,{waitUntil:'load'});await signal.waitFor();assert.match(await signal.innerText(),/Sin autenticación NFC/);assert.match(await signal.innerText(),/No evaluado/);assert.ok((await signal.innerText()).includes(label));}report.checks.push('QR and GS1 display their identity channel without claiming NFC authentication or seal evidence');
 await s.goto(base+'/sun?bid=TT-HISTORICAL-QA',{waitUntil:'load'});await signal.waitFor();assert.match(await signal.innerText(),/Registro histórico/);report.checks.push('Snapshot presentation is visibly historical and does not refresh cryptographic freshness');
 await s.locator('[data-testid="product-notices"][data-notice-state="published"]').waitFor();const requestsBeforeDemo=notices(await state());await s.goto(base+'/sun',{waitUntil:'load'});await signal.waitFor();assert.match(await signal.innerText(),/Ejemplo ilustrativo/);assert.equal(notices(await state()),requestsBeforeDemo);report.checks.push('Public demo remains explicitly simulated and makes no production-notice request');
 await fetch(api+'/qa-lift',{method:'POST'});await p.goto(base+'/me/products?focus=900001',{waitUntil:'load'});await p.getByRole('dialog').getByText('AVISO LEVANTADO',{exact:true}).waitFor();await p.getByRole('dialog').getByText('Ver aviso anterior',{exact:true}).click();assert.match(await p.getByRole('dialog').innerText(),/No utilizar las unidades/);report.checks.push('Independently lifted database notice retains visible resolution and earlier warning');
 await p.keyboard.press('Escape');await fetch(api+'/qa-mode?products=failed',{method:'POST'});await p.reload({waitUntil:'load'});await p.getByRole('heading',{name:'No pudimos cargar tus productos.'}).waitFor();assert.equal(await p.getByRole('heading',{name:'Todavía no hay productos guardados.'}).count(),0);await fetch(api+'/qa-mode?products=empty',{method:'POST'});await p.reload({waitUntil:'load'});await p.getByRole('heading',{name:'Todavía no hay productos guardados.'}).waitFor();await fetch(api+'/qa-mode',{method:'POST'});
 const anon=await open(false);await anon.page.goto(base+'/me/products',{waitUntil:'load'});await anon.page.waitForURL(url=>url.pathname==='/login',{timeout:20000});await anon.context.close();report.checks.push('Authenticated source errors stay distinct from empty accounts; anonymous accounts cannot read the collection');
 assert.deepEqual(user.errors,[]);assert.deepEqual(phone.errors,[]);assert.deepEqual(user.writes,[]);assert.deepEqual(phone.writes,[]);assert.equal((await state()).tagConfigUnchanged,true);report.checks.push('No business writes, auto-geolocation, tag/counter/TT changes or blockchain calls occurred in the browser flow');await user.context.close();await phone.context.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,12000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
