// Production catalogue component; bounded synthetic loopback inquiry receipts only.
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { build } from 'esbuild';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
const web=fileURLToPath(new URL('../',import.meta.url)),output=resolve(process.env.QA_OUTPUT||'artifacts/consumer-marketplace-context');await mkdir(output,{recursive:true});
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
const items=[{id:'inquiry-one',title:'Producto de ensayo uno',tenant_slug:'tenant-qa',stock_status:'active',request_to_buy_enabled:true},{id:'inquiry-two',title:'Producto de ensayo dos',tenant_slug:'tenant-qa',stock_status:'active',request_to_buy_enabled:true}];
const fixture=`import React from'react';import{createRoot}from'react-dom/client';import{MarketplaceGridClient}from'./src/app/me/marketplace/marketplace-grid-client';import shell from'./src/app/me/_components/portal-shell.module.css';const mode=new URLSearchParams(location.search).get('mode');createRoot(document.getElementById('app')).render(<main className={shell.portal} style={{padding:16,boxSizing:'border-box'}}><h1>Consultas de catálogo · ensayo local</h1><p>Datos sintéticos. No realiza compras, pagos ni operaciones reales.</p><MarketplaceGridClient items={${JSON.stringify(items)}} {...(mode==='global'?{}:{postTapEventId:mode==='invalid'?'01':'715'})}/></main>);`;
const bundled=await build({stdin:{contents:fixture,resolveDir:web,loader:'tsx'},bundle:true,write:false,outfile:'fixture.js',format:'esm',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},logLevel:'error'});
const globalCss=await postcss([tailwind()]).process(await readFile(join(web,'src/app/globals.css'),'utf8'),{from:join(web,'src/app/globals.css')}),js=bundled.outputFiles.find(f=>f.path.endsWith('.js')),css=(bundled.outputFiles.find(f=>f.path.endsWith('.css'))?.text||'')+'\n'+globalCss.css;
const server=createServer((req,res)=>{if(req.method!=='GET'){res.writeHead(405);return res.end();}const path=new URL(req.url,'http://fixture.invalid').pathname;if(path==='/fixture.js'){res.setHeader('content-type','text/javascript');return res.end(js.contents);}if(path==='/fixture.css'){res.setHeader('content-type','text/css');return res.end(css);}if(path==='/favicon.ico'){res.writeHead(204);return res.end();}res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><html lang='es-AR'><head><title>Consultas · ensayo local</title><meta name='viewport' content='width=device-width,initial-scale=1'><link rel='stylesheet' href='/fixture.css'><style>body{margin:0;font:16px/1.5 system-ui}h1{font-size:24px}</style></head><body><div id='app'></div><script type='module' src='/fixture.js'></script></body></html>`);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
const report={localOnly:true,actualProductionComponentAndCss:true,actualNextServer:false,syntheticInquiryOnly:true,realBusinessWrites:0,realPurchaseCertified:false,physicalTapMeasured:false,errors:[],externalRequests:[],geolocationCalls:0,checks:[],views:[],sourceHashes:{}};
for(const path of['src/app/me/marketplace/page.tsx','src/app/me/marketplace/marketplace-grid-client.tsx','src/app/me/marketplace/marketplace-request.ts','src/app/me/marketplace/marketplace.module.css'])report.sourceHashes[path]=createHash('sha256').update(await readFile(join(web,path))).digest('hex');
const check=(value,name)=>{report.checks.push({name,passed:Boolean(value)});assert.ok(value,name);};
try{for(const width of[320,390,768,1280])for(const theme of['light','dark'])for(const mode of['context','global','withdrawn','invalid']){
 const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce',serviceWorkers:'block'}),page=await context.newPage(),calls=[],label=`${width}/${theme}/${mode}`;page.setDefaultTimeout(10000);page.on('pageerror',e=>report.errors.push(e.message));
 await page.addInitScript(theme=>{document.addEventListener('DOMContentLoaded',()=>document.documentElement.setAttribute('data-theme',theme),{once:true});window.__gpsCalls=0;Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(){window.__gpsCalls++;}}});},theme);
 await page.route('**/*',async route=>{const r=route.request(),url=new URL(r.url());if(url.origin!==origin){report.externalRequests.push(url.hostname);return route.abort();}if(url.pathname.startsWith('/api/marketplace/')){calls.push({path:url.pathname,method:r.method(),body:r.postDataJSON()});const status=mode==='withdrawn'?409:200;return route.fulfill({status,contentType:'application/json',body:JSON.stringify({ok:status===200,error:status===409?'marketplace_configuration_changed':undefined,request_mode:'request_only',fulfills_scanned_unit:false})});}return route.continue();});
 await page.goto(origin+'/?mode='+mode,{waitUntil:'networkidle'});const grid=page.locator('[data-marketplace-catalog]'),card=id=>grid.locator(`[data-marketplace-product="${id}"]`),list=page.getByRole('complementary',{name:'Lista de solicitudes'});
 if(mode==='invalid'){check(await card('inquiry-one').getByRole('button',{name:'Solicitar contacto',exact:true}).isDisabled(),label+': invalid event is inert');check(calls.length===0,label+': no downgrade to global');}
 else{await card('inquiry-one').getByRole('button',{name:'Agregar a la lista',exact:true}).click();await card('inquiry-two').getByRole('button',{name:'Agregar a la lista',exact:true}).click();await list.getByRole('button',{name:'Enviar solicitudes',exact:true}).click();
  if(mode==='withdrawn'){await grid.getByText('Las consultas desde esta lectura ya no están disponibles. Tu lista se conserva en esta pantalla.',{exact:true}).waitFor();check(calls.length===1,label+': withdrawal stops remaining contextual requests');check(await list.getByText('Producto de ensayo uno',{exact:true}).count()===1&&await list.getByText('Producto de ensayo dos',{exact:true}).count()===1,label+': full draft preserved');check(await list.getByRole('button',{name:'Enviar solicitudes',exact:true}).isDisabled(),label+': no repeat after withdrawal');}
  else{await list.getByText(/2 solicitudes registradas/).waitFor();check(calls.length===2,label+': one explicit inquiry per item');}
  check(calls.every(call=>call.method==='POST'&&(mode==='global'?!Object.hasOwn(call.body,'postTapEventId'):call.body.postTapEventId==='715')&&!Object.hasOwn(call.body,'fresh_token')),label+': exact contextual attribution, independent global body, no NFC assertion');
 }
 check(!/Compra confirmada|Pago realizado|Sumaste .*puntos/.test(await grid.innerText()),label+': no fabricated purchase or points');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),label+': no overflow');
 check(await grid.locator('button,a,input').evaluateAll(elements=>elements.filter(el=>el.getClientRects().length).every(el=>el.getBoundingClientRect().height>=44)),label+': controls have 44px targets');
 await page.addScriptTag({content:axe});const a11y=await page.evaluate(async()=>{const r=await axe.run('main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return{violations:r.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),incomplete:r.incomplete.map(v=>v.id)};});report.views.push({width,theme,mode,calls,...a11y});check(a11y.violations.length===0,label+': zero axe violations');await page.screenshot({path:join(output,`${mode}-${width}-${theme}.png`),fullPage:true});report.geolocationCalls+=await page.evaluate(()=>window.__gpsCalls);await context.close();
}check(report.errors.length===0,'zero browser exceptions');check(report.externalRequests.length===0,'zero external requests');check(report.geolocationCalls===0,'zero GPS');report.status='passed';}
finally{if(!report.status)report.status='failed';await writeFile(join(output,'report.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));}
console.log(JSON.stringify({checks:report.checks.length,views:report.views.length,status:report.status,output}));
