import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
const require=createRequire(import.meta.url),style=new Proxy({},{get:(_,p)=>p});
function load(path,overrides={}){const raw=readFileSync(new URL('../src/'+path,import.meta.url),'utf8');const m={exports:{}};const js=ts.transpileModule(raw,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;new Function('require','module','exports',js)(key=>key in overrides?overrides[key]:require(key),m,m.exports);return m.exports;}
const summary=load('lib/passport-evidence-summary.ts'),library=load('app/me/products/product-library-model.ts'),model=load('app/me/_components/consumer-home-model.ts');
const source=(notices=[],hasMore=false)=>({enabled:true,loading:false,failed:false,value:{notices,hasMore}});
test('an empty, failed or unqueried response never implies product safety',()=>{assert.equal(summary.publicNoticeSignal(null),'not_checked');assert.equal(summary.publicNoticeSignal({...source(),loading:true}),'checking');assert.equal(summary.publicNoticeSignal({...source(),failed:true}),'unknown');assert.equal(summary.publicNoticeSignal({...source(),value:null}),'unknown');assert.equal(summary.publicNoticeSignal(source()),'none');});
test('an active warning survives failed refresh and closed operational follow-up',()=>{const s=source([{noticeState:'active',trackingState:'closed'}]);assert.equal(summary.publicNoticeSignal(s),'warning');assert.equal(summary.publicNoticeSignal({...s,failed:true}),'stale_warning');assert.equal(summary.publicNoticeSignal({...s,loading:true}),'stale_warning');});
test('lifted notice is not absence of notices and an incomplete list is not a clean result',()=>{assert.equal(summary.publicNoticeSignal(source([{noticeState:'lifted'}])),'lifted');assert.equal(summary.publicNoticeSignal(source([{noticeState:'lifted'}],true)),'more');assert.equal(summary.publicNoticeSignal(source([{noticeState:'lifted'},{noticeState:'active'}])),'warning');});
test('carrier presentation never upgrades QR basic NFC or UHF to cryptographic NFC',()=>{for(const [code,expected] of [['qr_basic','qr'],['gs1_digital_link','gs1'],['ntag213','basic_nfc'],['uhf_rfid','uhf'],['ntag424_dna_tt','tagtamper'],['ntag424_dna','secure_nfc'],['new-chip','unknown']])assert.equal(summary.evidenceCarrier(code,false),expected);assert.equal(summary.evidenceCarrier('gs1_digital_link',true),'gs1');assert.equal(summary.evidenceCarrier('ntag424_dna_tt',true),'qr');});
test('public notice scope uses validated product metadata, not query-injected paths',()=>{assert.deepEqual(library.publicProductScope({tenantSlug:'company-a',batch:'LOT-10'}),{tenant:'company-a',bid:'LOT-10'});for(const v of [null,'../admin','company/other','<script>'])assert.equal(library.publicProductScope({tenantSlug:v,batch:'LOT-10'}),null);assert.equal(library.publicProductScope({tenantSlug:'company-a',batch:'L/1'}),null);});
const products=model.buildHomeProductsSource({ok:true,items:[{product_name:'Café orgánico',tenant_slug:'farm',brand_name:'Campo',bid:'L1',latest_tap_event_id:'9007199254740993',latest_tap_at:'2026-09-19T13:00:00Z'},{product_name:'Aceite de oliva',tenant_slug:'olive',bid:'L2',latest_tap_event_id:'9007199254740994',latest_tap_at:'2026-09-18T13:00:00Z'}]}).data;
test('search sort and filters operate on loaded products without changing identity or sources',()=>{const before=JSON.stringify(products);assert.equal(library.filterProductLibrary(products,'cafe','','original')[0].index,0);assert.equal(library.filterProductLibrary(products,'','olive','original')[0].index,1);assert.equal(library.filterProductLibrary(products,'','','name')[0].index,1);assert.equal(library.filterProductLibrary(products,'','','recent')[0].index,0);assert.equal(JSON.stringify(products),before);});
test('deep-link focus resolves only an exact single reference in the current account list',()=>{assert.equal(library.productFocus(products,'9007199254740993'),0);assert.equal(library.productFocus(products,'9007199254740992'),null);assert.equal(library.productFocus(products,'../foreign'),null);assert.equal(library.productFocus([products[0],products[0]],'9007199254740993'),null);});
function signals(code,overrides={}){const part=load('app/sun/passport-essential-signals.tsx',{'../../lib/product-notice-resource':{useProductNotices:()=>source()},'../../lib/passport-evidence-summary':summary,'./sun-locale-provider':{useSunLocale:()=>({locale:'es-AR',text:v=>v})},'./passport-essential-signals.module.css':{__esModule:true,default:style}});return renderToStaticMarkup(React.createElement(part.PassportEssentialSignals,{identityLabel:'Verificada',sealLabel:'Cerrado',tone:'closed',carrierCode:code,isQr:false,isDemo:false,isHistorical:false,...overrides}));}
test('all informational carriers render unambiguous limits even if a caller supplies positive labels',()=>{for(const c of ['qr_basic','gs1_digital_link','ntag213','uhf_rfid']){const html=signals(c);assert.match(html,/Sin autenticación NFC/);assert.match(html,/No evaluado/);assert.doesNotMatch(html,/>Verificada<|>Cerrado</);}});
test('NFC signal stays separate from product notices and never loses recorded TT state',()=>{const html=signals('ntag424_dna_tt');assert.match(html,/>Verificada</);assert.match(html,/>Cerrado</);assert.match(html,/Sin avisos publicados/);assert.match(html,/href="#product-notices"/);assert.doesNotMatch(html,/Producto seguro|Sin riesgos|Apto para consumo/);});
test('provider owns one bounded request and skips demo/persistence/polling',()=>{const source=readFileSync(new URL('../src/lib/product-notice-resource.tsx',import.meta.url),'utf8');assert.equal((source.match(/await fetch\(/g)||[]).length,1);assert.match(source,/if\(!enabled\)return/);assert.match(source,/8000/);assert.match(source,/parseProductNoticesV2/);assert.doesNotMatch(source,/localStorage|sessionStorage|setInterval|method:.*POST/);});
test('portal UI only reads notices for an explicitly selected saved product',()=>{const src=readFileSync(new URL('../src/app/me/products/product-library.tsx',import.meta.url),'utf8');assert.match(src,/selected!==null/);assert.match(src,/publicProductScope\(p\)/);assert.match(src,/ProductNoticePanel tenant=\{scope.tenant\}/);assert.doesNotMatch(src,/fetch\(|localStorage|window.ethereum|signTransaction|createWallet|verifyTap/);});
test('new account handoff reuses safe event context, not the dynamic tag proof',()=>{const page=readFileSync(new URL('../src/app/sun/page.tsx',import.meta.url),'utf8');assert.match(page,/href=\{withTapQuery\("\/me\/products","products"\)\}/);const code=page.slice(page.indexOf('const tapParams'),page.indexOf('const registerHref'));assert.doesNotMatch(code,/freshToken|cmac|picc_data|enc\W/);});

test('selected passport is bound to its exact account payload, not a reused array position',()=>{const src=readFileSync(new URL('../src/app/me/products/product-library.tsx',import.meta.url),'utf8');assert.match(src,/products\[selected.index\]===selected.item/);assert.match(src,/setSelected\(\{index,item:p\}\)/);});

test('consumer labels explain QR and logistics without promoting them to NFC proof',()=>{assert.equal(model.homeVerdictLabel('QR_VIEW'),'Consulta informativa por QR');assert.equal(model.homeVerdictLabel('DECLARED_LOGISTICS_EVENT'),'Evento logístico declarado');assert.match(model.homeVerdictLabel('VALID_UNKNOWN_TAMPER'),/sin confirmar/);assert.match(model.homeVerdictLabel('REPLAY_SUSPECT'),/nueva lectura/);assert.equal(model.homeVerdictLabel('NEW_UNKNOWN_STATUS'),'NEW_UNKNOWN_STATUS');});
