import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import ts from 'typescript';
const source=await readFile(new URL('../src/lib/product-notices.ts',import.meta.url),'utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;const {parseProductNotices,noticeScope,boundedNoticeJson}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const fixture={ok:true,protocol:'nexid.product-notices.v1',scope:{tenant:'qa',bid:'LOT-QA'},observedAt:new Date().toISOString(),notices:[],total:0,hasMore:false,doesNotDetermineNfcAuthenticity:true,closureDoesNotReleaseProduct:true};
test('empty notice list is scoped evidence, not general product safety',()=>{assert.equal(parseProductNotices(fixture,'qa','LOT-QA').total,0);assert.throws(()=>parseProductNotices({...fixture,doesNotDetermineNfcAuthenticity:false},'qa','LOT-QA'));});
test('unknown tenant or malformed scope does not fall back to an unrelated company',()=>{assert.throws(()=>parseProductNotices(fixture,'other','LOT-QA'));assert.throws(()=>noticeScope('../foreign','LOT-QA'));});
test('closed published notices remain visible without leaking private investigation',()=>{const n={id:'10000000-0000-4000-8000-000000000001',kind:'recall',title:'Recall QA',message:'Published',instructions:'Contact support',contact:'QA',publishedAt:new Date().toISOString(),trackingState:'closed',privateReason:'SHOULD_NOT_LEAK'};const r=parseProductNotices({...fixture,notices:[n],total:1},'qa','LOT-QA');assert.equal(r.notices[0].trackingState,'closed');assert.ok(!JSON.stringify(r).includes('SHOULD_NOT_LEAK'));});
test('unpublished or unknown states and oversized responses are rejected',async()=>{const n={id:'10000000-0000-4000-8000-000000000001',kind:'recall',title:'QA',message:'QA',instructions:'QA',contact:'QA',publishedAt:new Date().toISOString(),trackingState:'draft'};assert.throws(()=>parseProductNotices({...fixture,notices:[n],total:1},'qa','LOT-QA'));await assert.rejects(()=>boundedNoticeJson(new Response('x'.repeat(65537))));});
test('SUN notices use resolved identity, never URL claims, and do not alter NFC truth',async()=>{const page=await readFile(new URL('../src/app/sun/page.tsx',import.meta.url),'utf8');assert.match(page,/ProductNotices tenant=\{String\(result.identity\?\.tenantSlug/);const component=await readFile(new URL('../src/app/sun/product-notices.tsx',import.meta.url),'utf8');assert.doesNotMatch(component,/setInterval|localStorage|CMAC|navigator.geolocation/);assert.match(component,/state.failed\|\|!value\?'unknown'/);assert.match(component,/previous.value\?\.scope.tenant===tenant/);});

test('the services technical status does not claim absence of product recalls',async()=>{const s=await readFile(new URL('../src/app/sun/sun-services-hub.tsx',import.meta.url),'utf8');assert.doesNotMatch(s,/label: "Sin alertas reportadas"/);assert.match(s,/estado técnico no determina/);});
