import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {join} from 'node:path';import {fileURLToPath} from 'node:url';import postcss from 'postcss';
import {splitPublicStyles,NON_TAP_FAMILIES} from '../scripts/public-style-split.mjs';import {preparePublicStyles} from '../scripts/prepare-public-styles.mjs';
const web=fileURLToPath(new URL('../',import.meta.url));
for(const selector of ['.landing-card','.demo-lab-card:hover','html.theme-light .demo-lab-card > .shared',':where(.landing-card,.demo-lab-card) span',':is(.landing-card,.demo-lab-card):focus','.landing-a, .demo-lab-b'])test('only proven marketing selectors leave the cold SUN bundle: '+selector,()=>{const r=splitPublicStyles(selector+'{color:red}', 'sun-content');assert.equal(r.removed.length,1);assert.ok(!r.css.includes('color:red'));});
for(const selector of ['.sun-card','body','html[data-theme="light"]','.unknown-widget',':not(.demo-lab-card)',':is(.landing-card,.sun-card)',':where(.demo-lab-card,.unrelated)',':has(.demo-lab-card)','[class^="landing-"]','.sun-card, .landing-card'])test('uncertain or shared selector stays: '+selector,()=>{const r=splitPublicStyles(selector+'{color:red}', '');assert.equal(r.removed.length,0);assert.ok(r.css.includes('color:red'));});
test('a family used anywhere in the conservative SUN source set is retained',()=>{const r=splitPublicStyles('.demo-lab-card{color:red}.landing-card{color:blue}', 'className={`demo-lab-${kind}`}');assert.equal(r.removed.length,1);assert.ok(r.css.includes('.demo-lab-card'));assert.ok(r.retainedFamilies.includes('demo-lab-'));});
test('media/supports conditions and animation names are not changed',()=>{const input='@media(min-width:600px){.sun-card{padding:1rem}.demo-lab-card{color:red}}@supports(display:grid){.unknown{display:grid}}@keyframes landing-spin{from{opacity:0}to{opacity:1}}';const r=splitPublicStyles(input,'');assert.equal(r.removed.length,1);assert.ok(r.css.includes('@media(min-width:600px){.sun-card{padding:1rem}'));assert.ok(r.css.includes('@keyframes landing-spin{from{opacity:0}to{opacity:1}}'));assert.ok(r.css.includes('@supports(display:grid){.unknown{display:grid}}'));});
test('zero family removals is a valid conservative fallback, never silent aggressive purging',()=>{const r=splitPublicStyles('.landing-card{color:red}.demo-lab-card{color:blue}',NON_TAP_FAMILIES.join(' '));assert.equal(r.removed.length,0);});
const compiled=await preparePublicStyles();
test('generated bundle preserves the exact ordered declaration sequence of all retained rules',async()=>{const original=postcss.parse(await readFile(join(web,'src/app/globals.css'),'utf8')),after=postcss.parse(compiled.css);const omitted=new Set(compiled.removed.map(r=>r.line+'|'+r.selector));const digest=rule=>[rule.selector,rule.nodes.filter(n=>n.type==='decl').map(n=>[n.prop,n.value,Boolean(n.important)]),(()=>{const chain=[];for(let p=rule.parent;p;p=p.parent)if(p.type==='atrule')chain.unshift([p.name,p.params]);return chain;})()];const a=[],b=[];original.walkRules(r=>{if(!omitted.has(r.source.start.line+'|'+r.selector))a.push(digest(r));});after.walkRules(r=>b.push(digest(r)));assert.deepEqual(b,a);assert.ok(compiled.report.commonGzip<compiled.report.sourceGzip*0.5);assert.ok(compiled.report.rootBaseBytes<5000);});
async function pages(folder){const found=[];for(const x of await readdir(folder,{withFileTypes:true})){const p=join(folder,x.name);if(x.isDirectory())found.push(...await pages(p));else if(x.name==='page.tsx')found.push(p);}return found;}
test('every non-SUN page inherits the complete original stylesheet without moving a route',async()=>{const app=join(web,'src/app'),list=await pages(app);for(const p of list){const relative=p.slice(app.length+1).replaceAll('\\','/');if(relative.startsWith('sun/'))continue;const entry=relative==='page.tsx'?p:join(app,relative.split('/')[0],'layout.tsx');const source=await readFile(entry,'utf8');assert.ok(/import ["'](?:\.\/|\.\.\/)globals\.css["']/.test(source),relative+' must retain complete site styling');}});
test('SUN has the smaller bundle while root only loads reset/theme; neither imports full marketing',async()=>{const layout=await readFile(join(web,'src/app/layout.tsx'),'utf8'),sun=await readFile(join(web,'src/app/sun/layout.tsx'),'utf8'),base=await readFile(join(web,'src/app/generated/root-base.css'),'utf8');assert.match(layout,/generated\/root-base\.css/);assert.doesNotMatch(layout,/import ["']\.\/globals\.css/);assert.match(sun,/generated\/sun-root\.css/);assert.doesNotMatch(sun,/import ["']\.\.\/globals\.css/);assert.match(base,/--background/);assert.match(base,/@tailwind base/);assert.doesNotMatch(base,/\.demo-lab-|\.landing-/);});
test('build and dev generate CSS before compiling; full source is the single editable stylesheet',async()=>{const pkg=JSON.parse(await readFile(join(web,'package.json'),'utf8'));for(const mode of ['build','dev'])assert.ok(pkg.scripts[mode].startsWith('node scripts/prepare-public-styles.mjs && node scripts/prepare-sun-map-worker.mjs && next '));assert.ok(compiled.report.sourceHash.match(/^[a-f0-9]{64}$/));assert.ok(compiled.paths.every(p=>!p.includes('node_modules')));});
