// Actual loading/locale components; synthetic local UI, no NFC data or external delivery.
import assert from 'node:assert/strict';import {createServer} from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {fileURLToPath,pathToFileURL} from 'node:url';import {join,dirname,resolve} from 'node:path';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import {build} from 'esbuild';
const root=resolve(fileURLToPath(new URL('../../../',import.meta.url))),web=resolve(root,'apps/web');
const output=resolve(process.env.QA_OUTPUT||'artifacts/sun-first-paint');await mkdir(output,{recursive:true});
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
const css=(await readFile(join(web,'src/app/sun/sun-loading.module.css'),'utf8')).replaceAll(':global(html[data-theme=light])','html[data-theme=light]')+'\n'+(await readFile(join(web,'src/app/sun/sun-brand-identity.module.css'),'utf8')).replaceAll(':global(html:is(.theme-light, [data-theme="light"]))','html:is(.theme-light, [data-theme="light"])');
const stylePlugin={name:'local-css-map',setup(b){b.onLoad({filter:/sun-(loading|brand-identity)[.]module[.]css$/},()=>({contents:"export default new Proxy({}, {get:(_,key)=>String(key)});",loader:'js'}));}};
const ssr=await build({stdin:{contents:"import React from 'react';import{renderToString}from'react-dom/server';import{SunLoadingView}from'./src/app/sun/sun-loading-view';export const render=(locale)=>renderToString(React.createElement(SunLoadingView,{locale}));",resolveDir:web,loader:'tsx'},bundle:true,write:false,platform:'node',format:'cjs',jsx:'automatic',plugins:[stylePlugin],logLevel:'silent'});
const module={exports:{}};new Function('module','exports','require',ssr.outputFiles[0].text)(module,module.exports,createRequire(import.meta.url));
const fixture="import React from'react';import{createRoot}from'react-dom/client';import{SunLocaleProvider}from'./src/app/sun/sun-locale-provider';function Fixture(){return <SunLocaleProvider initialLocale='en'><h1>Local mutation benchmark</h1><div id='volatile'>Compartir ubicación</div><div data-sun-server-evidence='true'>{Array.from({length:1500},(_,i)=><span key={i}>Producto registrado {i}</span>)}</div></SunLocaleProvider>};createRoot(document.getElementById('app')).render(<Fixture/>);";
const original=execFileSync('git',['show','150610df4ecb973f713d27cf768d8125fed9c111:apps/web/src/app/sun/sun-locale-provider.tsx'],{cwd:root,encoding:'utf8'});
const bundles={};for(const variant of ['before','after']){const plugins=variant==='before'?[{name:'exact-before-provider',setup(b){b.onLoad({filter:/sun-locale-provider[.]tsx$/},args=>({contents:original,loader:'tsx',resolveDir:dirname(args.path)}));}}]:[];const result=await build({stdin:{contents:fixture,resolveDir:web,loader:'tsx'},bundle:true,write:false,format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},plugins,logLevel:'silent'});bundles[variant]=result.outputFiles[0].contents;}
const server=createServer((req,res)=>{const u=new URL(req.url,'http://fixture.invalid');if(req.method!=='GET'){res.writeHead(405);return res.end();}if(u.pathname==='/fixture.js'){res.setHeader('content-type','text/javascript');return res.end(bundles[u.searchParams.get('variant')==='before'?'before':'after']);}if(u.pathname==='/favicon.ico'){res.writeHead(204);return res.end();}const pending=u.pathname==='/pending',theme=u.searchParams.get('theme')==='dark'?'dark':'light';res.setHeader('content-type','text/html;charset=utf-8');res.end(`<!doctype html><html lang='${u.searchParams.get('lang')==='en'?'en':'es-AR'}' data-theme='${theme}'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>SUN local performance test</title><style>body{margin:0}${pending?css:''}</style></head><body>${pending?module.exports.render(u.searchParams.get('lang')||'es-AR'):`<div id='app'></div><script src='/fixture.js?variant=${u.searchParams.get('variant')}'></script>`}</body></html>`);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined});
const report={actualLoadingComponent:true,syntheticUi:true,physicalTapMeasured:false,checks:[],views:[],mutations:[],errors:[]};
const check=(value,name)=>report.checks.push({name,passed:Boolean(value)});
try{
 for(const theme of ['light','dark'])for(const width of [320,390,768,1440]){
  const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'}),page=await context.newPage();let geo=0,external=0;
  await page.addInitScript(()=>{window.__geo=0;Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(){window.__geo++;}}});});
  await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():(external++,r.abort()));page.on('pageerror',e=>report.errors.push(e.message));
  await page.goto(origin+'/pending?theme='+theme);await page.getByTestId('sun-loading').waitFor();
  check(await page.getByRole('heading',{name:'Abriendo el pasaporte'}).isVisible(),'Pending card visible without hydration '+width+' '+theme);
  check(await page.locator('script').count()===0,'Loading component needs no client script '+width+' '+theme);
  check(await page.evaluate(()=>window.__geo)===0&&!external,'No permission or external request while pending '+width+' '+theme);
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile viewport fit '+width+' '+theme);
  await page.addScriptTag({content:axe});const violations=await page.evaluate(async()=>(await axe.run('main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>v.id));check(!violations.length,'Axe pending '+width+' '+theme);
  const file='loading-'+width+'-'+theme+'.png';await page.screenshot({path:join(output,file),fullPage:true});report.views.push({width,theme,file,violations});await context.close();
 }
 for(const variant of ['before','after']){
  const context=await browser.newContext(),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.addInitScript(()=>{window.__walks=[];const original=document.createTreeWalker.bind(document);document.createTreeWalker=(root,...args)=>{window.__walks.push({whole:Boolean(root.dataset?.sunLocale),nodes:root.textContent?.length||0});return original(root,...args);};});
  await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await page.goto(origin+'/?variant='+variant);await page.locator('[data-sun-locale]').waitFor();await page.evaluate(()=>new Promise(r=>setTimeout(r,30)));
  const result=await page.evaluate(async()=>{window.__walks=[];for(let i=0;i<6;i++){const span=document.createElement('span');span.textContent='Compartir ubicación';document.querySelector('#volatile').replaceChildren(span);await new Promise(r=>setTimeout(r,15));}return {wholeTreeWalks:window.__walks.filter(w=>w.whole).length,visitedText:window.__walks.reduce((sum,w)=>sum+w.nodes,0),text:document.querySelector('#volatile').textContent,evidence:document.querySelector('[data-sun-server-evidence]').textContent};});
  check(result.evidence.startsWith('Producto registrado 0'),'Server evidence is unchanged '+variant);report.mutations.push({variant,...result,evidence:undefined});await context.close();
 }
 const before=report.mutations.find(r=>r.variant==='before'),after=report.mutations.find(r=>r.variant==='after');check(before.wholeTreeWalks>=6,'Baseline traverses complete passport on each update');check(after.wholeTreeWalks===0,'Changed UI no longer traverses whole passport');check(after.visitedText<before.visitedText,'Measured DOM work decreases for local updates');check(after.text===before.text,'Translation result remains the same');check(!report.errors.length,'No browser exceptions');
}finally{await browser.close();await new Promise(r=>server.close(r));await writeFile(join(output,'report.json'),JSON.stringify(report,null,2));}
console.log(JSON.stringify({checks:report.checks.length,failed:report.checks.filter(c=>!c.passed),views:report.views.length,mutations:report.mutations},null,2));assert.ok(report.checks.every(c=>c.passed));
