import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {dirname,join} from 'node:path';import {fileURLToPath} from 'node:url';
import {configureSunMapWorker,SUN_MAP_WORKER_PATH} from '../src/lib/sun-map-worker.ts';
import {prepareSunMapWorker} from '../scripts/prepare-sun-map-worker.mjs';
for(const origin of ['https://nexid.lat','https://preview.example.invalid','http://127.0.0.1:3456'])test('worker remains same-origin '+origin,()=>{const calls=[];configureSunMapWorker({setWorkerUrl:url=>calls.push(url)},origin);assert.deepEqual(calls,[origin+SUN_MAP_WORKER_PATH]);assert.equal(new URL(calls[0]).search,'');});
test('path and query in an origin argument cannot leak a SUN capability into worker requests',()=>{const calls=[];configureSunMapWorker({setWorkerUrl:url=>calls.push(url)},'https://nexid.lat/sun?access=do-not-send');assert.equal(calls[0],'https://nexid.lat'+SUN_MAP_WORKER_PATH);});
test('published worker and shared module are byte-identical to the pinned installed engine',async()=>{const result=await prepareSunMapWorker();assert.equal(result.version,'6.4.1');assert.equal(result.files.length,3);const dist=dirname(fileURLToPath(import.meta.resolve('maplibre-gl')));for(const f of result.files){const original=await readFile(join(dist,f.name==='LICENSE.txt'?'../LICENSE.txt':f.name));assert.deepEqual(await readFile(join(result.folder,f.name)),original);assert.match(f.sha256,/^[0-9a-f]{64}$/);}});
test('worker relative dependency is shipped beside the worker, without third-party worker URLs',async()=>{const result=await prepareSunMapWorker();const worker=await readFile(join(result.folder,'maplibre-gl-worker.mjs'),'utf8');assert.match(worker,/from["']\.\/maplibre-gl-shared\.mjs["']/);assert.doesNotMatch(SUN_MAP_WORKER_PATH,/https?:|\?|#/);});
test('every production build and local dev launch prepares its assets; vendored copies are not hand-maintained',async()=>{const pkg=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8'));for(const task of ['build','dev'])assert.ok(pkg.scripts[task].includes('node scripts/prepare-sun-map-worker.mjs && next '));const ignored=await readFile(new URL('../../../.gitignore',import.meta.url),'utf8');assert.ok(ignored.includes('/apps/web/public/maplibre/'));});
test('same map styling and truth layers remain; only readiness includes tiles and worker',async()=>{const code=await readFile(new URL('../src/app/sun/sun-passport-map.tsx',import.meta.url),'utf8');assert.ok(code.indexOf('configureSunMapWorker(maplibre, window.location.origin)')<code.indexOf('new maplibre.Map('));assert.doesNotMatch(code,/if \(!disposed && !styleReady\) setLoadState/);assert.match(code,/if \(!disposed && !fullyReady\) setLoadState\("error"\)/);assert.match(code,/if \(disposed \|\| !rasterTileLoaded\) return/);for(const marker of ['sun-tap-accuracy','sun-demo-connection','no-route','noreferrer','Cartografía parcial'])assert.ok(code.includes(marker));});
