// Actual production components and styles, synthetic loopback API only; no provider or customer operations.
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { build } from 'esbuild';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';

const web = fileURLToPath(new URL('../', import.meta.url)), output = resolve(process.env.QA_OUTPUT || 'artifacts/sun-tenant-actions');
await mkdir(output, { recursive: true });
const { chromium } = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const axe = await readFile(process.env.AXE_MODULE_PATH, 'utf8');
const id = '10000000-0000-4000-8000-000000000001', revision = 'a'.repeat(64), nextRevision = 'b'.repeat(64);
const program = { id: '10000000-0000-4000-8000-000000000002', name: 'Programa de ensayo', pointsName: 'Puntos', pointsPerValidTap: 0 };
const configuration = { version: 'nexid.tenant-actions.v1', status: 'published', allowedActions: [], program, trivia: { id, title: 'Trivia de ensayo', revision, pointsPerCorrect: 0, completionBonus: 0 }, catalogAvailable: false };
const quiz = { ok: true, quiz: { id, revision, questions: [{ id: 'q1', prompt: 'Pregunta original de ensayo', options: ['Respuesta original uno', 'Respuesta original dos'] }] } };
const updated = { ...configuration, trivia: { ...configuration.trivia, revision: nextRevision } };
const newQuiz = { ...quiz, quiz: { ...quiz.quiz, revision: nextRevision, questions: [{ id: 'q2', prompt: 'Pregunta nueva de ensayo', options: ['Respuesta nueva uno', 'Respuesta nueva dos'] }] } };
const partialModes = ['partial-missing','partial-unavailable','partial-malformed'];
const fixture = `import React,{useState}from'react';import{createRoot}from'react-dom/client';import{SunLocaleProvider}from'./src/app/sun/sun-locale-provider';import{QREngagementSuite}from'./src/app/sun/qr-engagement-suite';import{SunServicesHub}from'./src/app/sun/sun-services-hub';import{resolveSunTenantIdentity}from'./src/app/sun/sun-tenant-identity';import shell from'./src/app/me/_components/portal-shell.module.css';const mode=new URLSearchParams(location.search).get('mode'),base=${JSON.stringify(configuration)};function Fixture(){const partial=${JSON.stringify(partialModes)}.includes(mode);let start=base;if(['all-off','zero-tabs','only-sommelier','only-lead','opened'].includes(mode))start={...base,program:null,trivia:null,allowedActions:mode==='only-sommelier'?['sommelier']:mode==='only-lead'?['lead']:mode==='opened'?['feedback','marketplace']:[],status:mode==='zero-tabs'?'unpublished':'published'};if(mode==='projection-missing'||mode==='partial-missing')start=null;if(mode==='partial-unavailable')start={...base,status:'unavailable'};if(mode==='partial-malformed')start={...base,allowedActions:'marketplace'};const[config,setConfig]=useState(start);window.__setConfiguration=setConfig;const tenant=resolveSunTenantIdentity({identity:{tenantSlug:'tenant-qa'},tenant:{slug:mode==='conflict'?'tenant-other':'tenant-qa'}}).tenantSlug;return <SunLocaleProvider initialLocale='es-AR'><main className={shell.portal} style={{padding:16,boxSizing:'border-box'}}><h1>Opciones de marca · ensayo local</h1><p>Datos sintéticos. Sin etiqueta física ni operaciones reales.</p><section className='sun-tap-experience'><SunServicesHub configuration={config} verifiedTenant={Boolean(tenant)} riskState={mode==='replay'?'blocked':'clear'} freshnessState={mode==='replay'?'stale':'fresh'} locale='es-AR' purchaseHref='/me/marketplace?tenant=tenant-qa' subscribeHref='#qr-engagement' claimOrManageHref={partial?'#claim-review':null} warrantyHref={partial?'#warranty-review':null} policyAvailability={{promotion:false,purchase:mode!=='replay',subscribe:mode==='only-lead',claimOrManage:partial,warranty:partial}}/><QREngagementSuite wineryName='Empresa de ensayo' productName='Producto de ensayo' tenantSlug={tenant} eventId='715' freshToken={mode==='replay'?'':'synthetic-verified-capability'} configuration={config} canEngage={mode!=='replay'} initialTab={mode==='only-sommelier'?'sommelier':mode==='only-lead'?'contact':mode==='opened'?'feedback':'trivia'} allowedActions={mode==='replay'?[]:['rewards','marketplace']} blockedActions={mode==='opened'?['marketplace']:mode==='replay'?['marketplace','rewards']:[]}/></section></main></SunLocaleProvider>}createRoot(document.getElementById('app')).render(<Fixture/>);`;
const bundled = await build({ stdin: { contents: fixture, resolveDir: web, loader: 'tsx' }, bundle: true, write: false, outfile: 'fixture.js', format: 'esm', platform: 'browser', jsx: 'automatic', define: { 'process.env.NODE_ENV': '"production"' }, plugins: [{ name: 'inert-navigation', setup(b) { b.onResolve({ filter: /^next\/(link|navigation)$/ }, args => ({ path: args.path, namespace: 'nav' })); b.onLoad({ filter: /.*/, namespace: 'nav' }, args => ({ contents: args.path==='next/navigation' ? "export function useRouter(){return {push(){throw Error('Fixture navigation must stay inert')}}}" : "import React from'react';export default function Link({prefetch,...props}){return <a {...props}/>}", loader: 'tsx', resolveDir: web })); } }], logLevel: 'error' });
const globalCss = await postcss([tailwind()]).process(await readFile(join(web, 'src/app/globals.css'), 'utf8'), { from: join(web, 'src/app/globals.css') });
const js = bundled.outputFiles.find(file => file.path.endsWith('.js')), css = (bundled.outputFiles.find(file => file.path.endsWith('.css'))?.text || '') + '\n' + globalCss.css;
const server = createServer((req, res) => { if (req.method !== 'GET') { res.writeHead(405); return res.end(); } const path = new URL(req.url, 'http://fixture.invalid').pathname;
  if (path === '/fixture.js') { res.setHeader('content-type','text/javascript'); return res.end(js.contents); }
  if (path === '/fixture.css') { res.setHeader('content-type','text/css'); return res.end(css); }
  if (path === '/favicon.ico') { res.writeHead(204); return res.end(); }
  res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><html lang='es-AR'><head><title>Opciones · ensayo local</title><meta name='viewport' content='width=device-width,initial-scale=1'><link rel='stylesheet' href='/fixture.css'><style>body{margin:0;font:16px/1.5 system-ui}h1{font-size:24px}button,a{overflow-wrap:anywhere}</style></head><body><div id='app'></div><script type='module' src='/fixture.js'></script></body></html>`);
});
await new Promise(r => server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser = await chromium.launch({ headless:true,executablePath:process.env.CHROME_PATH });
const report={localOnly:true,actualProductionComponentsAndCss:true,actualNextServer:false,nextNavigationReplacedWithInertFixtures:true,syntheticApi:true,physicalTapMeasured:false,realBusinessWrites:0,sourceOverlay:true,sourceHashes:{},errors:[],externalRequests:[],geolocationCalls:0,checks:[],views:[]};
for (const path of ['src/app/sun/qr-engagement-suite.tsx','src/app/sun/tenant-action-availability.ts','src/app/sun/sun-services-hub.tsx','src/app/sun/sun-trivia-model.ts']) report.sourceHashes[path]=createHash('sha256').update(await readFile(join(web,path))).digest('hex');
const check=(value,name)=>{report.checks.push({name,passed:Boolean(value)});assert.ok(value,name);};
async function scenario(mode,width,theme){const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce',serviceWorkers:'block'}),page=await context.newPage(),calls=[];let reloaded=false;
  page.setDefaultTimeout(10000);page.on('pageerror',e=>report.errors.push(e.message));await page.addInitScript(theme=>{document.addEventListener('DOMContentLoaded',()=>document.documentElement.setAttribute('data-theme',theme),{once:true});window.__gpsCalls=0;Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(){window.__gpsCalls++;}}});},theme);
  await page.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.origin!==origin){report.externalRequests.push(url.hostname);return route.abort();}
    if(url.pathname.startsWith('/api/')){const body=request.method()==='POST'?request.postDataJSON():null;calls.push({path:url.pathname,method:request.method(),body});let payload,status=200;
      if(url.pathname==='/api/cognitive-ai')payload={ok:true,optimizedText:'Orientación general de ensayo; ficha específica no verificada.',fallback:true};
      else if(url.pathname==='/api/leads')payload={ok:true};
      else if(url.pathname.startsWith('/api/public/')){reloaded=true;payload={ok:true,configuration:updated};}
      else if(request.method()==='POST'){if(mode==='conflict-submit'){status=409;payload={ok:false,error:'quiz_configuration_changed'};}else payload={ok:true,score:1,total:1,pointsAwarded:0,requiresLogin:false,alreadyCompleted:false};}
      else payload=reloaded?newQuiz:quiz;
      return route.fulfill({status,contentType:'application/json',body:JSON.stringify(payload)});
    }return route.continue();});await page.goto(origin+'/?mode='+mode,{waitUntil:'networkidle'});return{page,calls,close:async()=>{report.geolocationCalls+=await page.evaluate(()=>window.__gpsCalls);await context.close();}};
}
async function assess(page,width,theme,mode){check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${width}/${theme}/${mode}: no overflow`);
  const small=await page.locator('.sun-engagement-suite button,.sun-engagement-suite a,.sun-services-action').evaluateAll(elements=>elements.filter(e=>e.getClientRects().length&&e.getBoundingClientRect().height<44).map(e=>({text:e.textContent,height:e.getBoundingClientRect().height})));
  check(small.length===0,`${width}/${theme}/${mode}: touch targets ${JSON.stringify(small)}`);await page.addScriptTag({content:axe});const result=await page.evaluate(async()=>{const r=await axe.run('main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return{violations:r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)})),incomplete:r.incomplete.map(v=>v.id)};});report.views.push({width,theme,mode,...result});check(result.violations.length===0,`${width}/${theme}/${mode}: zero axe violations`);await page.screenshot({path:join(output,`${mode}-${width}-${theme}.png`),fullPage:true});}
try{for(const width of[320,390,768,1280])for(const theme of['light','dark'])for(const mode of['all-off','zero-tabs','only-sommelier','only-lead','zero-score','scoring-withdrawal','projection-missing','conflict','replay','conflict-submit','opened',...partialModes]){
  const t=await scenario(mode,width,theme),label=`${width}/${theme}/${mode}`;
  if(partialModes.includes(mode)){await t.page.getByTestId('sun-services-unavailable').waitFor();check(await t.page.getByTestId('sun-services-unavailable').count()===1,label+': one partial configuration notice');check((await t.page.getByTestId('sun-services-unavailable').innerText()).includes('No pudimos cargar algunas opciones'),label+': partial notice explains retained options');check(await t.page.getByRole('link',{name:'Solicitar vínculo o gestionar'}).count()===1&&await t.page.getByRole('link',{name:'Solicitar garantía'}).count()===1,label+': independent policy services remain');check(await t.page.getByRole('link',{name:'Solicitar compra'}).count()===0,label+': unavailable marketplace stays closed');check(t.calls.length===0,label+': notice triggers no API requests');}
  else if(['all-off','zero-tabs','projection-missing','conflict','replay'].includes(mode)){await t.page.getByTestId('sun-actions-unavailable').waitFor();check(await t.page.locator('.sun-engagement-suite input,.sun-engagement-suite textarea,.sun-engagement-suite button').count()===0,label+': zero inert tabs/forms');check(t.calls.length===0,label+': no API requests');}
  else if(mode==='only-sommelier'){check(await t.page.getByRole('button',{name:'Novedades',exact:true}).count()===0,label+': no silent contact form');await t.page.getByTitle('Escribí una pregunta para el sommelier virtual').fill('¿Con qué comida?');await t.page.getByTitle('Enviar pregunta').click();await t.page.getByText('Orientación general de ensayo; ficha específica no verificada.').waitFor();check(t.calls.length===1&&t.calls[0].path==='/api/cognitive-ai'&&t.calls[0].body.postTapEventId==='715',label+': only explicit authorized question, zero leads');}
  else if(mode==='only-lead'){await t.page.getByTitle('Nombre para registrar el beneficio').fill('Persona de ensayo');await t.page.getByTitle('Contacto para recibir novedades autorizadas').fill('synthetic@example.invalid');check(await t.page.getByRole('button',{name:'Registrarme',exact:true}).isDisabled(),label+': explicit contact consent');await t.page.getByLabel('Autorizo a la marca').check();await t.page.getByRole('button',{name:'Registrarme',exact:true}).click();await t.page.getByText('Contacto guardado', {exact:true}).waitFor();check(t.calls.length===1&&t.calls[0].path==='/api/leads'&&t.calls[0].body.engagement.optIn==='brand_updates'&&t.calls[0].body.gps.consent===false,label+': one consented synthetic lead, no GPS');}
  else if(mode==='opened'){await t.page.getByLabel('Calificar con 4 estrellas',{exact:true}).click();await t.page.getByRole('button',{name:'Enviar opinión',exact:true}).click();await t.page.getByText('Gracias por calificar',{exact:true}).waitFor();check(await t.page.getByText('Comprar', {exact:true}).count()===0,label+': opened has no purchase');check(t.calls.length===1&&t.calls[0].body.source==='qr_feedback',label+': informational feedback retained');}
  else{await t.page.getByTitle('Elegir respuesta 1').click();if(mode==='scoring-withdrawal'){await t.page.evaluate(base=>window.__setConfiguration({...base,program:null,trivia:null}),configuration);await t.page.getByTestId('sun-trivia-saved-answers').waitFor();check(await t.page.getByRole('button',{name:'Finalizar trivia',exact:true}).count()===0,label+': withdrawn scoring cannot submit');check(t.calls.every(call=>call.method==='GET'),label+': no write after withdrawal');}
    else{await t.page.getByRole('button',{name:'Finalizar trivia',exact:true}).click();const submitted=t.calls.find(call=>call.method==='POST');check(submitted?.body.expectedQuizId===id&&submitted?.body.expectedQuizRevision===revision,label+': expected publication bound to submission');
      if(mode==='conflict-submit'){await t.page.getByTestId('sun-trivia-saved-answers').waitFor();check((await t.page.getByTestId('sun-trivia-saved-answers').innerText()).includes('Respuesta original uno'),label+': conflict preserves answers');check(t.calls.filter(call=>call.method==='GET').length===1,label+': no automatic reassignment');await t.page.getByRole('button',{name:'Cargar trivia actualizada',exact:true}).click();await t.page.getByText('Pregunta nueva de ensayo',{exact:true}).waitFor();check(await t.page.getByRole('button',{name:'Finalizar trivia',exact:true}).isDisabled(),label+': new questions begin unanswered');check((await t.page.getByTestId('sun-trivia-saved-answers').innerText()).includes('Respuesta original uno'),label+': old answers remain read-only');check(t.calls.filter(call=>call.method==='POST').length===1,label+': explicit reload makes no write');}
      else{await t.page.getByText('Se confirmaron 0 puntos.',{exact:true}).waitFor();check(t.calls.filter(call=>call.method==='POST').length===1,label+': zero is confirmed without a replay button');}}
  }
  if(['all-off','zero-tabs'].includes(mode))check(await t.page.getByTestId('sun-services-unavailable').count()===0,label+': legitimate empty or unpublished configuration is not an error');
  if(mode==='projection-missing')check(await t.page.getByTestId('sun-services-unavailable').count()===1,label+': unavailable full notice is not duplicated');
  await assess(t.page,width,theme,mode);await t.close();
}check(report.geolocationCalls===0,'zero GPS');check(report.externalRequests.length===0,'zero external requests');check(report.errors.length===0,'zero browser exceptions');report.status='passed';}
finally{if(!report.status)report.status='failed';await writeFile(join(output,'report.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));}
console.log(JSON.stringify({checks:report.checks.length,views:report.views.length,output,status:report.status}));
