import {prepareSunMapWorker} from '../scripts/prepare-sun-map-worker.mjs';
import {createTestRaster} from './sun-test-raster.mjs';
import assert from 'node:assert/strict';import {createServer} from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {fileURLToPath,pathToFileURL} from 'node:url';import {resolve,join,dirname} from 'node:path';import {build} from 'esbuild';
const web=fileURLToPath(new URL('../',import.meta.url)),root=resolve(web,'../..'),output=resolve(process.env.QA_OUTPUT||'artifacts/sun-map-recovery');await mkdir(output,{recursive:true});
const preparedWorker=await prepareSunMapWorker();
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const source=await readFile(join(web,'src/app/sun/sun-passport-map.tsx'),'utf8');
const fixture=`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{SunPassportMap}from'./src/app/sun/sun-passport-map';const first={origin:{id:'qa-origin',lat:-32.89,lng:-68.84,label:'Origen de ensayo',evidence:'Declarado por la empresa de prueba',source:'declared_origin'},tap:{id:'qa-tap',lat:-32.91,lng:-68.83,label:'Zona de ensayo',evidence:'Ensayo sin teléfono real',source:'browser_geolocation_approximate_consent',accuracyM:1000},showRoute:false,distanceLabel:'2 km'};function App(){const[p,set]=useState(first);window.__change=set;window.__initial=first;return <main><h1>Mapa SUN · ensayo local</h1><p>Geografía de prueba, sin datos de clientes ni solicitudes de ubicación.</p><SunPassportMap {...p}/></main>};createRoot(document.getElementById('app')).render(<App/>);`;
const result=await build({stdin:{contents:fixture,resolveDir:web,loader:'tsx'},bundle:true,write:false,format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'map-fixture',setup(b){b.onLoad({filter:/sun-passport-map[.]tsx$/},args=>({contents:source.replace('mapRef.current = map;','mapRef.current = map; (window as any).__qaMap=map;(window as any).__mapEvents=[]; for(const eventName of ["load","style.load","idle","sourcedata","error"])map.on(eventName as any,(e:any)=>{(window as any).__mapEvents.push({type:eventName,source:e.sourceId,part:e.sourceDataType,state:e.tile?.state,error:e.error?.message});});'),loader:'tsx',resolveDir:dirname(args.path)}));b.onLoad({filter:/sun-passport-map[.]module[.]css$/},()=>({contents:'export default new Proxy({}, {get:(_,key)=>String(key)});',loader:'js'}));}}],logLevel:'silent'});
const css=(await readFile(join(web,'src/app/sun/sun-passport-map.module.css'),'utf8')).replace(/:global\(([^)]+)\)/g,'$1');const engineCss=await readFile(join(root,'node_modules/maplibre-gl/dist/maplibre-gl.css'),'utf8');
const server=createServer(async(req,res)=>{const u=new URL(req.url,'http://test.invalid');if(req.method!=='GET'){res.writeHead(405);return res.end();}if(u.pathname==='/fixture.js'){res.setHeader('content-type','text/javascript');return res.end(result.outputFiles[0].contents);}if(u.pathname.startsWith('/maplibre/6.4.1/')){const name=u.pathname.split('/').at(-1);if(!['maplibre-gl-worker.mjs','maplibre-gl-shared.mjs'].includes(name)){res.writeHead(404);return res.end();}res.setHeader('content-type','text/javascript');return res.end(await readFile(join(preparedWorker.folder,name)));}if(u.pathname==='/favicon.ico'){res.writeHead(204);return res.end();}res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><html lang='es-AR' data-theme='${u.searchParams.get('theme')==='dark'?'dark':'light'}'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='referrer' content='no-referrer'><title>SUN map fixture</title><style>${engineCss}\n${css}\nbody{margin:0;padding:16px;font:14px/1.5 system-ui;background:#0b1420;color:#eaf6ff}main{max-width:1000px;margin:auto}h1{font-size:22px}*,*::before,*::after{box-sizing:border-box}button,a{font:inherit}</style></head><body><div id='app'></div><script src='/fixture.js'></script></body></html>`);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined,args:['--enable-unsafe-swiftshader']});
const report={actualMapLibre:true,syntheticLocations:true,syntheticTileImages:true,checks:[],views:[],errors:[],network:[]};const check=(v,name)=>report.checks.push({name,passed:Boolean(v)});
// Tiny PNG tests delivery/lifecycle only; it is not represented as real map imagery.
const png=createTestRaster();
async function scenario(mode='success',width=390,theme='dark'){
 const context=await browser.newContext({viewport:{width,height:1100},reducedMotion:'reduce',serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(15000);const state={mode,requests:0,held:[]};
 page.on('pageerror',e=>report.errors.push(e.message));await page.addInitScript(()=>{window.__geoRequests=0;Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(){window.__geoRequests++;}}});});
 await page.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.origin===origin&&req.method()==='GET'){if(u.pathname.startsWith('/maplibre/')&&state.mode==='worker-failure')return route.fulfill({status:503,contentType:'text/plain',body:'synthetic worker outage'});return route.continue();}if(req.method()==='GET'&&u.hostname==='server.arcgisonline.com'&&u.pathname.includes('/tile/')){state.requests++;if(req.headers()['referer'])report.network.push('unexpected-referrer');if(state.mode==='hang'){state.held.push(route);return;}if(state.mode==='live')return route.continue();return route.fulfill({status:state.mode==='failure'?503:200,contentType:state.mode==='failure'?'text/plain':'image/png',headers:{'access-control-allow-origin':'*','cache-control':'no-store'},body:state.mode==='failure'?'synthetic outage':png});}report.network.push(req.method()+' '+u.origin+u.pathname);return route.abort();});
 await page.goto(origin+'/?theme='+theme);await page.locator('[data-sun-passport-map]').waitFor();await page.waitForFunction(()=>window.__qaMap);return{page,context,state,width,theme};
}
const stateOf=t=>t.page.locator('[data-sun-passport-map]').getAttribute('data-basemap-state');
async function ready(t){await t.page.waitForFunction(()=>document.querySelector('[data-sun-passport-map]')?.getAttribute('data-basemap-state')==='ready'&&window.__qaMap.loaded()&&window.__qaMap.areTilesLoaded(),null,{timeout:7500});}
async function picture(t,name){const file=`${name}-${t.width}-${t.theme}.png`;await t.page.screenshot({path:join(output,file),fullPage:true});report.views.push({file,name,width:t.width,theme:t.theme});}
try{
 const hang=await scenario('hang');await hang.page.waitForTimeout(8500);
 check(hang.state.requests>0,'Real renderer requested raster tiles');check(await stateOf(hang)==='error','Loaded style with stalled raster exits loading');check(await hang.page.getByRole('button',{name:'Reintentar mapa',exact:true}).count()===1,'Stalled map offers explicit retry');
 check(await hang.page.getByText('Origen de ensayo',{exact:true}).isVisible(),'Origin remains available when tile transfer stalls');
 await picture(hang,'stalled');hang.state.mode='success';await hang.page.evaluate(()=>window.__oldMap=window.__qaMap);await hang.page.getByRole('button',{name:'Reintentar mapa',exact:true}).click();await ready(hang);
 check(await hang.page.evaluate(()=>window.__qaMap!==window.__oldMap),'Retry replaces only the map renderer');check(await hang.page.locator('.maplibregl-canvas').count()===1,'Retry does not duplicate canvases');for(const route of hang.state.held.splice(0))await route.abort().catch(()=>{});await hang.page.waitForTimeout(100);check(await stateOf(hang)==='ready','Old failed requests cannot overwrite the replacement map');await hang.context.close();
 for(const mode of ['failure','worker-failure']){
  const t=await scenario(mode);await t.page.waitForTimeout(8500);check(await stateOf(t)==='error','Failure '+mode+' never claims the blank map is ready');check(!await t.page.getByText('Cargando cartografía',{exact:true}).count(),'Failure '+mode+' ends its loading message');check(await t.page.getByRole('button',{name:'Reintentar mapa',exact:true}).isVisible(),'Failure '+mode+' keeps recovery available');await t.context.close();
 }
 for(const theme of ['light','dark'])for(const width of [320,390,768,1440]){
  const t=await scenario('success',width,theme);await ready(t);check(await t.page.evaluate(()=>window.__qaMap.loaded()&&window.__qaMap.areTilesLoaded()),'Real raster and accuracy layer ready '+width+' '+theme);check(await t.page.locator('.maplibregl-marker').count()===2,'Both original markers visible '+width+' '+theme);
  check(await t.page.getByRole('button',{name:'Ver ambos puntos',exact:true}).isVisible(),'Original map controls retained '+width+' '+theme);check(await t.page.evaluate(()=>Boolean(window.__qaMap.getSource('sun-tap-accuracy'))),'Consented precision area present '+width+' '+theme);
  check(await t.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Viewport fits '+width+' '+theme);check(await t.page.evaluate(()=>window.__geoRequests)===0,'Map does not request phone permission '+width+' '+theme);await picture(t,'restored');
  await t.page.getByRole('button',{name:'Enfocar origen en el mapa: Origen de ensayo'}).click();check(await t.page.locator('.maplibregl-popup').count()===1,'Original point detail works '+width+' '+theme);await t.context.close();
 }
 {
  const t=await scenario();await ready(t);await t.page.evaluate(()=>{window.__oldMap=window.__qaMap;document.documentElement.dataset.theme='light';});await t.page.waitForFunction(()=>window.__qaMap.getPaintProperty('configured-basemap','raster-saturation')===-0.12);await ready(t);check(await t.page.evaluate(()=>window.__qaMap===window.__oldMap),'Theme change retains the interactive map instance');
  await t.page.evaluate(()=>{window.__beforeUpdate=window.__qaMap;window.__change({...window.__initial,tap:{...window.__initial.tap,id:'qa-replacement',lat:-32.93,label:'Otra zona de ensayo'}});});await t.page.waitForFunction(()=>window.__qaMap!==window.__beforeUpdate);await t.page.getByText('Otra zona de ensayo',{exact:true}).waitFor();await ready(t);check(await t.page.locator('.maplibregl-marker').count()===2,'New same-page coordinates replace markers without duplication');check(await t.page.evaluate(()=>window.__geoRequests)===0,'Updating map evidence never requests permission again');await t.context.close();
 }
 check(!report.errors.length,'No browser exceptions');check(!report.network.length,'No unrelated requests or referrer disclosure');

}finally{await browser.close();await new Promise(r=>server.close(r));await writeFile(join(output,'report.json'),JSON.stringify(report,null,2));}
console.log(JSON.stringify({checks:report.checks.length,failed:report.checks.filter(c=>!c.passed),views:report.views.length,errors:report.errors,network:report.network},null,2));assert.ok(report.checks.every(c=>c.passed));
