"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,ChevronLeft,ChevronRight,Clock3,History,Search,Filter,ScanLine,ShieldCheck,TriangleAlert,Info,MapPin,Package,Copy,Check,RefreshCw,X} from 'lucide-react';
import {boundedHistoryJson,parseHistory,historyParams,historySearch,informationalReading,EMPTY_HISTORY_FILTERS,type HistoryPage,type HistoryFilters,type HistoryRow} from './history-model';
import styles from './consumer-history.module.css';
type Attempt={q:HistoryFilters;cursor:string|null;page:number;cutoff?:string;account?:string};
export function ConsumerHistory({initial,initialFilters=EMPTY_HISTORY_FILTERS}:{initial:HistoryPage|null;initialFilters?:HistoryFilters}){
 const [brands,setBrands]=useState(initial?.brands||[]),[queryOpen,setQueryOpen]=useState(!initial);
 const [page,setPage]=useState(initial),[filters,setFilters]=useState<HistoryFilters>(initial?.query||initialFilters),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(initial?'':'No pudimos confirmar tu historial. Esto no significa que esté vacío.'),[login,setLogin]=useState(false),[advanced,setAdvanced]=useState(false),[localTime,setLocalTime]=useState(false),[zone,setZone]=useState('UTC'),[trail,setTrail]=useState<string[]>(initial?[initial.navigation.cursor]:[]);
 const live=useRef(true),controller=useRef<AbortController|null>(null),sequence=useRef(0),retry=useRef<Attempt|null>(null),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{live.current=true;setZone(Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC');return()=>{live.current=false;sequence.current++;controller.current?.abort();};},[]);
 const rows=useMemo(()=>page?historySearch(page.items,search):[],[page,search]);
 const labels=useMemo(()=>new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeStyle:'short',timeZone:localTime?zone:'UTC'}),[localTime,zone]);
 const invalid=Boolean(page&&JSON.stringify(filters)!==JSON.stringify(page.query));
 function changed(next:HistoryFilters){sequence.current++;retry.current=null;setFilters(next);setError('Filtros modificados: consultá para confirmar los resultados.');setPage(null);setTrail([]);}
 async function load(a:Attempt){
  if(controller.current)return;const c=new AbortController(),s=++sequence.current;controller.current=c;retry.current=a;setBusy(true);setError('');setPage(null);setLogin(false);const timer=setTimeout(()=>c.abort(),14000);
  try{
   const response=await fetch('/api/consumer/taps/history?'+historyParams(a.q,a.cursor),{cache:'no-store',credentials:'same-origin',signal:c.signal});
   if(!response.ok){if(response.status===401){setLogin(true);setBrands([]);retry.current=null;throw Error('Tu sesión terminó. Iniciá sesión para consultar sólo tus lecturas.');}if(response.status===409){retry.current=null;throw Error('La navegación venció o cambió la cuenta. Usá Consultar historial para empezar de nuevo.');}throw Error(response.status===400?'Revisá la referencia y las fechas: se necesitan ambas y un período de hasta 366 días.':'No se confirmó la página. Reintentá; no se muestra información anterior como actual.');}
   const next=parseHistory(await boundedHistoryJson(response),{query:a.q,page:a.page,account:a.account,cutoff:a.cutoff});
   if(live.current&&sequence.current===s){setPage(next);setBrands(next.brands);setFilters(next.query);setQueryOpen(false);setAdvanced(false);setTrail(previous=>a.cursor?[...previous.slice(0,a.page-1),next.navigation.cursor]:[next.navigation.cursor]);requestAnimationFrame(()=>{heading.current?.focus({preventScroll:true});if(window.matchMedia('(max-width:700px)').matches)heading.current?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});});}
  }catch(e){if(live.current&&sequence.current===s)setError(e instanceof Error?e.message:'Historial no disponible.');}
  finally{clearTimeout(timer);if(controller.current===c)controller.current=null;if(live.current)setBusy(false);}
 }
 const newQuery=()=>load({q:filters,cursor:null,page:1});
 function move(next:boolean){if(!page)return;const number=page.navigation.page+(next?1:-1),cursor=next?page.navigation.nextCursor:trail[number-1];if(number<1||!cursor)return;void load({q:page.query,page:number,cursor,cutoff:page.navigation.cutoff,account:page.accountKey});}
 return <section className={styles.root} data-testid="consumer-history">
  <nav className={styles.top} aria-label="Navegación del historial"><Link prefetch={false} href="/me"><ArrowLeft size={16} aria-hidden="true"/>Mi cuenta</Link><Link prefetch={false} href="/me/products"><Package size={16} aria-hidden="true"/>Mis productos</Link></nav>
  <header className={styles.hero}><div><span className={styles.kicker}>TU HISTORIA, EN UN SOLO LUGAR</span><h2>Volvé a una lectura guardada</h2><p>Encontrá su referencia y abrí la evidencia, sin repetir el TAP ni cambiar el producto.</p></div><span className={styles.heroIcon}><History size={29} aria-hidden="true"/></span></header>
  <details className={styles.queryFold} data-testid="history-filter-panel" open={queryOpen} onToggle={e=>setQueryOpen(e.currentTarget.open)}><summary><Filter size={17} aria-hidden="true"/><span>Buscar por empresa, referencia o fecha<small>{filters.event?'Lectura #'+filters.event:brands.find(b=>b.slug===filters.tenant)?.name||filters.tenant||'Todo mi historial guardado'}{filters.from?' · '+filters.from+' al '+filters.to:''}</small></span></summary><form className={styles.query} onSubmit={e=>{e.preventDefault();void newQuery();}}>
   <div className={styles.mainFilters}><label>Empresa<select value={filters.tenant} disabled={busy} onChange={e=>changed({...filters,tenant:e.target.value})}><option value="">Todas mis empresas</option>{filters.tenant&&!brands.some(b=>b.slug===filters.tenant)&&<option value={filters.tenant}>{filters.tenant}</option>}{brands.map(b=><option value={b.slug} key={b.slug}>{b.name||b.slug}</option>)}</select></label><label>Referencia de lectura<input inputMode="numeric" maxLength={19} placeholder="Número de lectura, sin #" value={filters.event} disabled={busy} onChange={e=>changed({...filters,event:e.target.value.trim()})}/></label><button type="submit" className={styles.primary} disabled={busy}><RefreshCw size={16} aria-hidden="true"/>{busy?'Consultando…':'Consultar historial'}</button></div>
   <details open={advanced} onToggle={e=>setAdvanced(e.currentTarget.open)} className={styles.dates}><summary><Filter size={15} aria-hidden="true"/>Filtrar por fecha en que se guardó</summary><div><label>Desde · UTC<input type="date" value={filters.from} disabled={busy} onChange={e=>changed({...filters,from:e.target.value})}/></label><label>Hasta · inclusive UTC<input type="date" value={filters.to} disabled={busy} onChange={e=>changed({...filters,to:e.target.value})}/></label><p>Ambas vacías recorren todo el historial. Con fechas: hasta 366 días por consulta.</p></div></details>
   {(filters.tenant||filters.from||filters.to||filters.event)&&<div className={styles.filterSummary}><span>{brands.find(b=>b.slug===filters.tenant)?.name||filters.tenant||'Todas mis empresas'}{filters.event?' · lectura #'+filters.event:''}{filters.from?' · '+filters.from+' al '+(filters.to||'…'):''}</span><button type="button" disabled={busy} onClick={()=>changed({...EMPTY_HISTORY_FILTERS})}><X size={13} aria-hidden="true"/>Quitar filtros</button></div>}
  </form></details>
  <p role="status" className={styles.status}>{error||(busy?'Recuperando esta página de tu cuenta…':page?`Consulta confirmada · ${labels.format(new Date(page.observedAt))} ${localTime?zone:'UTC'}`:'Historial sin confirmar.')}</p>
  {login?<div className={styles.error}><TriangleAlert size={23} aria-hidden="true"/><div><h3>Iniciá sesión para continuar</h3><Link prefetch={false} className={styles.primary} href="/login?consumer=1&next=%2Fme%2Ftaps">Entrar a mi cuenta</Link></div></div>:!page&&!busy&&error?<div className={styles.error}><Info size={23} aria-hidden="true"/><div><h3>El historial todavía no está confirmado</h3><p>No interpretamos una caída como ausencia de lecturas.</p><button type="button" onClick={()=>void load(retry.current||{q:filters,cursor:null,page:1})}>Reintentar consulta</button></div></div>:null}
  <section className={styles.results} aria-labelledby="personal-history-results"><div className={styles.listTitle}><div><h3 ref={heading} tabIndex={-1} id="personal-history-results">{page?`Página ${page.navigation.page}`:'Tu historial privado'}</h3><span>{page?`${page.items.length} ${page.items.length===1?'lectura guardada':'lecturas guardadas'} en esta página`:'Sólo registros asociados a tu cuenta'}</span></div><div className={styles.navigation}><button type="button" aria-label="Página anterior de mis lecturas" disabled={busy||!page||page.navigation.page===1||invalid} onClick={()=>move(false)}><ChevronLeft size={16} aria-hidden="true"/>Anterior</button><button type="button" aria-label="Página siguiente de mis lecturas" disabled={busy||!page?.navigation.hasNext||invalid} onClick={()=>move(true)}>Siguiente<ChevronRight size={16} aria-hidden="true"/></button></div></div>
   {page&&<><div className={styles.local}><label><Search size={17} aria-hidden="true"/><span className={styles.srOnly}>Buscar en esta página</span><input type="search" maxLength={160} placeholder="Buscar entre las lecturas de esta página" value={search} onChange={e=>setSearch(e.target.value)}/></label><button type="button" aria-pressed={localTime} onClick={()=>setLocalTime(x=>!x)}><Clock3 size={15} aria-hidden="true"/>{localTime?'Hora de mi dispositivo':'Horarios UTC'}</button></div><p className={styles.note}>{rows.length} coincidencias locales. La consulta por empresa, referencia y fechas recorre tus registros, no sólo estas filas.</p>
   {rows.length?<ol className={styles.list} aria-label="Lecturas guardadas de mi cuenta">{rows.map(t=><SavedReading key={t.rowId} row={t} displayDate={labels.format(new Date(t.savedAt))+' '+(localTime?'· hora local':'UTC')}/>)}</ol>:<div className={styles.empty}><ScanLine size={30} aria-hidden="true"/><h3>{page.items.length?'Sin coincidencias en esta página':'Sin lecturas en esta selección'}</h3><p>{page.navigation.hasNext?'Hay páginas siguientes. Para buscar una referencia en todo el historial usá el filtro superior.':'Acercá el celular a una etiqueta o escaneá un QR, y guardá su lectura desde el pasaporte. Este panel no inventa lecturas ni las vincula automáticamente.'}</p>{search&&<button type="button" onClick={()=>setSearch('')}>Limpiar búsqueda local</button>}</div>}
   <div className={styles.end}>{page.navigation.hasNext&&<button type="button" className={styles.primary} disabled={busy} onClick={()=>move(true)}>Continuar con más lecturas<ChevronRight size={16} aria-hidden="true"/></button>}<span>{page.navigation.hasNext?'Hay más lecturas guardadas para consultar.':'No se detectaron más registros para esta consulta.'}</span><Link prefetch={false} href="/me/products">Abrir mis productos<ArrowRight size={15} aria-hidden="true"/></Link></div>
   <details className={styles.explanation}><summary>Qué fecha veo y qué representa el resultado</summary><p>El orden y los filtros usan la fecha en que la lectura se guardó en tu cuenta; puede ser posterior al TAP. El nombre mostrado corresponde al producto asociado en tu colección, cuando existe una referencia inequívoca.</p><p>Los resultados son históricos. No confirman el estado físico actual del precinto, la ubicación del producto o su titularidad. En el detalle de la lectura podés consultar los avisos actuales del lote cuando está identificado.</p><p>La navegación mantiene un corte de registros: {page.navigation.cutoff}. No es una fotografía inmutable; una eliminación o corrección puede cambiar páginas posteriores. Consultar historial reinicia la búsqueda. No solicitamos GPS ni guardamos el historial en el almacenamiento del navegador.</p>{page.moreBrands&&<p>La lista de empresas muestra hasta 50 referencias asociadas; no es el catálogo completo de NexID.</p>}</details></>}
  </section>
 </section>;
}
function SavedReading({row:t,displayDate}:{row:HistoryRow;displayDate:string}){
 const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false),informative=informationalReading(t),Icon=informative?ScanLine:t.status==='validated'?ShieldCheck:t.status==='attention'?TriangleAlert:Info;
 return <li><article className={styles.reading} data-tone={informative?'information':t.status}>
  <span className={styles.readingIcon}><Icon size={22} aria-hidden="true"/></span><div className={styles.readingContent}><div className={styles.badges}><span>{informative?'Enlace informativo · sin autenticación NFC':t.statusLabel}</span><small>Registro histórico</small></div><h4>{t.productName||t.brandName||t.tenantName||t.tenantSlug||'Lectura guardada'}</h4>{t.productName&&<p className={styles.brand}>{t.brandName||t.tenantName||t.tenantSlug}</p>}<p className={styles.saved}><Clock3 size={14} aria-hidden="true"/>Guardada <time dateTime={t.savedAt}>{displayDate}</time></p><p className={styles.location}><MapPin size={14} aria-hidden="true"/>{t.location?`Zona reportada: ${t.location}`:'Zona no reportada'}</p><div className={styles.actions}><Link prefetch={false} className={styles.primary} href={t.href!} aria-label={`Abrir lectura ${t.id}`}>Abrir lectura<ArrowRight size={16} aria-hidden="true"/></Link><button type="button" aria-label={`Copiar referencia ${t.id}`} onClick={async()=>{try{await navigator.clipboard.writeText(t.id!);setCopied(true);setCopyError(false);}catch{setCopyError(true);}}}>{copied?<Check size={14} aria-hidden="true"/>:<Copy size={14} aria-hidden="true"/>}{copied?'Referencia copiada':'#'+t.id}</button></div>{copyError&&<p role="status">No se pudo copiar. Referencia: {t.id}</p>}<details className={styles.record}><summary>Datos del registro</summary><dl><div><dt>Resultado almacenado</dt><dd>{t.verdict||'No informado'}</dd></div><div><dt>Señal de riesgo guardada</dt><dd>{t.risk.label}</dd></div><div><dt>Empresa</dt><dd>{t.tenantName||t.tenantSlug}</dd></div></dl><p>La señal guardada no es una evaluación nueva del producto.</p></details></div>
 </article></li>;
}
