import {reusableFields,type PublishedChoice,type PublishedLibrary} from '../../lib/passport-reuse';
import type {StudioSnapshot,StudioDocument} from '../../lib/passport-studio-contract';
export type ReuseRequest={snapshot:StudioSnapshot;document:StudioDocument;apply:(source:PublishedChoice,fields:string[])=>boolean};
export type LibraryReader=(target:StudioSnapshot,q:string,source:PublishedChoice|undefined,signal:AbortSignal)=>Promise<PublishedLibrary>;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function openPublishedReuse(host:HTMLElement,request:ReuseRequest,read:LibraryReader,onClose:()=>void){
 const previous=document.activeElement as HTMLElement|null,dialog=document.createElement('dialog');dialog.className='ps-root ps-reuse-dialog';dialog.setAttribute('aria-labelledby','ps-reuse-title');
 dialog.innerHTML=`<header class="ps-reuse-heading"><div><span class="ps-kicker">PUBLICACIÓN → NUEVO BORRADOR</span><h2 id="ps-reuse-title">Reutilizar contenido publicado</h2><p>Destino: <strong>${esc(request.snapshot.scope.bid)}</strong> · ${esc(request.document.locale)}</p></div><button type="button" class="ps-btn" data-close aria-label="Cerrar biblioteca de contenido">✕</button></header>
 <div class="ps-reuse-body"><details class="ps-reuse-boundary"><summary>Los datos del lote se conservan</summary><p>No se copian SKU, GTIN, fechas, lote comercial, distribuidor, canal autorizado, avisos de retiro o beneficios. Tampoco claves NFC, autenticidad o aprobaciones.</p></details>
 <form data-search-form class="ps-reuse-search"><label>Producto o lote publicado<input type="search" data-library-query maxlength="120" placeholder="Nombre o referencia del lote" autocomplete="off"/></label><button class="ps-btn ps-primary" type="submit">Buscar publicaciones</button></form>
 <p role="status" aria-live="polite" data-library-status>Buscá dentro de esta empresa. Se muestran publicaciones de la misma plantilla e idioma, no borradores ni contenido inicial sin revisar.</p><div data-library-sources></div><section data-library-preview></section></div>
 <footer class="ps-reuse-footer"><span data-selected-summary>Ningún campo seleccionado</span><button class="ps-btn" type="button" data-close>Cancelar</button><button type="button" class="ps-btn ps-primary" data-apply disabled>Aplicar campos al borrador</button></footer>`;
 host.appendChild(dialog);const events=new AbortController();let pending:AbortController|null=null,closed=false,source:PublishedChoice|null=null,choices:PublishedChoice[]=[],selected=new Set<string>();
 const status=dialog.querySelector<HTMLElement>('[data-library-status]')!,sources=dialog.querySelector<HTMLElement>('[data-library-sources]')!,preview=dialog.querySelector<HTMLElement>('[data-library-preview]')!,search=dialog.querySelector<HTMLInputElement>('[data-library-query]')!,apply=dialog.querySelector<HTMLButtonElement>('[data-apply]')!,summary=dialog.querySelector<HTMLElement>('[data-selected-summary]')!;
 function controls(){dialog.querySelectorAll<HTMLInputElement|HTMLButtonElement>('input,button:not([data-close])').forEach(e=>e.disabled=Boolean(pending));apply.disabled=Boolean(pending)||!source||!selected.size;summary.textContent=selected.size?`${selected.size} campos seleccionados · sólo trabajo local`:'Ningún campo seleccionado';}
 function close(){if(closed)return;closed=true;pending?.abort();events.abort();dialog.close();dialog.remove();previous?.isConnected&&previous.focus({preventScroll:true});onClose();}
 async function fetchSource(choice?:PublishedChoice,applyAfter=false){
  if(pending||closed)return;const controller=new AbortController();pending=controller;const timer=setTimeout(()=>controller.abort(),12000);controls();status.textContent=applyAfter?'Revalidando la publicación y la revisión del destino…':'Consultando publicaciones autorizadas…';
  if(!choice){dialog.classList.remove('ps-reuse-selected');source=null;selected.clear();preview.innerHTML='';sources.innerHTML='';}
  try{
   const result=await read(request.snapshot,search.value,choice,controller.signal);if(closed)return;
   if(applyAfter){const current=result.items[0];if(!request.apply(current,[...selected]))throw Error('El trabajo de destino cambió. Revisá el borrador antes de reutilizar contenido.');close();return;}
   if(choice){dialog.classList.add('ps-reuse-selected');source=result.items[0];selected.clear();const fields=reusableFields(request.document,source.document!);
    preview.innerHTML=`<div class="ps-reuse-source-title"><button type="button" class="ps-link" data-change-source>Cambiar publicación de origen</button><span class="ps-kicker">2 · SELECCIONÁ QUÉ REUTILIZAR</span><h3 tabindex="-1">${esc(source.product)}</h3><p>${esc(source.bid)} · publicación v${source.version} · ${esc(new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(source.publishedAt))+' UTC')}</p></div>
    <p class="ps-reuse-copy-note">No hay campos marcados por defecto. Compará el contenido de origen con tu borrador. La aprobación del origen no se aplica al destino.</p><div class="ps-reuse-fields">${fields.map(f=>`<label class="ps-reuse-field"><span class="ps-reuse-label"><input type="checkbox" data-reuse-field="${esc(f.path)}"/><strong>${esc(f.label)}</strong></span><span class="ps-reuse-values"><span><small>Tu borrador</small><span>${esc(f.before||'Sin contenido')}</span></span><span><small>Publicado de origen</small><span>${esc(f.after)}</span></span></span>${f.kind==='url'?'<em>Sólo se copiaría la URL declarada. El documento externo no fue descargado ni verificado.</em>':''}</label>`).join('')||'<p>No hay valores distintos y reutilizables en esta publicación. No se reemplazan campos con contenido vacío.</p>'}</div>`;
    status.textContent=`Publicación v${source.version} recibida. Elegí campos; todavía no cambió el borrador.`;
    preview.querySelector<HTMLElement>('h3')?.focus({preventScroll:true});if(matchMedia('(max-width:700px)').matches)preview.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});
   }else{choices=result.items;sources.innerHTML=`<div class="ps-reuse-results">${choices.map((c,i)=>`<button class="ps-reuse-source" type="button" data-source-index="${i}"><span><strong>${esc(c.product)}</strong><small>${esc(c.bid)} · v${c.version}</small></span><span>Revisar campos →</span></button>`).join('')||'<div class="ps-empty"><strong>No hay publicaciones compatibles con esta búsqueda.</strong><p>Primero necesitás publicar contenido en otro lote de la misma empresa. No se incorporan lotes ni se publican documentos automáticamente.</p></div>'}</div>`;status.textContent=`${choices.length} publicaciones visibles${result.hasMore?' · hay más: afiná la búsqueda':''}. Las nuevas revisiones en borrador no sustituyen la publicación de origen.`;}
  }catch(e){if(!closed){dialog.classList.remove('ps-reuse-selected');source=null;choices=[];selected.clear();preview.innerHTML='';sources.innerHTML='';status.textContent=e instanceof Error?e.message:'No se confirmó la consulta. Tus campos permanecen intactos.';}}
  finally{clearTimeout(timer);pending=null;if(!closed)controls();}
 }
 dialog.querySelector('form')!.addEventListener('submit',e=>{e.preventDefault();void fetchSource();},{signal:events.signal});
 search.addEventListener('input',()=>{source=null;selected.clear();choices=[];sources.innerHTML='';preview.innerHTML='';status.textContent='Búsqueda modificada. Presioná Buscar publicaciones; escribir no consulta la base.';controls();},{signal:events.signal});
 dialog.addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLButtonElement>('button');if(!b||b.disabled)return;if(b.hasAttribute('data-close')){close();return;}if(b.hasAttribute('data-change-source')){dialog.classList.remove('ps-reuse-selected');source=null;selected.clear();preview.innerHTML='';controls();search.focus();status.textContent='Elegí otra publicación o realizá una nueva búsqueda. Tu borrador no cambió.';return;}if(b.dataset.sourceIndex!==undefined){const c=choices[Number(b.dataset.sourceIndex)];if(c){source=null;selected.clear();preview.innerHTML='';void fetchSource(c);}}if(b.hasAttribute('data-apply')&&source&&selected.size)void fetchSource(source,true);},{signal:events.signal});
 dialog.addEventListener('change',e=>{const input=e.target;if(!(input instanceof HTMLInputElement)||!input.dataset.reuseField||pending)return;input.checked?selected.add(input.dataset.reuseField):selected.delete(input.dataset.reuseField);controls();},{signal:events.signal});
 dialog.addEventListener('cancel',e=>{e.preventDefault();close();},{signal:events.signal});
 dialog.showModal();search.focus();return {destroy:close};
}
