export const pricingPlans = [
  {
    slug: "basic",
    name: "Basic",
    badge: "NTAG215",
    description: "Marketing tags, events, loyalty and basic product follow-up.",
    monthlyUsd: 99,
    monthlyLabel: "Software desde USD 99 / mes",
    unitExample: "Referencia recurrente; setup, tags, encoding y servicios se cotizan aparte",
    features: [
      "Scan logs",
      "Dashboard basico",
      "Experiencias tap to web",
      "Sin antifraude criptografico",
    ],
  },
  {
    slug: "secure",
    name: "Secure",
    badge: "NTAG 424 DNA TT",
    description: "SUN message verification, replay and copy-resistance signals, reported TT state and secure batch operations.",
    monthlyUsd: 249,
    monthlyLabel: "Software desde USD 249 / mes",
    unitExample: "Referencia recurrente; setup, tags 424, encoding y servicios se cotizan aparte",
    features: [
      "SUN message validation",
      "Manifest allowlist",
      "Replay/duplicate alerts",
      "Batch keys",
      "Reported TT workflows",
    ],
  },
  {
    slug: "enterprise",
    name: "Enterprise",
    badge: "White label",
    description: "Reseller, branding, APIs, governance and digital identity layer.",
    monthlyUsd: 499,
    monthlyLabel: "Software desde USD 499 / mes + uso",
    unitExample: "Implementacion, SLA y deployment quedan sujetos a readiness review, alcance y contrato",
    features: [
      "Reseller panel",
      "White label",
      "API keys",
      "Webhooks",
      "Tokenization layer",
      "SLA y soporte luego de readiness review",
    ],
  },
];
