import type { SommelierContext, SommelierLocale } from "./sommelier-contract";
const SHEET = "https://vallesecreto.cl/wp-content/uploads/2025/10/10-2025-Ficha-Tecnica-PROFUNDO-2019.pdf";
const PRACTICES = "https://vallesecreto.cl/wp-content/uploads/2025/10/Practicas-Sustentables-Formato-VVS-Aprobada_VS.pdf";
const EXPERIENCES = "https://vallesecreto.cl/experiencias/";
/** Fixed public producer facts. No tenant/NFC identity, sensors or visitor data. */
export function valleSecretoSommelierFacts(locale: SommelierLocale): SommelierContext {
  const labels = { "es-AR": ["Vino", "Origen", "Cosecha", "Ensamblaje", "Barrica", "Servicio", "Maridajes", "Prácticas publicadas", "Visita"], en: ["Wine", "Origin", "Vintage", "Blend", "Barrels", "Serving", "Pairings", "Published practices", "Visit"], "pt-BR": ["Vinho", "Origem", "Safra", "Composição", "Barricas", "Serviço", "Harmonizações", "Práticas publicadas", "Visita"] }[locale];
  const values = { "es-AR": ["Profundo 2019 · Valle Secreto", "Cachapoal Andes, Chile", "2019", "34% Cabernet Sauvignon, 23% Cabernet Franc, 23% Carmenere, 15% Petit Verdot, 5% Malbec", "24 meses en barricas Magnum nuevas de roble francés", "16–18 °C, recomendación de la ficha; no es una medición de la botella", "Cordero, carnes de caza y pato", "Energía solar, tratamiento de residuos líquidos y reutilización de materiales; sin huella por botella publicada en esta demo", "Experiencias y Mapa del Tesoro publicados por la viña; consultar disponibilidad, sin reserva automática"], en: ["Profundo 2019 · Valle Secreto", "Cachapoal Andes, Chile", "2019", "34% Cabernet Sauvignon, 23% Cabernet Franc, 23% Carmenere, 15% Petit Verdot, 5% Malbec", "24 months in new French oak Magnum barrels", "16–18 °C, a sheet recommendation, not a bottle measurement", "Lamb, game and duck", "Solar energy, liquid waste treatment and material reuse; no bottle-level footprint published in this demo", "Producer-published experiences and Treasure Map; check availability, no automatic booking"], "pt-BR": ["Profundo 2019 · Valle Secreto", "Cachapoal Andes, Chile", "2019", "34% Cabernet Sauvignon, 23% Cabernet Franc, 23% Carmenere, 15% Petit Verdot, 5% Malbec", "24 meses em barricas Magnum novas de carvalho francês", "16–18 °C, recomendação da ficha; não é uma medição da garrafa", "Cordeiro, carnes de caça e pato", "Energia solar, tratamento de resíduos líquidos e reutilização de materiais; sem pegada por garrafa publicada nesta demo", "Experiências e Mapa do Tesouro publicados pela vinícola; consulte disponibilidade, sem reserva automática"] }[locale];
  const ids = ["wine", "origin", "vintage", "blend", "barrel", "serving", "pairing", "practices", "visit"];
  return { source: "valle_secreto_demo", tenantId: "demo:valle-secreto", demo: true, facts: ids.map((id, i) => ({ id, label: labels[i], text: values[i], url: i === 7 ? PRACTICES : i === 8 ? EXPERIENCES : SHEET })) };
}
