export type ChannelIdentity={id:string;gtin:string;lot:string;serial:string;status:string;entitlementStatus:string;ready:boolean;url:string};
export type BatchChannels={contract:'nexid.batch-channels.v1';source:'database';scope:{tenant:string;bid:string;batchId:string};observedAt:string;product:string;batchStatus:string;carrier:{code:string|null;name:string;mode:'tagtamper'|'secure_nfc'|'qr'|'gs1'|'other';cryptographic:boolean;tamper:boolean};policyEnabled:boolean;publicReady:boolean;publicUrl:string|null;canRegister:boolean;tt:{enabled:boolean;source:string|null;length:number|null;encoding:string|null;closed:string[];opened:string[];invalid:string[];physicalState:'NOT_READ_BY_CONFIGURATION'}|null;identities:ChannelIdentity[];moreIdentities:boolean;prefixes:string[]};
export function safeChannelUrl(value:unknown):string{if(typeof value!=='string'||value.length>2048)throw new Error('channel_url');const u=new URL(value);if(u.origin!=='https://nexid.lat'||u.username||u.password||u.hash||(!u.pathname.startsWith('/01/')&&u.pathname!=='/sun'))throw new Error('channel_url');if(u.searchParams.has('cmac')||u.searchParams.has('enc')||u.searchParams.has('picc_data'))throw new Error('channel_dynamic_url');return value;}
export function parseBatchChannels(raw:unknown,bid:string,tenant:string):BatchChannels{
 const r=raw as BatchChannels&{ok:boolean};
 if(!r||r.ok!==true||r.contract!=='nexid.batch-channels.v1'||r.source!=='database'||r.scope?.bid!==bid||(tenant&&r.scope.tenant!==tenant)||!r.scope.tenant||!/^[a-f0-9-]{36}$/.test(r.scope.batchId))throw new Error('channel_scope');
 if(!r.carrier||!['tagtamper','secure_nfc','qr','gs1','other'].includes(r.carrier.mode)||typeof r.canRegister!=='boolean'||!Array.isArray(r.identities)||r.identities.length>100||!Array.isArray(r.prefixes)||r.prefixes.length>100||!Number.isFinite(Date.parse(r.observedAt)))throw new Error('channel_source');
 if(r.publicUrl){safeChannelUrl(r.publicUrl);const u=new URL(r.publicUrl);if(r.carrier.mode!=='qr'||u.searchParams.get('bid')!==bid||u.searchParams.get('tenant')!==r.scope.tenant||u.searchParams.get('carrier')!=='qr_basic')throw new Error('channel_binding');}
 for(const i of r.identities){safeChannelUrl(i.url);if(typeof i.ready!=='boolean'||!/^\d{14}$/.test(i.gtin)||new URL(i.url).pathname!==gs1PathLocal(i.gtin,i.lot,i.serial))throw new Error('channel_identity');}
 if(['tagtamper','secure_nfc'].includes(r.carrier.mode)&&(r.publicUrl||r.identities.length))throw new Error('channel_security_mismatch');
 if(r.tt&&r.tt.physicalState!=='NOT_READ_BY_CONFIGURATION')throw new Error('channel_tamper_assertion');
 return r;
}
function gs1PathLocal(gtin:string,lot:string,serial:string){return `/01/${gtin}${lot?`/10/${encodeURIComponent(lot)}`:''}${serial?`/21/${encodeURIComponent(serial)}`:''}`;}
export function validGtin(value:string){if(!/^\d{14}$/.test(value))return false;let total=0;for(let i=0;i<13;i++)total+=Number(value[i])*(i%2?1:3);return (10-total%10)%10===Number(value[13]);}
export function channelWriteBody(gtin:string,lot:string,serial:string,displayName:string){if(!validGtin(gtin))throw new Error('GTIN de 14 dígitos con control inválido.');for(const v of [lot,serial])if(v&&(!/^[!-~]{1,20}$/.test(v)||/[\/?#%]/.test(v)))throw new Error('Lote y serie: hasta 20 caracteres imprimibles, sin espacios, barras ni % .');return {gtin,lot,serial,displayName,reason:'Alta de identidad del lote desde configuración de canales'};}
