import {eventLabels,stepLabels,custodyLabels,type BatchTrace} from './batch-traceability';
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function traceExports(data:BatchTrace){
 const serialized=JSON.stringify(data),sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(serialized)))].map(v=>v.toString(16).padStart(2,'0')).join('');
 const row=(cells:unknown[])=>'<tr>'+cells.map(c=>'<td>'+escape(c)+'</td>').join('')+'</tr>';
 const events=data.events.map(e=>row([e.occurredAt,eventLabels[e.type]||e.type,stepLabels[e.step||'']||e.step||'No informado',e.action||'Sin acción',e.correctionDeclared?'Corrección declarada':'Sin corrección reportada',e.references.map(r=>`${r.role}: ${r.gtin}${r.serial?' / '+r.serial:''} · ${r.bid}${r.quantity!==null?' · '+r.quantity+' '+(r.uom||'unidad no informada'):''}`).join('\n'),e.recordedAt]));
 const custody=data.custody.map(e=>row([e.recordedAt,custodyLabels[e.type]||e.type,e.shipmentCode||'Sin envío informado']));
 const shipments=data.shipments.map(s=>row([s.code,s.status,s.createdAt,s.updatedAt]));
 const table=(head:string[],rows:string[])=>'<table><thead><tr>'+head.map(t=>'<th>'+escape(t)+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table>';
 const html='<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recorrido del lote</title><style>body{font:14px/1.7 system-ui,sans-serif;color:#133548;max-width:1180px;margin:32px auto;padding:0 24px}h1{font-size:32px;line-height:1.2}h2{margin-top:32px;font-size:21px}header{border-bottom:3px solid #168591;padding-bottom:20px}p{white-space:pre-wrap}table{border-collapse:collapse;width:100%;font-size:11px}th,td{text-align:left;vertical-align:top;border:1px solid #c8dce4;padding:9px;white-space:pre-wrap;overflow-wrap:anywhere}th{background:#edf7f9}code{font-size:11px;overflow-wrap:anywhere}.note{background:#eff7fa;border-left:3px solid #16758a;padding:14px}@media print{body{margin:0}thead{display:table-header-group}tr{break-inside:avoid}@page{size:A4 landscape;margin:12mm}}</style><header><p>NEXID · EXPEDIENTE OPERATIVO</p><h1>'+escape(data.product.name)+'</h1><p>Empresa: '+escape(data.scope.tenant)+' · Lote: '+escape(data.scope.bid)+'\nPeríodo incluido: '+escape(data.window.from)+' al '+escape(data.window.to)+' UTC\nConsulta: '+escape(data.observedAt)+'</p></header><p class="note">EPCIS muestra declaraciones registradas. La custodia corresponde al flujo de logística. Ninguna relación histórica certifica ubicación, pertenencia actual, contenido o autenticidad NFC. Las filas visibles no son el total histórico del lote.</p><h2>Eventos EPCIS · '+data.events.length+' visibles</h2>'+table(['Fecha declarada UTC','Tipo','Paso','Acción','Corrección','Referencias informadas','Registrado UTC'],events)+'<p>'+escape(data.hasMore.events?'Hay más eventos en el período: reducir el rango para consultar otra selección.':'No se detectó truncamiento de eventos EPCIS para esta ventana.')+'</p><h2>Custodia registrada · '+data.custody.length+' visibles</h2>'+table(['Fecha de registro UTC','Movimiento','Envío'],custody)+'<p>'+escape(data.logisticsAccess==='restricted'?'No incluida: el rol no tiene permiso de logística.':data.hasMore.custody?'La selección de custodia está truncada.':'Sólo movimientos vinculados al lote mediante sus precintos registrados.')+'</p><h2>Envíos vinculados · estado actual</h2>'+table(['Envío','Estado del flujo','Creado UTC','Actualizado UTC'],shipments)+'<p>Los envíos son una selección actual, no entregas confirmadas dentro del período. '+escape(data.hasMore.shipments?'Hay más envíos vinculados fuera de esta selección.':'')+'</p><footer><h2>Integridad de esta consulta</h2><code>'+sha256+'</code><p>SHA-256 del objeto de datos JSON. No es firma digital, prueba de blockchain ni certificación física. Consultar cambios posteriores desde el sistema.</p></footer></html>';
 return {html,json:JSON.stringify({schema:'nexid.trace-export.v1',sha256,data},null,2),sha256};
}
