export const customerActivityCopy = {
  "es-AR": {
    title: "Actividad recibida", workspace: "Bandeja de trabajo", scope: "Empresa", global: "Vista global autorizada", demo: "Datos ilustrativos",
    hint: "Muestra cargada por cada fuente, no el historial completo. Prospectos, tickets y pedidos son registros distintos; no representan etapas de conversión.",
    limits: "No se infieren reuniones, ventas ganadas, ingresos ni personas únicas a partir del texto o del estado de un registro.",
    filterHint: "La búsqueda filtra las bandejas, no estos conteos. Abrir una bandeja desde aquí limpia la búsqueda local.",
    leads: "Prospectos", tickets: "Tickets de soporte", orders: "Solicitudes de pedido",
    production: "Fuente operativa", loaded: "Registros cargados", empty: "La fuente confirmó una muestra vacía.",
    access_denied: "Sin permiso para consultar esta fuente.", upstream_error: "La fuente no pudo responder. No se conoce el conteo.",
    unreachable: "No se pudo conectar con la fuente. No se conoce el conteo.", invalid_payload: "Datos sin confirmar para este contexto. No se muestra un conteo.",
    statuses: "Estados registrados", missing: "Sin estado informado", literal: "Estado literal de la fuente",
    openLeads: "Abrir prospectos", openTickets: "Abrir tickets", openOrders: "Abrir pedidos",
  },
  en: {
    title: "Received activity", workspace: "Work inbox", scope: "Company", global: "Authorized global view", demo: "Illustrative data",
    hint: "The loaded sample from each source, not the complete history. Prospects, tickets and order requests are different records, not conversion stages.",
    limits: "Meetings, won sales, revenue and unique people are not inferred from a record's text or status.",
    filterHint: "Search filters the inboxes, not these counts. Opening an inbox here clears the local search.",
    leads: "Prospects", tickets: "Support tickets", orders: "Order requests",
    production: "Operational source", loaded: "Loaded records", empty: "The source confirmed an empty sample.",
    access_denied: "No permission to read this source.", upstream_error: "The source could not respond. Its count is unknown.",
    unreachable: "The source could not be reached. Its count is unknown.", invalid_payload: "Data is unconfirmed for this context. No count is shown.",
    statuses: "Recorded statuses", missing: "Status not provided", literal: "Literal source status",
    openLeads: "Open prospects", openTickets: "Open tickets", openOrders: "Open orders",
  },
  "pt-BR": {
    title: "Atividade recebida", workspace: "Caixa de trabalho", scope: "Empresa", global: "Visão global autorizada", demo: "Dados ilustrativos",
    hint: "Amostra carregada de cada fonte, não o histórico completo. Prospectos, tickets e pedidos são registros diferentes, não etapas de conversão.",
    limits: "Reuniões, vendas ganhas, receita e pessoas únicas não são inferidas do texto ou do estado de um registro.",
    filterHint: "A busca filtra as caixas, não estas contagens. Abrir uma caixa aqui limpa a busca local.",
    leads: "Prospectos", tickets: "Tickets de suporte", orders: "Solicitações de pedido",
    production: "Fonte operacional", loaded: "Registros carregados", empty: "A fonte confirmou uma amostra vazia.",
    access_denied: "Sem permissão para consultar esta fonte.", upstream_error: "A fonte não respondeu. A contagem é desconhecida.",
    unreachable: "Não foi possível conectar à fonte. A contagem é desconhecida.", invalid_payload: "Dados não confirmados para este contexto. Nenhuma contagem é exibida.",
    statuses: "Estados registrados", missing: "Estado não informado", literal: "Estado literal da fonte",
    openLeads: "Abrir prospectos", openTickets: "Abrir tickets", openOrders: "Abrir pedidos",
  },
} as const;
