export const customerInboxCopy = {
  "es-AR": {
    tabs: "Bandejas de atención", signals: "Señales de cliente", opportunities: "Intereses comerciales", prospects: "Prospectos", tickets: "Tickets de soporte", orders: "Solicitudes de pedido", ai_queries: "Registros del asistente",
    search: "Buscar señales por referencia, contacto o detalle", searchPlaceholder: "Referencia, contacto o detalle", missing: "No informado", unknownCount: "conteo sin confirmar",
    assistantTitle: "Registros capturados por el asistente", assistantHint: "Se muestran los prospectos cargados cuyo canal declarado corresponde al asistente. No es un historial completo de conversaciones.",
    responseBoundary: "La fuente consultada no conserva la respuesta enviada: una pregunta, nota o estado del prospecto no confirma una respuesta de IA ni su entrega.",
    recorded: "Registros cargados", matching: "Coinciden con la búsqueda", noRecords: "La fuente no informó registros del asistente en esta muestra.", noMatches: "No hay coincidencias en los registros cargados.",
    question: "Consulta registrada", notes: "Notas del registro", status: "Estado del prospecto", interest: "Interés declarado", channel: "Canal declarado", reference: "Referencia", date: "Fecha registrada", company: "Empresa", contact: "Contacto",
    demo: "Datos ilustrativos", production: "Fuente operativa", page: "Página", previous: "Anterior", next: "Siguiente", pageHint: "La paginación recorre solo esta muestra cargada.",
    access_denied: "Esta sesión no tiene permiso para consultar la fuente.", upstream_error: "La fuente devolvió un error. El conteo no está disponible.", unreachable: "No se pudo conectar con la fuente. El conteo no está disponible.", invalid_payload: "La fuente no confirmó datos válidos para esta empresa y modo de trabajo.",
    unavailableTitle: "Bandeja sin datos confirmados", retry: "Reintentar carga", reloading: "Actualizando fuentes…", recovery: "Reintentar consulta las fuentes con la misma sesión y empresa; no modifica registros.", clear: "Limpiar búsqueda", ticketHint: "La búsqueda filtra los tickets cargados. La consulta exacta permite buscar por referencia completa.", signalHint: "La búsqueda filtra hasta las 80 señales cargadas más recientes.",
  },
  en: {
    tabs: "Customer inboxes", signals: "Customer signals", opportunities: "Commercial interests", prospects: "Prospects", tickets: "Support tickets", orders: "Order requests", ai_queries: "Assistant records",
    search: "Search signals by reference, contact or detail", searchPlaceholder: "Reference, contact or detail", missing: "Not provided", unknownCount: "unconfirmed count",
    assistantTitle: "Records captured through the assistant", assistantHint: "Loaded prospects with a declared assistant channel. This is not a complete conversation history.",
    responseBoundary: "This source does not retain the sent answer: a question, note or prospect status does not confirm an AI response or its delivery.",
    recorded: "Loaded records", matching: "Matching search", noRecords: "The source returned no assistant records in this sample.", noMatches: "No matching records in the loaded sample.",
    question: "Recorded query", notes: "Record notes", status: "Prospect status", interest: "Declared interest", channel: "Declared channel", reference: "Reference", date: "Recorded date", company: "Company", contact: "Contact",
    demo: "Illustrative data", production: "Operational source", page: "Page", previous: "Previous", next: "Next", pageHint: "Pagination covers only the loaded sample.",
    access_denied: "This session cannot read the source.", upstream_error: "The source returned an error. Its count is unavailable.", unreachable: "The source could not be reached. Its count is unavailable.", invalid_payload: "The source did not confirm valid data for this company and mode.",
    unavailableTitle: "Inbox without confirmed data", retry: "Retry loading", reloading: "Refreshing sources…", recovery: "Retry reads the sources with the same session and company; it does not change records.", clear: "Clear search", ticketHint: "Search filters loaded tickets. Exact lookup accepts a complete reference.", signalHint: "Search filters up to the 80 most recent loaded signals.",
  },
  "pt-BR": {
    tabs: "Caixas de atendimento", signals: "Sinais de clientes", opportunities: "Interesses comerciais", prospects: "Prospectos", tickets: "Tickets de suporte", orders: "Solicitações de pedido", ai_queries: "Registros do assistente",
    search: "Buscar sinais por referência, contato ou detalhe", searchPlaceholder: "Referência, contato ou detalhe", missing: "Não informado", unknownCount: "contagem não confirmada",
    assistantTitle: "Registros capturados pelo assistente", assistantHint: "Prospectos carregados com canal declarado do assistente. Não é um histórico completo de conversas.",
    responseBoundary: "Esta fonte não preserva a resposta enviada: pergunta, nota ou estado do prospecto não confirma resposta de IA nem sua entrega.",
    recorded: "Registros carregados", matching: "Correspondem à busca", noRecords: "A fonte não informou registros do assistente nesta amostra.", noMatches: "Nenhum registro corresponde à busca na amostra carregada.",
    question: "Consulta registrada", notes: "Notas do registro", status: "Estado do prospecto", interest: "Interesse declarado", channel: "Canal declarado", reference: "Referência", date: "Data registrada", company: "Empresa", contact: "Contato",
    demo: "Dados ilustrativos", production: "Fonte operacional", page: "Página", previous: "Anterior", next: "Próxima", pageHint: "A paginação percorre somente a amostra carregada.",
    access_denied: "Esta sessão não tem permissão para consultar a fonte.", upstream_error: "A fonte retornou um erro. A contagem está indisponível.", unreachable: "Não foi possível conectar à fonte. A contagem está indisponível.", invalid_payload: "A fonte não confirmou dados válidos para esta empresa e modo.",
    unavailableTitle: "Caixa sem dados confirmados", retry: "Tentar carregar novamente", reloading: "Atualizando fontes…", recovery: "A nova tentativa consulta as fontes com a mesma sessão e empresa; não altera registros.", clear: "Limpar busca", ticketHint: "A busca filtra tickets carregados. A consulta exata aceita a referência completa.", signalHint: "A busca filtra até os 80 sinais carregados mais recentes.",
  },
} as const;
