/** Public release metadata, not physical product certification. */
export const DASHBOARD_RELEASE="2026.09.18-dashboard.10";
export const DASHBOARD_RELEASE_DATE="2026-09-18";
export const RELEASE_NOTES={
 "es-AR":{
 link:"Novedades y versión",eyebrow:"Passport Studio · contenido gobernado",title:"Del borrador al pasaporte publicado.",summary:"Editor integrado al expediente del lote: guardado real, comparación, revisión independiente y publicación con historial. El contenido visible no cambia mientras escribís.",back:"Abrir rollos y productos",site:"Sitio de nexID",label:"Versión de esta interfaz",changes:"Qué cambió",guide:"Cómo probar esta entrega",
 steps:["Elegí un lote en Rollos y productos y abrí Passport Studio desde Producto.","Confirmá la activación editorial y editá el borrador. Guardar no publica.","Enviá a revisión. Otro usuario autorizado debe aprobar el contenido guardado.","Publicá la versión aprobada; el historial permite preparar otra revisión sin reemplazar silenciosamente lo vigente."],
 boundary:"La activación es por lote y protege la edición directa anterior. Revisión editorial no equivale a autenticidad NFC, aprobación de calidad ni verificación legal de documentos. Se conservan los datos de otros rubros, aunque sus campos avanzados aún no se editan aquí.",
 cards:[
 {title:"Edición y vista previa juntas",text:"Identidad, perfil agro, documentos y soporte con vista móvil. El editor diferencia borrador, referencia inicial y contenido publicado, sin simular un TAP.",tag:"UX editorial"},
 {title:"Guardado que se puede comprobar",text:"Borradores y movimientos se guardan en PostgreSQL. Un intento repetido conserva su identificación y no crea otra revisión. Los conflictos no pisan el trabajo ajeno.",tag:"Persistencia real"},
 {title:"Revisión independiente",text:"Crear, editar o presentar un borrador impide autoaprobarlo. Revisión y publicación tienen permisos propios; no se habilitan cuentas ni permisos automáticamente.",tag:"Control por roles"},
 {title:"Publicación e historial",text:"La publicación confirma revisión y contenido, actualiza solo campos públicos y conserva los técnicos. Recuperar contenido anterior prepara un borrador; no lo publica por sí solo.",tag:"Trazabilidad"}],
 },
 en:{
 link:"What's new and version",eyebrow:"Passport Studio · governed content",title:"From draft to published passport.",summary:"An editor inside the batch dossier with persisted drafts, comparison, independent review and versioned publication.",back:"Open rolls and products",site:"nexID website",label:"This interface version",changes:"What's changed",guide:"Try this release",
 steps:["Select a batch and open Passport Studio from Product.","Confirm editorial enrollment and edit a draft; saving does not publish.","Submit for review by another authorized person.","Publish the approved revision or prepare a new draft from history."],
 boundary:"Enrollment is per batch and protects the legacy editor. Editorial review is not NFC authentication, physical quality approval or legal validation. Advanced fields outside the first templates are preserved but not editable here.",
 cards:[{title:"Edit and preview",text:"Shared identity, agro fields, documents and support next to a mobile preview. Draft, initial reference and published content stay distinct.",tag:"Editorial UX"},{title:"Verified persistence",text:"Draft and history commit to PostgreSQL. Identified retries do not create another revision and concurrent edits are rejected instead of overwriting.",tag:"Persistence"},{title:"Independent review",text:"Creators, last editors and submitters cannot self-approve. Review and publish permissions remain separate and are never assigned automatically.",tag:"Access control"},{title:"Publication and history",text:"Publication checks approval and current content while preserving technical configuration. Restoring old content creates draft work, not an immediate publication.",tag:"Traceability"}],
 },
 "pt-BR":{
 link:"Novidades e versão",eyebrow:"Passport Studio · conteúdo governado",title:"Do rascunho ao passaporte publicado.",summary:"Editor no dossiê do lote, com rascunho persistido, comparação, revisão independente e publicação com histórico.",back:"Abrir rolos e produtos",site:"Site da nexID",label:"Versão desta interface",changes:"O que mudou",guide:"Como testar esta entrega",
 steps:["Escolha um lote e abra Passport Studio em Produto.","Confirme a ativação editorial e edite o rascunho; salvar não publica.","Envie para revisão por outra pessoa autorizada.","Publique a versão aprovada ou prepare outra revisão pelo histórico."],
 boundary:"A ativação é por lote e protege a edição direta anterior. Revisão editorial não é autenticação NFC, aprovação física ou validação legal. Campos avançados de outros modelos são preservados, mas ainda não são editados aqui.",
 cards:[{title:"Editor com prévia móvel",text:"Identidade, perfil agro, documentos e suporte ao lado da prévia. Rascunho, referência inicial e conteúdo publicado ficam distintos.",tag:"UX editorial"},{title:"Persistência verificável",text:"Rascunhos e histórico são gravados no PostgreSQL. Repetir uma tentativa identificada não cria outra revisão; conflitos não sobrescrevem o trabalho alheio.",tag:"Persistência"},{title:"Revisão independente",text:"Quem criou, editou por último ou enviou o rascunho não pode aprová-lo. Revisão e publicação mantêm permissões distintas.",tag:"Controle de acesso"},{title:"Publicação com histórico",text:"A publicação verifica a aprovação e atualiza apenas campos públicos. Recuperar conteúdo antigo prepara um rascunho, sem publicar automaticamente.",tag:"Rastreabilidade"}],
 },
} as const;
export function releaseCopy(locale:string){return RELEASE_NOTES[locale==="en"||locale==="pt-BR"?locale:"es-AR"];}
