export const QUEUE_STATES={draft:'Borrador',changes_requested:'Cambios solicitados',in_review:'En revisión',approved:'Aprobado',published:'Publicado'} as const;
export type QueueState=keyof typeof QUEUE_STATES;
export const QUEUE_STEPS={edit:{label:'Continuar edición',role:'Equipo editor',detail:'Revisá el contenido, corregí lo pendiente y enviá la revisión desde Passport Studio.'},review:{label:'Revisar contenido',role:'Revisor independiente',detail:'La cuenta no figura entre quienes crearon, editaron o presentaron esta revisión. Abrí Studio para comparar y decidir.'},publish:{label:'Revisar publicación',role:'Responsable de publicación',detail:'El contenido tiene una revisión aprobada. La publicación y su comprobante se confirman únicamente en Studio.'},needs_editor:{label:'Consultar borrador',role:'Equipo editor',detail:'La cuenta actual puede consultar, pero la siguiente edición requiere permiso editorial.'},needs_independent_review:{label:'Esperando otra cuenta',role:'Revisor independiente',detail:'Participaste en este contenido. No podés autoaprobar la revisión; otra cuenta autorizada debe revisarla.'},needs_reviewer:{label:'Esperando revisión',role:'Revisor independiente',detail:'La siguiente decisión requiere una cuenta con permiso de revisión editorial.'},needs_publisher:{label:'Esperando publicación',role:'Responsable de publicación',detail:'Otra cuenta con permiso de publicación debe confirmar la salida pública en Studio.'},published:{label:'Consultar publicación',role:'Sin paso pendiente',detail:'La revisión está publicada. Para cambiar su contenido se prepara una nueva revisión, sin reemplazar silenciosamente la anterior.'}} as const;
export type QueueFilters={state:string;view:'all'|'mine';q:string};
export const INITIAL_QUEUE_FILTERS:QueueFilters={state:'',view:'all',q:''};
export type QueueItem={id:string;bid:string;tenant:string;tenantName:string;product:string|null;state:QueueState;revision:number;publishedVersion:number;template:'general'|'agro';locale:'es-AR'|'en'|'pt-BR';updatedAt:string;lastChange:{actorLabel:string;note:string|null;action:string;at:string}|null;code:keyof typeof QUEUE_STEPS;forActor:boolean};
export type EditorialQueue={ok:true;protocol:'nexid.editorial-queue.v1';source:'database';observedAt:string;scope:{tenant:string;mode:'tenant'|'global'};filters:QueueFilters;summary:{total:number;byState:Record<QueueState,number>;forActor:number;basis:'enrolled_passports_in_scope'};matched:number;items:QueueItem[];navigation:{page:number;pageSize:25;hasNext:boolean;nextCursor:string|null;order:'oldest_update_first';consistency:'live_queue_rechecked_on_each_request'};readOnly:true};
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
function assert(v:unknown):asserts v{if(!v)throw Error('La fuente no confirmó una bandeja válida para esta cuenta.');}
function number(v:unknown){assert(Number.isSafeInteger(v)&&Number(v)>=0);}
function text(v:unknown,max=180){assert(typeof v==='string'&&v.length<=max);}
export function parseEditorialQueue(raw:unknown,tenant:string,f:QueueFilters,expectedPage=1):EditorialQueue{
 const r=raw as EditorialQueue;assert(r?.ok===true&&r.protocol==='nexid.editorial-queue.v1'&&r.source==='database'&&r.readOnly===true&&r.scope?.tenant===tenant&&r.scope.mode===(tenant?'tenant':'global'));
 assert(Number.isFinite(Date.parse(r.observedAt)));assert(r.filters&&r.filters.state===f.state&&r.filters.q===f.q.trim()&&r.filters.view===f.view);assert(!r.filters.state||Object.hasOwn(QUEUE_STATES,r.filters.state));
 assert(r.summary?.basis==='enrolled_passports_in_scope');number(r.summary.total);number(r.summary.forActor);number(r.matched);assert(r.matched<=r.summary.total&&r.summary.forActor<=r.summary.total);
 let total=0;for(const k of Object.keys(QUEUE_STATES) as QueueState[]){number(r.summary.byState[k]);total+=r.summary.byState[k];}assert(total===r.summary.total);
 assert(Array.isArray(r.items)&&r.items.length<=25&&r.items.length<=r.matched);const seen=new Set<string>();
 for(const i of r.items){assert(uuid.test(i.id)&&!seen.has(i.id));seen.add(i.id);text(i.bid,160);text(i.tenant,120);text(i.tenantName,240);assert(!tenant||i.tenant===tenant);assert(i.product===null||typeof i.product==='string'&&i.product.length<=160);assert(Object.hasOwn(QUEUE_STATES,i.state)&&Object.hasOwn(QUEUE_STEPS,i.code));number(i.revision);assert(i.revision>0);number(i.publishedVersion);assert(['general','agro'].includes(i.template)&&['es-AR','en','pt-BR'].includes(i.locale));assert(Number.isFinite(Date.parse(i.updatedAt))&&typeof i.forActor==='boolean');assert(!f.state||i.state===f.state);assert(f.view!=='mine'||i.forActor);
  const eligible=i.code==='edit'||i.code==='review'||i.code==='publish';assert(eligible===i.forActor);assert((i.state==='in_review'&&['review','needs_reviewer','needs_independent_review'].includes(i.code))||(i.state==='approved'&&['publish','needs_publisher'].includes(i.code))||(i.state==='published'&&i.code==='published')||(['draft','changes_requested'].includes(i.state)&&['edit','needs_editor'].includes(i.code)));
  if(i.lastChange){text(i.lastChange.actorLabel);assert(['start','save','submit','request_changes','approve','publish','reopen'].includes(i.lastChange.action));assert(Number.isFinite(Date.parse(i.lastChange.at)));assert(i.lastChange.note===null||i.lastChange.action==='request_changes'&&typeof i.lastChange.note==='string'&&i.lastChange.note.length<=800);}
 }
 const n=r.navigation;assert(n?.page===expectedPage&&n.pageSize===25&&typeof n.hasNext==='boolean'&&n.order==='oldest_update_first'&&n.consistency==='live_queue_rechecked_on_each_request');assert(n.hasNext?typeof n.nextCursor==='string'&&/^[-_A-Za-z0-9]{1,1024}$/.test(n.nextCursor)&&r.items.length===25:n.nextCursor===null);return r;
}
export function queueParams(tenant:string,f:QueueFilters,cursor:string|null=null){const p=new URLSearchParams();if(tenant)p.set('tenant',tenant);if(f.q.trim())p.set('q',f.q.trim());if(f.state)p.set('state',f.state);if(f.view==='mine')p.set('view','mine');if(cursor)p.set('cursor',cursor);return p;}
export function queueStudioHref(item:Pick<QueueItem,'bid'|'tenant'>){return `/batches/${encodeURIComponent(item.bid)}/passport?${new URLSearchParams({tenant:item.tenant})}`;}
export function queueDate(value:string){return new Intl.DateTimeFormat('es-AR',{timeZone:'UTC',dateStyle:'medium',timeStyle:'short'}).format(new Date(value))+' UTC';}
