import {readRecallJson} from './recall-workspace';
export {readRecallJson};
export type NoticeText={title:string;publicMessage:string;instructions:string;contact:string};
export type NoticeProposal={protocol:string;id:string;caseId:string;tenantId:string;batchId:string;kind:'correction'|'lift';state:'draft'|'in_review'|'changes_requested'|'applied'|'cancelled';version:number;baseCaseVersion:number;baseNoticeVersion:number;baseNotice:NoticeText;requestedNotice:NoticeText|null;resolutionMessage:string|null;reason:string;evidenceReference:string;contentDigest:string;contributorIds:string[];createdBy:string;createdAt:string;updatedAt:string;approvedAt:string|null;approvedBy:string|null};
export type NoticeBoard={ok:true;protocol:string;source:'database';scope:{tenant:string;bid:string;tenantId:string;batchId:string;caseId:string};product:string;tenantName:string;observedAt:string;effectiveAt:string;kind:'recall'|'quarantine';resolutionMessage:string|null;current:{tenantId:string;batchId:string;caseId:string;caseVersion:number;noticeVersion:number;trackingState:'active'|'closing'|'closed';publishedAt:string;noticeState:'active'|'lifted';notice:NoticeText};actor:{id:string;label:string;role:string;mfaVerified:boolean;canRead:boolean;canWrite:boolean;canPublish:boolean;canExport:boolean};proposals:NoticeProposal[];hasMore:boolean;history:{id:string;proposal_id:string;actor_label:string;action:string;created_at:string;version:string;kind:string;state:string;reason:string|null;evidence_reference:string|null}[];historyTruncated:boolean};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const states=['draft','in_review','changes_requested','applied','cancelled'];
const assert=(value:unknown,message:string)=>{if(!value)throw Error(message);};
const text=(v:unknown,max:number)=>typeof v==='string'&&v.length<=max;
function notice(v:any){assert(v&&text(v.title,160)&&text(v.publicMessage,600)&&text(v.instructions,1000)&&text(v.contact,200),'Texto de aviso inválido.');}
export function readProposal(p:any,scope:NoticeBoard['scope']):NoticeProposal{
 assert(p&&p.protocol==='nexid.recall-notice-review.v1'&&UUID.test(p.id)&&p.caseId===scope.caseId&&p.tenantId===scope.tenantId&&p.batchId===scope.batchId,'La propuesta no corresponde al expediente.');
 assert(['correction','lift'].includes(p.kind)&&states.includes(p.state)&&Number.isSafeInteger(p.version)&&p.version>0&&Number.isSafeInteger(p.baseCaseVersion)&&p.baseCaseVersion>0&&Number.isSafeInteger(p.baseNoticeVersion)&&p.baseNoticeVersion>0,'Versión de propuesta inválida.');
 notice(p.baseNotice);if(p.kind==='correction')notice(p.requestedNotice);else assert(text(p.resolutionMessage,1000),'Resolución inválida.');
 assert(text(p.reason,1000)&&text(p.evidenceReference,400)&&/^[a-f0-9]{64}$/.test(p.contentDigest)&&Array.isArray(p.contributorIds)&&p.contributorIds.length>0&&p.contributorIds.length<=100&&p.contributorIds.every((id:string)=>UUID.test(id))&&UUID.test(p.createdBy)&&p.contributorIds.includes(p.createdBy)&&Number.isFinite(Date.parse(p.updatedAt)),'Evidencia de propuesta inválida.');return p;
}
export function parseNoticeBoard(raw:any,bid:string,tenant:string,caseId:string):NoticeBoard{
 assert(raw?.ok===true&&raw.protocol==='nexid.recall-notice-workspace.v1'&&raw.source==='database'&&raw.scope?.bid===bid&&raw.scope.tenant===tenant&&raw.scope.caseId===caseId&&UUID.test(raw.scope.tenantId)&&UUID.test(raw.scope.batchId),'Fuente o alcance sin confirmar.');
 const c=raw.current;assert(c?.tenantId===raw.scope.tenantId&&c.batchId===raw.scope.batchId&&c.caseId===caseId&&['active','lifted'].includes(c.noticeState)&&['active','closing','closed'].includes(c.trackingState)&&Number.isSafeInteger(c.caseVersion)&&c.caseVersion>0&&Number.isSafeInteger(c.noticeVersion)&&c.noticeVersion>0,'Estado del aviso inválido.');notice(c.notice);
 assert(raw.actor?.canRead===true&&UUID.test(raw.actor.id)&&['canWrite','canPublish','canExport','mfaVerified'].every(k=>typeof raw.actor[k]==='boolean'),'Permisos no confirmados.');
 assert(Array.isArray(raw.proposals)&&raw.proposals.length<=20&&Array.isArray(raw.history)&&raw.history.length<=100&&Number.isFinite(Date.parse(raw.observedAt))&&Number.isFinite(Date.parse(raw.effectiveAt)),'Historial no confirmado.');
 raw.proposals.forEach((p:any)=>readProposal(p,raw.scope));assert(c.noticeState!=='lifted'||text(raw.resolutionMessage,1000),'Falta la resolución visible.');return raw;
}
export function noticeReceipt(raw:any,body:any,action:string,scope:NoticeBoard['scope']){
 assert(raw?.ok===true&&raw.protocol==='nexid.recall-notice-workspace.v1'&&(['tenant','bid','caseId','tenantId','batchId'] as const).every(k=>raw.scope?.[k]===scope[k]),'Alcance del comprobante inválido.');
 const p=readProposal(raw.review,scope),r=raw.receipt;
 assert(p.id===body.proposalId&&p.version===body.expectedReviewVersion+1&&r?.operationId===body.operationId&&r.action===action&&r.proposalId===p.id&&r.reviewVersion===p.version&&r.committed===true&&typeof r.replayed==='boolean'&&UUID.test(r.id),'La respuesta no confirma la operación.');
 if(action==='approve')assert(p.state==='applied'&&raw.effect?.nextNoticeVersion===body.expectedNoticeVersion+1&&raw.effect?.doesNotReleaseProduct===true&&raw.caseVersion===body.expectedCaseVersion+1,'No se confirmó el efecto público.');return {proposal:p,receipt:r};
}
export function sourceChanged(b:NoticeBoard,p:NoticeProposal){return p.baseCaseVersion!==b.current.caseVersion||p.baseNoticeVersion!==b.current.noticeVersion||(['title','publicMessage','instructions','contact'] as const).some(k=>p.baseNotice[k]!==b.current.notice[k]);}
export const PROPOSAL_LABELS={draft:'Borrador',in_review:'En revisión',changes_requested:'Correcciones solicitadas',applied:'Aplicada',cancelled:'Cancelada'};
export const NOTICE_FIELDS={title:'Título público',publicMessage:'Mensaje del aviso',instructions:'Instrucciones al consumidor',contact:'Contacto público'} as const;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function noticeReport(b:NoticeBoard){return `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aviso y revisiones · nexID</title><style>body{font:14px/1.8 system-ui;color:#16394b;margin:32px auto;max-width:1050px;padding:0 18px}h1{font-size:30px}article{padding:18px;border:1px solid #cadae3;border-radius:12px;margin:16px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:10px;border-bottom:1px solid #cfdee5;font-size:12px;vertical-align:top}small{color:#496675}@media print{article{break-inside:avoid}}</style><h1>Aviso del producto y revisiones</h1><p>${esc(b.tenantName)} · ${esc(b.product)} · ${esc(b.scope.bid)}</p><p>Consulta ${esc(b.observedAt)} · aviso v${b.current.noticeVersion} · expediente r${b.current.caseVersion}</p><article><strong>${b.current.noticeState==='lifted'?'Aviso levantado con resolución':'Aviso vigente'}</strong>${Object.entries(NOTICE_FIELDS).map(([k,v])=>`<h3>${esc(v)}</h3><pre>${esc(b.current.notice[k as keyof NoticeText])}</pre>`).join('')}${b.resolutionMessage?`<h3>Resolución pública</h3><pre>${esc(b.resolutionMessage)}</pre>`:''}</article><p>Rectificar o levantar este aviso no libera existencias, certifica inocuidad ni modifica autenticidad NFC o precintos. La base de evidencia son registros declarados por responsables autorizados.</p><h2>Propuestas consultadas</h2><p>${b.hasMore?'Últimas 20 propuestas; historial parcial.':'Propuestas disponibles en esta consulta.'}</p>${b.proposals.map(p=>`<article><h3>${p.kind==='lift'?'Levantamiento':'Rectificación'} · ${esc(PROPOSAL_LABELS[p.state])} · r${p.version}</h3><p>Base: expediente r${p.baseCaseVersion}, aviso v${p.baseNoticeVersion}.</p><pre>${esc(p.reason)}</pre><p>Evidencia: ${esc(p.evidenceReference)}</p><table><thead><tr><th>Campo</th><th>Antes</th><th>Propuesto</th></tr></thead><tbody>${Object.entries(NOTICE_FIELDS).map(([k,v])=>`<tr><td>${esc(v)}</td><td>${esc(p.baseNotice[k as keyof NoticeText])}</td><td>${esc(p.requestedNotice?.[k as keyof NoticeText]||p.baseNotice[k as keyof NoticeText])}</td></tr>`).join('')}</tbody></table>${p.resolutionMessage?`<p>Resolución: ${esc(p.resolutionMessage)}</p>`:''}<small>Propuesta ${esc(p.id)} · aprobada por ${esc(p.approvedBy||'Sin aprobar')}</small></article>`).join('')}<h2>Operaciones</h2><p>${b.historyTruncated?'Últimos 100 movimientos.':'Movimientos disponibles en esta consulta.'} Fuente: product_recall_notice_reviews / product_recall_notice_operations.</p><table><tbody>${b.history.map(h=>`<tr><td>${esc(h.created_at)}</td><td>${esc(h.action)}</td><td>${esc(h.actor_label)}</td><td>${esc(h.reason)}<br>${esc(h.evidence_reference)}</td></tr>`).join('')}</tbody></table><p>Este informe no es una firma digital ni una autorización de uso del producto.</p></html>`;}
