export const PILOT_REPORT_VERSION='nexid.pilot-evidence.v1';
export type PilotReport={schemaVersion:typeof PILOT_REPORT_VERSION;reportId:string;generatedAt:string;source:'persisted_database_snapshot';scope:{tenantId:string;tenantSlug:string;tenantName:string;bid:string|null};window:{from:string;to:string;start:string;endExclusive:string;days:number;timeZone:'UTC';effectiveEnd:string};inventory:{basis:'current_snapshot';batches:number;registered:number;active:number;inactive:number;other:number};interactions:{basis:'period_persisted_real';events:number;nfcAttempts:number;verifiedNfc:number;nfcUnconfirmed:number;identityViews:number;other:number;replaySignals:number;sealClosed:number;sealOpened:number;sealUnknown:number;verifiedLinked:number;verifiedUnits:number};incidents:{basis:'created_in_period_current_state';created:number;resolved:number;dismissed:number;pending:number;other:number;timedResolved:number;medianResolutionSeconds:number|null};sdk:{basis:'not_attributed_to_batch'|'period_logged_requests';requests:number|null;success:number|null;clientErrors:number|null;serverErrors:number|null;other:number|null;latencySamples:number|null;p95Ms:number|null};exclusions:{candidates:number;nonReal:number;automated:number;unbound:number};daily:{day:string;events:number;verified:number;identity_views:number}[];unavailable:string[];rowLimit:number};
export type PilotEnvelope={ok:true;report:PilotReport;integrity:{algorithm:'SHA-256';digest:string;meaning:'content_integrity_not_digital_signature'}};
export function canonicalReport(value:unknown):string{if(Array.isArray(value))return '['+value.map(canonicalReport).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonicalReport((value as any)[k])).join(',')+'}';return JSON.stringify(value);}
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const KEYS={root:'schemaVersion reportId generatedAt source scope window inventory interactions incidents sdk exclusions daily unavailable rowLimit',scope:'tenantId tenantSlug tenantName bid',window:'from to start endExclusive days timeZone effectiveEnd',inventory:'basis batches registered active inactive other',interactions:'basis events nfcAttempts verifiedNfc nfcUnconfirmed identityViews other replaySignals sealClosed sealOpened sealUnknown verifiedLinked verifiedUnits',incidents:'basis created resolved dismissed pending other timedResolved medianResolutionSeconds',sdk:'basis requests success clientErrors serverErrors other latencySamples p95Ms',exclusions:'candidates nonReal automated unbound'};
function exact(value:any,keys:string){if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).sort().join(' ')!==keys.split(' ').sort().join(' '))throw new Error('pilot_contract_invalid');}
function count(v:unknown){if(typeof v!=='number'||!Number.isSafeInteger(v)||v<0||v>100000)throw new Error('pilot_count_invalid');}
function text(v:unknown,max:number){if(typeof v!=='string'||v.length>max)throw new Error('pilot_text_invalid');}
function stamp(v:unknown){if(typeof v!=='string'||new Date(v).toISOString()!==v)throw new Error('pilot_time_invalid');return Date.parse(v);}
export async function parsePilotEnvelope(raw:unknown,expected:{tenant:string;bid:string;from:string;to:string}):Promise<PilotEnvelope>{
 const e=raw as PilotEnvelope;exact(e,'ok report integrity');if(e.ok!==true)throw new Error('pilot_source_invalid');const r=e.report;exact(r,KEYS.root);
 for(const k of ['scope','window','inventory','interactions','incidents','sdk','exclusions'] as const)exact(r[k],KEYS[k]);
 exact(e.integrity,'algorithm digest meaning');if(e.integrity.algorithm!=='SHA-256'||e.integrity.meaning!=='content_integrity_not_digital_signature'||! /^[a-f0-9]{64}$/.test(e.integrity.digest))throw new Error('pilot_integrity_invalid');
 if(r.schemaVersion!==PILOT_REPORT_VERSION||r.source!=='persisted_database_snapshot'||!UUID.test(r.reportId)||!UUID.test(r.scope.tenantId)||r.scope.tenantSlug!==expected.tenant||(r.scope.bid||'')!==expected.bid||r.window.from!==expected.from||r.window.to!==expected.to)throw new Error('pilot_scope_mismatch');
 text(r.scope.tenantName,240);text(r.scope.tenantSlug,128);if(r.scope.bid!==null)text(r.scope.bid,160);
 const start=stamp(r.window.start),end=stamp(r.window.endExclusive),effective=stamp(r.window.effectiveEnd),generated=stamp(r.generatedAt);
 if(r.window.timeZone!=='UTC'||r.window.days<1||r.window.days>93||(end-start)/86400000!==r.window.days||r.window.start.slice(0,10)!==r.window.from||new Date(end-86400000).toISOString().slice(0,10)!==r.window.to||effective!==Math.min(end,generated)||effective<start)throw new Error('pilot_window_invalid');
 if(r.inventory.basis!=='current_snapshot'||r.interactions.basis!=='period_persisted_real'||r.incidents.basis!=='created_in_period_current_state'||r.sdk.basis!==(expected.bid?'not_attributed_to_batch':'period_logged_requests')||r.rowLimit!==100000)throw new Error('pilot_basis_invalid');
 for(const section of [r.inventory,r.interactions,r.exclusions])for(const [k,v] of Object.entries(section))if(k!=='basis')count(v);
 for(const [k,v] of Object.entries(r.incidents))if(k!=='basis'&&k!=='medianResolutionSeconds')count(v);
 for(const k of ['medianResolutionSeconds'] as const){const n=r.incidents[k];if(n!==null&&(typeof n!=='number'||!Number.isFinite(n)||n<0))throw new Error('pilot_duration_invalid');}
 for(const [k,v] of Object.entries(r.sdk))if(k!=='basis'&&k!=='p95Ms'){if(expected.bid){if(v!==null)throw new Error('pilot_sdk_scope');}else count(v);}
 if(expected.bid&&r.sdk.p95Ms!==null)throw new Error('pilot_sdk_scope');if(r.sdk.p95Ms!==null&&(typeof r.sdk.p95Ms!=='number'||!Number.isFinite(r.sdk.p95Ms)||r.sdk.p95Ms<0))throw new Error('pilot_duration_invalid');
 const inv=r.inventory,a=r.interactions,i=r.incidents,s=r.sdk,x=r.exclusions;
 if(inv.registered!==inv.active+inv.inactive+inv.other||a.events!==a.nfcAttempts+a.identityViews+a.other||a.nfcAttempts!==a.verifiedNfc+a.nfcUnconfirmed||a.verifiedNfc!==a.sealClosed+a.sealOpened+a.sealUnknown||a.verifiedLinked>a.verifiedNfc||a.verifiedUnits>a.verifiedLinked||a.verifiedUnits>inv.registered||a.replaySignals>a.nfcAttempts||i.created!==i.resolved+i.dismissed+i.pending+i.other||i.timedResolved>i.resolved||x.candidates!==a.events+x.nonReal+x.automated+x.unbound)throw new Error('pilot_denominator_invalid');
 if((i.timedResolved===0)!==(i.medianResolutionSeconds===null))throw new Error('pilot_duration_sample_invalid');
 if(!expected.bid&&(s.requests!==s.success!+s.clientErrors!+s.serverErrors!+s.other!||s.latencySamples!>s.requests!||(s.latencySamples===0)!==(s.p95Ms===null)))throw new Error('pilot_sdk_denominator');
 if(!Array.isArray(r.daily)||r.daily.length!==r.window.days)throw new Error('pilot_trend_invalid');let total=0,verified=0,views=0;
 r.daily.forEach((d,idx)=>{exact(d,'day events verified identity_views');if(d.day!==new Date(start+idx*86400000).toISOString().slice(0,10))throw new Error('pilot_trend_invalid');count(d.events);count(d.verified);count(d.identity_views);if(d.verified+d.identity_views>d.events)throw new Error('pilot_trend_invalid');total+=d.events;verified+=d.verified;views+=d.identity_views;});
 if(total!==a.events||verified!==a.verifiedNfc||views!==a.identityViews)throw new Error('pilot_trend_invalid');
 if(!Array.isArray(r.unavailable)||r.unavailable.join('|')!=='tap_uptime_before_persistence|historical_activation_count|sales_and_roi|person_identity_and_marketing_consent|document_usage_conversion|provider_invoice|completed_recall_workflow')throw new Error('pilot_limits_invalid');
 const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonicalReport(r)));const digest=[...new Uint8Array(hash)].map(v=>v.toString(16).padStart(2,'0')).join('');if(digest!==e.integrity.digest)throw new Error('pilot_integrity_mismatch');return e;
}
export function parsePilotOptions(raw:any,tenant:string,bound:boolean){exact(raw,'ok contract source tenantOptions batchOptions limit');if(raw.ok!==true||raw.contract!==PILOT_REPORT_VERSION||raw.source!=='database'||raw.limit!==100||!Array.isArray(raw.tenantOptions)||raw.tenantOptions.length>100||!Array.isArray(raw.batchOptions)||raw.batchOptions.length>100)throw new Error('pilot_options_invalid');
 for(const t of raw.tenantOptions){exact(t,'id slug name');if(!UUID.test(t.id)||typeof t.slug!=='string'||!/^[a-z0-9][a-z0-9._-]{0,127}$/.test(t.slug)||(bound&&t.slug!==tenant))throw new Error('pilot_scope_mismatch');text(t.name,240);}
 for(const b of raw.batchOptions){exact(b,'id bid product');if(!UUID.test(b.id)||!tenant)throw new Error('pilot_scope_mismatch');text(b.bid,160);text(b.product,240);}
 return raw as {ok:true;tenantOptions:{id:string;slug:string;name:string}[];batchOptions:{id:string;bid:string;product:string}[]};
}
export type EvidenceMetric={id:string;label:string;value:number|null;unit:'count'|'percent'|'seconds'|'ms';numerator:number|null;denominator:number|null;source:string;basis:string;note:string};
export function evidenceMetrics(r:PilotReport):EvidenceMetric[]{const a=r.interactions,i=r.incidents,s=r.sdk,metrics:EvidenceMetric[]=[],sdkBasis=s.basis==='not_attributed_to_batch'?'no atribuible al lote':'período / empresa';
 const add=(id:string,label:string,value:number|null,unit:EvidenceMetric['unit'],source:string,basis:string,note:string,numerator:number|null=null,denominator:number|null=null)=>metrics.push({id,label,value,unit,source,basis,note,numerator,denominator});
 add('verified','Lecturas NFC verificadas',a.verifiedNfc,'count','events','período','TAP_VALID, veredicto válido, CMAC correcto, allowlist y resultado canónico permitido.');
 add('verified_ratio','Verificación entre intentos NFC',a.nfcAttempts?a.verifiedNfc/a.nfcAttempts*100:null,'percent','events','período','No mide disponibilidad del servicio ni visitas sin persistir.',a.verifiedNfc,a.nfcAttempts);
 add('identity_views','Visitas de identidad sin autenticación',a.identityViews,'count','events','período','PROVENANCE_VIEWED con identidad registrada; no es autenticación NFC.');
 add('units','Unidades registradas con lectura verificada',a.verifiedUnits,'count','events + tags','período y vínculo actual','Identificadores de etiquetas distintas, no personas. Sólo vínculos a la etiqueta del mismo lote.');
 add('closed','Mensajes verificados que reportan cerrado',a.sealClosed,'count','events','período','Estado reportado por lectura; no certifica que todas las unidades sigan cerradas.');
 add('opened','Mensajes verificados que reportan apertura',a.sealOpened,'count','events','período','Puede repetir la misma unidad. Una apertura no implica que la etiqueta sea falsa.');
 add('unknown','Lecturas verificadas sin estado abierto/cerrado',a.sealUnknown,'count','events','período','Conserva explícitamente evidencia de precinto no concluyente.');
 add('replay','Señales registradas de repetición',a.replaySignals,'count','events','período','No equivalen a una cantidad de fraudes confirmados.');
 add('active','Etiquetas activas ahora',r.inventory.active,'count','tags + batches','instantánea al generar','No representa cuántas fueron activadas durante el período.');
 add('inactive','Etiquetas inactivas conservadas',r.inventory.inactive,'count','tags + batches','instantánea al generar','No borra ni reactiva registros históricos.');
 add('cases','Incidentes creados en el período',i.created,'count','event_incidents + events','cohorte del período','Sólo incidentes vinculados a eventos reales de esta empresa/lote.');
 add('resolved','Incidentes de la cohorte resueltos',i.resolved,'count','event_incidents','estado actual de la cohorte','El estado se observa al generar; puede haber cambiado después del período.');
 add('resolution_ratio','Resolución actual de la cohorte',i.created?i.resolved/i.created*100:null,'percent','event_incidents','estado actual de la cohorte','Descartados no se suman a los resueltos.',i.resolved,i.created);
 add('dismissed','Incidentes descartados',i.dismissed,'count','event_incidents','estado actual de la cohorte','Descartar no demuestra corrección del problema.');
 add('pending','Incidentes aún abiertos o en atención',i.pending,'count','event_incidents','estado actual de la cohorte','Incluye abiertos, investigando y contenidos.');
 add('median','Mediana hasta resolución registrada',i.medianResolutionSeconds,'seconds','event_incidents','resueltos de la cohorte','Sólo casos actualmente resueltos con fechas consistentes; no mide tiempo activo de trabajo.',i.timedResolved,null);
 add('sdk','Solicitudes SDK registradas',s.requests,'count','sdk_usage_logs',sdkBasis,'No es factura de infraestructura ni el total de solicitudes SUN. Sin atribución por lote.');
 add('sdk_errors','Errores SDK 5xx registrados',s.serverErrors,'count','sdk_usage_logs',sdkBasis,'Sólo lo que llegó al registro de uso; no calcula uptime.');
 add('sdk_latency','Percentil 95 de latencia SDK registrada',s.p95Ms,'ms','sdk_usage_logs',sdkBasis,'Muestras con latencia no negativa; no mide latencia NFC extremo a extremo.',s.latencySamples,null);
 return metrics;
}
export function csvCell(value:unknown){let s=value==null?'':String(value);if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
export function pilotCsv(e:PilotEnvelope){const r=e.report;const header=['metric','label','value','unit','numerator','denominator','tenant','bid','period_from_utc','period_end_exclusive_utc','data_until_utc','snapshot_at_utc','source','basis','note','report_id','sha256'];const rows=evidenceMetrics(r).map(m=>[m.id,m.label,m.value,m.unit,m.numerator,m.denominator,r.scope.tenantSlug,r.scope.bid,r.window.start,r.window.endExclusive,r.window.effectiveEnd,r.generatedAt,m.source,m.basis,m.note,r.reportId,e.integrity.digest]);return '﻿'+[header,...rows].map(row=>row.map(csvCell).join(',')).join('\r\n')+'\r\n';}
export function metricValue(metric:Pick<EvidenceMetric,'value'|'unit'>){if(metric.value===null)return 'Sin base';if(metric.unit==='seconds')return new Intl.NumberFormat('es-AR',{maximumFractionDigits:1}).format(metric.value/3600)+' h';return new Intl.NumberFormat('es-AR',{maximumFractionDigits:metric.unit==='count'?0:1}).format(metric.value)+(metric.unit==='percent'?' %':metric.unit==='ms'?' ms':'');}
export function pilotHtml(e:PilotEnvelope){const r=e.report,escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));const rows=evidenceMetrics(r).map(m=>`<tr><td><b>${escape(m.label)}</b><small>${escape(m.note)}</small></td><td class="value">${escape(metricValue(m))}</td><td>${escape(m.numerator??'—')} / ${escape(m.denominator??'—')}</td><td>${escape(m.source)}<small>${escape(m.basis)}</small></td></tr>`).join('');
 return `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Informe del piloto · ${escape(r.scope.tenantName)}</title><style>body{margin:0;background:#f2f6fa;color:#173044;font:14px/1.6 system-ui,sans-serif}main{max-width:1080px;padding:36px;margin:24px auto;background:white;border:1px solid #d2e2eb;border-radius:16px}h1{font-size:32px;line-height:1.2;letter-spacing:-.035em}h2{font-size:18px;margin-top:30px}.brand{font-weight:850;font-size:24px;color:#047482}.meta{color:#526c7e}table{border-collapse:collapse;width:100%;font-size:12px}th{text-align:left;background:#edf7f8;color:#125c66}th,td{padding:12px;border-bottom:1px solid #d2e2eb;vertical-align:top}small{display:block;color:#526c7e;font-size:11px;line-height:1.5;margin-top:5px}.value{white-space:nowrap;font-weight:750}code{overflow-wrap:anywhere;font-size:10px}.note{padding:14px;background:#f1f8fa;border-left:3px solid #168a96}.footer{font-size:11px;color:#526c7e}@media print{body{background:white}main{margin:0;border:0;border-radius:0;padding:10px}thead{display:table-header-group}tr{break-inside:avoid}h2{break-after:avoid}a{color:inherit}}</style><main><div class="brand">nexID</div><h1>Informe del piloto</h1><h2>${escape(r.scope.tenantName)}</h2><p class="meta">${escape(r.scope.tenantSlug)} · ${escape(r.scope.bid||'Todos los lotes')}<br>Período: ${escape(r.window.from)} a ${escape(r.window.to)} inclusive · UTC<br>Datos del período hasta: ${escape(r.window.effectiveEnd)}<br>Instantánea generada: ${escape(r.generatedAt)}</p><p class="note">Datos persistidos y agregados. La autenticidad, el estado del precinto y el resultado comercial son dimensiones distintas. Este informe no demuestra ventas, rentabilidad ni cumplimiento de un retiro.</p><table><thead><tr><th>Indicador</th><th>Valor</th><th>Base / denominador</th><th>Fuente y alcance temporal</th></tr></thead><tbody>${rows}</tbody></table><h2>Cobertura y límites</h2><p>${r.exclusions.candidates} eventos candidatos. Excluidos: ${r.exclusions.nonReal} con fuente distinta de real; ${r.exclusions.automated} accesos automatizados detectados; ${r.exclusions.unbound} sin vínculo al lote autorizado.</p><p>El inventario y los estados de incidentes son actuales al generar, no un cierre histórico. No incluye disponibilidad antes de persistir, ventas/ROI, consentimiento comercial, uso efectivo de documentos, factura del proveedor ni circuito de retiro completo.</p><p class="footer">Informe ${escape(r.reportId)} · ${escape(r.schemaVersion)}<br>Integridad SHA-256 del objeto JSON report (no firma digital):<br><code>${escape(e.integrity.digest)}</code></p></main></html>`;
}
