export const ASSIGNED_TASK_PROTOCOL='nexid.recall-assigned-tasks.v1';
export type AssignedTask={caseId:string;destinationId:string;bid:string;tenant:string;tenantName:string;product:string;version:number;state:'active'|'closing'|'closed';kind:'recall'|'quarantine';publishedAt:string;updatedAt:string;notice:{version:number;state:'active'|'lifted';title:string;message:string;instructions:string;contact:string;resolution:string|null};recipient:string;unitLabel:string;assignedUnits:number;returnedUnits:number;heldUnits:number;acknowledgedAt:string|null;accountedAt:string|null;acknowledgedBySelf:boolean;canAcknowledge:boolean;canAccount:boolean};
export type TaskIdentity={id:string;label:string;canRespond:boolean};
export type AssignedTaskBoard={observedAt:string;actor:TaskIdentity;tasks:AssignedTask[];hasMore:boolean;includeClosed:boolean};
export type AssignedTaskDetail={observedAt:string;actor:TaskIdentity;task:AssignedTask;history:{id:string;action:'acknowledge'|'account';at:string;actorLabel:string;bySelf:boolean;source:'assigned_task'|'management_record';reference:string;reason:string;returnedUnits:number|null;heldUnits:number|null}[];historyTruncated:boolean};
export type TaskExpected={actorId:string;tenant:string|null};
const uuid=(v:unknown)=>{if(typeof v!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v))throw Error('Identidad de tarea inválida.');return v;};
const text=(v:unknown,max:number)=>{if(typeof v!=='string'||v.length>max)throw Error('Campo de tarea inválido.');return v;};
const count=(v:unknown,max=10000000)=>{if(!Number.isSafeInteger(v)||Number(v)<0||Number(v)>max)throw Error('Cantidad no confirmada.');return Number(v);};
const bool=(v:unknown)=>{if(typeof v!=='boolean')throw Error('Permiso no confirmado.');return v;};
const date=(v:unknown)=>{const s=text(v,40);if(!Number.isFinite(Date.parse(s))||!/(Z|[+-]\d{2}:\d{2})$/.test(s))throw Error('Fecha sin confirmar.');return s;};
function base(raw:any,e:TaskExpected){
 if(!raw||raw.ok!==true||raw.protocol!==ASSIGNED_TASK_PROTOCOL||raw.source!=='database'||raw.actor?.id!==e.actorId)throw Error('La fuente no corresponde a la cuenta actual.');
 return {observedAt:date(raw.observedAt),actor:{id:uuid(raw.actor.id),label:text(raw.actor.label,180),canRespond:bool(raw.actor.canRespond)}};
}
function task(t:any,e:TaskExpected,actor:TaskIdentity):AssignedTask{
 if(!t||!['active','closing','closed'].includes(t.state)||!['recall','quarantine'].includes(t.kind)||!t.notice||!['active','lifted'].includes(t.notice.state))throw Error('Estado de tarea no confirmado.');
 if(e.tenant&&t.tenant!==e.tenant)throw Error('La tarea pertenece a otra empresa.');
 const r:AssignedTask={caseId:uuid(t.caseId),destinationId:uuid(t.destinationId),bid:text(t.bid,160),tenant:text(t.tenant,120),tenantName:text(t.tenantName,180),product:text(t.product,500),version:count(t.version,1000000),state:t.state,kind:t.kind,publishedAt:date(t.publishedAt),updatedAt:date(t.updatedAt),notice:{version:count(t.notice.version),state:t.notice.state,title:text(t.notice.title,160),message:text(t.notice.message,600),instructions:text(t.notice.instructions,1000),contact:text(t.notice.contact,200),resolution:t.notice.resolution===null?null:text(t.notice.resolution,1000)},recipient:text(t.recipient,160),unitLabel:text(t.unitLabel,40),assignedUnits:count(t.assignedUnits),returnedUnits:count(t.returnedUnits),heldUnits:count(t.heldUnits),acknowledgedAt:t.acknowledgedAt===null?null:date(t.acknowledgedAt),accountedAt:t.accountedAt===null?null:date(t.accountedAt),acknowledgedBySelf:bool(t.acknowledgedBySelf),canAcknowledge:bool(t.canAcknowledge),canAccount:bool(t.canAccount)};
 if(!r.version||!r.notice.version||!r.assignedUnits||r.returnedUnits+r.heldUnits>r.assignedUnits||(r.canAcknowledge&&(!actor.canRespond||r.state!=='active'||r.acknowledgedAt))||(r.canAccount&&(!actor.canRespond||r.state!=='active'||!r.acknowledgedAt)))throw Error('Permisos o cantidades contradictorios.');
 return r;
}
export function parseAssignedBoard(raw:any,e:TaskExpected):AssignedTaskBoard{const b=base(raw,e);if(!Array.isArray(raw.tasks)||raw.tasks.length>50)throw Error('Listado de tareas fuera de límite.');return {...b,tasks:raw.tasks.map((t:any)=>task(t,e,b.actor)),hasMore:bool(raw.hasMore),includeClosed:bool(raw.includeClosed)};}
export function parseAssignedDetail(raw:any,e:TaskExpected,caseId:string,destinationId:string):AssignedTaskDetail{
 const b=base(raw,e),t=task(raw.task,e,b.actor);if(t.caseId!==caseId||t.destinationId!==destinationId||raw.evidenceBasis!=='assigned_account_declaration'||!Array.isArray(raw.history)||raw.history.length>50)throw Error('Respuesta ajena a la tarea seleccionada.');
 const history=raw.history.map((h:any)=>{if(!['acknowledge','account'].includes(h.action)||!['assigned_task','management_record'].includes(h.source))throw Error('Movimiento no confirmado.');return {id:uuid(h.id),action:h.action,at:date(h.at),actorLabel:text(h.actorLabel,180),bySelf:bool(h.bySelf),source:h.source,reference:text(h.reference,400),reason:text(h.reason,1000),returnedUnits:h.returnedUnits===null?null:count(h.returnedUnits),heldUnits:h.heldUnits===null?null:count(h.heldUnits)};});
 return {...b,task:t,history,historyTruncated:bool(raw.historyTruncated)};
}
export function assignedTaskCommand(t:AssignedTask,action:'acknowledge'|'account',input:{reason:string;reference:string;returned:string;held:string}){
 if(action==='acknowledge'?!t.canAcknowledge:!t.canAccount)throw Error('La tarea no admite esa acción.');
 const reason=input.reason.trim(),reference=input.reference.trim();if(reason.length<10||reason.length>1000||reference.length<5||reference.length>400)throw Error('Completá un motivo de al menos 10 caracteres y un comprobante de al menos 5.');
 const body:any={operationId:crypto.randomUUID(),caseId:t.caseId,destinationId:t.destinationId,expectedVersion:t.version,expectedNoticeVersion:t.notice.version,reason,evidenceReference:reference};
 if(action==='account'){if(!/^(0|[1-9][0-9]{0,7})$/.test(input.returned)||!/^(0|[1-9][0-9]{0,7})$/.test(input.held))throw Error('Ingresá totales enteros, sin signos ni decimales.');body.returnedUnits=Number(input.returned);body.heldUnits=Number(input.held);if(body.returnedUnits+body.heldUnits>t.assignedUnits)throw Error('Devueltas e inmovilizadas no pueden superar tu cantidad asignada.');}
 return body;
}
export function assignedReceipt(raw:any,body:any,action:string,e:TaskExpected){
 const r=raw?.receipt;if(!r||r.operationId!==body.operationId||r.caseId!==body.caseId||r.destinationId!==body.destinationId||r.action!==action||r.committed!==true||typeof r.replayed!=='boolean'||r.caseVersion!==body.expectedVersion+1)throw Error('No se pudo comprobar el guardado. Conservamos el intento.');uuid(r.id);
 const d=parseAssignedDetail(raw,e,body.caseId,body.destinationId);if(d.task.version<r.caseVersion)throw Error('La lectura es anterior al comprobante.');return {detail:d,replayed:r.replayed as boolean,receiptId:r.id as string};
}
export const taskLink=(t:{caseId:string;destinationId:string})=>'/tasks/recalls?'+new URLSearchParams({case:t.caseId,destination:t.destinationId});
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function assignedTaskReport(d:AssignedTaskDetail){const t=d.task;return `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Constancia de tarea · nexID</title><style>body{font:14px/1.8 system-ui;color:#173548;max-width:940px;margin:40px auto;padding:0 22px}h1{font-size:28px;line-height:1.3}header small{color:#446777}.notice{border-left:4px solid #b25d11;background:#fff5e7;padding:15px}td,th{text-align:left;vertical-align:top;border-bottom:1px solid #d9e2e8;padding:10px}table{width:100%;border-collapse:collapse;font-size:12px;overflow-wrap:anywhere}.stats{padding:15px;border:1px solid #cee2e7;border-radius:10px}p{white-space:pre-wrap}@media print{body{margin:0}tr{break-inside:avoid}}</style><header><small>NEXID · REGISTRO DE MI TAREA</small><h1>${esc(t.notice.title)}</h1><p>${esc(t.tenantName)} · ${esc(t.product)} · lote ${esc(t.bid)}</p><p>Destino: ${esc(t.recipient)} · cuenta consultante: ${esc(d.actor.label)}<br>Consulta: ${esc(d.observedAt)} · revisión ${t.version} · aviso v${t.notice.version}</p></header><div class="notice">Los acuses y cantidades son declaraciones de cuentas autenticadas. No certifican devolución física, autenticidad NFC ni liberación del producto.</div><h2>Instrucciones vigentes</h2><p>${esc(t.notice.message)}</p><p>${esc(t.notice.instructions)}</p><p>${esc(t.notice.contact)}</p>${t.notice.resolution?`<p>Resolución: ${esc(t.notice.resolution)}</p>`:''}<h2>Tu destino de seguimiento</h2><div class="stats">Asignadas: ${t.assignedUnits} · devueltas: ${t.returnedUnits} · inmovilizadas: ${t.heldUnits} · pendientes: ${t.assignedUnits-t.returnedUnits-t.heldUnits} ${esc(t.unitLabel)}.<br>Acuse: ${esc(t.acknowledgedAt||'Pendiente')} · estado del seguimiento: ${esc(t.state)}.</div><h2>Movimientos de este destino</h2><p>${d.historyTruncated?'Últimos 50 movimientos; historial parcial.':'Movimientos disponibles para este destino.'}</p><table><thead><tr><th>Fecha / acción</th><th>Cuenta y origen</th><th>Referencia / declaración</th></tr></thead><tbody>${d.history.map(h=>`<tr><td>${esc(h.at)}<br>${esc(h.action==='acknowledge'?'Acuse':'Totales acumulados')}</td><td>${esc(h.actorLabel)}<br>${h.source==='assigned_task'?'Cuenta asignada':'Registro de gestión'}</td><td>${esc(h.reference)}<br>${esc(h.reason)}${h.action==='account'?`<br>Devueltas: ${h.returnedUnits} · inmovilizadas: ${h.heldUnits}`:''}</td></tr>`).join('')}</tbody></table><footer><p>Este informe no es una firma digital. Caso ${esc(t.caseId)} · destino ${esc(t.destinationId)}. Fuente: product_recall_cases / product_recall_operations.</p></footer></html>`;}
