import type { TicketLookupLocale } from "./ticket-reference-lookup";

export const ticketLookupCopy = {
  "es-AR": {
    title: "Buscar por referencia", hint: "Pegá la referencia del reporte para consultar sus detalles, incluso si ya no aparece entre los tickets recientes.",
    recentHint: "El filtro de la lista busca entre los tickets cargados. Para una referencia anterior, usá Buscar por referencia.",
    label: "Referencia completa del ticket", search: "Buscar ticket", cancel: "Cancelar búsqueda", retry: "Reintentar búsqueda",
    invalid: "Revisá que la referencia esté completa y conserve sus guiones.", loading: "Buscando la referencia…", found: "Ticket encontrado", untitled: "Ticket registrado",
    not_found: "No encontramos esa referencia entre los tickets que tu cuenta puede consultar. Revisá la referencia y la organización seleccionada.",
    forbidden: "Tu sesión no permite consultar este ticket. Verificá tus permisos o volvé a iniciar sesión.",
    unconfirmed: "No pudimos confirmar el resultado. La referencia se conserva para reintentar; esto no significa que el ticket no exista.",
    demo: "La búsqueda de tickets reales no está disponible en modo demo.", denied: "Tu rol no tiene permiso para buscar tickets por referencia.",
    scope: "Organización seleccionada", global: "Todas las organizaciones autorizadas", reference: "Referencia consultada", status: "Estado actual", created: "Creado (UTC)", tenant: "Organización", contact: "Contacto informado", category: "Motivo informado",
    noContact: "No informado", open: "Abierto", pending: "Pendiente", closed: "Cerrado",
    unknownStatus: "Estado no informado o no reconocido", detailUnavailable: "El detalle registrado no está disponible en un formato compatible.", detailMissing: "Este ticket no tiene un detalle registrado.",
    tap_review: "Revisar la lectura", seal_opened: "Precinto abierto", product_problem: "Problema con el producto", other: "Otro motivo",
  },
  en: {
    title: "Find by reference", hint: "Paste the report reference to view its details, even if it no longer appears among recent tickets.",
    recentHint: "The list filter searches loaded tickets. For an older reference, use Find by reference.",
    label: "Complete ticket reference", search: "Find ticket", cancel: "Cancel search", retry: "Retry search",
    invalid: "Check that the reference is complete and keeps its hyphens.", loading: "Looking up the reference…", found: "Ticket found", untitled: "Recorded ticket",
    not_found: "We could not find this reference among the tickets your account can access. Check the reference and selected organization.",
    forbidden: "Your session cannot access this ticket. Check your permissions or sign in again.",
    unconfirmed: "We could not confirm the result. Your reference is kept for another attempt; this does not mean the ticket does not exist.",
    demo: "Real ticket lookup is unavailable in demo mode.", denied: "Your role cannot look up tickets by reference.",
    scope: "Selected organization", global: "All authorized organizations", reference: "Requested reference", status: "Current status", created: "Created (UTC)", tenant: "Organization", contact: "Provided contact", category: "Reported reason",
    noContact: "Not provided", open: "Open", pending: "Pending", closed: "Closed",
    unknownStatus: "Status not provided or not recognized", detailUnavailable: "The recorded details are unavailable in a compatible format.", detailMissing: "No details were recorded for this ticket.",
    tap_review: "Review the tap", seal_opened: "Opened seal", product_problem: "Product problem", other: "Other reason",
  },
  "pt-BR": {
    title: "Buscar por referência", hint: "Cole a referência do relato para consultar seus detalhes, mesmo que ele não apareça mais entre os tickets recentes.",
    recentHint: "O filtro da lista busca entre os tickets carregados. Para uma referência anterior, use Buscar por referência.",
    label: "Referência completa do ticket", search: "Buscar ticket", cancel: "Cancelar busca", retry: "Tentar novamente",
    invalid: "Confira se a referência está completa e mantém os hífens.", loading: "Buscando a referência…", found: "Ticket encontrado", untitled: "Ticket registrado",
    not_found: "Não encontramos essa referência entre os tickets que sua conta pode consultar. Confira a referência e a organização selecionada.",
    forbidden: "Sua sessão não permite consultar este ticket. Confira suas permissões ou entre novamente.",
    unconfirmed: "Não foi possível confirmar o resultado. A referência foi mantida para tentar novamente; isso não significa que o ticket não exista.",
    demo: "A busca de tickets reais não está disponível no modo demo.", denied: "Seu perfil não tem permissão para buscar tickets por referência.",
    scope: "Organização selecionada", global: "Todas as organizações autorizadas", reference: "Referência consultada", status: "Estado atual", created: "Criado (UTC)", tenant: "Organização", contact: "Contato informado", category: "Motivo informado",
    noContact: "Não informado", open: "Aberto", pending: "Pendente", closed: "Fechado",
    unknownStatus: "Estado não informado ou não reconhecido", detailUnavailable: "Os detalhes registrados não estão disponíveis em um formato compatível.", detailMissing: "Este ticket não tem detalhes registrados.",
    tap_review: "Revisar a leitura", seal_opened: "Lacre aberto", product_problem: "Problema com o produto", other: "Outro motivo",
  },
} satisfies Record<TicketLookupLocale, Record<string, string>>;
