export const ticketWorkflowCopy = {
  "es-AR": {
    heading: "Gestionar estado y ver historial", hint: "Registrá el avance de la atención con un motivo. Cambiar el estado no envía un mensaje al cliente ni confirma que un retiro de producto haya terminado.",
    load: "Consultar estado e historial", refresh: "Volver a consultar", loading: "Consultando el historial…", empty: "Todavía no hay cambios de estado registrados en este historial.",
    unavailable: "No pudimos consultar el historial. Podés volver a intentarlo.", denied: "Tu sesión no permite gestionar este ticket. Revisá tus permisos o volvé a iniciar sesión.",
    current: "Estado consultado", target: "Nuevo estado", reason: "Motivo del cambio", reasonHelp: "Contá qué se hizo o qué falta resolver (hasta 1.000 caracteres).",
    review: "Revisar cambio", reviewTitle: "Revisá antes de confirmar", confirm: "Confirmar cambio de estado", edit: "Volver al motivo", submitting: "Guardando el cambio…",
    invalid: "Elegí un estado diferente y escribí el motivo dentro del límite indicado.", unavailableAction: "No se pudo confirmar el cambio. El motivo se conserva.",
    uncertain: "No pudimos confirmar si el cambio se guardó. Reintentá la misma operación; por ahora conservamos el estado y el motivo sin editarlos para evitar duplicados.",
    retry: "Reintentar el mismo cambio", saved: "Cambio de estado confirmado. No se envió un mensaje al cliente.",
    conflict: "El ticket cambió o esta operación no coincide con la registrada. Volvé a consultar el estado antes de revisar otro cambio. Conservamos tu motivo.",
    reload: "Consultar el estado antes de continuar", reloadHint: "El motivo sigue en el formulario. Revisá el estado recién consultado antes de confirmar un cambio nuevo.",
    sticky: "Una operación anterior sigue sin confirmación. Reintentala con los mismos datos; no podemos asegurar que no se haya guardado.",
    history: "Cambios registrados", from: "Estado anterior", to: "Estado posterior", actor: "Registrado por", actorMissing: "Identidad no informada", at: "Fecha (UTC)",
    choose: "Elegí un estado", older: "Cargar cambios anteriores", blocked: "Este ticket se consulta aquí, pero su estado no se puede cambiar desde esta pantalla.", incident_managed: "El estado se gestiona desde el incidente vinculado.", legacy_status: "El estado registrado necesita revisión antes de usar este flujo.", tenant_unassigned: "El ticket no tiene una organización asignada para este flujo.",
    reference: "Referencia", tenant: "Organización", batch: "Lote", notProvided: "No informado", open: "Abierto", pending: "Pendiente", closed: "Cerrado", unknown: "Estado no informado", more: "Se muestran los cambios más recientes disponibles.",
  },
  en: {
    heading: "Manage status and view history", hint: "Record progress on the support request with a reason. Changing its status does not message the customer or confirm that a product recall is complete.",
    load: "Check status and history", refresh: "Check again", loading: "Loading history…", empty: "No status changes have been recorded in this history yet.",
    unavailable: "We could not load the history. You can try again.", denied: "Your session cannot manage this ticket. Check your permissions or sign in again.",
    current: "Confirmed status", target: "New status", reason: "Reason for the change", reasonHelp: "Explain what was done or what remains to be resolved (up to 1,000 characters).",
    review: "Review change", reviewTitle: "Review before confirming", confirm: "Confirm status change", edit: "Back to the reason", submitting: "Saving the change…",
    invalid: "Choose a different status and enter a reason within the stated limit.", unavailableAction: "The change could not be confirmed. Your reason is kept.",
    uncertain: "We could not confirm whether the change was saved. Retry the same operation; the status and reason stay locked for now to prevent duplicates.",
    retry: "Retry the same change", saved: "Status change confirmed. No message was sent to the customer.",
    conflict: "The ticket changed or this operation does not match the recorded one. Check its status before reviewing another change. Your reason is kept.",
    reload: "Check status before continuing", reloadHint: "Your reason remains in the form. Review the newly confirmed status before confirming a new change.",
    sticky: "An earlier operation remains unconfirmed. Retry it with the same details; we cannot guarantee it was not saved.",
    history: "Recorded changes", from: "Previous status", to: "New status", actor: "Recorded by", actorMissing: "Identity not provided", at: "Date (UTC)",
    choose: "Choose a status", older: "Load earlier changes", blocked: "You can view this ticket here, but its status cannot be changed from this screen.", incident_managed: "The linked incident manages this status.", legacy_status: "The recorded status needs review before using this workflow.", tenant_unassigned: "The ticket has no organization assigned for this workflow.",
    reference: "Reference", tenant: "Organization", batch: "Batch", notProvided: "Not provided", open: "Open", pending: "Pending", closed: "Closed", unknown: "Status not provided", more: "The most recent available changes are shown.",
  },
  "pt-BR": {
    heading: "Gerenciar estado e ver histórico", hint: "Registre o andamento do atendimento com um motivo. Alterar o estado não envia mensagem ao cliente nem confirma o término de um recolhimento de produto.",
    load: "Consultar estado e histórico", refresh: "Consultar novamente", loading: "Consultando o histórico…", empty: "Ainda não há alterações de estado registradas neste histórico.",
    unavailable: "Não foi possível consultar o histórico. Você pode tentar novamente.", denied: "Sua sessão não permite gerenciar este ticket. Confira suas permissões ou entre novamente.",
    current: "Estado consultado", target: "Novo estado", reason: "Motivo da alteração", reasonHelp: "Conte o que foi feito ou o que falta resolver (até 1.000 caracteres).",
    review: "Revisar alteração", reviewTitle: "Revise antes de confirmar", confirm: "Confirmar alteração de estado", edit: "Voltar ao motivo", submitting: "Salvando a alteração…",
    invalid: "Escolha um estado diferente e informe o motivo dentro do limite indicado.", unavailableAction: "Não foi possível confirmar a alteração. Seu motivo foi mantido.",
    uncertain: "Não foi possível confirmar se a alteração foi salva. Tente a mesma operação novamente; o estado e o motivo ficam bloqueados por enquanto para evitar duplicações.",
    retry: "Tentar a mesma alteração novamente", saved: "Alteração de estado confirmada. Nenhuma mensagem foi enviada ao cliente.",
    conflict: "O ticket mudou ou esta operação não corresponde à registrada. Consulte o estado antes de revisar outra alteração. Seu motivo foi mantido.",
    reload: "Consultar o estado antes de continuar", reloadHint: "O motivo continua no formulário. Revise o estado recém-consultado antes de confirmar uma nova alteração.",
    sticky: "Uma operação anterior continua sem confirmação. Tente novamente com os mesmos dados; não podemos garantir que ela não foi salva.",
    history: "Alterações registradas", from: "Estado anterior", to: "Novo estado", actor: "Registrado por", actorMissing: "Identidade não informada", at: "Data (UTC)",
    choose: "Escolha um estado", older: "Carregar alterações anteriores", blocked: "Você pode consultar este ticket aqui, mas não pode alterar seu estado nesta tela.", incident_managed: "O estado é gerenciado pelo incidente vinculado.", legacy_status: "O estado registrado precisa de revisão antes de usar este fluxo.", tenant_unassigned: "O ticket não tem uma organização atribuída para este fluxo.",
    reference: "Referência", tenant: "Organização", batch: "Lote", notProvided: "Não informado", open: "Aberto", pending: "Pendente", closed: "Fechado", unknown: "Estado não informado", more: "As alterações mais recentes disponíveis são exibidas.",
  },
};
