"use client";
import {useMemo,useState} from 'react';import Link from 'next/link';import {useRouter} from 'next/navigation';
import {Search,ArrowUpRight,PackagePlus,RefreshCw,FilePenLine,Upload} from 'lucide-react';
import {filterBatchWorkRows,batchWorkHref,type BatchWorkSource} from '../lib/batch-workbench';
import styles from './operations-workspace.module.css';
type Props={source:BatchWorkSource;scope:string;global:boolean;accountLabel:string;canConfigure:boolean;canImport:boolean;canOrder:boolean;canReport?:boolean;canRecalls?:boolean;canTrace?:boolean};
const number=(v:number)=>v.toLocaleString('es-AR');
const statusLabel:Record<string,string>={active:'Activo',draft:'Borrador',blocked:'Bloqueado',revoked:'Revocado',inactive:'Inactivo',pending:'Pendiente'};
export function BatchWorkbench({source,scope,global,accountLabel,canConfigure,canImport,canOrder,canReport=false,canRecalls=false,canTrace=false}:Props){
 const router=useRouter(),[query,setQuery]=useState(''),[tenant,setTenant]=useState(''),[state,setState]=useState('all'),[page,setPage]=useState(0);
 const rows=source.rows||[],visible=useMemo(()=>filterBatchWorkRows(rows,{query,tenant,state}),[rows,query,tenant,state]);
 const pageRows=visible.slice(page*20,(page+1)*20),tenants=[...new Set(rows.map(r=>r.tenant))].sort();
 const orderHref='/batches/supplier?'+new URLSearchParams(scope?{tenant:scope,intent:'new'}:{intent:'new'});
 return <main className={`${styles.workspace} ${styles.batchWorkbench}`} data-testid="batch-workbench">
  <header className={styles.batchHeading}><div><p className={styles.eyebrow}>Productos y etiquetas</p><h1 className={styles.title}>Lotes de trabajo</h1><p className={styles.note}>{accountLabel} · {scope||'Todas las empresas autorizadas'}</p></div><div className={styles.links}>{canReport&&<Link prefetch={false} href={"/analytics/pilot"+(scope?"?tenant="+encodeURIComponent(scope):"")} className={styles.button}>Informe del piloto</Link>}<button type="button" className={styles.button} onClick={()=>router.refresh()}><RefreshCw size={15} aria-hidden="true"/>Actualizar lista</button>{canOrder&&<Link prefetch={false} href={orderHref} className={`${styles.button} ${styles.primary}`}><PackagePlus size={16} aria-hidden="true"/>Pedido a fábrica</Link>}</div></header>
  {source.state!=='ready'?<section className={styles.feedback} role="status" data-testid="batches-source-unavailable"><h2>{source.state==='forbidden'?'El servidor rechazó el acceso a estos lotes':'No se pudo consultar el inventario'}</h2><p>La lista no está confirmada; no es inventario cero. Reintentá la consulta sin modificar tus productos.</p><button type="button" className={styles.button} onClick={()=>router.refresh()}>Reintentar consulta</button></section>:<>
   <div className={styles.toolbar}><label className={`${styles.field} ${styles.search}`}><span>Buscar producto, lote o SKU</span><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Nombre del producto o identificador"/></label>{global&&<label className={styles.field}>Empresa<select value={tenant} onChange={e=>{setTenant(e.target.value);setPage(0);}}><option value="">Todas las cargadas</option>{tenants.map(t=><option value={t} key={t}>{t}</option>)}</select></label>}<label className={styles.field}>Estado o tarea<select value={state} onChange={e=>{setState(e.target.value);setPage(0);}}><option value="all">Todos</option><option value="needs-product">Falta configurar producto</option><option value="awaiting-units">Sin unidades recibidas</option><option value="active">Activos</option><option value="blocked">Bloqueados</option><option value="revoked">Revocados</option></select></label></div>
   <p className={styles.note} role="status">{visible.length} lotes encontrados · {rows.length} cargados{rows.length===300?' (límite de la consulta: 300)':''}. Búsqueda y filtros sin consultas adicionales.</p>
   {pageRows.length?<div className={styles.batchList}>{pageRows.map(row=><article key={row.id} className={styles.batchCard}>
    <div className={styles.batchMain}><div><p className={styles.eyebrow}>{row.tenant} · {row.bid}</p><h2>{row.name||'Producto por configurar'}</h2><p className={styles.note}>{row.sku?'SKU '+row.sku:'Sin SKU'}{row.brand?' · '+row.brand:''}</p></div><span className={styles.badge}>{statusLabel[row.status]||row.status||'Estado no informado'}</span></div>
    <div className={styles.batchNumbers}><span><b>{number(row.quantity)}</b> registradas</span><span><b>{number(row.active)}</b> activas</span><span><b>{number(row.inactive)}</b> inactivas</span>{row.revoked>0&&<span><b>{number(row.revoked)}</b> revocadas</span>}<span>{row.carrier||'Perfil por confirmar'}</span></div>
    <div className={styles.batchActions}>{canTrace&&<Link prefetch={false} className={styles.button} href={`/batches/${encodeURIComponent(row.bid)}/traceability?${new URLSearchParams({tenant:row.tenant})}`}>Trazabilidad</Link>}{canRecalls&&<Link prefetch={false} className={styles.button} href={`/batches/${encodeURIComponent(row.bid)}/recalls?${new URLSearchParams({tenant:row.tenant})}`}>Retiro / cuarentena</Link>}<Link prefetch={false} className={styles.button} href={`/batches/${encodeURIComponent(row.bid)}/channels?${new URLSearchParams({tenant:row.tenant})}`}>Enlaces QR / estado NFC</Link>{canConfigure&&<Link prefetch={false} className={`${styles.button} ${styles.primary}`} href={batchWorkHref(row,'product')}><FilePenLine size={16} aria-hidden="true"/>{row.editorial?'Editar pasaporte':'Configurar producto'}</Link>}{canImport&&row.quantity===0&&<Link prefetch={false} className={styles.button} href={batchWorkHref(row,'units')}><Upload size={16} aria-hidden="true"/>Recibir archivo del proveedor</Link>}<Link prefetch={false} className={styles.button} href={batchWorkHref(row,'detail')}>Abrir lote <ArrowUpRight size={16} aria-hidden="true"/></Link></div>
   </article>)}</div>:<section className={styles.intake} data-testid="batches-empty"><h2>{rows.length?'Ningún lote coincide con estos filtros':'Todavía no hay lotes en esta consulta'}</h2>{rows.length?<button type="button" className={styles.button} onClick={()=>{setQuery('');setTenant('');setState('all');setPage(0);}}>Limpiar filtros</button>:canOrder?<Link prefetch={false} className={styles.button} href={orderHref}>Preparar primer pedido</Link>:<p className={styles.note}>La empresa necesita registrar un pedido con un usuario autorizado.</p>}</section>}
   {visible.length>20&&<nav aria-label="Páginas de lotes" className={styles.links}><button type="button" className={styles.button} disabled={page===0} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page+1} de {Math.ceil(visible.length/20)}</span><button type="button" className={styles.button} disabled={(page+1)*20>=visible.length} onClick={()=>setPage(p=>p+1)}>Siguiente</button></nav>}
   <p className={styles.note}>Las unidades activas no certifican la recepción de fábrica ni la calidad del producto. Las acciones de cada lote conservan sus controles.</p>
  </>}
 </main>;
}
