"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,ArrowDown,Boxes,Package,Truck,GitBranch,Search,RefreshCw,Download,Clock3,FileSearch,ShieldAlert,Link2,Activity,ChevronRight,Database} from 'lucide-react';
import {parseBatchTrace,readTraceJson,traceTimeline,traceSummary,isRelationship,eventLabels,actionLabels,stepLabels,dispositionLabels,custodyLabels,type BatchTrace,type TraceEvent,type CustodyEvent,type TraceRef} from '../lib/batch-traceability';
import {traceExports} from '../lib/batch-traceability-export';
import styles from './batch-traceability-workspace.module.css';
const format=(value:string)=>new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(value))+' UTC';
function defaultDates(){const now=new Date(),to=now.toISOString().slice(0,10);return {from:new Date(Date.parse(to)-29*86400000).toISOString().slice(0,10),to};}
const title=(e:TraceEvent|CustodyEvent)=>e.kind==='epcis'?(eventLabels[e.type]||e.type):(custodyLabels[e.type]||'Movimiento de custodia');
function save(content:string,name:string,type:string){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function BatchTraceabilityWorkspace({initial,bid,tenant,canLogistics=false,enabled=true}:{initial:BatchTrace|null;bid:string;tenant:string;canLogistics?:boolean;enabled?:boolean}){
 const defaults=initial?.window||defaultDates();const [data,setData]=useState(initial),[from,setFrom]=useState(defaults.from),[to,setTo]=useState(defaults.to),[kind,setKind]=useState('all'),[search,setSearch]=useState(''),[tab,setTab]=useState<'journey'|'relations'|'shipments'>('journey'),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[exporting,setExporting]=useState(false),[error,setError]=useState(initial?'':'La fuente no confirmó el recorrido. Esto no representa cero movimientos.');
 const flight=useRef<AbortController|null>(null),alive=useRef(true),detail=useRef<HTMLElement|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;flight.current?.abort();};},[]);
 function invalidate(){flight.current?.abort();setData(null);setSelected(null);setError('Filtros modificados. Consultá para obtener el nuevo recorrido.');}
 async function refresh(){if(flight.current||!enabled)return;setBusy(true);setData(null);setSelected(null);setError('');const controller=new AbortController();flight.current=controller;const timer=setTimeout(()=>controller.abort(),15000);
  try{const q=new URLSearchParams({tenant,from,to});const response=await fetch(`/api/admin/batches/${encodeURIComponent(bid)}/traceability?${q}`,{cache:'no-store',credentials:'same-origin',signal:controller.signal});if(!response.ok)throw Error(response.status===403?'La cuenta no tiene acceso a este alcance.':response.status===400?'Revisá las fechas: entre 1 y 93 días completos en UTC.':'No se pudo confirmar el recorrido. No se muestran datos anteriores como actuales.');const next=parseBatchTrace(await readTraceJson(response),bid,tenant,{from,to});if(alive.current)setData(next);}
  catch(e){if(alive.current)setError(e instanceof Error?e.message:'Consulta no disponible.');}finally{clearTimeout(timer);flight.current=null;if(alive.current)setBusy(false);}
 }
 const rows=useMemo(()=>data?traceTimeline(data,tab==='relations'?'relationships':kind,search):[],[data,kind,search,tab]);
 const active=rows.find(e=>e.id===selected)||rows[0]||null,metrics=data?traceSummary(data):null;
 function select(id:string){setSelected(id);if(matchMedia('(max-width:850px)').matches)requestAnimationFrame(()=>{detail.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});detail.current?.focus({preventScroll:true});});}
 async function exportData(which:'html'|'json'){if(!data||exporting)return;setExporting(true);try{const files=await traceExports(data);save(files[which],`nexid-recorrido-${data.window.from}.${which}`,which==='html'?'text/html;charset=utf-8':'application/json');}catch{setError('No se pudo generar la exportación. No se guardó un informe incompleto.');}finally{setExporting(false);}}
 const qs=new URLSearchParams(tenant?{tenant}:{}),dossier=`/batches/${encodeURIComponent(bid)}?${qs}`;
 return <main className={styles.root} data-testid="batch-traceability"><div className={styles.top}><Link prefetch={false} href={dossier}><ArrowLeft size={15} aria-hidden="true"/>Volver al expediente</Link><span>Consulta de trazabilidad · sin escrituras</span></div>
  <header className={styles.hero}><div><p className={styles.eyebrow}>HISTORIA OPERATIVA DEL PRODUCTO</p><h1>Recorrido del lote</h1><p>{data?.product.name||bid} · {data?.scope.tenantName||tenant||'Empresa por confirmar'}</p></div><span className={styles.heroIcon}><GitBranch size={31} aria-hidden="true"/></span></header>
  <form className={styles.toolbar} onSubmit={e=>{e.preventDefault();void refresh();}}><label>Desde · UTC<input aria-label="Desde UTC" type="date" value={from} disabled={busy||exporting} onChange={e=>{invalidate();setFrom(e.target.value);}}/></label><label>Hasta · inclusive UTC<input aria-label="Hasta UTC" type="date" value={to} disabled={busy||exporting} onChange={e=>{invalidate();setTo(e.target.value);}}/></label><button type="submit" className={styles.primary} disabled={busy||exporting||!enabled}><RefreshCw size={16} aria-hidden="true"/>{busy?'Consultando fuentes…':'Consultar recorrido'}</button><div className={styles.export}><button type="button" disabled={!data||exporting||busy} onClick={()=>void exportData('html')}><Download size={15} aria-hidden="true"/>Informe HTML</button><button type="button" disabled={!data||exporting||busy} onClick={()=>void exportData('json')}>Evidencia JSON</button></div></form>
  <p className={styles.source} role="status">{error||(busy?'Recuperando referencias del período.':data?`Fuente: base operativa · consultado ${format(data.observedAt)}. Exportar y filtrar la lista no generan consultas.`:'Sin consultar.')}</p>
  <p className={styles.metricScope}>Conteos de registros visibles, no totales históricos ni unidades físicas certificadas.</p><div className={styles.metrics}>{[[Activity,'Eventos EPCIS',metrics?.epcis,'Declaraciones visibles'],[GitBranch,'Relaciones',metrics?.relationships,'Eventos de agrupación o cambio'],[Package,'Identidades',metrics?.identities,'Referencias distintas en esta consulta'],[Truck,'Custodia',data?.logisticsAccess==='restricted'?null:metrics?.custody,data?.logisticsAccess==='restricted'?'Requiere permiso de logística':'Movimientos registrados visibles']].map(([Icon,label,value,note])=>{const I=Icon as typeof Activity;return <div key={String(label)}><I size={19} aria-hidden="true"/><span>{String(label)}</span><strong>{typeof value==='number'?value:'—'}</strong><small>{String(note)}</small></div>;})}</div>
  <nav className={styles.tabs} aria-label="Vistas de trazabilidad">{[['journey','Recorrido',Clock3],['relations','Relaciones por evento',GitBranch],['shipments','Envíos vinculados',Truck]].map(([key,label,Icon])=>{const I=Icon as typeof Truck;return <button type="button" key={String(key)} aria-pressed={tab===key} onClick={()=>{setTab(key as typeof tab);setSelected(null);}}><I size={16} aria-hidden="true"/>{String(label)}</button>;})}</nav>
  {tab!=='shipments'?<><div className={styles.listFilters}><label><Search size={16} aria-hidden="true"/><span className={styles.srOnly}>Buscar GTIN, serie, lote o envío</span><input type="search" maxLength={160} value={search} placeholder="GTIN, serie, lote o envío" onChange={e=>{setSearch(e.target.value);setSelected(null);}}/></label>{tab==='journey'&&<select aria-label="Fuente de movimientos" value={kind} onChange={e=>{setKind(e.target.value);setSelected(null);}}><option value="all">Todas las fuentes autorizadas</option><option value="epcis">Declaraciones EPCIS</option><option value="custody">Custodia registrada</option></select>}<span>{rows.length} resultados en la selección</span></div>
   {data&&(data.hasMore.events||data.hasMore.custody)&&<p className={styles.notice}>La ventana contiene más registros. Se muestran hasta 50 eventos EPCIS y 50 movimientos de custodia. Acotá las fechas para consultar otros; los contadores no son el total histórico.</p>}
   <div className={styles.grid}><section className={styles.timeline} aria-label="Movimientos del lote">{rows.map(e=><button type="button" className={styles.event} key={e.kind+e.id} data-selected={active?.id===e.id} onClick={()=>select(e.id)} aria-label={`Abrir ${title(e)} ${format(e.kind==='epcis'?e.occurredAt:e.recordedAt)}`}><span className={styles.dot} data-kind={e.kind}>{e.kind==='epcis'?<Boxes size={18} aria-hidden="true"/>:<Truck size={18} aria-hidden="true"/>}</span><span className={styles.eventBody}><small>{format(e.kind==='epcis'?e.occurredAt:e.recordedAt)}</small><strong>{title(e)}</strong><span>{e.kind==='epcis'?(stepLabels[e.step||'']||e.step||'Paso de negocio sin informar'):(e.shipmentCode||'Envío no informado')}</span><em>{e.kind==='epcis'?'Declaración externa': 'Registro de custodia'}{e.kind==='epcis'&&e.correctionDeclared?' · corrección declarada':''}</em></span><ChevronRight size={16} aria-hidden="true"/></button>)}
    {!rows.length&&<div className={styles.empty}><FileSearch size={31} aria-hidden="true"/><h2>{data?'Sin movimientos en esta selección':'Recorrido sin confirmar'}</h2><p>{data?'No se encontraron referencias vinculadas al lote para los filtros actuales. No se dibujan cajas, pallets ni recepciones supuestos.':'Volvé a consultar la fuente antes de interpretar esta vista.'}</p>{data&&<><Link prefetch={false} className={styles.secondary} href={`${dossier}#dossier-readings`}>Ver lecturas NFC existentes</Link><Link prefetch={false} className={styles.secondary} href={`/batches/${encodeURIComponent(bid)}/channels?${qs}`}>Revisar identidades del lote</Link></>}</div>}
   </section><section ref={detail} tabIndex={-1} className={styles.detail} aria-label="Detalle del movimiento">{active?<TraceEventDetail event={active} tenant={data?.scope.tenant||tenant} canLogistics={canLogistics}/>:<div className={styles.empty}><GitBranch size={31} aria-hidden="true"/><h2>La relación aparece con su evidencia</h2><p>Elegí un movimiento registrado para revisar referencias, fecha declarada y fecha de ingreso. La vista no calcula una ubicación física actual.</p></div>}</section></div></>:<section className={styles.shipments}><header><h2>Envíos asociados a precintos de este lote</h2><p>Estado actual del flujo, independiente del período de eventos. Un precinto vinculado no describe todos los productos transportados.</p></header>{data?.logisticsAccess==='restricted'?<p className={styles.notice}>La cuenta no tiene permiso <code>logistics:read</code>. Los envíos y sus movimientos no se incluyeron en la respuesta.</p>:data?.shipments.map(s=><article key={s.id} className={styles.shipment}><Truck size={23} aria-hidden="true"/><div><h3>{s.code}</h3><span>{custodyLabels[s.status]||s.status}</span><p>Actualizado {format(s.updatedAt)}</p></div>{canLogistics&&<Link prefetch={false} className={styles.secondary} href={`/logistics/shipments/${s.id}?${qs}`}>Abrir envío<ArrowRight size={15} aria-hidden="true"/></Link>}</article>)}{data?.logisticsAccess==='allowed'&&!data.shipments.length&&<p className={styles.notice}>No hay envíos vinculados por precinto en esta consulta. No se asociaron por similitud de nombre o ubicación.</p>}{data?.hasMore.shipments&&<p>Se muestran los 20 envíos actualizados más recientemente.</p>}</section>}
  <footer className={styles.boundary}><ShieldAlert size={18} aria-hidden="true"/><p><strong>Historia registrada, no autenticidad añadida.</strong> Agrupar, separar o transformar son declaraciones del evento. No representan pertenencia actual ni verifican un chip UHF/NFC. Las lecturas SUN y el estado del precinto conservan sus controles originales.</p></footer>
 </main>;
}
function ReferenceGroup({title,items,tenant}:{title:string;items:TraceRef[];tenant:string}){
 return <section className={styles.references}><h4>{title} <span>{items.length}</span></h4>{items.map((r,index)=><article key={r.id+index} data-focus={r.focus}><span className={styles.refLabel}>{r.focus?'Identidad de este lote':'Referencia de esta empresa'}</span><strong>{r.gtin}</strong><p>{r.lot?`Lote ${r.lot}`:'Sin lote GS1'} · {r.serial?`Serie ${r.serial}`:'Sin serie'}</p>{r.quantity!==null&&<p>{r.quantity} · {r.uom||'Unidad de medida no informada'} (cantidad declarada)</p>}<Link prefetch={false} href={`/batches/${encodeURIComponent(r.bid)}?${new URLSearchParams({tenant})}`}>{r.bid}<ArrowRight size={13} aria-hidden="true"/></Link></article>)}{!items.length&&<p>No hay referencias visibles para este papel.</p>}</section>;
}
function TraceEventDetail({event:e,tenant,canLogistics}:{event:TraceEvent|CustodyEvent;tenant:string;canLogistics:boolean}){
 if(e.kind==='custody')return <><p className={styles.eyebrow}>FLUJO LOGÍSTICO REGISTRADO</p><h2>{title(e)}</h2><p>Registrado {format(e.recordedAt)}</p><dl className={styles.facts}><div><dt>Envío</dt><dd>{e.shipmentCode||'No informado'}</dd></div><div><dt>Tipo original</dt><dd>{e.type}</dd></div></dl>{canLogistics&&e.shipmentId&&<Link prefetch={false} className={styles.secondary} href={`/logistics/shipments/${e.shipmentId}?${new URLSearchParams({tenant})}`}>Abrir expediente del envío</Link>}<p className={styles.notice}>Este registro no vuelve a verificar el chip ni determina el estado actual de su precinto. La fecha corresponde al ingreso en custodia.</p></>;
 const parent=e.references.filter(r=>r.role==='parent'),children=e.references.filter(r=>r.role==='child'),inputs=e.references.filter(r=>r.role==='input'),outputs=e.references.filter(r=>r.role==='output');
 return <><p className={styles.eyebrow}>DECLARACIÓN EPCIS · EVIDENCIA DEL EVENTO</p><h2>{title(e)}</h2><span className={styles.action} data-action={e.action}>{e.action?(actionLabels[e.action]||e.action):'Entradas y salidas declaradas'}</span>{e.correctionDeclared&&<p className={styles.notice}>Este evento contiene una declaración de error o corrección. No se usa para afirmar una relación vigente; esta vista conserva la referencia histórica.</p>}
  <dl className={styles.facts}><div><dt>Cuándo ocurrió según el emisor</dt><dd>{format(e.occurredAt)}</dd></div><div><dt>Cuándo ingresó a NexID</dt><dd>{format(e.recordedAt)}</dd></div><div><dt>Paso de negocio</dt><dd>{stepLabels[e.step||'']||e.step||'No informado'}</dd></div><div><dt>Disposición declarada</dt><dd>{dispositionLabels[e.disposition||'']||e.disposition||'No informada'}</dd></div></dl>
  {['AggregationEvent','AssociationEvent'].includes(e.type)?<div className={styles.flow}><ReferenceGroup title="Agrupador declarado" items={parent} tenant={tenant}/><div className={styles.flowArrow}><ArrowDown size={21} aria-hidden="true"/>{e.action==='DELETE'?'Separación informada, no borrado de historia':e.action==='OBSERVE'?'Relación observada según el emisor':'Relación añadida según el emisor'}</div><ReferenceGroup title="Contenido referenciado" items={children} tenant={tenant}/></div>:e.type==='TransformationEvent'?<div className={styles.flow}><ReferenceGroup title="Entradas declaradas" items={inputs} tenant={tenant}/><div className={styles.flowArrow}><ArrowDown size={21} aria-hidden="true"/>Transformación declarada · sin inferir cantidades equivalentes</div><ReferenceGroup title="Salidas declaradas" items={outputs} tenant={tenant}/></div>:<ReferenceGroup title="Objetos referenciados" items={e.references.filter(r=>r.role==='object')} tenant={tenant}/>}
  {e.omittedReferences>0&&<p className={styles.notice}>{e.omittedReferences} referencias no se muestran por límite o falta de vínculo autorizado. No se interpreta la selección como contenido completo.</p>}
  <details className={styles.technical}><summary><Database size={15} aria-hidden="true"/>Origen y referencia técnica</summary><dl><div><dt>Punto de lectura declarado</dt><dd>{e.readPoint||'No informado o no publicable'}</dd></div><div><dt>Ubicación declarada</dt><dd>{e.location||'No informada o no publicable'}</dd></div><div><dt>Referencia del evento</dt><dd>{e.id}</dd></div><div><dt>Tipo original</dt><dd>{e.type}</dd></div></dl></details>
 </>;
}
