"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,ArrowDown,Boxes,Package,Truck,GitBranch,Search,RefreshCw,Download,Clock3,FileSearch,ShieldAlert,Activity,ChevronRight,ChevronLeft,Database,Filter,X} from 'lucide-react';
import {readTraceJson,traceSummary,eventLabels,actionLabels,stepLabels,dispositionLabels,custodyLabels,type TraceEvent,type CustodyEvent,type TraceRef} from '../lib/batch-traceability';
import {parseTracePage,tracePageParams,tracePageTimeline,emptyTraceQuery,normalizedTraceQuery,type TracePage,type TraceQuery} from '../lib/trace-page';
import {tracePageExports} from '../lib/trace-page-export';
import styles from './batch-traceability-workspace.module.css';
const format=(value:string)=>new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(value))+' UTC';
function defaultDates(){const to=new Date().toISOString().slice(0,10);return {from:new Date(Date.parse(to)-29*86400000).toISOString().slice(0,10),to};}
const title=(e:TraceEvent|CustodyEvent)=>e.kind==='epcis'?(eventLabels[e.type]||e.type):(custodyLabels[e.type]||'Movimiento de custodia');
const keyOf=(e:{kind:string;id:string})=>e.kind+':'+e.id;
function save(content:string,name:string,type:string){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
type ReadAttempt={cursor:string|null;index:number;query:TraceQuery;from:string;to:string;cutoff?:string;batchId?:string};
export function BatchTraceabilityWorkspace({initial,bid,tenant,canLogistics=false,enabled=true,canIntake=false}:{initial:TracePage|null;bid:string;tenant:string;canLogistics?:boolean;enabled?:boolean;canIntake?:boolean}){
 const defaults=initial?.trace.window||defaultDates();
 const [page,setPage]=useState(initial),[from,setFrom]=useState(defaults.from),[to,setTo]=useState(defaults.to),[query,setQuery]=useState<TraceQuery>(initial?.query||emptyTraceQuery);
 const [filtersOpen,setFiltersOpen]=useState(false);
 const [search,setSearch]=useState(''),[tab,setTab]=useState<'journey'|'relations'|'shipments'>('journey'),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[exporting,setExporting]=useState(false);
 const [trail,setTrail]=useState<string[]>(initial?[initial.navigation.currentCursor]:[]),[error,setError]=useState(initial?'':'La fuente no confirmó el recorrido. Esto no representa cero movimientos.');
 const flight=useRef<AbortController|null>(null),alive=useRef(true),generation=useRef(0),lastAttempt=useRef<ReadAttempt|null>(null),detail=useRef<HTMLElement|null>(null),list=useRef<HTMLElement|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;flight.current?.abort();};},[]);
 function invalidate(){generation.current++;flight.current?.abort();lastAttempt.current=null;setPage(null);setTrail([]);setSelected(null);setError('Filtros modificados. Consultá para obtener la nueva selección.');}
 function field(k:keyof TraceQuery,value:string){invalidate();setQuery(q=>normalizedTraceQuery({...q,[k]:value,exact:false}));}
 async function load(attempt:ReadAttempt){
  if(flight.current||!enabled||exporting)return;
  const wanted={...attempt,query:normalizedTraceQuery(attempt.query)};lastAttempt.current=wanted;
  const seq=++generation.current,controller=new AbortController();flight.current=controller;const timer=setTimeout(()=>controller.abort(),15000);
  setBusy(true);setPage(null);setSelected(null);setError('');
  try{
   const params=tracePageParams(tenant,wanted.from,wanted.to,wanted.query,wanted.cursor);
   const response=await fetch(`/api/admin/batches/${encodeURIComponent(bid)}/traceability/page?${params}`,{cache:'no-store',credentials:'same-origin',signal:controller.signal});
   if(!response.ok){if(response.status===409)lastAttempt.current=null;throw Error(response.status===403?'No hay permiso para la fuente o la empresa solicitada.':response.status===409?'La posición venció o cambiaron filtros/permisos. Iniciá una nueva consulta.':response.status===400?'Revisá fechas, GTIN y calificadores. Lote/serie requieren un GTIN válido.':'La página no pudo confirmarse. No se ofrece el resultado anterior como actual.');}
   const next=parseTracePage(await readTraceJson(response),bid,tenant,{from:wanted.from,to:wanted.to,query:wanted.query,page:wanted.index+1,cutoff:wanted.cutoff,batchId:wanted.batchId});
   if(alive.current&&seq===generation.current){setPage(next);setQuery(next.query);setFiltersOpen(false);setTrail(previous=>wanted.cursor?[...previous.slice(0,wanted.index),next.navigation.currentCursor]:[next.navigation.currentCursor]);requestAnimationFrame(()=>list.current?.scrollTo({top:0}));}
  }catch(e){if(alive.current&&seq===generation.current)setError(e instanceof Error?e.message:'Consulta no disponible.');}
  finally{clearTimeout(timer);if(flight.current===controller)flight.current=null;if(alive.current)setBusy(false);}
 }
 function refresh(){void load({cursor:null,index:0,query,from,to});}
 function navigate(direction:'previous'|'next'){
  if(!page)return;const index=direction==='next'?page.navigation.page:page.navigation.page-2;
  const cursor=direction==='next'?page.navigation.nextCursor:trail[index];if(!cursor||index<0)return;
  void load({cursor,index,query:page.query,from,to,cutoff:page.navigation.cutoff,batchId:page.trace.scope.batchId});
 }
 function investigate(r:TraceRef){if(busy||exporting)return;const q:TraceQuery={source:'epcis',type:'',gtin:r.gtin,lot:r.lot,serial:r.serial,exact:true};setQuery(q);setTab('journey');setSearch('');void load({cursor:null,index:0,query:q,from,to});}
 const data=page?.trace,rows=useMemo(()=>page?tracePageTimeline(page,tab==='relations'?'relationships':'all',search):[],[page,search,tab]);
 const active=rows.find(e=>keyOf(e)===selected)||rows[0]||null,metrics=data?traceSummary(data):null;
 function select(e:TraceEvent|CustodyEvent){setSelected(keyOf(e));if(matchMedia('(max-width:850px)').matches)requestAnimationFrame(()=>{detail.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});detail.current?.focus({preventScroll:true});});}
 async function exportData(which:'html'|'json'){if(!page||exporting)return;setExporting(true);try{const files=await tracePageExports(page);if(alive.current)save(files[which],`nexid-recorrido-${page.trace.window.from}-p${page.navigation.page}.${which}`,which==='html'?'text/html;charset=utf-8':'application/json');}catch{if(alive.current)setError('No se pudo preparar el informe de la página.');}finally{if(alive.current)setExporting(false);}}
 const qs=new URLSearchParams(tenant?{tenant}:{}),dossier=`/batches/${encodeURIComponent(bid)}?${qs}`;
 return <main className={styles.root} data-testid="batch-traceability">
  <div className={styles.top}><Link prefetch={false} href={dossier}><ArrowLeft size={15} aria-hidden="true"/>Volver al expediente</Link><span>Investigación del historial · sin escrituras</span>{canIntake&&<Link prefetch={false} className={styles.primary} href={`/batches/${encodeURIComponent(bid)}/intake?${qs}`}>Registrar movimiento<ArrowRight size={15} aria-hidden="true"/></Link>}</div>
  <header className={styles.hero}><div><p className={styles.eyebrow}>DE LA IDENTIDAD A SU HISTORIA</p><h1>Recorrido del lote</h1><p>{data?.product.name||bid} · {data?.scope.tenantName||tenant||'Empresa por confirmar'}</p></div><span className={styles.heroIcon}><GitBranch size={31} aria-hidden="true"/></span></header>
  <form className={styles.queryPanel} onSubmit={e=>{e.preventDefault();refresh();}}>
   <div className={styles.toolbar}><label>Desde · UTC<input aria-label="Desde UTC" type="date" value={from} disabled={busy||exporting} onChange={e=>{invalidate();setFrom(e.target.value);}}/></label><label>Hasta · inclusive UTC<input aria-label="Hasta UTC" type="date" value={to} disabled={busy||exporting} onChange={e=>{invalidate();setTo(e.target.value);}}/></label>
    <label>Fuente de la consulta<select aria-label="Fuente de la consulta" value={query.source} disabled={busy||exporting||Boolean(query.gtin||query.type)} onChange={e=>field('source',e.target.value)}><option value="all">Todas las fuentes autorizadas</option><option value="epcis">Declaraciones EPCIS</option><option value="custody" disabled={!canLogistics||data?.logisticsAccess!=='allowed'}>Custodia registrada</option></select></label>
    <button type="submit" className={styles.primary} disabled={busy||exporting||!enabled}><RefreshCw size={16} aria-hidden="true"/>{busy?'Consultando historial…':'Consultar recorrido'}</button></div>
   <details className={styles.identityQuery} open={filtersOpen} onToggle={e=>setFiltersOpen(e.currentTarget.open)}><summary><Filter size={15} aria-hidden="true"/>Buscar identidad o tipo en todo el período</summary><div className={styles.identityFields}>
    <label>GTIN de 14 dígitos<input aria-label="GTIN del historial" inputMode="numeric" maxLength={14} value={query.gtin} disabled={busy||exporting} onChange={e=>field('gtin',e.target.value)} placeholder="Conservar ceros iniciales"/></label>
    <label>Lote GS1<input aria-label="Lote GS1 del historial" maxLength={20} value={query.lot} disabled={busy||exporting} onChange={e=>field('lot',e.target.value)} placeholder="Opcional"/></label><label>Serie<input aria-label="Serie del historial" maxLength={20} value={query.serial} disabled={busy||exporting} onChange={e=>field('serial',e.target.value)} placeholder="Opcional"/></label>
    <label>Tipo de evento<select aria-label="Tipo de evento del historial" value={query.type} disabled={busy||exporting} onChange={e=>field('type',e.target.value)}><option value="">Todos</option><option value="relationships">Relaciones y transformaciones</option>{Object.entries(eventLabels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>
   </div><p>Se consulta el registro completo del período, en páginas. Lote y serie vacíos no filtran, salvo al seguir una identidad exacta. Los filtros de identidad sólo corresponden a EPCIS, no se atribuyen a la custodia.</p></details>
   {(query.gtin||query.type||query.source!=='all')&&<div className={styles.filterState}><span>{query.exact?'Identidad exacta':'Filtros de consulta'}{query.gtin?` · ${query.gtin} / ${query.lot||'sin lote'} / ${query.serial||'sin serie'}`:''}</span><button type="button" disabled={busy||exporting} onClick={()=>{invalidate();setQuery(emptyTraceQuery);}}><X size={13} aria-hidden="true"/>Quitar filtros</button></div>}
  </form>
  <p className={styles.source} role="status">{error||(busy?'Recuperando esta página con sus filtros y permisos.':data?`Fuente: base operativa · consultado ${format(data.observedAt)}.`:'Sin consultar.')}</p>
  {!page&&!busy&&error&&lastAttempt.current&&<button type="button" onClick={()=>void load(lastAttempt.current!)}>Reintentar la página solicitada</button>}
  <p className={styles.metricScope}>Conteos de esta página, no totales históricos ni unidades físicas certificadas.</p>
  <div className={styles.metrics}>{[[Activity,'Eventos EPCIS',metrics?.epcis,'Declaraciones de la página'],[GitBranch,'Relaciones',metrics?.relationships,'Eventos de agrupación o cambio'],[Package,'Identidades',metrics?.identities,'Referencias de esta página'],[Truck,'Custodia',data?.logisticsAccess==='restricted'?null:metrics?.custody,data?.logisticsAccess==='restricted'?'Requiere permiso de logística':'Movimientos de esta página']].map(([Icon,label,value,note])=>{const I=Icon as typeof Activity;return <div key={String(label)}><I size={19} aria-hidden="true"/><span>{String(label)}</span><strong>{typeof value==='number'?value:'—'}</strong><small>{String(note)}</small></div>;})}</div>
  <div className={styles.pager} aria-label="Páginas del historial"><div><strong>{page?`Página ${page.navigation.page}`:'Página sin confirmar'}</strong><span>{page?`${page.navigation.returned} movimientos · ${page.navigation.hasNext?'hay más registros':'sin continuación detectada'}`:'Consultá para navegar el historial.'}</span></div><div className={styles.pagerButtons}><button type="button" aria-label="Página anterior" disabled={!page||page.navigation.page<=1||busy||exporting} onClick={()=>navigate('previous')}><ChevronLeft size={16} aria-hidden="true"/>Anterior</button><button type="button" aria-label="Página siguiente" disabled={!page?.navigation.hasNext||busy||exporting} onClick={()=>navigate('next')}>Siguiente<ChevronRight size={16} aria-hidden="true"/></button></div><div className={styles.export}><button type="button" disabled={!page||exporting||busy} onClick={()=>void exportData('html')}><Download size={15} aria-hidden="true"/>Informe de esta página</button><button type="button" disabled={!page||exporting||busy} onClick={()=>void exportData('json')}>JSON de esta página</button></div></div>
  {page&&<details className={styles.cutoff}><summary>Corte de registros: {format(page.navigation.cutoff)} · qué incluye la navegación</summary><p>Se excluyen registros ingresados después del corte. Cada página consulta nuevamente los permisos y los datos: no es una fotografía inmutable entre solicitudes. Una corrección o cambio de vínculo puede alterar el historial. “Consultar recorrido” reinicia la búsqueda y recoge datos nuevos. Los envíos muestran el estado actual del lote completo.</p></details>}
  <nav className={styles.tabs} aria-label="Vistas de trazabilidad">{[['journey','Recorrido',Clock3],['relations','Relaciones de esta página',GitBranch],['shipments','Envíos vinculados',Truck]].map(([k,label,Icon])=>{const I=Icon as typeof Truck;return <button type="button" key={String(k)} aria-pressed={tab===k} onClick={()=>{setTab(k as typeof tab);setSelected(null);}}><I size={16} aria-hidden="true"/>{String(label)}</button>;})}</nav>
  {tab!=='shipments'?<><div className={styles.listFilters}><label><Search size={16} aria-hidden="true"/><span className={styles.srOnly}>Buscar en esta página</span><input type="search" maxLength={160} value={search} placeholder="Buscar en la página cargada" onChange={e=>{setSearch(e.target.value);setSelected(null);}}/></label><span>{rows.length} visibles en esta página. La búsqueda local no recorre otras páginas.</span></div>
   <div className={styles.grid}><section ref={list} tabIndex={0} className={`${styles.timeline} ${styles.pagedTimeline}`} aria-label="Movimientos de esta página">{rows.map(e=><button type="button" className={styles.event} key={keyOf(e)} data-selected={active&&keyOf(active)===keyOf(e)} onClick={()=>select(e)} aria-label={`Abrir ${title(e)} ${format(e.kind==='epcis'?e.occurredAt:e.recordedAt)}`}><span className={styles.dot} data-kind={e.kind}>{e.kind==='epcis'?<Boxes size={18} aria-hidden="true"/>:<Truck size={18} aria-hidden="true"/>}</span><span className={styles.eventBody}><small>{format(e.kind==='epcis'?e.occurredAt:e.recordedAt)}</small><strong>{title(e)}</strong><span>{e.kind==='epcis'?(stepLabels[e.step||'']||e.step||'Paso sin informar'):(e.shipmentCode||'Envío no informado')}</span><em>{e.kind==='epcis'?'Declaración externa':'Custodia registrada'}{e.kind==='epcis'&&e.correctionDeclared?' · corrección declarada':''}</em></span><ChevronRight size={16} aria-hidden="true"/></button>)}
    {!rows.length&&<div className={styles.empty}><FileSearch size={31} aria-hidden="true"/><h2>{page?'Sin movimientos en esta selección':'Recorrido sin confirmar'}</h2><p>{page?.navigation.hasNext?'La búsqueda local no encontró coincidencias aquí; hay más páginas disponibles. Usá los filtros de identidad para consultar todo el período.':page?'No se encontraron referencias en esta selección. Las lecturas NFC se consultan por separado.':'Consultá nuevamente antes de interpretar un resultado.'}</p><Link prefetch={false} className={styles.secondary} href={`${dossier}#dossier-readings`}>Ver lecturas NFC existentes</Link></div>}
   </section><section ref={detail} tabIndex={-1} className={styles.detail} aria-label="Detalle del movimiento">{active?<TraceEventDetail event={active} tenant={data?.scope.tenant||tenant} canLogistics={canLogistics&&data?.logisticsAccess==='allowed'} onInvestigate={investigate}/>:<div className={styles.empty}><GitBranch size={31} aria-hidden="true"/><h2>Seleccioná un movimiento registrado</h2><p>El detalle conserva relaciones y fechas del evento. No se dibuja contenido actual de un pallet sin evidencia suficiente.</p></div>}</section></div>
  </>:<section className={styles.shipments}><header><h2>Envíos vinculados al lote completo</h2><p>Estado de esta consulta, no sólo de la identidad filtrada ni del período EPCIS. Un precinto vinculado no describe todos los productos transportados.</p></header>{data?.logisticsAccess==='restricted'?<p className={styles.notice}>La cuenta no tiene permiso <code>logistics:read</code>. No se incluyeron envíos ni custodia.</p>:data?.shipments.map(s=><article key={s.id} className={styles.shipment}><Truck size={23} aria-hidden="true"/><div><h3>{s.code}</h3><span>{custodyLabels[s.status]||s.status}</span><p>Actualizado {format(s.updatedAt)}</p></div>{canLogistics&&<Link prefetch={false} className={styles.secondary} href={`/logistics/shipments/${s.id}?${qs}`}>Abrir envío<ArrowRight size={15} aria-hidden="true"/></Link>}</article>)}{data?.logisticsAccess==='allowed'&&!data.shipments.length&&<p className={styles.notice}>No hay envíos vinculados por precinto en esta consulta.</p>}{data?.hasMore.shipments&&<p>Se muestran los 20 envíos actualizados más recientemente.</p>}</section>}
  <footer className={styles.boundary}><ShieldAlert size={18} aria-hidden="true"/><p><strong>Historia registrada, no autenticidad añadida.</strong> El historial preserva las declaraciones, separaciones y correcciones. No certifica pertenencia actual, ubicación física ni lectura de hardware UHF. El TAP y su precinto mantienen la verificación original.</p></footer>
 </main>;
}
function ReferenceGroup({title,items,tenant,onInvestigate}:{title:string;items:TraceRef[];tenant:string;onInvestigate:(r:TraceRef)=>void}){
 return <section className={styles.references}><h4>{title} <span>{items.length}</span></h4>{items.map((r,index)=><article key={r.id+index} data-focus={r.focus}><span className={styles.refLabel}>{r.focus?'Identidad de este lote':'Referencia de esta empresa'}</span><strong>{r.gtin}</strong><p>{r.lot?`Lote ${r.lot}`:'Sin lote GS1'} · {r.serial?`Serie ${r.serial}`:'Sin serie'}</p>{r.quantity!==null&&<p>{r.quantity} · {r.uom||'Unidad de medida no informada'} (cantidad declarada)</p>}<Link prefetch={false} href={`/batches/${encodeURIComponent(r.bid)}?${new URLSearchParams({tenant})}`}>{r.bid}<ArrowRight size={13} aria-hidden="true"/></Link>{r.focus&&<button type="button" className={styles.inspect} onClick={()=>onInvestigate(r)}><Search size={13} aria-hidden="true"/>Seguir esta identidad</button>}</article>)}{!items.length&&<p>No hay referencias visibles para este papel.</p>}</section>;
}
function TraceEventDetail({event:e,tenant,canLogistics,onInvestigate}:{event:TraceEvent|CustodyEvent;tenant:string;canLogistics:boolean;onInvestigate:(r:TraceRef)=>void}){
 if(e.kind==='custody')return <><p className={styles.eyebrow}>FLUJO LOGÍSTICO REGISTRADO</p><h2>{title(e)}</h2><p>Registrado {format(e.recordedAt)}</p><dl className={styles.facts}><div><dt>Envío</dt><dd>{e.shipmentCode||'No informado'}</dd></div><div><dt>Tipo original</dt><dd>{e.type}</dd></div></dl>{canLogistics&&e.shipmentId&&<Link prefetch={false} className={styles.secondary} href={`/logistics/shipments/${e.shipmentId}?${new URLSearchParams({tenant})}`}>Abrir expediente del envío</Link>}<p className={styles.notice}>Este registro no vuelve a verificar el chip ni determina el estado actual de su precinto. La fecha corresponde al ingreso en custodia.</p></>;
 const parent=e.references.filter(r=>r.role==='parent'),children=e.references.filter(r=>r.role==='child'),inputs=e.references.filter(r=>r.role==='input'),outputs=e.references.filter(r=>r.role==='output');
 return <><p className={styles.eyebrow}>DECLARACIÓN EPCIS · EVIDENCIA DEL EVENTO</p><h2>{title(e)}</h2><span className={styles.action} data-action={e.action}>{e.action?(actionLabels[e.action]||e.action):'Entradas y salidas declaradas'}</span>{e.correctionDeclared&&<p className={styles.notice}>Este evento contiene una declaración de error o corrección. No se usa para afirmar una relación vigente; esta vista conserva la referencia histórica.</p>}
  <dl className={styles.facts}><div><dt>Cuándo ocurrió según el emisor</dt><dd>{format(e.occurredAt)}</dd></div><div><dt>Cuándo ingresó a NexID</dt><dd>{format(e.recordedAt)}</dd></div><div><dt>Paso de negocio</dt><dd>{stepLabels[e.step||'']||e.step||'No informado'}</dd></div><div><dt>Disposición declarada</dt><dd>{dispositionLabels[e.disposition||'']||e.disposition||'No informada'}</dd></div></dl>
  {['AggregationEvent','AssociationEvent'].includes(e.type)?<div className={styles.flow}><ReferenceGroup title="Agrupador declarado" items={parent} tenant={tenant} onInvestigate={onInvestigate}/><div className={styles.flowArrow}><ArrowDown size={21} aria-hidden="true"/>{e.action==='DELETE'?'Separación informada, no borrado de historia':e.action==='OBSERVE'?'Relación observada según el emisor':'Relación añadida según el emisor'}</div><ReferenceGroup title="Contenido referenciado" items={children} tenant={tenant} onInvestigate={onInvestigate}/></div>:e.type==='TransformationEvent'?<div className={styles.flow}><ReferenceGroup title="Entradas declaradas" items={inputs} tenant={tenant} onInvestigate={onInvestigate}/><div className={styles.flowArrow}><ArrowDown size={21} aria-hidden="true"/>Transformación declarada · sin inferir cantidades equivalentes</div><ReferenceGroup title="Salidas declaradas" items={outputs} tenant={tenant} onInvestigate={onInvestigate}/></div>:<ReferenceGroup title="Objetos referenciados" items={e.references.filter(r=>r.role==='object')} tenant={tenant} onInvestigate={onInvestigate}/>}
  {e.omittedReferences>0&&<p className={styles.notice}>{e.omittedReferences} referencias no se muestran por límite o falta de vínculo autorizado. No se interpreta la selección como contenido completo.</p>}
  <details className={styles.technical}><summary><Database size={15} aria-hidden="true"/>Origen y referencia técnica</summary><dl><div><dt>Punto de lectura declarado</dt><dd>{e.readPoint||'No informado o no publicable'}</dd></div><div><dt>Ubicación declarada</dt><dd>{e.location||'No informada o no publicable'}</dd></div><div><dt>Referencia del evento</dt><dd>{e.id}</dd></div><div><dt>Tipo original</dt><dd>{e.type}</dd></div></dl></details>
 </>;
}
