"use client";
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {ArrowLeft,CheckCircle2,ShieldCheck,Users,Wallet,FlaskConical,RefreshCw,FileText,Download,X,ArrowRight} from 'lucide-react';
import {boundedDossierJson} from '../lib/batch-dossier-readings';
import {parseLaunchBoard,parseLaunchDetail,checkLaunchReceipt,minorInput,launchMoney,launchReport,launchActions,launchStates,type LaunchBoard,type LaunchDetail,type LaunchSettings} from '../lib/campaign-launch';
import styles from './campaign-launch-workspace.module.css';
const when=(s:string)=>new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short',timeZone:'UTC'}).format(new Date(s))+' UTC';
export function CampaignLaunchWorkspace({initial,initialDetail,tenantScope,global}:{initial:LaunchBoard|null;initialDetail:LaunchDetail|null;tenantScope:string;global:boolean}){
 const [tenantOptions,setTenantOptions]=useState(initial?.tenantOptions||[]);
 const [board,setBoard]=useState(initial),[detail,setDetail]=useState(initialDetail),[tenant,setTenant]=useState(tenantScope),[query,setQuery]=useState(''),[tab,setTab]=useState<'prepare'|'result'|'history'>('prepare'),[busy,setBusy]=useState(false),[message,setMessage]=useState(initial?'':'No se pudo confirmar la consulta.'),[uncertain,setUncertain]=useState(false),[modal,setModal]=useState<{action:string;settings?:LaunchSettings}|null>(null),[note,setNote]=useState(''),[confirm,setConfirm]=useState(false);
 const [currency,setCurrency]=useState<LaunchSettings['currency']>(initialDetail?.plan?.settings.currency||'ARS'),[unitCost,setUnitCost]=useState(initialDetail?.plan?(initialDetail.plan.settings.unitCostMinor/100).toFixed(2):''),[budget,setBudget]=useState(initialDetail?.plan?(initialDetail.plan.settings.budgetMinor/100).toFixed(2):''),[maxRecipients,setMaxRecipients]=useState(initialDetail?.plan?String(initialDetail.plan.settings.maxRecipients):'');
 const pending=useRef<{id:string;tenant:string;action:string;body:any}|null>(null),inflight=useRef(false),controller=useRef<AbortController|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 const sameSettings=Boolean(detail?.plan&&currency===detail.plan.settings.currency&&Number(unitCost.replace(',','.'))===detail.plan.settings.unitCostMinor/100&&Number(budget.replace(',','.'))===detail.plan.settings.budgetMinor/100&&Number(maxRecipients)===detail.plan.settings.maxRecipients);
 const dirty=Boolean(detail&&!sameSettings&&(unitCost||budget||maxRecipients));
 useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 function assign(d:LaunchDetail){setDetail(d);setCurrency(d.plan?.settings.currency||'ARS');setUnitCost(d.plan?(d.plan.settings.unitCostMinor/100).toFixed(2):'');setBudget(d.plan?(d.plan.settings.budgetMinor/100).toFixed(2):'');setMaxRecipients(d.plan?String(d.plan.settings.maxRecipients):'');setBoard(b=>b?{...b,drafts:b.drafts.map(x=>x.id===d.draft.id?{...x,revision:d.draft.revision,review_state:d.plan?.state||null,review_version:d.plan?.version||null,reviewed_revision:d.plan?.draft_revision||null}:x)}:b);}
 const error=(code:string,status:number)=>({launch_draft_changed:'El borrador cambió. Actualizá el estado y configurá una nueva revisión: la aprobación anterior ya no habilita otra simulación.',launch_revision_conflict:'Otra persona actualizó el plan. Se conservan tus importes locales; actualizá antes de continuar.',launch_independent_review_required:'La aprobación requiere otra persona, distinta del autor, editor y quien presentó este plan.',launch_approval_required:'Primero debe aprobarlo otra cuenta autorizada.',launch_draft_archived:'El borrador está archivado. Restauralo desde el editor existente antes de continuar.',launch_action_forbidden:'Tu cuenta no tiene permiso para esta acción o falta MFA.',launch_review_locked:'La revisión está bloqueada. Devolvela a preparación antes de cambiarla.',launch_audience_limit:'La audiencia excede el límite de este ensayo; no se tomó una muestra como si fuera el total.'}[code]||`No se confirmó la operación (${status}). ${code||''}`);
 async function request(path:string,options:RequestInit={}){const abort=new AbortController();controller.current=abort;const timer=setTimeout(()=>abort.abort(),15000);try{const r=await fetch('/api/admin/campaigns/launch'+path,{...options,cache:'no-store',signal:abort.signal});const raw=await boundedDossierJson(r) as any;return {r,raw};}finally{clearTimeout(timer);}}
 async function load(id?:string){if(inflight.current)return;if(dirty&&!window.confirm('Hay importes sin guardar. ¿Descartarlos para consultar el estado del servidor?'))return;inflight.current=true;setBusy(true);setMessage('');
 try{const selectedTenant=id?board?.scope?.slug||tenant:tenant;const {r,raw}=await request((id?'/'+id:'')+'?'+new URLSearchParams(selectedTenant?{tenant:selectedTenant}:{}));if(!r.ok)throw Error(error(raw.reason,r.status));if(!mounted.current)return;if(id){assign(parseLaunchDetail(raw,selectedTenant,id));setTab('prepare');}else{const next=parseLaunchBoard(raw,selectedTenant);setBoard(next);setTenantOptions(next.tenantOptions);setDetail(null);}pending.current=null;setUncertain(false);}
 catch(e){if(mounted.current){if(!id){setBoard(null);setDetail(null);}setMessage((e as Error).message);}}finally{inflight.current=false;if(mounted.current)setBusy(false);}}
 function ask(action:string){setMessage('');setNote('');setConfirm(false);if(action==='configure'){try{const s={currency,unitCostMinor:minorInput(unitCost),budgetMinor:minorInput(budget),maxRecipients:Number(maxRecipients)};if(s.unitCostMinor<1||s.unitCostMinor>10000000||s.budgetMinor>100000000||!Number.isSafeInteger(s.maxRecipients)||s.maxRecipients<1||s.maxRecipients>10000)throw Error('Indicá costo unitario mayor a cero, presupuesto válido y entre 1 y 10.000 destinatarios.');setModal({action,settings:s});}catch(e){setMessage((e as Error).message);}}else setModal({action});}
 async function execute(retry=false){if(inflight.current||!detail||(!retry&&(!modal||!confirm)))return;
 const op=retry?pending.current:{id:detail.draft.id,tenant:detail.scope.slug,action:modal!.action,body:{operationId:crypto.randomUUID(),expectedVersion:detail.plan?.version||0,expectedDraftRevision:detail.draft.revision,...(modal!.settings?{settings:modal!.settings}:{}),...(modal!.action==='request_changes'?{note}:{})}};
 if(!op)return;pending.current=op;setModal(null);inflight.current=true;setBusy(true);setMessage('');let committed=false;
 try{const {r,raw}=await request('/'+op.id+'/'+op.action+'?'+new URLSearchParams({tenant:op.tenant}),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(op.body)});if(!r.ok){if(r.status<500&&r.status!==408&&r.status!==429){pending.current=null;setUncertain(false);}throw Error(error(raw.reason,r.status));}
 const p=checkLaunchReceipt(raw,op.body,op.tenant,op.id,op.action);committed=true;pending.current=null;if(!mounted.current)return;setUncertain(false);assign({...detail,plan:p,sourceChanged:p.draft_revision!==detail.draft.revision||p.draft_snapshot.message!==detail.draft.message||p.draft_snapshot.title!==detail.draft.title||p.draft_snapshot.channel!==detail.draft.channel,history:[]});setTab(op.action==='simulate'?'result':'prepare');setMessage(raw.receipt.replayed?'El intento anterior quedó confirmado, sin duplicar el movimiento.':'Guardado con comprobante. No se enviaron mensajes.');
 try{const fresh=await request('/'+op.id+'?'+new URLSearchParams({tenant:op.tenant}));if(fresh.r.ok&&mounted.current)assign(parseLaunchDetail(fresh.raw,op.tenant,op.id));}catch{if(mounted.current)setMessage('El comprobante confirmó el cambio. La actualización del historial quedó pendiente.');}
 }catch(e){if(mounted.current){if(!committed&&pending.current)setUncertain(true);setMessage((e as Error).message);}}finally{inflight.current=false;if(mounted.current)setBusy(false);}}
 async function download(){if(inflight.current||!detail?.actor.canExport)return;inflight.current=true;setBusy(true);try{const {r,raw}=await request('/'+detail.draft.id+'?'+new URLSearchParams({tenant:detail.scope.slug,export:'1'}));if(!r.ok)throw Error(error(raw.reason,r.status));const d=parseLaunchDetail(raw,detail.scope.slug,detail.draft.id);const url=URL.createObjectURL(new Blob([launchReport(d)],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='nexid-simulacion-campana.html';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Informe de la simulación descargado. No contiene una lista de contactos.');}catch(e){setMessage((e as Error).message);}finally{inflight.current=false;setBusy(false);}}
 const p=detail?.plan,s=p?.latest_simulation,a=s?.audience,canWrite=detail?.actor.canWrite&&!busy&&!uncertain&&detail.draft.status==='draft';
 const canApprove=Boolean(detail?.actor.canApprove&&p&&![p.prepared_by,p.submitted_by,detail.draft.createdBy,detail.draft.updatedBy].includes(detail.actor.id));
 const needsConfig=!p||detail?.sourceChanged;const filtered=(board?.drafts||[]).filter(d=>(d.title+' '+d.channel).toLowerCase().includes(query.toLowerCase()));
 const scope=board?.scope?.slug||tenantScope;
 return <main className={styles.root} data-testid="campaign-launch-workspace"><div className={styles.top}><Link prefetch={false} href={'/loyalty/campaigns?'+new URLSearchParams(scope?{tenant:scope}:{})}><ArrowLeft size={16} aria-hidden="true"/>Editor de campañas</Link><span className={styles.safe}><FlaskConical size={15} aria-hidden="true"/>Sin envíos pagos</span></div>
 <header className={styles.hero}><div><p className={styles.eyebrow}>ACTIVACIÓN COMERCIAL · S7</p><h1>Campañas bajo control.</h1><p>Texto aprobado, audiencia consentida y límites visibles antes de enviar.</p></div><span className={styles.heroIcon}><ShieldCheck size={31} aria-hidden="true"/></span></header>
 <div className={styles.toolbar}>{global&&<label>Empresa<select value={tenant} disabled={busy||uncertain} onChange={e=>{if(dirty&&!window.confirm('¿Descartar los importes locales para consultar otra empresa?'))return;setTenant(e.target.value);setBoard(null);setDetail(null);setMessage('Consultá la empresa elegida para continuar.');}}><option value="">Elegí una empresa</option>{tenantOptions.map(t=><option key={t.slug} value={t.slug}>{t.name}</option>)}</select></label>}<button type="button" disabled={busy} onClick={()=>void load(global&&tenant!==board?.scope?.slug?undefined:detail?.draft.id)}><RefreshCw size={15} aria-hidden="true"/>{busy?'Consultando…':'Actualizar estado'}</button><span>{board?.scope?.name||'Empresa sin seleccionar'} · {board?.actor.label||'Fuente no confirmada'}</span></div>
 <p role="status" className={styles.status}>{message||'Simulación operativa. No crea colas de entrega ni llama a proveedores de mensajería.'}</p>
 {uncertain&&<div className={styles.warning}>No se confirmó la respuesta. Conservamos el mismo intento.<button type="button" disabled={busy} onClick={()=>void execute(true)}>Reconciliar el mismo intento</button></div>}
 <div className={styles.layout}><aside className={styles.sidebar}><div className={styles.sidebarTitle}><FileText size={17} aria-hidden="true"/><h2>Borradores guardados</h2></div><label className={styles.search}>Buscar campaña<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Título o canal"/></label><div className={styles.draftList}>{filtered.map(d=><button key={d.id} type="button" aria-pressed={detail?.draft.id===d.id} disabled={busy} onClick={()=>void load(d.id)}><span>{d.channel} · texto v{d.revision}</span><strong>{d.title}</strong><small>{d.status==='archived'?'Archivado':d.reviewed_revision&&d.reviewed_revision!==d.revision?'Revisión desactualizada':d.review_state?launchStates[d.review_state]:'Por preparar'}</small></button>)}</div>{!filtered.length&&<p>{board?.scope?'No hay borradores en esta consulta. Guardá uno desde el editor existente.':'Seleccioná la empresa para consultar sus campañas.'}</p>}{board?.truncated&&<p>Últimos 50 borradores, no todo el histórico.</p>}<Link prefetch={false} className={styles.linkButton} href={'/loyalty/campaigns?'+new URLSearchParams(scope?{tenant:scope}:{})}>Abrir editor <ArrowRight size={14} aria-hidden="true"/></Link></aside>
 <section className={styles.work}>{!detail?<div className={styles.empty}><ShieldCheck size={46} aria-hidden="true"/><h2>Un mensaje no alcanza.<br/>Hace falta control.</h2><p>Seleccioná un borrador. Definí el límite, pedí revisión y comprobá la audiencia que cumple los requisitos actuales, sin enviar ni un mensaje.</p><div className={styles.emptySteps}><span>01 · Límites</span><span>02 · Revisión</span><span>03 · Simulación</span></div></div>:<>
 <div className={styles.caseTitle}><div><p className={styles.eyebrow}>{detail.draft.channel} · texto v{detail.draft.revision}</p><h2>{detail.draft.title}</h2></div><span className={styles.state}>{detail.draft.status==='archived'?'Archivado':needsConfig?'Por configurar':launchStates[p!.state]}</span></div>
 <div className={styles.tabs} role="group" aria-label="Vistas de campaña">{[['prepare','Preparación y revisión'],['result','Resultado del ensayo'],['history','Historial']].map(([k,v])=><button type="button" aria-pressed={tab===k} key={k} onClick={()=>setTab(k as typeof tab)}>{v}</button>)}</div>
 {detail.sourceChanged&&<p className={styles.warning}>El borrador cambió después de configurar este plan. La aprobación y los resultados anteriores son históricos; no habilitan una nueva simulación.</p>}
 {tab==='prepare'&&<div className={styles.prepareGrid}><div><section className={styles.preview}><div className={styles.previewHeader}><span className={styles.channelDot}/>{detail.draft.channel==='email'?'Vista del contenido':'Texto de comunicación'}<small>Sin envío</small></div><p>{detail.draft.message}</p><footer>Texto v{detail.draft.revision} · el editor original conserva el contenido.</footer></section><p className={styles.note}>El canal determina el consentimiento requerido: <strong>{detail.draft.channel}_marketing</strong>. Aprobar no otorga consentimiento ni garantiza que el proveedor acepte el mensaje.</p></div>
 <div className={styles.controls}><h3><Wallet size={18} aria-hidden="true"/>Límites de la simulación</h3><form onSubmit={e=>{e.preventDefault();ask('configure');}}><div className={styles.pair}><label>Moneda<select value={currency} disabled={!canWrite||p?.state==='in_review'} onChange={e=>setCurrency(e.target.value as LaunchSettings['currency'])}><option>ARS</option><option>USD</option><option>EUR</option></select></label><label>Máximo de destinatarios<input required inputMode="numeric" value={maxRecipients} disabled={!canWrite||p?.state==='in_review'} onChange={e=>setMaxRecipients(e.target.value)} placeholder="Ej.: 100"/></label></div><label>Costo unitario de referencia<input required inputMode="decimal" value={unitCost} disabled={!canWrite||p?.state==='in_review'} onChange={e=>setUnitCost(e.target.value)} placeholder="Ingresá tu referencia"/></label><label>Presupuesto de referencia<input required inputMode="decimal" value={budget} disabled={!canWrite||p?.state==='in_review'} onChange={e=>setBudget(e.target.value)} placeholder="Importe máximo"/></label><p className={styles.note}>Valores ingresados por la empresa. No son precios consultados al proveedor ni un límite de facturación real.</p><button type="submit" className={styles.primary} disabled={!canWrite||p?.state==='in_review'||(!dirty&&!needsConfig)}>Guardar límites</button></form>
 {p?.state==='configured'&&<button type="button" disabled={!canWrite||dirty||needsConfig} onClick={()=>ask('submit')}>Solicitar revisión</button>}
 {p?.state==='in_review'&&<><button type="button" className={styles.primary} disabled={!canApprove||busy||uncertain||needsConfig} onClick={()=>ask('approve')}>Aprobar simulación</button>{!canApprove&&<p className={styles.note}>Debe revisar otra cuenta de administración autorizada, con MFA; no el autor ni quien preparó o presentó el plan.</p>}</>}
 {p&&['in_review','approved'].includes(p.state)&&<button type="button" disabled={!canWrite} onClick={()=>ask('request_changes')}>Devolver a preparación</button>}
 {p?.state==='approved'&&<button type="button" className={styles.primary} disabled={!canWrite||dirty||needsConfig} onClick={()=>ask('simulate')}><FlaskConical size={17} aria-hidden="true"/>Simular audiencia</button>}
 </div></div>}
 {tab==='result'&&(s&&a?<div><div className={styles.resultHeader}><div><p className={styles.eyebrow}>DATOS OBSERVADOS · NO ENTREGAS</p><h3>Resultado de la simulación</h3><p>{when(s.observedAt)} · texto v{s.draftRevision} · plan r{s.planVersion}</p></div><button type="button" disabled={!detail.actor.canExport||busy} onClick={()=>void download()}><Download size={16} aria-hidden="true"/>Descargar informe</button></div>
 <div className={styles.metrics}><div><Users size={18} aria-hidden="true"/><span>Destinos únicos elegibles</span><strong>{a.eligibleDestinations}</strong><small>Con consentimiento actual del canal</small></div><div><ShieldCheck size={18} aria-hidden="true"/><span>Candidatos simulados</span><strong>{s.candidateCount}</strong><small>Dentro de ambos límites</small></div><div><Wallet size={18} aria-hidden="true"/><span>Estimación de referencia</span><strong>{launchMoney(s.estimatedCostMinor,s.currency)}</strong><small>No facturado por el proveedor</small></div></div>
 <div className={styles.budgetLine}><span>Presupuesto configurado: <b>{launchMoney(s.budgetMinor,s.currency)}</b></span><div role="meter" aria-label="Presupuesto de referencia utilizado en la simulación" aria-valuemin={0} aria-valuemax={s.budgetMinor||1} aria-valuenow={s.estimatedCostMinor}><span style={{width:(s.budgetMinor?100*s.estimatedCostMinor/s.budgetMinor:0)+'%'}}/></div></div>
 <h3 className={styles.sectionTitle}>Cómo se obtuvo este resultado</h3><div className={styles.breakdown}>{[['Miembros de la empresa observados',a.membersObserved],['Membresías inactivas',a.inactiveMembership],['Sin consentimiento vigente del canal',a.missingCurrentConsent],['Contacto ausente o con formato no utilizable',a.unusableContact],['Destinos duplicados',a.duplicateDestinations],['Excluidos por máximo de destinatarios',s.excludedByRecipientLimit],['Excluidos por presupuesto de referencia',s.excludedByBudget]].map(([k,v])=><div key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div>
 <p className={styles.safeResult}><CheckCircle2 size={18} aria-hidden="true"/>Este ensayo: <strong>0 mensajes enviados · 0 cargos de mensajería</strong></p><p className={styles.note}>El consentimiento se vuelve a leer en cada ensayo. Este resultado no es una lista exportable de contactos ni una autorización futura de envío. La validez real del contacto y de la plantilla requiere al proveedor.</p></div>:<div className={styles.empty}><FlaskConical size={38} aria-hidden="true"/><h3>Todavía no hay una simulación confirmada.</h3><p>Guardá límites, pedí revisión y ejecutá el ensayo aprobado. No se inventan audiencia ni resultados de entrega.</p></div>)}
 {tab==='history'&&<div><h3>Últimos 30 movimientos</h3><p className={styles.note}>Cada cambio conserva actor, fecha y versión. Un reintento idéntico no crea otra aprobación ni otra simulación.</p>{detail.history.map(h=><article className={styles.historyItem} key={h.id}><span>r{h.version}</span><div><strong>{launchActions[h.action]||h.action}</strong><p>{h.actorLabel} · {when(h.at)}</p>{h.note&&<p>{h.note}</p>}{h.simulation&&<p>{h.simulation.candidateCount} candidatos simulados · {launchMoney(h.simulation.estimatedCostMinor,h.simulation.currency)} de referencia · sin envíos</p>}</div></article>)}{!detail.history.length&&<p>Sin movimientos recibidos en esta consulta.</p>}</div>}
 </> }</section></div>
 {modal&&<LaunchDialog title={launchActions[modal.action]} onClose={()=>setModal(null)}><p>{modal.action==='configure'?'Se guardará el límite para la versión actual del texto. Una aprobación o simulación anterior deja de estar vigente.':modal.action==='approve'?'Vas a aprobar el contenido y los límites para una simulación. Esto no habilita el envío real ni autoriza cargos.':modal.action==='simulate'?'Se consultará el consentimiento vigente y se guardará un resultado agregado. No se contactará a ninguna persona ni se llamará a un proveedor.':modal.action==='request_changes'?'Se retirará la aprobación vigente y se dejará el plan listo para corregir. Los movimientos previos se conservan.':'Se bloqueará la configuración para revisión por otra cuenta autorizada.'}</p>{modal.action==='request_changes'&&<label>Motivo de la devolución<textarea value={note} minLength={10} maxLength={500} onChange={e=>setNote(e.target.value)}/></label>}<label className={styles.checkbox}><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Confirmo guardar esta acción sin enviar mensajes.</label><div className={styles.dialogActions}><button type="button" onClick={()=>setModal(null)}>Volver</button><button type="button" className={styles.primary} disabled={!confirm||busy||(modal.action==='request_changes'&&note.trim().length<10)} onClick={()=>void execute()}>Confirmar acción</button></div></LaunchDialog>}
 </main>;
}
function LaunchDialog({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const prior=document.activeElement as HTMLElement;ref.current?.showModal();return()=>prior?.focus();},[]);return <dialog className={styles.dialog} ref={ref} aria-labelledby="launch-dialog-title" onCancel={e=>{e.preventDefault();onClose();}}><div className={styles.dialogHeader}><h2 id="launch-dialog-title">{title}</h2><button type="button" aria-label="Cerrar confirmación" onClick={onClose}><X size={20} aria-hidden="true"/></button></div>{children}</dialog>;}
