"use client";
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {ArrowLeft,ArrowRight,CheckCheck,FilePenLine,Search,RefreshCw,ClipboardCheck,Clock3,ChevronLeft,ChevronRight,Link2,ShieldCheck,BookOpen,Users,Filter} from 'lucide-react';
import {parseEditorialQueue,queueParams,queueStudioHref,queueDate,QUEUE_STATES,QUEUE_STEPS,INITIAL_QUEUE_FILTERS,type QueueFilters,type EditorialQueue,type QueueItem} from '../lib/editorial-queue';
import {boundedDossierJson} from '../lib/batch-dossier-readings';
import styles from './editorial-queue.module.css';
export function EditorialQueueWorkspace({initial,tenant,filters:initialFilters,enabled=true}:{initial:EditorialQueue|null;tenant:string;filters:QueueFilters;enabled?:boolean}){
 const [filtersOpen,setFiltersOpen]=useState(false);
 const [data,setData]=useState(initial),[filters,setFilters]=useState(initialFilters),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null),[trail,setTrail]=useState<(string|null)[]>([null]),[error,setError]=useState(initial?'':'La fuente todavía no confirmó los pasaportes. No se presume una bandeja vacía.'),[copied,setCopied]=useState(false);
 const alive=useRef(true),flight=useRef<AbortController|null>(null),generation=useRef(0),detail=useRef<HTMLElement|null>(null),list=useRef<HTMLDivElement|null>(null),retry=useRef<{f:QueueFilters;cursor:string|null;index:number}|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;generation.current++;flight.current?.abort();};},[]);
 function change(next:QueueFilters){generation.current++;flight.current?.abort();setData(null);setSelected(null);setCopied(false);retry.current=null;setFilters(next);setTrail([null]);setError('Filtros modificados. Consultá para actualizar los resultados.');}
 async function load(f:QueueFilters,cursor:string|null=null,index=0){
  if(flight.current||!enabled)return;const applied={...f,q:f.q.trim()},seq=++generation.current,controller=new AbortController();flight.current=controller;retry.current={f:applied,cursor,index};setBusy(true);setData(null);setSelected(null);setError('');setCopied(false);const timer=setTimeout(()=>controller.abort(),12000);
  try{
   const response=await fetch('/api/admin/passport-editorial/queue?'+queueParams(tenant,applied,cursor),{cache:'no-store',credentials:'same-origin',signal:controller.signal});
   if(!response.ok){if(response.status===409)retry.current=null;throw Error(response.status===403?'No hay permiso para consultar este alcance.':response.status===409?'Cambió la posición o los permisos. Iniciá una nueva consulta.':response.status===400?'Revisá los filtros; no se aceptan campos inesperados.':'La fuente no pudo confirmar esta página. Reintentá sin modificar los pasaportes.');}
   const result=parseEditorialQueue(await boundedDossierJson(response),tenant,applied,index+1);if(alive.current&&seq===generation.current){setData(result);setFilters(applied);setFiltersOpen(false);setTrail(t=>[...t.slice(0,index),cursor]);requestAnimationFrame(()=>list.current?.scrollTo({top:0}));}
  }catch(e){if(alive.current&&seq===generation.current)setError(e instanceof Error?e.message:'Consulta no confirmada.');}
  finally{clearTimeout(timer);if(flight.current===controller)flight.current=null;if(alive.current)setBusy(false);}
 }
 function navigate(direction:'previous'|'next'){if(!data)return;const index=direction==='next'?data.navigation.page:data.navigation.page-2,cursor=direction==='next'?data.navigation.nextCursor:trail[index];if(index<0||direction==='next'&&!cursor)return;void load(data.filters,cursor??null,index);}
 function pick(row:QueueItem){setSelected(row.id);if(matchMedia('(max-width:800px)').matches)requestAnimationFrame(()=>{detail.current?.focus({preventScroll:true});detail.current?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});});}
 async function copy(){if(!data)return;const url=new URL('/passports/review',window.location.origin);url.search=queueParams(tenant,data.filters).toString();try{await navigator.clipboard.writeText(url.href);setCopied(true);}catch{setError('No se pudo copiar el enlace. Los filtros y los datos permanecen intactos.');}}
 const active=data?.items.find(x=>x.id===selected)||data?.items[0],pending=(data?.summary.byState.in_review||0)+(data?.summary.byState.approved||0);
 return <main className={styles.root} data-testid="editorial-queue"><div className={styles.top}><Link prefetch={false} href={'/batches?'+queueParams(tenant,INITIAL_QUEUE_FILTERS)}><ArrowLeft size={16} aria-hidden="true"/>Volver a Lotes</Link><span>Productos y pasaportes · revisión editorial</span></div>
 <header className={styles.hero}><div><p className={styles.eyebrow}>DE LA PREPARACIÓN A LA PUBLICACIÓN</p><h1>Bandeja editorial</h1><p>{tenant||'Todas las empresas autorizadas'} · Pasaportes que ya usan Studio.</p></div><div className={styles.heroIcon}><ClipboardCheck size={32} aria-hidden="true"/></div></header>
 <div className={styles.metrics}><section><BookOpen size={18} aria-hidden="true"/><span>Pasaportes en Studio</span><strong>{data?data.summary.total:'—'}</strong></section><section><Users size={18} aria-hidden="true"/><span>Revisión o publicación pendientes</span><strong>{data?pending:'—'}</strong></section><section><FilePenLine size={18} aria-hidden="true"/><span>Próximo paso para mi rol</span><strong>{data?data.summary.forActor:'—'}</strong></section></div>
 <p className={styles.meta}>Indicadores de todo este alcance, no sólo de la página o búsqueda. No incluyen lotes sin incorporar a Studio.</p>
 <button type="button" className={styles.filterToggle} aria-expanded={filtersOpen} aria-controls="editorial-queue-filters" onClick={()=>setFiltersOpen(v=>!v)}><Filter size={16} aria-hidden="true"/>Buscar y filtrar</button><p className={styles.filterSummary}>{filters.state?QUEUE_STATES[filters.state as keyof typeof QUEUE_STATES]||"Estado por validar":"Todos los estados"} · {filters.view==='mine'?"Para mi rol":"Todo el alcance"}{filters.q?` · ${filters.q}`:""}</p><form id="editorial-queue-filters" data-open={filtersOpen} className={styles.filters} onSubmit={e=>{e.preventDefault();void load(filters);}}><label className={styles.search}><span>Producto, lote o empresa</span><div><Search size={17} aria-hidden="true"/><input type="search" maxLength={100} value={filters.q} disabled={busy} placeholder="Buscar entre pasaportes gestionados" onChange={e=>change({...filters,q:e.target.value})}/></div></label><label>Estado editorial<select value={filters.state} disabled={busy} onChange={e=>change({...filters,state:e.target.value})}><option value="">Todos los estados</option>{Object.entries(QUEUE_STATES).map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label><label>Trabajo a consultar<select value={filters.view} disabled={busy} onChange={e=>change({...filters,view:e.target.value as 'all'|'mine'})}><option value="all">Todo el alcance</option><option value="mine">Para mi rol</option></select></label><button className={styles.primary} type="submit" disabled={busy||!enabled}><RefreshCw size={16} aria-hidden="true"/>{busy?'Consultando…':'Consultar bandeja'}</button></form>
 <p className={styles.status} role="status">{error||(busy?'Consultando estados y permisos vigentes.':data?`Fuente: base operativa · ${queueDate(data.observedAt)} · ${data.matched} coincidencias.`:'Sin resultados confirmados.')}{copied?' Enlace copiado: abre la primera página con estos filtros; requiere autorización.':''}</p>
 {error&&!busy&&retry.current&&<button type="button" onClick={()=>{const r=retry.current!;void load(r.f,r.cursor,r.index);}}>Reintentar esta página</button>}
 {data&&<><nav className={styles.states} aria-label="Filtrar por estado editorial">{Object.entries(QUEUE_STATES).map(([state,label])=><button type="button" key={state} aria-pressed={filters.state===state} onClick={()=>{const f={...filters,state};setFilters(f);void load(f);}}><span className={styles.dot} data-state={state}/>{label}<b>{data.summary.byState[state as keyof typeof QUEUE_STATES]}</b></button>)}</nav>
 <div className={styles.pagebar}><span>Página {data.navigation.page} · {data.items.length} pasaportes visibles</span><div><button type="button" aria-label="Página anterior" disabled={busy||data.navigation.page===1} onClick={()=>navigate('previous')}><ChevronLeft size={16} aria-hidden="true"/>Anterior</button><button type="button" aria-label="Página siguiente" disabled={busy||!data.navigation.hasNext} onClick={()=>navigate('next')}>Siguiente<ChevronRight size={16} aria-hidden="true"/></button><button type="button" disabled={busy} onClick={()=>void copy()}><Link2 size={16} aria-hidden="true"/>Copiar búsqueda</button></div></div>
 {data.items.length?<div className={styles.layout}><div ref={list} tabIndex={0} className={styles.list} role="region" aria-label="Pasaportes de esta página">{data.items.map(row=><article className={styles.item} data-selected={active?.id===row.id} key={row.id}><button type="button" className={styles.select} onClick={()=>pick(row)} aria-label={`Ver próximo paso de ${row.product||row.bid}`}><span className={styles.eyebrow}>{row.tenantName} · {row.bid}</span><h2>{row.product||'Producto por completar'}</h2><span className={styles.badge} data-state={row.state}>{QUEUE_STATES[row.state]}</span><p>Revisión r{row.revision} · {row.publishedVersion?'publicado v'+row.publishedVersion:'contenido inicial sin publicación Studio'}</p><small><Clock3 size={13} aria-hidden="true"/>Último cambio: {queueDate(row.updatedAt)}</small></button><footer><span>{QUEUE_STEPS[row.code].role}</span><Link prefetch={false} href={queueStudioHref(row)}>{row.forActor?QUEUE_STEPS[row.code].label:'Consultar en Studio'}<ArrowRight size={15} aria-hidden="true"/></Link></footer></article>)}</div><section ref={detail} tabIndex={-1} className={styles.detail} aria-label="Próximo paso del pasaporte">{active&&<QueueDetail item={active}/>}</section></div>:<section className={styles.empty}><Filter size={32} aria-hidden="true"/><h2>{data.summary.total?'No hay pasaportes que coincidan con estos filtros':'Todavía no hay pasaportes incorporados a Studio'}</h2><p>{data.summary.total?'Esto no cambia el estado de tus pasaportes. Revisá el estado elegido o consultá todo el alcance.':'Los productos actuales no se inscriben automáticamente. Abrí Lotes y elegí un pasaporte para iniciar su circuito editorial con una cuenta autorizada.'}</p>{data.summary.total?<button type="button" onClick={()=>{setFilters(INITIAL_QUEUE_FILTERS);void load(INITIAL_QUEUE_FILTERS);}}>Consultar sin filtros</button>:<Link className={styles.primary} prefetch={false} href={'/batches?'+queueParams(tenant,INITIAL_QUEUE_FILTERS)}>Abrir Lotes<ArrowRight size={16} aria-hidden="true"/></Link>}</section>}
 <p className={styles.boundary}><ShieldCheck size={17} aria-hidden="true"/>Orden por último cambio más antiguo. No indica vencimiento ni incumplimiento. La cola se vuelve a consultar: los cambios de estado pueden mover filas entre páginas.</p></>}
 </main>;
}
function QueueDetail({item:i}:{item:QueueItem}){const step=QUEUE_STEPS[i.code];return <><p className={styles.eyebrow}>SIGUIENTE PASO · {step.role}</p><h2>{i.product||i.bid}</h2><p className={styles.subtitle}>{i.tenantName} · {i.bid}</p><div className={styles.next}><ClipboardCheck size={22} aria-hidden="true"/><div><h3>{step.label}</h3><p>{step.detail}</p></div></div><ol className={styles.flow} aria-label="Etapas del pasaporte">{[['Preparar',['draft','changes_requested']],['Revisar',['in_review']],['Publicar',['approved']],['Publicado',['published']]].map(([label,states],n)=><li key={String(label)} data-current={(states as string[]).includes(i.state)}><span>{n+1}</span>{String(label)}</li>)}</ol><dl className={styles.facts}><div><dt>Estado guardado</dt><dd>{QUEUE_STATES[i.state]} · r{i.revision}</dd></div><div><dt>Versión pública de Studio</dt><dd>{i.publishedVersion?'v'+i.publishedVersion:'Todavía no publicada desde Studio'}</dd></div><div><dt>Plantilla / idioma</dt><dd>{i.template==='agro'?'Agro':'General'} · {i.locale}</dd></div><div><dt>Último movimiento</dt><dd>{i.lastChange?.actorLabel||'Responsable no informado'}<small>{queueDate(i.updatedAt)}</small></dd></div></dl>{i.lastChange?.note&&<section className={styles.correction}><h3>Corrección solicitada</h3><p>{i.lastChange.note}</p><small>Comentario guardado en la revisión; no modifica el pasaporte público.</small></section>}<Link prefetch={false} className={styles.primary} href={queueStudioHref(i)}>Abrir Passport Studio<ArrowRight size={17} aria-hidden="true"/></Link><p className={styles.safety}>Este acceso no aprueba ni publica. Studio vuelve a comprobar la revisión, los permisos y los requisitos de MFA. “Para mi rol” no es una asignación personal ni una autorización permanente.</p></>;}
