"use client";
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {ArrowLeft,ArrowRight,Check,ClipboardCheck,FileJson,FileUp,History,Layers,RefreshCw,ShieldCheck,Download} from 'lucide-react';
import {guidedEpcis,parseDocumentText,parseIntakeBoard,parseIntakePreview,parseIntakeCommit,INTAKE_TYPES,type IntakeBoard,type IntakePreview,type IntakeReceipt} from '../lib/epcis-intake-model';
import {boundedDossierJson} from '../lib/batch-dossier-readings';
import styles from './epcis-intake-workspace.module.css';
const steps:Record<string,string>={receiving:'Recepción',shipping:'Despacho',storing:'Almacenamiento'};
const when=(s:string)=>new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(s))+' UTC';
const errors:Record<string,string>={intake_event_time_with_zone_required:'Cada evento necesita una fecha válida con hora y zona horaria explícita.',intake_unique_event_id_required:'Cada evento necesita un identificador estable y no repetido.',epcis_unknown_gs1_identity:'Hay identidades que no están registradas y habilitadas para esta empresa.',intake_event_not_linked_to_selected_batch:'Cada evento debe incluir una identidad del lote seleccionado.',intake_event_fields_unsupported:'El evento contiene campos no admitidos por este asistente. No se descartaron silenciosamente.',intake_document_fields_unsupported:'El archivo contiene extensiones no admitidas por el asistente.',epcis_event_id_conflict:'El identificador del evento ya existe. Revisá el recorrido: no se duplicó ni reemplazó.',intake_operation_payload_conflict:'Este intento ya fue usado con otro contenido. Se conserva el comprobante original.',intake_preview_changed:'El contenido o sus identidades cambiaron. Prepará una nueva revisión.',intake_write_or_mfa_required:'Para confirmar necesitás permiso de escritura logística y una sesión con MFA.'};
export function EpcisIntakeWorkspace({initial,bid,tenant}:{initial:IntakeBoard|null;bid:string;tenant:string}){
 const [board,setBoard]=useState(initial),[mode,setMode]=useState<'guided'|'file'>('guided'),[reference,setReference]=useState(''),[identity,setIdentity]=useState(''),[date,setDate]=useState(''),[step,setStep]=useState('receiving'),[raw,setRaw]=useState(''),[fileName,setFileName]=useState(''),[preview,setPreview]=useState<IntakePreview|null>(null),[document,setDocument]=useState<unknown>(null),[receipt,setReceipt]=useState<IntakeReceipt|null>(null),[agree,setAgree]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(initial?'':'La configuración no pudo confirmarse. Reintentá la consulta.'),[tab,setTab]=useState<'prepare'|'receipts'>('prepare'),[uncertain,setUncertain]=useState(false);
 const pending=useRef<any>(null),controller=useRef<AbortController|null>(null),mounted=useRef(true),running=useRef(false),result=useRef<HTMLDivElement|null>(null),review=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{if(receipt)result.current?.focus();},[receipt]);
 useEffect(()=>{if(!preview)return;review.current?.focus({preventScroll:true});if(window.matchMedia('(max-width:780px)').matches)review.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});},[preview]);
 const locked=busy||uncertain,base=`/api/admin/batches/${encodeURIComponent(bid)}/epcis-intake`,query='?'+new URLSearchParams(tenant?{tenant}:{});
 function invalidate(){setPreview(null);setDocument(null);setAgree(false);setReceipt(null);setMessage('');}
 function save(value:unknown,name:string){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=window.document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);}
 async function readFile(file:File){if(locked||running.current)return;invalidate();setRaw('');setFileName('');if(file.size>100000){setMessage('El archivo supera 100 kB. No se cargó.');return;}running.current=true;setBusy(true);try{const text=await file.text();parseDocumentText(text);if(mounted.current){setRaw(text);setFileName(file.name.slice(0,120));setMode('file');}}catch(e){if(mounted.current)setMessage((e as Error).message);}finally{running.current=false;if(mounted.current)setBusy(false);}}
 async function run(action:'read'|'preview'|'commit'){
  if(running.current)return;running.current=true;setBusy(true);setMessage('');const c=new AbortController();controller.current=c;const timer=setTimeout(()=>c.abort(),20000);
  try{
   let body:any;
   if(action==='preview'){let doc;if(reference.trim().length<4)throw Error('Ingresá una referencia única de la recepción, despacho o archivo.');if(mode==='guided'){const chosen=board?.identities.find(i=>i.id===identity);if(!chosen)throw Error('Elegí una identidad registrada del lote.');doc=await guidedEpcis(board!.scope.tenant,chosen,reference,date,step);}else doc=parseDocumentText(raw);body={document:doc};setPreview(null);setDocument(doc);setReceipt(null);}
   if(action==='commit'){if(!preview||!board?.capabilities.canCommit||!agree)throw Error('Revisá y confirmá el alcance antes de registrar.');body=pending.current||{document,operationId:crypto.randomUUID(),previewDigest:preview.previewDigest,reference:reference.trim(),confirmBid:bid};pending.current=body;}
   const response=await fetch(base+(action==='read'?'':'/'+action)+query,{method:action==='read'?'GET':'POST',headers:action==='read'?undefined:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:c.signal});
   const data=await boundedDossierJson(response) as any;
   if(!response.ok)throw Error(response.status===429?'Límite de confirmaciones alcanzado. Esperá un minuto y retomá el mismo intento.':(errors[data.reason]||`No se confirmó la operación: ${data.reason||response.status}.`)+(data.row?` Revisá el evento ${data.row}.`:''));
   if(!mounted.current)return;
   if(action==='read'){const next=parseIntakeBoard(data,bid,tenant);setBoard(next);const recovered=next.receipts.find(r=>r.operationId===pending.current?.operationId&&r.documentDigest===preview?.documentDigest&&r.reference===pending.current?.reference);if(recovered){setReceipt({...recovered,replayed:true});setUncertain(false);pending.current=null;setTab('prepare');setMessage('Comprobante recuperado. No se volvió a registrar el archivo.');}}
   if(action==='preview'){const next=parseIntakePreview(data,bid,tenant);setPreview(next);setAgree(false);setMessage(next.ready?'Validación completa. Todavía no se registraron movimientos.':'Hay eventos ya registrados. Revisá el recorrido o recuperá el comprobante; no se reemplazan.');}
   if(action==='commit'){const saved=parseIntakeCommit(data,board!.scope,body.operationId,preview!.documentDigest);setReceipt(saved);setBoard({...board!,receipts:[saved,...board!.receipts.filter(r=>r.captureId!==saved.captureId)].slice(0,15)});setUncertain(false);pending.current=null;setMessage(saved.replayed?'Se recuperó el comprobante original, sin duplicación.':'Movimiento registrado. Ya está disponible en el recorrido del lote.');}
  }catch(e){if(mounted.current){if(action==='commit'&&pending.current)setUncertain(true);setMessage(e instanceof Error?e.message:'No se confirmó la operación.');}}
  finally{clearTimeout(timer);running.current=false;controller.current=null;if(mounted.current)setBusy(false);}
 }
 return <main className={styles.root} data-testid="epcis-intake-workspace">
 <nav className={styles.top}><Link prefetch={false} href={`/batches/${encodeURIComponent(bid)}/traceability?${new URLSearchParams(tenant?{tenant}:{})}`}><ArrowLeft size={16} aria-hidden="true"/>Recorrido del lote</Link><button type="button" onClick={()=>void run('read')} disabled={busy}><RefreshCw size={15} aria-hidden="true"/>Actualizar comprobantes</button></nav>
 <header className={styles.hero}><div><p className={styles.eyebrow}>DEL MOVIMIENTO A LA EVIDENCIA</p><h1>Registrar movimientos</h1><p>{board?.scope.product||bid} · {board?.scope.tenant||tenant}</p></div><span className={styles.heroIcon}><Layers size={31} aria-hidden="true"/></span></header>
 <ol className={styles.steps}>{['Preparar','Validar','Registrar'].map((label,i)=><li key={label} data-current={(receipt?2:preview?1:0)===i}><span>{receipt&&i===2?<Check size={17} aria-hidden="true"/>:String(i+1).padStart(2,'0')}</span>{label}</li>)}</ol>
 <div className={styles.tabs} role="group" aria-label="Trabajo con movimientos"><button type="button" aria-pressed={tab==='prepare'} onClick={()=>setTab('prepare')}><FileJson size={17} aria-hidden="true"/>Nuevo movimiento</button><button type="button" aria-pressed={tab==='receipts'} onClick={()=>setTab('receipts')}><History size={17} aria-hidden="true"/>Mis comprobantes</button></div>
 <p role="status" className={styles.status}>{message}</p>
 <section hidden={tab!=='prepare'} className={styles.layout}>
 <div className={styles.card}><h2>1. Prepará los datos</h2><p>Elegí una recepción, despacho o almacenamiento; también podés cargar un archivo EPCIS del sistema origen.</p>
 <div className={styles.modes}><button type="button" disabled={locked} aria-pressed={mode==='guided'} onClick={()=>{setMode('guided');invalidate();}}>Carga guiada</button><button type="button" disabled={locked} aria-pressed={mode==='file'} onClick={()=>{setMode('file');invalidate();}}>Archivo del ERP / WMS</button></div>
 <label className={styles.field}>Referencia única del movimiento<input value={reference} maxLength={160} placeholder="Ej.: RECEPCION-00042" disabled={locked} onChange={e=>{setReference(e.target.value);invalidate();}}/></label><p className={styles.small}>Mantené la misma referencia al reintentar. No uses la misma para movimientos distintos.</p>
 {mode==='guided'?<div className={styles.form}>
 <label className={styles.field}>Identidad registrada<select value={identity} disabled={locked} onChange={e=>{setIdentity(e.target.value);invalidate();}}><option value="">Elegí el producto o unidad</option>{board?.identities.map(i=><option key={i.id} value={i.id}>{i.gtin} · {i.serial||i.lot||'sin serie'}</option>)}</select></label>
 <div className={styles.pair}><label className={styles.field}>Qué ocurrió<select value={step} disabled={locked} onChange={e=>{setStep(e.target.value);invalidate();}}><option value="receiving">Recepción</option><option value="shipping">Despacho</option><option value="storing">Almacenamiento</option></select></label><label className={styles.field}>Cuándo ocurrió · hora local<input type="datetime-local" value={date} disabled={locked} onChange={e=>{setDate(e.target.value);invalidate();}}/></label></div>
 {board?.identityCount===0&&<p className={styles.notice}>Este lote todavía no tiene identidades GS1 registradas. No creamos una para simular movimientos ni cambiamos sus etiquetas NFC. <Link prefetch={false} href={`/batches/${encodeURIComponent(bid)}/channels?${new URLSearchParams(tenant?{tenant}:{})}`}>Abrir configuración del lote</Link></p>}
 </div>:<div className={styles.upload} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files[0])void readFile(e.dataTransfer.files[0]);}}><FileUp size={28} aria-hidden="true"/><label>Arrastrá un archivo JSON o seleccioná uno<input type="file" accept=".json,application/json,application/ld+json" disabled={locked} onChange={e=>{if(e.target.files?.[0])void readFile(e.target.files[0]);}}/></label><span>{fileName||'Hasta 100 kB · 50 eventos · 100 vínculos'}</span><label className={styles.field}>O pegá el documento EPCIS<textarea rows={6} value={raw} maxLength={100000} disabled={locked} onChange={e=>{setRaw(e.target.value);setFileName('');invalidate();}} spellCheck={false}/></label></div>}
 <button type="button" className={styles.primary} disabled={locked||!board?.capabilities.canPrepare} onClick={()=>void run('preview')}><ClipboardCheck size={17} aria-hidden="true"/>Validar sin registrar</button>
 <details className={styles.help}><summary>Qué valida este paso</summary><p>Formato EPCIS 2.0 del perfil admitido, identificadores de evento estables, identidades GS1 autorizadas y relación con este lote. No prueba la lectura física de una antena ni la verificación NFC.</p></details>
 </div>
 <div ref={review} tabIndex={-1} className={`${styles.card} ${styles.review}`}><h2>{receipt?'3. Comprobante registrado':'2. Revisá antes de confirmar'}</h2>
 {receipt?<div ref={result} tabIndex={-1} className={styles.receipt} data-testid="intake-receipt"><Check size={31} aria-hidden="true"/><h3>{receipt.replayed?'Comprobante recuperado':'Movimientos registrados'}</h3><p>{receipt.reference} · {receipt.eventCount} {receipt.eventCount===1?'evento':'eventos'} · {receipt.projectionCount} vínculos</p><p>{when(receipt.at)}</p><code>{receipt.captureId}</code><button type="button" className={styles.primary} onClick={()=>save({scope:board!.scope,receipt},'nexid-comprobante-movimientos.json')}><Download size={16} aria-hidden="true"/>Descargar comprobante</button><Link prefetch={false} className={styles.button} href={`/batches/${encodeURIComponent(bid)}/traceability?${new URLSearchParams({tenant:board!.scope.tenant})}`}>Abrir recorrido del lote<ArrowRight size={16} aria-hidden="true"/></Link><p className={styles.small}>Es evidencia de una declaración registrada; no certifica presencia física, custodia actual o estado del precinto.</p></div>:preview?<>
 <div className={styles.metrics}><div><strong>{preview.eventCount}</strong><span>eventos revisados</span></div><div><strong>{preview.projectionCount}</strong><span>vínculos a identidades</span></div><div><strong>{preview.webhookEndpoints}</strong><span>integraciones receptoras</span></div></div>
 <ol className={styles.events}>{preview.events.map(e=><li key={e.id}><span className={styles.eventNo}>{e.row}</span><div><strong>{INTAKE_TYPES[e.type]||e.type}</strong><p>{when(e.time)} · {steps[e.step.split('-').at(-1)||'']||e.step||'Paso no informado'}</p><p>{e.identities.map(i=>i.serial||i.lot||i.gtin).join(' · ')}</p><span className={e.existing?styles.badgeWarning:styles.badge}>{e.existing?'Ya registrado':'Identidades verificadas en el registro'}</span><details><summary>Referencia del sistema origen</summary><code>{e.id}</code></details></div></li>)}</ol>
 {preview.webhookEndpoints>0&&<p className={styles.notice}>Al confirmar, el motor pondrá en cola notificaciones para las integraciones ya configuradas. No envía campañas comerciales ni mensajes al consumidor.</p>}
 <label className={styles.confirm}><input type="checkbox" checked={agree} disabled={busy||uncertain||!preview.ready||!board?.capabilities.canCommit} onChange={e=>setAgree(e.target.checked)}/><span>Confirmo registrar estos movimientos declarados en <strong>{bid}</strong>. No estoy verificando físicamente el producto.</span></label>
 <button type="button" className={styles.primary} disabled={busy||!agree||!board?.capabilities.canCommit||!preview.ready} onClick={()=>void run('commit')}><ShieldCheck size={18} aria-hidden="true"/>{uncertain?'Reconciliar el mismo intento':'Confirmar registro'}</button>
 {uncertain&&<p className={styles.notice}>La respuesta quedó sin confirmar. Los datos se mantienen bloqueados para recuperar el mismo intento. También podés actualizar los comprobantes sin enviar otra operación.</p>}
 {board?.capabilities.mfaRequired&&<p className={styles.notice}>La sesión necesita verificación MFA antes de confirmar.</p>}
 {!board?.capabilities.canCommit&&!board?.capabilities.mfaRequired&&<p className={styles.notice}>Tu cuenta puede preparar la carga; la confirmación requiere escritura logística y MFA.</p>}
 <button type="button" className={styles.button} disabled={busy} onClick={()=>save(document,'nexid-documento-epcis.json')}><FileJson size={16} aria-hidden="true"/>Descargar documento revisado</button>
 </>:<div className={styles.empty}><ClipboardCheck size={33} aria-hidden="true"/><h3>El registro empieza por una revisión</h3><p>Los eventos y sus destinos aparecerán aquí después de validar. Seleccionar un archivo o abrir esta página no escribe movimientos.</p></div>}
 </div></section>
 <section hidden={tab!=='receipts'} className={styles.card}><h2>Mis comprobantes de este lote</h2><p>Hasta 15 confirmaciones recientes de tu cuenta. Se conservan aunque cierres el navegador.</p><div className={styles.history}>{board?.receipts.map(r=><article key={r.captureId}><ClipboardCheck size={21} aria-hidden="true"/><div><strong>{r.reference}</strong><p>{r.eventCount} {r.eventCount===1?'evento':'eventos'} · {when(r.at)}</p><small>{r.captureId}</small></div><button type="button" onClick={()=>save({scope:board!.scope,receipt:r},'nexid-comprobante-movimientos.json')}><Download size={15} aria-hidden="true"/>Descargar</button></article>)}</div>{board&&!board.receipts.length&&<p className={styles.notice}>No hay registros de tu cuenta para este lote. No se cargaron datos de demostración.</p>}</section>
 <p className={styles.boundary}>Se conserva el motor EPCIS existente. No se cambian tags, claves, TTStatus, propiedad digital ni estados de los envíos. Máximo de admisión: dos confirmaciones de documento por minuto y empresa.</p>
 </main>;
}
