"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Upload,FileCheck2,Printer,Download,CheckCircle2,ShieldCheck,History,RefreshCw,AlertTriangle,Files} from 'lucide-react';
import type {BatchChannels} from '../lib/batch-channels';
import {parseLabelCsv,localLabelRows,rowLabels,boundedProductionJson,parseImportResult,parseLabelPack,productionMessages,type ImportRow,type ImportPlan,type ImportReceipt,type RowResult} from '../lib/label-production';
import styles from './label-production-workspace.module.css';
function saveFile(data:string,type:string,name:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function LabelProductionWorkspace({initial,bid,tenant}:{initial:BatchChannels|null;bid:string;tenant:string}){
 const [text,setText]=useState('gtin,lot,serial\n'),[rows,setRows]=useState<ImportRow[]>([]),[fileName,setFileName]=useState(''),[plan,setPlan]=useState<ImportPlan|null>(null),[receipt,setReceipt]=useState<ImportReceipt|null>(null),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(''),[copies,setCopies]=useState('12');
 const [busy,setBusy]=useState(''),[message,setMessage]=useState(''),[uncertain,setUncertain]=useState(false),[tab,setTab]=useState<'work'|'history'>('work'),[history,setHistory]=useState<any[]|null>(null),[pack,setPack]=useState<ReturnType<typeof parseLabelPack>|null>(null),[qrImage,setQrImage]=useState<string|null>(null);
 const alive=useRef(true),inflight=useRef(false),controller=useRef<AbortController|null>(null),attempt=useRef<any>(null),qrUrl=useRef<string|null>(null);
 const scope=initial?.scope,gs1=initial?.carrier.mode==='gs1',qr=initial?.carrier.mode==='qr',base=`/api/admin/batches/${encodeURIComponent(bid)}/production/`,query=new URLSearchParams(tenant?{tenant}:{}),local=localLabelRows(rows),shown:RowResult[]=receipt?.rows||plan?.rows||local;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();if(qrUrl.current)URL.revokeObjectURL(qrUrl.current);};},[]);
 function clearPack(){if(qrUrl.current)URL.revokeObjectURL(qrUrl.current);qrUrl.current=null;setQrImage(null);setPack(null);}
 function reset(){setRows([]);setPlan(null);setReceipt(null);setConfirmed(false);setMessage('');clearPack();}
 function prepare(csv=text,name='Contenido pegado'){
  if(inflight.current||uncertain)return;reset();
  try{const next=parseLabelCsv(csv);setRows(next);setText(csv);setFileName(name);setMessage('Archivo preparado localmente. Todavía no se registraron identidades.');}
  catch(error){setMessage((error as Error).message);}
 }
 async function choose(file?:File){if(!file||inflight.current||uncertain)return;if(file.size>65536){setMessage('Máximo 64 KiB y 100 identidades por archivo.');return;}try{prepare(await file.text(),file.name);}catch{setMessage('No se pudo leer el archivo.');}}
 async function request(action:string,payload?:unknown,operationId?:string){
  const params=new URLSearchParams(query);if(operationId)params.set('operationId',operationId);
  const response=await fetch(base+action+'?'+params,{method:action==='history'?'GET':'POST',body:action==='history'?undefined:JSON.stringify(payload),headers:action==='history'?undefined:{'content-type':'application/json'},cache:'no-store',signal:controller.current!.signal});
  const body=await boundedProductionJson(response);
  if(!response.ok){if(action==='commit'&&response.status<500&&![408,429].includes(response.status)){attempt.current=null;setUncertain(false);setPlan(null);setConfirmed(false);}throw Error(productionMessages[body.reason]||`No se confirmó la operación (${response.status}).`);}
  return body;
 }
 async function run(action:'preview'|'commit'|'print'|'history'|'receipt',operationId?:string){
  if(inflight.current||!scope)return;
  if(action==='preview'&&(!rows.length||uncertain||local.some(r=>r.state!=='ready')))return;
  if(action==='commit'&&!attempt.current&&(!plan?.canCommit||!confirmed||!initial?.canRegister||reason.trim().length<3))return;
  const selected=receipt?.rows.map(r=>r.identityId!).filter(Boolean)||[];
  const selection=gs1?{identityIds:selected}:{copies:Number(copies)};
  if(action==='print'&&(gs1&&!selected.length||qr&&(!Number.isInteger(selection.copies)||Number(selection.copies)<1||Number(selection.copies)>100)))return;
  if(action==='commit'&&!attempt.current)attempt.current={operationId:crypto.randomUUID(),rows,expectedPlanDigest:plan!.planDigest,reason:reason.trim()};
  inflight.current=true;setBusy(action);setMessage('');if(['preview','commit','print','receipt'].includes(action))clearPack();const abort=new AbortController();controller.current=abort;const timer=setTimeout(()=>abort.abort(),20000);
  try{
   if(action==='preview'){
    setReceipt(null);setPlan(null);const raw=await request('preview',{rows});const next=parseImportResult(raw,scope,rows);if(next.protocol!=='nexid.gs1-import.v1')throw Error('Respuesta de preparación incorrecta.');if(alive.current){setPlan(next);setConfirmed(false);setMessage(next.canCommit?'Preparación confirmada. Revisá las filas y autorizá el registro.':'Hay bloqueos. No se modificó ninguna identidad.');}
   }else if(action==='commit'){
    const pending=attempt.current,raw=await request('commit',pending),next=parseImportResult(raw,scope,pending.rows);
    if(next.protocol!=='nexid.gs1-import-receipt.v1'||next.operationId!==pending.operationId||next.planDigest!==pending.expectedPlanDigest)throw Error('Resultado incierto: el comprobante no coincide con el intento.');
    if(alive.current){setReceipt(next);setUncertain(false);attempt.current=null;setConfirmed(false);setMessage(next.replayed?'El intento anterior quedó confirmado, sin duplicar identidades.':`${next.counts.new} identidades registradas y ${next.counts.existing} existentes conservadas. Ya podés preparar la impresión.`);setHistory(null);}
   }else if(action==='print'){
    const next=parseLabelPack(await request('print',selection),scope,selection);
    const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(next.html)))].map(v=>v.toString(16).padStart(2,'0')).join('');if(digest!==next.htmlSha256)throw Error('No coincide la integridad del archivo de impresión.');
    if(alive.current){setPack(next);qrUrl.current=URL.createObjectURL(new Blob([next.previewSvg],{type:'image/svg+xml'}));setQrImage(qrUrl.current);setMessage('Paquete preparado con el estado actual del registro. No se activaron etiquetas ni se aprobó la impresión física.');}
   }else{
    const id=action==='receipt'?operationId:undefined,raw=await request('history',undefined,id);
    if(raw.protocol!=='nexid.gs1-import-history.v1'||raw.source!=='database'||raw.scope?.batchId!==scope.batchId||raw.scope?.tenant!==scope.tenant||raw.scope?.bid!==scope.bid||!Array.isArray(raw.receipts)||raw.receipts.length>10)throw Error('El historial no corresponde al lote.');
    if(action==='receipt'){
     if(raw.receipts.length!==1)throw Error('No se encontró un comprobante único.');const next=parseImportResult(raw.receipts[0],scope);if(next.protocol!=='nexid.gs1-import-receipt.v1'||next.operationId!==id)throw Error('Comprobante no confirmado.');
     if(attempt.current&&next.operationId!==attempt.current.operationId)throw Error('Primero reconciliá el intento pendiente.');
     if(alive.current){setReceipt(next);setPlan(null);setRows(next.rows.map(({gtin,lot,serial})=>({gtin,lot,serial})));setTab('work');setUncertain(false);attempt.current=null;setMessage('Comprobante recuperado del servidor. La impresión vuelve a comprobar vigencia y permisos.');}
    }else if(alive.current){setHistory(raw.receipts);setTab('history');}
   }
  }catch(error){if(alive.current){if(action==='commit'&&attempt.current)setUncertain(true);setMessage(error instanceof Error?error.message:'No se confirmó la operación.');}}
  finally{clearTimeout(timer);inflight.current=false;controller.current=null;if(alive.current)setBusy('');}
 }
 return <main className={styles.root} data-testid="label-production-workspace">
  <div className={styles.top}><Link prefetch={false} href={`/batches/${encodeURIComponent(bid)}/channels?${query}`}><ArrowLeft size={16} aria-hidden="true"/>Volver a enlaces y etiquetas</Link>{gs1&&<button type="button" disabled={Boolean(busy)} onClick={()=>void run('history')}><History size={16} aria-hidden="true"/>Importaciones guardadas</button>}</div>
  <header className={styles.hero}><div><p className={styles.eyebrow}>DEL ARCHIVO A LA ETIQUETA</p><h1>Producción QR / GS1</h1><p>{initial?.product||'Configuración del lote'} · {scope?.tenant||tenant} · {bid}</p></div><div className={styles.heroIcon}><Printer size={30} aria-hidden="true"/></div></header>
  {!initial?<div className={styles.notice}>No se pudo confirmar la configuración. Volvé al expediente y reintentá; no se presume que el lote esté habilitado.</div>:!gs1&&!qr?<section className={styles.card}><ShieldCheck size={26} aria-hidden="true"/><h2>Este lote conserva su tecnología NFC.</h2><p>Su URL dinámica y el precinto no se convierten en códigos estáticos. Prepará un lote con el perfil QR o GS1 correspondiente desde el pedido de fábrica.</p><Link className={styles.button} prefetch={false} href={`/batches/${encodeURIComponent(bid)}/channels?${query}`}>Ver configuración NFC existente</Link></section>:<>
   <div className={styles.steps}><div data-active={!plan&&!receipt}><span>01</span><strong>{qr?'Cantidad de copias':'Preparar archivo'}</strong><p>{qr?'Un enlace de lote, sin series ficticias':'Hasta 100 identidades · validación local'}</p></div><div data-active={Boolean(plan)&&!receipt}><span>02</span><strong>{qr?'Comprobar canal':'Registrar con control'}</strong><p>{qr?'Estado actual de empresa y lote':'Todo el archivo o ninguna fila nueva'}</p></div><div data-active={Boolean(receipt)||Boolean(pack)}><span>03</span><strong>Imprimir con evidencia</strong><p>Plancha, datos y manifiesto verificables</p></div></div>
   <p role="status" className={styles.status}>{message||'La preparación no modifica el producto, los tags ni sus claves.'}</p>
   {uncertain&&<div className={styles.uncertain}><AlertTriangle size={20} aria-hidden="true"/><div><strong>Resultado pendiente de reconciliación</strong><p>Conservamos el mismo intento. No lo reemplaces por un archivo distinto.</p><button type="button" disabled={Boolean(busy)} onClick={()=>void run('commit')}>Reintentar el mismo intento</button><button type="button" disabled={Boolean(busy)} onClick={()=>void run('receipt',attempt.current?.operationId)}>Consultar comprobante</button></div></div>}
   {tab==='history'?<section className={styles.card}><div className={styles.sectionTitle}><h2>Últimas importaciones</h2><button type="button" onClick={()=>setTab('work')}>Volver al trabajo</button></div><p>Hasta diez comprobantes persistidos de este lote. Recuperarlos no registra nuevas identidades.</p>{history===null?<p>No se pudo confirmar el historial.</p>:history.length?history.map(h=><article className={styles.historyRow} key={h.operationId}><div><strong>{h.counts?.new??'—'} nuevas · {h.counts?.existing??'—'} conservadas</strong><p>{String(h.recordedAt)}</p></div><button type="button" disabled={Boolean(busy)||uncertain} onClick={()=>void run('receipt',h.operationId)}>Abrir comprobante</button></article>):<p>No hay importaciones registradas en esta consulta.</p>}</section>:<div className={styles.layout}>
    <section className={styles.card}>
     <div className={styles.sectionTitle}><div><p className={styles.eyebrow}>{qr?'QR DE LOTE':'IDENTIDADES GS1 DIGITAL LINK'}</p><h2>{qr?'Preparar copias para impresión':'Cargar y revisar identidades'}</h2></div><FileCheck2 size={24} aria-hidden="true"/></div>
     {gs1?<><div className={styles.upload} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void choose(e.dataTransfer.files[0]);}}><Upload size={24} aria-hidden="true"/><strong>Elegí un CSV o arrastralo aquí</strong><span>Cabecera: gtin,lot,serial · 64 KiB máximo</span><label className={styles.button}>Seleccionar archivo<input type="file" accept=".csv,text/csv" disabled={Boolean(busy)||uncertain} onChange={e=>{void choose(e.target.files?.[0]);e.target.value='';}} className={styles.fileInput}/></label><button type="button" className={styles.textButton} onClick={()=>saveFile('gtin,lot,serial\r\n','text/csv;charset=utf-8','nexid-identidades-plantilla.csv')}>Descargar plantilla vacía</button></div>
      <details className={styles.paste}><summary>Pegar o editar CSV</summary><label>Contenido del archivo<textarea spellCheck={false} value={text} disabled={Boolean(busy)||uncertain} onChange={e=>{setText(e.target.value);reset();}} rows={5}/></label><button type="button" disabled={Boolean(busy)||uncertain} onClick={()=>prepare()}>Preparar contenido</button></details>
      <p className={styles.note}>GTIN de 14 dígitos como texto, conservando ceros iniciales. Lote y serie son opcionales; no se inventan ni se autorizan prefijos desde aquí.</p>
      {shown.length>0&&<><div className={styles.fileSummary}><Files size={17} aria-hidden="true"/><strong>{receipt?'Comprobante guardado':fileName||'Archivo preparado'}</strong><span>{shown.length} filas</span></div><div className={styles.tableWrap} tabIndex={0} role="region" aria-label="Validación por fila"><table><thead><tr><th>Fila</th><th>Identidad</th><th>Resultado</th></tr></thead><tbody>{shown.map(r=><tr key={r.row}><td>{r.row}</td><td><strong>{r.gtin}</strong><span>{r.lot||'Sin lote GS1'} · {r.serial||'Sin serie'}</span></td><td><span className={styles.rowStatus} data-ok={['ready','created','already_registered'].includes(r.state)}>{rowLabels[r.state]}</span></td></tr>)}</tbody></table></div></>}
      {!receipt&&<button type="button" className={styles.primary} disabled={Boolean(busy)||uncertain||!rows.length||local.some(r=>r.state!=='ready')} onClick={()=>void run('preview')}>{busy==='preview'?'Validando…':'Validar con el registro'}<ArrowRight size={16} aria-hidden="true"/></button>}
      {plan&&!receipt&&<div className={styles.confirmBox}><h3>{plan.counts.new} nuevas · {plan.counts.existing} existentes · {plan.counts.blocked} bloqueadas</h3>{!plan.channelReady&&<p>La empresa, el lote y la política GS1 deben estar activos. No se habilitan automáticamente.</p>}{plan.canCommit&&<><label>Referencia de preparación<input value={reason} disabled={Boolean(busy)||uncertain||!initial.canRegister} maxLength={1000} placeholder="Pedido o referencia interna" onChange={e=>{setReason(e.target.value);setConfirmed(false);}}/></label><label className={styles.check}><input type="checkbox" checked={confirmed} disabled={Boolean(busy)||uncertain||!initial.canRegister} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo registrar este archivo en la empresa y el lote indicados. No modifica ni activa chips NFC.</label><button type="button" className={styles.primary} disabled={Boolean(busy)||uncertain||!confirmed||reason.trim().length<3||!initial.canRegister} onClick={()=>void run('commit')}>{busy==='commit'?'Registrando…':'Confirmar importación'}</button>{!initial.canRegister&&<p>Tu cuenta puede consultar; para registrar necesita permiso de configuración.</p>}</>}</div>}
      {receipt&&<div className={styles.success}><CheckCircle2 size={20} aria-hidden="true"/><div><strong>Registro confirmado</strong><p>{receipt.counts.new} creadas · {receipt.counts.existing} conservadas. Referencia: {receipt.operationId}</p><button type="button" onClick={()=>saveFile(JSON.stringify(receipt,null,2),'application/json','nexid-comprobante-importacion.json')}>Descargar comprobante</button></div></div>}
     </>:<><p className={styles.notice}>Todas las copias contendrán el mismo QR del lote. No se crearán identidades únicas por unidad.</p><label className={styles.quantity}>Copias para la plancha<input type="number" min={1} max={100} value={copies} disabled={Boolean(busy)} onChange={e=>{setCopies(e.target.value);clearPack();}}/></label></>}
    </section>
    <aside className={styles.card}><Printer size={25} aria-hidden="true"/><h2>Salida para imprenta</h2><p>El servidor vuelve a comprobar el canal y las identidades antes de generar la plancha. No se usa una URL ingresada manualmente.</p><button type="button" className={styles.primary} disabled={Boolean(busy)||uncertain||!initial.publicReady||(gs1&&!receipt)||(qr&&(!Number.isInteger(Number(copies))||Number(copies)<1||Number(copies)>100))} onClick={()=>void run('print')}>{busy==='print'?'Preparando…':'Preparar plancha de etiquetas'}<Printer size={16} aria-hidden="true"/></button>
     {pack&&qrImage?<div className={styles.output}><img src={qrImage} width={230} height={230} alt="Vista previa de la primera etiqueta del paquete"/><strong>{pack.manifest.labels.length} etiquetas preparadas</strong><p>{pack.manifest.sameDestination?'Mismo QR de lote en todas las copias':'Una identidad GS1 por cada fila confirmada'}</p><button type="button" onClick={()=>saveFile(pack.html,'text/html;charset=utf-8','nexid-etiquetas.html')}><Download size={16} aria-hidden="true"/>Descargar plancha HTML</button><button type="button" onClick={()=>saveFile(pack.csv,'text/csv;charset=utf-8','nexid-etiquetas.csv')}>Descargar datos CSV</button><button type="button" onClick={()=>saveFile(JSON.stringify(pack.manifest,null,2),'application/json','nexid-etiquetas-manifiesto.json')}>Descargar manifiesto JSON</button><details><summary>Integridad del archivo</summary><code>{pack.htmlSha256}</code></details></div>:<div className={styles.outputEmpty}><Printer size={38} aria-hidden="true"/><p>{gs1?'El paquete se habilita después de confirmar o recuperar la importación.':'Elegí la cantidad y prepará el paquete del lote.'}</p></div>}
     <div className={styles.notice}><strong>Antes de fabricar</strong><p>Imprimí una muestra al 100% y comprobá lectura, tamaño y soporte real. La plancha no aprueba QA, no mide devoluciones y no verifica autenticidad NFC.</p></div>
    </aside>
   </div>}
  </>}
 </main>;
}
