"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, ListChecks, PackagePlus, ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { SecureDeliveryOpsConsole } from "./secure-delivery-ops-console";
import { logisticsStatus, type LogisticsOverview } from "../lib/logistics-workspace-model";
import styles from "./logistics-workspace.module.css";
export function LogisticsWorkspace({overview,tenant,canWrite,canSupplier,role}:{overview:LogisticsOverview;tenant:string;canWrite:boolean;canSupplier:boolean;role:string}){
  const [search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[panel,setPanel]=useState<"shipments"|"operations">("shipments");
  const router=useRouter();const [refreshing,setRefreshing]=useState(false);
  const rows=useMemo(()=>overview.rows.filter(row=>(filter==="all"||(filter==="attention"?["DELIVERED_OPENED","QUARANTINED"].includes(row.status):row.status===filter))&&[row.code,row.origin,row.destination,row.tenant].join(" ").toLowerCase().includes(search.trim().toLowerCase())),[overview.rows,filter,search]);
  const updated=overview.observedAt?new Intl.DateTimeFormat("es-AR",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"}).format(new Date(overview.observedAt))+" UTC":"No confirmado";
  const stats=overview.stats;
  return <main className={styles.root} data-testid="logistics-workspace" data-logistics-source={overview.ready?"production":"unavailable"}>
    <div className={styles.hero}><div><p className={styles.eyebrow}>Logística · registros y evidencia</p><h1>Envíos bajo control.</h1><p>Registrá el envío, vinculá el precinto y documentá su recepción. Cada operación confirmada conserva un comprobante; no se declara un paquete intacto por falta de información.</p></div><Link href="/" prefetch={false} className={styles.button}><ArrowLeft size={14} aria-hidden="true"/>Centro en Vivo</Link></div>
    <div className={styles.actions} role="group" aria-label="Vista de logística"><button type="button" className={styles.button} aria-pressed={panel==="shipments"} onClick={()=>setPanel("shipments")}><ListChecks size={16} aria-hidden="true"/>Envíos registrados</button><button type="button" className={styles.button} aria-pressed={panel==="operations"} onClick={()=>setPanel("operations")}><PackagePlus size={16} aria-hidden="true"/>Registrar operación</button><button type="button" className={styles.button} disabled={refreshing} onClick={()=>{setRefreshing(true);router.refresh();setTimeout(()=>setRefreshing(false),2500);}}>Actualizar consulta</button></div>
    <p className={styles.muted}>Empresa: {tenant||"Alcance global autorizado"} · Consultado: {updated} · sin actualización automática</p>
    <div className={styles.metrics}>{[["Envíos registrados",stats?.total],["En tránsito declarado",stats?.in_transit],["Recepción cerrada reportada",stats?.delivered],["Requieren revisión",stats?.alerts]].map(([label,value])=><div className={styles.metric} key={String(label)}><span>{label}</span><strong>{typeof value==="number"?value.toLocaleString("es-AR"):"—"}</strong></div>)}</div>
    {!overview.ready&&<p className={styles.notice} role="status">La API no entregó una fuente coherente para este alcance. No se muestran ceros como si fueran inventario confirmado ni se habilitan operaciones a ciegas.</p>}
    <p className={styles.notice}><ShieldCheck size={17} aria-hidden="true"/><span>Estos registros documentan declaraciones operativas. No prueban contenido, custodia física ni ubicación continua. El mapa de TAP permanece en su centro geográfico.</span></p>
    <section hidden={panel!=="shipments"} className={styles.card} aria-label="Registros de envíos"><div className={styles.sectionHead}><div><h2>Últimos envíos</h2><p className={styles.muted}>Hasta 100 registros recientes. El resumen superior corresponde al alcance completo de la consulta.</p></div><span className={styles.badge}>{rows.length} en la vista</span></div>
      <div className={styles.toolbar}><label className={`${styles.field} ${styles.search}`}>Buscar en los envíos<input value={search} maxLength={120} onChange={event=>setSearch(event.target.value)} placeholder="Referencia, origen o destino"/></label><label className={styles.field}>Estado<select value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">Todos</option><option value="draft">Borradores</option><option value="SEALED">Precintado declarado</option><option value="IN_TRANSIT">En tránsito declarado</option><option value="DELIVERED_CLOSED">Recibidos · cerrado reportado</option><option value="attention">Requieren revisión</option></select></label></div>
      <div className={styles.tableWrap}><table className={styles.table}><caption>Fuente administrativa · cantidades sin multiplicación por eventos o precintos asociados</caption><thead><tr><th scope="col">Envío</th><th scope="col">Estado informado</th><th scope="col">Contenido declarado</th><th scope="col">Evidencia registrada</th><th scope="col">Detalle</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.code}</strong><small>{row.origin||"Origen sin informar"} → {row.destination||"Destino sin informar"}</small>{!tenant&&<small>Empresa: {row.tenant}</small>}</td><td>{logisticsStatus(row.status)}</td><td>{row.units} unidades<small>{row.items} partidas</small></td><td>{row.seals} precintos<small>{row.events} eventos declarados</small></td><td><Link href={`/logistics/shipments/${row.id}`} prefetch={false}>Abrir expediente <ArrowUpRight size={13} aria-hidden="true" style={{display:"inline"}}/></Link></td></tr>)}</tbody></table></div>
      {!rows.length&&<p className={styles.notice}>{overview.ready?overview.rows.length?"No hay coincidencias en esta muestra.":"La fuente confirmó que no hay envíos en este alcance.":"Registros no disponibles."}</p>}
      <div className={styles.actions} style={{marginTop:16}}><Link prefetch={false} href="/logistics/shipments" className={styles.button}>Abrir listado completo</Link>{canSupplier&&<Link prefetch={false} href="/batches/supplier#supplier-order-console" className={styles.button}>Pedidos de etiquetas</Link>}</div>
    </section>
    <div hidden={panel!=="operations"}><SecureDeliveryOpsConsole tenantSlug={tenant||null} role={role} canWrite={canWrite&&overview.ready&&overview.protocolReady} shipments={overview.rows}/></div>
    <details className={styles.process} data-logistics-visual="non-geographic-process"><summary>Cómo se registra el proceso · no es un mapa geográfico</summary><ol>{[["01 · Registro","El envío y sus partidas se guardan juntos."],["02 · Asignación","Se comprueba empresa y vínculo antes de cambiar el precinto."],["03 · Traspaso","Se registra la declaración del operador sin inventar una posición."],["04 · Recepción","Precinto, evento, recepción y eventual revisión se guardan en una transacción."]].map(([title,text])=><li key={title}><strong>{title}</strong><span>{text}</span></li>)}</ol><p>Repetir el mismo intento identificado devuelve el comprobante original. Una operación nueva o un cliente que no envía identificador de idempotencia no recibe esa protección entre solicitudes.</p></details>
  </main>;
}
