"use client";
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {ArrowLeft,RefreshCw,FilePenLine,ShieldCheck,FileCheck2,History,ArrowRight,Download,X,ShieldAlert} from 'lucide-react';
import {parseNoticeBoard,noticeReceipt,readRecallJson,sourceChanged,noticeReport,PROPOSAL_LABELS,NOTICE_FIELDS,type NoticeBoard,type NoticeProposal,type NoticeText} from '../lib/notice-review-workspace';
import styles from './notice-review-workspace.module.css';
type Editor={kind:'correction'|'lift';notice:NoticeText;resolutionMessage:string;reason:string;evidenceReference:string};
const date=(v:string)=>new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v));
const labels:Record<string,string>={create_correction:'Guardar propuesta',create_lift:'Guardar solicitud',save_correction:'Guardar cambios',save_lift:'Guardar cambios',submit:'Enviar a revisión',return_for_changes:'Devolver con observaciones',approve:'Aprobar y aplicar',cancel:'Cancelar propuesta'};
const errors:Record<string,string>={notice_review_source_changed:'El expediente o el aviso cambió. Tus campos se conservan, pero esta propuesta ya no puede aprobarse. Cancelala y prepará una revisión sobre la información actual.',notice_review_revision_conflict:'Otra persona guardó una revisión. Conservamos tus campos; consultá el estado antes de continuar.',notice_review_pending_exists:'Ya existe una propuesta pendiente para este caso. Actualizá para continuar esa revisión.',notice_review_independent_approval_required:'Debe revisar otra persona que no haya creado, editado ni presentado esta propuesta.',notice_review_close_tracking_first:'Primero hay que cerrar el seguimiento con sus acuses, cantidades y revisión independiente.',notice_review_no_public_change:'No hay diferencias respecto del aviso vigente.',notice_review_approval_forbidden:'Esta aprobación requiere permiso vigente y MFA verificado.',notice_review_already_lifted:'El aviso ya tiene una resolución de levantamiento. No se reactivó ni se borró su historial.'};
export function NoticeReviewWorkspace({initial,bid,tenant,caseId}:{initial:NoticeBoard|null;bid:string;tenant:string;caseId:string}){
 const [board,setBoard]=useState(initial),[selected,setSelected]=useState<NoticeProposal|null>(()=>initial?.proposals.find(p=>['draft','in_review','changes_requested'].includes(p.state))||null),[editor,setEditor]=useState<Editor|null>(null),[tab,setTab]=useState<'edit'|'compare'|'history'>('edit'),[busy,setBusy]=useState(false),[message,setMessage]=useState(initial?'':'No se confirmó el aviso de este expediente.'),[uncertain,setUncertain]=useState(false),[creating,setCreating]=useState(false),[dialog,setDialog]=useState<string|null>(null),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState('');
 const alive=useRef(true),flight=useRef(false),abort=useRef<AbortController|null>(null),pending=useRef<{action:string;body:any}|null>(null),newId=useRef('');
 function fromProposal(p:NoticeProposal):Editor{return {kind:p.kind,notice:structuredClone(p.requestedNotice||p.baseNotice),resolutionMessage:p.resolutionMessage||'',reason:p.reason,evidenceReference:p.evidenceReference};}
 const base=`/api/admin/batches/${encodeURIComponent(bid)}/notice-reviews/${caseId}`,params=new URLSearchParams({tenant});
 const baseline=selected?fromProposal(selected):null;const dirty=!!editor&&(creating||JSON.stringify(editor)!==JSON.stringify(baseline));
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;abort.current?.abort();};},[]);
 useEffect(()=>{if(selected&&!editor)setEditor(fromProposal(selected));},[selected]);
 useEffect(()=>{if(!dirty&&!uncertain)return;const fn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty,uncertain]);
 function mayDiscard(){return !(dirty||uncertain)||window.confirm(uncertain?'El último intento aún no está confirmado. Consultar descartará el comando local; no revierte lo guardado. ¿Continuar?':'Se perderán los campos sin guardar. ¿Continuar?');}
 async function fetchBoard(){const c=new AbortController();abort.current=c;const timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(base+'?'+params,{cache:'no-store',signal:c.signal});const d=await readRecallJson(r);if(!r.ok)throw Error(errors[d.reason]||'No se pudo consultar el aviso. No se presume que fue retirado.');return parseNoticeBoard(d,bid,tenant,caseId);}finally{clearTimeout(timer);}}
 function acceptBoard(b:NoticeBoard,id?:string){setBoard(b);const p=b.proposals.find(p=>p.id===id)||b.proposals.find(p=>['draft','in_review','changes_requested'].includes(p.state))||null;setSelected(p);setEditor(p?fromProposal(p):null);setCreating(false);}
 async function refresh(){if(flight.current||!mayDiscard())return;flight.current=true;setBusy(true);try{const b=await fetchBoard();if(alive.current){acceptBoard(b,selected?.id);pending.current=null;setUncertain(false);setMessage('Aviso y expediente consultados desde la fuente.');}}catch(e){if(alive.current)setMessage((e as Error).message);}finally{flight.current=false;if(alive.current)setBusy(false);}}
 function start(kind:Editor['kind']){if(!board||!board.actor.canWrite||busy||uncertain||!mayDiscard())return;newId.current=crypto.randomUUID();setSelected(null);setCreating(true);setEditor({kind,notice:structuredClone(board.current.notice),resolutionMessage:'',reason:'',evidenceReference:''});setTab('edit');setMessage('Propuesta local. El aviso vigente no cambia al escribir.');}
 function select(p:NoticeProposal){if(busy||!mayDiscard())return;setSelected(p);setEditor(fromProposal(p));setCreating(false);setTab(['applied','cancelled'].includes(p.state)?'compare':'edit');pending.current=null;setUncertain(false);}
 async function execute(action:string,retry=false){
  if(flight.current||!board)return;let body:any;
  if(retry)body=pending.current?.body;else {body={operationId:crypto.randomUUID(),caseId,proposalId:creating?newId.current:selected?.id,expectedReviewVersion:creating?0:selected?.version,expectedCaseVersion:board.current.caseVersion,expectedNoticeVersion:board.current.noticeVersion};if(action.startsWith('create_')||action.startsWith('save_')){body.reason=editor?.reason;body.evidenceReference=editor?.evidenceReference;if(editor?.kind==='correction')body.notice=editor.notice;else body.resolutionMessage=editor?.resolutionMessage;}if(['return_for_changes','cancel'].includes(action))body.reason=reason;}
  if(!body)return;pending.current={action,body};flight.current=true;setBusy(true);setDialog(null);setMessage('');let committed=false;const c=new AbortController();abort.current=c;const timer=setTimeout(()=>c.abort(),20000);
  try{const r=await fetch(base+'/'+action+'?'+params,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:c.signal});const raw=await readRecallJson(r);if(!r.ok){if(r.status<500&&![408,429].includes(r.status)){pending.current=null;setUncertain(false);}throw Error(errors[raw.reason]||`No se confirmó la operación (${r.status}). ${raw.reason||''}`);}
   const result=noticeReceipt(raw,body,action,board.scope);committed=true;pending.current=null;if(!alive.current)return;setSelected(result.proposal);setEditor(fromProposal(result.proposal));setCreating(false);setUncertain(false);setMessage(raw.receipt.replayed?'El intento anterior quedó confirmado sin duplicar cambios.':action==='approve'?'Cambio aprobado y aplicado con comprobante.':'Propuesta guardada con comprobante.');
   try{const b=await fetchBoard();if(alive.current)acceptBoard(b,result.proposal.id);}catch{if(alive.current)setMessage('La operación fue confirmada. Falta actualizar la vista para consultar el aviso vigente.');}
  }catch(e){if(alive.current){if(!committed&&pending.current)setUncertain(true);setMessage((e as Error).message);}}finally{clearTimeout(timer);flight.current=false;if(alive.current)setBusy(false);}
 }
 function ask(action:string){setReason('');setConfirmed(false);setDialog(action);}
 async function download(){if(flight.current||!board?.actor.canExport)return;flight.current=true;setBusy(true);const c=new AbortController();abort.current=c;const timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(base+'?'+params+'&export=1',{cache:'no-store',signal:c.signal});if(!r.ok)throw Error('No se autorizó la descarga.');const b=parseNoticeBoard(await readRecallJson(r),bid,tenant,caseId);const url=URL.createObjectURL(new Blob([noticeReport(b)],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='nexid-aviso-y-revisiones.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Informe descargado con el aviso y las revisiones consultadas.');}catch(e){setMessage((e as Error).message);}finally{clearTimeout(timer);flight.current=false;if(alive.current)setBusy(false);}}
 const pendingProposal=board?.proposals.find(p=>['draft','in_review','changes_requested'].includes(p.state));
 const stale=!!board&&!!selected&&!['applied','cancelled'].includes(selected.state)&&sourceChanged(board,selected);
 const editable=board?.actor.canWrite&&!busy&&!uncertain&&!stale&&(creating||selected?.state==='draft'||selected?.state==='changes_requested');
 const canApprove=board?.actor.canPublish&&board.actor.mfaVerified&&selected?.state==='in_review'&&!selected.contributorIds.includes(board.actor.id)&&!stale&&!dirty;
 return <main className={styles.root} data-testid="notice-review-workspace"><div className={styles.top}><Link prefetch={false} href={`/batches/${encodeURIComponent(bid)}/recalls?${params}`} onClick={e=>{if(!mayDiscard())e.preventDefault();}}><ArrowLeft size={16} aria-hidden="true"/>Volver al seguimiento</Link><button type="button" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={15} aria-hidden="true"/>Actualizar aviso</button></div>
 <header className={styles.hero}><div><p className={styles.eyebrow}>SEGURIDAD DEL PRODUCTO · CONTROL DE CAMBIOS</p><h1>Revisar el aviso publicado</h1><p>{board?.product||bid} · {board?.tenantName||tenant}</p></div><ShieldCheck size={36} aria-hidden="true"/></header>
 <p role="status" className={styles.status}>{message||'El aviso anterior permanece vigente hasta aprobar y confirmar el cambio.'}</p>{uncertain&&<div className={styles.warning}><strong>Resultado pendiente de confirmar.</strong><p>Conservamos la misma operación; no prepares otra para repetir este cambio.</p><button type="button" disabled={busy} onClick={()=>{if(pending.current)void execute(pending.current.action,true);}}>Reconciliar el mismo intento</button></div>}
 {board&&<><section className={styles.current} aria-label="Aviso vigente"><div className={styles.sectionHead}><div><span className={styles.badge}>{board.current.noticeState==='lifted'?'LEVANTADO CON RESOLUCIÓN':'AVISO VIGENTE'}</span><h2>{board.current.notice.title}</h2></div><small>Aviso v{board.current.noticeVersion} · expediente r{board.current.caseVersion}<br/>{date(board.effectiveAt)}</small></div><p>{board.current.notice.publicMessage}</p>{board.resolutionMessage&&<div className={styles.resolution}><strong>Resolución publicada</strong><p>{board.resolutionMessage}</p></div>}<p className={styles.boundary}>El estado de este aviso es independiente de la autenticidad NFC. Su levantamiento no libera stock ni autoriza el uso del producto.</p></section>
 <div className={styles.toolbar}>{board.actor.canWrite&&board.current.noticeState==='active'&&!pendingProposal&&<><button type="button" className={styles.primary} disabled={busy||uncertain||creating} onClick={()=>start('correction')}><FilePenLine size={16} aria-hidden="true"/>Rectificar aviso</button><button type="button" disabled={busy||uncertain||creating||board.current.trackingState!=='closed'} onClick={()=>start('lift')}>Solicitar levantamiento</button></>}{board.current.trackingState!=='closed'&&board.current.noticeState==='active'&&<span>El levantamiento requiere el seguimiento cerrado.</span>}{board.actor.canExport&&<button type="button" disabled={busy} onClick={()=>void download()}><Download size={16} aria-hidden="true"/>Descargar evidencia</button>}</div>
 <div className={styles.layout}><aside className={styles.sidebar}><h2>Revisiones del aviso</h2>{board.proposals.map(p=><button type="button" key={p.id} aria-pressed={selected?.id===p.id} disabled={busy} onClick={()=>select(p)}><strong>{p.kind==='correction'?'Rectificación':'Levantamiento'}</strong><span>{PROPOSAL_LABELS[p.state]} · r{p.version}</span><small>{date(p.updatedAt)}</small></button>)}{!board.proposals.length&&<p>Sin propuestas registradas. El aviso publicado se conserva.</p>}{board.hasMore&&<p>Últimas 20 propuestas.</p>}</aside>
 <section className={styles.workspace}>{!editor?<div className={styles.empty}><FileCheck2 size={36} aria-hidden="true"/><h2>{board.current.noticeState==='lifted'?'Resolución conservada en el historial':'Un cambio, una revisión verificable'}</h2><p>Rectificá el texto sin reescribir el retiro, sus destinatarios, unidades o comprobantes.</p></div>:<>
 <div className={styles.sectionHead}><div><p className={styles.eyebrow}>{editor.kind==='correction'?'RECTIFICACIÓN':'LEVANTAMIENTO DEL AVISO'}</p><h2>{creating?'Nueva propuesta':PROPOSAL_LABELS[selected!.state]}</h2></div><span className={styles.badge}>{creating?'Local · sin guardar':'r'+selected?.version}</span></div>
 <div className={styles.tabs} role="group" aria-label="Vistas de la propuesta">{[['edit','Propuesta'],['compare','Antes y después'],['history','Historial']].map(([k,v])=><button type="button" key={k} aria-pressed={tab===k} onClick={()=>setTab(k as typeof tab)}>{v}</button>)}</div>
 {stale&&<p className={styles.warning}>Cambió el expediente o el aviso base. No se puede aplicar esta revisión. Conservá el texto, cancelá la propuesta y prepará otra sobre la fuente actual.</p>}
 {tab==='edit'&&<form className={styles.form} onSubmit={e=>{e.preventDefault();ask((creating?'create_':'save_')+editor.kind);}}>
 {editor.kind==='correction'?Object.entries(NOTICE_FIELDS).map(([key,label])=><label key={key}>{label}{key==='title'||key==='contact'?<input required minLength={key==='title'?5:3} maxLength={key==='title'?160:200} value={editor.notice[key]} disabled={!editable} onChange={e=>setEditor({...editor,notice:{...editor.notice,[key]:e.target.value}})}/>:<textarea required minLength={10} maxLength={key==='instructions'?1000:600} rows={3} value={editor.notice[key as keyof NoticeText]} disabled={!editable} onChange={e=>setEditor({...editor,notice:{...editor.notice,[key]:e.target.value}})}/>}</label>):<label>Mensaje público de resolución<textarea required minLength={10} maxLength={1000} rows={4} disabled={!editable} value={editor.resolutionMessage} onChange={e=>setEditor({...editor,resolutionMessage:e.target.value})}/><small>Se mostrará con el aviso anterior; no como un certificado de producto apto.</small></label>}
 <div className={styles.private}><h3>Respaldo interno · no aparece en el pasaporte</h3><label>Justificación del cambio<textarea required minLength={10} maxLength={1000} rows={3} value={editor.reason} disabled={!editable} onChange={e=>setEditor({...editor,reason:e.target.value})}/></label><label>Referencia de evidencia<input required minLength={5} maxLength={400} value={editor.evidenceReference} disabled={!editable} onChange={e=>setEditor({...editor,evidenceReference:e.target.value})} placeholder="Resolución, acta o expediente"/></label></div>
 {(creating||['draft','changes_requested'].includes(selected?.state||''))&&<div className={styles.actions}><button type="submit" className={styles.primary} disabled={!editable||!dirty}>Guardar propuesta</button>{selected&&<button type="button" disabled={busy||uncertain||dirty||stale||!board.actor.canWrite} onClick={()=>ask('submit')}>Enviar a revisión <ArrowRight size={15} aria-hidden="true"/></button>}</div>}
 </form>}
 {tab==='compare'&&<div className={styles.comparison}>{Object.entries(NOTICE_FIELDS).map(([key,label])=>{const before=selected?.baseNotice||board.current.notice,after=editor.notice;return <article key={key} data-changed={editor.kind==='correction'&&before[key as keyof NoticeText]!==after[key as keyof NoticeText]}><h3>{label}</h3><div><section><small>VERSIÓN BASE</small><p>{before[key as keyof NoticeText]}</p></section><section><small>{editor.kind==='lift'?'SE CONSERVA COMO ANTECEDENTE':'PROPUESTA'}</small><p>{after[key as keyof NoticeText]}</p></section></div></article>;})}{editor.kind==='lift'&&<div className={styles.resolution}><strong>Resolución propuesta</strong><p>{editor.resolutionMessage||'Completar el mensaje antes de solicitar revisión.'}</p></div>}</div>}
 {tab==='history'&&<div className={styles.history}>{board.history.filter(h=>!selected||h.proposal_id===selected.id).map(h=><article key={h.id}><History size={17} aria-hidden="true"/><div><strong>{labels[h.action]||h.action} · r{h.version}</strong><p>{h.actor_label} · {date(h.created_at)}</p>{h.reason&&<p>{h.reason}</p>}{h.evidence_reference&&<small>{h.evidence_reference}</small>}</div></article>)}<p>{board.historyTruncated?'Últimos 100 movimientos.':'Movimientos disponibles en la consulta.'}</p></div>}
 {selected?.state==='in_review'&&<div className={styles.review}><ShieldAlert size={20} aria-hidden="true"/><div><h3>Revisión independiente</h3><p>{canApprove?'Revisá el contenido y sus referencias antes de aplicarlo al pasaporte.':'La aprobación requiere otra cuenta autorizada, no participante en la propuesta, con MFA.'}</p><div className={styles.actions}><button type="button" className={styles.primary} disabled={!canApprove||busy||uncertain} onClick={()=>ask('approve')}>{editor.kind==='lift'?'Aprobar levantamiento':'Aprobar rectificación'}</button><button type="button" disabled={!canApprove||busy||uncertain} onClick={()=>ask('return_for_changes')}>Devolver con observaciones</button></div></div></div>}
 {selected&&['draft','in_review','changes_requested'].includes(selected.state)&&board.actor.canWrite&&<button className={styles.textButton} type="button" disabled={busy||uncertain} onClick={()=>ask('cancel')}>Cancelar propuesta sin cambiar el aviso</button>}
 </>}</section></div></>}
 {dialog&&<NoticeDialog title={dialog==='approve'?(editor?.kind==='lift'?'Confirmar levantamiento del aviso':'Confirmar rectificación pública'):labels[dialog]} onCancel={()=>setDialog(null)}><p>{dialog==='approve'?'Se aplicará al pasaporte la versión revisada. No cambia stock, etiquetas, contadores ni precintos.':'Se registrará esta operación con tu identidad. El aviso vigente se conserva hasta una aprobación confirmada.'}</p>{['return_for_changes','cancel'].includes(dialog)&&<label>Motivo de la decisión<textarea rows={3} minLength={10} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>}<label className={styles.check}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo la acción y sus referencias.</label><div className={styles.actions}><button type="button" onClick={()=>setDialog(null)}>Volver</button><button type="button" className={styles.primary} disabled={!confirmed||busy||(['return_for_changes','cancel'].includes(dialog)&&reason.trim().length<10)} onClick={()=>void execute(dialog)}>Confirmar cambio</button></div></NoticeDialog>}
 </main>;
}
function NoticeDialog({title,children,onCancel}:{title:string;children:React.ReactNode;onCancel:()=>void}){const ref=useRef<HTMLDialogElement>(null),previous=useRef<HTMLElement|null>(null);useEffect(()=>{previous.current=document.activeElement as HTMLElement;ref.current?.showModal();return()=>previous.current?.focus();},[]);return <dialog ref={ref} className={styles.dialog} aria-labelledby="notice-dialog-title" onCancel={e=>{e.preventDefault();onCancel();}}><div className={styles.sectionHead}><h2 id="notice-dialog-title">{title}</h2><button type="button" aria-label="Cerrar confirmación" onClick={onCancel}><X size={18} aria-hidden="true"/></button></div>{children}</dialog>;}
