"use client";
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {BarChart3,Download,FileCheck2,FileJson,RefreshCw,CalendarDays,ShieldCheck} from 'lucide-react';
import {boundedDossierJson} from '../lib/batch-dossier-readings';
import {parsePilotEnvelope,parsePilotOptions,evidenceMetrics,metricValue,pilotCsv,pilotHtml,type PilotEnvelope} from '../lib/pilot-report';
import styles from './pilot-report.module.css';
type Options=ReturnType<typeof parsePilotOptions>;
const reasons:Record<string,string>={pilot_range_exceeds_limit:'El período supera el volumen seguro de esta consulta. Acortá las fechas o elegí un lote; no se exporta una muestra como si fuera el total.',pilot_future_window:'La fecha final no puede estar en el futuro.',pilot_window_1_to_93_days:'Elegí entre 1 y 93 días consecutivos.',pilot_date_invalid:'Revisá las fechas del informe.',pilot_source_unavailable:'No se pudo confirmar la fuente. No se muestran ceros ni resultados anteriores como si fueran nuevos.',pilot_tenant_required:'Seleccioná una empresa.',pilot_batch_not_found:'El lote no pertenece a la empresa seleccionada o ya no está disponible.',pilot_tenant_forbidden:'Tu cuenta no tiene alcance sobre esa empresa.'};
function download(content:string,name:string,type:string){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
export function PilotReportWorkspace({initial,tenantBound,initialTenant,fromDefault,toDefault,authorized}:{initial:Options|null;tenantBound:boolean;initialTenant:string;fromDefault:string;toDefault:string;authorized:boolean}){
 const [options,setOptions]=useState(initial),[tenant,setTenant]=useState(initialTenant),[bid,setBid]=useState(''),[from,setFrom]=useState(fromDefault),[to,setTo]=useState(toDefault),[busy,setBusy]=useState(false),[report,setReport]=useState<PilotEnvelope|null>(null),[message,setMessage]=useState(!authorized?'Tu rol necesita lectura de analítica y exportación de informes. No se cambian permisos al abrir esta pantalla.':initial?'':'No se pudo consultar la lista de empresas. Reintentá la conexión.');
 const controller=useRef<AbortController|null>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[]);
 const changed=()=>{setReport(null);setMessage('Filtros actualizados. Generá el informe para consultar datos de este alcance.');};
 async function load(kind:'options'|'report',selected=tenant){if(controller.current||!authorized)return;setBusy(true);setMessage('');setReport(null);if(kind==='options'){setBid('');setOptions(prev=>prev?{...prev,batchOptions:[]}:null);}const abort=new AbortController();controller.current=abort;const timer=setTimeout(()=>abort.abort(),15000);
 try{const expected={tenant:selected,bid,from,to};const query=new URLSearchParams(kind==='report'?expected:selected?{tenant:selected}:{});
 const res=await fetch('/api/admin/pilot-report'+(kind==='options'?'/options':'')+'?'+query,{cache:'no-store',signal:abort.signal});
 if(res.headers.get('x-nexid-data-mode')==='demo')throw new Error('No se exportan datos de demostración como un piloto real.');
 const result=await boundedDossierJson(res) as any;if(!res.ok)throw new Error(reasons[result.reason]||(res.status===403?'Tu cuenta no tiene permiso para este informe.':res.status===401?'La sesión venció. Volvé a ingresar.':'No se confirmó el informe. Reintentá la consulta.'));
 if(kind==='report'){const confirmed=await parsePilotEnvelope(result,expected);if(alive.current){setReport(confirmed);setMessage('Informe generado desde una instantánea de la base. Las descargas usan exactamente estos datos, sin nuevas consultas.');}}
 else{const confirmed=parsePilotOptions(result,selected,tenantBound);if(alive.current)setOptions(confirmed);}
 }catch(e){if(alive.current)setMessage(e instanceof Error?e.message:'No se confirmó la consulta.');}finally{clearTimeout(timer);controller.current=null;if(alive.current)setBusy(false);}}
 const r=report?.report,metrics=r?evidenceMetrics(r):[],byId=(id:string)=>metrics.find(m=>m.id===id)!;
 const filename=r?'nexid-piloto-'+r.scope.tenantSlug+'-'+r.window.from+'-'+r.window.to:'';
 function exportFile(type:'html'|'csv'|'json'){if(!report)return;if(type==='html')download(pilotHtml(report),filename+'.html','text/html;charset=utf-8');else if(type==='csv')download(pilotCsv(report),filename+'.csv','text/csv;charset=utf-8');else download(JSON.stringify(report,null,2),filename+'.json','application/json');}
 return <main className={styles.root} data-testid="pilot-report-workspace"><div className={styles.top}><Link prefetch={false} href={'/analytics'+(tenant?'?tenant='+encodeURIComponent(tenant):'')}>← Analítica</Link><span>S6 · evidencia del piloto</span></div>
 <header className={styles.hero}><div><p className={styles.kicker}>DATOS PARA DECIDIR · NO ESCENARIOS ILUSTRATIVOS</p><h1>Informe del piloto.</h1><p>Qué se verificó, qué pasó con las incidencias y qué uso quedó registrado. Un mismo corte de datos para revisar y compartir.</p></div><FileCheck2 size={36} aria-hidden="true"/></header>
 <form className={styles.filters} onSubmit={e=>{e.preventDefault();void load('report');}}><label>Empresa<select aria-label="Empresa" value={tenant} disabled={busy||tenantBound||!authorized} onChange={e=>{setTenant(e.target.value);changed();void load('options',e.target.value);}}><option value="">Elegí una empresa</option>{options?.tenantOptions.map(t=><option key={t.id} value={t.slug}>{t.name}</option>)}{initialTenant&&!options?.tenantOptions.some(t=>t.slug===initialTenant)&&<option value={initialTenant}>{initialTenant}</option>}</select></label>
 <label>Lote<select aria-label="Lote" value={bid} disabled={busy||!tenant||!authorized} onChange={e=>{setBid(e.target.value);changed();}}><option value="">Todos los lotes</option>{options?.batchOptions.map(b=><option value={b.bid} key={b.id}>{b.product||b.bid} · {b.bid}</option>)}</select></label>
 <label>Desde · UTC<input aria-label="Desde · UTC" type="date" value={from} max={to} required disabled={busy||!authorized} onChange={e=>{setFrom(e.target.value);changed();}}/></label><label>Hasta · UTC<input aria-label="Hasta · UTC" type="date" value={to} min={from} max={toDefault} required disabled={busy||!authorized} onChange={e=>{setTo(e.target.value);changed();}}/></label><button type="submit" className={styles.primary} disabled={busy||!tenant||!authorized}><BarChart3 size={17} aria-hidden="true"/>{busy?'Consultando…':'Generar informe'}</button></form>
 <div className={styles.context}><span><CalendarDays size={14} aria-hidden="true"/>1–93 días · fechas inclusivas UTC · actualización bajo demanda</span><button type="button" disabled={busy||!authorized} onClick={()=>void load('options')}><RefreshCw size={14} aria-hidden="true"/>Actualizar empresas y lotes</button></div><p role="status" className={styles.status}>{message}</p>
 {!r?<section className={styles.empty}><ShieldCheck size={27} aria-hidden="true"/><h2>Elegí el alcance y generá la evidencia.</h2><p>No se carga el histórico al abrir la pantalla. El informe agrega resultados, sin exponer UIDs, ubicaciones, personas ni claves.</p><p>Inventario actual, datos del período y métricas sin base quedan separados.</p></section>:<section className={styles.report} data-testid="pilot-report-result"><div className={styles.summaryHead}><div><p className={styles.kicker}>{r.scope.tenantName}</p><h2>{r.scope.bid||'Todos los lotes de la empresa'}</h2><p>{r.window.from} → {r.window.to} · UTC · captura {r.generatedAt}</p></div><div className={styles.exports}><button onClick={()=>exportFile('html')} type="button"><Download size={16} aria-hidden="true"/>Informe para compartir</button><button onClick={()=>exportFile('csv')} type="button">CSV de indicadores</button><button onClick={()=>exportFile('json')} type="button"><FileJson size={15} aria-hidden="true"/>JSON con integridad</button></div></div>
 <div className={styles.kpis}>{['verified','verified_ratio','units','active'].map(id=>{const m=byId(id);return <article key={id}><span>{m.label}</span><strong>{metricValue(m)}</strong><small>{m.denominator!==null?`${m.numerator} de ${m.denominator} intentos NFC`:m.id==='active'?'Inventario al generar, no altas del período':m.id==='units'?'Etiquetas distintas con vínculo comprobado, no personas':'Mensajes que cumplen la política criptográfica'}</small></article>;})}</div>
 <div className={styles.two}><section className={styles.card}><h3>Lecturas y visitas del período</h3><p>{r.interactions.events} eventos reales persistidos · {r.interactions.identityViews} visitas de identidad sin autenticación · {r.interactions.nfcUnconfirmed} intentos NFC no confirmados</p><div className={styles.chart} role="img" aria-label={'Eventos diarios UTC: '+r.daily.map(d=>`${d.day}: ${d.verified} NFC verificados, ${d.identity_views} identidad sin autenticación, ${d.events} total`).join('; ')}>{r.daily.map(d=><div className={styles.day} key={d.day} title={`${d.day}: ${d.events} eventos, ${d.verified} verificados`}><span style={{height:d.events/Math.max(1,...r.daily.map(v=>v.events))*115}}><i style={{height:(d.events?d.verified/d.events*100:0)+'%'}}/></span></div>)}</div><div className={styles.legend}><span>{r.window.from}</span><span>NFC verificado / resto de eventos</span><span>{r.window.to}</span></div><details><summary>Ver valores diarios</summary><table><thead><tr><th>Fecha UTC</th><th>Eventos</th><th>NFC verificados</th><th>Identidad sin autenticar</th></tr></thead><tbody>{r.daily.map(d=><tr key={d.day}><td>{d.day}</td><td>{d.events}</td><td>{d.verified}</td><td>{d.identity_views}</td></tr>)}</tbody></table></details></section>
 <section className={styles.card}><h3>Incidentes: de la detección al cierre</h3><p>Creados en el período, con su estado actual al generar. Descartar no equivale a solucionar.</p><div className={styles.caseCounts}>{[['Creados',r.incidents.created],['Resueltos',r.incidents.resolved],['En atención',r.incidents.pending],['Descartados',r.incidents.dismissed]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className={styles.note}>Mediana hasta resolución: <b>{metricValue(byId('median'))}</b> · base: {r.incidents.timedResolved} casos resueltos con fechas consistentes.</div><p className={styles.small}>No es el estado histórico al último día. Las resoluciones posteriores también pueden aparecer al generar este informe.</p></section></div>
 <section className={styles.card}><h3>Indicadores con fuente y denominador</h3><div className={styles.tableScroll} tabIndex={0} role="region" aria-label="Tabla de indicadores"><table><thead><tr><th>Indicador</th><th>Valor</th><th>Base</th><th>Fuente / alcance</th></tr></thead><tbody>{metrics.map(m=><tr key={m.id}><td><strong>{m.label}</strong><small>{m.note}</small></td><td className={styles.value}>{metricValue(m)}</td><td>{m.numerator??'—'} / {m.denominator??'—'}</td><td>{m.source}<small>{m.basis}</small></td></tr>)}</tbody></table></div></section>
 <section className={styles.card}><h3>Qué incluye y qué no demuestra</h3><p><b>{r.exclusions.candidates} eventos candidatos</b>; excluidos: {r.exclusions.nonReal} con fuente distinta de real, {r.exclusions.automated} accesos automatizados detectados y {r.exclusions.unbound} sin vínculo al lote autorizado.</p><p>Datos del período hasta <b>{r.window.effectiveEnd}</b>. El día de hoy puede estar incompleto. {r.interactions.verifiedLinked} de {r.interactions.verifiedNfc} lecturas verificadas tienen vínculo a una etiqueta registrada del mismo lote.</p><p>Sin base en este informe: disponibilidad antes de guardar en la base, altas históricas de etiquetas, ventas/ROI, audiencia con consentimiento, uso efectivo de documentos, factura del proveedor y circuito de retiro completo.</p><p className={styles.note}>Compartir descarga un HTML autónomo, sin rastreadores ni recursos externos, listo para abrir e imprimir. CSV y JSON provienen de esta misma instantánea; no vuelven a consultar Neon.</p><details><summary>Identificación e integridad</summary><p className={styles.small}>Informe {r.reportId} · {r.schemaVersion}</p><code>{report!.integrity.digest}</code><p className={styles.small}>SHA-256 del objeto JSON report. Detecta cambios respecto a este archivo; no es firma digital ni certificación.</p></details></section></section>}
 </main>;
}
