"use client";
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {ClipboardCheck,RefreshCw,ArrowUpRight,Check,Download,ShieldAlert,X,FileCheck2} from 'lucide-react';
import {boundedDossierJson} from '../lib/batch-dossier-readings';
import {parseAssignedBoard,parseAssignedDetail,assignedTaskCommand,assignedReceipt,assignedTaskReport,taskLink,type AssignedTaskBoard,type AssignedTaskDetail,type AssignedTask,type TaskExpected} from '../lib/recall-assigned-tasks';
import styles from './recall-assigned-workspace.module.css';
const fmt=(v:string|null)=>v?new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'Sin registrar';
const stateLabel=(t:AssignedTask)=>t.state==='closed'?'Seguimiento cerrado':t.state==='closing'?'Cierre en revisión':!t.acknowledgedAt?'Tu acuse está pendiente':t.returnedUnits+t.heldUnits===t.assignedUnits?'Cantidades conciliadas':'Cantidades por informar';
const key=(t:{caseId:string;destinationId:string})=>t.caseId+'/'+t.destinationId;
function problem(code:string,status:number){const known:Record<string,string>={recall_task_not_found:'No hay una tarea accesible con ese enlace para tu cuenta. No se muestran datos ajenos.',recall_revision_conflict:'El expediente cambió. Conservamos tus campos: actualizá la tarea y revisá los datos antes de confirmar.',recall_task_notice_changed:'Cambió el aviso. Leé la versión actual antes de responder.',recall_acknowledgement_exists:'Ya hay un acuse registrado. Actualizá para consultarlo.',recall_units_invalid:'La suma de devueltas e inmovilizadas no puede superar las unidades asignadas.',recall_task_respond_forbidden:'Tu cuenta no tiene autorización para responder esta tarea.',recall_acknowledgement_required:'Primero debe quedar registrado el acuse.',recall_transition_invalid:'La gestión ya no admite esa acción en su estado actual.'};return known[code]||`No se confirmó la operación (${status}). No se asume que faltan tareas ni se guarda una acción nueva.`;}
export function AssignedRecallWorkspace({initial,initialDetail=null,expected,initialSelection,canOpenBatches,demo}:{initial:AssignedTaskBoard|null;initialDetail?:AssignedTaskDetail|null;expected:TaskExpected;initialSelection:{caseId:string;destinationId:string}|null;canOpenBatches:boolean;demo:boolean}){
 const [showList,setShowList]=useState(!initialDetail);
 const [board,setBoard]=useState(initial),[detail,setDetail]=useState(initialDetail),[includeClosed,setIncludeClosed]=useState(false),[filter,setFilter]=useState(''),[tab,setTab]=useState<'action'|'history'>('action');
 const [busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[stale,setStale]=useState(false),[message,setMessage]=useState(!initial?'No se confirmó la lista. Reintentá la consulta.':initialSelection&&!initialDetail?'El enlace no tiene una tarea confirmada para tu cuenta. Consultá la lista asignada.':'');
 const [reason,setReason]=useState(''),[reference,setReference]=useState(''),[returned,setReturned]=useState(String(initialDetail?.task.returnedUnits||0)),[held,setHeld]=useState(String(initialDetail?.task.heldUnits||0)),[modal,setModal]=useState<'acknowledge'|'account'|null>(null),[confirmed,setConfirmed]=useState(false);
 const inFlight=useRef(false),alive=useRef(true),abort=useRef<AbortController|null>(null),pending=useRef<{action:'acknowledge'|'account';body:any}|null>(null);
 const current=detail?.task,dirty=Boolean(reason||reference||(current&&(returned!==String(current.returnedUnits)||held!==String(current.heldUnits))));
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;abort.current?.abort();};},[]);
 useEffect(()=>{if(!dirty&&!uncertain)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,uncertain]);
 function replace(d:AssignedTaskDetail,reset=true){setDetail(d);setShowList(false);setStale(false);setBoard(b=>b?{...b,tasks:b.tasks.map(t=>key(t)===key(d.task)?d.task:t)}:b);if(reset){setReason('');setReference('');setReturned(String(d.task.returnedUnits));setHeld(String(d.task.heldUnits));}}
 async function read(which?:{caseId:string;destinationId:string}){
  if(inFlight.current||demo)return;
  if(uncertain){setMessage('Primero reconciliá el intento pendiente con el mismo identificador. No iniciamos otro ni descartamos su resultado.');return;}
  if(dirty&&!window.confirm('Hay campos sin guardar. ¿Descartarlos y consultar la versión actual?'))return;
  inFlight.current=true;setBusy(true);setMessage('');setStale(true);const c=new AbortController();abort.current=c;const timer=setTimeout(()=>c.abort(),15000);
  try{const url='/api/admin/recall-tasks'+(which?'/'+key(which):'?includeClosed='+(includeClosed?'1':'0'));const r=await fetch(url,{cache:'no-store',signal:c.signal});const raw=await boundedDossierJson(r) as any;if(!r.ok)throw Error(problem(raw.reason,r.status));if(!alive.current)return;
   if(which){replace(parseAssignedDetail(raw,expected,which.caseId,which.destinationId));window.history.replaceState(null,'',taskLink(which));requestAnimationFrame(()=>{if(window.matchMedia('(max-width:820px)').matches)document.getElementById('assigned-task-panel')?.scrollIntoView({block:'start'});});}else{setBoard(parseAssignedBoard(raw,expected));setDetail(null);setShowList(true);setReason('');setReference('');setStale(false);}
   if(!which)window.history.replaceState(null,'','/tasks/recalls');setTab('action');setMessage('Consulta confirmada. Ninguna acción se registró al abrir la tarea.');
  }catch(e){if(alive.current){if(!which){setBoard(null);setDetail(null);}setMessage((e as Error).message);}}
  finally{clearTimeout(timer);inFlight.current=false;if(alive.current)setBusy(false);}
 }
 function prepare(action:'acknowledge'|'account'){if(!current||busy||stale||uncertain)return;try{assignedTaskCommand(current,action,{reason,reference,returned,held});}catch(e){setMessage((e as Error).message);return;}setConfirmed(false);setModal(action);}
 async function submit(action:'acknowledge'|'account',retry=false){
  if(inFlight.current||!current||demo)return;let body;
  try{body=retry?pending.current?.body:assignedTaskCommand(current,action,{reason,reference,returned,held});if(!body)return;}catch(e){setMessage((e as Error).message);return;}
  pending.current={action,body};inFlight.current=true;setBusy(true);setModal(null);setMessage('');const c=new AbortController();abort.current=c;const timer=setTimeout(()=>c.abort(),18000);
  try{const r=await fetch('/api/admin/recall-tasks/'+body.caseId+'/'+body.destinationId+'/'+action,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:c.signal});const raw=await boundedDossierJson(r) as any;
   if(!r.ok){if(r.status<500&&r.status!==408&&r.status!==429){pending.current=null;setUncertain(false);setStale(true);}throw Error(problem(raw.reason,r.status));}
   const result=assignedReceipt(raw,body,action,expected);if(!alive.current)return;
   pending.current=null;setUncertain(false);replace(result.detail);setMessage(result.replayed?'El intento anterior quedó confirmado. No se duplicó el movimiento.':'Guardado con tu cuenta y comprobante. La gestión ya dispone de esta información.');
  }catch(e){if(alive.current){if(pending.current)setUncertain(true);setMessage((e as Error).message);}}
  finally{clearTimeout(timer);inFlight.current=false;if(alive.current)setBusy(false);}
 }
 function download(){if(!detail||uncertain||busy||stale)return;const url=URL.createObjectURL(new Blob([assignedTaskReport(detail)],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nexid-mi-tarea-de-retiro.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const visible=(board?.tasks||[]).filter(t=>`${t.product} ${t.bid} ${t.recipient} ${t.tenantName}`.toLowerCase().includes(filter.trim().toLowerCase()));
 const pendingCount=(board?.tasks||[]).filter(t=>!t.acknowledgedAt&&t.state==='active').length;
 const completedCount=(board?.tasks||[]).filter(t=>t.returnedUnits+t.heldUnits===t.assignedUnits).length;
 const total=current?current.assignedUnits-current.returnedUnits-current.heldUnits:0;
 return <main className={styles.root} data-testid="assigned-recall-workspace" data-active-task={Boolean(current)} data-show-list={showList}>
  <header className={styles.hero}><div><p className={styles.kicker}>OPERACIÓN · RESPONSABILIDADES ASIGNADAS</p><h1>Mis tareas de retiro</h1><p>Recibí el aviso, informá tus cantidades y conservá el comprobante. Sólo se muestran los destinos asignados a tu cuenta.</p></div><span className={styles.heroIcon}><ClipboardCheck size={30} aria-hidden="true"/></span></header>
  <div className={styles.toolbar}>{current&&<button className={styles.mobileTaskSwitch} type="button" onClick={()=>setShowList(v=>!v)}>{showList?'Volver a la tarea abierta':'Ver mis otras tareas'}</button>}<span className={styles.identity}>{board?.actor.label||detail?.actor.label||'Cuenta autenticada'}</span><label className={styles.checkbox}><input type="checkbox" checked={includeClosed} disabled={busy||uncertain} onChange={e=>setIncludeClosed(e.target.checked)}/>Incluir seguimiento cerrado</label><button type="button" disabled={busy||demo} onClick={()=>void read()}><RefreshCw size={15} aria-hidden="true"/>Consultar tareas</button>{canOpenBatches&&<Link prefetch={false} href="/batches">Ir a la gestión de lotes <ArrowUpRight size={15} aria-hidden="true"/></Link>}</div>
  <p role="status" className={styles.status}>{message||`Fuente: base operativa · ${fmt(board?.observedAt||null)} · sin notificaciones ni consultas automáticas.`}</p>
  {uncertain&&<div className={styles.warning}><strong>El resultado está pendiente de confirmar.</strong><p>Conservamos el intento original. No cambies de cuenta ni inicies otra carga para repetirlo.</p><button type="button" disabled={busy} onClick={()=>{if(pending.current)void submit(pending.current.action,true);}}>Reconciliar el mismo intento</button></div>}
  <div className={styles.metrics}>{[['Tareas en esta consulta',board?.tasks.length],['Acuses por responder',board?pendingCount:null],['Destinos con cantidades conciliadas',board?completedCount:null]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value??'—'}</strong></div>)}</div>
  <div className={styles.layout}><aside className={styles.inbox}><label className={styles.search}>Buscar entre mis tareas<input type="search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Producto, lote o destino"/></label><p className={styles.caption}>Hasta 50 destinos recientes. No es una lista de todos los retiros de la empresa.</p>
   {visible.map(t=><button className={styles.task} key={key(t)} type="button" disabled={busy||uncertain} aria-pressed={current&&key(current)===key(t)} onClick={()=>{if(current&&key(t)===key(current)){setShowList(false);return;}void read(t);}}><span className={styles.taskState}>{stateLabel(t)}</span><strong>{t.product||t.bid}</strong><span>{t.recipient}</span><small>{t.tenantName} · {t.bid}</small><span className={styles.taskCounts}>{t.returnedUnits+t.heldUnits} / {t.assignedUnits} {t.unitLabel} conciliadas</span></button>)}
   {board&&!visible.length&&<p className={styles.emptyText}>{filter?'No coinciden tareas en esta consulta.':'No hay tareas asignadas en esta consulta. La empresa debe publicar el caso con tu cuenta como responsable; no creamos tareas de ejemplo.'}</p>}{!board&&<p className={styles.emptyText}>No se confirmó la fuente. Consultá nuevamente; no se interpreta como cero tareas.</p>}{board?.hasMore&&<p className={styles.caption}>Hay más tareas fuera de este listado acotado.</p>}
  </aside><section className={styles.workspace} id="assigned-task-panel">
   {!detail?<div className={styles.empty}><FileCheck2 size={38} aria-hidden="true"/><h2>Una tarea. Una respuesta trazable.</h2><p>Elegí tu destino de seguimiento. Podés confirmar que recibiste el aviso y declarar las unidades devueltas o inmovilizadas. Publicar, cerrar o levantar el retiro sigue a cargo de la empresa.</p><p className={styles.caption}>Se requiere una cuenta de la empresa con permiso de tarea. Un enlace no da acceso ni sustituye la asignación.</p></div>:<>
    <div className={styles.taskHeading}><div><p className={styles.kicker}>{current!.tenantName} · {current!.bid}</p><h2>{current!.recipient}</h2><span className={styles.badge}>{stateLabel(current!)}</span></div><button type="button" disabled={busy||uncertain} onClick={()=>void read(current!)}><RefreshCw size={15} aria-hidden="true"/>Actualizar tarea</button></div>
    <div className={styles.tabs} role="group" aria-label="Vistas de mi tarea"><button type="button" aria-pressed={tab==='action'} onClick={()=>setTab('action')}>Aviso y respuesta</button><button type="button" aria-pressed={tab==='history'} onClick={()=>setTab('history')}>Comprobantes e historial</button></div>
    {stale&&<p className={styles.warning}>El contexto no está confirmado para un nuevo guardado. Actualizá la tarea antes de continuar.</p>}
    <div hidden={tab!=='action'}>
     <div className={styles.notice} data-lifted={current!.notice.state==='lifted'}><div className={styles.noticeTitle}><ShieldAlert size={20} aria-hidden="true"/><strong>{current!.notice.state==='lifted'?'Aviso levantado con resolución':current!.kind==='recall'?'Aviso de retiro vigente':'Aviso de cuarentena vigente'}</strong><small>v{current!.notice.version}</small></div><h3>{current!.notice.title}</h3>{current!.notice.resolution&&<p>{current!.notice.resolution}</p>}<p>{current!.notice.message}</p><h4>Qué tenés que hacer</h4><p>{current!.notice.instructions}</p><p className={styles.contact}>{current!.notice.contact}</p></div>
     <div className={styles.quantities}><div><span>Asignadas a tu destino</span><strong>{current!.assignedUnits}</strong></div><div><span>Devueltas</span><strong>{current!.returnedUnits}</strong></div><div><span>Inmovilizadas</span><strong>{current!.heldUnits}</strong></div><div><span>Pendientes</span><strong>{total}</strong></div></div>
     <div className={styles.progress} role="progressbar" aria-label="Unidades declaradas como conciliadas" aria-valuemin={0} aria-valuemax={current!.assignedUnits} aria-valuenow={current!.returnedUnits+current!.heldUnits}><span style={{width:`${100*(current!.returnedUnits+current!.heldUnits)/current!.assignedUnits}%`}}/></div><p className={styles.caption}>{current!.unitLabel} · cantidades declaradas, no verificadas por el NFC.</p>
     <div className={styles.response}><div className={styles.stepLabel}><span>{current!.acknowledgedAt?'02':'01'}</span><h3>{current!.acknowledgedAt?'Informá los totales acumulados':'Confirmá que recibiste el aviso'}</h3></div>
      {current!.acknowledgedAt&&<p className={styles.ack}><Check size={17} aria-hidden="true"/>Acuse registrado el {fmt(current!.acknowledgedAt)}{current!.acknowledgedBySelf?' por tu cuenta.':' por gestión. El historial identifica quién lo cargó.'}</p>}
      {current!.state!=='active'?<p className={styles.caption}>Esta tarea está en consulta porque el seguimiento está {current!.state==='closed'?'cerrado':'en revisión de cierre'}. No se libera producto ni se cambian las etiquetas.</p>:!detail.actor.canRespond?<p className={styles.warning}>Tu cuenta tiene consulta, no respuesta. El administrador debe revisar el permiso recall_tasks:respond; la asignación no lo concede por sí sola.</p>:<form onSubmit={e=>{e.preventDefault();prepare(current!.canAcknowledge?'acknowledge':'account');}}>
       {current!.canAccount&&<div className={styles.formRow}><label>Devueltas acumuladas<input type="number" min={0} max={current!.assignedUnits} step={1} value={returned} disabled={busy||uncertain||stale} onChange={e=>setReturned(e.target.value)}/></label><label>Inmovilizadas acumuladas<input type="number" min={0} max={current!.assignedUnits} step={1} value={held} disabled={busy||uncertain||stale} onChange={e=>setHeld(e.target.value)}/></label></div>}
       {current!.canAccount&&<p className={styles.caption}>Ingresá el total hasta hoy, no una cantidad para sumar. Repetir el mismo envío no debe contar unidades dos veces.</p>}
       <label>Motivo o detalle de la respuesta<textarea rows={3} minLength={10} maxLength={1000} required value={reason} disabled={busy||uncertain||stale} onChange={e=>setReason(e.target.value)} placeholder="Confirmo recepción y separación de las unidades indicadas…"/></label><label>Referencia del comprobante<input minLength={5} maxLength={400} required value={reference} disabled={busy||uncertain||stale} onChange={e=>setReference(e.target.value)} placeholder="Acta, remito o referencia interna"/></label>
       <button className={styles.primary} type="submit" disabled={busy||uncertain||stale||(!current!.canAcknowledge&&!current!.canAccount)}><ClipboardCheck size={17} aria-hidden="true"/>{current!.canAcknowledge?'Revisar y confirmar acuse':'Revisar y guardar cantidades'}</button>
      </form>}
     </div>
    </div>
    <div hidden={tab!=='history'} className={styles.evidence}><div className={styles.taskHeading}><div><h3>Lo registrado para tu destino</h3><p className={styles.caption}>Fuente consultada: {fmt(detail.observedAt)}. No incluye otros destinatarios ni el motivo interno del retiro.</p></div><button type="button" disabled={busy||uncertain||stale} onClick={download}><Download size={15} aria-hidden="true"/>Descargar constancia</button></div>{detail.history.map(h=><article className={styles.historyItem} key={h.id}><span className={styles.historyDot}/><div><strong>{h.action==='acknowledge'?'Acuse registrado':'Cantidades actualizadas'}</strong><p>{h.actorLabel} · {fmt(h.at)} · {h.source==='assigned_task'?'Desde cuenta asignada':'Registro de gestión'}</p><p>{h.reason}</p><span className={styles.reference}>{h.reference}</span>{h.action==='account'&&<p>Devueltas: {h.returnedUnits} · inmovilizadas: {h.heldUnits}</p>}</div></article>)}{!detail.history.length&&<p className={styles.caption}>Todavía no hay respuestas registradas para este destino.</p>}{detail.historyTruncated&&<p className={styles.caption}>Se muestran las últimas 50 respuestas, no todo el historial.</p>}</div>
   </>}
  </section></div>
  {modal&&current&&<TaskDialog title={modal==='acknowledge'?'Confirmar recepción del aviso':'Confirmar cantidades acumuladas'} onClose={()=>setModal(null)}><p>Se guardará tu respuesta para <strong>{current.recipient}</strong> con la cuenta <strong>{detail!.actor.label}</strong>, revisión {current.version} y aviso v{current.notice.version}.</p>{modal==='account'&&<p>Devueltas: <strong>{returned}</strong> · inmovilizadas: <strong>{held}</strong> de {current.assignedUnits} {current.unitLabel}. Son totales acumulados.</p>}<p>Comprobante: <strong>{reference}</strong></p><p className={styles.caption}>No publica ni levanta avisos. No modifica stock, precintos o autenticidad. La referencia es aportada por vos; no se verifica automáticamente su documento.</p><label className={styles.checkbox}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo la declaración y su referencia.</label><div className={styles.dialogActions}><button type="button" onClick={()=>setModal(null)}>Volver</button><button type="button" className={styles.primary} disabled={!confirmed||busy} onClick={()=>void submit(modal)}>Confirmar respuesta</button></div></TaskDialog>}
 </main>;
}
function TaskDialog({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null),prior=useRef<HTMLElement|null>(null);useEffect(()=>{prior.current=document.activeElement as HTMLElement;ref.current?.showModal();return()=>prior.current?.focus();},[]);return <dialog ref={ref} className={styles.dialog} aria-labelledby="assigned-task-dialog-title" onCancel={e=>{e.preventDefault();onClose();}}><header><h2 id="assigned-task-dialog-title">{title}</h2><button aria-label="Cerrar confirmación" type="button" onClick={onClose}><X size={18} aria-hidden="true"/></button></header>{children}</dialog>;}
