"use client";
import {useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {ArrowLeft,Plus,ShieldAlert,RefreshCw,Download,CheckCircle2,ClipboardList,Send,FileCheck2,X,Trash2} from 'lucide-react';
import {RECALL_LABELS,parseRecallBoard,parseRecallDetail,recallReceipt,readRecallJson,recallReportHtml,type RecallBoard,type RecallDetail,type RecallDoc,type RecallRecord} from '../lib/recall-workspace';
import styles from './recall-workspace.module.css';
import {taskLink} from '../lib/recall-assigned-tasks';
const actions:Record<string,string>={notice_corrected:'Aviso público rectificado',notice_lifted:'Aviso levantado con resolución',submit:'Enviar a revisión',revise:'Solicitar correcciones',publish:'Publicar aviso del lote',cancel:'Cancelar borrador',acknowledge:'Registrar acuse',account:'Registrar cantidades',request_close:'Solicitar cierre',resume:'Volver al seguimiento',close:'Aprobar cierre'};
function blank(actor:string):RecallDoc{return {kind:'recall',title:'',reason:'',publicMessage:'',instructions:'',contact:'',unitLabel:'unidades',destinations:[{id:crypto.randomUUID(),recipient:'',assigneeId:actor,units:0}]};}
const date=(s:string|null)=>s?new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(s)):'—';
function saveFile(body:string,type:string,name:string){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function RecallWorkspace({initial,bid,tenant}:{initial:RecallBoard|null;bid:string;tenant:string}){
 const [board,setBoard]=useState(initial),[selected,setSelected]=useState<RecallRecord|null>(null),[detail,setDetail]=useState<RecallDetail|null>(null),[document,setDocument]=useState<RecallDoc|null>(null),[creating,setCreating]=useState(false),[tab,setTab]=useState<'document'|'progress'|'evidence'>('document'),[busy,setBusy]=useState(false),[message,setMessage]=useState(initial?'':'No se confirmó la consulta. Reintentá sin modificar el lote.'),[uncertain,setUncertain]=useState(false),[modal,setModal]=useState<{action:string;destinationId?:string}|null>(null),[reason,setReason]=useState(''),[evidence,setEvidence]=useState(''),[returned,setReturned]=useState('0'),[held,setHeld]=useState('0'),[accept,setAccept]=useState(false);
 const pending=useRef<{action:string;body:any}|null>(null),newId=useRef(''),busyRef=useRef(false),alive=useRef(true),active=useRef<AbortController|null>(null);
 const dirty=Boolean(document&&(creating||JSON.stringify(document)!==JSON.stringify(selected?.document)));
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;active.current?.abort();};},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const base=`/api/admin/batches/${encodeURIComponent(bid)}/recalls`,params=new URLSearchParams({tenant});
 async function get(path:string){const controller=new AbortController();active.current=controller;const timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(base+path,{cache:'no-store',signal:controller.signal});const data=await readRecallJson(r);if(!r.ok)throw Error(errorText(data.reason,r.status));return data;}finally{clearTimeout(timer);}}
 function errorText(code:string,status:number){const known:Record<string,string>={recall_pending_actions:'Quedan acuses o cantidades pendientes. No se cerró el seguimiento.',recall_revision_conflict:'Otra persona actualizó el caso. Conservamos tus campos; consultá la revisión actual antes de guardar.',recall_independent_review_required:'Esta aprobación requiere otra persona autorizada, distinta de quien preparó la revisión.',recall_open_case_exists:'Este lote ya tiene un caso abierto. Continuá ese seguimiento.',recall_units_invalid:'Las cantidades deben ser enteras y no superar el objetivo del destino.',recall_assignee_forbidden:'El responsable elegido ya no pertenece al alcance autorizado.',recall_action_forbidden:'Tu sesión no tiene permiso para esta acción. No se modificaron tus permisos.'};return known[code]||`No se confirmó la operación (${status}). ${code||'Fuente no disponible.'}`;}
 function replaceRecord(c:RecallRecord){setSelected(c);setDocument(structuredClone(c.document));setCreating(false);setBoard(b=>b?{...b,cases:[{id:c.id,title:c.document.title,kind:c.document.kind,state:c.state,version:c.version,created_at:c.created_at},...b.cases.filter(i=>i.id!==c.id)]}:b);}
 async function load(id?:string){if(busyRef.current)return;if(dirty&&!window.confirm('Hay campos sin guardar. ¿Descartarlos y consultar el estado guardado?'))return;busyRef.current=true;setBusy(true);setMessage('');try{if(id){const d=parseRecallDetail(await get('/'+id+'?'+params),bid,tenant);if(!alive.current)return;setDetail(d);replaceRecord(d.case);setTab(['active','closing','closed'].includes(d.case.state)?'progress':'document');}else{const b=parseRecallBoard(await get('?'+params),bid,tenant);if(!alive.current)return;setBoard(b);setSelected(null);setDocument(null);setDetail(null);setCreating(false);}setUncertain(false);pending.current=null;}catch(e){if(alive.current)setMessage((e as Error).message);}finally{busyRef.current=false;if(alive.current)setBusy(false);}}
 async function copyAssignedLink(destinationId:string){if(!selected)return;try{await navigator.clipboard.writeText(window.location.origin+taskLink({caseId:selected.id,destinationId}));setMessage('Enlace copiado. Sólo la cuenta asignada y autorizada puede responder. No se envió una notificación.');}catch{setMessage('No se pudo copiar el enlace.');}}
 function start(){if(!board?.actor.canWrite||busy||uncertain)return;if(dirty&&!window.confirm('¿Descartar los campos sin guardar?'))return;newId.current=crypto.randomUUID();setSelected(null);setDetail(null);setDocument(blank(board.actor.id));setCreating(true);setTab('document');setMessage('Borrador local. No existe un aviso público hasta guardar, revisar y publicar.');}
 async function execute(action:string,extra:Record<string,unknown>={},retry=false){
  if(busyRef.current||!board)return;
  const body=retry?pending.current?.body:{operationId:crypto.randomUUID(),caseId:creating?newId.current:selected?.id,expectedVersion:creating?0:selected?.version,...extra};if(!body)return;
  pending.current={action,body};busyRef.current=true;setBusy(true);setModal(null);setMessage('');let committed=false;
  const controller=new AbortController();active.current=controller;const timer=setTimeout(()=>controller.abort(),20000);
  try{const r=await fetch(base+'/'+action+'?'+params,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:controller.signal});const raw=await readRecallJson(r);if(!r.ok){if(r.status<500&&r.status!==408&&r.status!==429){pending.current=null;setUncertain(false);}throw Error(errorText(raw.reason,r.status));}
   const c=recallReceipt(raw,body,bid,tenant);if(!alive.current)return;committed=true;pending.current=null;setUncertain(false);replaceRecord(c);setDetail(null);setTab(['active','closing','closed'].includes(c.state)?'progress':'document');setMessage(raw.receipt.replayed?'El intento anterior quedó confirmado sin duplicar la operación.':'Operación guardada con comprobante.');
   try{const d=parseRecallDetail(await get('/'+c.id+'?'+params),bid,tenant);if(alive.current){setDetail(d);replaceRecord(d.case);}}catch{if(alive.current)setMessage('Operación guardada. No se pudo releer el historial; el comprobante ya confirmó el cambio.');}
  }catch(e){if(alive.current){if(!committed&&pending.current)setUncertain(true);setMessage((e as Error).message);}}finally{clearTimeout(timer);busyRef.current=false;if(alive.current)setBusy(false);}
 }
 function confirm(action:string,destinationId?:string){setReason('');setEvidence('');const progress=destinationId?selected?.progress[destinationId]:null;setReturned(String(progress?.returnedUnits||0));setHeld(String(progress?.heldUnits||0));setAccept(false);setModal({action,destinationId});}
 function submitModal(){if(!modal||!accept)return;const extra:Record<string,unknown>={};if(['revise','cancel','request_close','resume','close','acknowledge','account'].includes(modal.action))extra.reason=reason;if(modal.destinationId){extra.destinationId=modal.destinationId;extra.evidenceReference=evidence;}if(modal.action==='account'){extra.returnedUnits=Number(returned);extra.heldUnits=Number(held);}void execute(modal.action,extra);}
 async function exportReport(){if(!selected||!board?.actor.canExport||busyRef.current)return;busyRef.current=true;setBusy(true);try{const fresh=parseRecallDetail(await get('/'+selected.id+'?'+params+'&export=1'),bid,tenant);saveFile(recallReportHtml(fresh),'text/html;charset=utf-8','nexid-seguimiento-retiro.html');setDetail(fresh);setMessage('Informe descargado desde la revisión consultada, con cantidades declaradas y comprobantes.');}catch(e){setMessage((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
 const editable=board?.actor.canWrite&&(creating||selected?.state==='draft')&&!uncertain&&!busy;
 const canReview=board?.actor.canPublish&&selected&&![selected.created_by,selected.last_editor_id,selected.submitted_by].includes(board.actor.id);
 const canClose=board?.actor.canPublish&&selected?.close_requested_by!==board.actor.id;
 const allDone=selected&&selected.totals.pendingUnits===0&&selected.totals.acknowledgedDestinations===selected.totals.totalDestinations;
 const options=board?[{id:board.actor.id,label:board.actor.label},...board.members.filter(m=>m.id!==board.actor.id)]:[];
 return <main className={styles.root} data-testid="recall-workspace">
  <div className={styles.top}><Link prefetch={false} href={'/batches?'+params}><ArrowLeft size={16} aria-hidden="true"/>Lotes de trabajo</Link><button type="button" onClick={()=>void load(selected?.id)} disabled={busy}><RefreshCw size={15} aria-hidden="true"/>Actualizar estado</button></div>
  <header className={styles.hero}><div><p className={styles.eyebrow}>OPERACIÓN · SEGURIDAD DEL PRODUCTO</p><h1>Retiros y cuarentenas</h1><p>{board?.product||bid} · {board?.tenantName||tenant} · {bid}</p></div>{board?.actor.canWrite&&!board.cases.some(c=>['draft','in_review','active','closing'].includes(c.state))&&<button type="button" className={styles.primary} onClick={start} disabled={busy||uncertain}><Plus size={17} aria-hidden="true"/>Preparar un caso</button>}</header>
  <p role="status" className={styles.status}>{message||'Fuente: base operativa. Sin envíos automáticos ni cambios en autenticidad NFC.'}</p>{uncertain&&<div className={styles.warning}>La respuesta no confirmó el resultado. Conservamos el mismo intento; no vuelvas a crear el caso.<button type="button" disabled={busy} onClick={()=>{if(pending.current)void execute(pending.current.action,{},true);}}>Reconciliar el mismo intento</button></div>}
  <div className={styles.layout}><aside className={styles.sidebar}><h2>Casos del lote</h2>{board?.cases.map(c=><button type="button" key={c.id} aria-pressed={selected?.id===c.id} disabled={busy} onClick={()=>void load(c.id)}><span>{RECALL_LABELS[c.state]}</span><strong>{c.title}</strong><small>r{c.version} · {date(c.created_at)}</small></button>)}{!board?.cases.length&&<p>No hay casos confirmados en esta consulta.</p>}{board?.hasMore&&<p>Se muestran los últimos 30 casos.</p>}<div className={styles.context}><ShieldAlert size={20} aria-hidden="true"/><p>El aviso afecta a todo el lote. No revoca las etiquetas ni transforma un resultado NFC válido en inválido.</p></div></aside>
  <section className={styles.workspace}>
   {!document?<div className={styles.empty}><ClipboardList size={42} aria-hidden="true"/><h2>Del hallazgo al seguimiento documentado</h2><p>Definí el aviso, los destinos y sus responsables. Otra cuenta autorizada revisa lo que se publica; después registrás acuses y cantidades con referencia a sus comprobantes.</p>{board?.actor.canWrite?<button type="button" className={styles.primary} disabled={busy||board.cases.some(c=>['draft','in_review','active','closing'].includes(c.state))} onClick={start}>Preparar un caso</button>:<p>Tu cuenta puede consultar los casos, pero no iniciar ni modificar un retiro.</p>}</div>:<>
   <div className={styles.caseHeading}><div><p className={styles.eyebrow}>{creating?'BORRADOR SIN GUARDAR':RECALL_LABELS[selected!.state]}</p><h2>{document.title||'Nuevo caso del lote'}</h2></div><span className={styles.badge}>{creating?'Local':'Revisión '+selected?.version}</span></div>
   <div className={styles.tabs} role="group" aria-label="Vistas del caso">{[['document','Aviso y alcance'],['progress','Acuses y cantidades'],['evidence','Evidencia e historial']].map(([k,v])=><button type="button" key={k} aria-pressed={tab===k} onClick={()=>setTab(k as typeof tab)} disabled={creating&&k!=='document'}>{v}</button>)}</div>
   {selected?.published_at&&<div className={styles.review}><div><h3>Aviso público y resolución</h3><p>La corrección o el levantamiento se revisan por separado del cierre del seguimiento.</p><Link prefetch={false} className={styles.textButton} href={`/batches/${encodeURIComponent(bid)}/recalls/${selected.id}/notice?${params}`}>Revisar aviso publicado →</Link></div></div>}
   {selected&&<div className={styles.metrics}>{[['Objetivo declarado',selected.totals.declaredUnits],['Devueltas',selected.totals.returnedUnits],['Inmovilizadas',selected.totals.heldUnits],['Pendientes',selected.totals.pendingUnits]].map(([k,v])=><div key={String(k)}><span>{k}</span><strong>{v}</strong><small>{selected.document.unitLabel}</small></div>)}</div>}
   {tab==='document'&&<form onSubmit={e=>{e.preventDefault();void execute(creating?'create':'save',{document});}} className={styles.form}>
    <div className={styles.row}><label>Tipo de medida<select value={document.kind} disabled={!editable} onChange={e=>setDocument({...document,kind:e.target.value as RecallDoc['kind']})}><option value="recall">Retiro del lote</option><option value="quarantine">Aviso de cuarentena</option></select></label><label>Unidad de seguimiento<input required minLength={2} maxLength={40} value={document.unitLabel} disabled={!editable} onChange={e=>setDocument({...document,unitLabel:e.target.value})}/></label></div>
    <label>Título del caso<input required minLength={5} maxLength={160} value={document.title} disabled={!editable} onChange={e=>setDocument({...document,title:e.target.value})}/></label>
    <label>Motivo interno · no aparece en el pasaporte<textarea required minLength={10} maxLength={2000} rows={3} value={document.reason} disabled={!editable} onChange={e=>setDocument({...document,reason:e.target.value})}/></label>
    <section className={styles.publicPreview}><h3>Lo que verá el consumidor después de aprobar</h3><label>Aviso público<textarea required minLength={10} maxLength={600} rows={2} value={document.publicMessage} disabled={!editable} onChange={e=>setDocument({...document,publicMessage:e.target.value})}/></label><label>Instrucciones al consumidor<textarea required minLength={10} maxLength={1000} rows={3} value={document.instructions} disabled={!editable} onChange={e=>setDocument({...document,instructions:e.target.value})}/></label><label>Contacto público del responsable<input required minLength={3} maxLength={200} value={document.contact} disabled={!editable} onChange={e=>setDocument({...document,contact:e.target.value})}/></label></section>
    <div className={styles.sectionHeading}><h3>Destinos de seguimiento</h3>{editable&&<button type="button" disabled={document.destinations.length>=50} onClick={()=>setDocument({...document,destinations:[...document.destinations,{id:crypto.randomUUID(),recipient:'',assigneeId:board!.actor.id,units:0}]})}><Plus size={15} aria-hidden="true"/>Agregar destino</button>}</div>
    <p className={styles.hint}>Cantidades que declara la empresa para este seguimiento; no se completan contando TAP ni etiquetas. El responsable debe registrar evidencia. Agregar un destino no envía mensajes. La cuenta asignada puede responder desde Mis tareas de retiro si tiene recall_tasks:read y recall_tasks:respond, o autoridad de gestión de retiros. Asignarla no concede permisos.</p>
    {document.destinations.map((d,i)=><div key={d.id} className={styles.destinationForm}><label>Destino {i+1}<input required minLength={2} maxLength={160} value={d.recipient} disabled={!editable} onChange={e=>setDocument({...document,destinations:document.destinations.map(x=>x.id===d.id?{...x,recipient:e.target.value}:x)})}/></label><label>Responsable<select value={d.assigneeId} disabled={!editable} onChange={e=>setDocument({...document,destinations:document.destinations.map(x=>x.id===d.id?{...x,assigneeId:e.target.value}:x)})}>{options.map(m=><option value={m.id} key={m.id}>{m.label}</option>)}{!options.some(m=>m.id===d.assigneeId)&&<option value={d.assigneeId}>Responsable histórico · {d.assigneeId}</option>}</select></label><label>Cantidad declarada<input required type="number" min={1} max={10000000} step={1} value={d.units||''} disabled={!editable} onChange={e=>setDocument({...document,destinations:document.destinations.map(x=>x.id===d.id?{...x,units:Number(e.target.value)}:x)})}/></label>{editable&&document.destinations.length>1&&<button type="button" aria-label={'Quitar destino '+(i+1)} onClick={()=>setDocument({...document,destinations:document.destinations.filter(x=>x.id!==d.id)})}><Trash2 size={17} aria-hidden="true"/></button>}</div>)}
    {(creating||selected?.state==='draft')&&<div className={styles.actions}><button type="submit" className={styles.primary} disabled={!editable||!dirty}><FileCheck2 size={16} aria-hidden="true"/>Guardar borrador</button>{selected&&board?.actor.canWrite&&<button type="button" disabled={busy||dirty||uncertain} onClick={()=>confirm('submit')}><Send size={16} aria-hidden="true"/>Enviar a revisión</button>}</div>}
    {selected?.state==='in_review'&&<div className={styles.actions}><button type="button" className={styles.danger} disabled={!canReview||busy||uncertain} onClick={()=>confirm('publish')}>Publicar aviso del lote</button>{board?.actor.canWrite&&<button type="button" disabled={busy||uncertain} onClick={()=>confirm('revise')}>Solicitar correcciones</button>}{!canReview&&<p className={styles.hint}>La publicación requiere otra cuenta responsable autorizada para publicar o aprobar calidad del lote, con MFA verificado.</p>}</div>}
    {selected&&['draft','in_review'].includes(selected.state)&&board?.actor.canWrite&&<button type="button" className={styles.textButton} disabled={busy||uncertain} onClick={()=>confirm('cancel')}>Cancelar borrador sin publicar</button>}
   </form>}
   {tab==='progress'&&selected&&<div><p className={styles.warning}>{selected.published_at?'El caso conserva un aviso publicado. Consultá su versión vigente en «Revisar aviso publicado». Cerrar el seguimiento no levanta el aviso ni autoriza usar el producto.':'Todavía no se publicó el aviso; no se registran acuses ni cantidades hasta aprobarlo.'}</p>
    {document.destinations.map(d=>{const p=selected.progress[d.id]||{},open=d.units-(p.returnedUnits||0)-(p.heldUnits||0);return <article key={d.id} className={styles.task}><div className={styles.sectionHeading}><div><h3>{d.recipient}</h3><p>{options.find(m=>m.id===d.assigneeId)?.label||'Responsable '+d.assigneeId}</p></div><span className={styles.badge}>{p.acknowledgedAt?'Acuse registrado':'Acuse pendiente'}</span></div><div className={styles.taskNumbers}><span>Objetivo <b>{d.units}</b></span><span>Devueltas <b>{p.returnedUnits||0}</b></span><span>Inmovilizadas <b>{p.heldUnits||0}</b></span><span>Pendientes <b>{open}</b></span></div>{p.ackEvidence&&<p className={styles.hint}>Acuse: {p.ackEvidence} · {date(p.acknowledgedAt!)}</p>}{p.accountEvidence&&<p className={styles.hint}>Último comprobante: {p.accountEvidence}</p>}{selected.published_at&&<div className={styles.actions}><button type="button" disabled={busy} onClick={()=>void copyAssignedLink(d.id)}>Copiar enlace para el responsable</button>{d.assigneeId===board?.actor.id&&<Link prefetch={false} className={styles.textButton} href={taskLink({caseId:selected.id,destinationId:d.id})}>Responder mi tarea →</Link>}</div>}{board?.actor.canWrite&&selected.state==='active'&&<div className={styles.actions}>{!p.acknowledgedAt&&<button type="button" disabled={busy||uncertain} onClick={()=>confirm('acknowledge',d.id)}>Registrar acuse</button>}<button type="button" disabled={busy||uncertain||!p.acknowledgedAt} onClick={()=>confirm('account',d.id)}>Registrar cantidades</button></div>}</article>;})}
    {selected.state==='active'&&board?.actor.canWrite&&<button type="button" className={styles.primary} disabled={busy||uncertain||!allDone} onClick={()=>confirm('request_close')}>Solicitar cierre</button>}
    {selected.state==='closing'&&<div className={styles.review}><h3>Cierre pendiente de revisión</h3><p>{selected.close_reason}</p><div className={styles.actions}><button type="button" className={styles.primary} disabled={!canClose||busy||uncertain} onClick={()=>confirm('close')}>Aprobar cierre</button>{board?.actor.canWrite&&<button type="button" disabled={busy||uncertain} onClick={()=>confirm('resume')}>Volver al seguimiento</button>}</div></div>}
    {selected.state==='closed'&&<p className={styles.success}><CheckCircle2 size={18} aria-hidden="true"/>Seguimiento cerrado el {date(selected.closed_at)}. Cantidades y acuses declarados conservados en el historial.</p>}
   </div>}
   {tab==='evidence'&&selected&&<div><div className={styles.sectionHeading}><div><h3>Evidencia y trazabilidad del caso</h3><p>Revisión {selected.version} · cantidades informadas por operadores, no validadas por NFC.</p></div><button type="button" disabled={!board?.actor.canExport||busy} onClick={()=>void exportReport()}><Download size={16} aria-hidden="true"/>Descargar informe</button></div>{detail?<><p className={styles.hint}>{detail.historyTruncated?'Últimas 500 operaciones; el historial no está completo en esta consulta.':detail.operationCount+' operaciones registradas.'} Fuente consultada: {date(detail.observedAt)}</p><div className={styles.history}>{detail.history.slice().reverse().map(h=><article key={h.id}><span>r{h.version}</span><div><strong>{actions[h.action]||({'create':'Caso creado','save':'Borrador guardado'} as Record<string,string>)[h.action]||h.action}</strong><p>{h.actorLabel} · {date(h.at)}{h.submissionSource==='assigned_task'?' · Cuenta asignada':''}</p>{h.reason&&<p>{h.reason}</p>}{h.evidenceReference&&<p>Comprobante: {h.evidenceReference}</p>}</div></article>)}</div></>:<p>Actualizá el caso para consultar el historial persistido.</p>}</div>}
   </>}
  </section></div>
  {modal&&<RecallDialog title={actions[modal.action]} onCancel={()=>setModal(null)}><p>{modal.action==='publish'?'Esta acción publica el aviso para todo el lote. No envía mensajes a distribuidores ni modifica la autenticidad de las etiquetas.':modal.action==='close'?'Aprueba el cierre de los destinos y cantidades declarados. El aviso del lote se conserva; el producto no queda liberado automáticamente.':'Se guardará un movimiento con tu identidad y revisión actual del caso.'}</p>{['revise','cancel','request_close','resume','close','acknowledge','account'].includes(modal.action)&&<label>Motivo o evidencia de la acción<textarea rows={3} minLength={10} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>}{modal.destinationId&&<label>Referencia del comprobante<input minLength={5} maxLength={400} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Acta, remito o referencia de acuse"/></label>}{modal.action==='account'&&<div className={styles.row}><label>Total devueltas a la fecha<input type="number" min={0} step={1} value={returned} onChange={e=>setReturned(e.target.value)}/></label><label>Total inmovilizadas a la fecha<input type="number" min={0} step={1} value={held} onChange={e=>setHeld(e.target.value)}/></label></div>}<label className={styles.checkbox}><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/>Confirmo guardar esta acción con la evidencia indicada.</label><div className={styles.actions}><button type="button" onClick={()=>setModal(null)}>Volver</button><button type="button" className={modal.action==='publish'?styles.danger:styles.primary} disabled={!accept||busy||(['revise','cancel','request_close','resume','close','acknowledge','account'].includes(modal.action)&&reason.trim().length<10)||(!!modal.destinationId&&evidence.trim().length<5)} onClick={submitModal}>Confirmar acción</button></div></RecallDialog>}
 </main>;
}
function RecallDialog({title,children,onCancel}:{title:string;children:React.ReactNode;onCancel:()=>void}){const ref=useRef<HTMLDialogElement>(null),previous=useRef<HTMLElement|null>(null);useEffect(()=>{previous.current=document.activeElement as HTMLElement;ref.current?.showModal();return()=>previous.current?.focus();},[]);return <dialog ref={ref} className={styles.dialog} aria-labelledby="recall-dialog-title" onCancel={e=>{e.preventDefault();onCancel();}}><div className={styles.dialogHeading}><h2 id="recall-dialog-title">{title}</h2><button type="button" aria-label="Cerrar confirmación" onClick={onCancel}><X size={20} aria-hidden="true"/></button></div>{children}</dialog>;}
