"use client";
import{useEffect,useRef,useState}from"react";
import{SupplierRequestError,type SupplierRequest}from"../lib/supplier-request-client";
import{supplierBindingCall,type BindingOperation,type BindingSnapshot}from"../lib/supplier-request-binding-client";
import{parseBindingCommand,type SupplierBindingCommand,type SupplierBindingEvent}from"../lib/supplier-binding-policy";
import type{SupplierRequestReviewGuard}from"./supplier-request-review";
import styles from"./supplier-request-workspace.module.css";
import view from"./supplier-request-binding.module.css";
type Props={request:SupplierRequest;isNexid:boolean;suspended:boolean;canInteract:()=>boolean;onGuard:(v:SupplierRequestReviewGuard)=>void;onAccessUnavailable:()=>void;onExit:()=>void};
type Form={reference:string;name:string;confirmation_ref:string;reason:string};
const blank=():Form=>({reference:'',name:'',confirmation_ref:'',reason:''});
const stamp=(value:string)=>value.slice(0,16).replace('T',' ')+' UTC';
const labels={none:'Proveedor sin registrar',current:'Proveedor y especificación vinculados',stale:'La especificación requiere revisión',withdrawn:'Vínculo retirado'};
export function SupplierRequestBinding({request,isNexid,suspended,canInteract,onGuard,onAccessUnavailable,onExit}:Props){
 const[mode,setMode]=useState<'closed'|'loading'|'view'|'edit'|'confirm'|'saving'|'uncertain'|'error'|'denied'>('closed');
 const[snapshot,setSnapshot]=useState<BindingSnapshot|null>(null),[history,setHistory]=useState<SupplierBindingEvent[]>([]),[cursor,setCursor]=useState<number|null>(null),[error,setError]=useState('');
 const[form,setForm]=useState<Form>(blank),[action,setAction]=useState<'assign'|'withdraw'>('assign'),[reviewed,setReviewed]=useState<SupplierBindingCommand|null>(null),[receipt,setReceipt]=useState<BindingSnapshot['receipt']>();
 const alive=useRef(true),epoch=useRef(0),busy=useRef(false),uncertain=useRef(false),active=useRef<AbortController|null>(null),operation=useRef<BindingOperation|null>(null),editing=useRef(false),draft=useRef<Form>(blank());
 const heading=useRef<HTMLHeadingElement|null>(null),opener=useRef<HTMLButtonElement|null>(null),restoreFocus=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;epoch.current++;active.current?.abort();};},[]);
 useEffect(()=>{if(mode==='confirm')heading.current?.focus({preventScroll:true});if(mode==='closed'&&restoreFocus.current){restoreFocus.current=false;opener.current?.focus();}},[mode]);
 const scope={id:request.id,orderId:request.order_id!,tenant:request.tenant_slug,tenantId:request.tenant_id};
 function allowed(kind:'assign'|'withdraw'){return Boolean(isNexid&&snapshot?.writes_enabled&&snapshot.order.status==='pack_ready'&&!snapshot.dispatch_receipt&&(kind==='assign'?snapshot.specification.ready:snapshot.current?.action==='assign'));}
 function close(){if(busy.current||uncertain.current)return;if(editing.current&&Object.values(draft.current).some(Boolean)&&!window.confirm('¿Descartar esta edición local y cerrar el proveedor?'))return;
 epoch.current++;active.current?.abort();active.current=null;editing.current=false;draft.current=blank();setForm(blank());setReviewed(null);setError('');setMode('closed');restoreFocus.current=true;onGuard({dirty:false,locked:false});}
 function revoke(){setSnapshot(null);setHistory([]);setCursor(null);setReceipt(undefined);setReviewed(null);onAccessUnavailable();}
 async function load(older=false){if(busy.current||uncertain.current||active.current||!canInteract())return;
 const generation=++epoch.current,controller=new AbortController();active.current=controller;onGuard({dirty:editing.current,locked:true});setError('');if(!older)setMode('loading');
 try{const result=await supplierBindingCall({...scope,before:older?cursor:null,signal:controller.signal});if(!alive.current||epoch.current!==generation)return;
 if(older&&snapshot&&result.revision===snapshot.revision){setHistory([...new Map([...result.history,...history].sort((a,b)=>a.revision-b.revision).map(e=>[e.id,e])).values()]);}else setHistory(result.history);
 setCursor(result.next_before_revision);setSnapshot(result);setMode(editing.current?'edit':'view');onGuard({dirty:editing.current,locked:editing.current});
 }catch(issue){if(!alive.current||epoch.current!==generation)return;const failure=issue instanceof SupplierRequestError?issue:new SupplierRequestError('supplier_binding_unavailable');
 if([401,403,404].includes(failure.status)){revoke();setMode('denied');setError('El acceso cambió. Se ocultaron el proveedor, la especificación y los datos del expediente. No se registró una asignación.');}
 else{setMode('error');setError('No se confirmó el proveedor ni la especificación actual. La edición local se conserva; esto no significa que no haya un vínculo registrado.');}
 }finally{if(active.current===controller)active.current=null;}}
 function start(kind:'assign'|'withdraw'){if(!allowed(kind)||!canInteract()||active.current)return;setAction(kind);draft.current=blank();setForm(blank());setReviewed(null);setReceipt(undefined);setError('');editing.current=true;onGuard({dirty:true,locked:true});setMode('edit');}
 function edit(key:keyof Form,value:string){if(busy.current||uncertain.current)return;draft.current={...draft.current,[key]:value};setForm(draft.current);setReviewed(null);}
 function inspect(){if(!snapshot||!allowed(action)||!canInteract()||active.current)return;try{const f=draft.current,s=snapshot.specification;
 const command=parseBindingCommand({action,expected_revision:snapshot.revision,expected_request_revision:snapshot.request_revision,order_id:snapshot.order.id,supplier:action==='assign'?{reference:f.reference,name:f.name,confirmation_ref:f.confirmation_ref}:null,spec:action==='assign'?{revision:s.revision,hash:s.hash,decision_id:s.decision_id}:null,reason:f.reason});
 setReviewed(command);setError('');setMode('confirm');}catch{setError('Completá referencia del proveedor (letras, números, punto, guion o guion bajo), nombre, referencia de confirmación y motivo. No incluyas llaves, contraseñas ni enlaces de descarga privados.');}}
 async function execute(command:BindingOperation){if(busy.current||active.current||!canInteract())return;busy.current=true;operation.current=command;const controller=new AbortController(),generation=epoch.current;active.current=controller;setMode('saving');setError('');onGuard({dirty:true,locked:true});
 try{const result=await supplierBindingCall({...scope,command,signal:controller.signal});if(!alive.current||epoch.current!==generation)return;
 uncertain.current=false;operation.current=null;editing.current=false;draft.current=blank();setForm(blank());setReviewed(null);setSnapshot(result);setHistory(result.history);setCursor(result.next_before_revision);setReceipt(result.receipt);setMode('view');onGuard({dirty:false,locked:false});
 }catch(issue){if(!alive.current||epoch.current!==generation)return;const failure=issue instanceof SupplierRequestError?issue:new SupplierRequestError('supplier_binding_unavailable',0,true);uncertain.current ||= failure.uncertain;
 if([401,403,404].includes(failure.status))revoke();setMode(uncertain.current?'uncertain':[401,403,404].includes(failure.status)?'denied':'error');
 setError(uncertain.current?'El resultado sigue sin confirmar. Comprobá la misma operación; no se creará una asignación nueva.':failure.status===409?'Cambió el proveedor, la especificación o el estado del envío. Tu edición se conserva: consultá nuevamente y revisá antes de confirmar.':failure.code==='supplier_request_secret_content_rejected'?'Retirá secretos del nombre, la referencia de confirmación o el motivo.':'La operación no se confirmó. Revisá disponibilidad y permisos antes de volver a intentarlo.');if(!uncertain.current)operation.current=null;
 }finally{busy.current=false;if(active.current===controller)active.current=null;}}
 function confirm(){if(!reviewed||busy.current||uncertain.current||!canInteract()||!allowed(reviewed.action))return;void execute(Object.freeze({key:crypto.randomUUID(),body:Object.freeze({...reviewed,supplier:reviewed.supplier?Object.freeze({...reviewed.supplier}):null,spec:reviewed.spec?Object.freeze({...reviewed.spec}):null})}));}
 const orderHref=`/supplier-orders/${request.order_id}?tenant=${encodeURIComponent(request.tenant_slug)}`;
 if(mode==='closed')return<section className={styles.reviewPanel}><h3>Proveedor y especificación</h3><p className={styles.muted}>Vinculá el destinatario confirmado con la versión aprobada del pedido. No envía documentos ni registra fabricación.</p><button ref={opener} className={styles.button} type="button" data-testid="binding-open" disabled={suspended} onClick={()=>{if(!canInteract()){setError('Guardá o descartá las otras ediciones antes de consultar el proveedor.');return;}void load();}}>Consultar proveedor y especificación</button>{error?<p role="alert">{error}</p>:null}</section>;
 return<section className={styles.reviewPanel} data-testid="binding-panel" aria-labelledby="binding-heading" aria-busy={mode==='loading'||mode==='saving'}><h3 id="binding-heading">Preparación para el proveedor</h3>
 <p className={view.hint}>Proveedor y confirmación declarados por NexID. La coincidencia de la especificación es un control del registro técnico, no una certificación del fabricante ni una prueba de entrega.</p>
 {mode==='loading'||mode==='saving'?<p role="status">{mode==='loading'?'Consultando fuente e historial…':'Registrando la operación…'}</p>:null}{error?<p role="alert" className={styles.error}>{error}</p>:null}
 {receipt?<p role="status" className={styles.notice} data-testid="binding-receipt">Operación registrada · revisión {receipt.revision}{snapshot&&snapshot.revision>receipt.revision?' · se recuperó un recibo anterior; el vínculo actual se muestra debajo.':''}</p>:null}
 {snapshot?<><div className={view.steps} aria-label="Estado de preparación"><div className={view.step}><strong>Pedido técnico</strong><span>{snapshot.order.status==='pack_ready'?'Preparado, sin envío registrado':'Estado: '+snapshot.order.status}</span></div><div className={view.step}><strong>Especificación v{snapshot.specification.revision}</strong><span>{snapshot.specification.ready?'Aprobación e historial coincidentes':'Aprobación sin confirmar'}</span></div><div className={view.step}><strong>Proveedor</strong><span>{labels[snapshot.binding_status]}</span></div></div>
 {!snapshot.writes_enabled?<p role="status">Registro de cambios desactivado. El historial sigue disponible.</p>:null}{!isNexid?<p className={styles.notice}>Acceso de empresa: consulta. Sólo NexID puede registrar o retirar el proveedor.</p>:null}
 {snapshot.binding_status==='stale'?<p role="status" className={styles.notice}>La especificación actual ya no coincide con la vinculada. Revisá la aprobación y registrá un vínculo actualizado antes del comprobante de envío.</p>:null}
 {snapshot.current?<div className={view.vendor} data-testid="binding-current"><h4>{snapshot.current.supplier.name}{snapshot.current.action==='withdraw'?' · vínculo retirado':''}</h4><p>Referencia del destinatario: <strong>{snapshot.current.supplier.reference}</strong><br/>Confirmación declarada: {snapshot.current.supplier.confirmation_ref}<br/>Especificación vinculada: v{snapshot.current.spec.revision}</p><p className={view.hash}>{snapshot.current.spec.hash}</p><p className={view.hint}>{stamp(snapshot.current.created_at)} · responsable (ID): {snapshot.current.actor_id}</p></div>:<p role="status">La fuente confirma que todavía no se registró un proveedor en este circuito.</p>}
 {snapshot.dispatch_receipt?<p role="status" data-testid="binding-dispatch" className={styles.notice}>Existe un comprobante manual de envío: {snapshot.dispatch_receipt.id} · {stamp(snapshot.dispatch_receipt.created_at)}. {snapshot.dispatch_receipt.binding_event_id?'Está vinculado a esta asignación.':'Es anterior a este circuito de vinculación.'} No es un acuse de recepción ni certifica fabricación. Los cambios de proveedor están cerrados.</p>:null}
 <p className={view.hint}>Consulta: {stamp(snapshot.as_of)} · solicitud versión {snapshot.request_revision} · vínculo revisión {snapshot.revision}</p>
 </>:null}
 {mode==='view'?<div className={styles.actions}>{allowed('assign')?<button className={styles.button} type="button" data-testid="binding-assign" onClick={()=>start('assign')}>{snapshot?.current?'Preparar vínculo actualizado':'Registrar proveedor'}</button>:null}{allowed('withdraw')?<button className={styles.button} type="button" data-testid="binding-withdraw" onClick={()=>start('withdraw')}>Retirar vínculo</button>:null}<button className={styles.button} type="button" data-testid="binding-refresh" onClick={()=>void load()}>Actualizar información</button><a className={styles.button} data-testid="binding-order" href={orderHref}>Abrir pedido, especificación y envío</a></div>:null}
 {(mode==='edit'||mode==='error'&&editing.current)?<div data-testid="binding-form"><h4>{action==='assign'?'Datos del proveedor':'Motivo del retiro'}</h4>{action==='assign'?<div className={styles.grid}><label>Referencia del proveedor<input data-testid="binding-reference" maxLength={128} value={form.reference} onChange={e=>edit('reference',e.target.value)} placeholder="Ejemplo: PROV-001"/></label><label>Nombre del proveedor<input data-testid="binding-name" maxLength={200} value={form.name} onChange={e=>edit('name',e.target.value)}/></label><label>Referencia de su confirmación<input data-testid="binding-confirmation-ref" maxLength={240} value={form.confirmation_ref} onChange={e=>edit('confirmation_ref',e.target.value)} placeholder="Identificador de correo o documento"/></label></div>:null}<label>Motivo de esta operación<textarea data-testid="binding-reason" rows={3} maxLength={1000} value={form.reason} onChange={e=>edit('reason',e.target.value)}/></label><p className={view.hint}>No se adjuntan ni descargan archivos. Guardá las evidencias por su circuito autorizado y registrá aquí sólo una referencia sin secretos.</p>{mode==='edit'&&allowed(action)?<button className={styles.button} type="button" data-testid="binding-inspect" onClick={inspect}>Revisar antes de registrar</button>:null}{mode==='edit'&&!allowed(action)?<p role="status">La fuente actual no permite esta acción. No se enviará la edición conservada.</p>:null}</div>:null}
 {mode==='confirm'&&reviewed&&snapshot?<div className={styles.review} data-testid="binding-confirmation"><h3 ref={heading} tabIndex={-1}>{action==='assign'?'Confirmar proveedor y especificación':'Confirmar retiro del vínculo'}</h3><p><strong>{request.title}</strong><br/>Empresa: {request.tenant_slug}<br/>Pedido: {snapshot.order.id}</p>{reviewed.supplier&&reviewed.spec?<><p>Proveedor: {reviewed.supplier.name}<br/>Referencia: {reviewed.supplier.reference}<br/>Confirmación: {reviewed.supplier.confirmation_ref}<br/>Especificación aprobada v{reviewed.spec.revision}</p><p className={view.hash}>{reviewed.spec.hash}</p></>:<p>El historial se conserva. El registro de envío de este circuito quedará bloqueado hasta vincular nuevamente un proveedor.</p>}<p className={styles.pre}>{reviewed.reason}</p><p>No se envía un pedido ni un paquete de claves. El comprobante manual de envío conserva sus controles de exportación, permisos y MFA.</p><div className={styles.actions}><button className={styles.primary} type="button" data-testid="binding-confirm" onClick={confirm}>Confirmar {action==='assign'?'vínculo':'retiro'}</button><button className={styles.button} type="button" onClick={()=>setMode('edit')}>Volver a editar</button></div></div>:null}
 {mode==='error'?<button className={styles.button} type="button" data-testid="binding-reload" onClick={()=>void load()}>Consultar versión actual</button>:null}
 {mode==='uncertain'?<><button className={styles.button} type="button" data-testid="binding-retry" onClick={()=>{if(operation.current)void execute(operation.current);}}>Comprobar la misma operación</button><button className={styles.button} type="button" data-testid="binding-exit-uncertain" onClick={()=>{if(busy.current||!window.confirm('¿Salir con resultado sin confirmar? Salir no revierte ni reenvía el vínculo. Consultá de nuevo antes de intentar otra operación.'))return;uncertain.current=false;operation.current=null;onGuard({dirty:false,locked:false});onExit();}}>Salir con resultado sin confirmar</button></>:null}
 {mode==='denied'?<button className={styles.button} type="button" data-testid="binding-exit-denied" onClick={()=>{onGuard({dirty:false,locked:false});onExit();}}>Cerrar consulta sin acceso</button>:null}
 {snapshot&&history.length?<details className={styles.commercial} data-testid="binding-history"><summary>Historial del proveedor ({history.length} registros cargados)</summary><ol className={view.history}>{history.map(e=><li key={e.id}><strong>Revisión {e.revision} · {e.action==='assign'?'Proveedor vinculado':'Vínculo retirado'}</strong><p>{e.supplier.name} · {e.supplier.reference}<br/>Especificación v{e.spec.revision} · {stamp(e.created_at)}<br/>Responsable (ID): {e.actor_id}</p><p className={styles.pre}>{e.reason}</p></li>)}</ol>{cursor?<button className={styles.button} type="button" data-testid="binding-older" disabled={mode!=='view'} onClick={()=>void load(true)}>Cargar historial anterior</button>:null}</details>:null}
 {!['saving','uncertain','denied'].includes(mode)?<button className={styles.button} type="button" data-testid="binding-close" onClick={close}>Cerrar sin registrar otra operación</button>:null}
 </section>;
}
