"use client";
import{useEffect,useRef,useState}from"react";
import{SupplierRequestError,type SupplierRequest}from"../lib/supplier-request-client";
import{supplierDeliveryAckCall,type DeliveryAckOperation,type DeliveryAckSnapshot}from"../lib/supplier-request-delivery-ack-client";
import{parseDeliveryAckCommand,type DeliveryAckCommand,type DeliveryAckEvent}from"../lib/supplier-delivery-ack-policy";
import type{SupplierRequestReviewGuard}from"./supplier-request-review";
import styles from"./supplier-request-workspace.module.css";
import view from"./supplier-request-binding.module.css";
type Props={request:SupplierRequest;isNexid:boolean;suspended:boolean;canInteract:()=>boolean;onGuard:(v:SupplierRequestReviewGuard)=>void;onAccessUnavailable:()=>void;onAccessRestored:()=>void;onExit:()=>void};
type Form={artifact_id:string;reported_hash:string;evidence_ref:string;reason:string};
const blank=():Form=>({artifact_id:'',reported_hash:'',evidence_ref:'',reason:''});
const stamp=(value:string)=>value.slice(0,16).replace('T',' ')+' UTC';
const labels={received:'Recepción documental declarada',issue:'Incidencia documental registrada',withdraw:'Declaración retirada'};
export function SupplierRequestDeliveryAck({request,isNexid,suspended,canInteract,onGuard,onAccessUnavailable,onAccessRestored,onExit}:Props){
 const[mode,setMode]=useState<'closed'|'loading'|'view'|'edit'|'confirm'|'saving'|'uncertain'|'error'|'denied'>('closed');
 const[snapshot,setSnapshot]=useState<DeliveryAckSnapshot|null>(null),[history,setHistory]=useState<DeliveryAckEvent[]>([]),[cursor,setCursor]=useState<number|null>(null),[error,setError]=useState('');
 const[form,setForm]=useState<Form>(blank),[action,setAction]=useState<'received'|'issue'|'withdraw'>('received'),[reviewed,setReviewed]=useState<DeliveryAckCommand|null>(null),[receipt,setReceipt]=useState<DeliveryAckSnapshot['receipt']>();
 const alive=useRef(true),epoch=useRef(0),busy=useRef(false),uncertain=useRef(false),active=useRef<AbortController|null>(null),operation=useRef<DeliveryAckOperation|null>(null),editing=useRef(false),draft=useRef<Form>(blank());
 const heading=useRef<HTMLHeadingElement|null>(null),opener=useRef<HTMLButtonElement|null>(null),restoreFocus=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;epoch.current++;active.current?.abort();};},[]);
 useEffect(()=>{if(mode==='confirm')heading.current?.focus({preventScroll:true});if(mode==='closed'&&restoreFocus.current){restoreFocus.current=false;opener.current?.focus();}},[mode]);
 const scope={id:request.id,orderId:request.order_id!,tenant:request.tenant_slug,tenantId:request.tenant_id};
 function allowed(kind:'received'|'issue'|'withdraw'){return Boolean(isNexid&&snapshot?.writes_enabled&&(kind==='withdraw'?snapshot.current&&snapshot.current.action!=='withdraw':snapshot.source&&snapshot.artifacts.length));}
 function close(){if(busy.current||uncertain.current)return;if(editing.current&&Object.values(draft.current).some(Boolean)&&!window.confirm('¿Descartar esta edición local y cerrar el acuse?'))return;
 epoch.current++;active.current?.abort();active.current=null;editing.current=false;draft.current=blank();setForm(blank());setReviewed(null);setError('');setMode('closed');restoreFocus.current=true;onGuard({dirty:false,locked:false});}
 function revoke(){setSnapshot(null);setHistory([]);setCursor(null);setReceipt(undefined);setReviewed(null);onAccessUnavailable();}
 async function load(older=false){if(busy.current||uncertain.current||active.current||!canInteract())return;
 const generation=++epoch.current,controller=new AbortController();active.current=controller;onGuard({dirty:editing.current,locked:true});setError('');if(!older)setMode('loading');
 try{const result=await supplierDeliveryAckCall({...scope,before:older?cursor:null,signal:controller.signal});if(!alive.current||epoch.current!==generation)return;
 if(older&&snapshot&&result.revision===snapshot.revision){setHistory([...new Map([...result.history,...history].sort((a,b)=>a.revision-b.revision).map(e=>[e.id,e])).values()]);}else setHistory(result.history);
 setCursor(result.next_before_revision);setSnapshot(result);onAccessRestored();setMode(editing.current?'edit':'view');onGuard({dirty:editing.current,locked:editing.current});
 }catch(issue){if(!alive.current||epoch.current!==generation)return;const failure=issue instanceof SupplierRequestError?issue:new SupplierRequestError('supplier_delivery_ack_unavailable');
 if([401,403,404].includes(failure.status)){revoke();setMode('denied');setError('El acceso cambió. Se ocultaron el paquete, el envío y los datos del expediente. No se registró un acuse.');}
 else{setMode('error');setError('No se confirmó el envío ni los paquetes actual. La edición local se conserva; esto no significa que no haya un vínculo registrado.');}
 }finally{if(active.current===controller)active.current=null;}}
 function start(kind:'received'|'issue'|'withdraw'){if(!allowed(kind)||!canInteract()||active.current)return;setAction(kind);draft.current=blank();setForm(blank());setReviewed(null);setReceipt(undefined);setError('');editing.current=true;onGuard({dirty:true,locked:true});setMode('edit');}
 function edit(key:keyof Form,value:string){if(busy.current||uncertain.current)return;draft.current={...draft.current,[key]:value};setForm(draft.current);setReviewed(null);}
 function inspect(){if(!snapshot||!allowed(action)||!canInteract()||active.current)return;try{const f=draft.current,src=snapshot.source,previous=snapshot.current,artifact=snapshot.artifacts.find(a=>a.id===f.artifact_id);
 const target=action==='withdraw'?previous:artifact&&src?{artifact_id:artifact.id,artifact_hash:artifact.hash,dispatch_id:src.dispatch_id,binding_id:src.binding_id}:null;if(!target)throw Error();
 const command=parseDeliveryAckCommand({action,expected_revision:snapshot.revision,expected_request_revision:snapshot.request_revision,order_id:snapshot.order_id,dispatch_id:target.dispatch_id,binding_id:target.binding_id,artifact_id:target.artifact_id,artifact_hash:target.artifact_hash,reported_hash:action==='withdraw'?null:f.reported_hash.trim()||null,evidence_ref:f.evidence_ref,reason:f.reason});
 setReviewed(command);setError('');setMode('confirm');}catch{setError('Elegí un paquete y completá referencia del comprobante y motivo. Para registrar recepción, ingresá el SHA-256 del sobre cifrado informado en la comunicación; debe coincidir exactamente. Una diferencia se registra como incidencia.');}}
 async function execute(command:DeliveryAckOperation){if(busy.current||active.current||!canInteract())return;busy.current=true;operation.current=command;const controller=new AbortController(),generation=epoch.current;active.current=controller;setMode('saving');setError('');onGuard({dirty:true,locked:true});
 try{const result=await supplierDeliveryAckCall({...scope,command,signal:controller.signal});if(!alive.current||epoch.current!==generation)return;
 uncertain.current=false;operation.current=null;editing.current=false;draft.current=blank();setForm(blank());setReviewed(null);setSnapshot(result);onAccessRestored();setHistory(result.history);setCursor(result.next_before_revision);setReceipt(result.receipt);setMode('view');onGuard({dirty:false,locked:false});
 }catch(issue){if(!alive.current||epoch.current!==generation)return;const failure=issue instanceof SupplierRequestError?issue:new SupplierRequestError('supplier_delivery_ack_unavailable',0,true);uncertain.current ||= failure.uncertain;
 if([401,403,404].includes(failure.status))revoke();setMode(uncertain.current?'uncertain':[401,403,404].includes(failure.status)?'denied':'error');
 setError(uncertain.current?'El resultado sigue sin confirmar. Comprobá la misma operación; no se creará un acuse nueva.':failure.status===409?'Cambió el paquete, el envío o el estado del envío. Tu edición se conserva: consultá nuevamente y revisá antes de confirmar.':failure.code==='supplier_request_secret_content_rejected'?'Retirá secretos de la referencia del comprobante o el motivo.':'La operación no se confirmó. Revisá disponibilidad y permisos antes de volver a intentarlo.');if(!uncertain.current)operation.current=null;
 }finally{busy.current=false;if(active.current===controller)active.current=null;}}
 function confirm(){if(!reviewed||busy.current||uncertain.current||!canInteract()||!allowed(reviewed.action))return;void execute(Object.freeze({key:crypto.randomUUID(),body:Object.freeze({...reviewed})}));}
 const orderHref=`/supplier-orders/${request.order_id}?tenant=${encodeURIComponent(request.tenant_slug)}`;
 if(mode==='closed')return<section className={styles.reviewPanel}><h3>Acuse del paquete cifrado</h3><p className={styles.muted}>Registrá la comunicación recibida sobre un paquete exportado y su envío. No realiza una entrega ni verifica al proveedor.</p><button ref={opener} className={styles.button} type="button" data-testid="ack-open" disabled={suspended} onClick={()=>{if(!canInteract()){setError('Guardá o descartá las otras ediciones antes de consultar el acuse.');return;}void load();}}>Consultar envío y acuses</button>{error?<p role="alert">{error}</p>:null}</section>;
 return<section className={styles.reviewPanel} data-testid="ack-panel" aria-labelledby="ack-heading" aria-busy={mode==='loading'||mode==='saving'}><h3 id="ack-heading">Seguimiento documental del paquete cifrado</h3>
 <p className={view.hint}>Registro manual de NexID sobre una comunicación del proveedor. No verifica identidad externa, descarga, descifrado ni recepción física. Cada declaración se refiere a un paquete, no a todo el pedido.</p>
 {mode==='loading'||mode==='saving'?<p role="status">{mode==='loading'?'Consultando envío, exportaciones e historial…':'Registrando el comprobante…'}</p>:null}{error?<p role="alert" className={styles.error}>{error}</p>:null}
 {receipt?<p role="status" className={styles.notice} data-testid="ack-receipt">Operación registrada · revisión {receipt.revision}{snapshot&&snapshot.revision>receipt.revision?' · recibo anterior recuperado; se conserva el estado más reciente.':''}</p>:null}
 {snapshot?<><div className={view.steps}><div className={view.step}><strong>Envío</strong><span>{snapshot.source?'Comprobante manual vinculado':'Fuente de envío sin confirmar'}</span></div><div className={view.step}><strong>Paquetes elegibles cargados</strong><span>{snapshot.artifacts_count}{snapshot.artifacts_truncated?' · hay más fuera de esta respuesta':''}</span></div><div className={view.step}><strong>Última declaración</strong><span>{snapshot.current?labels[snapshot.current.action]:'Sin declaraciones'}</span></div></div>
 {!snapshot.writes_enabled?<p role="status">Registro de acuses desactivado. El historial permanece consultable.</p>:null}{!isNexid?<p className={styles.notice}>Acceso de empresa: sólo consulta. El acuse documental lo registra NexID.</p>:null}
 {snapshot.source?<div className={view.vendor} data-testid="ack-source"><h4>{snapshot.source.supplier_name}</h4><p>Referencia: {snapshot.source.supplier_ref}<br/>Envío registrado: {stamp(snapshot.source.sent_at)}<br/>Comprobante: {snapshot.source.dispatch_id}<br/>Especificación vinculada: v{snapshot.source.spec_revision}</p></div>:<p role="status">No se confirmó un envío vinculado al proveedor y la especificación aprobada. Consultá el pedido; no se puede registrar un nuevo acuse.</p>}
 {snapshot.source&&!snapshot.artifacts_count?<p role="status">No hay paquetes cifrados elegibles en esta respuesta. No se genera ni se exporta un paquete para completar este paso.</p>:null}
 {snapshot.current?<div className={view.vendor} data-testid="ack-current"><h4>{labels[snapshot.current.action]} · revisión {snapshot.current.revision}</h4><p>Paquete: {snapshot.current.artifact_id}<br/>Referencia documental: {snapshot.current.evidence_ref}</p><p className={view.hash}>Huella del sobre exportado: {snapshot.current.artifact_hash}</p><p className={view.hint}>Dato declarado por NexID · {stamp(snapshot.current.created_at)} · responsable (ID): {snapshot.current.actor_id}</p><p className={styles.pre}>{snapshot.current.reason}</p></div>:null}
 <p className={view.hint}>Consulta: {stamp(snapshot.as_of)} · solicitud versión {snapshot.request_revision} · historial revisión {snapshot.revision}</p></>:null}
 {mode==='view'?<div className={styles.actions}>{allowed('received')?<button className={styles.button} type="button" data-testid="ack-received" onClick={()=>start('received')}>Registrar recepción declarada</button>:null}{allowed('issue')?<button className={styles.button} type="button" data-testid="ack-issue" onClick={()=>start('issue')}>Registrar incidencia documental</button>:null}{allowed('withdraw')?<button className={styles.button} type="button" data-testid="ack-withdraw" onClick={()=>start('withdraw')}>Retirar última declaración</button>:null}<button className={styles.button} type="button" data-testid="ack-refresh" onClick={()=>void load()}>Actualizar información</button><a className={styles.button} href={orderHref}>Abrir pedido y envío</a></div>:null}
 {(mode==='edit'||mode==='error'&&editing.current)?<div data-testid="ack-form"><h4>{action==='withdraw'?'Corregir el historial sin borrarlo':action==='received'?'Datos de la comunicación recibida':'Describir la incidencia'}</h4>{action!=='withdraw'?<><label>Paquete cifrado<select data-testid="ack-artifact" value={form.artifact_id} onChange={e=>edit('artifact_id',e.target.value)}><option value="">Seleccionar paquete exportado</option>{snapshot?.artifacts.map(a=><option key={a.id} value={a.id}>{a.id} · {stamp(a.created_at)}</option>)}</select></label>{form.artifact_id?<p className={view.hash}>Huella registrada al exportar: {snapshot?.artifacts.find(a=>a.id===form.artifact_id)?.hash}</p>:null}<label>SHA-256 informado por el proveedor {action==='issue'?'(opcional)':''}<input data-testid="ack-reported-hash" autoComplete="off" spellCheck={false} maxLength={71} value={form.reported_hash} onChange={e=>edit('reported_hash',e.target.value)} placeholder="sha256:…"/></label><p className={view.hint}>Del archivo .zip.enc completo, no del ZIP descifrado. No se completa automáticamente. La coincidencia compara referencias; no autentica al remitente.</p></>:null}
 <label>Referencia del comprobante o comunicación<input data-testid="ack-evidence" maxLength={240} value={form.evidence_ref} onChange={e=>edit('evidence_ref',e.target.value)} placeholder="Identificador del correo o documento"/></label><label>Motivo y observaciones<textarea data-testid="ack-reason" rows={3} maxLength={1000} value={form.reason} onChange={e=>edit('reason',e.target.value)}/></label><p className={view.hint}>No incluyas contraseñas, claves ni enlaces privados. Sólo se registra una referencia: aquí no se adjuntan ni se abren archivos.</p>
 {mode==='edit'&&allowed(action)?<button className={styles.button} type="button" data-testid="ack-inspect" onClick={inspect}>Revisar antes de registrar</button>:null}{mode==='edit'&&!allowed(action)?<p role="status">La fuente actual no habilita la acción. Consultá nuevamente sin perder esta edición.</p>:null}</div>:null}
 {mode==='confirm'&&reviewed&&snapshot?<div className={styles.review} data-testid="ack-confirmation"><h3 ref={heading} tabIndex={-1}>{action==='withdraw'?'Confirmar retiro de declaración':'Confirmar registro documental'}</h3><p><strong>{request.title}</strong><br/>Empresa: {request.tenant_slug}<br/>Pedido: {reviewed.order_id}<br/>Envío: {reviewed.dispatch_id}<br/>Paquete: {reviewed.artifact_id}</p><p className={view.hash}>{reviewed.artifact_hash}</p><p>Resultado: {labels[action]}<br/>Referencia: {reviewed.evidence_ref}</p><p className={styles.pre}>{reviewed.reason}</p><p>{action==='withdraw'?'Se conserva el evento original. Retirar esta declaración no retira el paquete enviado ni revoca sus claves.':'Se registra una declaración de NexID. No se confirma una descarga, descifrado, fabricación o recepción de etiquetas.'}</p><div className={styles.actions}><button className={styles.primary} type="button" data-testid="ack-confirm" onClick={confirm}>Confirmar registro</button><button className={styles.button} type="button" onClick={()=>setMode('edit')}>Volver a editar</button></div></div>:null}
 {mode==='error'?<button className={styles.button} type="button" data-testid="ack-reload" onClick={()=>void load()}>Consultar versión actual</button>:null}
 {mode==='uncertain'?<><button className={styles.button} type="button" data-testid="ack-retry" onClick={()=>{if(operation.current)void execute(operation.current);}}>Comprobar la misma operación</button><button className={styles.button} type="button" data-testid="ack-exit-uncertain" onClick={()=>{if(busy.current||!window.confirm('¿Salir con resultado sin confirmar? Salir no revierte ni reenvía el registro. Consultá otra vez antes de una nueva operación.'))return;uncertain.current=false;operation.current=null;onGuard({dirty:false,locked:false});onExit();}}>Salir con resultado sin confirmar</button></>:null}
 {mode==='denied'?<button className={styles.button} type="button" data-testid="ack-exit-denied" onClick={()=>{onGuard({dirty:false,locked:false});onExit();}}>Cerrar consulta sin acceso</button>:null}
 {snapshot&&history.length?<details className={styles.commercial} data-testid="ack-history"><summary>Historial documental ({history.length} registros cargados)</summary><ol className={view.history}>{history.map(e=><li key={e.id}><strong>Revisión {e.revision} · {labels[e.action]}</strong><p>Paquete: {e.artifact_id}<br/>Referencia: {e.evidence_ref}<br/>{stamp(e.created_at)} · operador (ID): {e.actor_id}</p><p className={styles.pre}>{e.reason}</p></li>)}</ol>{cursor?<button className={styles.button} type="button" data-testid="ack-older" disabled={mode!=='view'} onClick={()=>void load(true)}>Cargar historial anterior</button>:null}</details>:null}
 {!['saving','uncertain','denied'].includes(mode)?<button className={styles.button} type="button" data-testid="ack-close" onClick={close}>Cerrar sin registrar otra operación</button>:null}
 </section>;
}
