"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Building2,PackageCheck,ShieldCheck,ArrowRight,RefreshCw,Boxes,Users} from 'lucide-react';
import {SupplierOrderConsole} from './supplier-order-console';
import {SupplierLegacyIntakeBlocked} from './supplier-legacy-intake-blocked';
import {RECEPTION_ACTION_LABELS,parseReception,receptionNextStep,type ReceptionData,type ReceptionOrder,type ReceptionAction} from '../lib/supplier-reception-contract';
import {boundedDossierJson} from '../lib/batch-dossier-readings';
import {dashboardCanOpenDestination} from '../lib/dashboard-destination-policy';
import styles from './supplier-reception-workspace.module.css';
type Access={role:string;label:string;tenantSlug:string|null;permissions:string[];deniedPermissions:string[];isDemo:boolean};
const ROLE_LABELS:Record<string,string>={'super-admin':'Superadministrador de NexID','tenant-owner':'Responsable de la empresa','tenant-admin':'Administrador de la empresa','operations-manager':'Responsable de operaciones','packaging-operator':'Operador de recepción','marketing-manager':'Editor comercial',viewer:'Solo consulta'};
const when=(v:string|null)=>v?new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(v))+' UTC':'Sin fecha informada';
export function SupplierReceptionWorkspace({initial,access,requestedTenant,prepareNew=false}:{initial:ReceptionData|null;access:Access;requestedTenant:string;prepareNew?:boolean}){
 const canPrepareInitially=prepareNew&&!access.isDemo&&!!initial?.tenant&&initial.actor.capabilities['supplier_order.create'];
 const [data,setData]=useState(initial),[options,setOptions]=useState(initial?.tenantOptions||[]),[tenant,setTenant]=useState(access.tenantSlug||requestedTenant),[pending,setPending]=useState(false),[error,setError]=useState(initial?'':'La fuente no confirmó esta consulta. No se presume inventario cero.');
 const [tab,setTab]=useState<'reception'|'roles'|'operations'>(canPrepareInitially?'operations':'reception'),[profile,setProfile]=useState('current'),[selection,setSelection]=useState<{tenant:string;order:ReceptionOrder|null}|null>(canPrepareInitially?{tenant:initial!.tenant!.slug,order:null}:null);
 const flight=useRef<AbortController|null>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;if(window.location.hash==='#supplier-order-console')setTab('operations');return()=>{alive.current=false;flight.current?.abort();};},[]);
 async function refresh(){
  if(flight.current||access.isDemo)return;
  if(selection&&!window.confirm('Cambiar la consulta descarta lo ingresado en la consola, no las operaciones ya guardadas. ¿Continuar?'))return;
  setSelection(null);setTab('reception');setData(null);setError('');setPending(true);const controller=new AbortController();flight.current=controller;const timer=setTimeout(()=>controller.abort(),15000);
  try{const response=await fetch('/api/admin/supplier-reception?'+new URLSearchParams(tenant?{tenant}:{}),{cache:'no-store',credentials:'same-origin',signal:controller.signal});if(!response.ok)throw new Error(response.status===403?'Tu cuenta no tiene acceso a ese alcance.':'La fuente no está disponible; la consulta no confirma datos nuevos.');if(response.headers.get('x-nexid-data-mode')==='demo')throw new Error('No se utilizan datos simulados para una recepción real.');const next=parseReception(await boundedDossierJson(response),{role:access.role,tenantSlug:access.tenantSlug,requestedTenant:tenant,isDemo:access.isDemo});if(alive.current){setData(next);setOptions(next.tenantOptions);setProfile('current');}}
  catch(e){if(alive.current)setError(e instanceof Error?e.message:'No se confirmó la consulta.');}finally{clearTimeout(timer);flight.current=null;if(alive.current)setPending(false);}
 }
 function operate(order:ReceptionOrder|null){
  if(!data?.tenant||access.isDemo)return;
  const next={tenant:data.tenant.slug,order};if(selection&&(selection.tenant!==next.tenant||selection.order?.id!==order?.id)&&!window.confirm('Cambiar de pedido descarta los campos sin guardar de la consola. Las operaciones guardadas se conservan. ¿Continuar?'))return;
  setSelection(next);setTab('operations');
 }
 const actor=data?.actor,inventory=data?.inventory;
 const canOpenDossier=dashboardCanOpenDestination('batches',{role:access.role,permissions:access.permissions,deniedPermissions:access.deniedPermissions,isDemo:access.isDemo});
 const preview=profile==='current'?null:data?.roleProfiles.find(r=>r.role===profile);
 const shown=preview?.capabilities||actor?.capabilities;
 return <main className={styles.root} data-testid="supplier-reception-workspace">
  <header className={styles.hero}><div><p className={styles.eyebrow}>DEL PEDIDO DE FÁBRICA A LA OPERACIÓN</p><h1>Recepción de rollos.</h1><p>Identificá la empresa y el pedido. Revisá el manifiesto, la evidencia y quién tiene autorización para cada paso.</p></div><span className={styles.heroIcon}><PackageCheck size={32} aria-hidden="true"/></span></header>
  <div className={styles.identity}><ShieldCheck size={19} aria-hidden="true"/><div><strong>{access.label} · {ROLE_LABELS[access.role]||access.role}</strong><span>{access.role==='super-admin'?'Administración global. Elegir una empresa no cambia tu rol ni suplanta su aprobación.':'Alcance fijo de tu empresa. No se modifica la sesión para explorar otros perfiles.'}</span></div><span className={styles.badge}>{access.isDemo?'Sesión ilustrativa · no operativa':'Sesión autenticada'}</span></div>
  <div className={styles.toolbar}><label className={styles.field}>Empresa para esta recepción<select value={tenant} disabled={Boolean(access.tenantSlug)||pending||access.isDemo} onChange={e=>setTenant(e.target.value)}><option value="">Elegí una empresa</option>{options.map(t=><option key={t.id} value={t.slug}>{t.name} · {t.slug}</option>)}{access.tenantSlug&&!options.some(t=>t.slug===access.tenantSlug)&&<option value={access.tenantSlug}>{access.tenantSlug}</option>}</select></label><button type="button" className={styles.button} disabled={pending||access.isDemo} onClick={()=>void refresh()}><RefreshCw size={15} aria-hidden="true"/>{pending?'Consultando…':'Consultar empresa'}</button>{actor?.capabilities['tenants:write']&&<Link href="/tenants" prefetch={false} className={styles.button}><Building2 size={15} aria-hidden="true"/>Administrar empresas</Link>}{actor?.capabilities['users:manage']&&<Link href="/users" prefetch={false} className={styles.button}><Users size={15} aria-hidden="true"/>Equipo y permisos</Link>}</div>
  <p className={styles.source} role="status">{pending?'Consulta en curso; todavía no hay un resultado confirmado.':error|| (data?'Fuente: base operativa · '+when(data.observedAt)+' · actualización manual.':'Sin consultar.')}</p>
  <div className={styles.tabs} role="group" aria-label="Espacio de recepción">{[['reception','Recepción y seguimiento'],['roles','Roles y permisos'],['operations','Consola de operación']].map(([key,label])=><button type="button" key={key} aria-pressed={tab===key} className={styles.tab} onClick={()=>setTab(key as typeof tab)}>{label}</button>)}</div>
  <section hidden={tab!=='reception'}>
   <div className={styles.metrics}>{[['Etiquetas activas',inventory?.active],['Inactivas conservadas',inventory?.inactive],['Registros totales',inventory?.total],['Lotes de la empresa',inventory?.batches]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{typeof value==='number'?value.toLocaleString('es-AR'):'—'}</strong></div>)}</div>
   {!data?.tenant?<div className={styles.card}><h2>Primero, un alcance claro.</h2><p>Elegí la empresa a la que llegará el pedido. No se mezclan inventarios ni se interpreta el nombre de una empresa como una sesión demo.</p></div>:<>
    <div className={styles.card}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>{data.tenant.name}</p><h2>Pedidos de fábrica y rollos recibidos</h2><p>Hasta 10 pedidos recientes. Los estados son registros de la fuente; esta vista no aprueba ni activa etiquetas.</p></div>{actor?.capabilities['supplier_order.create']&&<button className={`${styles.button} ${styles.primary}`} type="button" onClick={()=>operate(null)}>Preparar pedido <ArrowRight size={15} aria-hidden="true"/></button>}</div>
     {data.orders.length?data.orders.map(order=><article key={order.id} className={styles.order}><div className={styles.sectionHead}><div><h3>{order.order_name||order.order_code||'Pedido registrado'}</h3><p>{order.effective_pack_purpose==='production'?'Producción: requiere aceptación de lote':order.effective_pack_purpose==='trial_integration'?'Integración: no habilita liberación comercial':'Propósito sin clasificar'} · {order.total_quantity} unidades declaradas</p></div><button className={styles.button} onClick={()=>operate(order)} type="button">Abrir operación del pedido</button></div><div className={styles.rolls}>{order.sub_batches.map(roll=><div key={roll.id} className={styles.roll}><strong>{roll.bid}</strong><p>{receptionNextStep(order,roll)}</p><dl><div><dt>Esperadas</dt><dd>{roll.expected_quantity??'—'}</dd></div><div><dt>Manifiesto</dt><dd>{roll.manifest_count??'—'} · {roll.manifest_status||'sin informar'}</dd></div><div><dt>QA declarado</dt><dd>{roll.qa_status||'sin informar'}</dd></div><div><dt>Activación</dt><dd>{roll.active_count??'—'} activas</dd></div></dl></div>)}</div>{!order.sub_batches.length&&<p className={styles.notice}>Sin rollos en esta respuesta. No se presume un pedido recibido.</p>}</article>):<p className={styles.notice}>No hay pedidos industriales registrados en esta consulta. Un lote existente y sus TAP físicos no equivalen a una recepción de fábrica auditada.</p>}
    </div>
    <div className={styles.card}><div className={styles.sectionHead}><div><h2>Etiquetas que ya usa esta empresa</h2><p>Hasta 20 lotes. Activas, inactivas e historial no son lo mismo; no reactivamos registros para completar un número.</p></div><Boxes size={22} aria-hidden="true"/></div><div className={styles.batchGrid}>{data.batches.map(batch=><article className={styles.batch} key={batch.id}><h3>{batch.bid}</h3><p><strong>{batch.active} activas</strong> · {batch.inactive} inactivas · {batch.total} registradas</p><span className={styles.badge}>{batch.supplier_order_id?'Pedido industrial vinculado':'Lote existente · sin pedido vinculado'}</span><p className={styles.small}>Última lectura registrada: {when(batch.last_seen_at)}. No certifica QA del rollo.</p>{canOpenDossier?<Link className={styles.button} prefetch={false} href={`/batches/${encodeURIComponent(batch.bid)}`}>Abrir expediente</Link>:<p className={styles.small}>El expediente completo requiere batches:read. Tu permiso de recepción se mantiene acotado a su tarea.</p>}</article>)}</div>{!data.batches.length&&<p>La fuente no encontró lotes de esta empresa.</p>}</div>
   </>}
  </section>
  <section hidden={tab!=='roles'} className={styles.card} data-testid="reception-role-matrix"><div className={styles.sectionHead}><div><h2>Qué puede hacer cada participante</h2><p>{preview?'Perfil estándar configurado. No representa a una cuenta concreta, no cambia tu sesión ni concede permisos.':'Permisos efectivos de la sesión autenticada, incluyendo restricciones del rol y denegaciones.'}</p></div><label className={styles.field}>Comparar responsabilidades<select value={profile} onChange={e=>setProfile(e.target.value)}><option value="current">Mi sesión actual</option>{data?.roleProfiles.map(r=><option value={r.role} key={r.role}>{ROLE_LABELS[r.role]||r.label} · perfil estándar</option>)}</select></label></div>
   <div className={styles.capabilities}>{Object.entries(RECEPTION_ACTION_LABELS).map(([key,label])=><div key={key}><span>{label}</span><strong data-allowed={Boolean(shown?.[key as ReceptionAction])}>{shown?shown[key as ReceptionAction]?'Permiso disponible':'No habilitado para este perfil':'Sin confirmar'}</strong></div>)}</div>
   <div className={styles.notice}><ShieldCheck size={17} aria-hidden="true"/><span>Marcá la diferencia al probar: el superadministrador gobierna NexID y puede ejecutar QA y solicitar activación; la aprobación del plan de calidad pertenece a la empresa cliente. Un permiso no reemplaza evidencia, otra firma requerida ni las condiciones de liberación.</span></div>
   <div className={styles.testGuide}><h3>Prueba de recepción con cuentas separadas</h3><p>Administrador de empresa: preparar el pedido y organizar el equipo. Operador de recepción: importar el manifiesto autorizado. Operaciones: completar QA y solicitar activación. Responsable del cliente: aprobar su plan. Consulta: sin mutaciones. El proveedor trabaja mediante el intercambio autorizado, no como superadministrador.</p><p>Para probar permisos reales, iniciá sesión con la cuenta correspondiente en otro perfil del navegador. Este comparador no cambia la cuenta ni la autoridad con la que estás operando.</p></div>
  </section>
  <section hidden={tab!=='operations'} id="supplier-order-console" className={`${styles.operations} scroll-mt-52 md:scroll-mt-24`}>
   {selection?<><p className={styles.notice}>Empresa fijada: <strong>{selection.tenant}</strong> · {selection.order?.order_name||'Pedido nuevo'} · Las acciones siguientes sí pueden guardar cambios y conservan sus controles del servidor.</p><SupplierOrderConsole key={`${selection.tenant}:${selection.order?.id||'new'}`} currentRole={access.role} currentPermissions={access.permissions} currentDeniedPermissions={access.deniedPermissions} tenantSlug={selection.tenant} initialOrder={selection.order||undefined}/><details className={styles.card}><summary>Ingreso legado y límites técnicos</summary><p>Las claves del lote se protegen mediante una clave maestra de aplicación guardada como secreto de Vercel. No es Google Cloud KMS ni HSM. Google Cloud KMS SOFTWARE queda reservado a custodia blockchain. No se envía cada TAP a blockchain.</p><SupplierLegacyIntakeBlocked/></details></>:<div className={styles.card}><h2>Seleccioná qué pedido vas a operar.</h2><p>La consola no inicia solicitudes, exporta claves ni modifica etiquetas al abrir esta pestaña. Elegí una empresa y un pedido desde Recepción y seguimiento.</p><button type="button" className={styles.button} onClick={()=>setTab('reception')}>Volver al recorrido</button></div>}
  </section>
 </main>;
}
