"use client";
import {useEffect,useRef,useState}from"react";
import{SupplierRequestError,type SupplierRequest}from"../lib/supplier-request-client";
import{supplierQuoteCall,type QuoteOperation,type QuoteSnapshot}from"../lib/supplier-request-quote-client";
import{parseQuoteCommand,quoteMinorFromText,quoteTotal,quoteMoney,QUOTE_CURRENCIES,type QuoteAction,type QuoteCommand,type QuoteEvent,type QuoteCurrency}from"../lib/supplier-quote-policy";
import type{SupplierRequestReviewGuard}from"./supplier-request-review";
import styles from"./supplier-request-workspace.module.css";
type Props={request:SupplierRequest;isNexid:boolean;suspended:boolean;canInteract:()=>boolean;onGuard:(value:SupplierRequestReviewGuard)=>void;onCurrent:(item:SupplierRequest)=>void;onAccessUnavailable:()=>void;onExit:()=>void};
type Form={currency:string;net:string;tax:string;shipping:string;validLocal:string;conditions:string;reason:string};
const blank=():Form=>({currency:'',net:'',tax:'',shipping:'',validLocal:'',conditions:'',reason:''});
const actionLabels:Record<QuoteAction,string>={issue:'Publicar cotización',accept:'Aceptar cotización',reject:'Rechazar cotización',withdraw:'Retirar cotización'};
const stateLabels={offered:'Pendiente de respuesta',accepted:'Aceptada por la empresa',rejected:'Rechazada por la empresa',withdrawn:'Retirada por NexID'};
const stamp=(value:string)=>value.slice(0,16).replace('T',' ')+' UTC';
function Offer({value}:{value:QuoteEvent}){return <dl className={styles.grid}><div><dt>Importe neto</dt><dd>{quoteMoney(value.net_minor,value.currency)}</dd></div><div><dt>Impuestos cotizados</dt><dd>{quoteMoney(value.tax_minor,value.currency)}</dd></div><div><dt>Envío cotizado</dt><dd>{quoteMoney(value.shipping_minor,value.currency)}</dd></div><div><dt>Total cotizado</dt><dd><strong>{quoteMoney(value.total_minor,value.currency)}</strong></dd></div><div><dt>Validez de la oferta</dt><dd>{stamp(value.valid_until)}</dd></div></dl>;}
export function SupplierRequestQuotation({request,isNexid,suspended,canInteract,onGuard,onCurrent,onAccessUnavailable,onExit}:Props){
 const [mode,setMode]=useState<'closed'|'loading'|'view'|'edit'|'confirm'|'saving'|'uncertain'|'error'|'denied'>('closed');
 const [snapshot,setSnapshot]=useState<QuoteSnapshot|null>(null),[history,setHistory]=useState<QuoteEvent[]>([]),[cursor,setCursor]=useState<number|null>(null),[error,setError]=useState('');
 const [form,setForm]=useState<Form>(blank),[action,setAction]=useState<QuoteAction>('issue'),[reviewed,setReviewed]=useState<QuoteCommand|null>(null),[receipt,setReceipt]=useState<QuoteSnapshot['receipt']>();
 const alive=useRef(true),epoch=useRef(0),busy=useRef(false),uncertain=useRef(false),active=useRef<AbortController|null>(null),operation=useRef<QuoteOperation|null>(null),editing=useRef(false),draft=useRef<Form>(blank()),loadedAt=useRef(0);
 const head=useRef<HTMLHeadingElement|null>(null),opener=useRef<HTMLButtonElement|null>(null),restoreFocus=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;epoch.current++;active.current?.abort();};},[]);
 useEffect(()=>{if(mode==='confirm')head.current?.focus({preventScroll:true});if(mode==='closed'&&restoreFocus.current){restoreFocus.current=false;opener.current?.focus();}},[mode]);
 const scope={id:request.id,tenant:request.tenant_slug,tenantId:request.tenant_id};
 const now=()=>snapshot?Date.parse(snapshot.as_of)+Math.max(0,performance.now()-loadedAt.current):Date.now();
 function allowed(kind:QuoteAction,s=snapshot){if(!s||!s.writes_enabled||s.request.status!=='submitted'||s.current?.state==='accepted')return false;
  if(kind==='issue')return isNexid&&s.request.review_summary?.state!=='needs_information';
  if(kind==='withdraw')return isNexid&&s.current?.state==='offered';
  if(isNexid||s.current?.state!=='offered')return false;
  return kind==='reject'||(s.request.review_summary?.state!=='needs_information'&&s.current.review_revision===s.request.review_summary?.revision&&Date.parse(s.current.valid_until)>now());
 }
 function close(){if(busy.current||uncertain.current)return;if(editing.current&&Object.values(draft.current).some(Boolean)&&!window.confirm('¿Descartar esta edición local y cerrar la cotización?'))return;
  epoch.current++;active.current?.abort();active.current=null;editing.current=false;draft.current=blank();setForm(blank());setReviewed(null);setError('');setMode('closed');restoreFocus.current=true;onGuard({dirty:false,locked:false});
 }
 async function load(older=false){
  if(busy.current||uncertain.current||active.current||!canInteract())return;
  const generation=++epoch.current,controller=new AbortController();active.current=controller;onGuard({dirty:editing.current,locked:true});setError('');if(!older)setMode('loading');
  try{
   const result=await supplierQuoteCall({...scope,before:older?cursor:null,signal:controller.signal});if(!alive.current||epoch.current!==generation)return;
   loadedAt.current=performance.now();
   if(older&&snapshot&&result.revision===snapshot.revision){const merged=[...result.history,...history].sort((a,b)=>a.revision-b.revision);const unique=[...new Map(merged.map(item=>[item.id,item])).values()];setHistory(unique);setCursor(result.next_before_revision);}else{setHistory(result.history);setCursor(result.next_before_revision);}
   setSnapshot(result);setMode(editing.current?'edit':'view');onGuard({dirty:editing.current,locked:editing.current});if(!editing.current)onCurrent(result.request);
  }catch(issue){if(!alive.current||epoch.current!==generation)return;const failure=issue instanceof SupplierRequestError?issue:new SupplierRequestError('supplier_quotes_unavailable');
   if([401,403,404].includes(failure.status)){setSnapshot(null);setHistory([]);setCursor(null);setMode('denied');onAccessUnavailable();setError('El acceso cambió. Se ocultó el contenido de la solicitud; no se registró ninguna cotización.');}
   else{setMode('error');setError('No se confirmó la cotización actual. El contenido local se conserva; no se emitió ni aceptó nada.');}
  }finally{if(active.current===controller)active.current=null;}
 }
 function start(kind:QuoteAction){if(!allowed(kind)||!canInteract()||active.current)return;setAction(kind);setForm(blank());draft.current=blank();editing.current=true;setReviewed(null);setReceipt(undefined);setError('');onGuard({dirty:true,locked:true});setMode('edit');}
 function edit(key:keyof Form,value:string){if(busy.current||uncertain.current)return;draft.current={...draft.current,[key]:value};setForm(draft.current);setReviewed(null);onGuard({dirty:true,locked:true});}
 function inspect(){if(!snapshot||!allowed(action)||!canInteract()||active.current)return;
  try{const f=draft.current;const offer=action==='issue'?{currency:f.currency as QuoteCurrency,net_minor:quoteMinorFromText(f.net),tax_minor:quoteMinorFromText(f.tax,true),shipping_minor:quoteMinorFromText(f.shipping,true),valid_until:new Date(f.validLocal).toISOString(),conditions:f.conditions}:null;
   const command=parseQuoteCommand({action,expected_revision:snapshot.revision,expected_request_revision:snapshot.request.revision,expected_review_revision:snapshot.request.review_summary!.revision,offer,reason:f.reason});
   if(offer&&(Date.parse(offer.valid_until)<=now()||Date.parse(offer.valid_until)>now()+90*86400000))throw Error();setReviewed(command);setError('');setMode('confirm');
  }catch{setError('Completá moneda, importes sin separador de miles (hasta dos decimales), validez futura de hasta 90 días, condiciones y motivo. Impuestos y envío requieren un importe explícito, incluso cero.');}
 }
 async function execute(command:QuoteOperation){
  if(busy.current||active.current||!canInteract())return;busy.current=true;operation.current=command;const controller=new AbortController(),generation=epoch.current;active.current=controller;setMode('saving');setError('');onGuard({dirty:true,locked:true});
  try{const result=await supplierQuoteCall({...scope,command,signal:controller.signal});if(!alive.current||epoch.current!==generation)return;
   uncertain.current=false;operation.current=null;editing.current=false;draft.current=blank();setForm(blank());setReviewed(null);setSnapshot(result);setHistory(result.history);setCursor(result.next_before_revision);loadedAt.current=performance.now();setReceipt(result.receipt);setMode('view');onGuard({dirty:false,locked:false});onCurrent(result.request);
  }catch(issue){if(!alive.current||epoch.current!==generation)return;const failure=issue instanceof SupplierRequestError?issue:new SupplierRequestError('supplier_quotes_unavailable',0,true);uncertain.current ||= failure.uncertain;
   if([401,403,404].includes(failure.status)){setSnapshot(null);setHistory([]);setCursor(null);onAccessUnavailable();}
   setMode(uncertain.current?'uncertain':[401,403,404].includes(failure.status)?'denied':'error');
   setError(uncertain.current?'El resultado sigue sin confirmar. Conservamos la misma operación; comprobarla no crea una nueva cotización ni una segunda decisión.':failure.status===409?'La oferta, solicitud o aclaración cambió, venció o no permite esta acción. Conservamos tu edición: consultá de nuevo y revisá antes de confirmar.':failure.code==='supplier_request_secret_content_rejected'?'Retirá llaves, tokens o secretos del motivo y las condiciones.':'No se pudo autorizar o registrar la operación. No se informó como completada.');if(!uncertain.current)operation.current=null;
  }finally{busy.current=false;if(active.current===controller)active.current=null;}
 }
 function confirm(){if(!reviewed||busy.current||uncertain.current||!canInteract())return;if(!allowed(reviewed.action)){setError('La cotización venció o ya no permite esta acción. Consultá la versión actual antes de confirmar.');setMode('error');return;}void execute(Object.freeze({key:crypto.randomUUID(),body:Object.freeze({...reviewed,offer:reviewed.offer?Object.freeze({...reviewed.offer}):null})}));}
 const current=snapshot?.current,expired=Boolean(current?.state==='offered'&&Date.parse(current.valid_until)<=now());
 if(mode==='closed')return <section className={styles.reviewPanel}><h3>Cotización comercial</h3><p className={styles.muted}>Propuestas versionadas de NexID y respuesta explícita de la empresa. Sin pagos ni órdenes automáticas.</p><button ref={opener} type="button" data-testid="quote-open" className={styles.button} disabled={suspended} onClick={()=>{if(!canInteract()){setError('Guardá o descartá las otras ediciones antes de abrir la cotización.');return;}void load();}}>Consultar cotización</button>{error?<p role="alert">{error}</p>:null}</section>;
 return <section className={styles.reviewPanel} data-testid="quote-panel" aria-labelledby="quote-heading" aria-busy={mode==='loading'||mode==='saving'}><h3 id="quote-heading">Cotización y respuesta de la empresa</h3>
  <p className={styles.notice}>Aceptar registra una decisión comercial sobre esta versión. No confirma pago, compra a fábrica, programación de etiquetas ni aprobación técnica.</p>
  {mode==='loading'||mode==='saving'?<p role="status">{mode==='loading'?'Consultando estado e historial…':'Registrando la operación…'}</p>:null}
  {error?<p role="alert" className={styles.error}>{error}</p>:null}
  {receipt?<p role="status" data-testid="quote-receipt" className={styles.notice}>Operación guardada · revisión {receipt.revision} · cotización v{receipt.quote_version}{snapshot&&snapshot.revision>receipt.revision?' · el estado actual es posterior al recibo recuperado.':''}</p>:null}
  {snapshot?<><p className={styles.muted}>Solicitud versión {snapshot.request.revision} · historial de cotización {snapshot.revision} · consulta {stamp(snapshot.as_of)}</p>{!snapshot.writes_enabled?<p role="status">Registro de nuevas operaciones desactivado. El historial permanece disponible.</p>:null}{snapshot.request.status!=='submitted'?<p role="status">Solicitud {snapshot.request.status==='cancelled'?'cancelada':'con pedido técnico preparado'}: sólo consulta.</p>:null}
   {current?<div data-testid="quote-current" className={styles.notice}><h4>Cotización v{current.quote_version} · {expired?'Oferta vencida':stateLabels[current.state]}</h4><Offer value={current}/>{current.state==='offered'&&current.review_revision!==snapshot.request.review_summary?.revision?<p role="status">La propuesta es anterior a nuevas aclaraciones. NexID debe publicar otra versión antes de que la empresa pueda aceptarla.</p>:null}<p className={styles.pre}>{current.conditions}</p><p className={styles.muted}>Los importes son declarados por NexID. No se calculan alícuotas ni conversiones de moneda.</p></div>:<p role="status">La fuente confirma que todavía no hay una cotización para esta solicitud.</p>}
  </>:null}
  {mode==='view'?<div className={styles.actions}>{(['issue','accept','reject','withdraw']as QuoteAction[]).filter(kind=>allowed(kind)).map(kind=><button key={kind} type="button" className={styles.button} data-testid={'quote-'+kind} onClick={()=>start(kind)}>{kind==='issue'&&current?'Preparar nueva versión':actionLabels[kind]}</button>)}<button type="button" className={styles.button} data-testid="quote-refresh" onClick={()=>void load()}>Actualizar cotización</button></div>:null}
  {mode==='edit'||mode==='error'&&editing.current?<div data-testid="quote-form"><h4>{actionLabels[action]}</h4>{action==='issue'?<><div className={styles.grid}><label>Moneda<select data-testid="quote-currency" value={form.currency} onChange={e=>edit('currency',e.target.value)}><option value="">Elegir moneda</option>{QUOTE_CURRENCIES.map(code=><option key={code} value={code}>{code}</option>)}</select></label><label>Importe neto<input data-testid="quote-net" inputMode="decimal" value={form.net} onChange={e=>edit('net',e.target.value)}/></label><label>Impuestos cotizados<input data-testid="quote-tax" inputMode="decimal" value={form.tax} onChange={e=>edit('tax',e.target.value)}/></label><label>Envío cotizado<input data-testid="quote-shipping" inputMode="decimal" value={form.shipping} onChange={e=>edit('shipping',e.target.value)}/></label><label>Vence (hora local)<input data-testid="quote-valid-until" type="datetime-local" value={form.validLocal} onChange={e=>edit('validLocal',e.target.value)}/></label></div><p className={styles.muted}>No uses separadores de miles. Indicá impuestos y envío manualmente; cero es válido. La confirmación mostrará el vencimiento en UTC.</p><label>Condiciones de la propuesta<textarea data-testid="quote-conditions" rows={4} maxLength={2000} value={form.conditions} onChange={e=>edit('conditions',e.target.value)}/></label></>:null}<label>{action==='accept'?'Comentario (opcional)':'Motivo de esta operación'}<textarea data-testid="quote-reason" rows={3} maxLength={2000} value={form.reason} onChange={e=>edit('reason',e.target.value)}/></label><p className={styles.muted}>El motivo y las condiciones son visibles para la empresa y NexID. No incluyas llaves ni secretos.</p>{mode==='edit'?<button type="button" className={styles.button} data-testid="quote-inspect" onClick={inspect}>Revisar antes de confirmar</button>:null}</div>:null}
  {mode==='confirm'&&reviewed&&snapshot?<div className={styles.review} data-testid="quote-confirmation"><h3 ref={head} tabIndex={-1}>{actionLabels[reviewed.action]} · confirmar</h3><p><strong>{snapshot.request.title}</strong><br/>Empresa: {snapshot.request.tenant_slug}<br/>Referencia: {snapshot.request.id}<br/>Cantidad solicitada: {snapshot.request.quantity}</p>
   {reviewed.offer?<><dl className={styles.grid}><div><dt>Neto</dt><dd>{quoteMoney(reviewed.offer.net_minor,reviewed.offer.currency)}</dd></div><div><dt>Impuestos</dt><dd>{quoteMoney(reviewed.offer.tax_minor,reviewed.offer.currency)}</dd></div><div><dt>Envío</dt><dd>{quoteMoney(reviewed.offer.shipping_minor,reviewed.offer.currency)}</dd></div><div><dt>Total de esta propuesta</dt><dd><strong>{quoteMoney(quoteTotal(reviewed.offer),reviewed.offer.currency)}</strong></dd></div><div><dt>Vencimiento</dt><dd>{stamp(reviewed.offer.valid_until)}</dd></div></dl><p className={styles.pre}>{reviewed.offer.conditions}</p></>:current?<><p>Cotización v{current.quote_version}</p><Offer value={current}/></>:null}
   <p className={styles.pre}>{reviewed.reason||'Sin comentario adicional.'}</p><p>Quedarán registrados responsable, fecha y versión. No se reescribe una propuesta anterior.</p><div className={styles.actions}><button type="button" className={styles.primary} data-testid="quote-confirm" onClick={confirm}>Confirmar {reviewed.action==='issue'?'publicación':reviewed.action==='accept'?'aceptación':reviewed.action==='reject'?'rechazo':'retiro'}</button><button type="button" className={styles.button} onClick={()=>setMode('edit')}>Volver a editar</button></div></div>:null}
  {mode==='error'?<button type="button" className={styles.button} data-testid="quote-reload" onClick={()=>void load()}>Consultar versión actual</button>:null}
  {mode==='uncertain'?<><button type="button" className={styles.button} data-testid="quote-retry" onClick={()=>{if(operation.current)void execute(operation.current);}}>Comprobar la misma operación</button><button type="button" className={styles.button} data-testid="quote-exit-uncertain" onClick={()=>{if(busy.current||!window.confirm('¿Salir con el resultado sin confirmar? Salir no revierte ni reenvía esta operación. Consultá el expediente antes de intentar otra vez.'))return;uncertain.current=false;operation.current=null;onGuard({dirty:false,locked:false});onExit();}}>Salir con resultado sin confirmar</button></>:null}
  {mode==='denied'?<button type="button" className={styles.button} onClick={()=>{onGuard({dirty:false,locked:false});onExit();}}>Cerrar consulta sin acceso</button>:null}
  {snapshot&&history.length?<details className={styles.commercial} data-testid="quote-history"><summary>Historial de cotizaciones y decisiones ({history.length} registros cargados)</summary><ol>{history.map(item=><li key={item.id}><strong>v{item.quote_version} · {actionLabels[item.action]} · revisión {item.revision}</strong><p>{stamp(item.created_at)} · {quoteMoney(item.total_minor,item.currency)}<br/>Responsable (ID): {item.actor_id}<br/>Aclaraciones consultadas: revisión {item.review_revision}</p><p className={styles.pre}>{item.reason}</p><details><summary>Ver importes y condiciones de esta versión</summary><Offer value={item}/><p className={styles.pre}>{item.conditions}</p></details></li>)}</ol>{cursor?<button className={styles.button} type="button" data-testid="quote-older" disabled={mode!=='view'} onClick={()=>void load(true)}>Cargar historial anterior</button>:null}</details>:null}
  {!['saving','uncertain','denied'].includes(mode)?<button type="button" className={styles.button} data-testid="quote-close" onClick={close}>Cerrar sin enviar otra operación</button>:null}
 </section>;
}
