import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {parseBatchTrace,traceSummary,traceTimeline,readTraceJson} from '../src/lib/batch-traceability.ts';import {traceExports} from '../src/lib/batch-traceability-export.ts';
const BID='LOT-QA',B='10000000-0000-4000-8000-000000000001',E='20000000-0000-4000-8000-000000000001',I='30000000-0000-4000-8000-000000000001';
const make=()=>({ok:true,protocol:'nexid.batch-traceability.v1',source:'database',observedAt:'2026-09-19T12:00:00Z',scope:{tenant:'company-qa',tenantName:'QA',bid:BID,batchId:B},product:{name:'Producto QA',carrier:'gs1_digital_link',status:'active'},window:{from:'2026-09-01',to:'2026-09-19',start:'2026-09-01T00:00:00.000Z',endExclusive:'2026-09-20T00:00:00.000Z',timezone:'UTC'},events:[{id:E,kind:'epcis',type:'AggregationEvent',action:'DELETE',occurredAt:'2026-09-10T12:00:00Z',recordedAt:'2026-09-19T12:00:00Z',step:'unpacking',disposition:'in_progress',readPoint:null,location:null,correctionDeclared:true,references:[{id:I,bid:BID,batchId:B,gtin:'09506000134352',lot:'L1',serial:'S1',role:'child',quantity:null,uom:null,focus:true}],omittedReferences:0,basis:'external_declaration'}],custody:[],shipments:[],hasMore:{events:false,custody:false,shipments:false},logisticsAccess:'restricted',limits:{events:50,shipments:20,custody:50,referencesPerEvent:100,days:93},readOnly:true,relationshipMode:'historical_events_not_current_containment'});
const parse=r=>parseBatchTrace(r,BID,'company-qa');
test('contract requires exact requested scope and trustworthy provenance',()=>{const r=parse(make());assert.equal(r.scope.bid,BID);for(const patch of [{source:'demo'},{readOnly:false},{relationshipMode:'current_position'}])assert.throws(()=>parse({...make(),...patch}));assert.throws(()=>parseBatchTrace(make(),BID,'another-tenant'));});
test('time window and hidden logistics scope cannot be smuggled into the response',()=>{const r=make();r.events[0].occurredAt='2026-08-31T12:00:00Z';assert.throws(()=>parse(r));const q=make();q.hasMore.shipments=true;assert.throws(()=>parse(q));assert.throws(()=>parseBatchTrace(make(),BID,'company-qa',{from:'2026-08-01',to:'2026-08-20'}));});
test('known references are projected without forwarding arbitrary extra payload fields',()=>{const raw=make();raw.events[0].private='DO_NOT_EXPORT';raw.product.rawKey='DO_NOT_EXPORT';const r=parse(raw);assert.doesNotMatch(JSON.stringify(r),/DO_NOT_EXPORT/);const clone=make();clone.events[0].references[0].focus=false;assert.throws(()=>parse(clone));});
test('filters search only loaded data and never infer current relations',()=>{const data=parse(make());assert.equal(traceTimeline(data,'relationships','S1').length,1);assert.equal(traceTimeline(data,'custody','').length,0);assert.deepEqual(traceSummary(data),{epcis:1,custody:0,relationships:1,identities:1});assert.equal(data.events[0].action,'DELETE');});
test('response size and duplicate event rows are rejected rather than counted twice',async()=>{const r=make();r.events.push(r.events[0]);assert.throws(()=>parse(r));await assert.rejects(()=>readTraceJson(new Response('x'.repeat(1048577))));});
test('HTML and JSON share the same read snapshot, escape text and do not run scripts',async()=>{const d=parse(make());d.product.name='<script>alert(1)</script>';const out=await traceExports(d);const json=JSON.parse(out.json);assert.equal(json.sha256,createHash('sha256').update(JSON.stringify(d)).digest('hex'));assert.match(out.html,/&lt;script&gt;/);assert.doesNotMatch(out.html,/<script|<iframe|<img|src=/i);assert.match(out.html,/no autenticidad|autenticidad NFC/);assert.match(out.html,/No incluida: el rol/);});
test('read page and BFF keep session and permission gates',async()=>{const page=await readFile(new URL('../src/app/(app)/batches/[bid]/traceability/page.tsx',import.meta.url),'utf8'),policy=await readFile(new URL('../src/lib/permission-policy.ts',import.meta.url),'utf8');assert.match(page,/requireDashboardSession\('batches:read'\)/);assert.match(page,/!session.isDemo/);assert.match(policy,/traceability/);});
test('UI explicitly refreshes and invalidates data; no polling or invisible writes',async()=>{const s=await readFile(new URL('../src/components/batch-traceability-workspace.tsx',import.meta.url),'utf8');assert.match(s,/setPage\(null\)/);assert.match(s,/flight.current\?\.abort/);assert.match(s,/reduced-motion/);assert.doesNotMatch(s,/setInterval|localStorage|sessionStorage|method:.*POST|navigator.geolocation/);});

import {traceRequestScopeAllowed} from '../src/lib/batch-traceability-access.ts';
test('explicit cross-company requests are rejected before BFF tenant rewriting',async()=>{assert.equal(traceRequestScopeAllowed({role:'tenant-admin',tenantSlug:'a'},'b'),false);assert.equal(traceRequestScopeAllowed({role:'tenant-admin',tenantSlug:'a'},'a'),true);assert.equal(traceRequestScopeAllowed({role:'super-admin'},'b'),true);assert.equal(traceRequestScopeAllowed({role:'super-admin',isDemo:true},'b'),false);const s=await readFile(new URL('../src/app/api/admin/[...path]/route.ts',import.meta.url),'utf8');assert.ok(s.indexOf('trace_tenant_forbidden')<s.indexOf('const tenantScope = resolveDashboardTenantScope'));});
