import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';
import {parseBatchWorkRows,filterBatchWorkRows,batchWorkHref} from '../src/lib/batch-workbench.ts';
const raw=()=>({id:'20000000-0000-4000-8000-000000000001',bid:'LOT-QA-01',tenant_slug:'tenant-qa',product_name:'Producto QA',sku:'SKU-QA',winery:'Empresa QA',status:'active',quantity:20,active_tags:10,inactive_tags:10,revoked_tags:0,editorial_managed:false,requested_quantity:null});
test('active and historical inactive tags remain distinct',()=>{const [r]=parseBatchWorkRows([raw()],'tenant-qa');assert.equal(r.active,10);assert.equal(r.inactive,10);assert.equal(r.quantity,20);assert.equal(r.expected,null);});
test('one client cannot receive rows from another company',()=>{assert.throws(()=>parseBatchWorkRows([raw()],'other-tenant'));assert.throws(()=>parseBatchWorkRows([raw(),raw()],''));});
test('malformed or contradictory counts do not become zero inventory',()=>{for(const patch of [{quantity:null},{active_tags:21},{inactive_tags:-1},{quantity:'20'}])assert.throws(()=>parseBatchWorkRows([{...raw(),...patch}],''));assert.throws(()=>parseBatchWorkRows({ok:true},''));});
test('search and task filtering only operate on confirmed rows',()=>{const rows=parseBatchWorkRows([raw()],'');assert.equal(filterBatchWorkRows(rows,{query:'sku-qa',tenant:'',state:'all'}).length,1);assert.equal(filterBatchWorkRows(rows,{query:'',tenant:'',state:'awaiting-units'}).length,0);assert.equal(filterBatchWorkRows(rows,{query:'unrelated',tenant:'',state:'all'}).length,0);});
test('actions preserve company and open the actual editor/receiver',()=>{const [row]=parseBatchWorkRows([raw()],'');assert.equal(batchWorkHref(row,'product'),'/batches/LOT-QA-01?tenant=tenant-qa#dossier-product');assert.equal(batchWorkHref(row,'units'),'/batches/LOT-QA-01?tenant=tenant-qa#dossier-units');assert.equal(batchWorkHref({...row,editorial:true},'product'),'/batches/LOT-QA-01/passport?tenant=tenant-qa');});
test('list renders no sales dashboard and makes only its necessary bounded read',async()=>{const page=await readFile(new URL('../src/app/(app)/batches/page.tsx',import.meta.url),'utf8');assert.doesNotMatch(page,/product-assets|ModuleAudienceHero|OpsCommandCenter|BALMEC|DEMO-2026-02/);assert.match(page,/AbortSignal.timeout\(12000\)/);assert.match(page,/batches-access-denied/);assert.doesNotMatch(page,/requireDashboardSession\("batches:read"\)/);const ui=await readFile(new URL('../src/components/batch-workbench.tsx',import.meta.url),'utf8');assert.doesNotMatch(ui,/fetch\(|setInterval|localStorage/);assert.match(ui,/batches-source-unavailable/);assert.match(ui,/Configurar producto/);});
