// Full project UI/BFF with actual registry/query code on disposable PostgreSQL; no customer writes.
import assert from 'node:assert/strict';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3147',api='http://127.0.0.1:4198',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,realPostgres:true,realRegistry:true,visual:[],checks:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json();
async function open(bid,role='editor',width=1440){const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce',serviceWorkers:'block'});await context.addCookies([{name:'nexid_dashboard_session',value:'local-channels-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await page.goto(base+'/batches/'+bid+'/channels',{waitUntil:'load',timeout:90000});await page.getByRole('heading',{name:'Producto '+bid,exact:true}).waitFor();return {context,page,errors};}
try{
 const original=await state();const tt=await open('TT-LOCAL');await tt.page.getByRole('heading',{name:'TagTamper conservado',exact:true}).waitFor();assert.equal(await tt.page.getByRole('button',{name:/Generar QR/}).count(),0);assert.match(await tt.page.getByTestId('batch-channels').innerText(),/4343/);assert.match(await tt.page.getByTestId('batch-channels').innerText(),/4F4F, 4F43/);await tt.context.close();report.checks.push('TT does not generate static proof or change config');
 const qr=await open('QR-LOCAL');await qr.page.getByRole('button',{name:'Generar QR descargable',exact:true}).click();await qr.page.getByRole('img',{name:'Código QR de la identidad registrada'}).waitFor();assert.ok(await qr.page.getByRole('img',{name:'Código QR de la identidad registrada'}).evaluate(i=>i.complete&&i.naturalWidth>0));const url=await qr.page.getByRole('link',{name:'Abrir enlace público',exact:true}).getAttribute('href');assert.equal(new URL(url).searchParams.get('carrier'),'qr_basic');assert.equal(new URL(url).searchParams.get('bid'),'QR-LOCAL');await qr.context.close();report.checks.push('QR source is a ready registered batch');
 const gs=await open('GS1-LOCAL');const p=gs.page;await p.getByRole('textbox',{name:'GTIN · 14 dígitos',exact:true}).fill('09506000134352');await p.getByRole('textbox',{name:'Lote GS1 · opcional',exact:true}).fill('TEST-L1');await p.getByRole('textbox',{name:'Serie · opcional',exact:true}).fill('TEST-S1');await p.getByRole('checkbox').check();await fetch(api+'/qa-lose-next',{method:'POST'});await p.getByRole('button',{name:'Registrar identidad GS1',exact:true}).click();await p.getByRole('button',{name:'Reconciliar la misma identidad',exact:true}).waitFor();assert.equal((await state()).identities,1);await p.getByRole('button',{name:'Reconciliar la misma identidad',exact:true}).click();await p.getByRole('status').filter({hasText:'no se duplicó'}).waitFor();assert.equal((await state()).identities,1);report.checks.push('lost write response reconciles original registry identity');
 await p.getByRole('button',{name:'Generar QR',exact:true}).waitFor();await p.getByRole('button',{name:'Generar QR',exact:true}).click();await p.getByRole('img',{name:'Código QR de la identidad registrada'}).waitFor();const publicUrl=await p.getByRole('link',{name:'Abrir enlace público',exact:true}).getAttribute('href');assert.equal(publicUrl,'https://nexid.lat/01/09506000134352/10/TEST-L1/21/TEST-S1');const resolved=await(await fetch(api+'/public/gs1/resolve?gtin=09506000134352&lot=TEST-L1&serial=TEST-S1')).json();assert.equal(resolved.registry.bid,'GS1-LOCAL');assert.equal(resolved.registry.tenantSlug,'channels-qa');report.checks.push('actual persisted GS1 registry resolves correct tenant and batch');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1000});await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Page overflow');await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('[data-testid="batch-channels"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`channels-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}assert.deepEqual(gs.errors,[]);await gs.context.close();
 const viewer=await open('GS1-LOCAL','viewer',390);assert.equal(await viewer.page.getByRole('button',{name:'Registrar identidad GS1'}).isDisabled(),true);await viewer.context.close();const denied=await fetch(api+'/admin/batches/GS1-LOCAL/channels?tenant=another-tenant',{headers:{Authorization:'Bearer local-channels-editor'}});assert.equal(denied.status,403);report.checks.push('viewer cannot register and cross-tenant lookup is refused');
 const finished=await state();assert.deepEqual(finished.batches,original.batches);report.checks.push('all TT QR GS1 batch configurations remain byte-for-byte unchanged');report.status='passed';
}catch(error){report.status='failed';report.error=error.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=await p.locator('body').innerText();await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw error;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
