import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3211',api='http://127.0.0.1:4311',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,realReadHandlers:true,realPostgres:true,checks:[],visual:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json();
async function open(role='reader'){const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',serviceWorkers:'block',acceptDownloads:true});await context.addCookies([{name:'nexid_dashboard_session',value:'qa-trace-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await context.newPage(),errors=[],writes=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(['POST','PATCH','DELETE'].includes(r.method())&&r.url().includes('/api/admin/'))writes.push(r.url());});await p.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());return {p,context,errors,writes};}
try{
 await fetch(api+'/qa-mode');const user=await open(),p=user.p;await p.goto(base+'/batches/GS1-LOCAL/traceability?from=2026-09-18&to=2026-09-20',{waitUntil:'load',timeout:90000});await p.getByRole('heading',{name:'Trazabilidad del lote',exact:true}).waitFor();await p.getByRole('main').getByText('Producto GS1-LOCAL',{exact:false}).waitFor();
 const start=(await state()).calls.length;await p.getByRole('button',{name:'Envíos vinculados',exact:true}).click();await p.getByRole('heading',{name:'SHIP-TRACE-QA',exact:true}).waitFor();assert.match(await p.getByRole('link',{name:'Abrir envío y custodia',exact:false}).getAttribute('href'),/tenant=channels-qa/);await p.getByRole('button',{name:'Cronología y relaciones',exact:true}).click();assert.equal((await state()).calls.length,start);report.checks.push('One scoped query populates timeline and seal-linked shipments; tab switching adds no reads');
 await p.getByRole('button',{name:/Vinculación declarada/}).click();const detail=p.getByTestId('trace-event-detail');await detail.getByRole('heading',{name:'Elemento padre',exact:true}).waitFor();assert.match(await detail.innerText(),/BOX-001/);assert.match(await detail.innerText(),/UNIT-001/);assert.ok(!(await detail.innerText()).includes('PRIVATE_'));report.checks.push('Selected aggregation resolves registered parent and child with source time and record time kept distinct');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1000});await p.evaluate(t=>{document.documentElement.dataset.theme=t;document.documentElement.classList.toggle('theme-light',t==='light');document.documentElement.classList.toggle('theme-dark',t==='dark');window.scrollTo(0,0);},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('[data-testid="batch-trace-workspace"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`trace-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}
 const countBeforeEvidence=(await state()).calls.length;const [evidenceFile]=await Promise.all([p.waitForEvent('download'),detail.getByRole('button',{name:'Descargar evidencia del evento',exact:true}).click()]);await evidenceFile.saveAs(join(out,'event-evidence.json'));const evidence=JSON.parse(await readFile(join(out,'event-evidence.json'),'utf8'));assert.equal(evidence.interpretation,'selected_event_only');assert.equal(evidence.identities.length,2);assert.equal((await state()).calls.length,countBeforeEvidence);report.checks.push('Selected-event evidence exports its exact scoped roles and references without another query');
 const beforeExport=(await state()).calls.length;for(const [label,name] of [['Informe HTML','trace.html'],['CSV','trace.csv'],['JSON','trace.json']]){const [dl]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:label,exact:true}).click()]);await dl.saveAs(join(out,name));}assert.equal((await state()).calls.length,beforeExport);const reportData=JSON.parse(await readFile(join(out,'trace.json'),'utf8'));assert.equal(reportData.events.length,6);assert.equal(reportData.scope.tenant,'channels-qa');assert.ok(!(await readFile(join(out,'trace.html'),'utf8')).includes('<script'));report.checks.push('HTML CSV and JSON export the same query snapshot without extra database reads');
 await detail.getByRole('link',{name:'Seguir en BOX-LOCAL',exact:false}).click();await p.getByRole('main').getByText('Agrupación de prueba',{exact:false}).waitFor();await p.getByRole('button',{name:/Vinculación declarada/}).first().click();await p.getByTestId('trace-event-detail').getByText('Serie PALLET-001',{exact:false}).waitFor();report.checks.push('Following the registered parent navigates to its lot and reveals its own pallet relation');
 await p.goto(base+'/batches/GS1-LOCAL/traceability?from=2026-09-18&to=2026-09-20',{waitUntil:'load'});await p.getByRole('button',{name:/Desvinculación declarada/}).click();await p.getByTestId('trace-event-detail').getByText('La desvinculación es una declaración histórica.',{exact:false}).waitFor();await p.getByRole('button',{name:/Entradas y salidas declaradas/}).click();await p.getByTestId('trace-event-detail').getByRole('heading',{name:'Entradas',exact:true}).waitFor();await p.getByTestId('trace-event-detail').getByRole('heading',{name:'Salidas',exact:true}).waitFor();report.checks.push('Disaggregation and transformation are distinguished, without fabricating present containment');
 await p.getByRole('button',{name:/Declarado en error/}).click();await p.getByTestId('trace-event-detail').getByText('El origen declaró este evento en error.',{exact:false}).waitFor();report.checks.push('Erroneous source event retains its warning in the selected evidence');
 await p.getByLabel('Desde · UTC',{exact:true}).fill('2026-09-17');assert.equal(await p.getByRole('button',{name:'Informe HTML',exact:true}).isDisabled(),true);await p.getByRole('button',{name:'Consultar trazabilidad',exact:true}).click();await p.getByRole('main').getByText('Fuente: base operativa',{exact:false}).waitFor();report.checks.push('Edited filters disable exports until a new query is confirmed');
 await fetch(api+'/qa-mode?state=unavailable');await p.getByRole('button',{name:'Consultar trazabilidad',exact:true}).click();await p.getByText('No se pudo consultar la trazabilidad.',{exact:false}).waitFor();assert.equal(await p.getByRole('button',{name:'Informe HTML',exact:true}).count(),0);assert.equal(await p.getByTestId('trace-event-detail').count(),0);await fetch(api+'/qa-mode');report.checks.push('Source failure clears prior result and detail rather than presenting false zero data');
 const viewer=await open('viewer');const forbidden=await viewer.context.request.get(base+'/api/admin/batches/GS1-LOCAL/traceability?from=2026-09-18&to=2026-09-20');assert.equal(forbidden.status(),403);const cross=await user.context.request.get(base+'/api/admin/batches/GS1-LOCAL/traceability?tenant=other-qa');assert.equal(cross.status(),200);assert.equal((await cross.json()).scope.tenant,'channels-qa');await viewer.context.close();report.checks.push('Existing viewer and tenant boundaries are enforced by the live request path');
 assert.equal((await state()).unchanged,true);assert.deepEqual(user.errors,[]);assert.deepEqual(user.writes,[]);report.checks.push('No business mutation or tag configuration change occurred');await user.context.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,10000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
