import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const base='http://localhost:3215',api='http://127.0.0.1:4315',out=process.env.QA_OUTPUT;
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,realReadHandler:true,realPostgres:true,checks:[],visual:[]};
const calls=async()=>((await(await fetch(api+'/qa-state')).json()).calls).length;
async function open(role){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'es-AR',serviceWorkers:'block',reducedMotion:'reduce',acceptDownloads:true});if(role)await context.addCookies([{name:'nexid_dashboard_session',value:'qa-trace-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage(),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(['POST','PATCH','DELETE'].includes(r.method())&&r.url().includes('/api/admin/'))writes.push(r.url());});await page.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());return {context,page,errors,writes};}
const path='/batches/GS1-LOCAL/traceability?tenant=channels-qa&from=2026-09-01&to=2026-09-19';
try{
 await fetch(api+'/qa-mode?fail=0',{method:'POST'});const item=await open('editor'),p=item.page;await p.goto(base+path,{waitUntil:'load',timeout:90000});await p.getByRole('heading',{name:'Recorrido del lote',exact:true}).waitFor();const root=p.getByTestId('batch-traceability'),detail=p.getByRole('region',{name:'Detalle del movimiento',exact:true});assert.equal(await p.getByRole('button',{name:/^Abrir .* UTC$/}).count(),8);
 const before=await calls();await p.getByRole('button',{name:'Relaciones por evento',exact:true}).click();assert.equal(await p.getByRole('button',{name:/^Abrir .* UTC$/}).count(),4);await p.getByRole('button',{name:/^Abrir Agrupación de unidades/}).first().click();await detail.getByText('Retiro o separación declarados',{exact:true}).waitFor();assert.match(await detail.innerText(),/corrección/);assert.match(await detail.innerText(),/PACK-LOCAL/);assert.match(await detail.innerText(),/GS1-LOCAL/);report.checks.push('History distinguishes ADD OBSERVE DELETE and correction, with parent and child references');
 await p.getByRole('button',{name:/^Abrir Transformación/}).click();assert.match(await detail.innerText(),/Entradas declaradas/);assert.match(await detail.innerText(),/Salidas declaradas/);await p.getByRole('button',{name:'Envíos vinculados',exact:true}).click();await p.getByRole('heading',{name:'SHIP-LOCAL-01'}).waitFor();assert.match(await root.innerText(),/Estado actual del flujo/);assert.equal(await p.getByRole('link',{name:'Abrir envío'}).count(),1);assert.equal(await calls(),before);report.checks.push('Relationship selection and linked shipments navigate locally without further database calls');
 await p.getByRole('button',{name:'Recorrido',exact:true}).click();await p.getByRole('searchbox',{name:'Buscar GTIN, serie, lote o envío'}).fill('UNIT-02');assert.equal(await p.getByRole('button',{name:/^Abrir .* UTC$/}).count(),1);assert.match(await detail.innerText(),/2.5/);assert.match(await detail.innerText(),/KGM/);await p.getByRole('searchbox',{name:'Buscar GTIN, serie, lote o envío'}).fill('');assert.equal(await calls(),before);report.checks.push('Local search preserves quantity units and does not invent item counts');
 const [download]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Evidencia JSON',exact:true}).click()]);await download.saveAs(join(out,'trace.json'));const file=JSON.parse(await readFile(join(out,'trace.json'),'utf8'));assert.equal(file.sha256,createHash('sha256').update(JSON.stringify(file.data)).digest('hex'));assert.equal(file.data.events.length,7);assert.equal(file.data.custody.length,1);assert.doesNotMatch(JSON.stringify(file),/PRIVATE_|SYNTHETIC_/);
 const [print]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Informe HTML',exact:true}).click()]);await print.saveAs(join(out,'trace.html'));const html=await readFile(join(out,'trace.html'),'utf8');assert.ok(html.includes(file.sha256));assert.doesNotMatch(html,/<script|<iframe|src=/);assert.equal(await calls(),before);const rendered=await item.context.newPage();let external=0;await rendered.route('**/*',r=>{external++;return r.abort();});await rendered.setContent(html);assert.equal(await rendered.locator('table').count(),3);assert.equal(external,0);await rendered.screenshot({path:join(out,'export.png'),fullPage:true});await rendered.close();report.checks.push('HTML and JSON export one confirmed snapshot without network, script execution or secret fields');
 await p.getByRole('button',{name:'Relaciones por evento',exact:true}).click();await p.getByRole('button',{name:/^Abrir Agrupación de unidades/}).first().click();
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1000});await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');window.scrollTo(0,0);},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow');await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const result=await axe.run('[data-testid="batch-traceability"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return result.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`trace-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}
 await p.getByLabel('Desde UTC',{exact:true}).fill('2026-09-02');assert.equal(await p.getByRole('button',{name:'Informe HTML',exact:true}).isDisabled(),true);await p.getByLabel('Hasta UTC',{exact:true}).fill('2026-09-02');await p.getByRole('button',{name:'Consultar recorrido',exact:true}).click();await p.getByRole('status').filter({hasText:'consultado'}).waitFor();assert.equal(await p.getByRole('button',{name:/^Abrir .* UTC$/}).count(),1);report.checks.push('Changing dates invalidates the prior dataset and exports until the new read completes');
 await fetch(api+'/qa-mode?fail=1',{method:'POST'});await p.getByRole('button',{name:'Consultar recorrido',exact:true}).click();await p.getByRole('status').filter({hasText:'No se pudo confirmar'}).waitFor();assert.equal(await p.getByRole('button',{name:'Evidencia JSON'}).isDisabled(),true);assert.equal(await p.getByRole('button',{name:/^Abrir .* UTC$/}).count(),0);await fetch(api+'/qa-mode?fail=0',{method:'POST'});report.checks.push('Source failure is not converted to zero movement or stale data');
 const reader=await open('reader');await reader.page.goto(base+path,{waitUntil:'load'});await reader.page.getByRole('heading',{name:'Recorrido del lote',exact:true}).waitFor();await reader.page.getByRole('button',{name:'Envíos vinculados',exact:true}).click();assert.match(await reader.page.locator('[data-testid="batch-traceability"]:visible').innerText(),/no tiene permiso/);assert.equal(await reader.page.getByRole('link',{name:'Abrir envío'}).count(),0);assert.equal((await reader.context.request.get(base+'/api/admin/batches/GS1-LOCAL/traceability?tenant=other-qa')).status(),403);report.checks.push('Product-only reader cannot access or count logistics and cross-tenant queries are rejected');await reader.context.close();
 assert.deepEqual(item.errors,[]);assert.deepEqual(item.writes,[]);await item.context.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const page=browser.contexts().at(-1)?.pages().at(-1);if(page){report.visible=(await page.locator('body').innerText()).slice(0,10000);await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
