import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3432',api='http://127.0.0.1:4532',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH}),report={localOnly:true,realPostgres:true,realQueueHandler:true,existingEditorialService:true,checks:[],visual:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json();const root=p=>p.locator('[data-testid="editorial-queue"]:visible');
async function open(role='editor',path='/passports/review'){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'es-AR',reducedMotion:'reduce',serviceWorkers:'block',permissions:['clipboard-read','clipboard-write']});await context.addCookies([{name:'nexid_dashboard_session',value:'queue-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await context.newPage(),errors=[],writes=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(['POST','PATCH','DELETE'].includes(r.method())&&r.url().includes('/api/admin/'))writes.push(new URL(r.url()).pathname);});await p.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await p.goto(base+path,{waitUntil:'load',timeout:90000});await root(p).getByRole('heading',{name:'Bandeja editorial',exact:true}).waitFor();return {context,p,errors,writes};}
async function loaded(p,matched){await root(p).getByRole('status').filter({hasText:matched+' coincidencias.'}).waitFor();}
async function submit(p){await root(p).getByRole('button',{name:'Consultar bandeja',exact:true}).click();}
try{
 await fetch(api+'/qa-mode',{method:'POST'});const editor=await open(),p=editor.p;await loaded(p,35);assert.equal(await root(p).getByRole('button',{name:/Ver próximo paso de/}).count(),25);const before=await state();await root(p).getByRole('button',{name:/Ver próximo paso de/}).nth(2).click();assert.equal((await state()).calls.length,before.calls.length);assert.equal((await state()).history,before.history);report.checks.push('Overview counts are backed by enrolled passports and selecting a row is read-only without another query');
 await root(p).getByRole('button',{name:'Página siguiente',exact:true}).click();await root(p).getByText('Página 2 · 10 pasaportes visibles',{exact:true}).waitFor();assert.equal(await root(p).getByRole('button',{name:/Ver próximo paso de/}).count(),10);await root(p).getByRole('button',{name:'Página anterior',exact:true}).click();await root(p).getByText('Página 1 · 25 pasaportes visibles',{exact:true}).waitFor();report.checks.push('Next and previous pages reach all 35 enrolled passports without duplicate rows in the unchanged fixture');
 await root(p).getByRole('combobox',{name:'Estado editorial',exact:true}).selectOption('changes_requested');assert.equal(await root(p).getByRole('button',{name:/Ver próximo paso de/}).count(),0);await submit(p);await loaded(p,1);await root(p).getByRole('heading',{name:'Corrección solicitada',exact:true}).waitFor();assert.match(await root(p).getByRole('region',{name:'Próximo paso del pasaporte'}).innerText(),/Confirmar la ficha técnica/);assert.equal(await root(p).locator('script').count(),0);assert.equal((await state()).history,before.history);
 const target=await root(p).getByRole('link',{name:'Abrir Passport Studio',exact:false}).getAttribute('href');assert.equal(target,'/batches/CORRECTION/passport?tenant=queue-qa');await root(p).getByRole('button',{name:'Copiar búsqueda',exact:true}).click();const copied=await p.evaluate(()=>navigator.clipboard.readText());assert.match(copied,/state=changes_requested/);assert.ok(!copied.includes('cursor')&&!copied.includes('session'));report.checks.push('Correction comments render as text; workflow links and reusable filtered searches retain the correct company without granting permissions');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1000});await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');window.scrollTo(0,0);},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('[data-testid="editorial-queue"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`queue-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['critical','serious'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}
 const reviewer=await open('reviewer','/passports/review?view=mine');await loaded(reviewer.p,2);assert.equal(await root(reviewer.p).getByRole('link',{name:'Revisar contenido',exact:false}).count(),2);const own=await open('self','/passports/review?state=in_review');await loaded(own.p,2);await root(own.p).getByRole('button',{name:'Ver próximo paso de Producto REVIEW-SELF',exact:true}).click();assert.match(await root(own.p).getByRole('region',{name:'Próximo paso del pasaporte'}).innerText(),/Participaste en este contenido/);report.checks.push('Reviewer workload and author involvement are distinguished without silently granting self-approval');
 await fetch(api+'/qa-approve',{method:'POST'});await submit(reviewer.p);await loaded(reviewer.p,1);const publisher=await open('publisher','/passports/review?view=mine');await loaded(publisher.p,2);assert.equal(await root(publisher.p).getByRole('link',{name:'Revisar publicación',exact:false}).count(),2);report.checks.push('An actual service approval moves the item between role queues on an explicit fresh read');
 await root(p).getByRole('button',{name:'Buscar y filtrar',exact:true}).click(); await root(p).getByRole('combobox',{name:'Estado editorial'}).selectOption('');await submit(p);await loaded(p,35);await fetch(api+'/qa-mode?unavailable=1',{method:'POST'});await root(p).getByRole('button',{name:'Página siguiente'}).click();await root(p).getByRole('status').filter({hasText:'La fuente no pudo confirmar'}).waitFor();assert.equal(await root(p).getByRole('button',{name:/Ver próximo paso de/}).count(),0);assert.equal(await root(p).getByRole('heading',{name:'Todavía no hay pasaportes incorporados a Studio'}).count(),0);await fetch(api+'/qa-mode',{method:'POST'});await root(p).getByRole('button',{name:'Reintentar esta página',exact:true}).click();await root(p).getByText('Página 2 · 10 pasaportes visibles',{exact:true}).waitFor();report.checks.push('Failed reads remove stale work and retry the same position without claiming a successfully empty queue');
 const reader=await open('reader','/passports/review?view=mine');await loaded(reader.p,0);assert.equal(await root(reader.p).getByRole('button',{name:/Ver próximo paso de/}).count(),0);const forbidden=await reader.context.request.get(base+'/api/admin/passport-editorial/queue?tenant=other-queue');assert.equal(forbidden.status(),403);const denied=await open('global','/passports/review?tenant=empty-scope');await loaded(denied.p,0);await root(denied.p).getByRole('heading',{name:'Todavía no hay pasaportes incorporados a Studio'}).waitFor();report.checks.push('Reader and global empty-scope views remain explicit, and foreign-tenant requests are refused before rewriting');
 const global=await open('global','/passports/review?q=REVIEW-OTHER');await loaded(global.p,2);const foreignCard=root(global.p).locator('article').filter({hasText:'Empresa ajena'});await foreignCard.getByRole('link',{name:'Continuar edición',exact:false}).click();await global.p.locator('.ps-root:visible').getByRole('heading',{name:'Passport Studio',exact:true}).waitFor();assert.ok(global.p.url().includes('tenant=other-queue'));const field=global.p.locator('.ps-root:visible').getByRole('textbox',{name:'Nombre del producto',exact:false});await field.fill('Contenido de la empresa ajena QA');await global.p.locator('.ps-root:visible').getByRole('button',{name:'Guardar borrador',exact:true}).click();await global.p.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await global.p.locator('.ps-root:visible').getByText('Borrador guardado. El pasaporte publicado no cambió.',{exact:true}).waitFor();assert.equal(global.writes.length,1);assert.ok(global.writes[0].endsWith('/passport-editorial/save'));await global.p.getByRole('link',{name:'Bandeja editorial',exact:true}).last().click();await loaded(global.p,1);assert.match(await root(global.p).innerText(),/Contenido de la empresa ajena QA/);report.checks.push('Global operator opens and saves the intended tenant when two companies have the same BID; return navigation retains that scope');
 for(const user of [editor,reviewer,publisher,own,reader,denied]){assert.deepEqual(user.writes,[]);assert.deepEqual(user.errors,[]);}assert.deepEqual(global.errors,[]);const final=await state();assert.equal(final.history,before.history+2);report.checks.push('Queue interactions create no workflow events; only the explicit service approval and explicit Studio save changed the local history');
 for(const user of [editor,reviewer,publisher,own,reader,denied,global])await user.context.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,12000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
