import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {parseEditorialQueue,queueParams,queueStudioHref,INITIAL_QUEUE_FILTERS} from '../src/lib/editorial-queue.ts';
import {requiredPermissionForAdminResource} from '../src/lib/permission-policy.ts';
import {dashboardCanOpenDestination} from '../src/lib/dashboard-destination-policy.ts';
import {groupTaskNavigation} from '../src/lib/dashboard-task-navigation.ts';
const make=()=>({ok:true,protocol:'nexid.editorial-queue.v1',source:'database',readOnly:true,observedAt:'2026-09-19T12:00:00Z',scope:{tenant:'company',mode:'tenant'},filters:{state:'',view:'all',q:''},summary:{total:1,byState:{draft:0,changes_requested:0,in_review:1,approved:0,published:0},forActor:0,basis:'enrolled_passports_in_scope'},matched:1,items:[{id:'10000000-0000-4000-8000-000000000001',bid:'LOT-1',tenant:'company',tenantName:'Company',product:'Producto',state:'in_review',revision:3,publishedVersion:0,template:'general',locale:'es-AR',updatedAt:'2026-09-19T12:00:00Z',lastChange:null,code:'needs_independent_review',forActor:false}],navigation:{page:1,pageSize:25,hasNext:false,nextCursor:null,order:'oldest_update_first',consistency:'live_queue_rechecked_on_each_request'}});
const parse=d=>parseEditorialQueue(d,'company',INITIAL_QUEUE_FILTERS);
test('metadata is usable only for the requested tenant, filters and page',()=>{assert.equal(parse(make()).items[0].publishedVersion,0);for(const mutation of [d=>d.scope.tenant='foreign',d=>d.items[0].tenant='foreign',d=>d.filters.view='mine',d=>d.navigation.page=2,d=>d.source='demo',d=>d.readOnly=false]){const d=make();mutation(d);assert.throws(()=>parse(d));}});
test('unmatched counts or actions cannot turn an author into a reviewer',()=>{for(const mutation of [d=>d.summary.total=2,d=>d.items[0].forActor=true,d=>d.items[0].code='publish',d=>d.navigation.hasNext=true,d=>d.items.push(d.items[0])]){const d=make();mutation(d);assert.throws(()=>parse(d));}});
test('filter bookmarks exclude cursor, actor ID and credentials',()=>{const p=queueParams('company',{state:'in_review',view:'mine',q:' vino '});assert.equal(p.get('q'),'vino');assert.equal(p.get('view'),'mine');assert.ok(!p.has('cursor'));assert.ok(!p.has('actor'));assert.match(queueStudioHref({bid:'LOT/1',tenant:'a&b'}),/LOT%2F1/);assert.match(queueStudioHref({bid:'LOT/1',tenant:'a&b'}),/tenant=a%26b/);});
test('queue destination is permission-gated inside Products and passports',()=>{assert.equal(dashboardCanOpenDestination('editorialQueue',{role:'tenant-admin',permissions:['batches:read']}),true);assert.equal(dashboardCanOpenDestination('editorialQueue',{role:'tenant-admin',permissions:[]}),false);assert.equal(dashboardCanOpenDestination('editorialQueue',{role:'tenant-admin',permissions:['batches:read'],deniedPermissions:['batches:read']}),false);const groups=groupTaskNavigation([{destination:'editorialQueue',href:'/passports/review',label:'Editorial'}],'es-AR');assert.equal(groups[0].id,'products');assert.equal(groups[0].items[0].label,'Bandeja editorial');});
test('BFF admits read permission and rejects foreign scope before tenant rewriting',async()=>{assert.equal(requiredPermissionForAdminResource('GET','passport-editorial/queue'),'batches:read');const s=await readFile(new URL('../src/app/api/admin/[...path]/route.ts',import.meta.url),'utf8');assert.ok(s.indexOf('editorial_queue_tenant_forbidden')<s.indexOf('const tenantScope = resolveDashboardTenantScope'));});
test('UI offers workflow links rather than approval writes, and discards stale responses',async()=>{const s=await readFile(new URL('../src/components/editorial-queue.tsx',import.meta.url),'utf8');assert.match(s,/queueStudioHref/);assert.match(s,/setData\(null\)/);assert.match(s,/seq===generation.current/);assert.doesNotMatch(s,/method:.*POST|localStorage|sessionStorage|setInterval|dangerouslySetInnerHTML/);});

import {studioRequestPath} from '../src/lib/passport-studio-transport.ts';
test('Studio paths preserve explicit tenant after action without weakening endpoint restrictions',()=>{assert.equal(studioRequestPath('/api/admin/batches/LOT-1/passport-editorial','save','company'),'/api/admin/batches/LOT-1/passport-editorial/save?tenant=company');assert.equal(studioRequestPath('/api/admin/batches/LOT-1/passport-editorial','save'),'/api/admin/batches/LOT-1/passport-editorial/save');assert.throws(()=>studioRequestPath('https://other.invalid/api/admin/x','save','company'));assert.throws(()=>studioRequestPath('/api/admin/x?tenant=other','save','company'));assert.throws(()=>studioRequestPath('/api/admin/x','save','company&other'));});
