import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import ts from 'typescript';
import {INITIAL_QUEUE_FILTERS,queueParams,queueFiltersFromSearch} from '../src/lib/editorial-queue.ts';
import {readEditorialQueue,EditorialQueueReadError,QUEUE_READ_COPY} from '../src/lib/editorial-queue-read.ts';import {queueFixture} from './editorial-queue-continuity-fixture.mjs';
const source=await readFile(new URL('../src/app/(app)/passports/review/page.tsx',import.meta.url),'utf8');
const compiled=ts.transpileModule(source.replace(/^import .*;\r?$/gm,''),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React}}).outputText;
const principal={id:'synthetic-session-not-for-browser',userId:'qa-user',role:'tenant-admin',tenantId:'10000000-0000-4000-8000-000000000001',tenantSlug:'company',permissions:['batches:read'],deniedPermissions:[],isDemo:false};
async function page({session=principal,query={},status=200,mode='production'}={}){
 const calls=[],exports={},React={createElement:(type,props,...children)=>({type,props,children})};
 const params=['exports','React','createHash','requireDashboardSession','createAdminPageContext','fetchAdminPage','INITIAL_QUEUE_FILTERS','queueParams','queueFiltersFromSearch','readEditorialQueue','EditorialQueueReadError','QUEUE_READ_COPY','EditorialQueueWorkspace'];
 new Function(...params,compiled)(exports,React,createHash,async permission=>{assert.equal(permission,'batches:read');return session;},async(s,tenant)=>{if(Array.isArray(tenant)||s.tenantSlug&&tenant&&tenant!==s.tenantSlug)throw Error('denied scope');return {tenantSlug:s.tenantSlug||tenant||''};},async(context,path,init)=>{calls.push({context,path,init});return Response.json(status===200?queueFixture(context.tenantSlug):{ok:false},{status,headers:{'x-nexid-data-mode':mode}});},INITIAL_QUEUE_FILTERS,queueParams,queueFiltersFromSearch,readEditorialQueue,EditorialQueueReadError,QUEUE_READ_COPY,'queue');
 const node=await exports.default({searchParams:Promise.resolve(query)});return{node,calls};
}
test('page uses one bounded authenticated BFF read and sends only a hashed context',async()=>{const r=await page();assert.equal(r.calls.length,1);assert.equal(r.calls[0].path,'passport-editorial/queue?');assert.equal(r.calls[0].context.tenantSlug,'company');assert.equal(r.calls[0].init.method,'GET');assert.equal(r.calls[0].init.redirect,'error');assert.match(r.node.props.contextKey,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(r.node.props).includes(principal.id));assert.ok(r.node.props.initial);});
for(const query of [{state:['draft','published']},{view:'unauthorized'},{q:'x'.repeat(101)},{actor:'injected'}])test('malformed shared link performs no read '+JSON.stringify(query),async()=>{const r=await page({query});assert.equal(r.calls.length,0);assert.equal(r.node.props.initial,null);assert.match(r.node.props.initialError,/filtros/);});
test('demo never makes a BFF request or renders a prior queue',async()=>{const r=await page({session:{...principal,isDemo:true}});assert.equal(r.calls.length,0);assert.equal(r.node.props.enabled,false);assert.equal(r.node.props.initial,null);});
test('foreign tenant is not rewritten into the user scope',async()=>assert.rejects(page({query:{tenant:'other'}}),/denied scope/));
for(const status of [401,403,404,409,503])test('SSR error '+status+' remains unconfirmed rather than an empty queue',async()=>{const r=await page({status});assert.equal(r.node.props.initial,null);assert.ok(r.node.props.initialError);assert.equal(r.calls.length,1);});
test('a demo header cannot pass through a real server page',async()=>{const r=await page({mode:'demo'});assert.equal(r.node.props.initial,null);assert.ok(r.node.props.initialError);});
for(const change of [{id:'another-session'},{userId:'other-user'},{role:'super-admin'},{deniedPermissions:['batch.product.review']}])test('context identity changes on '+Object.keys(change)[0],async()=>{const a=await page(),b=await page({session:{...principal,...change}});assert.notEqual(a.node.props.contextKey,b.node.props.contextKey);});
