import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3322',api='http://127.0.0.1:4422',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
const report={localOnly:true,actualCapture:true,actualPostgres:true,checks:[],visual:[]},state=async()=>await(await fetch(api+'/qa-state')).json();
async function open(who='editor',width=1440){const c=await browser.newContext({viewport:{width,height:1050},locale:'es-AR',reducedMotion:'reduce',serviceWorkers:'block',acceptDownloads:true});await c.addCookies([{name:'nexid_dashboard_session',value:'qa-intake-'+who,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await p.goto(base+'/batches/GS1-LOCAL/intake',{waitUntil:'load',timeout:90000});const root=p.locator('[data-testid="epcis-intake-workspace"]:visible');await root.getByRole('heading',{name:'Registrar movimientos',exact:true}).waitFor();return {p,c,root,errors};}
async function prepare(p,reference,action='Agrupar'){
 await p.getByRole('button',{name:'Unidades, cajas y pallets',exact:true}).click();await p.getByRole('textbox',{name:'Referencia única del movimiento',exact:true}).fill(reference);
 await p.getByRole('button',{name:action,exact:true}).click();await p.getByLabel('Cuándo ocurrió la agrupación · hora local',{exact:true}).fill('2026-09-19T12:25');
 await p.getByRole('combobox',{name:'Dónde buscar',exact:true}).selectOption('company');await p.getByRole('textbox',{name:'Buscar lote GTIN o serie',exact:true}).fill('BOXES');await p.getByRole('button',{name:'Buscar identidades',exact:true}).click();await p.getByRole('button',{name:'Usar BOX-001 como contenedor',exact:true}).click();
 await p.getByRole('combobox',{name:'Dónde buscar',exact:true}).selectOption('batch');await p.getByRole('textbox',{name:'Buscar lote GTIN o serie',exact:true}).fill('UNIT-');await p.getByRole('button',{name:'Buscar identidades',exact:true}).click();await p.getByRole('button',{name:'Agregar UNIT-001 a unidades',exact:true}).click();await p.getByRole('button',{name:'Agregar UNIT-002 a unidades',exact:true}).click();
}
async function validate(p){await p.getByRole('button',{name:'Validar sin registrar',exact:true}).click();await p.getByText('Validación completa. Todavía no se registraron movimientos.',{exact:true}).waitFor();}
try{
 const user=await open(),p=user.p;const initialCalls=(await state()).calls.length;
 await p.getByRole('button',{name:'Unidades, cajas y pallets',exact:true}).click();await p.getByRole('textbox',{name:'Buscar lote GTIN o serie'}).fill('UN');assert.equal((await state()).calls.length,initialCalls);report.checks.push('Selecting relation mode and typing do not write or query automatically');
 await prepare(p,'GROUP-BROWSER-001');const before=(await state()).calls.length;await p.getByRole('button',{name:'Mis comprobantes',exact:true}).click();await p.getByRole('button',{name:'Nuevo movimiento',exact:true}).click();assert.equal(await p.getByRole('textbox',{name:'Referencia única del movimiento'}).inputValue(),'GROUP-BROWSER-001');assert.match(await p.getByTestId('relation-summary').innerText(),/BOX-001/);assert.equal((await state()).calls.length,before);
 await validate(p);assert.equal((await state()).captures,0);const review=p.getByRole('region',{name:'Agrupación validada'});await review.getByRole('heading',{name:'Agrupar unidades',exact:true}).waitFor();assert.match(await review.innerText(),/UNIT-001/);assert.match(await review.innerText(),/BOX-001/);report.checks.push('Cross-lot registered parent and selected units are verified by the API before any capture; tabs preserve data');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1050});await p.evaluate(t=>{document.documentElement.dataset.theme=t;document.documentElement.classList.toggle('theme-light',t==='light');document.documentElement.classList.toggle('theme-dark',t==='dark');scrollTo(0,0);},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.addScriptTag({content:axe});const issues=await p.evaluate(async()=>{const r=await axe.run('[data-testid="epcis-intake-workspace"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`grouping-${width}-${theme}.png`),fullPage:true});assert.deepEqual(issues.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({width,theme,issues});}
 await p.getByRole('checkbox').check();await fetch(api+'/qa-lose',{method:'POST'});await p.getByRole('button',{name:'Confirmar registro',exact:true}).click();await p.getByRole('button',{name:'Reconciliar el mismo intento',exact:true}).waitFor();assert.equal((await state()).captures,1);assert.equal(await p.getByRole('button',{name:'Agrupar',exact:true}).isDisabled(),true);await p.getByRole('button',{name:'Reconciliar el mismo intento',exact:true}).click();await p.getByTestId('intake-receipt').waitFor();assert.equal((await state()).captures,1);report.checks.push('Lost confirmation response is recovered through the unchanged engine, without creating another grouping');
 const [dl]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Descargar comprobante',exact:true}).click()]);await dl.saveAs(join(out,'grouping-receipt.json'));const receipt=JSON.parse(await readFile(join(out,'grouping-receipt.json'),'utf8'));assert.equal(receipt.receipt.projectionCount,3);assert.equal(receipt.receipt.eventCount,1);assert.equal(receipt.receipt.evidence,'declared_business_event');
 await p.getByRole('button',{name:'Preparar otro movimiento',exact:true}).click();assert.equal(await p.getByRole('textbox',{name:'Referencia única del movimiento'}).inputValue(),'');assert.equal((await state()).captures,1);
 await p.reload({waitUntil:'load'});await prepare(p,'UNGROUP-BROWSER-001','Separar');await validate(p);await p.getByRole('region',{name:'Agrupación validada'}).getByText('Sólo se declara la separación',{exact:false}).waitFor();await p.getByRole('checkbox').check();await p.getByRole('button',{name:'Confirmar registro',exact:true}).click();await p.getByTestId('intake-receipt').waitFor();const query=await(await fetch(api+'/qa-query')).json();assert.equal(query.events.length,2);assert.ok(query.events.some(e=>e.action==='ADD'));assert.ok(query.events.some(e=>e.action==='DELETE'));report.checks.push('Explicit separation appends a new event and preserves the earlier grouping in the existing query');
 await p.reload({waitUntil:'load'});await prepare(p,'OBSERVE-BROWSER-001','Observar');await validate(p);await p.getByRole('checkbox').check();await p.getByRole('button',{name:'Confirmar registro',exact:true}).click();await p.getByTestId('intake-receipt').waitFor();assert.equal((await state()).captures,3);report.checks.push('Observation records only the chosen relationship without declaring packaging or disassembly');
 await p.reload({waitUntil:'load'});await p.getByRole('button',{name:'Mis comprobantes',exact:true}).click();await user.root.getByText('GROUP-BROWSER-001',{exact:true}).waitFor();await user.root.getByText('UNGROUP-BROWSER-001',{exact:true}).waitFor();report.checks.push('All receipts persist and are recoverable after reloading the workbench');
 await p.getByRole('button',{name:'Nuevo movimiento',exact:true}).click();await p.getByRole('button',{name:'Unidades, cajas y pallets',exact:true}).click();await p.getByRole('button',{name:'Buscar identidades',exact:true}).click();await p.getByRole('button',{name:'Más coincidencias',exact:false}).waitFor();const first=await p.getByTestId('relation-composer').locator('ul').last().innerText();await p.getByRole('button',{name:'Más coincidencias',exact:false}).click();await p.getByRole('status').filter({hasText:'5 identidades en esta página.'}).waitFor();const second=await p.getByTestId('relation-composer').locator('ul').last().innerText();assert.notEqual(first,second);report.checks.push('Large identity lists use bounded search pages instead of an oversized selector');
 const beforeFailed=(await state()).captures;await fetch(api+'/qa-mode?fail=1',{method:'POST'});await p.getByRole('button',{name:'Buscar identidades',exact:true}).click();await p.getByRole('status').filter({hasText:'No se pudieron consultar las identidades.'}).waitFor();assert.equal(await p.getByRole('button',{name:/Usar .* como contenedor/}).count(),0);assert.equal((await state()).captures,beforeFailed);await fetch(api+'/qa-mode',{method:'POST'});report.checks.push('Unavailable directory clears selectable results without losing business records');
 const limited=await open('nomfa');await prepare(limited.p,'NO-MFA-BROWSER');await validate(limited.p);assert.equal(await limited.p.getByRole('button',{name:'Confirmar registro',exact:true}).isDisabled(),true);assert.equal((await state()).captures,3);assert.deepEqual(limited.errors,[]);await limited.c.close();
 assert.equal((await state()).unchanged,true);assert.deepEqual(user.errors,[]);report.checks.push('Unverified MFA cannot confirm and all original product, tag and technical fields remain unchanged');await user.c.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,10000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
