import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3271',api='http://127.0.0.1:4371',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
const report={localOnly:true,actualCaptureEngine:true,actualPostgres:true,syntheticAuth:true,checks:[],visual:[]};const state=async()=>await(await fetch(api+'/qa-state')).json();
async function open(who='editor',width=1440){const c=await browser.newContext({viewport:{width,height:1020},locale:'es-AR',reducedMotion:'reduce',serviceWorkers:'block',acceptDownloads:true});await c.addCookies([{name:'nexid_dashboard_session',value:'qa-intake-'+who,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await p.goto(base+'/batches/GS1-LOCAL/intake',{waitUntil:'load',timeout:90000});await p.locator('[data-testid="epcis-intake-workspace"]:visible').getByRole('heading',{name:'Registrar movimientos',exact:true}).waitFor();return {c,p,errors};}
async function fill(p,reference){const data=await state();await p.getByRole('textbox',{name:'Referencia única del movimiento',exact:true}).fill(reference);await p.getByRole('combobox',{name:'Identidad registrada',exact:true}).selectOption(data.identities[0].id);await p.getByLabel('Cuándo ocurrió · hora local',{exact:true}).fill('2026-09-19T10:15');await p.getByRole('button',{name:'Validar sin registrar',exact:true}).click();await p.getByText('Validación completa. Todavía no se registraron movimientos.',{exact:true}).waitFor();}
try{
 const user=await open(),p=user.p;assert.equal((await state()).captures,0);await fill(p,'RECEPCION-QA-001');assert.equal((await state()).captures,0);report.checks.push('Guided reception resolves a registered identity and prepares without any capture');
 const before=(await state()).calls.length;await p.getByRole('button',{name:'Mis comprobantes',exact:true}).click();await p.getByRole('button',{name:'Nuevo movimiento',exact:true}).click();assert.equal(await p.getByRole('textbox',{name:'Referencia única del movimiento'}).inputValue(),'RECEPCION-QA-001');assert.equal((await state()).calls.length,before);report.checks.push('Tabs preserve prepared fields and do not query the API again');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1020});await p.evaluate(t=>{document.documentElement.dataset.theme=t;document.documentElement.classList.toggle('theme-light',t==='light');document.documentElement.classList.toggle('theme-dark',t==='dark');window.scrollTo(0,0);},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.addScriptTag({content:axe});const issues=await p.evaluate(async()=>{const r=await axe.run('[data-testid="epcis-intake-workspace"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`intake-${width}-${theme}.png`),fullPage:true});assert.deepEqual(issues.filter(i=>['serious','critical'].includes(i.impact)),[]);report.visual.push({width,theme,issues});}
 await p.getByRole('checkbox').check();await fetch(api+'/qa-lose',{method:'POST'});await p.getByRole('button',{name:'Confirmar registro',exact:true}).click();await p.getByRole('button',{name:'Reconciliar el mismo intento',exact:true}).waitFor();assert.equal((await state()).captures,1);assert.equal(await p.getByRole('textbox',{name:'Referencia única del movimiento'}).isDisabled(),true);await p.getByRole('button',{name:'Reconciliar el mismo intento',exact:true}).click();await p.getByTestId('intake-receipt').waitFor();assert.equal((await state()).captures,1);report.checks.push('Lost response after SQL commit is recovered with the same operation and only one event');
 const [dl]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Descargar comprobante',exact:true}).click()]);await dl.saveAs(join(out,'receipt.json'));const saved=JSON.parse(await readFile(join(out,'receipt.json'),'utf8'));assert.equal(saved.scope.tenant,'channels-qa');assert.equal(saved.receipt.eventCount,1);assert.equal(saved.receipt.evidence,'declared_business_event');report.checks.push('Receipt download contains the confirmed scope, capture and human declaration basis');
 await p.reload({waitUntil:'load'});await p.getByRole('button',{name:'Mis comprobantes',exact:true}).click();await p.locator('[data-testid="epcis-intake-workspace"]:visible').getByText('RECEPCION-QA-001',{exact:true}).waitFor();await p.getByRole('button',{name:'Nuevo movimiento',exact:true}).click();await p.getByRole('button',{name:'Archivo del ERP / WMS',exact:true}).click();await p.getByRole('textbox',{name:'Referencia única del movimiento'}).fill('ARCHIVO-QA-001');const doc=await(await fetch(api+'/qa-document')).json();await p.locator('input[type=file]').setInputFiles({name:'aggregation.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await p.getByRole('button',{name:'Validar sin registrar',exact:true}).click();await p.getByText('Validación completa. Todavía no se registraron movimientos.',{exact:true}).waitFor();await p.getByRole('checkbox').check();await p.getByRole('button',{name:'Confirmar registro',exact:true}).click();await p.getByTestId('intake-receipt').waitFor();assert.equal((await state()).captures,2);const query=await(await fetch(api+'/qa-query')).json();assert.equal(query.events.length,2);report.checks.push('File aggregation uses the same engine and appears in the existing EPCIS query, not a parallel ledger');
 await p.reload({waitUntil:'load'});await p.getByRole('button',{name:'Archivo del ERP / WMS',exact:true}).click();await p.getByRole('textbox',{name:'Referencia única del movimiento'}).fill('REPEAT-FILE');await p.locator('input[type=file]').setInputFiles({name:'same.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(doc))});await p.getByRole('button',{name:'Validar sin registrar',exact:true}).click();await p.getByText('Hay eventos ya registrados.',{exact:false}).waitFor();assert.equal(await p.getByRole('button',{name:'Confirmar registro',exact:true}).isDisabled(),true);assert.equal((await state()).captures,2);report.checks.push('Previously captured event IDs block a fresh duplicate file instead of creating new movements');
 for(const who of ['reader','nomfa','denied']){const account=await open(who);await fill(account.p,'NEW-'+who);assert.equal(await account.p.getByRole('button',{name:'Confirmar registro',exact:true}).isDisabled(),true);await account.c.close();}report.checks.push('Read-only, MFA-unverified and explicitly denied accounts cannot confirm');
 await p.locator('input[type=file]').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await p.getByText('El archivo no contiene JSON válido.',{exact:true}).waitFor();assert.equal((await state()).captures,2);report.checks.push('Malformed files are rejected locally before any write');
 const cross=await user.c.request.get(base+'/api/admin/batches/GS1-LOCAL/epcis-intake?tenant=other-qa');assert.equal(cross.status(),200);assert.equal((await cross.json()).scope.tenant,'channels-qa');assert.equal((await state()).unchanged,true);assert.deepEqual(user.errors,[]);report.checks.push('BFF keeps tenant scope and no original tag state or product configuration changed');await user.c.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,9000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
