import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const base='http://localhost:3153',api='http://127.0.0.1:4212',out=process.env.QA_OUTPUT;
const manifest=JSON.parse(await readFile(new URL('../src/lib/integration-kit-manifest.json',import.meta.url),'utf8'));
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,realArtifact:true,visual:[],checks:[]};
async function open(role,width=1440){const context=await browser.newContext({viewport:{width,height:1050},serviceWorkers:'block',reducedMotion:'reduce',acceptDownloads:true,permissions:['clipboard-read','clipboard-write']});if(role)await context.addCookies([{name:'nexid_dashboard_session',value:'local-kit-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());return {context,p,errors};}
try{
 await fetch(api+'/qa-mode?unavailable=0');
 const editor=await open('admin');const p=editor.p;await p.goto(base+'/sdk-vision',{waitUntil:'load',timeout:90000});await p.getByRole('heading',{name:'Conectá el sistema del cliente.',exact:true}).waitFor();
 const [download]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Descargar kit ejecutable',exact:true}).click()]);await download.saveAs(join(out,'downloaded-kit.tgz'));const bytes=await readFile(join(out,'downloaded-kit.tgz'));assert.equal(createHash('sha256').update(bytes).digest('hex'),manifest.sha256);report.checks.push('Authenticated download matches pinned release artifact');
 await p.getByRole('button',{name:'Importar recepciones',exact:true}).click();const consoleView=p.getByTestId('integration-kit-console');assert.match(await consoleView.innerText(),/--confirm-tenant company-local/);await p.getByRole('button',{name:'Copiar comandos',exact:true}).click();const copied=await p.evaluate(()=>navigator.clipboard.readText());assert.match(copied,/--limit 10/);assert.match(copied,/--tenant company-local/);assert.ok(!copied.includes('local-kit-admin'));const keyLink=await consoleView.getByRole('link',{name:'Credenciales y webhooks',exact:true}).getAttribute('href');assert.match(keyLink,/profile=erp-csv/);assert.match(keyLink,/tenant=company-local/);report.checks.push('Minimum-scope profile and safe tenant-aware commands are connected');
 const [csv]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Plantilla de recepciones CSV',exact:true}).click()]);await csv.saveAs(join(out,'receipts.csv'));assert.match(await readFile(join(out,'receipts.csv'),'utf8'),/^external_id,bid,occurred_at,facility/);
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1050});await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow');await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('[data-testid="integration-kit-console"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await consoleView.screenshot({path:join(out,`kit-${width}-${theme}.png`)});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}assert.deepEqual(editor.errors,[]);
 for(const role of ['viewer','forged-viewer']){const user=await open(role);await user.p.goto(base+'/sdk-vision',{waitUntil:'load'});assert.equal(await user.p.getByRole('button',{name:'Descargar kit ejecutable',exact:true}).isDisabled(),true);const r=await user.context.request.get(base+'/api/integration-kit');assert.equal(r.status(),403);await user.context.close();}report.checks.push('Viewer and role-incompatible grants cannot download the private SDK');
 const anon=await open(null);assert.equal((await anon.context.request.get(base+'/api/integration-kit')).status(),401);await anon.context.close();
 await fetch(api+'/qa-mode?unavailable=1');const failed=await editor.context.request.get(base+'/api/integration-kit');assert.equal(failed.status(),503);await fetch(api+'/qa-mode?unavailable=0');report.checks.push('Unauthenticated and unavailable-session responses contain no artifact');
 const state=await(await fetch(api+'/qa-state')).json();assert.ok(state.calls.every(c=>c.method==='GET'));report.checks.push('No credential, business event, tag or webhook writes occurred during browser tests');await editor.context.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,4000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
