// Actual Next/BFF + production handlers + disposable PostgreSQL. Only users and commercial IDs are local fixtures.
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const base='http://localhost:3199',api='http://127.0.0.1:4299',out=process.env.QA_OUTPUT;
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH}),report={localOnly:true,realHandlers:true,realPostgres:true,checks:[],visual:[]};
const csv='gtin,lot,serial\n09506000134352,QA-ROLL,000001\n09506000134352,QA-ROLL,000002\n09506000134352,QA-ROLL,000003\n';
const state=async()=>await(await fetch(api+'/qa-state')).json();
async function open(role='editor',bid='GS1-LOCAL',width=1440){const context=await browser.newContext({viewport:{width,height:1050},reducedMotion:'reduce',serviceWorkers:'block',acceptDownloads:true,locale:'es-AR'});await context.addCookies([{name:'nexid_dashboard_session',value:'qa-production-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await page.goto(base+'/batches/'+bid+'/production',{waitUntil:'load',timeout:90000});await page.getByRole('heading',{name:'Producción QR / GS1',exact:true}).waitFor();return {context,page,errors};}
async function upload(page,buffer,name='identidades-qa.csv'){await page.locator('[data-testid="label-production-workspace"]:visible input[type=file]').setInputFiles({name,mimeType:'text/csv',buffer:Buffer.from(buffer)});}
async function download(page,label,name){const [d]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:label,exact:true}).click()]);await d.saveAs(join(out,name));return readFile(join(out,name),'utf8');}
try{
 const editor=await open(),p=editor.page;await upload(p,csv.replace('000003','000001'));await p.getByText('Identidad repetida en el archivo',{exact:true}).first().waitFor();assert.equal(await p.getByRole('button',{name:'Validar con el registro',exact:true}).isDisabled(),true);assert.equal((await state()).counts.identities,0);report.checks.push('Duplicate file rows are shown before any network mutation');
 await upload(p,csv);await p.getByRole('button',{name:'Validar con el registro',exact:true}).click();await p.getByRole('heading',{name:'3 nuevas · 0 existentes · 0 bloqueadas'}).waitFor();assert.equal((await state()).counts.identities,0);await p.getByRole('textbox',{name:'Referencia de preparación',exact:true}).fill('ORDEN-LOCAL-001');await p.getByRole('checkbox').check();await fetch(api+'/qa-lose-next',{method:'POST'});await p.getByRole('button',{name:'Confirmar importación',exact:true}).click();await p.getByRole('button',{name:'Reintentar el mismo intento',exact:true}).waitFor();assert.equal((await state()).counts.identities,3);await p.getByRole('button',{name:'Reintentar el mismo intento',exact:true}).click();await p.getByText('Registro confirmado',{exact:true}).waitFor();assert.deepEqual((await state()).counts,{identities:3,operations:1});report.checks.push('Atomic import and lost-response retry confirm the same three identities and one receipt');
 const rawReceipt=await download(p,'Descargar comprobante','receipt.json'),receipt=JSON.parse(rawReceipt);assert.equal(receipt.rows.length,3);assert.equal(receipt.rows[0].serial,'000001');
 await p.getByRole('button',{name:'Preparar plancha de etiquetas',exact:true}).click();await p.getByRole('img',{name:'Vista previa de la primera etiqueta del paquete'}).waitFor();assert.equal(await p.getByRole('img',{name:'Vista previa de la primera etiqueta del paquete'}).evaluate(i=>i.complete&&i.naturalWidth>0),true);
 const html=await download(p,'Descargar plancha HTML','labels.html'),manifest=JSON.parse(await download(p,'Descargar manifiesto JSON','labels.json'));await download(p,'Descargar datos CSV','labels.csv');assert.equal(manifest.labels.length,3);assert.equal(manifest.sameDestination,false);assert.equal(manifest.labels[0].serial,'000001');assert.equal(createHash('sha256').update(html).digest('hex').length,64);assert.ok(!html.includes('<script'));assert.match(html,/Imprimir una muestra/);
 const reportPage=await browser.newPage({viewport:{width:900,height:1050}});let remoteLoads=0;await reportPage.route('**/*',r=>{remoteLoads++;return r.abort();});await reportPage.setContent(html);assert.equal(await reportPage.locator('article.label').count(),3);assert.equal(await reportPage.locator('svg').count(),3);await reportPage.screenshot({path:join(out,'print-sheet.png'),fullPage:true});assert.equal(remoteLoads,0);await reportPage.close();report.checks.push('Downloadable self-contained sheet and manifest contain only the confirmed identities in order');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1050});await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');},theme);await p.evaluate(()=>window.scrollTo(0,0));await p.waitForTimeout(150);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow');await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('[data-testid="label-production-workspace"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`production-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['critical','serious'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}
 await p.reload({waitUntil:'load'});await p.getByRole('button',{name:'Importaciones guardadas',exact:true}).click();await p.getByRole('button',{name:'Abrir comprobante',exact:true}).first().click();await p.getByText('Registro confirmado',{exact:true}).waitFor();assert.deepEqual((await state()).counts,{identities:3,operations:1});report.checks.push('Saved import receipt can be recovered after reload without rewriting registry rows');
 await p.getByRole('button',{name:'Preparar plancha de etiquetas',exact:true}).click();await p.getByRole('button',{name:'Descargar plancha HTML',exact:true}).waitFor();await fetch(api+'/qa-mode?unavailable=1',{method:'POST'});await p.getByRole('button',{name:'Preparar plancha de etiquetas',exact:true}).click();await p.getByRole('status').filter({hasText:'No se confirmó'}).waitFor();assert.equal(await p.getByRole('button',{name:'Descargar plancha HTML',exact:true}).count(),0);await fetch(api+'/qa-mode',{method:'POST'});report.checks.push('Failed refresh does not leave a previous printable artifact offered as current');
 const qr=await open('viewer','QR-LOCAL',390);await qr.page.getByRole('spinbutton',{name:'Copias para la plancha'}).fill('5');await qr.page.getByRole('button',{name:'Preparar plancha de etiquetas',exact:true}).click();await qr.page.getByRole('button',{name:'Descargar manifiesto JSON',exact:true}).waitFor();const qrManifest=JSON.parse(await download(qr.page,'Descargar manifiesto JSON','qr-manifest.json'));assert.equal(qrManifest.labels.length,5);assert.equal(qrManifest.sameDestination,true);assert.equal(new Set(qrManifest.labels.map(r=>r.url)).size,1);assert.ok(qrManifest.labels.every(l=>l.identityId===null));report.checks.push('QR basic prints repeated batch links, not fabricated unique units');
 const viewer=await open('viewer');await upload(viewer.page,csv);await viewer.page.getByRole('button',{name:'Validar con el registro',exact:true}).click();await viewer.page.getByRole('heading',{name:'0 nuevas · 3 existentes · 0 bloqueadas'}).waitFor();assert.equal(await viewer.page.getByRole('button',{name:'Confirmar importación',exact:true}).isDisabled(),true);report.checks.push('Read-only accounts can review but cannot import');
 const tt=await open('editor','TT-LOCAL');await tt.page.getByRole('heading',{name:'Este lote conserva su tecnología NFC.'}).waitFor();assert.equal(await tt.page.getByRole('button',{name:'Preparar plancha de etiquetas',exact:true}).count(),0);report.checks.push('TagTamper keeps its dedicated workflow without static conversion or printing controls');
 for(const l of manifest.labels){const u=new URL(l.url),parts=u.pathname.split('/');const response=await fetch(api+'/public/gs1/resolve?'+new URLSearchParams({gtin:parts[2],lot:decodeURIComponent(parts[4]),serial:decodeURIComponent(parts[6])}));const result=await response.json();assert.equal(result.registry.bid,'GS1-LOCAL');assert.equal(result.registry.tenantSlug,'channels-qa');}report.checks.push('Every printed GS1 URI resolves through the actual registry to the intended batch');
 assert.equal((await state()).originalConfigUnchanged,true);assert.deepEqual(editor.errors,[]);assert.deepEqual(qr.errors,[]);assert.deepEqual(viewer.errors,[]);report.checks.push('No changes to batch configuration, SUN keys or counters');for(const context of browser.contexts())await context.close();report.status='passed';
}catch(error){report.status='failed';report.error=error.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,9000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw error;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
