import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
const base='http://localhost:3128';
const out=process.env.QA_OUTPUT;
assert.ok(out && process.env.PLAYWRIGHT_MODULE);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});
const report={localSyntheticOnly:true,base,map:{},roll:{},errors:[]};
const context=await browser.newContext({viewport:{width:1440,height:1050},serviceWorkers:'block',reducedMotion:'reduce'});
await context.addCookies([{name:'nexid_dashboard_session',value:'local-qa-only',url:base,httpOnly:true,sameSite:'Lax'}]);
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const allowed=new Set(['localhost','127.0.0.1','tiles.openfreemap.org','services.arcgisonline.com','tiles.mapterhorn.com']);
await page.route('**/*',r=>allowed.has(new URL(r.request().url()).hostname)?r.continue():r.abort());
try {
  let response=await page.goto(base+'/analytics/map',{waitUntil:'load',timeout:90000});assert.equal(response.status(),200);
  await page.locator('[data-testid="physical-map-workspace"]:visible').waitFor();
  assert.equal(await page.locator('tbody tr:visible').count(),3);
  await page.locator('.maplibregl-canvas').waitFor({timeout:45000});
  await page.waitForFunction(()=>!document.querySelector('.nexid-map-loading'),{},{timeout:45000});
  assert.equal(await page.locator('.nexid-map-error').count(),0);
  await page.getByRole('textbox', {name:'Buscar en la muestra'}).fill('Madrid');assert.equal(await page.locator('tbody tr:visible').count(),1);
  await page.getByRole('textbox', {name:'Buscar en la muestra'}).fill('');
  await page.getByRole('button',{name:'Eventos',exact:true}).click();
  assert.equal(await page.locator('[data-testid="crm-maplibre-map"]:visible').getAttribute('data-map-view'),'points');
  await page.waitForTimeout(8000);
  await page.screenshot({path:join(out,'map-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(600);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile overflow');
  await page.screenshot({path:join(out,'map-mobile.png'),fullPage:true});
  report.map={loaded:true,rows:3,search:true,eventsLayer:true,mobileNoOverflow:true};
  await page.setViewportSize({width:1440,height:1000});
  response=await page.goto(base+'/batches/QA-ROLL-01',{waitUntil:'load',timeout:90000});assert.equal(response.status(),200);
  await page.waitForFunction(()=>document.querySelectorAll('[data-testid="batch-roll-workspace"]').length===1);
  await page.locator('[data-testid="batch-roll-workspace"]:visible').waitFor();
  const editor=page.locator('[data-testid="roll-product-identity"]:visible');
  await editor.getByRole('textbox',{name:'Nombre del producto',exact:true}).fill('Producto editado LOCAL');
  await editor.getByRole('checkbox').check();await editor.getByRole('button',{name:'Guardar ficha del rollo'}).click();
  await editor.getByRole('status').filter({hasText:'Ficha guardada'}).waitFor();
  const intake=page.locator('[data-testid="roll-manifest-intake"]:visible');
  await intake.locator('summary').click();
  await intake.locator('input[type="file"]').setInputFiles({name:'rollo-qa.csv',mimeType:'text/csv',buffer:Buffer.from('uid,bid\n04000000000001,QA-ROLL-01\n04000000000002,QA-ROLL-01')});
  await intake.getByRole('button',{name:'Validar sin importar'}).click();
  await intake.getByRole('status').filter({hasText:'Validación confirmada'}).waitFor();
  const commitButton=intake.getByRole('button',{name:'Importar archivo validado'});assert.equal(await commitButton.isDisabled(),true);
  await intake.getByRole('checkbox').check();await commitButton.click();
  await intake.getByRole('status').filter({hasText:'Importación confirmada'}).waitFor();
  await page.screenshot({path:join(out,'roll-workspace.png'),fullPage:true});
  const state=await (await fetch('http://127.0.0.1:4198/qa-state')).json();
  assert.equal(state.imports,1);assert.equal(state.validations,1);
  assert.ok(state.calls.filter(c=>c.path.endsWith('/import-manifest')).every(c=>c.activateImported===false));
  assert.deepEqual(state.calls.find(c=>c.path.endsWith('/product-config')).fields,['product_name']);
  report.roll={productSaved:true,onlyChangedFields:true,validationBeforeImport:true,explicitConfirmation:true,imports:1,activated:false};
  assert.deepEqual(report.errors,[]);report.status='passed';
} catch(e){report.status='failed';report.error=e.stack;await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});throw e;}
finally {await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
