// Project Next/React/BFF + actual API handlers on disposable PostgreSQL. No production customers.
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3167',web='http://localhost:3168',api='http://127.0.0.1:4297',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,realPostgres:true,actualHandlers:true,screens:[],checks:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json(),pub=async()=>await(await fetch(api+'/public/product-notices/v2?tenant=recall-qa&bid=LOT-RECALL-QA')).json();
const cid=(await state()).caseId,path=`/batches/LOT-RECALL-QA/recalls/${cid}/notice?tenant=recall-qa`;
async function open(who,width=1440){const context=await browser.newContext({viewport:{width,height:1050},serviceWorkers:'block',reducedMotion:'reduce',acceptDownloads:true});await context.addCookies([{name:'nexid_dashboard_session',value:'qa-recall-'+who,url:base,httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await page.goto(base+path,{waitUntil:'load',timeout:90000});await page.getByRole('heading',{name:'Revisar el aviso publicado',exact:true}).waitFor();return {page,context,errors};}
async function confirm(page,name,reason){await page.getByRole('button',{name,exact:true}).click();const modal=page.getByRole('dialog');await modal.waitFor();if(reason)await modal.getByRole('textbox',{name:'Motivo de la decisión'}).fill(reason);await modal.getByRole('checkbox').check();await modal.getByRole('button',{name:'Confirmar cambio',exact:true}).click();await modal.waitFor({state:'hidden'});}
async function saved(p,text=/guardada con comprobante|aprobado y aplicado|intento anterior/){await p.getByRole('status').filter({hasText:text}).waitFor({timeout:30000});}
async function oldAction(p,name,{reason,evidence,returned,held}={}){await p.getByRole('button',{name,exact:true}).click();const d=p.getByRole('dialog');if(reason)await d.getByRole('textbox',{name:'Motivo o evidencia de la acción'}).fill(reason);if(evidence)await d.getByRole('textbox',{name:'Referencia del comprobante'}).fill(evidence);if(returned!==undefined)await d.getByRole('spinbutton',{name:'Total devueltas a la fecha'}).fill(String(returned));if(held!==undefined)await d.getByRole('spinbutton',{name:'Total inmovilizadas a la fecha'}).fill(String(held));await d.getByRole('checkbox').check();await d.getByRole('button',{name:'Confirmar acción',exact:true}).click();await p.getByRole('status').filter({hasText:'Operación guardada'}).waitFor({timeout:30000});}
try{
 const e=await open('editor'),p=e.page;assert.equal(await p.getByRole('button',{name:'Solicitar levantamiento',exact:true}).isDisabled(),true);await p.getByRole('button',{name:'Rectificar aviso',exact:true}).click();await p.getByRole('textbox',{name:'Título público',exact:true}).fill('Aviso rectificado QA');await p.getByRole('textbox',{name:'Mensaje del aviso',exact:true}).fill('No utilizar las unidades: contacto actualizado por revisión de calidad.');await p.getByRole('textbox',{name:'Justificación del cambio',exact:true}).fill('Motivo interno QA no debe aparecer en el pasaporte.');await p.getByRole('textbox',{name:'Referencia de evidencia',exact:true}).fill('ACTA-PRIVADA-001');
 const before=(await state()).calls.length;await p.getByRole('button',{name:'Antes y después',exact:true}).click();await p.getByText('VERSIÓN BASE',{exact:true}).first().waitFor();await p.getByRole('button',{name:'Propuesta',exact:true}).click();assert.equal(await p.getByRole('textbox',{name:'Título público',exact:true}).inputValue(),'Aviso rectificado QA');assert.equal((await state()).calls.length,before);assert.equal((await pub()).notices[0].title,'Retiro preventivo QA');report.checks.push('Before/after preserves inputs and does not publish or query silently');
 await fetch(api+'/qa-lose-next',{method:'POST'});await confirm(p,'Guardar propuesta');await p.getByRole('button',{name:'Reconciliar el mismo intento',exact:true}).waitFor();assert.equal((await state()).proposalCount,1);await p.getByRole('button',{name:'Reconciliar el mismo intento',exact:true}).click();await saved(p,/intento anterior/);assert.equal((await state()).operationCount,1);report.checks.push('Lost save response reconciles one persisted proposal');
 await confirm(p,'Enviar a revisión');await saved(p);assert.equal(await p.getByRole('button',{name:'Aprobar rectificación',exact:true}).isDisabled(),true);const reviewer=await open('reviewer'),r=reviewer.page;
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await r.setViewportSize({width,height:1050});await r.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');},theme);await r.getByRole('button',{name:'Antes y después',exact:true}).click();assert.ok(await r.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow');await r.addScriptTag({content:axe});const violations=await r.evaluate(async()=>{const v=await axe.run('[data-testid="notice-review-workspace"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return v.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await r.screenshot({path:join(out,`review-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.screens.push({width,theme,violations});}
 await r.setViewportSize({width:1440,height:1050});await confirm(r,'Aprobar rectificación');await saved(r,/aprobado y aplicado/);assert.equal((await pub()).notices[0].title,'Aviso rectificado QA');assert.equal((await pub()).notices[0].noticeVersion,2);report.checks.push('Independent approval updates the actual public v2 notice');
 const publicContext=await browser.newContext({locale:'es-AR',viewport:{width:390,height:850},reducedMotion:'reduce',serviceWorkers:'block'});const mobile=await publicContext.newPage();await mobile.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await mobile.goto(web+'/sun?qr=1&channel=qr&carrier=qr_basic&tenant=recall-qa&bid=LOT-RECALL-QA&lang=es-AR',{waitUntil:'load',timeout:90000});const box=mobile.getByTestId('product-notices');await box.getByRole('heading',{name:'Aviso rectificado QA',exact:true}).waitFor({timeout:30000});assert.ok(!(await box.innerText()).includes('ACTA-PRIVADA'));assert.ok(await box.evaluate(el=>el.getBoundingClientRect().top<520));await mobile.screenshot({path:join(out,'consumer-correction.png'),fullPage:false});
 // Continue the existing tracking flow instead of bypassing its closure controls.
 await p.goto(base+'/batches/LOT-RECALL-QA/recalls?tenant=recall-qa',{waitUntil:'load'});await p.getByRole('button',{name:/Retiro preventivo QA/}).first().click();await p.getByRole('link',{name:'Revisar aviso publicado →',exact:true}).waitFor();await oldAction(p,'Registrar acuse',{reason:'Acuse recibido del distribuidor local.',evidence:'ACUSE-LOCAL-01'});await oldAction(p,'Registrar cantidades',{reason:'Siete devueltas y tres inmovilizadas según acta.',evidence:'ACTA-CANTIDAD-01',returned:7,held:3});await oldAction(p,'Solicitar cierre',{reason:'Todos los destinos y cantidades fueron conciliados.'});
 await r.goto(base+'/batches/LOT-RECALL-QA/recalls?tenant=recall-qa',{waitUntil:'load'});await r.getByRole('button',{name:/Retiro preventivo QA/}).first().click();await oldAction(r,'Aprobar cierre',{reason:'Segunda revisión completa de acuses y cantidades.'});await p.goto(base+path,{waitUntil:'load'});await p.getByRole('button',{name:'Solicitar levantamiento',exact:true}).click();await p.getByRole('textbox',{name:'Mensaje público de resolución',exact:false}).fill('Aviso levantado por resolución documentada. Consultar instrucciones vigentes y al responsable antes de usar el producto.');await p.getByRole('textbox',{name:'Justificación del cambio',exact:true}).fill('Resolución interna luego del seguimiento cerrado.');await p.getByRole('textbox',{name:'Referencia de evidencia',exact:true}).fill('RESOLUCION-PRIVADA-02');await confirm(p,'Guardar propuesta');await saved(p);await confirm(p,'Enviar a revisión');await saved(p);assert.equal((await pub()).notices[0].noticeState,'active');await r.goto(base+path,{waitUntil:'load'});await confirm(r,'Aprobar levantamiento');await saved(r,/aprobado y aplicado/);assert.equal((await pub()).notices[0].noticeState,'lifted');report.checks.push('Existing closure precedes independent notice lifting, with visible resolution');
 await box.getByRole('button',{name:'Actualizar avisos',exact:true}).click();await box.getByText('AVISO LEVANTADO',{exact:true}).waitFor();assert.match(await box.innerText(),/no constituye liberación|No constituye liberación/i);await box.getByText('Ver aviso anterior',{exact:true}).click();assert.match(await box.innerText(),/No utilizar las unidades: contacto actualizado/);assert.ok(!(await box.innerText()).includes('RESOLUCION-PRIVADA'));await mobile.addScriptTag({content:axe});const publicViolations=await mobile.evaluate(async()=>{const r=await axe.run('[data-testid="product-notices"]');return r.violations.map(v=>({id:v.id,impact:v.impact}));});assert.deepEqual(publicViolations.filter(v=>['serious','critical'].includes(v.impact)),[]);await mobile.screenshot({path:join(out,'consumer-resolution.png'),fullPage:false});
 await fetch(api+'/qa-public-failure?enabled=1');await box.getByRole('button',{name:'Actualizar avisos',exact:true}).click();await box.locator('[role="status"]').filter({hasText:'No se pudieron consultar'}).waitFor();assert.equal(await box.getAttribute('data-notice-state'),'unknown');assert.match(await box.innerText(),/AVISO LEVANTADO/);await fetch(api+'/qa-public-failure?enabled=0');report.checks.push('Consumer resolution and previous warning survive refresh failure without a safety claim');
 const [download]=await Promise.all([r.waitForEvent('download'),r.getByRole('button',{name:'Descargar evidencia',exact:true}).click()]);await download.saveAs(join(out,'notice-evidence.html'));const html=await readFile(join(out,'notice-evidence.html'),'utf8');assert.match(html,/RESOLUCION-PRIVADA-02/);assert.match(html,/Aviso levantado con resolución/);assert.match(html,/product_recall_notice_operations/);report.checks.push('Authorized report downloads current resolution, comparison and bounded history');
 const viewer=await open('viewer',390);assert.equal(await viewer.page.getByRole('button',{name:'Rectificar aviso',exact:true}).count(),0);assert.equal(await viewer.page.getByRole('button',{name:'Aprobar levantamiento',exact:true}).count(),0);assert.deepEqual(e.errors,[]);assert.deepEqual(reviewer.errors,[]);assert.deepEqual(viewer.errors,[]);await viewer.context.close();await publicContext.close();await e.context.close();await reviewer.context.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(-7000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
