// Browser-to-BFF-to-actual editorial service and disposable PostgreSQL. Sessions are synthetic local fixtures.
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3144',api='http://127.0.0.1:4194',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,realPostgres:true,realService:true,productionData:false,steps:[],visual:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json();
async function pageFor(role,width=1440){const context=await browser.newContext({viewport:{width,height:1050},serviceWorkers:'block',reducedMotion:'reduce'});await context.addCookies([{name:'nexid_dashboard_session',value:'local-studio-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await page.goto(base+'/batches/QA-STUDIO/passport',{waitUntil:'load',timeout:60000});return {context,page,errors};}
async function confirm(page,action){await page.getByRole('button',{name:action,exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();}
try{
 await fetch(api+'/qa-reset',{method:'POST'});
 const editor=await pageFor('editor');const p=editor.page;
 await p.getByRole('heading',{name:'Prepará hoy. Publicá con confianza.'}).waitFor();
 assert.equal((await state()).history,0);assert.equal(await p.getByRole('button',{name:'Iniciar Passport Studio'}).isDisabled(),true);
 await p.getByRole('checkbox').check();await p.getByRole('button',{name:'Iniciar Passport Studio'}).click();
 await p.getByRole('heading',{name:'Passport Studio',exact:true}).waitFor();assert.equal((await state()).history,1);report.steps.push('explicit_enrollment_no_live_content_change');
 await p.getByRole('textbox',{name:'Nombre del producto',exact:false}).fill('Semilla publicada QA');
 const before=await state();await p.getByRole('button',{name:'Cambios',exact:true}).click();await p.getByRole('button',{name:'Identidad',exact:true}).click();assert.equal(await p.getByRole('textbox',{name:'Nombre del producto',exact:false}).inputValue(),'Semilla publicada QA');assert.equal((await state()).history,before.history);
 await confirm(p,'Guardar borrador');await p.getByText('Borrador guardado. El pasaporte publicado no cambió.',{exact:true}).waitFor();assert.equal((await state()).product,'Semilla de prueba local');
 await confirm(p,'Enviar a revisión');await p.locator('[data-slot="stage"]').filter({hasText:'En revisión'}).waitFor();assert.equal(await p.getByRole('button',{name:'Aprobar contenido',exact:true}).count(),0);report.steps.push('persisted_draft_submit_and_self_approval_blocked');
 const reviewer=await pageFor('reviewer');await reviewer.page.getByRole('button',{name:'Aprobar contenido',exact:true}).waitFor();await confirm(reviewer.page,'Aprobar contenido');await reviewer.page.locator('[data-slot="stage"]').filter({hasText:'Aprobado'}).waitFor();assert.equal(await reviewer.page.getByRole('button',{name:'Publicar esta versión',exact:true}).count(),0);report.steps.push('independent_review_and_publish_permission');
 const publisher=await pageFor('publisher');await confirm(publisher.page,'Publicar esta versión');await publisher.page.getByText('Publicación confirmada por el servidor.',{exact:true}).waitFor();assert.equal((await state()).product,'Semilla publicada QA');report.steps.push('actual_database_publication');
 await confirm(publisher.page,'Preparar nueva revisión');await publisher.page.locator('[data-slot="stage"]').filter({hasText:'Borrador'}).waitFor();await publisher.page.getByRole('button',{name:'Historial',exact:true}).click();await publisher.page.getByRole('button',{name:'Usar contenido en el borrador'}).last().click();await publisher.page.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await publisher.page.getByRole('heading',{name:'Comparar cambios'}).waitFor();assert.equal((await state()).product,'Semilla publicada QA');report.steps.push('new_cycle_and_historical_restore_do_not_publish');
 await publisher.page.getByRole('button',{name:'Identidad',exact:true}).click();await confirm(publisher.page,'Guardar borrador');await publisher.page.getByText('Borrador guardado. El pasaporte publicado no cambió.',{exact:true}).waitFor();
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){
  const item=await pageFor('publisher',width);await item.page.getByRole('heading',{name:'Passport Studio',exact:true}).waitFor();await item.page.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');},theme);
  assert.ok(await item.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow');await item.page.addScriptTag({content:axe});
  const violations=await item.page.evaluate(async()=>{const r=await axe.run('.ps-root',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});
  await item.page.screenshot({path:join(out,`studio-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>v.impact==='serious'||v.impact==='critical'),[]);assert.deepEqual(item.errors,[]);report.visual.push({width,theme,violations,errors:item.errors});await item.context.close();
 }
 const viewer=await pageFor('viewer',390);await viewer.page.getByRole('heading',{name:'Passport Studio',exact:true}).waitFor();assert.equal(await viewer.page.getByRole('button',{name:'Guardar borrador',exact:true}).isDisabled(),true);assert.equal(await viewer.page.getByRole('textbox',{name:'Nombre del producto',exact:false}).isDisabled(),true);report.steps.push('viewer_read_only');
 assert.deepEqual([...editor.errors,...reviewer.errors,...publisher.errors,...viewer.errors],[]);report.state=await state();report.status='passed';
}catch(error){report.status='failed';report.error=error.stack;const page=browser.contexts().at(-1)?.pages().at(-1);if(page){report.visibleError=await page.locator('body').innerText();await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw error;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
