import assert from 'node:assert/strict';
import test from 'node:test';
import {EnrollmentError,prepareEnrollment,confirmEnrollment,startPassportEnrollment,enrollmentFailure} from '../src/lib/passport-enrollment.ts';
import {studioFixture} from './passport-studio-fixtures.mjs';
const key='50000000-0000-4000-8000-000000000001',endpoint='/api/admin/batches/LOTE-ANDINA-26/passport-editorial';
function enrollment(){const s=studioFixture();return{contract:s.contract,scope:s.scope,actorId:s.actorId,capabilities:s.capabilities,currentPublicDigest:'b'.repeat(64),template:'agro',locale:'es-AR',document:s.draft.document};}
const attempt=()=>prepareEnrollment(enrollment(),endpoint,'qa-company','agro','es-AR',key);
function body(){const s=studioFixture();s.draft.revision=1;s.published.version=0;return{ok:true,snapshot:s,receipt:{id:'60000000-0000-4000-8000-000000000001',operationId:key,action:'start',committed:true,replayed:false}};}
const response=(data=body(),status=200,mode='production')=>Response.json(data,{status,headers:{'x-nexid-data-mode':mode}});
test('start attempt is immutable, scoped, and contains only the reviewed editorial choices',()=>{const a=attempt();assert.ok(Object.isFrozen(a)&&Object.isFrozen(a.body)&&Object.isFrozen(a.body.scope));assert.equal(a.path,endpoint+'/start?tenant=qa-company');assert.deepEqual(Object.keys(a.body).sort(),['action','expectedPublicDigest','locale','operationId','scope','template']);assert.equal(a.body.expectedPublicDigest,enrollment().currentPublicDigest);});
for(const mutate of [e=>e.capabilities.edit=false,e=>e.scope.tenantId='bad',e=>e.currentPublicDigest='bad'])test('invalid or read-only enrollment cannot construct an attempt '+mutate,()=>{const e=enrollment();mutate(e);assert.throws(()=>prepareEnrollment(e,endpoint,'qa-company','agro','es-AR',key));});
for(const path of ['/api/admin/batches/FOREIGN/passport-editorial','https://foreign.invalid/collect','/api/admin/users'])test('endpoint must belong to the exact enrolled batch '+path,()=>{assert.throws(()=>prepareEnrollment(enrollment(),path,'qa-company','agro','es-AR',key));});
test('an existing agro profile cannot silently switch to general; unknown locale and operation ID rejected',()=>{assert.throws(()=>prepareEnrollment(enrollment(),endpoint,'qa-company','general','es-AR',key));assert.throws(()=>prepareEnrollment(enrollment(),endpoint,'qa-company','agro','xx',key));assert.throws(()=>prepareEnrollment(enrollment(),endpoint,'qa-company','agro','es-AR','bad'));});
for(const [name,mutate] of [['demo',d=>d.demo=true],['missing receipt',d=>delete d.receipt],['uncommitted',d=>d.receipt.committed=false],['bad receipt ID',d=>d.receipt.id='bad'],['wrong key',d=>d.receipt.operationId=d.receipt.id],['wrong action',d=>d.receipt.action='publish'],['unknown replay',d=>delete d.receipt.replayed],['foreign actor',d=>d.snapshot.actorId='other'],['foreign tenant',d=>d.snapshot.scope.tenantId=d.receipt.id],['foreign batch',d=>d.snapshot.scope.batchId=d.receipt.id],['foreign BID',d=>d.snapshot.scope.bid='other'],['advanced revision',d=>d.snapshot.draft.revision=2],['published',d=>d.snapshot.draft.state='published'],['wrong locale',d=>d.snapshot.draft.document.locale='en']])test('unconfirmed start: '+name,()=>{const d=body();mutate(d);assert.throws(()=>confirmEnrollment(d,attempt()));});
test('exact committed start and original replay receipt both confirm version one only',()=>{for(const replayed of [false,true]){const d=body();d.receipt.replayed=replayed;assert.equal(confirmEnrollment(d,attempt()).draft.revision,1);}});
test('transport sends one private same-origin POST with the exact immutable command',async()=>{const a=attempt(),calls=[];await startPassportEnrollment(a,{fetcher:async(url,init)=>{calls.push({url,init});return response();}});assert.equal(calls.length,1);assert.equal(calls[0].url,a.path);assert.equal(calls[0].init.method,'POST');assert.equal(calls[0].init.credentials,'same-origin');assert.equal(calls[0].init.cache,'no-store');assert.equal(calls[0].init.redirect,'error');assert.equal(calls[0].init.headers['idempotency-key'],key);assert.deepEqual(JSON.parse(calls[0].init.body),a.body);});
for(const status of [400,401,403,404,409,413,422,429])test('confirmed rejection '+status+' cannot erase previous uncertainty',async()=>{let e;try{await startPassportEnrollment(attempt(),{fetcher:async()=>response({ok:false,reason:'editorial_rejected'},status)});}catch(x){e=x;}assert.ok(e instanceof EnrollmentError&&!e.uncertain);assert.equal(enrollmentFailure(e,false).uncertain,false);assert.equal(enrollmentFailure(e,true).uncertain,true);assert.equal(enrollmentFailure(e,true).accessLost,[401,403,404].includes(status));});
for(const status of [408,500,502,503])test('HTTP '+status+' remains an uncertain write',async()=>{await assert.rejects(startPassportEnrollment(attempt(),{fetcher:async()=>response({ok:false,reason:'editorial_unavailable'},status)}),e=>e.uncertain&&e.status===status);});
for(const mode of ['demo','fallback',''])test('successful response needs production provenance '+JSON.stringify(mode),async()=>{await assert.rejects(startPassportEnrollment(attempt(),{fetcher:async()=>response(body(),200,mode)}),e=>e.uncertain);});
test('HTML error does not become proof that the original command failed',async()=>{await assert.rejects(startPassportEnrollment(attempt(),{fetcher:async()=>new Response('<html>provider error</html>',{status:403,headers:{'content-type':'text/html'}})}),e=>e.uncertain&&e.status===403);});
for(const [name,bytes] of [['invalid UTF8',new Uint8Array([255,254])],['oversized','x'.repeat(262145)],['invalid JSON','{bad']])test(name+' cannot confirm a partial reply',async()=>{await assert.rejects(startPassportEnrollment(attempt(),{fetcher:async()=>new Response(bytes,{headers:{'content-type':'application/json','x-nexid-data-mode':'production'}})}),e=>e.uncertain);});
for(const phase of ['headers','body'])test('one deadline settles a noncooperative '+phase,async()=>{let calls=0;const fetcher=async()=>{calls++;return phase==='headers'?new Promise(()=>{}):new Response(new ReadableStream({pull(){return new Promise(()=>{});}}),{headers:{'content-type':'application/json','x-nexid-data-mode':'production'}});};await assert.rejects(startPassportEnrollment(attempt(),{fetcher,timeoutMs:20}),e=>e.code==='timeout'&&e.uncertain);assert.equal(calls,1);});
test('aborted caller sends nothing and a pending abort stays uncertain',async()=>{const early=new AbortController();early.abort();let calls=0;await assert.rejects(startPassportEnrollment(attempt(),{signal:early.signal,fetcher:async()=>{calls++;return response();}}),e=>e.code==='cancelled'&&!e.uncertain);assert.equal(calls,0);const live=new AbortController();const p=startPassportEnrollment(attempt(),{signal:live.signal,fetcher:async()=>{calls++;return new Promise(()=>{});}});live.abort();await assert.rejects(p,e=>e.code==='cancelled'&&e.uncertain);assert.equal(calls,1);});
test('late completion after deadline is consumed but cannot revive success',async()=>{let release,cancelled=false;const p=startPassportEnrollment(attempt(),{fetcher:()=>new Promise(r=>release=r),timeoutMs:20});await assert.rejects(p,e=>e.code==='timeout');release(new Response(new ReadableStream({cancel(){cancelled=true;}}),{headers:{'content-type':'application/json'}}));await new Promise(r=>setTimeout(r,5));assert.equal(cancelled,true);});
test('exact retry retains the payload and key after a lost response',async()=>{const calls=[];let n=0;const fetcher=async(url,init)=>{calls.push({url,body:init.body,key:init.headers['idempotency-key']});if(!n++)throw Error('connection lost');const d=body();d.receipt.replayed=true;return response(d);};const a=attempt();await assert.rejects(startPassportEnrollment(a,{fetcher}),e=>e.uncertain);await startPassportEnrollment(a,{fetcher});assert.deepEqual(calls[0],calls[1]);});
for(const mutate of [a=>a.path='https://foreign.invalid/collect',a=>a.path=endpoint+'/start?tenant=a&tenant=b',a=>a.body.action='publish',a=>a.body.extra='private',a=>a.body.scope.actorId='other'])test('invalid attempt is refused before transport '+mutate,async()=>{const a=structuredClone(attempt());mutate(a);let calls=0;await assert.rejects(startPassportEnrollment(a,{fetcher:async()=>{calls++;return response();}}),e=>!e.uncertain);assert.equal(calls,0);});
