import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';
import {studioDocument,studioFixture} from './passport-studio-fixtures.mjs';
import {updateField} from '../src/lib/passport-studio-contract.ts';
import {comparisonSources,comparisonSource,compareEditorialDocuments,filterEditorialDifferences} from '../src/lib/passport-studio-comparison.ts';
test('mirrored identity changes appear once without hiding an inconsistent alias',()=>{const a=studioDocument(),b=updateField(a,'identity.product_name','Nueva semilla');assert.equal(compareEditorialDocuments(a,b).length,1);b.agro_product_profile.productName='Diferente';const rows=compareEditorialDocuments(a,b);assert.equal(rows.length,2);assert.equal(rows[1].group,'consistency');});
test('added changed and removed fields retain their direction and exact values',()=>{const a=studioDocument(),b=studioDocument();b.identity.region=null;b.agro_product_profile.trainingUrl='https://example.invalid/training';b.agro_product_profile.technicalSheetUrl='https://example.invalid/new.pdf';const r=compareEditorialDocuments(a,b);assert.deepEqual(r.map(x=>x.kind).sort(),['added','changed','removed']);assert.equal(r.find(x=>x.field.endsWith('technicalSheetUrl')).link,true);});
test('ordered guidance items use real line breaks and are not collapsed into a set',()=>{const a=studioDocument(),b=studioDocument();a.agro_product_profile.ppe.items=['Primero','Después'];b.agro_product_profile.ppe.items=['Después','Primero'];const r=compareEditorialDocuments(a,b);assert.equal(r[0].before,'Primero\nDespués');assert.equal(r[0].after,'Después\nPrimero');});
test('metadata and removal of agro fields are visible across template changes',()=>{const a=studioDocument(),b={...structuredClone(a),template:'general',locale:'en',agro_product_profile:null};const rows=compareEditorialDocuments(a,b);assert.ok(rows.some(x=>x.field==='template'));assert.ok(rows.some(x=>x.field==='locale'));assert.ok(rows.some(x=>x.group==='documents'&&x.kind==='removed'));});
test('sources distinguish initial content, publication version, draft revision and local edits',()=>{const s=studioFixture();s.published.version=0;const working=updateField(s.draft.document,'identity.region','Otra región');const list=comparisonSources(s,working);assert.match(list[0].label,/inicial/);assert.equal(list[1].local,true);assert.equal(list[2].document.identity.region,s.draft.document.identity.region);assert.match(list[3].label,/Historial r2/);assert.ok(!list[3].label.includes('v2'));});
test('missing publication is not fabricated as an approved revision',()=>{const s=studioFixture();s.published=null;const source=comparisonSources(s,s.draft.document)[0];assert.equal(source.document,null);assert.match(source.label,/Sin versión publicada/);assert.ok(compareEditorialDocuments(null,s.draft.document).every(x=>x.kind==='added'));});
test('unknown or duplicate historical source keys are refused',()=>{const s=studioFixture();assert.throws(()=>comparisonSource(comparisonSources(s,s.draft.document),'history:foreign'));s.history.push(structuredClone(s.history[0]));assert.throws(()=>comparisonSources(s,s.draft.document));});
test('comparison never mutates saved working or published documents',()=>{const s=studioFixture(),original=JSON.stringify(s),working=updateField(s.draft.document,'identity.product_name','Otro nombre');const before=JSON.stringify(working);const sources=comparisonSources(s,working);compareEditorialDocuments(sources[0].document,sources[1].document);assert.equal(JSON.stringify(s),original);assert.equal(JSON.stringify(working),before);});
test('section and kind filters only affect visible differences and treat query as text',()=>{const a=studioDocument(),b=updateField(a,'identity.product_name','Nueva semilla');b.agro_product_profile.technicalSheetUrl=null;const rows=compareEditorialDocuments(a,b);assert.equal(filterEditorialDifferences(rows,'documents','removed','ficha').length,1);assert.equal(filterEditorialDifferences(rows,'all','all','.*').length,0);assert.equal(rows.length,2);assert.throws(()=>filterEditorialDifferences(rows,'unknown','all',''));assert.throws(()=>filterEditorialDifferences(rows,'all','all','x'.repeat(161)));});
test('unknown technical fields are rejected instead of appearing in editorial comparisons',()=>{const a=studioDocument(),b=studioDocument();b.secretKey='NOT_EDITORIAL';assert.throws(()=>compareEditorialDocuments(a,b));});
test('dialog cancel is reset and conflict reread is explicit',async()=>{const s=await readFile(new URL('../src/components/passport-studio/passport-studio-view.ts',import.meta.url),'utf8');assert.match(s,/dataset.do==='reload'&&conflict/);assert.match(s,/dialog.returnValue='';dialog.showModal/);assert.match(s,/addEventListener\('cancel'/);assert.match(s,/if\(reloadRequested\)/);});
test('comparison module uses only existing editorial projections, without storage or network',async()=>{const s=await readFile(new URL('../src/lib/passport-studio-comparison.ts',import.meta.url),'utf8');assert.doesNotMatch(s,/fetch\(|localStorage|sessionStorage|XMLHttpRequest|sendBeacon/);assert.match(s,/readStudioDocument/);});

test('unfinished local guidance remains comparable while invalid persisted sources are refused',()=>{const a=studioDocument(),b=studioDocument();b.agro_product_profile.ppe.items=Array.from({length:13},(_,i)=>'Indicación '+i);assert.throws(()=>compareEditorialDocuments(a,b));const r=compareEditorialDocuments(a,b,{after:true});assert.equal(r[0].after.split('\n').length,13);assert.equal(b.agro_product_profile.ppe.items.length,13);});
