import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {build} from 'esbuild';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import {studioFixture} from './passport-studio-fixtures.mjs';
assert.ok(process.env.PLAYWRIGHT_MODULE&&process.env.AXE_MODULE_PATH,'Installed browser tooling required');
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
const dashboard=fileURLToPath(new URL('../',import.meta.url)),root=resolve(dashboard,'../..'),output=resolve(process.env.QA_OUTPUT||'artifacts/passport-enrollment');await mkdir(output,{recursive:true});
const fixture=`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{PassportStudioEntry}from'./src/components/passport-studio/passport-studio-entry';function App(){const[p,set]=useState(window.__initial);window.__change=set;return <main style={{padding:16,maxWidth:1280,margin:'auto'}}><aside style={{marginBottom:12}}>QA local: contenido y sesión sintéticos. No modifica lotes productivos.</aside><PassportStudioEntry {...p}/></main>};createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);`;
const bundle=await build({stdin:{contents:fixture,loader:'tsx',resolveDir:dashboard},bundle:true,write:false,outfile:'fixture.js',format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"development"','process.env':'{}'},logLevel:'silent'});
const css=(await postcss([tailwindcss({content:[join(dashboard,'src/**/*.{ts,tsx}').replaceAll('\\','/'),{raw:fixture,extension:'tsx'}],darkMode:['selector','[data-theme="dark"]'],theme:{extend:{colors:{brand:{dark:'#020617',card:'#0f172a',border:'#1e293b',cyan:'#06b6d4',blue:'#3b82f6'}}}},plugins:[]})]).process(await readFile(join(dashboard,'src/app/globals.css'),'utf8'),{from:undefined})).css+(bundle.outputFiles.find(f=>f.path.endsWith('.css'))?.text||'');
const js=bundle.outputFiles.find(f=>f.path.endsWith('.js')).contents;
const server=createServer((req,res)=>{const u=new URL(req.url,'http://qa.invalid');if(req.method!=='GET'){res.writeHead(405);return res.end();}if(u.pathname==='/fixture.js'){res.setHeader('content-type','text/javascript');return res.end(js);}if(u.pathname==='/favicon.ico'){res.writeHead(204);return res.end();}if(u.pathname!=='/'){res.writeHead(404);return res.end();}const theme=u.searchParams.get('theme')==='dark'?'dark':'light';res.setHeader('content-type','text/html;charset=utf-8');res.end(`<!doctype html><html lang="es-AR" data-theme="${theme}" class="theme-${theme}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Inicio editorial · QA</title><style>${css}</style></head><body><div id="root"></div><script src="/fixture.js"></script></body></html>`);});
await new Promise((done,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',done);});const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
const report={localOnly:true,syntheticSessionsAndTransport:true,actualComponents:['PassportStudioEntry','PassportStudio'],strictMode:true,productionUsed:false,checks:[],views:[],clientErrors:[],unexpectedRequests:[]};
const check=(v,name)=>report.checks.push({name,passed:Boolean(v)}),tick=page=>page.evaluate(()=>new Promise(done=>requestAnimationFrame(()=>requestAnimationFrame(done))));
function initial(){const s=studioFixture();s.scope.tenantLabel='Empresa de prueba';s.draft.document={...s.draft.document,template:'general',agro_product_profile:null};s.draft.document.identity.product_name='Envase Ámbar';return{initial:null,enrollment:{contract:s.contract,scope:s.scope,actorId:s.actorId,capabilities:s.capabilities,currentPublicDigest:'b'.repeat(64),template:'general',locale:'es-AR',document:s.draft.document},endpoint:'/api/admin/batches/'+s.scope.bid+'/passport-editorial',tenantSlug:'qa-company'};}
function reply(props,command){const s=studioFixture();s.scope=props.enrollment.scope;s.actorId=props.enrollment.actorId;s.capabilities=props.enrollment.capabilities;s.draft={...s.draft,id:randomUUID(),revision:1,state:'draft',createdBy:s.actorId,lastEditorId:s.actorId,submittedBy:null,document:{...props.enrollment.document,template:command.template,locale:command.locale}};s.published={version:0,contentDigest:props.enrollment.currentPublicDigest,document:s.draft.document};s.history=[];return{ok:true,snapshot:s,receipt:{id:randomUUID(),operationId:command.operationId,action:'start',committed:true,replayed:false}};}
async function scenario(props=initial(),width=390,theme='light'){
 const context=await browser.newContext({viewport:{width,height:1000},locale:'es-AR',reducedMotion:'reduce',serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(7000);
 await page.addInitScript(p=>{window.__initial=p;const real=window.fetch.bind(window);window.fetch=(url,init={})=>real(url,window.__ignoreAbort?{...init,signal:undefined}:init);},props);
 const state={mode:'success',calls:[],pending:[],responses:[],receipts:new Map()};page.on('pageerror',e=>report.clientErrors.push(e.message));
 await page.route('**/*',async route=>{const request=route.request(),u=new URL(request.url());
  if(u.origin===origin&&request.method()==='POST'&&u.pathname===props.endpoint+'/start'){
   const command=request.postDataJSON();state.calls.push({url:u.pathname+u.search,command,key:request.headers()['idempotency-key']});
   if(state.mode==='delayed'){state.pending.push({route,command});return;}
   const rejected=['503','403','409','408'].includes(state.mode),status=rejected?Number(state.mode):200;
   const replayed=state.receipts.has(command.operationId);
   if(!rejected&&!replayed)state.receipts.set(command.operationId,reply(props,command));
   const body=rejected?{ok:false,reason:status===409?'editorial_already_managed':status===403?'editorial_action_forbidden':'editorial_unavailable'}:structuredClone(state.receipts.get(command.operationId));
   if(body.receipt)body.receipt.replayed=replayed;
   if(state.mode==='commit-lost')return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,reason:'editorial_response_lost'})});
   if(state.mode==='bad-receipt')body.receipt.id='invalid';if(state.mode==='foreign')body.snapshot.scope={...body.snapshot.scope,tenantId:randomUUID()};
   state.responses.push(body);return route.fulfill({status,contentType:'application/json',headers:{'x-nexid-data-mode':state.mode==='demo'?'demo':'production'},body:JSON.stringify(body)});
  }
  if(u.origin===origin&&request.method()==='GET'&&['/','/fixture.js','/favicon.ico'].includes(u.pathname))return route.continue();report.unexpectedRequests.push(request.method()+' '+u.pathname);return route.abort();
 });
 await page.goto(origin+'/?theme='+theme);await page.getByTestId('passport-enrollment').waitFor();return{page,context,state,props,width,theme};
}
async function send(t){await t.page.getByRole('checkbox').check();await t.page.getByRole('button',{name:/^(Iniciar Passport Studio|Revisar inicio editorial)$/}).click();if(await t.page.getByTestId('enrollment-confirm').count())await t.page.getByTestId('enrollment-confirm').click();}
async function settled(t){await t.page.waitForFunction(()=>!document.querySelector('[data-testid="passport-enrollment"] button')?.textContent.includes('Creando'));await new Promise(r=>setTimeout(r,100));await tick(t.page);}
try{
 for(const mode of ['demo','bad-receipt']){const t=await scenario();t.state.mode=mode;await send(t);await settled(t);check(!await t.page.locator('[data-passport-studio-host]').count(),mode+' cannot confirm editorial governance');await t.context.close();}
 {const t=await scenario();t.state.mode='503';await send(t);await t.page.getByRole('button',{name:'Reconciliar el mismo inicio'}).waitFor();t.state.mode='403';await t.page.getByRole('button',{name:'Reconciliar el mismo inicio'}).click();await settled(t);check(await t.page.getByRole('button',{name:'Reconciliar el mismo inicio'}).count()===1,'A denial after an uncertain result retains the exact pending operation');check(t.state.calls.length===2&&t.state.calls[0].key===t.state.calls[1].key,'Retry uses the original idempotency key');t.state.mode='503';await t.page.getByRole('button',{name:'Reconciliar el mismo inicio'}).click();await settled(t);check(!(await t.page.getByTestId('passport-enrollment').innerText()).includes(t.props.enrollment.document.identity.product_name),'A subsequent outage cannot restore previously withdrawn product data');await t.context.close();}
 {const t=await scenario();await t.page.getByRole('checkbox').check();const next=initial();next.enrollment={...next.enrollment,actorId:'qa_other_editor',scope:{...next.enrollment.scope,tenantId:'10000000-0000-4000-8000-000000000002'}};await t.page.evaluate(p=>window.__change(p),next);await tick(t.page);check(!await t.page.getByRole('checkbox').isChecked(),'Changing authenticated company or actor removes the old confirmation');check(t.state.calls.length===0,'Context changes never start governance automatically');await t.context.close();}
 await extendedAcceptance();
 check(!report.clientErrors.length,'No browser exceptions');check(!report.unexpectedRequests.length,'No unexpected or external requests');
}finally{await browser.close();await new Promise(done=>server.close(done));await writeFile(join(output,'report.json'),JSON.stringify(report,null,2));}
console.log(JSON.stringify({checks:report.checks.length,failed:report.checks.filter(c=>!c.passed),views:report.views.length,output},null,2));assert.ok(report.checks.every(c=>c.passed));

async function inspect(t,name){
 await t.page.addScriptTag({content:axe});
 const violations=await t.page.evaluate(async()=>(await axe.run('[data-testid="passport-enrollment"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)})));
 check(!violations.length,name+' '+t.width+' '+t.theme+': no axe violations');
 check(await t.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' '+t.width+' '+t.theme+': no horizontal overflow');
 const clipped=await t.page.locator('[data-testid="passport-enrollment"] button,[data-testid="passport-enrollment"] select,[data-testid="passport-enrollment"] input').evaluateAll(nodes=>nodes.filter(n=>{const r=n.getBoundingClientRect();return r.width>0&&(r.left<0||r.right>innerWidth+1);}).length);
 check(!clipped,name+' '+t.width+' '+t.theme+': no clipped controls');const file=`${name}-${t.width}-${t.theme}.png`;await t.page.screenshot({path:join(output,file),fullPage:true});report.views.push({name,width:t.width,theme:t.theme,violations,file});
}
async function extendedAcceptance(){
 for(const theme of ['light','dark'])for(const width of [320,390,768,1440]){
  const t=await scenario(initial(),width,theme);check(t.state.calls.length===0,'Mount and StrictMode never start governance');
  await t.page.getByRole('checkbox').focus();await t.page.keyboard.press('Space');await t.page.getByTestId('enrollment-review').click();await tick(t.page);
  check(await t.page.locator('#enrollment-confirm-title').evaluate(n=>document.activeElement===n),'Review receives keyboard focus');check(t.state.calls.length===0,'Reviewing has no backend side effects');await inspect(t,'confirm');
  await t.page.keyboard.press('Escape');await tick(t.page);check(!await t.page.getByTestId('enrollment-confirmation').count(),'Escape closes the review only');check(await t.page.getByTestId('enrollment-review').evaluate(n=>document.activeElement===n),'Escape returns keyboard focus');
  await t.page.getByLabel('Idioma del contenido').selectOption('en');check(!await t.page.getByRole('checkbox').isChecked(),'Changing locale requires a fresh acknowledgement');
  await t.page.getByRole('checkbox').check();await t.page.getByTestId('enrollment-review').click();t.state.mode='commit-lost';
  await t.page.getByTestId('enrollment-confirm').evaluate(b=>{b.click();b.click();});await t.page.getByTestId('enrollment-retry').waitFor();check(t.state.calls.length===1&&t.state.receipts.size===1,'Double confirm sends exactly one operation');check(await t.page.getByLabel('Idioma del contenido').isDisabled(),'Uncertain start locks its reviewed choices');await inspect(t,'uncertain');
  t.state.mode='409';await t.page.getByTestId('enrollment-retry').click();await settled(t);check(await t.page.getByTestId('enrollment-retry').count()===1,'Later conflict never erases original uncertainty');
  t.state.mode='success';await t.page.getByTestId('enrollment-retry').click();await t.page.locator('[data-passport-studio-host]').waitFor();check(t.state.receipts.size===1&&new Set(t.state.calls.map(c=>c.key)).size===1,'Reconciliation recovers one existing draft, not a duplicate');check(t.state.calls.every(c=>c.command.locale==='en'),'Reconciliation retains the reviewed locale');await t.context.close();
 }
 for(const mode of ['403','409','408']){const t=await scenario();t.state.mode=mode;await send(t);await settled(t);check(!await t.page.locator('[data-passport-studio-host]').count(),'Unconfirmed '+mode+' never opens an editor');if(mode==='403')check(!(await t.page.locator('main').innerText()).includes(t.props.enrollment.document.identity.product_name),'Denial removes the previous product data');if(mode==='409')check(await t.page.getByRole('link',{name:'Volver a consultar el pasaporte'}).getAttribute('href')==='/batches/LOTE-ANDINA-26/passport?tenant=qa-company','Conflict reread retains the requested batch and company');await inspect(t,'failure-'+mode);await t.context.close();}
 const readonly=initial();readonly.enrollment.capabilities.edit=false;const r=await scenario(readonly);check(await r.page.getByTestId('enrollment-review').isDisabled(),'Read-only account cannot initiate enrollment');await r.page.getByTestId('enrollment-review').evaluate(b=>{b.disabled=false;b.click();});check(!await r.page.getByTestId('enrollment-confirmation').count()&&r.state.calls.length===0,'Forced control does not bypass account capabilities');await inspect(r,'readonly');await r.context.close();
 const changed=await scenario();await changed.page.getByRole('checkbox').check();await changed.page.getByTestId('enrollment-review').click();await changed.page.evaluate(p=>window.__change(p),structuredClone(changed.props));await tick(changed.page);check(await changed.page.getByTestId('enrollment-confirmation').count()===1,'Equivalent props rerender preserves the review');const b=initial();b.enrollment.actorId='other-editor';await changed.page.evaluate(p=>window.__change(p),b);await changed.page.evaluate(p=>window.__change(p),initial());await tick(changed.page);check(!await changed.page.getByRole('checkbox').isChecked()&&!await changed.page.getByTestId('enrollment-confirmation').count(),'A to B to A does not restore old consent');await changed.context.close();
 const late=await scenario();await late.page.evaluate(()=>window.__ignoreAbort=true);late.state.mode='delayed';await send(late);await late.page.waitForFunction(()=>document.querySelector('[aria-busy="true"]'));const next=initial();next.enrollment.actorId='different-editor';next.enrollment.document.identity.product_name='Otro producto';await late.page.evaluate(p=>window.__change(p),next);await tick(late.page);for(const pending of late.state.pending.splice(0))await pending.route.fulfill({status:200,contentType:'application/json',headers:{'x-nexid-data-mode':'production'},body:JSON.stringify(reply(late.props,pending.command))}).catch(()=>{});await tick(late.page);check(!await late.page.locator('[data-passport-studio-host]').count()&&(await late.page.getByTestId('passport-enrollment').innerText()).includes('Otro producto'),'A late start receipt cannot populate a different authenticated context');await late.context.close();
 const long=initial();long.enrollment.scope.bid='B'.repeat(160);long.enrollment.scope.tenantLabel='Empresa '.repeat(20);long.enrollment.document.identity.product_name='Producto '.repeat(17);long.endpoint='/api/admin/batches/'+long.enrollment.scope.bid+'/passport-editorial';const l=await scenario(long,320,'dark');await inspect(l,'long-identifiers');await l.context.close();
}
