import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {studioDocument,studioFixture} from './passport-studio-fixtures.mjs';
import {getField} from '../src/lib/passport-studio-contract.ts';
import {preparePublishedReuse,reusableFields,REUSE_FIELDS,reuseReference,parsePublishedLibrary} from '../src/lib/passport-reuse.ts';
import {requiredPermissionForAdminResource} from '../src/lib/permission-policy.ts';
const source=()=>{const d=studioDocument();d.identity.product_name='Otro nombre publicado';d.agro_product_profile.productName=d.identity.product_name;d.identity.public_lot_label='SOURCE-LOT';d.identity.sku='SOURCE-SKU';d.agro_product_profile.batchLot='SOURCE-LOT';d.agro_product_profile.sku='SOURCE-SKU';d.agro_product_profile.gtin='01234567890123';d.agro_product_profile.productionDate='2000-01-01';d.agro_product_profile.expirationDate='2001-01-01';d.agro_product_profile.distributor='SOURCE-DISTRIBUTOR';d.agro_product_profile.recallStatusUrl='https://example.invalid/recall-source';d.agro_product_profile.technicalSheetUrl='https://example.invalid/new-tech.pdf';return d;};
const protectedFields=['identity.public_lot_label','identity.sku','agro_product_profile.gtin','agro_product_profile.productionDate','agro_product_profile.expirationDate','agro_product_profile.distributor','agro_product_profile.authorizedChannel','agro_product_profile.recallStatusUrl','agro_product_profile.loyaltyUrl'];
test('all selected permitted content changes while lot-specific fields remain byte-equivalent',()=>{const a=studioDocument(),s=source();const selected=reusableFields(a,s).map(f=>f.path);const result=preparePublishedReuse(a,s,selected);assert.equal(result.identity.product_name,s.identity.product_name);assert.equal(result.agro_product_profile.productName,s.identity.product_name);for(const path of protectedFields)assert.deepEqual(getField(result,path),getField(a,path));assert.equal(result.template,a.template);assert.equal(result.locale,a.locale);});
test('no empty, duplicate, protected or nonexistent fields can be applied',()=>{const a=studioDocument(),s=source();for(const paths of [[],['identity.sku'],['identity.product_name','identity.product_name'],['meta_key_ct'],['agro_product_profile.gtin']])assert.throws(()=>preparePublishedReuse(a,s,paths));});
test('only explicitly selected fields change and neither input is mutated',()=>{const a=studioDocument(),s=source(),before=JSON.stringify([a,s]);const result=preparePublishedReuse(a,s,['agro_product_profile.technicalSheetUrl']);assert.equal(result.identity.product_name,a.identity.product_name);assert.equal(result.agro_product_profile.technicalSheetUrl,s.agro_product_profile.technicalSheetUrl);assert.equal(JSON.stringify([a,s]),before);});
test('null values cannot silently erase target fields; identical values offer nothing',()=>{const a=studioDocument(),s=structuredClone(a);s.agro_product_profile.technicalSheetUrl=null;assert.deepEqual(reusableFields(a,s),[]);assert.throws(()=>preparePublishedReuse(a,s,['agro_product_profile.technicalSheetUrl']));});
test('template language and unknown technical fields are never imported',()=>{const a=studioDocument();for(const mutate of [s=>s.locale='en',s=>{s.template='general';s.agro_product_profile=null;},s=>s.sdm_config={secret:1}]){const s=source();mutate(s);assert.throws(()=>preparePublishedReuse(a,s,['identity.product_name']));}});
test('URL comparison treats malicious strings as text, not instructions or network',()=>{const a=studioDocument(),s=source();s.identity.product_name='<script>alert(1)</script>';s.agro_product_profile.productName=s.identity.product_name;const r=preparePublishedReuse(a,s,['identity.product_name']);assert.equal(r.identity.product_name,s.identity.product_name);assert.equal(reusableFields(a,s).find(f=>f.path==='identity.product_name').after,s.identity.product_name);});
function payload(){const t=studioFixture();return {target:t,data:{ok:true,protocol:'nexid.passport-library.v1',source:'database',readOnly:true,observedAt:'2026-09-20T12:00:00Z',q:'',hasMore:false,scope:{...t.scope,tenant:'qa-company',draftId:t.draft.id,revision:t.draft.revision,contentDigest:t.draft.contentDigest,template:t.draft.document.template,locale:t.draft.document.locale},items:[{id:'80000000-0000-4000-8000-000000000001',bid:'SOURCE',product:'Origen',version:1,digest:'a'.repeat(64),template:t.draft.document.template,locale:t.draft.document.locale,publishedAt:'2026-09-19T12:00:00Z'}]}};}
test('library response must match the exact destination draft revision and scope',()=>{const {target,data}=payload();assert.equal(parsePublishedLibrary(data,target,'').items.length,1);for(const patch of [{revision:999},{batchId:'80000000-0000-4000-8000-000000000002'},{tenantId:'80000000-0000-4000-8000-000000000002'},{locale:'en'}])assert.throws(()=>parsePublishedLibrary({...data,scope:{...data.scope,...patch}},target,''));});
test('selected source is not silently updated to a different publication or digest',()=>{const {target,data}=payload(),selected=data.items[0];const detail={...data,items:[{...selected,document:source()}]};assert.equal(parsePublishedLibrary(detail,target,'',selected).items[0].version,1);assert.throws(()=>parsePublishedLibrary({...detail,items:[{...detail.items[0],version:2}]},target,'',selected));});
test('reference is an editor declaration for the next ordinary saved revision, not approval transfer',()=>{const {data}=payload(),note=reuseReference(data.items[0],2);assert.match(note,/declarada por el editor/);assert.match(note,/No transfiere la aprobación/);assert.ok(note.length<800);});
test('BFF capability is limited to existing content editing and comparison fetches no external URLs',async()=>{assert.equal(requiredPermissionForAdminResource('GET','batches/QA/passport-library'),'batch.product.configure');const s=await readFile(new URL('../src/components/passport-studio/published-reuse-dialog.ts',import.meta.url),'utf8');assert.doesNotMatch(s,/localStorage|setInterval|img src|method:'POST'|sendBeacon/);assert.match(s,/selected=new Set/);assert.match(s,/fetchSource\(source,true\)/);});
