import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';import {join} from 'node:path';
const base='http://localhost:3432',api='http://127.0.0.1:4732',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,realPostgres:true,realLibraryHandler:true,checks:[],visual:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json(),studio=p=>p.locator('[data-passport-studio-host] > section.ps-root:visible'),dialog=p=>p.getByRole('dialog',{name:'Reutilizar contenido publicado',exact:true});
async function open(role='editor'){const c=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',locale:'es-AR',serviceWorkers:'block'});await c.addCookies([{name:'nexid_dashboard_session',value:'queue-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await p.goto(base+'/batches/AGRO-TARGET/passport?tenant=queue-qa',{waitUntil:'load',timeout:90000});await studio(p).getByRole('heading',{name:'Passport Studio',exact:true}).waitFor();return {p,c,errors};}
async function search(p){await studio(p).getByRole('button',{name:'Reutilizar contenido',exact:true}).click();await dialog(p).getByRole('button',{name:'Buscar publicaciones',exact:true}).click();await dialog(p).getByRole('button',{name:/Agro AGRO-SOURCE/}).waitFor();await dialog(p).getByRole('button',{name:/Agro AGRO-SOURCE/}).click();await dialog(p).getByRole('checkbox',{name:/Nombre del producto/}).waitFor();}
async function save(p){await studio(p).getByRole('button',{name:'Guardar borrador',exact:true}).click();await p.getByRole('dialog',{name:'Guardar borrador',exact:true}).getByRole('button',{name:'Confirmar',exact:true}).click();}
try{
 const editor=await open(),p=editor.p,original=await state();
 await studio(p).getByRole('textbox',{name:'Origen declarado',exact:true}).fill('Mi edición local que se conserva');const before=await state();await search(p);assert.equal(await dialog(p).locator('input[type=checkbox]:checked').count(),0);assert.equal(await dialog(p).getByRole('button',{name:'Aplicar campos al borrador'}).isDisabled(),true);for(const field of ['SKU','GTIN','Fecha de vencimiento','Lote comercial','Avisos del producto'])assert.equal(await dialog(p).getByRole('checkbox',{name:field,exact:true}).count(),0);
 await dialog(p).getByRole('checkbox',{name:/Nombre del producto/}).check();await dialog(p).getByRole('checkbox',{name:/Ficha técnica/}).check();assert.equal((await state()).writes,before.writes);report.checks.push('Only published same-company matching-template content is offered, with no preselection or operational identifiers');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1000});await p.evaluate(t=>{document.documentElement.dataset.theme=t;document.documentElement.classList.toggle('theme-light',t==='light');document.documentElement.classList.toggle('theme-dark',t==='dark');},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('dialog[open]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`reuse-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}
 await p.keyboard.press('Escape');await dialog(p).waitFor({state:'hidden'});assert.equal(await studio(p).getByRole('textbox',{name:'Origen declarado',exact:true}).inputValue(),'Mi edición local que se conserva');assert.equal((await state()).writes,before.writes);report.checks.push('Cancel preserves existing unsaved destination edits without saving or publishing');
 await search(p);await dialog(p).getByRole('checkbox',{name:/Nombre del producto/}).check();await dialog(p).getByRole('checkbox',{name:/Ficha técnica/}).check();await dialog(p).getByRole('button',{name:'Aplicar campos al borrador',exact:true}).click();await dialog(p).waitFor({state:'hidden'});await studio(p).getByText(/2 campos preparados desde/).waitFor();assert.equal((await state()).writes,before.writes);await studio(p).getByRole('button',{name:'Identidad',exact:true}).click();assert.equal(await studio(p).getByRole('textbox',{name:'Nombre del producto',exact:false}).inputValue(),'Agro AGRO-SOURCE');assert.equal(await studio(p).getByRole('textbox',{name:'SKU / referencia',exact:true}).inputValue(),original.target.draft.document.identity.sku);assert.equal(await studio(p).getByRole('textbox',{name:'Origen declarado',exact:true}).inputValue(),'Mi edición local que se conserva');report.checks.push('Apply revalidates the selected publication and changes only chosen fields in the local destination draft');
 await fetch(api+'/qa-mode?lost=1',{method:'POST'});await save(p);await studio(p).getByText('No se confirmó la operación.',{exact:true}).waitFor();await studio(p).getByRole('button',{name:'Reintentar el mismo intento',exact:true}).click();await studio(p).getByText('El servidor confirmó el intento anterior; no se duplicó.',{exact:true}).waitFor();const persisted=await state();assert.equal(persisted.target.history.filter(h=>h.action==='save').length,1);assert.match(persisted.target.history[0].note,/Última reutilización declarada/);assert.equal(persisted.target.draft.state,'draft');assert.deepEqual(persisted.product,original.product);for(const k of ['gtin','productionDate','expirationDate','distributor','authorizedChannel','recallStatusUrl'])assert.equal(persisted.target.draft.document.agro_product_profile[k],original.target.draft.document.agro_product_profile[k]);report.checks.push('Ordinary durable save records the editor-declared source reference; lost response replay creates one revision and leaves public content and protected fields intact');
 // Source changes after selection must invalidate the local preparation.
 await studio(p).getByRole('button',{name:'Reutilizar contenido',exact:true}).click();await dialog(p).getByRole('button',{name:'Buscar publicaciones',exact:true}).click();await dialog(p).getByRole('button',{name:/Agro AGRO-SOURCE/}).click();await dialog(p).getByRole('checkbox',{name:/Origen declarado/}).check();await fetch(api+'/qa-source-republish',{method:'POST'});await dialog(p).getByRole('button',{name:'Aplicar campos al borrador'}).click();await dialog(p).getByRole('status').filter({hasText:'La fuente o la revisión cambiaron'}).waitFor();assert.equal(await dialog(p).getByRole('button',{name:'Aplicar campos al borrador'}).isDisabled(),true);await p.keyboard.press('Escape');await studio(p).getByRole('button',{name:'Identidad',exact:true}).click();assert.equal(await studio(p).getByRole('textbox',{name:'Origen declarado',exact:true}).inputValue(),'Mi edición local que se conserva');report.checks.push('A republished source cannot silently replace the version that the user reviewed');
 await studio(p).getByRole('button',{name:'Reutilizar contenido',exact:true}).click();await dialog(p).getByRole('button',{name:'Buscar publicaciones',exact:true}).click();await dialog(p).getByRole('button',{name:/Nombre publicado actualizado/}).click();await dialog(p).getByRole('checkbox',{name:/Nombre del producto/}).check();await fetch(api+'/qa-target-change',{method:'POST'});await dialog(p).getByRole('button',{name:'Aplicar campos al borrador'}).click();await dialog(p).getByRole('status').filter({hasText:'No se confirmó una fuente publicada compatible'}).waitFor();await p.keyboard.press('Escape');assert.equal(await studio(p).getByRole('textbox',{name:'Nombre del producto',exact:false}).inputValue(),'Agro AGRO-SOURCE');report.checks.push('Another editor changing the destination invalidates reuse rather than merging into an unconfirmed revision');
 await p.reload({waitUntil:'load'});await studio(p).getByRole('heading',{name:'Passport Studio',exact:true}).waitFor();await studio(p).getByRole('button',{name:'Reutilizar contenido'}).click();await fetch(api+'/qa-mode?unavailable=1',{method:'POST'});await dialog(p).getByRole('button',{name:'Buscar publicaciones'}).click();await dialog(p).getByRole('status').filter({hasText:'No se pudo confirmar'}).waitFor();assert.equal(await dialog(p).locator('[data-source-index]').count(),0);await fetch(api+'/qa-mode',{method:'POST'});await p.keyboard.press('Escape');
 const viewer=await open('reader');assert.equal(await studio(viewer.p).getByRole('button',{name:'Reutilizar contenido'}).isDisabled(),true);const denied=await viewer.c.request.get(base+'/api/admin/batches/AGRO-TARGET/passport-library?tenant=queue-qa');assert.equal(denied.status(),403);const foreign=await editor.c.request.get(base+'/api/admin/batches/AGRO-TARGET/passport-library?tenant=other-queue');assert.equal(foreign.status(),403);assert.deepEqual(editor.errors,[]);assert.deepEqual(viewer.errors,[]);report.checks.push('Read-only and cross-tenant access remain rejected; unavailable sources are not shown as successful empty content');
 await viewer.c.close();await editor.c.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,10000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
