// Actual Studio presenter, Next/BFF and current editorial service over disposable PostgreSQL.
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3387',api='http://127.0.0.1:4487',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,realEditorialService:true,realPostgres:true,syntheticSessions:true,checks:[],visual:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json(),root=p=>p.locator('.ps-root:visible');
async function open(role='editor',width=1440){const context=await browser.newContext({viewport:{width,height:1040},locale:'es-AR',reducedMotion:'reduce',serviceWorkers:'block'});await context.addCookies([{name:'nexid_dashboard_session',value:'local-studio-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await p.goto(base+'/batches/QA-PASSPORT/passport?tenant=qa-company',{waitUntil:'load',timeout:90000});return {p,context,errors};}
async function action(p,label){await root(p).getByRole('button',{name:label,exact:true}).click();const dialog=p.getByRole('dialog');await dialog.waitFor();return dialog;}
async function confirm(p,label){const dialog=await action(p,label);await dialog.getByRole('button',{name:'Confirmar',exact:true}).click();}
async function saved(p){await root(p).getByText('Borrador guardado. El pasaporte publicado no cambió.',{exact:true}).waitFor();}
try{
 const editor=await open(),p=editor.p;await p.getByRole('heading',{name:'Prepará hoy. Publicá con confianza.'}).waitFor();await p.getByRole('checkbox').check();await p.getByRole('button',{name:'Iniciar Passport Studio',exact:true}).click();await root(p).getByRole('heading',{name:'Passport Studio',exact:true}).waitFor();
 const initial=await state();assert.equal(initial.historyCount,1);
 await root(p).getByRole('textbox',{name:'Nombre del producto',exact:false}).fill('Semilla Horizonte revisión 1');await root(p).getByRole('textbox',{name:'Origen declarado',exact:true}).fill('Origen editorial de revisión 1');
 await root(p).getByRole('button',{name:'Documentos',exact:true}).click();await root(p).getByRole('textbox',{name:'Ficha técnica',exact:true}).fill('https://example.invalid/technical-v1.pdf');
 await root(p).getByRole('button',{name:'Cambios',exact:true}).click();await root(p).getByRole('combobox',{name:'Documento base de comparación'}).selectOption('saved');await root(p).getByRole('combobox',{name:'Documento de destino de comparación'}).selectOption('working');
 const beforeCompare=await state();assert.equal(await root(p).locator('[data-diff-field]').count(),3);assert.match(await root(p).innerText(),/Incluye trabajo local sin guardar/);
 await root(p).getByRole('combobox',{name:'Filtrar diferencias por sección'}).selectOption('documents');assert.equal(await root(p).locator('[data-diff-field]').count(),1);await root(p).getByRole('searchbox',{name:'Buscar en las diferencias'}).fill('no coincide');assert.equal(await root(p).locator('[data-diff-field]').count(),0);await root(p).getByRole('button',{name:'Mostrar todas las diferencias',exact:true}).click();assert.equal(await root(p).locator('[data-diff-field]').count(),3);
 await root(p).getByRole('button',{name:'Intercambiar documentos comparados'}).click();assert.match(await root(p).locator('[data-diff-field="agro_product_profile.technicalSheetUrl"]').innerText(),/Retirado/);await root(p).getByRole('button',{name:'Intercambiar documentos comparados'}).click();const afterCompare=await state();assert.equal(afterCompare.reads,beforeCompare.reads);assert.equal(afterCompare.writes,beforeCompare.writes);report.checks.push('Working-versus-saved comparison, filters and direction swap are local and preserve unsaved content');
 await root(p).getByRole('button',{name:'Documentos',exact:true}).click();await root(p).getByRole('textbox',{name:'Indicaciones de protección · una por línea',exact:true}).fill(Array.from({length:13},(_,i)=>'Indicación '+i).join('\n'));await root(p).getByRole('button',{name:'Cambios',exact:true}).click();assert.match(await root(p).locator('[data-diff-field="agro_product_profile.ppe.items"]').innerText(),/Indicación 12/);await root(p).getByRole('button',{name:'Documentos',exact:true}).click();await root(p).getByRole('textbox',{name:'Indicaciones de protección · una por línea',exact:true}).fill('');await root(p).getByRole('button',{name:'Cambios',exact:true}).click();report.checks.push('Invalid unfinished local guidance stays visible for correction without crashing the comparison or being silently shortened');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1040});await p.evaluate(t=>{document.documentElement.dataset.theme=t;document.documentElement.classList.toggle('theme-light',t==='light');document.documentElement.classList.toggle('theme-dark',t==='dark');window.scrollTo(0,0);},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('.ps-root',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`comparison-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}
 await confirm(p,'Guardar borrador');await saved(p);assert.equal((await state()).product.product_name,initial.product.product_name);
 const beforeEscape=(await state()).writes;await action(p,'Enviar a revisión');await p.keyboard.press('Escape');await p.getByRole('dialog').waitFor({state:'hidden'});assert.equal((await state()).writes,beforeEscape);assert.equal(await root(p).getByRole('button',{name:'Enviar a revisión',exact:true}).count(),1);report.checks.push('Escape after a previously confirmed save does not replay the old dialog return value or submit another operation');
 const submit=await action(p,'Enviar a revisión');assert.match(await submit.innerText(),/Trabajo guardado r/);await submit.getByRole('button',{name:'Confirmar',exact:true}).click();await root(p).locator('[data-slot=stage]').filter({hasText:'En revisión'}).waitFor();assert.equal(await root(p).getByRole('button',{name:'Aprobar contenido',exact:true}).count(),0);
 const reviewer=await open('reviewer');await root(reviewer.p).getByRole('button',{name:'Cambios',exact:true}).click();assert.match(await root(reviewer.p).getByRole('combobox',{name:'Documento base de comparación'}).innerText(),/Contenido inicial/);await confirm(reviewer.p,'Aprobar contenido');await root(reviewer.p).locator('[data-slot=stage]').filter({hasText:'Aprobado'}).waitFor();assert.equal(await root(reviewer.p).getByRole('button',{name:'Publicar esta versión',exact:true}).count(),0);
 const publisher=await open('publisher');const publish=await action(publisher.p,'Publicar esta versión');assert.match(await publish.innerText(),/Nombre del producto/);await publish.getByRole('button',{name:'Confirmar',exact:true}).click();await root(publisher.p).getByText('Publicación confirmada por el servidor.',{exact:true}).waitFor();assert.equal((await state()).product.product_name,'Semilla Horizonte revisión 1');report.checks.push('Saved-change summaries accompany submission and publication while independent reviewer and publication authority remain enforced');
 await confirm(publisher.p,'Preparar nueva revisión');await root(publisher.p).locator('[data-slot=stage]').filter({hasText:'Borrador'}).waitFor();await p.reload({waitUntil:'load'});await root(p).getByRole('heading',{name:'Passport Studio',exact:true}).waitFor();await root(p).getByRole('button',{name:'Historial',exact:true}).click();const historyCount=(await state()).historyCount;
 await root(p).getByRole('button',{name:'Comparar con el trabajo actual',exact:true}).last().click();await root(p).getByRole('heading',{name:'Comparar cambios',exact:true}).waitFor();assert.match(await root(p).getByRole('combobox',{name:'Documento base de comparación'}).locator('option:checked').innerText(),/Historial r/);assert.ok(await root(p).locator('[data-diff-field]').count()>0);assert.equal((await state()).historyCount,historyCount);report.checks.push('Selecting a historical revision compares its content without restoring, saving or mislabeling it as a published version');
 await root(p).getByRole('button',{name:'Historial',exact:true}).click();await root(p).getByRole('button',{name:'Usar contenido en el borrador',exact:true}).last().click();assert.match(await p.getByRole('dialog').innerText(),/Cambios sobre tu trabajo actual/);await p.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal((await state()).historyCount,historyCount);
 await root(p).getByRole('button',{name:'Usar contenido en el borrador',exact:true}).last().click();await p.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await root(p).getByText('Versión recuperada localmente. Revisá las diferencias antes de guardar.',{exact:true}).waitFor();assert.equal((await state()).historyCount,historyCount);assert.equal((await state()).product.product_name,'Semilla Horizonte revisión 1');await root(p).getByRole('button',{name:'Identidad',exact:true}).click();assert.equal(await root(p).getByRole('textbox',{name:'Nombre del producto',exact:false}).inputValue(),initial.product.product_name);report.checks.push('Restore preview can be cancelled; confirmation only replaces local editorial content and leaves the public passport unchanged');
 await confirm(p,'Guardar borrador');await saved(p);const other=await open('editor');await root(other.p).getByRole('textbox',{name:'Nombre del producto',exact:false}).fill('Revisión ganadora de otra pestaña');await confirm(other.p,'Guardar borrador');await saved(other.p);
 await root(p).getByRole('textbox',{name:'Nombre del producto',exact:false}).fill('Trabajo local que no debe perderse');await confirm(p,'Guardar borrador');await root(p).getByText('Existe una revisión más reciente.',{exact:true}).waitFor();const callsBeforeReload=(await state()).writes;
 await root(p).getByRole('button',{name:'Releer versión guardada',exact:true}).click();await p.getByRole('dialog').getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(await root(p).getByRole('textbox',{name:'Nombre del producto',exact:false}).inputValue(),'Trabajo local que no debe perderse');
 await root(p).getByRole('button',{name:'Releer versión guardada',exact:true}).click();await p.getByRole('dialog').getByRole('button',{name:'Confirmar',exact:true}).click();await root(p).getByRole('textbox',{name:'Nombre del producto',exact:false}).waitFor();await p.waitForFunction(()=>document.querySelector('[data-field="identity.product_name"]')?.value==='Revisión ganadora de otra pestaña');assert.equal((await state()).writes,callsBeforeReload);report.checks.push('A real conflicting revision preserves local work until explicit reload confirmation, then reads the latest server state without another write');
 const viewer=await open('viewer',390);await root(viewer.p).getByRole('button',{name:'Cambios',exact:true}).click();await root(viewer.p).getByRole('combobox',{name:'Documento base de comparación'}).selectOption('saved');assert.equal(await root(viewer.p).getByRole('button',{name:'Guardar borrador',exact:true}).isDisabled(),true);await root(viewer.p).getByRole('button',{name:'Historial',exact:true}).click();assert.equal(await root(viewer.p).getByRole('button',{name:'Usar contenido en el borrador',exact:true}).first().isDisabled(),true);
 const final=await state();assert.equal(final.product.meta_setting,'LOCAL_TEST_ONLY');assert.equal(final.product.sun.security.sentinel,true);assert.deepEqual([...editor.errors,...reviewer.errors,...publisher.errors,...other.errors,...viewer.errors],[]);report.checks.push('Read-only users may compare but cannot restore or publish; technical product fields remain unchanged');
 for(const item of [editor,reviewer,publisher,other,viewer])await item.context.close();report.status='passed';report.historyCount=final.historyCount;
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,12000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
