import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {parsePilotEnvelope,canonicalReport,evidenceMetrics,pilotCsv,pilotHtml,csvCell,metricValue,parsePilotOptions} from '../src/lib/pilot-report.ts';
import {requiredPermissionForAdminResource} from '../src/lib/permission-policy.ts';
const seed=JSON.parse(await readFile(new URL('./pilot-report.fixture.json',import.meta.url),'utf8'));
const expect={tenant:'pilot-local',bid:'',from:'2026-09-01',to:'2026-09-03'};
const clone=()=>structuredClone(seed);function sign(v){v.integrity.digest=createHash('sha256').update(canonicalReport(v.report)).digest('hex');return v;}
test('accepts real SQL snapshot and preserves active/inactive and identity distinctions',async()=>{const e=await parsePilotEnvelope(clone(),expect);assert.equal(e.report.inventory.active,10);assert.equal(e.report.interactions.verifiedUnits,2);assert.equal(e.report.interactions.identityViews,1);const m=evidenceMetrics(e.report);assert.equal(m.find(x=>x.id==='verified_ratio').value,50);assert.equal(m.find(x=>x.id==='resolution_ratio').value,50);});
test('wrong scope and changed bytes cannot become an exported report',async()=>{await assert.rejects(()=>parsePilotEnvelope(clone(),{...expect,tenant:'foreign-local'}));await assert.rejects(()=>parsePilotEnvelope(clone(),{...expect,bid:'FOREIGN'}));await assert.rejects(()=>parsePilotEnvelope(clone(),{...expect,from:'2026-09-02'}));const bad=clone();bad.report.scope.tenantName='Another';await assert.rejects(()=>parsePilotEnvelope(bad,expect),/integrity/);});
test('extra private fields, changed schema and missing sections fail closed',async()=>{for(const edit of [e=>e.report.scope.email='private@example.invalid',e=>delete e.report.sdk,e=>e.report.source='demo',e=>e.report.reportId='fake']){const e=clone();edit(e);sign(e);await assert.rejects(()=>parsePilotEnvelope(e,expect));}});
test('inconsistent numerators, sample sizes or daily totals are rejected even with a valid content hash',async()=>{for(const edit of [e=>e.report.interactions.verifiedNfc=20,e=>e.report.inventory.registered=10,e=>e.report.incidents.timedResolved=5,e=>e.report.daily[0].events=20,e=>e.report.exclusions.nonReal=0,e=>e.report.sdk.latencySamples=50]){const e=clone();edit(e);sign(e);await assert.rejects(()=>parsePilotEnvelope(e,expect));}});
test('null values remain no-base, not perfect availability or zero cost',()=>{assert.equal(metricValue({value:null,unit:'percent'}),'Sin base');assert.equal(metricValue({value:0,unit:'count'}),'0');assert.ok(evidenceMetrics(seed.report).every(m=>!m.id.includes('roi')&&!m.id.includes('uptime')));});
test('all export formats use the same period, report identity and checksum',()=>{const e=clone(),csv=pilotCsv(e),html=pilotHtml(e);assert.ok(csv.includes(e.integrity.digest));assert.ok(html.includes(e.integrity.digest));assert.ok(csv.includes(e.report.reportId));assert.ok(html.includes(e.report.reportId));assert.ok(csv.includes(e.report.window.effectiveEnd));assert.ok(html.includes(e.report.window.effectiveEnd));assert.match(csv,/numerator.*denominator/);});
test('spreadsheets neutralize formula prefixes and HTML escapes customer text',()=>{for(const s of ['=1+1','+CMD','-DDE','@SUM(A1)','  =CMD'])assert.ok(csvCell(s).startsWith('"\''));const e=clone();e.report.scope.tenantName='<script>alert(1)</script>';const html=pilotHtml(e);assert.ok(!html.includes('<script>'));assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/src=|<script|https?:\/\//);});
test('options cannot expose a foreign tenant to a tenant account',()=>{const o={ok:true,contract:'nexid.pilot-evidence.v1',source:'database',tenantOptions:[{id:'10000000-0000-4000-8000-000000000001',slug:'pilot-local',name:'QA'}],batchOptions:[],limit:100};assert.equal(parsePilotOptions(o,'pilot-local',true).tenantOptions.length,1);assert.throws(()=>parsePilotOptions(o,'another-company',true));});
test('BFF uses report permission while backend also checks analytics access',()=>{assert.equal(requiredPermissionForAdminResource('GET','pilot-report'),'reports.export');assert.equal(requiredPermissionForAdminResource('GET','pilot-report/options'),'reports.export');});
test('UI makes report reads explicit and never polls or writes business data',async()=>{const ui=await readFile(new URL('../src/components/pilot-report.tsx',import.meta.url),'utf8');assert.doesNotMatch(ui,/setInterval|localStorage|method:.*POST|dangerouslySetInnerHTML/);assert.match(ui,/setReport\(null\)/);assert.match(ui,/parsePilotEnvelope/);assert.match(ui,/URL.revokeObjectURL/);});

import {canReadPilotReport} from '../src/lib/pilot-report-access.ts';
test('report access uses ordinary report capability with role ceilings, rather than an unrelated high-impact enum',()=>{const s={role:'tenant-admin',permissions:['reports.export','analytics:read']};assert.equal(canReadPilotReport(s),true);assert.equal(canReadPilotReport({...s,role:'viewer'}),false);assert.equal(canReadPilotReport({...s,isDemo:true}),false);assert.equal(canReadPilotReport({...s,deniedPermissions:['reports.export']}),false);assert.equal(canReadPilotReport({...s,permissions:[]}),false);});

import {pilotRequestScopeAllowed} from '../src/lib/pilot-report-access.ts';
test('report BFF rejects a mismatched tenant before legacy proxy normalization can rewrite it',()=>{const s={role:'tenant-admin',tenantSlug:'pilot-local'};assert.equal(pilotRequestScopeAllowed(s,'foreign-local'),false);assert.equal(pilotRequestScopeAllowed(s,''),true);assert.equal(pilotRequestScopeAllowed({...s,isDemo:true},'pilot-local'),false);assert.equal(pilotRequestScopeAllowed({role:'super-admin',tenantSlug:null},'pilot-local'),true);});
