// Project Next/BFF and actual PostgreSQL report service. Session identities are local test fixtures.
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3163',api='http://127.0.0.1:4263',out=process.env.QA_OUTPUT;
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH}),report={localOnly:true,realPostgres:true,realService:true,visual:[],checks:[]};
const reads=async()=>(await(await fetch(api+'/qa-state')).json()).calls;
async function open(role,width=1440){const context=await browser.newContext({viewport:{width,height:1050},serviceWorkers:'block',acceptDownloads:true,reducedMotion:'reduce'});if(role)await context.addCookies([{name:'nexid_dashboard_session',value:'pilot-qa-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await context.newPage(),errors=[],writes=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(['POST','PATCH','DELETE'].includes(r.method())&&r.url().includes('/api/'))writes.push(r.url());});await p.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await p.goto(base+'/analytics/pilot',{waitUntil:'load',timeout:90000});return {p,context,errors,writes};}
async function generate(p){await p.locator('input[aria-label="Desde · UTC"]:visible').fill('2026-09-01');await p.locator('input[aria-label="Hasta · UTC"]:visible').fill('2026-09-03');await p.getByRole('button',{name:'Generar informe',exact:true}).click();await p.locator('[data-testid="pilot-report-result"]:visible').waitFor({timeout:30000});}
try{
 await fetch(api+'/qa-failure?value=0');const user=await open('admin');const p=user.p;await p.getByRole('heading',{name:'Informe del piloto.',exact:true}).waitFor();assert.equal(await p.getByRole('combobox',{name:'Empresa',exact:true}).isDisabled(),true);assert.equal(await p.locator('[data-testid="pilot-report-result"]:visible').count(),0);
 const before=await reads();await generate(p);assert.equal(await reads(),before+1);report.checks.push('One explicit report request gives one consistent PostgreSQL snapshot');
 const downloadFile=async(label,name)=>{const [f]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:label,exact:true}).click()]);await f.saveAs(join(out,name));return readFile(join(out,name),'utf8');};
 const calls=await reads();const json=JSON.parse(await downloadFile('JSON con integridad','report.json')),csv=await downloadFile('CSV de indicadores','indicators.csv'),html=await downloadFile('Informe para compartir','pilot.html');assert.equal(json.report.interactions.verifiedNfc,4);assert.equal(json.report.inventory.active,10);assert.ok(csv.includes(json.integrity.digest)&&html.includes(json.integrity.digest));assert.ok(csv.includes(json.report.reportId)&&html.includes(json.report.reportId));assert.equal(await reads(),calls);report.checks.push('HTML CSV and JSON export the same report without new database calls');
 const printed=await user.context.newPage();await printed.setContent(html);assert.equal(await printed.locator('script').count(),0);assert.equal(await printed.locator('img').count(),0);await printed.screenshot({path:join(out,'shared-report.png'),fullPage:true});await printed.emulateMedia({media:'print'});await printed.screenshot({path:join(out,'print-layout.png'),fullPage:true});await printed.close();report.checks.push('Shared report is self-contained and has a printable layout');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1050});await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Page overflow');await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('[data-testid="pilot-report-workspace"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`pilot-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}
 await p.getByRole('combobox',{name:'Lote',exact:true}).selectOption('LOT-QA');assert.equal(await p.locator('[data-testid="pilot-report-result"]:visible').count(),0);assert.equal(await p.getByRole('button',{name:'CSV de indicadores',exact:true}).count(),0);await p.getByRole('button',{name:'Generar informe',exact:true}).click();await p.locator('[data-testid="pilot-report-result"]:visible').waitFor();const scoped=JSON.parse(await downloadFile('JSON con integridad','batch-report.json'));assert.equal(scoped.report.sdk.requests,null);report.checks.push('Filter change invalidates prior exports and batch report does not borrow tenant SDK usage');
 await fetch(api+'/qa-failure?value=1');await p.getByRole('button',{name:'Generar informe',exact:true}).click();await p.getByRole('status').filter({hasText:'No se pudo confirmar la fuente'}).waitFor();assert.equal(await p.locator('[data-testid="pilot-report-result"]:visible').count(),0);await fetch(api+'/qa-failure?value=0');report.checks.push('Source failure removes the prior report instead of inventing zeros');
 await p.getByRole('button',{name:'Generar informe',exact:true}).click();await p.locator('[data-testid="pilot-report-result"]:visible').waitFor();await p.reload({waitUntil:'load'});assert.equal(await p.locator('[data-testid="pilot-report-result"]:visible').count(),0);report.checks.push('Reload does not quietly regenerate expensive report queries');
 const viewer=await open('viewer');assert.equal(await viewer.p.getByTestId('pilot-report-workspace').count(),0);assert.equal(await viewer.p.getByRole('button',{name:'Generar informe'}).count(),0);const denied=await viewer.context.request.get(base+'/api/admin/pilot-report?tenant=pilot-local&from=2026-09-01&to=2026-09-03');assert.equal(denied.status(),403);await viewer.context.close();
 const foreign=await user.context.request.get(base+'/api/admin/pilot-report?tenant=foreign-local&from=2026-09-01&to=2026-09-03');assert.equal(foreign.status(),403);report.checks.push('Unauthorized roles and cross-tenant requests cannot generate the report');
 const global=await open('global');await global.p.getByRole('heading',{name:'Informe del piloto.',exact:true}).waitFor();assert.equal(await global.p.getByRole('button',{name:'Generar informe'}).isDisabled(),true);await global.p.getByRole('combobox',{name:'Empresa',exact:true}).selectOption('pilot-local');await global.p.getByRole('combobox',{name:'Lote',exact:true}).locator('option[value="LOT-QA"]').waitFor({state:'attached'});await generate(global.p);assert.deepEqual(global.errors,[]);await global.context.close();
 assert.deepEqual(user.errors,[]);assert.deepEqual(user.writes,[]);report.status='passed';await user.context.close();
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(-6000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'acceptance.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
