import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {reconciliationRows,filterReconciliation,closureReadiness,previewRecallQuantities,formatRecallDate} from '../src/lib/recall-reconciliation.ts';
import {parseRecallRecord,parseRecallDetail} from '../src/lib/recall-reconciliation-guards.ts';
const id=n=>'10000000-0000-4000-8000-'+String(n).padStart(12,'0');
const actor={id:id(1),label:'Responsable',canRead:true,canWrite:true,canPublish:true,canExport:true};
const scope={tenantId:id(5),batchId:id(6),bid:'LOT',tenant:'company-qa'};
function record(){return {id:id(7),tenant_id:scope.tenantId,batch_id:scope.batchId,state:'active',version:4,created_by:id(1),last_editor_id:id(1),submitted_by:id(1),close_requested_by:null,close_reason:null,created_at:'2026-09-19T00:00:00Z',updated_at:'2026-09-19T12:00:00Z',published_at:'2026-09-19T01:00:00Z',closed_at:null,document:{kind:'recall',title:'Caso QA',reason:'Detalle privado de calidad',publicMessage:'Mensaje de prueba del aviso',instructions:'Separar las unidades reportadas',contact:'Calidad QA',unitLabel:'cajas',destinations:[{id:id(10),assigneeId:id(1),recipient:'Norte',units:10},{id:id(11),assigneeId:id(2),recipient:'Centro',units:8},{id:id(12),assigneeId:id(3),recipient:'Sur',units:12}]},progress:{[id(11)]:{acknowledgedAt:'2026-09-19T02:00:00Z',ackEvidence:'ACK-CENTRO',returnedUnits:3,heldUnits:0,accountEvidence:'COUNT-CENTRO'},[id(12)]:{acknowledgedAt:'2026-09-19T02:00:00Z',returnedUnits:7,heldUnits:5}},totals:{declaredUnits:30,returnedUnits:10,heldUnits:5,pendingUnits:15,acknowledgedDestinations:2,totalDestinations:3,basis:'operator_declared'}};}
function complete(){const r=record();r.progress[id(10)]={acknowledgedAt:'2026-09-19T02:00:00Z',returnedUnits:10,heldUnits:0};r.progress[id(11)].heldUnits=5;return r;}
test('destinations distinguish pending acknowledgement, quantities and completed declaration',()=>{const rows=reconciliationRows(record(),[{id:id(2),label:'Distribución'}]);assert.deepEqual(rows.map(r=>r.status),['acknowledgement','quantities','complete']);assert.equal(rows[1].assigneeLabel,'Distribución');assert.equal(rows[0].pending,10);assert.equal(rows[2].held,5);});
test('closure checklist matches the existing SQL rule without equating held stock with returned stock',()=>{const r=record(),ready=closureReadiness(r,actor);assert.equal(ready.missingAcknowledgements,1);assert.equal(ready.pendingUnits,15);assert.equal(ready.canRequest,false);assert.equal(closureReadiness(complete(),actor).canRequest,true);assert.equal(closureReadiness(complete(),actor).canApprove,false);});
test('a reconciled amount without acknowledgement is still a blocker',()=>{const r=complete();delete r.progress[id(10)].acknowledgedAt;assert.equal(closureReadiness(r,actor).ready,false);assert.equal(closureReadiness(r,actor).pendingUnits,0);});
test('approval retains state, write authority and independence of requesting account',()=>{const r=complete();r.state='closing';r.close_requested_by=id(1);assert.equal(closureReadiness(r,actor).canApprove,false);assert.equal(closureReadiness(r,{...actor,id:id(3)}).canApprove,true);assert.equal(closureReadiness(r,{...actor,id:id(3),canWrite:false}).canApprove,false);r.state='closed';assert.equal(closureReadiness(r,{...actor,id:id(3)}).canApprove,false);});
test('filters are local and never alter the denominator or hide destinations from closure criteria',()=>{const r=record(),rows=reconciliationRows(r,[]),original=JSON.stringify(r);assert.equal(filterReconciliation(rows,'complete','','').length,1);assert.equal(filterReconciliation(rows,'all',id(2),'ACK-CENTRO').length,1);assert.equal(filterReconciliation(rows,'all','','.*').length,0);assert.equal(closureReadiness(r,actor).pendingUnits,15);assert.equal(JSON.stringify(r),original);});
test('quantities show cumulative total, remaining amount and correction deltas',()=>{const r=record(),p=previewRecallQuantities(r,id(12),'6','6');assert.deepEqual(p,{ok:true,returned:6,held:6,pending:0,returnedDelta:-1,heldDelta:1,decreases:true});assert.equal(r.progress[id(12)].returnedUnits,7);});
test('empty, decimal, signed, exponential, out-of-range and foreign-target quantities are refused',()=>{for(const input of ['', '01', '-1', '1.5', '1e1', ' 0','10000001'])assert.equal(previewRecallQuantities(record(),id(10),input,'0').ok,false);assert.equal(previewRecallQuantities(record(),id(10),'8','3').ok,false);assert.equal(previewRecallQuantities(record(),id(99),'0','0').ok,false);});
test('explicit zeroes are valid but do not silently become completed destinations',()=>{const p=previewRecallQuantities(record(),id(10),'0','0');assert.equal(p.ok,true);assert.equal(p.pending,10);});
test('malformed progress is refused before readiness can render false successful totals',()=>{for(const value of [false,'0',NaN,-1,1.5]){const r=record();r.progress[id(11)].returnedUnits=value;assert.throws(()=>parseRecallRecord(r,scope));}const r=record();r.progress[id(11)].acknowledgedAt='not-a-date';assert.throws(()=>parseRecallRecord(r,scope));});
test('detail authorizations must be server-confirmed booleans, never truthy strings',()=>{const raw={ok:true,protocol:'nexid.batch-recalls.v1',source:'database',scope,case:record(),history:[],evidenceBasis:'operator_declared',actor};assert.equal(parseRecallDetail(raw,'LOT','company-qa').actor.canWrite,true);assert.throws(()=>parseRecallDetail({...raw,actor:{...actor,canWrite:'true'}},'LOT','company-qa'));});
test('refresh/export cannot discard the unresolved operation, closure preflights reuse the existing read',async()=>{const s=await readFile(new URL('../src/components/recall-workspace.tsx',import.meta.url),'utf8');const load=s.slice(s.indexOf('async function load'),s.indexOf('async function reviewClosure'));assert.match(load,/pending.current\|\|uncertain/);assert.doesNotMatch(load,/pending.current=null|setUncertain\(false\)/);const exportCode=s.slice(s.indexOf('async function exportReport'),s.indexOf('const editable'));assert.match(exportCode,/pending.current\|\|uncertain\|\|stale/);assert.match(s,/d.case.version!==before.version/);});
test('no automatic communications, stock updates or added background reads in reconciliation',async()=>{const s=await readFile(new URL('../src/components/recall-reconciliation.tsx',import.meta.url),'utf8');assert.doesNotMatch(s,/fetch\(|setInterval|localStorage|sessionStorage|sendBeacon/);assert.match(s,/no levanta el aviso/);assert.match(s,/Declarado por operadores/);});
test('read access revoked never gives a ready-to-write closure even with other stale flags',()=>{const r=complete();assert.equal(closureReadiness(r,{...actor,canRead:false}).canRequest,false);r.state='closing';r.close_requested_by=id(2);assert.equal(closureReadiness(r,{...actor,canRead:false}).canApprove,false);});
test('a fresh full-case export updates the live record as well as the history',async()=>{const s=await readFile(new URL('../src/components/recall-workspace.tsx',import.meta.url),'utf8');const part=s.slice(s.indexOf('async function exportReport'),s.indexOf('const editable'));assert.match(part,/acceptDetail\(fresh\)/);assert.match(part,/if\(!alive.current\)return/);});

test('timestamps are explicit UTC and stable across host timezone and day-period conventions',()=>{assert.equal(formatRecallDate('2026-09-21T00:12:30-03:00'),'21/09/2026 · 03:12 UTC');assert.equal(formatRecallDate('2026-09-21T03:12:30Z'),'21/09/2026 · 03:12 UTC');assert.equal(formatRecallDate(null),'—');assert.equal(formatRecallDate('invalid'),'Fecha sin confirmar');});
test('SSR case rows use the same deterministic formatter as browser updates',async()=>{const s=await readFile(new URL('../src/components/recall-workspace.tsx',import.meta.url),'utf8');assert.match(s,/const date=formatRecallDate/);assert.doesNotMatch(s,/new Intl.DateTimeFormat/);});
