import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3481',api='http://127.0.0.1:4681',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,actualRecallHandlers:true,actualPostgres:true,syntheticSessions:true,checks:[],visual:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json(),root=p=>p.locator('[data-testid="recall-workspace"]:visible'),panel=p=>p.getByTestId('recall-reconciliation');
const destination=(p,name)=>panel(p).locator('[data-destination]').filter({has:p.getByRole('heading',{name,exact:true})});
async function settled(p){await p.waitForFunction(()=>Array.from(document.querySelectorAll('[data-testid="recall-workspace"]')).some(el=>el.getClientRects().length>0&&el.getAttribute('aria-busy')==='false'));}
async function open(role='editor',width=1440){const c=await browser.newContext({viewport:{width,height:1040},locale:'es-AR',reducedMotion:'reduce',serviceWorkers:'block',acceptDownloads:true});await c.addCookies([{name:'nexid_dashboard_session',value:'qa-recall-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await p.goto(base+'/batches/LOT-RECALL-QA/recalls?tenant=recall-qa',{waitUntil:'load',timeout:90000});await root(p).getByRole('button',{name:/Retiro QA · conciliación de destinos/}).click();await panel(p).waitFor();await settled(p);return {p,c,errors};}
async function modal(p,button,{returned,held}={}){await button.click();const dialog=p.getByRole('dialog');await dialog.waitFor();await dialog.getByRole('textbox',{name:'Motivo o evidencia de la acción'}).fill('Declaración de prueba revisada con referencia operativa.');const reference=dialog.getByRole('textbox',{name:'Referencia del comprobante'});if(await reference.count())await reference.fill('EVIDENCE-TEST-001');if(returned!==undefined)await dialog.getByRole('spinbutton',{name:'Total devueltas a la fecha'}).fill(String(returned));if(held!==undefined)await dialog.getByRole('spinbutton',{name:'Total inmovilizadas a la fecha'}).fill(String(held));await dialog.getByRole('checkbox').check();return dialog;}
async function save(p,button,input){const dialog=await modal(p,button,input);await dialog.getByRole('button',{name:'Confirmar acción',exact:true}).click();await dialog.waitFor({state:'hidden'});await root(p).getByRole('status').filter({hasText:/Operación guardada|intento anterior/}).waitFor();await settled(p);}
try{
 const editor=await open(),p=editor.p;assert.equal(await destination(p,'Distribuidor Norte').count(),1);assert.equal(await panel(p).getByRole('button',{name:'Solicitar cierre',exact:true}).isDisabled(),true);const before=await state();
 await panel(p).getByRole('combobox',{name:'Situación del destino'}).selectOption('acknowledgement');assert.equal(await panel(p).locator('[data-destination]').count(),1);await panel(p).getByRole('combobox',{name:'Situación del destino'}).selectOption('complete');assert.equal(await destination(p,'Distribuidor Sur').count(),1);await panel(p).getByRole('combobox',{name:'Situación del destino'}).selectOption('all');await panel(p).getByRole('searchbox',{name:'Destino, responsable o comprobante'}).fill('COUNT-32');assert.equal(await destination(p,'Distribuidor Centro').count(),1);await panel(p).getByRole('searchbox').fill('');assert.equal((await state()).calls.length,before.calls.length);assert.equal((await state()).operations.length,before.operations.length);report.checks.push('Readiness and destination/reference filters identify actual blockers without requests or changing the case denominator');
 const south=destination(p,'Distribuidor Sur');const preview=await modal(p,south.getByRole('button',{name:'Registrar cantidades',exact:true}),{returned:'',held:12});assert.equal(await preview.getByRole('button',{name:'Confirmar acción'}).isDisabled(),true);await preview.getByRole('spinbutton',{name:'Total devueltas a la fecha'}).fill('10');assert.equal(await preview.getByRole('button',{name:'Confirmar acción'}).isDisabled(),true);await preview.getByRole('spinbutton',{name:'Total devueltas a la fecha'}).fill('6');await preview.getByRole('spinbutton',{name:'Total inmovilizadas a la fecha'}).fill('6');assert.match(await preview.innerText(),/Disminuye una cantidad ya declarada/);assert.match(await preview.innerText(),/Pendientes: 0/);await p.keyboard.press('Escape');assert.equal((await state()).operations.length,before.operations.length);report.checks.push('Quantity preview rejects missing/over-target totals, explains downward corrections and cancels without mutation');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1040});await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');window.scrollTo(0,0);},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(width===390){assert.equal(await root(p).getByRole('button',{name:'Elegir otro caso',exact:true}).isVisible(),true);assert.ok(await panel(p).getByText('Qué falta para solicitar el cierre',{exact:true}).evaluate(el=>el.getBoundingClientRect().top<window.innerHeight-150));}await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('[data-testid="recall-workspace"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`reconciliation-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}
 await fetch(api+'/qa-mode?lost=1',{method:'POST'});const ack=await modal(p,destination(p,'Distribuidor Norte').getByRole('button',{name:'Registrar acuse',exact:true}));await ack.getByRole('button',{name:'Confirmar acción'}).click();await root(p).getByRole('button',{name:'Reconciliar el mismo intento'}).waitFor();const unknown=await state();assert.equal(unknown.operations.length,before.operations.length+1);assert.equal(await root(p).getByRole('button',{name:'Actualizar estado',exact:true}).isDisabled(),true);assert.equal(await root(p).getByRole('button',{name:/Borrador anterior cancelado/,includeHidden:true}).isDisabled(),true);await root(p).getByRole('button',{name:'Evidencia e historial'}).click();assert.equal(await root(p).getByRole('button',{name:'Descargar informe'}).isDisabled(),true);assert.equal((await state()).calls.length,unknown.calls.length);
 await root(p).getByRole('button',{name:'Reconciliar el mismo intento'}).click();await root(p).getByRole('status').filter({hasText:'intento anterior'}).waitFor();await settled(p);assert.equal((await state()).operations.length,unknown.operations.length);report.checks.push('A committed response lost in transit cannot be discarded by refresh, case switching or export; replay recovers exactly one operation');
 await save(p,destination(p,'Distribuidor Norte').getByRole('button',{name:'Registrar cantidades',exact:true}),{returned:10,held:0});const assignment=await fetch(api+'/qa-assignee-account',{method:'POST'});assert.equal(assignment.status,200);await root(p).getByRole('button',{name:'Actualizar estado'}).click();await root(p).getByRole('status').filter({hasText:'Consulta confirmada.'}).waitFor();await settled(p);await panel(p).getByText('Cantidades conciliadas para revisar',{exact:true}).waitFor();assert.equal(await panel(p).getByRole('button',{name:'Solicitar cierre'}).isDisabled(),false);
 const center=destination(p,'Distribuidor Centro');await center.getByText('Comprobantes del destino',{exact:true}).click();await center.getByRole('button',{name:'Ver movimientos de este destino'}).click();assert.equal(await root(p).getByRole('combobox',{name:'Filtrar movimientos por destino'}).inputValue(),before.center);assert.match(await root(p).innerText(),/AGENT-CENTER-COUNT/);assert.ok(!(await root(p).innerText()).includes('COUNT-33'));await root(p).getByRole('button',{name:'Acuses y cantidades'}).click();report.checks.push('Assigned-account reconciliation appears in management and history can be focused on the selected destination without another request');
 const correction=await fetch(api+'/qa-concurrent-correction',{method:'POST'});assert.equal(correction.status,200);const writesBefore=(await state()).operations.length;await panel(p).getByRole('button',{name:'Solicitar cierre'}).click();await root(p).getByRole('status').filter({hasText:'El caso cambió'}).waitFor();await settled(p);assert.equal(await p.getByRole('dialog').count(),0);assert.equal((await state()).operations.length,writesBefore);assert.equal(await panel(p).getByRole('button',{name:'Solicitar cierre'}).isDisabled(),true);report.checks.push('Closure review rereads the current case and refuses a stale all-complete view after another operator changes quantities');
 await save(p,destination(p,'Distribuidor Sur').getByRole('button',{name:'Registrar cantidades'}),{returned:6,held:6});await save(p,panel(p).getByRole('button',{name:'Solicitar cierre'}));assert.equal((await state()).case.state,'closing');assert.equal(await panel(p).getByRole('button',{name:'Aprobar cierre'}).isDisabled(),true);
 const reviewer=await open('reviewer');const rp=reviewer.p;await fetch(api+'/qa-mode?unavailable=1',{method:'POST'});await panel(rp).getByRole('button',{name:'Aprobar cierre'}).click();await root(rp).getByRole('status').filter({hasText:'No se confirmó'}).waitFor();await settled(rp);assert.equal(await rp.getByRole('dialog').count(),0);assert.equal(await panel(rp).getByRole('button',{name:'Aprobar cierre'}).isDisabled(),true);await fetch(api+'/qa-mode',{method:'POST'});await root(rp).getByRole('button',{name:'Actualizar estado'}).click();await root(rp).getByRole('status').filter({hasText:'Consulta confirmada.'}).waitFor();await settled(rp);await panel(rp).getByRole('button',{name:'Aprobar cierre'}).waitFor();await save(rp,panel(rp).getByRole('button',{name:'Aprobar cierre'}));const closed=await state();assert.equal(closed.case.state,'closed');assert.equal(closed.notice.notices.length,1);assert.equal(closed.notice.notices[0].trackingState,'closed');report.checks.push('Failed pre-close reread cannot authorize a write; independent review then closes tracking while preserving the published product warning');
 await root(rp).getByRole('button',{name:'Evidencia e historial'}).click();const [dl]=await Promise.all([rp.waitForEvent('download'),root(rp).getByRole('button',{name:'Descargar informe'}).click()]);await dl.saveAs(join(out,'case-evidence.html'));const html=await readFile(join(out,'case-evidence.html'),'utf8');assert.match(html,/AGENT-CENTER-COUNT/);assert.match(html,/Cerrar seguimiento no libera/);assert.equal((await state()).unchanged,true);
 const viewer=await open('viewer',390);assert.equal(await panel(viewer.p).getByRole('button',{name:'Registrar cantidades'}).count(),0);assert.deepEqual(editor.errors,[]);assert.deepEqual(reviewer.errors,[]);assert.deepEqual(viewer.errors,[]);for(const c of [editor.c,reviewer.c,viewer.c])await c.close();report.checks.push('Existing whole-case export includes the saved evidence; read-only users cannot mutate and batch/tag configuration is unchanged');report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,12000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
