// Entire UI/BFF/API handlers and real disposable PostgreSQL. Only identities and SUN fixture are synthetic.
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3157',web='http://localhost:3158',api='http://127.0.0.1:4220',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,actualApiHandlers:true,realPostgres:true,publicSunFixture:'synthetic identity; not a physical TAP',screens:[],checks:[]};
async function open(who,width=1440){const context=await browser.newContext({viewport:{width,height:1050},serviceWorkers:'block',reducedMotion:'reduce',acceptDownloads:true});await context.addCookies([{name:'nexid_dashboard_session',value:'qa-recall-'+who,url:base,httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await page.goto(base+'/batches/LOT-RECALL-QA/recalls?tenant=recall-qa',{waitUntil:'load',timeout:90000});await page.getByRole('heading',{name:'Retiros y cuarentenas',exact:true}).waitFor();return {context,page,errors};}
async function select(page){await page.getByRole('button',{name:/Retiro preventivo QA/}).first().click();await page.getByRole('heading',{name:'Retiro preventivo QA',exact:true}).waitFor();}
async function action(page,name,{reason,evidence,returned,held}={}){await page.getByRole('button',{name,exact:true}).click();const dialog=page.getByRole('dialog');await dialog.waitFor();if(reason)await dialog.getByRole('textbox',{name:'Motivo o evidencia de la acción'}).fill(reason);if(evidence)await dialog.getByRole('textbox',{name:'Referencia del comprobante'}).fill(evidence);if(returned!==undefined)await dialog.getByRole('spinbutton',{name:'Total devueltas a la fecha'}).fill(String(returned));if(held!==undefined)await dialog.getByRole('spinbutton',{name:'Total inmovilizadas a la fecha'}).fill(String(held));await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Confirmar acción',exact:true}).click();await dialog.waitFor({state:'hidden'});await page.getByRole('status').filter({hasText:/Operación guardada|intento anterior/}).waitFor({timeout:30000});}
const notices=async()=>await(await fetch(api+'/public/product-notices?tenant=recall-qa&bid=LOT-RECALL-QA')).json();
try{
 const editor=await open('editor'),p=editor.page;await p.getByRole('button',{name:'Preparar un caso',exact:true}).first().click();
 await p.getByRole('textbox',{name:'Título del caso',exact:true}).fill('Retiro preventivo QA');await p.getByRole('textbox',{name:'Motivo interno · no aparece en el pasaporte',exact:true}).fill('Investigación privada de prueba con respaldo interno.');await p.getByRole('textbox',{name:'Aviso público',exact:true}).fill('Este lote tiene un retiro preventivo en curso.');await p.getByRole('textbox',{name:'Instrucciones al consumidor',exact:true}).fill('Separar las unidades y comunicarse con calidad antes de utilizarlas.');await p.getByRole('textbox',{name:'Contacto público del responsable',exact:true}).fill('Calidad · Empresa QA');await p.getByRole('textbox',{name:'Destino 1',exact:true}).fill('Distribuidor QA');await p.getByRole('spinbutton',{name:'Cantidad declarada',exact:true}).fill('10');
 await fetch(api+'/qa-lose-next',{method:'POST'});await p.getByRole('button',{name:'Guardar borrador',exact:true}).click();await p.getByRole('button',{name:'Reconciliar el mismo intento',exact:true}).waitFor();assert.equal((await(await fetch(api+'/qa-state')).json()).caseCount,1);await p.getByRole('button',{name:'Reconciliar el mismo intento',exact:true}).click();await p.getByRole('status').filter({hasText:'intento anterior'}).waitFor();assert.equal((await(await fetch(api+'/qa-state')).json()).operationCount,1);assert.equal((await notices()).notices.length,0);report.checks.push('Lost create response reconciles one durable draft; draft is not public');
 await action(p,'Enviar a revisión');assert.equal(await p.getByRole('button',{name:'Publicar aviso del lote',exact:true}).isDisabled(),true);
 const reviewer=await open('reviewer');await select(reviewer.page);await action(reviewer.page,'Publicar aviso del lote');assert.equal((await notices()).notices.length,1);report.checks.push('Separate responsible account publishes the approved batch warning');
 await p.getByRole('button',{name:'Actualizar estado',exact:true}).click();await p.getByRole('heading',{name:'Distribuidor QA',exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Solicitar cierre',exact:true}).isDisabled(),true);
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1050});await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow');await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('[data-testid="recall-workspace"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`recall-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.screens.push({width,theme,violations});}
 await p.setViewportSize({width:1440,height:1050});await action(p,'Registrar acuse',{reason:'Acuse recibido del responsable de distribución.',evidence:'ACUSE-QA-001'});await action(p,'Registrar cantidades',{reason:'Siete unidades devueltas y tres inmovilizadas en el depósito.',evidence:'ACTA-QA-001',returned:7,held:3});await action(p,'Solicitar cierre',{reason:'Se conciliaron todos los destinos del objetivo declarado.'});assert.equal(await p.getByRole('button',{name:'Aprobar cierre',exact:true}).isDisabled(),true);await reviewer.page.getByRole('button',{name:'Actualizar estado',exact:true}).click();await reviewer.page.getByRole('heading',{name:'Cierre pendiente de revisión',exact:true}).waitFor();await action(reviewer.page,'Aprobar cierre',{reason:'Se revisaron los acuses y comprobantes indicados por operaciones.'});assert.equal((await notices()).notices[0].trackingState,'closed');report.checks.push('Acknowledgement, quantity evidence and independent closure preserve the public warning');
 await p.getByRole('button',{name:'Actualizar estado',exact:true}).click();await p.getByRole('button',{name:'Evidencia e historial',exact:true}).click();const [download]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Descargar informe',exact:true}).click()]);await download.saveAs(join(out,'recall-evidence.html'));const exported=await readFile(join(out,'recall-evidence.html'),'utf8');assert.match(exported,/product_recall_cases/);assert.match(exported,/ACTA-QA-001/);assert.match(exported,/no a un inventario físico certificado/);report.checks.push('Actual persisted report downloads with denominator, operation history and evidence references');
 const viewer=await open('viewer',390);await select(viewer.page);assert.equal(await viewer.page.getByRole('button',{name:'Preparar un caso',exact:true}).count(),0);assert.deepEqual(editor.errors,[]);assert.deepEqual(reviewer.errors,[]);assert.deepEqual(viewer.errors,[]);
 const pub=await browser.newContext({locale:'es-AR',viewport:{width:390,height:850},reducedMotion:'reduce',serviceWorkers:'block'});const mobile=await pub.newPage();await mobile.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await mobile.goto(web+'/sun?qr=1&channel=qr&carrier=qr_basic&tenant=recall-qa&bid=LOT-RECALL-QA&lang=es-AR',{waitUntil:'load',timeout:90000});const notice=mobile.getByTestId('product-notices');await notice.getByRole('heading',{name:'Retiro preventivo QA',exact:true}).waitFor({timeout:30000});assert.ok(!(await notice.innerText()).includes('Investigación privada'));assert.match(await notice.innerText(),/Seguimiento cerrado/);assert.ok(await notice.evaluate(el=>el.getBoundingClientRect().top<500));await mobile.addScriptTag({content:axe});const publicViolations=await mobile.evaluate(async()=>{const r=await axe.run('[data-testid="product-notices"]');return r.violations.map(v=>({id:v.id,impact:v.impact}));});assert.deepEqual(publicViolations.filter(v=>['serious','critical'].includes(v.impact)),[]);await mobile.screenshot({path:join(out,'consumer-warning.png'),fullPage:false});report.checks.push('The actual SUN presentation shows the current product warning near the top, excluding private data');
 await mobile.route('**/api/product-notices?**',r=>r.fulfill({status:503,contentType:'application/json',body:'{"ok":false}'}));await notice.getByRole('button',{name:'Actualizar avisos',exact:true}).click();await notice.locator('[role="status"]').filter({hasText:'No se pudieron consultar'}).waitFor();assert.equal(await notice.getAttribute('data-notice-state'),'unknown');assert.equal(await notice.getByRole('heading',{name:'Retiro preventivo QA',exact:true}).count(),1);report.checks.push('Failure to refresh cannot silently become a no-recall or safe-product state');
 await pub.close();await editor.context.close();await reviewer.context.close();await viewer.context.close();report.status='passed';
}catch(error){report.status='failed';report.error=error.stack;const page=browser.contexts().at(-1)?.pages().at(-1);if(page){report.visible=(await page.locator('body').innerText()).slice(0,10000);await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw error;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
