// Full UI/BFF + assigned handlers + existing recall engine backed by real ephemeral PostgreSQL.
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const base='http://localhost:3163',api='http://127.0.0.1:4263',out=process.env.QA_OUTPUT,cid='60000000-0000-4000-8000-000000000001',dest='70000000-0000-4000-8000-000000000001';assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,actualHandlers:true,realPostgres:true,checks:[],visual:[]};
const state=async()=>await(await fetch(api+'/qa-state')).json();
async function open(who,path='/tasks/recalls'){const context=await browser.newContext({viewport:{width:1440,height:1050},serviceWorkers:'block',reducedMotion:'reduce',acceptDownloads:true});await context.addCookies([{name:'nexid_dashboard_session',value:'qa-task-'+who,url:base,httpOnly:true,sameSite:'Lax'}]);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());await page.goto(base+path,{waitUntil:'load',timeout:90000});await page.locator('[data-testid="assigned-recall-workspace"]:visible').waitFor();return {context,page,errors};}
async function fill(p,reason,reference){await p.getByRole('textbox',{name:'Motivo o detalle de la respuesta',exact:true}).fill(reason);await p.getByRole('textbox',{name:'Referencia del comprobante',exact:true}).fill(reference);}
async function confirm(p,name){await p.getByRole('button',{name,exact:true}).click();const d=p.getByRole('dialog');await d.getByRole('checkbox').check();await d.getByRole('button',{name:'Confirmar respuesta',exact:true}).click();}
try{
 await fetch(api+'/qa-reset',{method:'POST'});const item=await open('agent'),p=item.page;
 const taskButton=p.getByRole('button').filter({hasText:'Distribuidor de prueba · destino propio'});await taskButton.waitFor();assert.ok(!(await p.getByTestId('assigned-recall-workspace').innerText()).includes('HIDDEN_OTHER'));await taskButton.click();await p.getByRole('heading',{name:'Distribuidor de prueba · destino propio',exact:true}).waitFor();
 assert.ok(p.url().includes('destination='+dest));assert.equal((await state()).operations,3);report.checks.push('Assigned destination opens without writes or other-recipient exposure');
 await fill(p,'Confirmo recepción del aviso por el canal operativo.','ACK-LOCAL-001');const readCount=(await state()).calls.length;await p.getByRole('button',{name:'Comprobantes e historial',exact:true}).click();await p.getByRole('button',{name:'Aviso y respuesta',exact:true}).click();assert.equal(await p.getByRole('textbox',{name:'Referencia del comprobante'}).inputValue(),'ACK-LOCAL-001');assert.equal((await state()).calls.length,readCount);report.checks.push('Changing tabs preserves the form and makes no server requests');
 await fetch(api+'/qa-lose-next',{method:'POST'});await confirm(p,'Revisar y confirmar acuse');await p.getByRole('button',{name:'Reconciliar el mismo intento',exact:true}).waitFor();assert.equal((await state()).operations,4);await p.getByRole('button',{name:'Reconciliar el mismo intento',exact:true}).click();await p.getByRole('status').filter({hasText:'No se duplicó'}).waitFor();assert.equal((await state()).operations,4);assert.equal((await state()).case.progress[dest].acknowledgedBy,'30000000-0000-4000-8000-000000000003');report.checks.push('Lost acknowledgement reply reconciles the original durable operation');
 await p.reload({waitUntil:'load'});await p.getByRole('spinbutton',{name:'Devueltas acumuladas',exact:true}).waitFor();await p.getByRole('spinbutton',{name:'Devueltas acumuladas'}).fill('7');await p.getByRole('spinbutton',{name:'Inmovilizadas acumuladas'}).fill('3');await fill(p,'Declaro cantidades conciliadas según el comprobante.','COUNT-LOCAL-001');await confirm(p,'Revisar y guardar cantidades');await p.getByRole('status').filter({hasText:'Guardado con tu cuenta'}).waitFor();const saved=await state();assert.equal(saved.case.progress[dest].returnedUnits,7);assert.equal(saved.case.progress[dest].heldUnits,3);assert.equal(saved.case.progress['70000000-0000-4000-8000-000000000002'],undefined);report.checks.push('Cumulative counts persist in the management case and remain isolated to this destination');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1050});await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');},theme);if(width===390){const before=(await state()).calls.length;await p.getByRole('button',{name:'Ver mis otras tareas',exact:true}).click();await p.getByRole('button',{name:'Volver a la tarea abierta',exact:true}).click();assert.equal((await state()).calls.length,before);}
 assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow');await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('[data-testid="assigned-recall-workspace"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:join(out,`assigned-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['serious','critical'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}
 await p.getByRole('button',{name:'Comprobantes e historial',exact:true}).click();const [download]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Descargar constancia',exact:true}).click()]);await download.saveAs(join(out,'own-task-report.html'));const html=await readFile(join(out,'own-task-report.html'),'utf8');assert.ok(html.includes('COUNT-LOCAL-001')&&html.includes('ACK-LOCAL-001'));assert.ok(!html.includes('HIDDEN_OTHER_DISTRIBUTOR')&&!html.includes('REASON_INTERNAL'));report.checks.push('Own-task export contains confirmed evidence only, not the full case');
 const direct='/tasks/recalls?case='+cid+'&destination='+dest;const viewer=await open('viewer',direct);assert.equal(await viewer.page.getByRole('button',{name:'Revisar y guardar cantidades',exact:true}).count(),0);await viewer.context.close();const unassigned=await open('unassigned',direct);assert.equal(await unassigned.page.getByRole('heading',{name:'Distribuidor de prueba · destino propio',exact:true}).count(),0);await unassigned.context.close();report.checks.push('Viewer cannot respond; unassigned user cannot open a copied task URL');
 await fetch(api+'/qa-close',{method:'POST'});await p.getByRole('button',{name:'Actualizar tarea',exact:true}).click();await p.getByText('Esta tarea está en consulta porque el seguimiento está cerrado.',{exact:false}).waitFor();assert.equal(await p.getByRole('button',{name:'Revisar y guardar cantidades',exact:true}).count(),0);assert.match(await p.getByTestId('assigned-recall-workspace').innerText(),/Aviso de retiro vigente/);report.checks.push('Independent management closure disables responses but does not lift the public warning');
 await fetch(api+'/qa-mode?unavailable=1',{method:'POST'});await p.getByRole('button',{name:'Consultar tareas',exact:true}).click();await p.getByText('No se confirmó la fuente.',{exact:false}).waitFor();assert.equal(await p.getByRole('heading',{name:'Distribuidor de prueba · destino propio',exact:true}).count(),0);await fetch(api+'/qa-mode?unavailable=0',{method:'POST'});report.checks.push('Source outage never becomes a fictitious zero-work result');assert.deepEqual(item.errors,[]);await item.context.close();report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(-7000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
