import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {build} from 'esbuild';
const dashboard=fileURLToPath(new URL('../',import.meta.url));
assert.ok(process.env.PLAYWRIGHT_MODULE && process.env.AXE_MODULE_PATH);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
const out=resolve(process.env.QA_OUTPUT||'artifacts/roll-manifest-browser');await mkdir(out,{recursive:true});
const fixture=`import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{RollManifestIntake}from'./src/components/roll-manifest-intake';function Fixture(){const[props,setProps]=useState(window.__props);window.__update=p=>setProps(v=>({...v,...p}));return <main><h1>Recepción del rollo</h1><p>QA local sintética. No importa unidades reales.</p><RollManifestIntake {...props}/></main>}createRoot(document.getElementById('root')).render(<Fixture/>);`;
const bundle=await build({stdin:{contents:fixture,loader:'tsx',resolveDir:dashboard},bundle:true,write:false,outfile:'fixture.js',format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'navigation',setup(b){b.onResolve({filter:/^next\/navigation$/},()=>({path:'router',namespace:'qa'}));b.onLoad({filter:/.*/,namespace:'qa'},()=>({contents:`const router={refresh(){window.__refreshes=(window.__refreshes||0)+1}};export const useRouter=()=>router;`,loader:'js'}));}}]});
const css=bundle.outputFiles.find(f=>f.path.endsWith('.css')).text,js=bundle.outputFiles.find(f=>f.path.endsWith('.js')).text;
const server=createServer((req,res)=>{const url=new URL(req.url,'http://qa.invalid');if(url.pathname==='/fixture.js'){res.setHeader('content-type','text/javascript');return res.end(js);}if(url.pathname!=='/'){res.writeHead(404);return res.end();}const theme=url.searchParams.get('theme')==='dark'?'dark':'light';res.setHeader('content-type','text/html;charset=utf-8');res.end(`<!doctype html><html lang="es-AR" data-theme="${theme}" class="theme-${theme}"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Manifiesto QA</title><style>*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:${theme==='dark'?'#071524':'#f3f7fb'};color:${theme==='dark'?'#eaf3fc':'#143145'}}main{max-width:1100px;padding:16px;margin:auto}h1{font-size:26px}${css}</style></head><body><div id="root"></div><script src="/fixture.js"></script></body></html>`);});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
const report={syntheticData:true,actualComponent:true,productionTested:false,checks:[],views:[],errors:[],unexpected:[]};
const check=(ok,label)=>{report.checks.push({label,passed:Boolean(ok)});assert.ok(ok,label);};
const tick=page=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const content='uid,batch_id\n04000000000001,QA-ROLL-01\n04000000000002,QA-ROLL-01';
const upload=(page,name='roll.csv',buffer=content)=>page.locator('input[type=file]').setInputFiles({name,mimeType:'text/csv',buffer:Buffer.isBuffer(buffer)?buffer:Buffer.from(buffer)});
async function setup(width=390,theme='light',props={}){
 const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce',serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(8000);
 await page.addInitScript(p=>{window.__props=p;const original=File.prototype.text;File.prototype.text=function(){if(this.name==='slow.csv')return new Promise(r=>window.__fileResolve=r);if(this.name==='unreadable.csv')return Promise.reject(Error('local test read failure'));return original.call(this)};window.__clockOffset=0;const now=Date.now;Date.now=()=>now()+window.__clockOffset;},{bid:'QA-ROLL-01',canImport:true,alreadyRegistered:false,scopeKey:'A',...props});
 page.on('pageerror',e=>report.errors.push(e.message));const state={calls:[],mode:'ok',pending:[]};
 const reply=async(route,body,status=200)=>route.fulfill({status,headers:{'content-type':'application/json','x-nexid-data-mode':'production'},body:typeof body==='string'?body:JSON.stringify(body)}).catch(()=>{});
 await page.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(url.origin!==origin){report.unexpected.push(url.origin);return route.abort();}if(url.pathname.includes('/import-manifest')){const command=req.postDataJSON();state.calls.push(command);check(req.method()==='POST' && command.activateImported===false && Object.keys(command).sort().join(',')==='activateImported,csv,dryRun','Only bounded existing manifest command; no activation or overrides');const bid=decodeURIComponent(url.pathname.split('/').at(-2));const result={ok:true,batch:bid,...(command.dryRun?{dryRun:true}:{}),activated:false,importedRows:2,inserted:2,ignored:0,reactivated:0,duplicateUids:[]};if(state.mode==='delayed'){state.pending.push({route,result});return;}if(/^\d+$/.test(state.mode))return reply(route,{ok:false,reason:'SQL_OR_SECRET_MUST_NOT_RENDER'},Number(state.mode));if(state.mode==='invalid')return reply(route,'<html>bad gateway</html>');if(state.mode==='demo')result.demo=true;if(state.mode==='foreign')result.batch='OTHER';if(state.mode==='count')result.importedRows=3;return reply(route,result);}if(['/', '/fixture.js','/favicon.ico'].includes(url.pathname))return route.continue();report.unexpected.push(url.pathname);return route.abort();});
 state.release=async()=>{for(const x of state.pending.splice(0))await reply(x.route,x.result);};
 await page.goto(origin+'/?theme='+theme);await page.locator('[data-testid=roll-manifest-intake] > summary').click();return{page,context,state};
}
async function validate(t){await t.page.getByRole('button',{name:'Validar sin importar',exact:true}).click();await t.page.getByRole('status').filter({hasText:'Validación confirmada'}).waitFor();}
async function inspect(t,name,width,theme){await t.page.addScriptTag({content:axe});const violations=await t.page.evaluate(async()=> (await axe.run('main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>({id:v.id,impact:v.impact})));const overflow=await t.page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+1);check(violations.length===0,`${name}: accessibility checks`);check(!overflow,`${name}: no horizontal overflow`);await t.page.screenshot({path:join(out,`${name}-${width}-${theme}.png`),fullPage:true});report.views.push({name,width,theme,violations,overflow});}
try{
 // The original component allows a slower old file read to replace the newest file.
 const race=await setup();await upload(race.page,'slow.csv');await upload(race.page,'newest.csv');await race.page.getByText(/newest.csv/).waitFor();await race.page.evaluate(value=>window.__fileResolve(value),content);await tick(race.page);check((await race.page.locator('main').innerText()).includes('newest.csv')&&!(await race.page.locator('main').innerText()).includes('slow.csv'),'Late file A cannot replace newer selection B');await race.context.close();
 for(const theme of ['light','dark'])for(const width of [320,390,768,1440]){
  const t=await setup(width,theme);await upload(t.page);await t.page.getByTestId('roll-file-fingerprint').waitFor({state:'attached'});check(t.state.calls.length===0,'Selecting and hashing does not upload');await validate(t);check(await t.page.getByRole('button',{name:'Importar archivo validado',exact:true}).isDisabled(),'No import without explicit confirmation');await inspect(t,'manifest-reviewed',width,theme);await t.page.getByRole('checkbox').check();await t.page.getByRole('button',{name:'Importar archivo validado',exact:true}).evaluate(b=>{b.click();b.click()});await t.page.getByRole('status').filter({hasText:'Importación confirmada'}).waitFor();check(t.state.calls.length===2 && t.state.calls[0].dryRun===true && t.state.calls[1].dryRun===false,'One validation and one explicit import, duplicate clicks suppressed');check(await t.page.evaluate(()=>window.__refreshes)===1,'Successful import rereads parent once, never activates');await t.context.close();
 }
 for(const mode of ['503','408','invalid','count']){const t=await setup();await upload(t.page);await validate(t);await t.page.getByRole('checkbox').check();t.state.mode=mode;await t.page.getByRole('button',{name:'Importar archivo validado',exact:true}).click();await t.page.getByRole('status').filter({hasText:'sin confirmar'}).waitFor();check(await t.page.getByRole('button',{name:'Importar archivo validado',exact:true}).count()===0,'Uncertain '+mode+' disables another import');check(!(await t.page.locator('main').innerText()).includes('SQL_OR_SECRET'),'No server diagnostic echoed');await t.page.getByRole('button',{name:'Consultar estado actualizado',exact:true}).click();check(t.state.calls.length===2,'Manual refresh never retries an uncertain write');await t.context.close();}
 for(const mode of ['foreign','demo','invalid','403']){const t=await setup();await upload(t.page);t.state.mode=mode;await t.page.getByRole('button',{name:'Validar sin importar',exact:true}).click();await t.page.getByRole('status').waitFor();check(await t.page.getByRole('checkbox').count()===0,'Rejected '+mode+' validation cannot authorize import');await t.context.close();}
 const expiry=await setup();await upload(expiry.page);await validate(expiry);await expiry.page.getByRole('checkbox').check();await expiry.page.evaluate(()=>window.__clockOffset=300001);await expiry.page.getByRole('button',{name:'Importar archivo validado',exact:true}).click();await expiry.page.getByRole('status').filter({hasText:'Validá nuevamente'}).waitFor();check(expiry.state.calls.length===1,'Expired validation never reaches import endpoint');await expiry.context.close();
 const replace=await setup();await upload(replace.page);await validate(replace);await replace.page.getByRole('checkbox').check();await upload(replace.page,'replacement.csv');await replace.page.getByText(/replacement.csv/).waitFor();check(await replace.page.getByRole('checkbox').count()===0 && replace.state.calls.length===1,'New file clears earlier validation and confirmation');await replace.context.close();
 const stale=await setup();await upload(stale.page);stale.state.mode='delayed';await stale.page.getByRole('button',{name:'Validar sin importar',exact:true}).click();await stale.page.waitForFunction(()=>document.querySelector('input[type=file]')?.disabled);await stale.page.evaluate(()=>window.__update({scopeKey:'B'}));await tick(stale.page);await stale.page.evaluate(()=>window.__update({scopeKey:'A'}));await tick(stale.page);await stale.state.release();await tick(stale.page);check(await stale.page.getByRole('checkbox').count()===0 && !(await stale.page.locator('main').innerText()).includes('Validación confirmada'),'Old A response cannot revive validation after A-B-A scope change');await stale.context.close();
 const denied=await setup();await upload(denied.page);await validate(denied);await denied.page.evaluate(()=>window.__update({canImport:false}));await tick(denied.page);await denied.page.evaluate(()=>window.__update({canImport:true}));await tick(denied.page);check(await denied.page.getByRole('checkbox').count()===0,'Permission loss and restore requires a new file/validation');await denied.context.close();
 for(const [name,data] of [['secrets.csv','uid,k_meta\n04,placeholder'],['huge.csv',Buffer.alloc(1048577,65)],['bad.zip','not csv'],['unreadable.csv',content],['encoding.csv',Buffer.from([0xff,0xfe,0x00])]]){const t=await setup();await upload(t.page,name,data);await t.page.getByRole('status').waitFor();check(t.state.calls.length===0 && await t.page.getByRole('button',{name:'Validar sin importar',exact:true}).isDisabled(),'Invalid local '+name+' never leaves browser');await t.context.close();}
 const readonly=await setup(390,'light',{canImport:false});check(await readonly.page.locator('input[type=file]').count()===0 && readonly.state.calls.length===0,'Read-only identity never gets import controls');await readonly.context.close();
 const existing=await setup(390,'light',{alreadyRegistered:true});check(await existing.page.locator('input[type=file]').count()===0 && existing.state.calls.length===0,'Registered units cannot be silently replaced');await existing.context.close();
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.unexpected,[]);report.status='passed';
}catch(error){report.status='failed';report.failure=String(error.stack||error);throw error;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(done=>server.close(done));console.log(JSON.stringify({status:report.status,checks:report.checks.length,views:report.views.length,output:out}));}