import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import ts from 'typescript';
import {runtimeFixture} from './fixtures/runtime-console.mjs';
import {canReadRuntimeConsole,runtimeConsoleScopeKey} from '../src/lib/runtime-readiness-access.ts';
import {parseRuntimeSnapshot,runtimeSupportSummary,runtimeObservedTime,runtimeSnapshotExpiresAt,RUNTIME_CONSOLE_FEATURES} from '../src/lib/runtime-readiness-contract.ts';
import {readRuntimeSnapshot,fetchRuntimeSnapshot,RuntimeConsoleError} from '../src/lib/runtime-readiness-transport.ts';
const now=Date.parse('2026-09-24T12:00:00Z');
const principal=(patch={})=>({id:'session-A',role:'super-admin',tenantId:null,tenantSlug:null,isDemo:false,deniedPermissions:[],...patch});
const response=(value=runtimeFixture(),status=200,headers={})=>Response.json(value,{status,headers:{'x-nexid-data-mode':'production',...headers}});
const proxySource=await readFile(new URL('../src/lib/runtime-readiness-proxy.ts',import.meta.url),'utf8');
const compiled=ts.transpileModule(proxySource.replace(/^import .*;\r?$/gm,''),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const moduleExports={};new Function('exports','canReadRuntimeConsole','readRuntimeSnapshot','RuntimeConsoleError','productUrls','getDashboardSessionCredential',compiled)(moduleExports,canReadRuntimeConsole,readRuntimeSnapshot,RuntimeConsoleError,{api:'http://never.invalid'},()=>{throw Error('Unexpected credential access');});
const {forwardRuntimeReadiness}=moduleExports;
const req=(query='',method='GET',headers={},signal)=>new Request('http://localhost/api/admin/diagnostics/runtime-readiness'+query,{method,headers:{cookie:'NEVER_FORWARD_COOKIE',Authorization:'Bearer NEVER_FORWARD_CALLER','x-admin-scope':'super_admin','x-admin-tenant':'foreign',...headers},signal});
function deps(patch={},options={}){const calls=[];let credentials=0;return{calls,get credentials(){return credentials;},value:{credential:async()=>{credentials++;if(options.credentialError)throw Error('PRIVATE_CREDENTIAL');return options.missing?null:{session:principal(patch),bearerToken:'synthetic-runtime-session'};},fetcher:async(url,init)=>{calls.push({url,init});if(options.error)throw Error('postgresql://PRIVATE_SECRET/private');return response(options.body||runtimeFixture(),options.status||200,{'set-cookie':'NEVER_FORWARD_COOKIE','x-private':'NEVER_FORWARD_HEADER',...options.headers});},apiBase:options.apiBase||'http://synthetic-api.invalid'}};}
async function forward(d=deps(),request=req()){const r=await forwardRuntimeReadiness(request,d.value);assert.match(r.headers.get('cache-control'),/private.*no-store/);assert.equal(r.headers.get('vary'),'Cookie');assert.equal(r.headers.get('referrer-policy'),'no-referrer');assert.equal(r.headers.get('set-cookie'),null);return{status:r.status,body:await r.json()};}
test('real API projection parses; named prerequisites never grant permission to promote',()=>{const s=parseRuntimeSnapshot(runtimeFixture(now),now);assert.equal(s.requirements.length,8);assert.equal(s.readiness,'further_acceptance_required');assert.equal(s.promotionAllowed,false);assert.equal(s.migrationExecutionAllowed,false);});
for(const id of RUNTIME_CONSOLE_FEATURES.map(f=>f.id))test('derived status detects missing migration for '+id,()=>{const s=parseRuntimeSnapshot(runtimeFixture(now,{blocked:[id]}),now);assert.equal(s.requirements.find(f=>f.id===id).status,'schema_or_ledger_missing');assert.equal(s.readiness,'blocked_on_named_prerequisites');});
test('SQL execution privilege gaps differ from uninstalled schema',()=>{const s=parseRuntimeSnapshot(runtimeFixture(now,{denied:['assignments']}),now);assert.equal(s.requirements.find(f=>f.id==='assignments').status,'execute_privilege_missing');assert.equal(s.requirements.find(f=>f.id==='assignments').missingMigrations.length,0);});
test('enabled flags must agree with prerequisite state',()=>{const raw=runtimeFixture(now,{blocked:['cancellation'],enabled:['cancellation']});assert.deepEqual(parseRuntimeSnapshot(raw,now).enabledWithoutPrerequisites,['cancellation']);assert.throws(()=>parseRuntimeSnapshot({...raw,enabledWithoutPrerequisites:[]},now));});
for(const patch of [{ok:false},{protocol:'other'},{scope:'tenant_admin'},{promotionAllowed:true},{migrationExecutionAllowed:true},{customerRowsRead:true},{demo:true},{demoMode:true},{dataSource:'demo'},{readiness:'ready'}])test('unsafe or contradictory root metadata rejected '+JSON.stringify(patch),()=>assert.throws(()=>parseRuntimeSnapshot(runtimeFixture(now,{extra:patch}),now)));
for(const delta of [-60000,-61000,30001])test('expired or excessively future observation rejected '+delta,()=>assert.throws(()=>parseRuntimeSnapshot(runtimeFixture(now+delta),now)));
test('missing, duplicate or invented requirement is rejected, not displayed as complete',()=>{for(const transform of [r=>r.requirements.pop(),r=>r.requirements.push(r.requirements[0]),r=>r.requirements[0].id='invented',r=>r.requirements[0].status='named_prerequisites_present'&&'ready',r=>r.requirements[0].missingFunctions.push('public.evil()'),r=>r.requirements[0].missingMigrations.push('unverified.sql')]){const raw=runtimeFixture(now);transform(raw);assert.throws(()=>parseRuntimeSnapshot(raw,now));}});
test('ledger, catalogs, role indicators and flags are structurally consistent',()=>{for(const transform of [r=>r.ledger.count='1',r=>r.ledger.count=0,r=>r.ledger.featureMigrations.pop(),r=>r.ledger.featureMigrations.push(r.ledger.featureMigrations[0]),r=>r.ledger.requiredRuntimeMissing=['../secret'],r=>r.catalogs.valuesOrPricesReturned=true,r=>r.role.superuser=null,r=>r.privilegedConnection=true,r=>r.featureFlags.cancellation={configured:false,enabled:true},r=>r.database.endpointId='https://secret.invalid',r=>r.runtime.commit='../secret']){const raw=runtimeFixture(now);transform(raw);assert.throws(()=>parseRuntimeSnapshot(raw,now));}});
test('safe projection strips unknown extras and shared summary excludes infrastructure identifiers',()=>{const raw=runtimeFixture(now);raw.SECRET='NEVER_EXPORT';raw.database.password='NEVER_EXPORT';raw.role.extra='NEVER_EXPORT';const out=parseRuntimeSnapshot(raw,now),summary=runtimeSupportSummary(out);assert.doesNotMatch(JSON.stringify(out),/NEVER_EXPORT/);for(const value of [out.database.name,out.database.sessionRole,out.database.loginRole,out.database.endpointId,out.runtime.deploymentId,out.runtime.commit])assert.ok(!summary.includes(value));assert.match(summary,/No autoriza/);});
test('global superadmin policy respects actual deny semantics and rejects tenant-bound and demo identities',()=>{assert.equal(canReadRuntimeConsole(principal()),true);for(const patch of [{role:'tenant-owner'},{role:'tenant-admin'},{role:'supplier-operator'},{role:'api-integration'},{role:'viewer'},{tenantSlug:'company'},{tenantId:'tenant'},{isDemo:true},{deniedPermissions:['audit.read']},{deniedPermissions:['audit:read']},{deniedPermissions:['*']}])assert.equal(canReadRuntimeConsole(principal(patch)),false,JSON.stringify(patch));assert.equal(canReadRuntimeConsole(null),false);});
test('scope key changes with identity and permissions but not deny ordering',()=>{assert.notEqual(runtimeConsoleScopeKey(principal()),runtimeConsoleScopeKey(principal({id:'session-B'})));assert.notEqual(runtimeConsoleScopeKey(principal()),runtimeConsoleScopeKey(principal({deniedPermissions:['audit.read']})));assert.equal(runtimeConsoleScopeKey(principal({deniedPermissions:['x','y']})),runtimeConsoleScopeKey(principal({deniedPermissions:['y','x']})));});
test('BFF makes exactly one fixed request with its server credential, not caller headers',async()=>{const d=deps(),out=await forward(d);assert.equal(out.status,200);assert.equal(d.calls.length,1);const {url,init}=d.calls[0];assert.equal(url,'http://synthetic-api.invalid/admin/diagnostics/runtime-readiness');assert.equal(init.method,'GET');assert.equal(init.redirect,'error');assert.equal(init.headers.Authorization,'Bearer synthetic-runtime-session');assert.doesNotMatch(JSON.stringify(init),/NEVER_FORWARD|foreign/);assert.doesNotMatch(JSON.stringify(out),/NEVER_FORWARD|synthetic-runtime-session/);});
for(const patch of [{role:'tenant-owner'},{role:'supplier-operator'},{tenantSlug:'company'},{tenantId:'tenant'},{isDemo:true},{deniedPermissions:['audit.read']},{deniedPermissions:['*']}])test('BFF rejects private data access before transport '+JSON.stringify(patch),async()=>{const d=deps(patch);assert.equal((await forward(d)).status,403);assert.equal(d.calls.length,0);});
for(const query of ['?tenant=other','?url=https://other.invalid','?role=neondb_owner','?sql=SELECT%201','?sandbox=true'])test('selector rejection cannot redirect a diagnostic '+query,async()=>{const d=deps();assert.equal((await forward(d,req(query))).status,400);assert.equal(d.credentials,0);assert.equal(d.calls.length,0);});
for(const method of ['POST','PUT','PATCH','DELETE','HEAD','OPTIONS'])test('diagnostic has no write or method-override forwarding '+method,async()=>{const d=deps();assert.equal((await forward(d,req('',method))).status,405);assert.equal(d.credentials,0);});
test('missing, revoked and unavailable sessions remain distinct and errors are sanitized',async()=>{assert.equal((await forward(deps({}, {missing:true}))).status,401);assert.equal((await forward(deps({}, {credentialError:true}))).status,503);for(const status of [401,403,500,503]){const d=deps({}, {status,body:{ok:false,reason:'PRIVATE_SECRET'}}),out=await forward(d);assert.equal(out.status,status>=500?503:status);assert.doesNotMatch(JSON.stringify(out),/PRIVATE_SECRET/);}});
test('BFF refuses malformed or redirected content and strips upstream cookies and extra metadata',async()=>{for(const options of [{body:{ok:true}},{headers:{'content-type':'text/html'}},{error:true},{apiBase:'http://user:secret@other.invalid'}]){const result=await forward(deps({},options));assert.equal(result.status,503);assert.doesNotMatch(JSON.stringify(result),/PRIVATE|user:secret/);}const r=runtimeFixture();r.raw_password='NEVER_FORWARD';assert.doesNotMatch(JSON.stringify(await forward(deps({}, {body:r}))),/NEVER_FORWARD/);});
test('pre-aborted caller never resolves credentials or starts HTTP',async()=>{const c=new AbortController();c.abort();const d=deps();assert.equal((await forward(d,req('','GET',{},c.signal))).status,499);assert.equal(d.credentials,0);assert.equal(d.calls.length,0);});
test('client transport performs only opt-in same-origin GET and requires provenance',async()=>{let seen;await fetchRuntimeSnapshot(undefined,async(url,init)=>{seen={url,init};return response();});assert.equal(seen.url,'/api/admin/diagnostics/runtime-readiness');assert.equal(seen.init.credentials,'same-origin');assert.equal(seen.init.method,'GET');for(const headers of [{'x-nexid-data-mode':'demo'},{'x-nexid-data-mode':''},{'content-type':'text/html'}])await assert.rejects(readRuntimeSnapshot(response(undefined,200,headers),true),e=>e.code==='invalid');});
test('streaming response is bounded and invalid UTF8/JSON never produces a partial report',async()=>{let cancelled=false;const stream=new ReadableStream({pull(c){c.enqueue(new Uint8Array(32769));},cancel(){cancelled=true;}});await assert.rejects(readRuntimeSnapshot(new Response(stream,{headers:{'content-type':'application/json'}})),e=>e.code==='invalid');assert.equal(cancelled,true);for(const body of ['{bad',new Uint8Array([255,254])])await assert.rejects(readRuntimeSnapshot(new Response(body,{headers:{'content-type':'application/json'}})),e=>e.code==='invalid');});
test('client cancellation is forwarded without retries',async()=>{const c=new AbortController();let count=0;const call=fetchRuntimeSnapshot(c.signal,async(url,init)=>{count++;return new Promise((resolve,reject)=>init.signal.addEventListener('abort',()=>reject(new Error('abort'))));});c.abort();await assert.rejects(call,e=>e.code==='cancelled');assert.equal(count,1);});
test('page and settings navigation use the same policy; only GET is exported by the route',async()=>{const page=await readFile(new URL('../src/app/(app)/settings/runtime/page.tsx',import.meta.url),'utf8'),settings=await readFile(new URL('../src/app/(app)/settings/page.tsx',import.meta.url),'utf8'),route=await readFile(new URL('../src/app/api/admin/diagnostics/runtime-readiness/route.ts',import.meta.url),'utf8');assert.match(page,/requireDashboardSession/);assert.match(page,/canReadRuntimeConsole\(session\)/);assert.match(page,/notFound\(\)/);assert.match(settings,/canReadRuntimeConsole\(session\)/);assert.match(route,/export async function GET/);assert.doesNotMatch(route,/export (?:async )?function (?:POST|PATCH|PUT|DELETE)/);});
test('the diagnostic UI does not replace existing operational features or change the release contracts',async()=>{const baseline=JSON.parse(await readFile(new URL('./fixtures/runtime-console-baseline.json',import.meta.url),'utf8'));const digest=createHash('sha256');for(const p of baseline.paths){const content=(await readFile(new URL('../'+p.replace(/^apps\/dashboard\//,''),import.meta.url),'utf8')).replaceAll('\r\n','\n');digest.update(p+'\0'+createHash('sha256').update(content).digest('hex')+'\n');}assert.equal(digest.digest('hex'),baseline.digest);});

test('UTC time is unambiguous at midnight and future clock tolerance cannot extend client visibility past 60 seconds',()=>{
  assert.match(runtimeObservedTime('2026-09-25T00:01:02.000Z'),/00:01:02/);
  assert.equal(runtimeSnapshotExpiresAt(new Date(now+30000).toISOString(),now),now+60000);
  assert.equal(runtimeSnapshotExpiresAt(new Date(now-30000).toISOString(),now),now+30000);
});