import assert from 'node:assert/strict';
import {createServer}from'node:http';
import{mkdir,readFile,writeFile}from'node:fs/promises';
import{join,resolve}from'node:path';
import{fileURLToPath,pathToFileURL}from'node:url';
import{build}from'esbuild';import postcss from'postcss';import tailwindcss from'tailwindcss';
assert.ok(process.env.PLAYWRIGHT_MODULE&&process.env.AXE_MODULE_PATH);
const{chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');
const dashboard=fileURLToPath(new URL('../',import.meta.url)),root=resolve(dashboard,'../..'),output=resolve(process.env.QA_OUTPUT||'artifacts/runtime-access-hotfix-browser');await mkdir(output,{recursive:true});
const fixture=`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{RuntimeAccessNotice}from'./src/components/runtime-access-notice';import{RuntimeReadinessPanel}from'./src/components/runtime-readiness-panel';import{canReadRuntimeConsole}from'./src/lib/runtime-readiness-access';import{AdminNotificationBell}from'./src/components/admin-notification-bell';import{canReadGlobalNotifications}from'./src/lib/admin-notification-access';function App(){const[a,set]=useState(window.__qaAccess);window.__changeAccess=set;const authorized=canReadRuntimeConsole(a);return <div style={{maxWidth:1080,margin:'auto',padding:16}}><header style={{display:'flex',justifyContent:'space-between',gap:12,marginBottom:18}}><span>QA local · {a.role} · {a.tenantSlug||'global'}</span><AdminNotificationBell canReadSensitiveEvents={true} canReadNotifications={canReadGlobalNotifications(a)} scopeKey={JSON.stringify([a.id,a.role,a.tenantSlug,a.isDemo,a.deniedPermissions])}/></header>{authorized?<RuntimeReadinessPanel access={a}/>:<RuntimeAccessNotice reason={a.tenantSlug||a.tenantId?'tenant':'restricted'}/>}</div>};createRoot(document.getElementById('root')).render(<App/>);`;
const plugins=[{name:'qa-isolated-next-and-realtime',setup(b){b.onResolve({filter:/^next\/link$/},()=>({path:'link',namespace:'qa'}));b.onResolve({filter:/dashboard-realtime-provider$/},()=>({path:'realtime',namespace:'qa'}));b.onLoad({filter:/.*/,namespace:'qa'},args=>({loader:'jsx',resolveDir:dashboard,contents:args.path==='link'?`import React from'react';export default function Link({children,prefetch,...props}){return <a {...props}>{children}</a>}`:`import{useSyncExternalStore}from'react';const listen=f=>{window.addEventListener('qa-realtime',f);return()=>window.removeEventListener('qa-realtime',f);};export function useDashboardRealtime(){return useSyncExternalStore(listen,()=>window.__qaRealtime,()=>window.__qaRealtime);}`}));}}];
const bundle=await build({stdin:{contents:fixture,loader:'tsx',resolveDir:dashboard},plugins,bundle:true,write:false,outfile:'fixture.js',format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"','process.env':'{}'},logLevel:'silent'});
const css=(await postcss([tailwindcss({content:[join(dashboard,'src/**/*.{ts,tsx}').replaceAll('\\','/'),join(root,'packages/ui/src/**/*.{ts,tsx}').replaceAll('\\','/'),{raw:fixture,extension:'tsx'}],darkMode:['selector','[data-theme="dark"]'],theme:{extend:{colors:{brand:{dark:'#020617',card:'#0f172a',border:'#1e293b',cyan:'#06b6d4',blue:'#3b82f6'}}}},plugins:[]})]).process(await readFile(join(dashboard,'src/app/globals.css'),'utf8'),{from:undefined})).css+(bundle.outputFiles.find(f=>f.path.endsWith('.css'))?.text||'');
const js=bundle.outputFiles.find(f=>f.path.endsWith('.js')).contents;
const server=createServer((req,res)=>{const u=new URL(req.url,'http://qa.invalid');if(u.pathname==='/fixture.js'){res.setHeader('content-type','text/javascript');return res.end(js);}if(u.pathname==='/favicon.ico'){res.writeHead(204);return res.end();}if(u.pathname!=='/'){res.writeHead(404);return res.end();}const theme=u.searchParams.get('theme')==='dark'?'dark':'light';res.setHeader('content-type','text/html;charset=utf-8');res.end(`<!doctype html><html lang="es-AR" data-theme="${theme}" class="theme-${theme}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NexID acceso · QA</title><style>${css}</style></head><body><div id="root"></div><script src="/fixture.js"></script></body></html>`);});
await new Promise((done,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',done);});const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
const report={localOnly:true,syntheticIdentity:true,syntheticTransport:true,productionUsed:false,checks:[],views:[],clientErrors:[],unexpectedRequests:[]};
const check=(v,name)=>{report.checks.push({name,passed:Boolean(v)});assert.ok(v,name);};const global={id:'global-A',role:'super-admin',tenantSlug:null,tenantId:null,isDemo:false,deniedPermissions:[]};
const tenant={...global,id:'tenant-A',role:'tenant-admin',tenantSlug:'qa-company',tenantId:'qa-tenant'};
const waitFor=async f=>{for(let n=0;n<200;n++){if(f())return;await new Promise(r=>setTimeout(r,25));}assert.ok(f());};
async function scenario(a=tenant,options={}){
 const width=options.width||390,theme=options.theme||'light',context=await browser.newContext({viewport:{width,height:900},locale:'es-AR',reducedMotion:'reduce',serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(10000);
 await page.addInitScript(a=>{window.__qaAccess=a;window.__qaRealtime={status:'disconnected',snapshot:null,events:[],heartbeat:null,activeScopeKey:'qa-global',droppedThroughSequence:0};const original=window.fetch.bind(window);window.fetch=(url,init={})=>original(url,window.__ignoreAbort?{...init,signal:undefined}:init);},a);
 const state={requests:[],pending:[],mode:options.mode||'success',count:5};
 const body=()=>({ok:true,unreadCount:state.count,counts:{new_leads:state.count,open_tickets:0,new_orders:0},latest:[{contact:'private-should-never-render@example.invalid'}]});
 const send=(route,status,data)=>route.fulfill({status,headers:{'content-type':'application/json','cache-control':'no-store'},body:JSON.stringify(data)}).catch(()=>{});
 await page.route('**/*',async route=>{const request=route.request(),u=new URL(request.url());if(u.origin!==origin){report.unexpectedRequests.push(u.origin+u.pathname);return route.abort();}if(u.pathname==='/api/admin/notifications'){state.requests.push({method:request.method(),path:u.pathname});assert.equal(request.method(),'GET');if(state.mode==='delayed'||state.mode==='hang'){state.pending.push({route,data:body()});return;}if(['401','403','500'].includes(state.mode))return send(route,Number(state.mode),{ok:false});return send(route,200,state.mode==='malformed'?{...body(),unreadCount:99}:body());}if(['/','/fixture.js','/favicon.ico'].includes(u.pathname))return route.continue();report.unexpectedRequests.push(u.pathname);return route.abort();});
 page.on('pageerror',e=>report.clientErrors.push(e.message));state.release=async()=>{for(const p of state.pending.splice(0))await send(p.route,200,p.data);};
 await page.goto(origin+'/?theme='+theme);await page.locator('main').waitFor();return{page,context,state,width,theme};
}
async function trigger(page){await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));}
async function inspect(t,name){await t.page.addScriptTag({content:axe});const violations=await t.page.evaluate(async()=>(await window.axe.run('main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})));check(!violations.length,'No detected accessibility violations '+name);check(await t.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal overflow '+name);const file=`${name}-${t.width}-${t.theme}.png`;await t.page.screenshot({path:join(output,file),fullPage:true});report.views.push({name,width:t.width,theme:t.theme,violations,file});}
try{
 for(const theme of ['light','dark'])for(const width of [320,390,1440]){const t=await scenario(tenant,{width,theme});await t.page.getByTestId('runtime-access-restricted').waitFor();check((await t.page.locator('main').innerText()).includes('La página existe'),'Company receives explicit restriction rather than a missing page');check(!await t.page.getByTestId('runtime-refresh').count(),'Denied session has no diagnostic query control');await trigger(t.page);await t.page.evaluate(()=>{window.__qaRealtime={...window.__qaRealtime,status:'connected',snapshot:{receivedAt:new Date().toISOString()}};window.dispatchEvent(new Event('qa-realtime'));});await t.page.waitForTimeout(50);check(t.state.requests.length===0,'Tenant mount, visibility and realtime do not query global notifications');check(!await t.page.getByTestId('global-notification-bell').count(),'No global badge or invented zeros for a tenant');check(await t.page.getByRole('link',{name:'Volver a configuración'}).getAttribute('href')==='/settings','Clear safe return destination');const contrast=await t.page.getByRole('link',{name:'Volver a configuración'}).evaluate(node=>{const c=getComputedStyle(node);const lum=value=>{const rgb=value.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;};const a=lum(c.color),b=lum(c.backgroundColor);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05);});check(contrast>=4.5,'Primary return link has readable text contrast');await inspect(t,'tenant-access');await t.context.close();}
 const restricted=await scenario({...global,deniedPermissions:['audit.read']});await restricted.page.getByTestId('runtime-access-restricted').waitFor();check(!await restricted.page.getByTestId('runtime-refresh').count(),'Global account with audit deny stays outside diagnostics');await restricted.context.close();
 const valid=await scenario(global);await valid.page.getByLabel('5 unread notifications').waitFor();check(valid.state.requests.length===1,'Authorized global inbox loads once');check(await valid.page.getByTestId('runtime-refresh').count()===1,'Authorized runtime console retained');check(!(await valid.page.locator('body').innerText()).includes('private-should-never-render'),'Notification contacts never rendered from the payload');valid.state.mode='500';await trigger(valid.page);await valid.page.getByTitle('Resumen de notificaciones sin confirmar').waitFor();check(!await valid.page.getByLabel('5 unread notifications').count(),'Failed refresh clears stale badge instead of inventing zero');valid.state.mode='success';valid.state.count=0;await trigger(valid.page);await valid.page.getByTitle('Leads 0 / tickets 0 / orders 0').waitFor();check(true,'Genuinely confirmed zero remains distinct from unavailable');await valid.context.close();
 for(const mode of ['401','403']){const t=await scenario(global);await t.page.getByLabel('5 unread notifications').waitFor();t.state.mode=mode;await trigger(t.page);await t.page.getByTestId('global-notification-bell').waitFor({state:'detached'});const n=t.state.requests.length;for(let i=0;i<3;i++){await trigger(t.page);await t.page.evaluate(()=>{window.__qaRealtime={...window.__qaRealtime,snapshot:{receivedAt:new Date().toISOString()}};window.dispatchEvent(new Event('qa-realtime'));});}await t.page.waitForTimeout(100);check(t.state.requests.length===n,'No repeated request after authoritative '+mode);check(!await t.page.getByLabel('5 unread notifications').count(),'Denied response removes badge '+mode);await t.context.close();}
 const delayed=await scenario(global,{mode:'delayed'});await waitFor(()=>delayed.state.pending.length===1);await delayed.page.evaluate(()=>{window.__ignoreAbort=true;});await delayed.page.evaluate(a=>window.__changeAccess(a),tenant);await delayed.page.getByTestId('runtime-access-restricted').waitFor();await delayed.state.release();await delayed.page.waitForTimeout(100);check(!await delayed.page.getByTestId('global-notification-bell').count(),'Late global response cannot display counters in a tenant session');await delayed.context.close();
 const race=await scenario({...tenant,id:'start'});await race.page.evaluate(()=>{window.__ignoreAbort=true;});race.state.mode='delayed';await race.page.evaluate(a=>window.__changeAccess(a),global);await waitFor(()=>race.state.pending.length===1);await race.page.evaluate(a=>window.__changeAccess({...a,id:'global-B'}),global);await waitFor(()=>race.state.pending.length===2);race.state.mode='success';race.state.count=7;await race.page.evaluate(a=>window.__changeAccess(a),global);await race.page.getByLabel('7 unread notifications').waitFor();await race.state.release();await race.page.waitForTimeout(150);check(await race.page.getByLabel('7 unread notifications').count()===1&&!await race.page.getByLabel('5 unread notifications').count(),'A to B to A ignores older global responses even when abort is ignored');await race.context.close();
 const malformed=await scenario(global,{mode:'malformed'});await malformed.page.getByTitle('Resumen de notificaciones sin confirmar').waitFor();await waitFor(()=>malformed.state.requests.length===1);await malformed.page.waitForTimeout(100);check(!await malformed.page.locator('.admin-notification-bell__badge').count(),'Inconsistent counters never become a displayed notification count');await malformed.context.close();
 const timeout=await scenario(global,{mode:'hang'});await waitFor(()=>timeout.state.pending.length===1);await timeout.page.waitForTimeout(15700);check(timeout.state.requests.length===1,'Fifteen-second deadline does not trigger automatic retries');await timeout.page.evaluate(a=>window.__changeAccess(a),tenant);await timeout.context.close();
 assert.deepEqual(report.clientErrors,[]);assert.deepEqual(report.unexpectedRequests,[]);report.status='passed';
}catch(error){report.status='failed';report.error=String(error.stack||error);throw error;}
finally{await writeFile(join(output,'report.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(done=>server.close(done));console.log(JSON.stringify({status:report.status,checks:report.checks.length,views:report.views.length,output}));}
