import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {build} from 'esbuild';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import {runtimeFixture} from './fixtures/runtime-console.mjs';
assert.ok(process.env.PLAYWRIGHT_MODULE&&process.env.AXE_MODULE_PATH,'Use preinstalled isolated browser tools');
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const axeSource=await readFile(process.env.AXE_MODULE_PATH,'utf8');
const dashboard=fileURLToPath(new URL('../',import.meta.url)),root=resolve(dashboard,'../..');
const output=resolve(process.env.QA_OUTPUT||'artifacts/runtime-console-browser');await mkdir(output,{recursive:true});
const fixture=`import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{RuntimeReadinessPanel}from'./src/components/runtime-readiness-panel';function Fixture(){const[access,setAccess]=useState(window.__qaAccess);window.__qaAccessChange=setAccess;return <div style={{maxWidth:1280,margin:'auto',padding:16}}><aside aria-label="Alcance de prueba" style={{fontSize:12,marginBottom:18}}>QA local · sesión y transporte sintéticos. No se consulta producción.</aside><RuntimeReadinessPanel access={access}/></div>}createRoot(document.getElementById('root')).render(<Fixture/>);`;
const bundle=await build({stdin:{contents:fixture,loader:'tsx',resolveDir:dashboard},bundle:true,write:false,outfile:'fixture.js',format:'iife',platform:'browser',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"','process.env':'{}'},logLevel:'silent'});
const css=(await postcss([tailwindcss({content:[join(dashboard,'src/**/*.{ts,tsx}').replaceAll('\\','/'),join(root,'packages/ui/src/**/*.{ts,tsx}').replaceAll('\\','/'),{raw:fixture,extension:'tsx'}],darkMode:['selector','[data-theme="dark"]'],theme:{extend:{colors:{brand:{dark:'#020617',card:'#0f172a',border:'#1e293b',cyan:'#06b6d4',blue:'#3b82f6'}}}},plugins:[]})]).process(await readFile(join(dashboard,'src/app/globals.css'),'utf8'),{from:undefined})).css+(bundle.outputFiles.find(f=>f.path.endsWith('.css'))?.text||'');
const js=bundle.outputFiles.find(f=>f.path.endsWith('.js')).contents;
const server=createServer((req,res)=>{const u=new URL(req.url,'http://qa.invalid');if(req.method!=='GET'){res.writeHead(405);return res.end();}if(u.pathname==='/fixture.js'){res.setHeader('content-type','text/javascript');return res.end(js);}if(u.pathname==='/favicon.ico'){res.writeHead(204);return res.end();}if(u.pathname!=='/'){res.writeHead(404);return res.end();}const theme=u.searchParams.get('theme')==='dark'?'dark':'light';res.setHeader('content-type','text/html;charset=utf-8');res.end(`<!doctype html><html lang="es-AR" data-theme="${theme}" class="theme-${theme}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NexID Estado operativo · QA</title><style>${css}</style></head><body><div id="root"></div><script src="/fixture.js"></script></body></html>`);});
await new Promise((done,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',done);});const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
const report={localOnly:true,syntheticSessions:true,syntheticTransport:true,actualComponents:['RuntimeReadinessPanel'],actualParser:true,realNextServer:false,productionTested:false,checks:[],views:[],clientErrors:[],unexpectedRequests:[]};
const access={id:'session-A',role:'super-admin',tenantId:null,tenantSlug:null,isDemo:false,deniedPermissions:[]};
const check=(ok,description)=>{report.checks.push({description,passed:Boolean(ok)});assert.ok(ok,description);};
async function waitFor(predicate){for(let n=0;n<300;n++){if(predicate())return;await new Promise(done=>setTimeout(done,20));}assert.ok(predicate(),'Expected synthetic request');}
async function inspect(page,name,width,theme){await page.addScriptTag({content:axeSource});const violations=await page.evaluate(async()=>(await axe.run('main',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}})).violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)})));const dimensions=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));check(!violations.length,`${name} ${width} ${theme}: no axe violations`);check(dimensions.scroll<=dimensions.width+1,`${name} ${width} ${theme}: no horizontal overflow`);const screenshot=`${name}-${width}-${theme}.png`;await page.screenshot({path:join(output,screenshot),fullPage:true});report.views.push({name,width,theme,violations,screenshot});}
async function scenario(width=390,theme='light',options={}){
 const context=await browser.newContext({viewport:{width,height:1000},locale:'es-AR',reducedMotion:'reduce',serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(10000);
 await page.addInitScript(value=>{window.__qaAccess=value;window.__qaCopied=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.__qaCopied.push(text);}}});const original=window.fetch.bind(window);window.fetch=(url,init={})=>original(url,window.__qaIgnoreAbort?{...init,signal:undefined}:init);},options.access||access);
 page.on('pageerror',e=>report.clientErrors.push(e.message));const state={reads:[],mode:'success',pending:[],age:0,fixture:options.fixture||{blocked:['cancellation','quotations','supplier_binding','documentary_ack','ticket_type_compatibility'],broad:true}};
 const fulfill=(route,status,body,headers={})=>route.fulfill({status,headers:{'content-type':'application/json','x-nexid-data-mode':'production',...headers},body:typeof body==='string'?body:JSON.stringify(body)}).catch(()=>{});
 await page.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.origin!==origin){report.unexpectedRequests.push(request.method()+' '+url.origin+url.pathname);return route.abort();}
 if(url.pathname==='/api/admin/diagnostics/runtime-readiness'){state.reads.push({method:request.method(),query:url.search});if(request.method()!=='GET'||url.search){report.unexpectedRequests.push(request.method()+' '+url.pathname);return route.abort();}
 if(['401','403','503'].includes(state.mode))return fulfill(route,Number(state.mode),{ok:false,reason:'synthetic_unavailable'});
 const data=runtimeFixture(Date.now()-state.age,state.fixture);
 if(state.mode==='malformed')return fulfill(route,200,'{broken');if(state.mode==='demo')data.demo=true;if(state.mode==='foreign')data.scope='tenant_admin';if(state.mode==='invented')data.requirements[0].status='ready';
 if(state.mode==='html')return fulfill(route,200,'<html>Not an API response</html>',{'content-type':'text/html'});
 if(state.mode==='delayed'||state.mode==='hang'){state.pending.push({route,data});return;}
 return fulfill(route,200,data);
 }
 if(['/','/fixture.js','/favicon.ico'].includes(url.pathname))return route.continue();report.unexpectedRequests.push(request.method()+' '+url.pathname);return route.abort();});
 state.release=async()=>{for(const p of state.pending.splice(0))await fulfill(p.route,200,p.data);};
 await page.goto(origin+'/?theme='+theme);await page.locator('main').waitFor();return{context,page,state};
}
const query=async page=>{await page.getByTestId('runtime-refresh').click();await page.getByTestId('runtime-result').waitFor();};
try{
 for(const theme of ['light','dark'])for(const width of [320,390,1440]){
  const t=await scenario(width,theme);check(t.state.reads.length===0,'Opening the screen performs no background lookup');await query(t.page);check(t.state.reads.length===1,'One explicit consultation makes one GET');
  check(await t.page.locator('[data-testid^="runtime-feature-"]').count()===8,'Eight source-bound feature requirements shown');await t.page.getByRole('button',{name:'Sólo pendientes',exact:true}).click();check(await t.page.locator('[data-testid^="runtime-feature-"]').count()===5,'Filtering presents only pending requirements');check(t.state.reads.length===1,'Local filtering causes no new API requests');
  await t.page.getByRole('button',{name:'Todos los bloques',exact:true}).click();await t.page.getByTestId('runtime-feature-cancellation').locator('summary').click();await inspect(t.page,'runtime-requirements',width,theme);
  await t.page.getByTestId('runtime-identity').locator('summary').click();await t.page.getByTestId('runtime-summary').locator('summary').click();await t.page.getByTestId('runtime-copy').click();const copied=await t.page.evaluate(()=>window.__qaCopied[0]);
  check(copied.includes('No autoriza migraciones')&&!/qa_runtime_console|qa_effective_role|qa_login_role|ep-synthetic|dpl_Synthetic/.test(copied),'Support copy excludes infrastructure identity');check(t.state.reads.length===1,'Details and copy do not contact services');await inspect(t.page,'runtime-identity',width,theme);
  t.state.mode='403';await t.page.getByTestId('runtime-refresh').click();await t.page.waitForFunction(()=>document.querySelector('[data-testid="runtime-console"]').dataset.state==='forbidden');check(!await t.page.getByTestId('runtime-result').count()&&!/qa_runtime_console|qa_effective_role|ep-synthetic/.test(await t.page.locator('main').innerText()),'Revoked access clears previous counts, identifiers and summary');await t.context.close();
 }
 for(const mode of ['401','503','malformed','demo','foreign','invented','html']){const t=await scenario();t.state.mode=mode;await t.page.getByTestId('runtime-refresh').click();await t.page.waitForFunction(()=>!['idle','reading'].includes(document.querySelector('[data-testid="runtime-console"]').dataset.state));check(!await t.page.getByTestId('runtime-result').count(),'No zero metrics or prior data on '+mode);check(t.state.reads.length===1,'No automatic retry on '+mode);await t.context.close();}
 for(const patch of [{role:'tenant-owner',tenantSlug:'qa-company'},{role:'supplier-operator'},{isDemo:true},{deniedPermissions:['audit.read']}]){const t=await scenario(390,'light',{access:{...access,...patch}});check(!await t.page.getByTestId('runtime-refresh').count()&&t.state.reads.length===0,'Client scope denies before any fetch '+JSON.stringify(patch));await t.context.close();}
 const all=await scenario(390,'light',{fixture:{}});await query(all.page);await all.page.getByRole('button',{name:'Sólo pendientes',exact:true}).click();check((await all.page.locator('main').innerText()).includes('Todavía falta validar la publicación')&&await all.page.locator('[data-testid^="runtime-feature-"]').count()===0,'All named prerequisites present never means approved deployment');await all.context.close();
 const flag=await scenario(390,'light',{fixture:{blocked:['cancellation'],enabled:['cancellation']}});await query(flag.page);check(await flag.page.getByTestId('runtime-inconsistent').count()===1,'Enabled feature with missing schema is prominently flagged');await flag.context.close();
 const expiry=await scenario();expiry.state.age=59000;await query(expiry.page);await expiry.page.waitForFunction(()=>document.querySelector('[data-testid="runtime-console"]').dataset.state==='expired');check(!await expiry.page.getByTestId('runtime-result').count()&&expiry.state.reads.length===1,'Expired observation clears without polling');await expiry.context.close();
 const hidden=await scenario();await query(hidden.page);await hidden.page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await hidden.page.waitForFunction(()=>document.querySelector('[data-testid="runtime-console"]').dataset.state==='hidden');check(!await hidden.page.getByTestId('runtime-result').count()&&hidden.state.reads.length===1,'Page leave clears sensitive data and does not fetch on return');await hidden.context.close();
 const cancel=await scenario();cancel.state.mode='delayed';await cancel.page.getByTestId('runtime-refresh').evaluate(b=>{b.click();b.click();});await waitFor(()=>cancel.state.pending.length===1);check(cancel.state.reads.length===1,'Same-loop duplicate consultations are suppressed');await cancel.page.getByTestId('runtime-cancel').click();await cancel.state.release();await cancel.page.waitForTimeout(100);check(!await cancel.page.getByTestId('runtime-result').count(),'Cancelled response never restores data');check(await cancel.page.getByTestId('runtime-refresh').evaluate(n=>document.activeElement===n),'Cancel restores focus to the enabled query button');await cancel.context.close();
 const race=await scenario();await race.page.evaluate(()=>{window.__qaIgnoreAbort=true;});race.state.mode='delayed';await race.page.getByTestId('runtime-refresh').click();await waitFor(()=>race.state.pending.length===1);
 await race.page.evaluate(a=>window.__qaAccessChange({...a,id:'session-B'}),access);await race.page.waitForFunction(()=>document.querySelector('[data-testid="runtime-console"]').dataset.state==='idle');await race.page.evaluate(a=>window.__qaAccessChange({...a,id:'session-A'}),access);await race.page.waitForTimeout(50);await race.state.release();await race.page.waitForTimeout(100);check(!await race.page.getByTestId('runtime-result').count(),'Transport ignoring abort cannot restore old A data after A-B-A');race.state.mode='success';await query(race.page);await race.page.evaluate(a=>window.__qaAccessChange({...a,deniedPermissions:['audit.read']}),access);await race.page.getByRole('alert').waitFor();check(!await race.page.getByTestId('runtime-result').count(),'Permission withdrawal removes the entire protected view');await race.context.close();
 const timeout=await scenario();timeout.state.mode='hang';const started=Date.now();await timeout.page.getByTestId('runtime-refresh').click();await timeout.page.waitForFunction(()=>document.querySelector('[data-testid="runtime-console"]').dataset.state==='unavailable',{},{timeout:22000});check(Date.now()-started>=14000&&timeout.state.reads.length===1,'Real fifteen-second timeout ends the request without retry');await timeout.context.close();
 assert.deepEqual(report.clientErrors,[]);assert.deepEqual(report.unexpectedRequests,[]);report.status='passed';
}catch(error){report.status='failed';report.error=String(error.stack||error);throw error;}
finally{await writeFile(join(output,'report.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(done=>server.close(done));console.log(JSON.stringify({status:report.status,checks:report.checks.length,views:report.views.length,output},null,2));}
