import assert from 'node:assert/strict';import test from 'node:test';
import{supplierDeliveryAckCall,parseSupplierDeliveryAck}from'../src/lib/supplier-request-delivery-ack-client.ts';
import{ids,command,event,snapshot,result,scope}from'./fixtures/supplier-delivery-ack.mjs';
const op=()=>({key:ids.key,body:command()}),response=(v,status=200,headers={})=>Response.json(v,{status,headers:{'x-nexid-data-mode':'production',...headers}});
test('ack transport sends one source-bound command and no credentials or payload from the browser',async()=>{let seen;const data=await supplierDeliveryAckCall({...scope,command:op()},async(url,init)=>{seen={url,init};return response(result());});assert.equal(data.receipt.revision,1);assert.ok(seen.url.endsWith('/delivery-ack?tenant=qa-a'));assert.equal(seen.init.method,'POST');assert.equal(seen.init.credentials,'same-origin');assert.equal(seen.init.cache,'no-store');assert.deepEqual(JSON.parse(seen.init.body),command());assert.equal(seen.init.headers['Idempotency-Key'],ids.key);assert.doesNotMatch(JSON.stringify(seen),/password|ciphertext|auth_session/);});
test('foreign or demo envelopes and mismatched receipts cannot be promoted to success',()=>{
 for(const patch of [{protocol:'wrong'},{demo:true},{writes_enabled:null},{scope:{mode:'tenant',tenant_id:ids.other,tenant_slug:'qa-a'}},{current:event({source:'supplier_portal'}),history:[event({source:'supplier_portal'})]}])assert.throws(()=>parseSupplierDeliveryAck(snapshot(patch),scope));
 for(const patch of [{receipt:{...result().receipt,idempotency_key:ids.other}},{receipt:{...result().receipt,event_id:ids.other}},{receipt:{...result().receipt,revision:2}},{current:event({evidence_ref:'wrong'}),history:[event({evidence_ref:'wrong'})]},{idempotent_replay:undefined}])assert.throws(()=>parseSupplierDeliveryAck(result(patch),scope,op()));
});
test('read-only historical access works when writes are disabled',async()=>{const r=await supplierDeliveryAckCall(scope,async(url,init)=>{assert.equal(init.method,'GET');assert.equal(init.body,undefined);return response(snapshot({writes_enabled:false}));});assert.equal(r.writes_enabled,false);});
for(const status of [400,401,403,404,409,429])test('explicit refusal '+status+' is certain before any earlier uncertainty',async()=>{await assert.rejects(supplierDeliveryAckCall({...scope,command:op()},async()=>response({ok:false,reason:'supplier_delivery_ack_scope_forbidden'},status)),e=>!e.uncertain&&e.status===status);});
for(const status of [408,500,503])test('unconfirmed '+status+' preserves uncertain mutation',async()=>{await assert.rejects(supplierDeliveryAckCall({...scope,command:op()},async()=>response({ok:false,reason:'supplier_delivery_ack_unavailable'},status)),e=>e.uncertain);});
test('malformed JSON, oversized stream and wrong provenance never acknowledge a write',async()=>{
 for(const responseFactory of [()=>new Response('{broken'),()=>response(result(),200,{'x-nexid-data-mode':'demo'}),()=>new Response('x'.repeat(270000)),()=>response(result({receipt:null}))])await assert.rejects(supplierDeliveryAckCall({...scope,command:op()},async()=>responseFactory()),e=>e.uncertain);
});
test('invalid scopes, cursors and reported hashes fail before transport',async()=>{
 for(const patch of [{id:'bad'},{tenant:'../bad'},{tenantId:'bad'},{orderId:'bad'},{before:0},{before:1,command:op()},{command:{...op(),key:'bad'}},{command:{...op(),body:command({reported_hash:null})}}]){let calls=0;await assert.rejects(supplierDeliveryAckCall({...scope,...patch},async()=>{calls++;return response(result());}));assert.equal(calls,0);}
});
test('abort terminates the single call without automatically replaying',async()=>{const c=new AbortController();let calls=0;const pending=supplierDeliveryAckCall({...scope,signal:c.signal,command:op()},async(url,init)=>{calls++;return new Promise((resolve,reject)=>init.signal.addEventListener('abort',()=>reject(Error('cancel'))));});c.abort();await assert.rejects(pending,e=>e.uncertain);assert.equal(calls,1);});
