import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile}from'node:fs/promises';
import {prepareDraftComparison,resolveDraftComparison,draftRecordFields,draftComparisonValue}from'../src/lib/supplier-draft-comparison.ts';
const row=(patch={})=>({id:'40000000-0000-4000-8000-000000000001',tenant_id:'10000000-0000-4000-8000-000000000001',tenant_slug:'qa-only',status:'draft',revision:1,title:'Proyecto inicial',construction_id:'pet_wet',quantity:125,pack_purpose:null,notes:'Nota inicial',...patch});
const values={title:['Nombre local','Nombre remoto'],construction_id:['tt_bridge','white_wet'],quantity:['250','500'],pack_purpose:['trial_integration','production'],notes:['Notas locales','Notas remotas']};
const set=(record,field,value)=>({...record,[field]:field==='quantity'?Number(value):value});
for(const[field,[localValue,serverValue]]of Object.entries(values))for(const kind of ['unchanged','local_only','server_only','same_change','conflict'])test(field+' three-way '+kind,()=>{
 const base=row(),local={...draftRecordFields(base)},remote={...base,revision:2};
 if(['local_only','same_change','conflict'].includes(kind))local[field]=localValue;
 if(['server_only','conflict'].includes(kind))Object.assign(remote,set(remote,field,serverValue));
 if(kind==='same_change')Object.assign(remote,set(remote,field,localValue));
 const plan=prepareDraftComparison(base,remote,local),entry=plan.rows.find(r=>r.field===field);assert.equal(entry.kind,kind);assert.equal(plan.conflicts,kind==='conflict'?1:0);
 const resolved=resolveDraftComparison(base,remote,local,{});
 if(kind==='conflict'){assert.equal(resolved.ok,false);assert.equal(resolved.reason,'unresolved');assert.deepEqual(resolved.pending,[field]);for(const choice of ['local','server']){const out=resolveDraftComparison(base,remote,local,{[field]:choice});assert.equal(out.ok,true);assert.equal(out.fields[field],choice==='local'?localValue:serverValue);}}
 else{assert.equal(resolved.ok,true);assert.equal(resolved.fields[field],kind==='server_only'?serverValue:local[field]);assert.equal(resolved.revision,2);}
});
test('disjoint changes are proposed without discarding server content and inputs stay immutable',()=>{const base=Object.freeze(row()),server=Object.freeze(row({revision:2,notes:'Notas agregadas en otra sesión'})),local=Object.freeze({...draftRecordFields(base),title:'Nombre local'});const out=resolveDraftComparison(base,server,local,{});assert.equal(out.ok,true);assert.equal(out.fields.title,'Nombre local');assert.equal(out.fields.notes,server.notes);assert.equal(local.notes,base.notes);assert.equal(base.revision,1);});
test('equal normalized numbers and whitespace do not invent semantic conflicts or rewrite the local strings',()=>{const base=row(),server=row({revision:2}),local={...draftRecordFields(base),title:'  Proyecto inicial  ',quantity:'000125',notes:'Nota inicial\n'};const plan=prepareDraftComparison(base,server,local);assert.ok(plan.rows.every(r=>r.kind==='unchanged'));const out=resolveDraftComparison(base,server,local,{});assert.deepEqual(out.fields,local);});
test('clearing optional server/local data is a real explicit choice, never a fallback to original content',()=>{const base=row(),server=row({revision:2,notes:'Nota del servidor'}),local={...draftRecordFields(base),notes:''};assert.equal(resolveDraftComparison(base,server,local,{}).reason,'unresolved');assert.equal(resolveDraftComparison(base,server,local,{notes:'local'}).fields.notes,'');assert.equal(resolveDraftComparison(base,server,local,{notes:'server'}).fields.notes,server.notes);});
test('invalid local selection must be corrected or explicitly replaced from server',()=>{for(const patch of [{title:''},{quantity:'1e3'},{quantity:'1,000'},{notes:'x'.repeat(4001)},{construction_id:'invented'}]){const base=row(),server=row({revision:2}),local={...draftRecordFields(base),...patch};const out=resolveDraftComparison(base,server,local,{});assert.equal(out.reason,'invalid');const field=Object.keys(patch)[0];assert.equal(resolveDraftComparison(base,server,local,{[field]:'server'}).ok,true);}});
for(const status of ['submitted','provisioned','cancelled'])test('terminal record is comparable but never reopened by reconciliation '+status,()=>{const base=row(),server=row({revision:2,status}),local={...draftRecordFields(base),title:'Local'};assert.equal(prepareDraftComparison(base,server,local).editable,false);assert.equal(resolveDraftComparison(base,server,local,{title:'local'}).reason,'not_draft');});
for(const patch of [{id:'40000000-0000-4000-8000-000000000002'},{tenant_id:'10000000-0000-4000-8000-000000000002'},{tenant_slug:'other'},{revision:0},{revision:2147483647},{revision:'2'},{status:'invented'}])test('foreign or invalid source cannot reconcile '+JSON.stringify(patch),()=>assert.throws(()=>prepareDraftComparison(row(),row({revision:2,...patch}),draftRecordFields(row()))));
test('same revision cannot carry changed source data or status; older revisions are rejected',()=>{for(const patch of [{title:'Other'},{quantity:500},{status:'submitted'}])assert.throws(()=>prepareDraftComparison(row(),row(patch),draftRecordFields(row())));assert.throws(()=>prepareDraftComparison(row({revision:3}),row({revision:2}),draftRecordFields(row())));assert.equal(prepareDraftComparison(row(),row(),draftRecordFields(row())).rows[0].kind,'unchanged');});
test('closed local schema and explicit own-field choices prevent incidental authority or prototype fallbacks',()=>{const base=row(),server=row({revision:2,title:'Remoto'}),local={...draftRecordFields(base),title:'Local'};for(const value of [null,[],{}, {...local,id:base.id}])assert.throws(()=>prepareDraftComparison(base,server,value));for(const choices of [null,[],{title:'merge'},{status:'draft'},{tenant_id:'other'},Object.create({title:'server'})])assert.throws(()=>resolveDraftComparison(base,server,local,choices));assert.equal(resolveDraftComparison(base,server,local,Object.create(null)).reason,'unresolved');});
test('comparison token changes when the local text, identity, status or source revision changes',()=>{const base=row(),server=row({revision:2}),local=draftRecordFields(base),token=prepareDraftComparison(base,server,local).token;for(const[other,form]of [[row({revision:3}),local],[row({revision:2,status:'submitted'}),local],[server,{...local,notes:'Nueva nota'}]])assert.notEqual(prepareDraftComparison(base,other,form).token,token);});
test('display labels distinguish missing quantities and purpose, with original note text kept literal',()=>{assert.equal(draftComparisonValue('quantity',''),'Cantidad pendiente');assert.equal(draftComparisonValue('notes',''),'Sin notas');assert.equal(draftComparisonValue('pack_purpose',''),'Sin elegir');assert.match(draftComparisonValue('construction_id','tt_bridge'),/precinto/);assert.equal(draftComparisonValue('notes','<script>literal</script>'),'<script>literal</script>');});
test('workspace does not save or submit during unresolved comparison; selection preserves source revision and existing receipt path',async()=>{const s=await readFile(new URL('../src/components/supplier-request-workspace.tsx',import.meta.url),'utf8');assert.match(s,/resolveDraftComparison\(selected,comparison,fields,choices\)/);assert.match(s,/plan.token!==token/);assert.match(s,/setSelected\(comparison\);setFields\(merged\)/);assert.match(s,/expected_revision: selected.revision/);assert.match(s,/phase==='conflict' \|\| comparison/);assert.match(s,/if\(compare\)setComparison\(null\)/);assert.doesNotMatch(s,/localStorage|sessionStorage/);});
