import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const menuSource = await readFile(new URL("../src/components/tenant-account-menu.tsx", import.meta.url), "utf8");
const globalsSource = await readFile(new URL("../src/app/globals.css", import.meta.url), "utf8");
const pwaSetupSource = await readFile(new URL("../src/components/pwa-setup.tsx", import.meta.url), "utf8");
const serviceWorkerSource = await readFile(new URL("../public/sw.js", import.meta.url), "utf8");

test("tenant account menu renders as a top-level drawer above CRM layers", () => {
  assert.match(menuSource, /const ACCOUNT_MENU_PORTAL_ROOT_ID = "nexid-account-menu-root"/);
  assert.match(menuSource, /function getAccountMenuPortalRoot\(\)/);
  assert.match(menuSource, /function promoteAccountMenuPortalRoot\(root: HTMLElement\)/);
  assert.match(menuSource, /root\.setAttribute\("data-account-menu-root", "true"\)/);
  assert.match(menuSource, /document\.body\.appendChild\(root\)/);
  assert.match(menuSource, /root\.parentElement !== document\.body \|\| root !== document\.body\.lastElementChild/);
  assert.match(menuSource, /root\.style\.setProperty\("z-index", String\(ACCOUNT_MENU_Z_INDEX\), "important"\)/);
  assert.match(menuSource, /root\.style\.setProperty\("pointer-events", "none", "important"\)/);
  assert.match(menuSource, /root\.style\.setProperty\("width", "100vw", "important"\)/);
  assert.match(menuSource, /root\.style\.setProperty\("height", "100dvh", "important"\)/);
  assert.match(menuSource, /root\.toggleAttribute\("data-account-menu-active", value\)/);
  assert.match(menuSource, /root\.style\.setProperty\("pointer-events", value \? "auto" : "none", "important"\)/);
  assert.match(menuSource, /setPortalRoot\(root\)/);
  assert.match(menuSource, /window\.requestAnimationFrame\(\(\) => \{/);
  assert.match(menuSource, /const promotedRoot = getAccountMenuPortalRoot\(\)/);
  assert.match(menuSource, /setPortalRoot\(getAccountMenuPortalRoot\(\)\)/);
  assert.match(menuSource, /const activePortalRoot = typeof document !== "undefined" \? \(portalRoot \|\| getAccountMenuPortalRoot\(\)\) : null/);
  assert.match(menuSource, /createPortal\(menuPanel,\s*activePortalRoot\)/);
  assert.doesNotMatch(menuSource, /createPortal\(menuPanel,\s*portalRoot \|\| document\.body\)/);
  assert.match(menuSource, /const ACCOUNT_MENU_Z_INDEX = 2147483647/);
  assert.match(menuSource, /const ACCOUNT_MENU_BACKDROP_Z_INDEX = ACCOUNT_MENU_Z_INDEX - 1/);
  assert.match(menuSource, /const ACCOUNT_MENU_PANEL_Z_INDEX = ACCOUNT_MENU_Z_INDEX/);
  assert.match(menuSource, /const ACCOUNT_MENU_VERSION = "drawer-v12-top-layer-hardening"/);
  assert.match(menuSource, /const ACCOUNT_MENU_CRITICAL_CSS = `/);
  assert.match(menuSource, /body\.nexid-account-menu-open > :not\(#nexid-account-menu-root\):not\(script\):not\(style\)/);
  assert.match(menuSource, /html\.nexid-account-menu-open body > :not\(#nexid-account-menu-root\):not\(script\):not\(style\)/);
  assert.match(menuSource, /visibility:\s*hidden !important/);
  assert.match(menuSource, /user-select:\s*none !important/);
  assert.match(menuSource, /z-index:\s*\$\{ACCOUNT_MENU_Z_INDEX\} !important/);
  assert.match(menuSource, /z-index:\s*\$\{ACCOUNT_MENU_PANEL_Z_INDEX\} !important/);
  assert.doesNotMatch(menuSource, /z-index:\s*2147483630 !important/);
  assert.doesNotMatch(menuSource, /z-index:\s*2147483631 !important/);
  assert.doesNotMatch(menuSource, /z-index:\s*2147483632 !important/);
  assert.match(menuSource, /useRef<HTMLDivElement \| null>/);
  assert.doesNotMatch(menuSource, /useRef<HTMLDialogElement \| null>/);
  assert.doesNotMatch(menuSource, /showModal\(\)/);
  assert.doesNotMatch(menuSource, /dialog\.close\(\)/);
  assert.doesNotMatch(menuSource, /<dialog/);
  assert.match(menuSource, /role="dialog"/);
  assert.match(menuSource, /aria-modal="true"/);
  assert.match(menuSource, /data-account-menu-portal="body"/);
  assert.match(menuSource, /data-account-menu-version=\{ACCOUNT_MENU_VERSION\}/);
  assert.match(menuSource, /data-account-menu-top-layer="portal"/);
  assert.match(menuSource, /data-account-menu-critical-style="true"/);
  assert.match(menuSource, /data-testid="tenant-account-menu-critical-style"/);
  assert.match(menuSource, /dangerouslySetInnerHTML=\{\{ __html: ACCOUNT_MENU_CRITICAL_CSS \}\}/);
  assert.match(menuSource, /data-account-menu-backdrop="true"/);
  assert.match(menuSource, /data-testid="tenant-account-menu-backdrop"/);
  assert.match(menuSource, /className="nexid-account-backdrop"/);
  assert.match(menuSource, /data-testid="tenant-account-menu-context"/);
  assert.match(menuSource, /Workspace activo/);
  assert.match(menuSource, /Accesos SaaS/);
  assert.match(menuSource, /\[nextAction, \.\.\.primaryItems\.slice\(0, 2\)\]/);
  assert.doesNotMatch(menuSource, /onCancel=\{\(event\) => \{/);
  assert.match(menuSource, /const ACCOUNT_LAYER_STYLE: CSSProperties = \{/);
  assert.match(menuSource, /width:\s*"min\(100vw, 32rem\)"/);
  assert.match(menuSource, /height:\s*"100dvh"/);
  assert.match(menuSource, /maxWidth:\s*"min\(100vw, 32rem\)"/);
  assert.match(menuSource, /overscrollBehavior:\s*"contain"/);
  assert.match(menuSource, /const setDocumentMenuState = useCallback/);
  assert.match(menuSource, /const prepareMenuPortalRoot = useCallback/);
  assert.match(menuSource, /onPointerDownCapture=\{\(\) => \{/);
  assert.match(menuSource, /prepareMenuPortalRoot\(\)/);
  assert.match(menuSource, /document\.documentElement\.classList\.toggle\("nexid-account-menu-open", value\)/);
  assert.match(menuSource, /document\.body\.classList\.toggle\("nexid-account-menu-open", value\)/);
  assert.match(menuSource, /document\.body\.toggleAttribute\("data-account-menu-open", value\)/);
  assert.match(menuSource, /body\.nexid-account-menu-open \.dashboard-shell-root/);
  assert.match(menuSource, /function setCrmShellSuppression\(value: boolean\)/);
  assert.match(menuSource, /document\.querySelectorAll<HTMLElement>\("\.nexid-crm-shell"\)/);
  assert.match(menuSource, /node\.setAttribute\("data-account-menu-suppressed", "true"\)/);
  assert.match(menuSource, /node\.setAttribute\("aria-hidden", "true"\)/);
  assert.match(menuSource, /node\.style\.setProperty\("display", "none", "important"\)/);
  assert.match(menuSource, /node\.style\.setProperty\("z-index", "0", "important"\)/);
  assert.match(menuSource, /node\.style\.setProperty\("filter", "saturate\(0\.78\) brightness\(0\.48\) blur\(0\.5px\)", "important"\)/);
  assert.match(menuSource, /node\.style\.setProperty\("opacity", "0", "important"\)/);
  assert.match(menuSource, /node\.style\.setProperty\("visibility", "hidden", "important"\)/);
  assert.match(menuSource, /node\.style\.removeProperty\("display"\)/);
  assert.match(menuSource, /\.inert = true/);
  assert.match(menuSource, /\.inert = false/);
  assert.match(menuSource, /useIsomorphicLayoutEffect\(\(\) => \{\s*if \(!open\) return;\s*setDocumentMenuState\(true\)/);
  assert.match(menuSource, /surface\?: "dashboard" \| "crm"/);
  assert.match(menuSource, /surface = "dashboard"/);
  assert.match(menuSource, /data-testid="tenant-account-menu-close"/);
  assert.match(menuSource, /aria-label="Cerrar panel de cuenta"/);
  assert.match(menuSource, /aria-haspopup="dialog"/);
  assert.match(menuSource, /aria-label="Cuenta operativa nexID"/);
  assert.match(menuSource, /data-account-menu-source=\{surface\}/);
  assert.match(menuSource, /data-account-menu-surface=\{surface\}/);
  assert.match(menuSource, /data-account-menu-trigger-surface=\{surface\}/);
  assert.match(menuSource, /\.nexid-account-backdrop/);
  assert.doesNotMatch(menuSource, /nexid-account-dialog::backdrop/);
  assert.match(menuSource, /data-account-menu-panel="drawer"/);
  assert.match(menuSource, /closeButtonRef\.current\?\.focus\(\)/);
  assert.doesNotMatch(menuSource, /bg-slate-950\/80/);
  assert.match(menuSource, /backgroundColor:\s*"#020817"/);
  assert.doesNotMatch(menuSource, /backdrop-filter:\s*blur\(18px\) saturate\(1\.1\)/);
  assert.match(menuSource, /tenant-account-panel__header/);
  assert.match(menuSource, /top:\s*0/);
  assert.match(menuSource, /right:\s*0/);
  assert.match(menuSource, /bottom:\s*0/);
  assert.match(menuSource, /left:\s*"auto"/);
  assert.match(menuSource, /width:\s*"min\(100vw, 32rem\)"/);
  assert.match(menuSource, /height:\s*"100dvh"/);
  assert.match(menuSource, /maxHeight:\s*"100dvh"/);
  assert.match(menuSource, /const layerStyle = isCompact/);
  assert.match(menuSource, /maxWidth:\s*"100vw"/);
  assert.match(menuSource, /Object\.entries\(layerStyle\)/);
  assert.match(menuSource, /layerRef\.current\?\.style\.setProperty/);
  assert.match(menuSource, /const contentStyle = \{/);
  assert.match(menuSource, /width:\s*"100%"/);
  assert.match(menuSource, /maxHeight:\s*"100dvh"/);
  assert.match(menuSource, /className="tenant-account-panel isolate flex flex-col overflow-hidden/);
  assert.match(menuSource, /className="min-h-0 flex-1 overflow-y-auto p-3"/);
  assert.match(menuSource, /permissions = \[\]/);
  assert.match(menuSource, /const canManageUsers = role === "super-admin"/);
  assert.match(menuSource, /const isClerkSsoSession = role === "super-admin" && Boolean\(clerkEnabled\)/);
  assert.match(menuSource, /const accountSecurityOk = Boolean\(mfaVerified\) \|\| isClerkSsoSession/);
  assert.match(menuSource, /data-testid="tenant-account-session-summary"/);
  assert.match(menuSource, /data-testid="tenant-account-workspace-command-center"/);
  assert.match(menuSource, /const workspaceInsights = \[/);
  assert.match(menuSource, /label: "Workspace"/);
  assert.match(menuSource, /label: "Seguridad"/);
  assert.match(menuSource, /label: "Plan"/);
  assert.match(menuSource, /label: "Region"/);
  assert.match(menuSource, /Cuenta lista para operar SaaS/);
  assert.match(menuSource, /const workspaceStatus = setupCompleted === false/);
  assert.match(menuSource, /data-testid="tenant-account-primary-action"/);
  assert.match(menuSource, /const hasWildcardAccess = permissions\.includes\("\*"\)/);
  assert.match(menuSource, /role === "super-admin" \|\| mode === "global" \? "Acceso global" : "Tenant completo"/);
  assert.match(menuSource, /const nextAction = setupCompleted === false && role === "tenant-admin"/);
  assert.match(menuSource, /: !accountSecurityOk/);
  assert.match(menuSource, /isClerkSsoSession \? "sso ok" : mfaVerified \? "mfa ok" : "mfa revisar"/);
  assert.match(menuSource, /label: isTenantMode \? `Perfil \$\{tenantName\}` : "Directorio de tenants"/);
  assert.doesNotMatch(menuSource, /label: isTenantMode \? "Perfil Bodega Balmec"/);
  assert.match(menuSource, /href: canManageUsers \? "\/users" : "\/settings"/);
});

test("tenant account menu closes nexID and Clerk sessions when OAuth is active", () => {
  assert.match(menuSource, /import \{ useClerk \} from "@clerk\/nextjs"/);
  assert.match(menuSource, /function ClerkSecureLogoutButton/);
  assert.match(menuSource, /const \{ signOut \} = useClerk\(\)/);
  assert.match(menuSource, /await fetch\("\/logout", \{ method: "POST", cache: "no-store" \}\)/);
  assert.match(menuSource, /await signOut\(\{ redirectUrl: "\/login\?logged_out=1" \}\)/);
  assert.match(menuSource, /function SecureLogoutButton\(\{ clerkEnabled, onStart \}/);
  assert.match(menuSource, /if \(clerkEnabled\) return <ClerkSecureLogoutButton onStart=\{onStart\} \/>/);
  assert.match(menuSource, /<SecureLogoutButton clerkEnabled=\{clerkEnabled\} onStart=\{\(\) => setDocumentMenuState\(false\)\} \/>/);
});

test("global CSS prevents dashboard maps from covering account drawer", () => {
  assert.match(globalsSource, /html\.nexid-account-menu-open,\s*body\.nexid-account-menu-open\s*\{[\s\S]*overflow:\s*hidden/);
  assert.match(globalsSource, /body\.nexid-account-menu-open > :not\(#nexid-account-menu-root\):not\(script\):not\(style\)/);
  assert.match(globalsSource, /html\.nexid-account-menu-open body > :not\(#nexid-account-menu-root\):not\(script\):not\(style\)/);
  assert.match(globalsSource, /body\.nexid-account-menu-open > :not\(#nexid-account-menu-root\):not\(script\):not\(style\),[\s\S]*user-select:\s*none !important/);
  assert.match(globalsSource, /body\.nexid-crm-overlay-active \.dashboard-sidebar,\s*body\.nexid-crm-overlay-active \.dashboard-header,\s*body\.nexid-crm-overlay-active \.dashboard-mobile-dock\s*\{[\s\S]*display:\s*none !important/);
  assert.match(globalsSource, /\.dashboard-shell-root:has\(\.nexid-crm-shell\) \.dashboard-header \.dashboard-shell-account-menu\s*\{[\s\S]*display:\s*none !important/);
  assert.match(globalsSource, /\.dashboard-shell-root:has\(\.nexid-crm-shell\) \.dashboard-header \.dashboard-shell-account-menu\s*\{[\s\S]*pointer-events:\s*none !important/);
  assert.match(globalsSource, /\.nexid-crm-shell \.nexid-crm-account-menu\s*\{[\s\S]*z-index:\s*980 !important/);
  assert.match(globalsSource, /\.nexid-crm-shell \.nexid-crm-account-menu \[data-testid="tenant-account-menu-trigger"\]\s*\{[\s\S]*z-index:\s*981 !important/);
  assert.match(globalsSource, /#nexid-account-menu-root\s*\{[\s\S]*z-index:\s*2147483647 !important/);
  assert.match(globalsSource, /#nexid-account-menu-root\s*\{[\s\S]*display:\s*block !important/);
  assert.match(globalsSource, /#nexid-account-menu-root\s*\{[\s\S]*visibility:\s*visible !important/);
  assert.match(globalsSource, /#nexid-account-menu-root\s*\{[\s\S]*pointer-events:\s*none !important/);
  assert.match(globalsSource, /#nexid-account-menu-root\s*\{[\s\S]*width:\s*100vw !important/);
  assert.match(globalsSource, /#nexid-account-menu-root\s*\{[\s\S]*height:\s*100dvh !important/);
  assert.match(globalsSource, /#nexid-account-menu-root\[data-account-menu-active="true"\]/);
  assert.match(globalsSource, /html\.nexid-account-menu-open #nexid-account-menu-root/);
  assert.match(globalsSource, /body\.nexid-account-menu-open #nexid-account-menu-root/);
  assert.match(globalsSource, /#nexid-account-menu-root\[data-account-menu-active="true"\],[\s\S]*body\.nexid-account-menu-open #nexid-account-menu-root\s*\{[\s\S]*pointer-events:\s*auto !important/);
  assert.match(globalsSource, /#nexid-account-menu-root \.nexid-account-layer\s*\{[\s\S]*pointer-events:\s*auto !important/);
  assert.match(globalsSource, /#nexid-account-menu-root,\s*#nexid-account-menu-root \*\s*\{[\s\S]*visibility:\s*visible !important/);
  assert.match(globalsSource, /\.nexid-account-layer\s*\{[\s\S]*z-index:\s*2147483647 !important/);
  assert.match(globalsSource, /\.nexid-account-layer\s*\{[\s\S]*visibility:\s*visible !important/);
  assert.match(globalsSource, /\.nexid-account-layer\s*\{[\s\S]*opacity:\s*1 !important/);
  assert.match(globalsSource, /\.nexid-account-layer\s*\{[\s\S]*display:\s*flex !important/);
  assert.match(globalsSource, /\.nexid-account-layer\s*\{[\s\S]*width:\s*min\(100vw, 32rem\) !important/);
  assert.match(globalsSource, /\.nexid-account-layer\s*\{[\s\S]*max-width:\s*min\(100vw, 32rem\) !important/);
  assert.match(globalsSource, /\.nexid-account-layer\s*\{[\s\S]*linear-gradient\(180deg, #08111f 0%, #020817/);
  assert.match(globalsSource, /\.nexid-account-layer\s*\{[\s\S]*overscroll-behavior:\s*contain !important/);
  assert.match(globalsSource, /\.nexid-account-backdrop\s*\{[\s\S]*z-index:\s*2147483646 !important/);
  assert.match(globalsSource, /\.nexid-account-backdrop\s*\{[\s\S]*rgba\(2, 6, 23, 0\.86\) !important/);
  assert.doesNotMatch(globalsSource, /\.nexid-account-backdrop\s*\{[\s\S]*backdrop-filter:\s*blur\(18px\) saturate\(1\.1\)/);
  assert.match(globalsSource, /\.nexid-account-backdrop\s*\{[\s\S]*pointer-events:\s*auto !important/);
  assert.match(globalsSource, /\.nexid-account-context\s*\{[\s\S]*z-index:\s*2147483647 !important/);
  assert.match(globalsSource, /\.nexid-account-context\s*\{[\s\S]*width:\s*min\(46rem, calc\(100vw - 36rem - 6vw\)\) !important/);
  assert.match(globalsSource, /\.nexid-account-context\s*\{[\s\S]*pointer-events:\s*auto !important/);
  assert.match(globalsSource, /\.nexid-account-context\s*\{[\s\S]*visibility:\s*visible !important/);
  assert.match(globalsSource, /\.nexid-account-layer,\s*\.nexid-account-layer > \*\s*\{[\s\S]*pointer-events:\s*auto !important/);
  assert.doesNotMatch(globalsSource, /nexid-account-dialog::backdrop/);
  assert.match(globalsSource, /\.nexid-account-layer \.tenant-account-panel\s*\{[\s\S]*display:\s*flex !important/);
  assert.match(globalsSource, /\.nexid-account-layer \.tenant-account-panel\s*\{[\s\S]*z-index:\s*2147483647 !important/);
  assert.match(globalsSource, /\.nexid-account-layer \.tenant-account-panel\s*\{[\s\S]*position:\s*relative !important/);
  assert.match(globalsSource, /\.nexid-account-layer \.tenant-account-panel\s*\{[\s\S]*width:\s*100% !important/);
  assert.match(globalsSource, /\.nexid-account-layer \.tenant-account-panel\s*\{[\s\S]*height:\s*100% !important/);
  assert.match(globalsSource, /\.nexid-account-layer \.tenant-account-panel\s*\{[\s\S]*touch-action:\s*auto/);
  assert.match(globalsSource, /\.nexid-account-layer\s*\{[\s\S]*box-shadow:\s*-36px 0 120px/);
  assert.match(globalsSource, /html\.theme-light \.nexid-account-layer \.tenant-account-panel,\s*html\[data-theme="light"\] \.nexid-account-layer \.tenant-account-panel\s*\{[\s\S]*#020817/);
  assert.match(globalsSource, /html\.theme-light \.nexid-account-layer \.tenant-account-panel \[class\*="bg-slate-950"\]/);
  assert.match(globalsSource, /html\.theme-light \.nexid-account-layer \.tenant-account-panel \.text-slate-400/);
  assert.match(globalsSource, /html\.theme-light \.nexid-account-layer \.tenant-account-panel__header/);
  assert.match(globalsSource, /\.nexid-account-layer \.tenant-account-panel__header,[\s\S]*\{[\s\S]*color:\s*#f8fafc !important/);
  assert.match(globalsSource, /html\.theme-light \.nexid-account-layer \.tenant-account-panel__header \.text-white/);
  assert.match(globalsSource, /\.tenant-account-panel__header \.text-white,[\s\S]*\{[\s\S]*color:\s*#f8fafc !important/);
  assert.match(globalsSource, /html\.theme-light \.nexid-account-layer \.tenant-account-panel__header \.text-slate-400/);
  assert.match(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell,\s*\.nexid-crm-shell\[data-account-menu-suppressed="true"\]\s*\{[\s\S]*pointer-events:\s*none !important/);
  assert.match(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell,\s*\.nexid-crm-shell\[data-account-menu-suppressed="true"\]\s*\{[\s\S]*display:\s*none !important/);
  assert.match(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell,\s*\.nexid-crm-shell\[data-account-menu-suppressed="true"\]\s*\{[\s\S]*z-index:\s*0 !important/);
  assert.match(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell,\s*\.nexid-crm-shell\[data-account-menu-suppressed="true"\]\s*\{[\s\S]*filter:\s*saturate\(0\.78\) brightness\(0\.48\) blur\(0\.5px\) !important/);
  assert.match(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell,\s*\.nexid-crm-shell\[data-account-menu-suppressed="true"\]\s*\{[\s\S]*opacity:\s*0 !important/);
  assert.match(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell,\s*\.nexid-crm-shell\[data-account-menu-suppressed="true"\]\s*\{[\s\S]*visibility:\s*hidden !important/);
  assert.match(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell,\s*\.nexid-crm-shell\[data-account-menu-suppressed="true"\]\s*\{[\s\S]*contain:\s*none !important/);
  assert.match(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell,\s*\.nexid-crm-shell\[data-account-menu-suppressed="true"\]\s*\{[\s\S]*user-select:\s*none !important/);
  assert.match(globalsSource, /html\.nexid-account-menu-open \.dashboard-shell-root,\s*body\.nexid-account-menu-open \.dashboard-shell-root/);
  assert.match(globalsSource, /html\.nexid-account-menu-open \.dashboard-header,\s*body\.nexid-account-menu-open \.dashboard-header/);
  assert.match(globalsSource, /html\.nexid-account-menu-open \.dashboard-sidebar,\s*body\.nexid-account-menu-open \.dashboard-sidebar/);
  assert.match(globalsSource, /html\.nexid-account-menu-open \.dashboard-mobile-dock,\s*body\.nexid-account-menu-open \.dashboard-mobile-dock/);
  assert.match(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell \*\s*\{[\s\S]*pointer-events:\s*none !important/);
  assert.doesNotMatch(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell\s*\{[\s\S]*opacity:\s*0\.16 !important/);
  assert.doesNotMatch(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell \[class\*="fixed"\]/);
  assert.doesNotMatch(globalsSource, /body\.nexid-account-menu-open \.nexid-crm-shell \[class\*="absolute"\]/);
  assert.match(globalsSource, /html\.nexid-account-menu-open \.nexid-crm-shell \[id="live-tap-map"\]/);
  assert.match(globalsSource, /html\.nexid-account-menu-open \.nexid-crm-shell \.maplibregl-control-container/);
  assert.match(globalsSource, /body\.nexid-account-menu-open \.nexid-account-layer \*/);
  assert.match(globalsSource, /@media \(max-width:\s*640px\)\s*\{[\s\S]*\.nexid-account-layer\s*\{[\s\S]*inset:\s*0 !important/);
  assert.match(globalsSource, /@media \(max-width:\s*640px\)\s*\{[\s\S]*\.nexid-account-context\s*\{[\s\S]*display:\s*none !important/);
  assert.match(globalsSource, /@media \(max-width:\s*640px\)\s*\{[\s\S]*\.nexid-account-layer\s*\{[\s\S]*width:\s*100vw !important/);
  assert.match(globalsSource, /@media \(max-width:\s*640px\)\s*\{[\s\S]*\.nexid-account-layer\s*\{[\s\S]*max-width:\s*100vw !important/);
  assert.match(globalsSource, /@media \(max-width:\s*640px\)\s*\{[\s\S]*\.nexid-account-layer \.tenant-account-panel\s*\{[\s\S]*height:\s*100% !important/);
});

test("dashboard PWA registration is opt-in so stale admin CSS cannot mask fixes", () => {
  assert.match(pwaSetupSource, /process\.env\.NODE_ENV === "production" && process\.env\.NEXT_PUBLIC_ENABLE_PWA === "true"/);
  assert.match(pwaSetupSource, /navigator\.serviceWorker\.getRegistrations\(\)/);
  assert.match(pwaSetupSource, /registration\.unregister\(\)/);
  assert.match(pwaSetupSource, /nexid-dashboard-sw-cleared-v4/);
  assert.match(pwaSetupSource, /window\.location\.reload\(\)/);
  assert.doesNotMatch(pwaSetupSource, /NEXT_PUBLIC_ENABLE_PWA !== "false"/);
});

test("dashboard service worker refreshes shell styles before falling back to cache", () => {
  assert.match(serviceWorkerSource, /const CACHE_NAME = "nexid-dash-v4"/);
  assert.match(serviceWorkerSource, /request\.destination === "script" \|\| request\.destination === "style"/);
  assert.match(serviceWorkerSource, /fetchWithTimeout\(request\)\.then\(\(response\) => \{/);
  assert.match(serviceWorkerSource, /cache\.put\(request,\s*copy\)/);
  assert.match(serviceWorkerSource, /\.catch\(\(\) => caches\.match\(request\)\)/);
  assert.doesNotMatch(serviceWorkerSource, /request\.destination === "image" \|\| request\.destination === "style" \|\| request\.destination === "font"/);
});
