import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';import {join} from 'node:path';import {createHash} from 'node:crypto';
const base='http://localhost:3286',api='http://127.0.0.1:4386',out=process.env.QA_OUTPUT;assert.ok(out);
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href),axe=await readFile(process.env.AXE_MODULE_PATH,'utf8');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const report={localOnly:true,actualHandler:true,actualPostgres:true,checks:[],visual:[]};
const captured=new WeakMap();
const count=async()=>(await(await fetch(api+'/qa-state')).json()).calls.length;
async function open(role='editor',width=1440){const context=await browser.newContext({viewport:{width,height:1000},serviceWorkers:'block',reducedMotion:'reduce',locale:'es-AR',acceptDownloads:true});await context.addCookies([{name:'nexid_dashboard_session',value:'qa-trace-'+role,url:base,httpOnly:true,sameSite:'Lax'}]);const p=await context.newPage(),errors=[],writes=[],pages=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(['POST','PUT','PATCH','DELETE'].includes(r.method())&&r.url().includes('/api/'))writes.push(new URL(r.url()).pathname);});captured.set(p,pages);await p.route('**/*',async r=>{const u=new URL(r.request().url());if(!['localhost','127.0.0.1'].includes(u.hostname))return r.abort();if(u.pathname.startsWith('/api/admin/batches/')&&u.pathname.endsWith('/traceability/page')){const response=await r.fetch();if(response.ok())pages.push(await response.json());return r.fulfill({response});}return r.continue();});await p.goto(base+'/batches/GS1-LOCAL/traceability?from=2026-09-01&to=2026-09-19',{waitUntil:'load',timeout:90000});await p.getByRole('heading',{name:'Recorrido del lote',exact:true}).waitFor();return {context,p,errors,writes,pages};}
async function readAfter(p,button){const before=captured.get(p).length;const pending=p.waitForResponse(r=>r.url().includes('/api/admin/batches/')&&r.url().includes('/traceability/page')&&r.ok());await button.click();await pending;const pages=captured.get(p);assert.ok(pages.length>before);return pages.at(-1);}
async function pageNumber(p,n){await p.locator('[data-testid="batch-traceability"]:visible').getByText('Página '+n,{exact:true}).waitFor();}
try{
 await fetch(api+'/qa-mode',{method:'POST'});const admin=await open(),p=admin.p,root=p.locator('[data-testid="batch-traceability"]:visible');await pageNumber(p,1);const timeline=p.getByRole('region',{name:'Movimientos de esta página'});assert.equal(await timeline.getByRole('button').count(),50);
 const before=await count();await timeline.getByRole('button').nth(2).click();await p.getByRole('searchbox',{name:'Buscar en esta página'}).fill('not-found');assert.equal(await timeline.getByRole('button').count(),0);assert.equal(await p.getByRole('button',{name:'Página siguiente'}).isDisabled(),false);await p.getByRole('searchbox',{name:'Buscar en esta página'}).fill('');assert.equal(await count(),before);report.checks.push('Local row selection and text filtering do not make network reads and do not hide available next pages');
 const second=await readAfter(p,p.getByRole('button',{name:'Página siguiente',exact:true}));await pageNumber(p,2);assert.equal(second.navigation.page,2);assert.equal(second.navigation.returned,50);
 const first=await readAfter(p,p.getByRole('button',{name:'Página anterior',exact:true}));await pageNumber(p,1);assert.equal(first.navigation.cutoff,second.navigation.cutoff);const keys=new Set(first.navigation.positions.map(x=>x.kind+':'+x.id));assert.ok(second.navigation.positions.every(x=>!keys.has(x.kind+':'+x.id)));report.checks.push('Next and previous pages share a record boundary and have no overlapping source/event IDs');
 await p.getByRole('button',{name:'Página siguiente',exact:true}).click();await pageNumber(p,2);const exportBefore=await count();const [file]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'JSON de esta página',exact:true}).click()]);await file.saveAs(join(out,'page.json'));const evidence=JSON.parse(await readFile(join(out,'page.json'),'utf8'));assert.equal(evidence.data.navigation.page,2);assert.equal(evidence.data.navigation.returned,50);assert.equal(evidence.data.exportScope,'current_page_not_complete_history');assert.equal(createHash('sha256').update(JSON.stringify(evidence.data)).digest('hex'),evidence.sha256);assert.ok(!('currentCursor' in evidence.data.navigation));
 const [html]=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Informe de esta página',exact:true}).click()]);await html.saveAs(join(out,'page.html'));assert.equal(await count(),exportBefore);const printable=await admin.context.newPage();let external=0;await printable.route('**/*',r=>{external++;return r.abort();});await printable.setContent(await readFile(join(out,'page.html'),'utf8'));assert.match(await printable.locator('body').innerText(),/Página 2/);assert.equal(external,0);await printable.screenshot({path:join(out,'page-report.png'),fullPage:true});await printable.close();report.checks.push('HTML and JSON export only the loaded page with its filters, record boundary and verifiable digest, without another SQL request');
 await root.getByText('Buscar identidad o tipo en todo el período',{exact:true}).click();await p.getByRole('textbox',{name:'GTIN del historial'}).fill('09506000134352');await p.getByRole('textbox',{name:'Lote GS1 del historial'}).fill('QA-L1');await p.getByRole('textbox',{name:'Serie del historial'}).fill('UNIT-02');assert.equal(await p.getByRole('button',{name:'JSON de esta página'}).isDisabled(),true);await p.getByRole('button',{name:'Consultar recorrido',exact:true}).click();await pageNumber(p,1);assert.equal(await timeline.getByRole('button').count(),1);assert.match(await p.getByRole('region',{name:'Detalle del movimiento'}).innerText(),/2.5.*KGM/);assert.equal(await p.getByRole('button',{name:'Página siguiente'}).isDisabled(),true);report.checks.push('Server identity filters locate an event absent from the initial fifty and retain quantity units');
 const followed=await readAfter(p,p.getByRole('button',{name:'Seguir esta identidad',exact:true}));await root.getByText(/^Identidad exacta ·/).waitFor();await pageNumber(p,1);assert.equal(followed.query.exact,true);report.checks.push('Following a reference runs an exact GTIN/lot/serial investigation instead of mixing empty qualifiers');
 for(const [width,theme] of [[1440,'light'],[1440,'dark'],[390,'light'],[390,'dark']]){await p.setViewportSize({width,height:1000});await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle('theme-light',theme==='light');document.documentElement.classList.toggle('theme-dark',theme==='dark');window.scrollTo(0,0);},theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.addScriptTag({content:axe});const violations=await p.evaluate(async()=>{const r=await axe.run('[data-testid="batch-traceability"]',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)}));});await p.screenshot({path:join(out,`investigation-${width}-${theme}.png`),fullPage:true});assert.deepEqual(violations.filter(v=>['critical','serious'].includes(v.impact)),[]);report.visual.push({width,theme,violations});}
 await p.getByRole('button',{name:'Quitar filtros',exact:true}).click();await p.getByRole('button',{name:'Consultar recorrido',exact:true}).click();await pageNumber(p,1);
 await fetch(api+'/qa-mode?unavailable=1',{method:'POST'});await p.getByRole('button',{name:'Página siguiente'}).click();await p.getByRole('status').filter({hasText:'La página no pudo confirmarse'}).waitFor();assert.equal(await p.getByRole('button',{name:'JSON de esta página'}).isDisabled(),true);await fetch(api+'/qa-mode',{method:'POST'});await p.getByRole('button',{name:'Reintentar la página solicitada'}).click();await pageNumber(p,2);report.checks.push('Failed next-page lookup clears stale evidence and can retry the same read position');
 await fetch(api+'/qa-mode?revoked=1',{method:'POST'});await p.getByRole('button',{name:'Página siguiente'}).click();await p.getByRole('status').filter({hasText:'permisos'}).waitFor();assert.equal(await p.getByRole('button',{name:'JSON de esta página'}).isDisabled(),true);await p.getByRole('button',{name:'Consultar recorrido',exact:true}).click();await pageNumber(p,1);await p.getByRole('button',{name:'Envíos vinculados',exact:true}).click();assert.match(await root.innerText(),/No se incluyeron envíos ni custodia/);await fetch(api+'/qa-mode',{method:'POST'});report.checks.push('Changed logistics permissions invalidate the cursor and a fresh query hides protected custody and shipments');
 const reader=await open('reader',390);await pageNumber(reader.p,1);report.readerOption=await reader.p.locator('[data-testid="batch-traceability"]:visible select[aria-label="Fuente de la consulta"] option[value="custody"]').evaluate(el=>({disabled:el.disabled,attribute:el.getAttribute('disabled'),html:el.outerHTML}));assert.equal(report.readerOption.disabled,true);const forbidden=await reader.context.request.get(base+'/api/admin/batches/GS1-LOCAL/traceability/page?tenant=other-company&from=2026-09-01&to=2026-09-19');assert.equal(forbidden.status(),403);assert.deepEqual(reader.writes,[]);assert.deepEqual(reader.errors,[]);await reader.context.close();
 assert.deepEqual(admin.writes,[]);assert.deepEqual(admin.errors,[]);await admin.context.close();report.checks.push('All read-only browser flows preserve tenant restrictions and execute no business mutations');report.status='passed';
}catch(e){report.status='failed';report.error=e.stack;const p=browser.contexts().at(-1)?.pages().at(-1);if(p){report.visible=(await p.locator('body').innerText()).slice(0,12000);await p.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}
finally{await writeFile(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
