export type ProductNotice={id:string;kind:'recall'|'quarantine';title:string;message:string;instructions:string;contact:string;publishedAt:string;trackingState:'active'|'closing'|'closed'};
export type ProductNotices={ok:true;protocol:'nexid.product-notices.v1';scope:{tenant:string;bid:string};observedAt:string;notices:ProductNotice[];total:number;hasMore:boolean;doesNotDetermineNfcAuthenticity:true;closureDoesNotReleaseProduct:true};
export function noticeScope(tenant:unknown,bid:unknown){if(typeof tenant!=='string'||typeof bid!=='string'||!/^[a-z0-9][a-z0-9._-]{0,119}$/.test(tenant)||!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,159}$/.test(bid))throw Error('notice_scope_invalid');return {tenant,bid};}
export function parseProductNotices(value:unknown,tenant:string,bid:string):ProductNotices{
 const r=value as ProductNotices;noticeScope(tenant,bid);
 if(!r||r.ok!==true||r.protocol!=='nexid.product-notices.v1'||r.scope?.tenant!==tenant||r.scope?.bid!==bid||r.doesNotDetermineNfcAuthenticity!==true||r.closureDoesNotReleaseProduct!==true||!Array.isArray(r.notices)||r.notices.length>20||!Number.isSafeInteger(r.total)||r.total<r.notices.length||typeof r.hasMore!=='boolean'||r.hasMore!==(r.total>20)||!Number.isFinite(Date.parse(r.observedAt)))throw Error('notice_source_invalid');
 for(const n of r.notices){if(!['recall','quarantine'].includes(n.kind)||!['active','closing','closed'].includes(n.trackingState)||!/^[a-f0-9-]{36}$/i.test(n.id)||!Number.isFinite(Date.parse(n.publishedAt)))throw Error('notice_invalid');for(const [k,max] of [['title',160],['message',600],['instructions',1000],['contact',200]] as const)if(typeof n[k]!=='string'||n[k].length>max)throw Error('notice_invalid');}
 return {ok:true,protocol:r.protocol,scope:{tenant,bid},observedAt:r.observedAt,notices:r.notices.map(n=>({id:n.id,kind:n.kind,title:n.title,message:n.message,instructions:n.instructions,contact:n.contact,publishedAt:n.publishedAt,trackingState:n.trackingState})),total:r.total,hasMore:r.hasMore,doesNotDetermineNfcAuthenticity:true,closureDoesNotReleaseProduct:true};
}
export async function boundedNoticeJson(r:Response){if(!r.body)throw Error('notice_empty');const reader=r.body.getReader();let count=0;const chunks:Uint8Array[]=[];try{while(true){const x=await reader.read();if(x.done)break;count+=x.value.byteLength;if(count>65536)throw Error('notice_limit');chunks.push(x.value);}const bytes=new Uint8Array(count);let i=0;for(const x of chunks){bytes.set(x,i);i+=x.byteLength;}return JSON.parse(new TextDecoder().decode(bytes));}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}}
